### ISSUE TITLE
SAML Shibboleth Invalid Response

### ISSUE THREAD

**Issue by witlox** [RocketChat/Rocket.Chat#10005]
### Description:

We are trying to setup SAML in combination with Shibboleth. The certificates have been setup, parameters have been set on the IdP side and on the chat system side. Once the login request is directed back to the chat system, Invalid signature is reported.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0
* Operating System: Ubuntu 16.04.3 LTS
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: enabled
* Node Version: v8.9.3
* mongoDB Version: included

### Steps to Reproduce:

1. create a valid certificate to do SAML requests with your IdP
2. configure the correct parameters for your request with your IdP
3. setup chat SAML parameters according to documentation
4. try to login

### Expected behavior:

actually login to the system using the IdP credentials

### Actual behavior:

Sorry, an annoying error occured
Error: Unable to validate response url: Error: Invalid signature
Close Window

### Relevant logs:

{ provider: '<provider>',     entryPoint: 'https://<idp_url>?providerId=<our_id>&target=<our_id>',     idpSLORedirectURL: '',     issuer: '<our_id>',     cert: 'certificate',     privateCert: 'private',     privateKey: 'key',     callbackUrl: '<our_id>/_saml/validate <provider>',     id: 'id-67azKESpCfoYMaiXL',     protocol: 'https://',     path: '/saml/consume',     identifierFormat: 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress',     authnContext: 'urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport' } ]

<provider> { actionName: 'validate',   serviceName: '<provider>',   credentialToken: undefined } 

{ provider: '<provider>',     entryPoint: '<idp_url>?providerId=<our_id>&target=<our_id>',     idpSLORedirectURL: '',     issuer: '<our_id>',     cert: 'certificate',     privateCert: 'private',     privateKey: 'key',     callbackUrl: '<our_id>/_saml/validate/<provider>',     id: 'id-8u9EFac5eNBaKYaWB',     protocol: 'https://',     path: '/saml/consume',     identifierFormat: 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress',     authnContext: 'urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport' } ] 

<provider> 
RESULT :undefined

**Comment by TwizzyDizzy** [comment]
IIRC, @localguru uses Shibboleth and compiles himself, maybe he has sth. to contribute.

Cheers
Thomas

**Comment by beranPro** [comment]
+1

**Comment by Benderinho** [comment]
Also ran into this issue but could solve it. You have to get the certificates correct. Either on the rocket.chat side, where you need to pay close attention to official documentation https://rocket.chat/docs/administrator-guides/authentication/saml/ , here summarized:

* the first one needs to be without BEGIN CERTIFICATE and END CERTIFICATE lines
* the next two need to include the BEGIN CERTIFICATE/PRIVATE KEY and END CERTIFICATE/PRIVATE KEY lines
* all three should contain no line breaks, except for the BEGIN/END lines (webgui can fool you here, because every '/' is shown as line break)

If you got these correct, make sure the metadata.xml (you placed on the shibboleth server inside the metadata folder and pointed to, in metadata-providers.xml) contains the correct rocket.chat server certificate. You can get the xml on an url like

https://{server_name}/_saml/metadata/{custom_provider_name}

where custom_provider_name is set in the rocket.chat Settings for SAML. If you no longer receive "Invalid signature" errors, you need to configure shibboleth to use 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress' as NameID.

**Comment by pierre-lehnen-rc** [comment]
Closing this as it's quite old and the signature validation has been working well on the current versions.
