### ISSUE TITLE
change  phpmyadmin login password

### ISSUE THREAD

**Issue by rajak68amit** [RocketChat/Rocket.Chat#10075]
Hi Friends,
How i can change php admin password degital ocean

**Comment by JSzaszvari** [comment]
@rocket-cat close 

Hi @rajak68amit 

You will need to contact DigitalOcean support for this as it's not a official component of rocket.chat therefore is not supported by the team. 

Also - As this isn't a bug with rocket.chat I'm closing this issue because we're unable to support third party tools like PHPMyAdmin

**Comment by rajak68amit** [comment]
Hello @rocket-cat

Issues resolved.
