### ISSUE TITLE
Cannot find module '../build/Release/sharp.node'

### ISSUE THREAD

**Issue by dandingol03** [RocketChat/Rocket.Chat#10161]
Hi
   When i use `meteor npm start` command, it throw exception in callback of async function: Error: Cannot find module '../build/Release/sharp.node'.Here is my log:
```
Exception in callback of async function: Error: Cannot find module '../build/Release/sharp.node'
I20180317-01:40:38.539(8)?     at Function.Module._resolveFilename (module.js:538:15)
I20180317-01:40:38.539(8)?     at Function.Module._load (module.js:468:25)
I20180317-01:40:38.539(8)?     at Module.require (module.js:587:17)
I20180317-01:40:38.539(8)?     at require (internal/module.js:11:18)
I20180317-01:40:38.540(8)?     at Object.<anonymous> (/Users/danding/Documents/WebstormProj/Rocket.Chat/node_modules/sharp/lib/constructor.js:10:15)
I20180317-01:40:38.540(8)?     at Module._compile (module.js:643:30)
I20180317-01:40:38.540(8)?     at Object.Module._extensions..js (module.js:654:10)
I20180317-01:40:38.540(8)?     at Module.load (module.js:556:32)
I20180317-01:40:38.540(8)?     at tryModuleLoad (module.js:499:12)
I20180317-01:40:38.540(8)?     at Function.Module._load (module.js:491:3)
I20180317-01:40:38.540(8)?     at Module.require (module.js:587:17)
I20180317-01:40:38.540(8)?     at require (internal/module.js:11:18)
I20180317-01:40:38.540(8)?     at Object.<anonymous> (/Users/danding/Documents/WebstormProj/Rocket.Chat/node_modules/sharp/lib/index.js:3:15)
I20180317-01:40:38.541(8)?     at Module._compile (module.js:643:30)
I20180317-01:40:38.541(8)?     at Object.Module._extensions..js (module.js:654:10)
I20180317-01:40:38.541(8)?     at Module.load (module.js:556:32)
I20180317-01:40:38.541(8)?     at tryModuleLoad (module.js:499:12)
I20180317-01:40:38.541(8)?     at Function.Module._load (module.js:491:3)
I20180317-01:40:38.541(8)?     at Module.require (module.js:587:17)
I20180317-01:40:38.541(8)?     at require (internal/module.js:11:18)
I20180317-01:40:38.541(8)?     at npmRequire (/Users/danding/Documents/WebstormProj/Rocket.Chat/.meteor/local/build/programs/server/npm-require.js:133:10)
I20180317-01:40:38.542(8)?     at Module.useNode (packages/modules-runtime.js:697:18)
I20180317-01:40:38.542(8)?     at fileEvaluate (packages/modules-runtime.js:342:20)
I20180317-01:40:38.542(8)?     at require (packages/modules-runtime.js:238:16)
I20180317-01:40:38.542(8)?     at FileUpload.js (packages/rocketchat:file-upload/server/lib/FileUpload.js:1:351)
I20180317-01:40:38.542(8)?     at fileEvaluate (packages/modules-runtime.js:343:9)
I20180317-01:40:38.542(8)?     at require (packages/modules-runtime.js:238:16)
I20180317-01:40:38.542(8)?     at /Users/danding/Documents/WebstormProj/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_file-upload.js:2061:1
I20180317-01:40:38.542(8)?     at /Users/danding/Documents/WebstormProj/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_file-upload.js:2075:3
I20180317-01:40:38.542(8)?     at /Users/danding/Documents/WebstormProj/Rocket.Chat/.meteor/local/build/programs/server/boot.js:411:36
I20180317-01:40:38.543(8)?     at Array.forEach (<anonymous>)
I20180317-01:40:38.543(8)?     at /Users/danding/Documents/WebstormProj/Rocket.Chat/.meteor/local/build/programs/server/boot.js:220:19
I20180317-01:40:38.543(8)?     at /Users/danding/Documents/WebstormProj/Rocket.Chat/.meteor/local/build/programs/server/boot.js:471:5
I20180317-01:40:38.543(8)?     at Function.run (/Users/danding/Documents/WebstormProj/Rocket.Chat/.meteor/local/build/programs/server/profile.js:510:12)
I20180317-01:40:38.543(8)?     at /Users/danding/Documents/WebstormProj/Rocket.Chat/.meteor/local/build/programs/server/boot.js:470:11
```

**Comment by reetp** [comment]
You have not filled out all the information required for a bug so no one can really help you.

If you had searched for issues relating to the sharp module you may have found this first which may assist:

https://github.com/RocketChat/Rocket.Chat/issues/9943

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @dandingol03 
I am **temporarily** closing this issue as you have not used our [issue template](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/ISSUE_TEMPLATE.md) (the text that is already filled in automatically, when you open a new issue). Please understand, that in order to solve your issue as fast as possible, we need to understand your issue and your setup as good as possible to first reproduce it on our side and then fix it.

Therefore, we kindly ask you to adhere to the issue template and provide us with the information we need. **For that, please edit your inital post rather than replying with the issue template. We will then have a look at your feedback and re-open the issue.**

This benefits all users as we are able to understand and fix issues faster. Thank you for understanding and being kind to us and others :)

Cheers
Thomas

**Comment by leminhtuan2015** [comment]
I have the same problem, Please help me.

### Description:

Get errors:
* Exception in callback of async function: Error: Cannot find module '../build/Release/sharp.node'

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.0-develop
* Operating System: MacBook Pro 10.12.6
* Deployment Method(snap/docker/tar/etc): meteor
* Number of Running Instances: 1
* DB Replicaset Oplog: 0
* Node Version: v9.3.0
* mongoDB Version: v3.4.10

### Steps to Reproduce:

1. Follow: https://rocket.chat/docs/developer-guides/quick-start/
2. git clone https://github.com/RocketChat/Rocket.Chat.git
3. cd Rocket.Chat
4. meteor npm start

### Expected behavior:

successful install

### Actual behavior:

 Exception in callback of async function: Error: Cannot find module '../build/Release/sharp.node'
I20180322-08:34:14.185(7)?     at Function.Module._resolveFilename (module.js:538:15)
I20180322-08:34:14.185(7)?     at Function.Module._load (module.js:468:25)
I20180322-08:34:14.185(7)?     at Module.require (module.js:587:17)
I20180322-08:34:14.186(7)?     at require (internal/module.js:11:18)
I20180322-08:34:14.186(7)?     at Object.<anonymous> (/Users/fuji/Documents/My/Rocket.Chat/node_modules/sharp/lib/constructor.js:10:15)
I20180322-08:34:14.186(7)?     at Module._compile (module.js:643:30)
I20180322-08:34:14.186(7)?     at Object.Module._extensions..js (module.js:654:10)

### Relevant logs:


 Exception in callback of async function: Error: Cannot find module '../build/Release/sharp.node'
I20180322-08:34:14.185(7)?     at Function.Module._resolveFilename (module.js:538:15)
I20180322-08:34:14.185(7)?     at Function.Module._load (module.js:468:25)
I20180322-08:34:14.185(7)?     at Module.require (module.js:587:17)
I20180322-08:34:14.186(7)?     at require (internal/module.js:11:18)
I20180322-08:34:14.186(7)?     at Object.<anonymous> (/Users/fuji/Documents/My/Rocket.Chat/node_modules/sharp/lib/constructor.js:10:15)
I20180322-08:34:14.186(7)?     at Module._compile (module.js:643:30)
I20180322-08:34:14.186(7)?     at Object.Module._extensions..js (module.js:654:10)
I20180322-08:34:14.186(7)?     at Module.load (module.js:556:32)
I20180322-08:34:14.187(7)?     at tryModuleLoad (module.js:499:12)
I20180322-08:34:14.187(7)?     at Function.Module._load (module.js:491:3)
I20180322-08:34:14.187(7)?     at Module.require (module.js:587:17)
I20180322-08:34:14.187(7)?     at require (internal/module.js:11:18)
I20180322-08:34:14.188(7)?     at Object.<anonymous> (/Users/fuji/Documents/My/Rocket.Chat/node_modules/sharp/lib/index.js:3:15)
I20180322-08:34:14.188(7)?     at Module._compile (module.js:643:30)
I20180322-08:34:14.188(7)?     at Object.Module._extensions..js (module.js:654:10)
I20180322-08:34:14.188(7)?     at Module.load (module.js:556:32)
I20180322-08:34:14.189(7)?     at tryModuleLoad (module.js:499:12)
I20180322-08:34:14.189(7)?     at Function.Module._load (module.js:491:3)
I20180322-08:34:14.189(7)?     at Module.require (module.js:587:17)
I20180322-08:34:14.189(7)?     at require (internal/module.js:11:18)
I20180322-08:34:14.190(7)?     at npmRequire (/Users/fuji/Documents/My/Rocket.Chat/.meteor/local/build/programs/server/npm-require.js:133:10)
I20180322-08:34:14.190(7)?     at Module.useNode (packages/modules-runtime.js:697:18)
I20180322-08:34:14.190(7)?     at fileEvaluate (packages/modules-runtime.js:342:20)
I20180322-08:34:14.190(7)?     at require (packages/modules-runtime.js:238:16)
I20180322-08:34:14.190(7)?     at FileUpload.js (packages/rocketchat:file-upload/server/lib/FileUpload.js:1:351)
I20180322-08:34:14.191(7)?     at fileEvaluate (packages/modules-runtime.js:343:9)
I20180322-08:34:14.191(7)?     at require (packages/modules-runtime.js:238:16)
I20180322-08:34:14.191(7)?     at /Users/fuji/Documents/My/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_file-upload.js:2061:1
I20180322-08:34:14.191(7)?     at /Users/fuji/Documents/My/Rocket.Chat/.meteor/local/build/programs/server/packages/rocketchat_file-upload.js:2075:3
I20180322-08:34:14.192(7)?     at /Users/fuji/Documents/My/Rocket.Chat/.meteor/local/build/programs/server/boot.js:411:36
I20180322-08:34:14.192(7)?     at Array.forEach (<anonymous>)
I20180322-08:34:14.192(7)?     at /Users/fuji/Documents/My/Rocket.Chat/.meteor/local/build/programs/server/boot.js:220:19
I20180322-08:34:14.192(7)?     at /Users/fuji/Documents/My/Rocket.Chat/.meteor/local/build/programs/server/boot.js:471:5
I20180322-08:34:14.192(7)?     at Function.run (/Users/fuji/Documents/My/Rocket.Chat/.meteor/local/build/programs/server/profile.js:510:12)
I20180322-08:34:14.193(7)?     at /Users/fuji/Documents/My/Rocket.Chat/.meteor/local/build/programs/server/boot.js:470:11
W20180322-08:34:14.193(7)? (STDERR) Note: you are using a pure-JavaScript implementation of bcrypt.
W20180322-08:34:14.194(7)? (STDERR) While this implementation will work correctly, it is known to be
W20180322-08:34:14.194(7)? (STDERR) approximately three times slower than the native implementation.
W20180322-08:34:14.194(7)? (STDERR) In order to use the native implementation instead, run
W20180322-08:34:14.194(7)? (STDERR) 
W20180322-08:34:14.195(7)? (STDERR)   meteor npm install --save bcrypt
W20180322-08:34:14.195(7)? (STDERR) 
W20180322-08:34:14.195(7)? (STDERR) in the root directory of your application.

**Comment by nikeee** [comment]
Is there any solution for this?

**Comment by localguru** [comment]
@leminhtuan2015 for RC 0.69.2 nodejs v8.11.3 is recommended, so v9.3.0 can't be a recommended version for an older version as you run.

**Comment by xiefangzhenz** [comment]
<code>npm install sharp chai webpack postcss postcss-syntax fibers<code>
I use this code solved the error。

**Comment by miguelmota** [comment]
Getting the same problem on a fresh git clone
