### ISSUE TITLE
Audio and emoji are not displayed to guests

### ISSUE THREAD

**Issue by abdelrahmanahmed** [RocketChat/Rocket.Chat#10177]
### Description:

I am trying to enable Emoji and audio 

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.2
* Operating System: Linux (CentOS)
* Deployment Method(snap/docker/tar/etc):  [Manual: installing on CentOS](https://rocket.chat/docs/installation/manual-installation/centos/) 
* Number of Running Instances: 1
* DB Replicaset Oplog: ?
* Node Version: v8.9.3
* mongoDB Version: ?

### Steps to Reproduce:

1. Open new live chat between a guest and an operator.
2. As the operator, send a emoji in the chat
3. Open livechat box 

### Expected behavior:

Emoji and audio are displayed to guests 

### Actual behavior:

![image](https://user-images.githubusercontent.com/8146379/37662372-9abbdc98-2c5f-11e8-999f-e2a405c51d71.png)

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @abdelrahmanahmed 

we believe that the issue you reported has already been reported by somebody else. Please have a look at #8236 for further information. If you believe we closed your issue in error and your issue is, in fact, not the same as the one mentioned before, feel free to get back to us here and tell us why.

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
@rocket-cat label add duplicate
