### ISSUE TITLE
Allow @ symbol in user name

### ISSUE THREAD

**Issue by subesokun** [RocketChat/Rocket.Chat#10196]
### Description:

Unlucky all of our user names are in the form of `myusername@mycompany.com` which leads to an form validation error in the user profile page. This error prevents the user to change his name, avatar or e-mail address as the `Save changes` button is disabled.

A quick fix would be appreciated as this is a blocker for us.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.2
* Operating System: Official Rocket.Chat Docker container
* Deployment Method(snap/docker/tar/etc): Docker

**Comment by JSzaszvari** [comment]
Just use a different attribute if your using LDAP sync. If it's active directory the use the sAMAccountName attribute and not userPrincipalName 

This would not be too easy as @ is used for mentions. 

I don't know of any directory that allows a @ in the actual username unless it's the email address or full UPN in AD. @ is a delimiter and traditionally can't be part of a username.

**Comment by subesokun** [comment]
Actually we're using Oauth and we're using there the `unique_name` attribute. Sadly there is no other attribute for the user name in our case. Do you know if RC allows to strip/replace the `@` symbol during sync?

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Folks, if it's OK with you, I'd like to direct you to the [community forums](https://forums.rocket.chat/c/community-support) to discuss this, as I see no immediate bug involved here that could be fixed in Rocket.Chat. If you disagree or if in your discussion some different angle comes up that will make this a bug, please get back to me :) Concerning your issue though, I totally with @JSzaszvari's assessment.

Cheers
Thomas
