### ISSUE TITLE
integrations unreachable in Admin Menu

### ISSUE THREAD

**Issue by mc** [RocketChat/Rocket.Chat#10226]
I have given permission for manage-own-integrations (and manage-integrations) to the users group, but the users dont seem to be able to see the context-menu for Administration (the three vertical dots), so while they probably have permissions to manage integrations, they are not able to get to the page to manage the integrations.

### Server Setup Information:

* Version of Rocket.Chat Server: current ubuntu snap

**Comment by mc** [comment]
probably a duplicate of #9865, sorry, didnt find that one earlier.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @mc

I am **temporarily** closing this issue as you have not used our [issue template](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/ISSUE_TEMPLATE.md) (the text that is already filled in automatically, when you open a new issue). Please understand, that in order to solve your issue as fast as possible, we need to understand your issue and your setup as good as possible to first reproduce it on our side and then fix it.

Therefore, we kindly ask you to adhere to the issue template and provide us with the information we need. **For that, please edit your inital post rather than replying with the issue template. We will then have a look at your feedback and re-open the issue.**

This benefits all users as we are able to understand and fix issues faster. Thank you for understanding and being kind to us and others :)

Cheers
Thomas

**Comment by mc** [comment]
I dont see what more there is to understand.  The issue is the same as your emojis issue.  use the PR you already created (the one that is linked to the Issue i referenced) and add 'manage-integrations' and 'manage-own-integrations' to the list of roles that are permitted to the Administration menu - just like you added 'manage-emojis' to the list in the PR.
