### ISSUE TITLE
Message count in statistics is strange

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat#10233]
### Description:

In the admin info panel Rocket.chat displays usage statistics. However, it seems that the message count is not correct.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.1

### Actual behavior:

![usage-count](https://user-images.githubusercontent.com/3596824/37968868-9c1e2f94-31cf-11e8-96f9-e341c4b08f77.png)

=> as you see, the sum of all message is not correct if 

`Total Messages = Total Messages in Channels + Total Messages in Private Groups + Total Messages in Direct Messages + Total Messages in Livechats`

**Comment by kaiiiiiiiii** [comment]
The total message count is different because the calculation of the values is based on two different tables. The best thing would be to sum up the four already calculated values to get the exact total message count. However, I am not sure if the message count stored in the room object is always up to date.

https://github.com/RocketChat/Rocket.Chat/blob/c978136fd4a64e100e764c30714688e4e3fea90a/packages/rocketchat-statistics/server/functions/get.js#L35-L40

I'll submit a PR for that.

**Comment by engelgabriel** [comment]
Ref: https://github.com/RocketChat/Rocket.Chat/issues/10726

**Comment by subham103** [comment]
Previously, the message count for every channel is increased upon message addition but is not updated upon the deletion of a message #12610. Now that I have linked a pr #16650 on this issue we can save/fetch the actual message count of any channel onto/from the database.

So it will be better if we sum up the four values to get the exact total message count.

I want to work on this issue
