### ISSUE TITLE
Full disk usage after RocketChat snap installation.

### ISSUE THREAD

**Issue by isaipanelinha** [RocketChat/Rocket.Chat#10287]
### Description:

After I installed the RocketChat Snap package, on my Digital Ocean Droplet, I received an ISPConfig alert about full disk.
See the print:

Why did not the snap install go to the right location?
What to do?

### Server Setup Information:

* Operating System: Debian 9.4 x64
* Deployment Method(snap/docker/tar/etc): Snap
* Number of Running Instances: 1

![print-log](https://user-images.githubusercontent.com/8020373/38169337-c763460a-353d-11e8-9f59-0a7a0fe771bc.png)

**Comment by isaipanelinha** [comment]
OK! I've read that this is normal as they are read-only files. So I can conclude that there is no problem with the RocketChat snap package. Rocket chat is fantastic, but the only thing I have not been able to do is run on SSL with NGINX. I already followed the official Rocket tutorials, but it did not work out for me. :(

**Comment by Lawri-van-Buel** [comment]
What steps did you take to get ssl working?
What confit did you put in the nginx config file?

Did you read up on ssl and nginx?

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Don't mean to be rude, folks, but since there is no actual bug involved here, I'm closing this... BUT may I refer you, @isaipanelinha, to the community support forum regarding your SSL/NGINX topic: https://forums.rocket.chat/c/community-support

... I'm sure that it's in very good hands over there :)

Cheers & thanks for understanding
Thomas
