### ISSUE TITLE
Feature request: Make e-mail optional for Livechat registration and bots

### ISSUE THREAD

**Issue by tctovsli** [RocketChat/Rocket.Chat#10325]
### Description:
When using the Livechat with "Registration", the user has to enter both name and e-mail. To have an option where you can make e-mail optional would be useful. It isn't a neccessary field, as the guest users (without registration) doesn't have e-mail associated with them.

The same goes for bot users. When creating bot-accounts, a unique e-mail is required for each bot. In many cases, it would be useful for the bots to either just have the same e-mail address or to have no e-mail at all. They don't read their mail anyways!

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @tctovsli 

First off: thank you for takting interest in Rocket.Chat and its improvement. Unfortunately though,I am closing this issue because this is a feature request. The usual procedure for feature requests is as follows:

* feature request is incoming via [the feature requests category in the forums](https://forums.rocket.chat/c/feature-requests)
* feature request is pre-approved by Rocket.Chat team member
* feature request is discussed and refined until it is utterly clear what is to be implemented and what is to be achieved by the feature request. Technical details might be part of this discussion
* feature is approved by Rocket.Chat team member (**or not** - then it will not be done - yet might still be done as a Rocket.Chat App by the community)
* feature request is transferred to github and labelled with "Feature: Planned"

Please understand, that we do not want to clutter Github with wishes and ideas as we have decided to use the forums for that.

When you compose a feature request in the forums, please ask yourself the following questions:

* is my feature request something that benefits everybody or at least a great amount of people
* is my feature request something that is technically possible (only if you have the expertise)
* [... maybe more?...]

Cheers
Thomas
