### ISSUE TITLE
Black in Safari 9 and Chrome 49 after update to 0.63

### ISSUE THREAD

**Issue by mrandrey** [RocketChat/Rocket.Chat#10352]
### Description:

Safari 9 gives a black screen after logging in.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1

### Steps to Reproduce:

1. Open Safari 9.1.2, Chrome 49.0 on Mac, Safari or Chrome 65.0 on iOS 10
2. Go to the Rocket.Chat server and log in.

### Expected behavior:

Populated black bar on the left, main section on the right with content

### Actual behavior:

Unpopulated left menu bar (besides the top) that is covering the entire screen. There appears to be a sliver of white, so I wonder whether something's up with CSS and the content got moved up.

There are no errors, but 14 warnings (see screenshot below).

Also, on Safari on iPad running iOS 10, I get a black screen without the top left toolbar (Chrome + Firefox have the toolbar).

Safari 9.1.2:
<img width="662" alt="screen shot 2018-04-05 at 9 43 05 am" src="https://user-images.githubusercontent.com/444565/38388378-ca7c31ea-38b6-11e8-940a-60f09db5bcdf.png">

Chrome 49:
![chrome](https://user-images.githubusercontent.com/444565/38388562-48ed996a-38b7-11e8-81af-44066a012ad0.jpg)

**Comment by mrandrey** [comment]
Here's a picture where you can see the white line of content near the top a bit better:
<img width="411" alt="screen shot 2018-04-09 at 9 31 54 am" src="https://user-images.githubusercontent.com/444565/38518552-eb921d16-3bd8-11e8-947c-3afdbaf976b5.png">

And here's a picture of it highlighted in Safari inspector:
<img width="606" alt="screen shot 2018-04-09 at 9 35 29 am" src="https://user-images.githubusercontent.com/444565/38518723-6e56c90e-3bd9-11e8-92f6-01ddcec402c4.png">

And here's if I set the div style="height:100vh":
<img width="397" alt="screen shot 2018-04-09 at 9 37 18 am" src="https://user-images.githubusercontent.com/444565/38518806-b277cdf4-3bd9-11e8-8b81-2961ebb2aec5.png">

And here's if I also set aside style="height:100vh":
<img width="297" alt="screen shot 2018-04-09 at 9 38 39 am" src="https://user-images.githubusercontent.com/444565/38518870-d966dbf8-3bd9-11e8-80f8-fdb3b37fd56d.png">


So somehow the CSS height definition isn't older-browser-friendly.

**Comment by mrandrey** [comment]
Confirming that this is still an issue on 0.63.1.

**Comment by mrandrey** [comment]
I think it might have something to do with flex, which isn't supported on many older browsers:

.main-content {
    flex: 1 1 100%;
    width: 1vw;
    height: 100%;

If I take out the "flex" definition, the whole thing collapses, ignoring the height. Perhaps instead of height:100%, height:100vh can be used, since it's pretty well supported? Or something with JS calculating specific height on open/resize?

**Comment by GalvinGao** [comment]
iPad Air 2, iOS 10.3.3, Safari & Chrome both confirmed that the error was occurred.
iPad Air 2, iOS 11.3 Developer Beta 6: **NOT** confirmed and everything was working normally on either Safari and Chrome.
Due to the limitation that apple have, I can't see what had been said in the console.

Here's the screenshots that are in **iOS 10.3.3 Safari**.
The first one is the original screen you entered to the webpage. Notice that there was some contents on the top.
The second one is the screen you can use your finger to scroll down a bit, and you can clearly see the 'while line' on it.

![ad57a49c-673d-4b63-9b38-45a422d13abe](https://user-images.githubusercontent.com/12567059/38599172-ec9e22ee-3d91-11e8-9e64-bf8c7acc34a0.png)
![6156d678-957a-43c9-a488-62727f855684](https://user-images.githubusercontent.com/12567059/38599173-ed15d956-3d91-11e8-9522-bdd71891b799.png)

**Comment by mrandrey** [comment]
@karlprieb I only have Safari 9 installed as a way of testing older browsers, so can't say about Safari 10.

Just for kicks, I tested it on a Windows XP VM in Firefox 7 (way old, I know), and was actually able to send a message after a bit of firebug messing around. It's cool that the functionality is there, even though the CSS is far too advanced for such an old browser and it wasn't really useable.

**Comment by rafaelks** [comment]
I can confirm the Safari crash happens on version 11.1 too (latest stable).
