### ISSUE TITLE
[IMPROVEMENT] Allow access to remote IP in Incoming WebHooks

### ISSUE THREAD

**Issue by cinderblock** [RocketChat/Rocket.Chat#10368]
### Description:

I've been writing some custom WebHooks for various things and I thought it would be helpful to have access to the remote IP address of the requester.

This doesn't seem to be available in the current `request` object:
```
// request.url.hash
// request.url.search
// request.url.query
// request.url.pathname
// request.url.path
// request.url_raw
// request.url_params
// request.headers
// request.user._id
// request.user.name
// request.user.username
// request.content_raw
// request.content
```

This probably means we need a setting to set a certain IP as trusted to add accurate remote IP headers.

**Comment by graywolf336** [comment]
Hey @cinderblock,

First off: thank you for taking interest in Rocket.Chat and its improvement. Unfortunately though, I am closing this issue because this is a feature request. The usual procedure for feature requests is as follows:

* feature request is incoming via [the feature requests category in the forums](https://forums.rocket.chat/c/feature-requests)
* feature request is pre-approved by Rocket.Chat team member
* feature request is discussed and refined until it is utterly clear what is to be implemented and what is to be achieved by the feature request. Technical details might be part of this discussion
* feature is approved by Rocket.Chat team member (**or not** - then it will not be done - yet might still be done as a Rocket.Chat App by the community)
* feature request is transferred to github and labelled with "Feature: Planned"

Please understand, that we do not want to clutter Github with wishes and ideas as we have decided to use the forums for that.

Thanks,
Bradley

**Comment by cinderblock** [comment]
Ooops! I missed that you'd like improvement requests in a different place. My mistake.

Thanks for the awesome software! Cheers!

**Comment by graywolf336** [comment]
No worries! We're slowly changing every place to say we are now using the forums for feature requests.
