### ISSUE TITLE
to send the notification to channel users "/api/v1/channels.notifications " this api not working...

### ISSUE THREAD

**Issue by ArtiMane** [RocketChat/Rocket.Chat#10382]
### Server Setup Information:

* Version of Rocket.Chat Server: 
* Operating System: 
* Deployment Method(snap/docker/tar/etc): 
* Number of Running Instances: 
* DB Replicaset Oplog: 
* Node Version: 
* mongoDB Version: 

### Steps to Reproduce:

1. 
2. 
3.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @ArtiMane 

I am **temporarily** closing this issue as you have not used our [issue template](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/ISSUE_TEMPLATE.md) (the text that is already filled in automatically, when you open a new issue). Please understand, that in order to solve your issue as fast as possible, we need to understand your issue and your setup as good as possible to first reproduce it on our side and then fix it.

Therefore, we kindly ask you to adhere to the issue template and provide us with the information we need. **For that, please edit your inital post rather than replying with the issue template. We will then have a look at your feedback and re-open the issue.**

This benefits all users as we are able to understand and fix issues faster. Thank you for understanding and being kind to us and others :)

Cheers
Thomas
