### ISSUE TITLE
Confusing information while testing

### ISSUE THREAD

**Issue by a5his** [RocketChat/Rocket.Chat#10417]
While doing security testing, we were shown error message which includes some information regarding application(my guess). I have a concern as I am not sure about those information which is from `kadira` app monitoring tool. I need some help to understand what kind of information are they. 

Capistrano is used to deploy the app.

**File**
`https://myappdomainlocation/releases/20180201105052/bundle/programs/server/npm/node_modules/meteor/simple_json-routes/node_modules/connect/node_modules/body-parser/node_modules/raw-body/index.js:262:16`

**Information disclosed**
`
"ROOT_URL":"https://myappdomain.com","ROOT_URL_PATH_PREFIX":"","appId":"appid","kadira":{"appId":"9iRHAGEsQtP4Ti5Ja","endpoint":"https://enginex.kadira.io","clientEngineSyncDelay":10000,"enableErrorTracking":true},"accountsConfigCalled":true,"autoupdateVersion":"df64abf78405476a30c0c9f3bbafa72709a10e77","autoupdateVersionRefreshable":"0a2409ae894506bf0fd1ab7997e0f20434708a54","autoupdateVersionCordova":"111cd98c48d5637efc999e93bf659c579d717e13"}
`

Can you explain more on above information? Who they belong to - application or kadira? 
Is there any risk disclosing above information publicly?

Thanks in advance.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @a5his 

I am closing this issue because we think there is no actual bug in Rocket.Chat in what you're describing.

We use Github mainly for discussing bugs though. We understand, that setting up and operating a Rocket.Chat server is not trivial, yet we do not have the woman/man-power to help everybody. That is unfortunate, but simply a limitation of time. If it should turn out from your feedback to this message, that there is a bug involved, we will try to fix it with you.

That being said, we are very thankful that our community also does a great job in helping each other. I would therefore like to point you to some places where you can try asking for help. Usually, some friendly human being has time for you and your issue:

* **The Rocket.Chat Community Support Channel**:
https://open.rocket.chat/channel/support (for general support)
* **The Rocket.Chat Community Dev Channel**:
https://open.rocket.chat/channel/dev (for development-focussed support)
* **The Rocket.Chat Community Support Forum**:
https://forums.rocket.chat/c/community-support

If you don't find a solution to your problem there, don't fret, as we also offer paid support: https://rocket.chat/support

You could, of course, spare yourself the hassle entirely and just choose the hosted version, where we provide you with a running Rocket.Chat instance: https://rocket.chat/cloud

Cheers
Thomas
