### ISSUE TITLE
Channel search box ignores any text right of cursor

### ISSUE THREAD

**Issue by Unispezi** [RocketChat/Rocket.Chat#10479]
### Description:

When searching for channels using the search feature (^+K), any text to the right of the cursor seems to be ignored.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.2
* Version of Rocket Chat Client: Rocket.Chat+Version 2.10.5, seen in native client as well as in the web client running in Chrome 65.0.3325.181 (Official) (64-Bit)
* Operating System (client): Windows 10
* Deployment Method(snap/docker/tar/etc): Unknown
* Number of Running Instances: Unknown
* DB Replicaset Oplog: Unknown
* Node Version: Unknown
* mongoDB Version: Unknown

### Steps to Reproduce:

To reproduce:
1. Type "ey123456" into the search box -> no results are found
2. Press Cursor Left until cursor is between the e and the y -> suddenly results appear (any channel containing an e)

### Expected behavior:

Only channels containing "ey123456" should be found if the search box contains "ey123456" 

### Actual behavior:

Search results appear: any channel containing an e

**Comment by tehwalris** [comment]
Surprisingly this is done on purpose [here](https://github.com/RocketChat/Rocket.Chat/blob/3ebe15d97b11acfb93505b99ea699db9bc216b26/packages/rocketchat-ui-message/client/popup/messagePopup.js#L153). It seems like a very confusing choice and should probably be considered a bug.

Changing lines 153 and 175 to `const value = template.input.value;` should fix it. Feel free to make a PR.

**Comment by tehwalris** [comment]
Actually looking at it again, it seems like around 50-70% of the code in `messagePopup.js` is totally unused. The only code which consumes it is [this](https://github.com/RocketChat/Rocket.Chat/blob/725d3e00d0cabd0987f967f257f59070c6cc9166/packages/rocketchat-ui-sidenav/client/toolbar.js) from [here](https://github.com/RocketChat/Rocket.Chat/blob/41bffeadbc6dd6eaa1c3b486442b1232670bb477/packages/rocketchat-ui-sidenav/client/toolbar.html#L21). Options like `textFilter`, `trigger`, `prefix`, `suffix`, `selectorRegex` and `replaceRegex` seem to be related to eachother. They are all unused (set to noop-looking defaults) and make up most of the complexity in this code.

It seems like this was some kind of tab expansion feature, so typing `bob stuff` with the cursor after `bob` and pressing tab could expand to (`robert more`) with the appropriate `getValue` function (maps `bob` to `robert`).  That's the core of it, but as far as I can tell, the other options (like `selectorRegex`) all adjust details of this.

Since this is all very hard to understand and unused, the best approach may be to just remove all tab-completion related code. I don't work on RocketChat though, so I don't know what they want. I doubt this issue will be addressed any time soon, unless somebody submits a PR removing all this though.

**Comment by MartinSchoeler** [comment]
Hey I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
