### ISSUE TITLE
Error: read Econnreset

### ISSUE THREAD

**Issue by ChrisEHOliver** [RocketChat/Rocket.Chat#10516]
### Server Setup Information:

* Version of Rocket.Chat Server: 63.3
* Operating System: Centos 7
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: 
* mongoDB Version: 
Rocket.Chat
Version	0.63.3
Database Migration	109
Installed at	Thu Apr 19 2018 12:50:37 GMT-0400 (Eastern Daylight Time)
Uptime	1 hours, 59 minutes, 40 seconds
Running Instances	1
OpLog	Disabled
Hash	cbc951cead1efb17834fc481190cacfddbf061c8
Date	Wed Apr 18 23:57:59 2018 -0500
Branch	HEAD
Tag	0.63.3
Author	Bradley Hilton
Subject	Merge pull request #10504 from RocketChat/release-0.63.3
Runtime Environment
OS Type	Linux
OS Platform	linux
OS Arch	x64
OS Release	3.10.0-693.21.1.el7.x86_64
Node Version	v8.9.3
OS Uptime	6 hours, 28 minutes, 12 seconds
OS Load Average	0.12, 0.27, 0.29
OS Total Memory	3.61 GB
OS Free Memory	251.59 MB
OS CPU Count	2
Build Environment
OS Platform	linux
OS Arch	x64
OS Release	4.4.0-119-generic
Node Version	v8.11.1
Date	April 19, 2018 1:18 AM

### Steps to Reproduce:
Error:  [34mI20180419-14:19:17.655(-5) rocketchat_logger rocketchat_logger.js:278 [31mLDAP ➔ Connection.error connection { Error: read ECONNRESET     at _errnoException (util.js:1024:11)     at TCP.onread (net.js:615:25)  code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } 
[34mI20180419-14:20:47.701(-5) rocketchat_logger rocketchat_logger.js:278 [31mLDAP ➔ Connection.error connection { Error: read ECONNRESET     at _errnoException (util.js:1024:11)     at TCP.onread (net.js:615:25)  code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } 
[34mI20180419-14:21:17.716(-5) rocketchat_logger rocketchat_logger.js:278 [31mLDAP ➔ Connection.error connection { Error: read ECONNRESET     at _errnoException (util.js:1024:11)     at TCP.onread (net.js:615:25)  code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } 

After setting up Ldap authentication, errors appear in Log file

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @ChrisEHOliver 

I am closing this issue because we think there is no actual bug in Rocket.Chat in what you're describing. Here's why:

* `ECONNRESET` indicates that there is something wrong on (or on the network-layer to) your LDAP-Server

We use Github mainly for discussing bugs though. We understand, that setting up and operating a Rocket.Chat server is not trivial, yet we do not have the woman/man-power to help everybody. That is unfortunate, but simply a limitation of time. If it should turn out from your feedback to this message, that there is a bug involved, we will try to fix it with you.

That being said, we are very thankful that our community also does a great job in helping each other. I would therefore like to point you to some places where you can try asking for help. Usually, some friendly human being has time for you and your issue:

* **The Rocket.Chat Community Support Channel**:
https://open.rocket.chat/channel/support (for general support)
* **The Rocket.Chat Community Dev Channel**:
https://open.rocket.chat/channel/dev (for development-focussed support)
* **The Rocket.Chat Community Support Forum**:
https://forums.rocket.chat/c/community-support

If you don't find a solution to your problem there, don't fret, as we also offer paid support: https://rocket.chat/support

You could, of course, spare yourself the hassle entirely and just choose the hosted version, where we provide you with a running Rocket.Chat instance: https://rocket.chat/cloud

Cheers
Thomas
