### ISSUE TITLE
Cannot properly Search and start chats

### ISSUE THREAD

**Issue by adamkwilliams** [RocketChat/Rocket.Chat#10577]
I have provided a link to the video which shows what I am talking about. It is difficult to search and start a chat with someone. I reset app data and it's still not working. This happens on both PC and MAC, as well as App based and Web based.

https://drive.google.com/file/d/1K4NvRgw2PHhOwTPSG3OGNmXSpvkSLQqf/view?usp=sharing

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Thanks for your video, but please adhere to the [issue template](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/ISSUE_TEMPLATE.md) and give us all the information we need. Otherwise we cannot help you.

Since I've watched your video it might also be a good idea to tell us about which browser (and what version) you're using and whether you have any Custom CSS rules applied to your Rocket.Chat instance.

I'm going to reopen this issue once you have provided all information

Cheers
Thomas
