### ISSUE TITLE
Chrome enable notification

### ISSUE THREAD

**Issue by exagon** [RocketChat/Rocket.Chat#10572]
Hi, i've a problem with notifications.

On my account I see : 
![image](https://user-images.githubusercontent.com/2110701/39189675-14a88a54-47d3-11e8-84a1-9a7f88119595.png)

but when I go on site setting I see : 

![image](https://user-images.githubusercontent.com/2110701/39189831-814449c8-47d3-11e8-9739-6c4856f2a2a2.png)

the notification ara blocked ? How I can enable ? The chat is not configure to use https.

Thanks in advance
regards

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this since it is no bug in Rocket.Chat. That being said: indeed it seems to be the case, that Chrome/Chromium does disable some functions if your site is not requested via HTTPS (which - to me - totally makes sense as it's a pretty heavy attack vector). Notifications seem to be one of those functions. Looks like you gonna have to enable SSL.

Cheers
Thomas
