### ISSUE TITLE
Support of upload office documents in chat room

### ISSUE THREAD

**Issue by steedos** [RocketChat/Rocket.Chat#1058]
Currently, only images are valid to upload. and there is a bug, if i drag a file to the window, it will ignore the file extension check.

Also, it's need the admin settings for documents size limit.

**Comment by graywolf336** [comment]
There's already an issue for setting of max upload file size: #756.

**Comment by gmsecrieru** [comment]
- [ ] Create Admin setting to define allowed [media types](http://www.iana.org/assignments/media-types/media-types.xhtml)
- [ ] Change form validation to reflect newly-added setting
- [ ] Inspect/fix drag-and-drop upload

**Comment by IQ2022** [comment]
Go for it, we have an issue with anyone dropping a file into chat, it hang chat and you might actually lose connection to room.

**Comment by gmsecrieru** [comment]
It turns out the drag-and-drop validation is related to an existing bug on `jalik:ufs`. I have created a PR to fix that (jalik/jalik-ufs#19), hopefully it gets accepted soon and we can leverage this fix.

I will put this on hold while we wait for a reply from the package maintainer. Otherwise we can add my forked version to our `packages`.

**Comment by jalik** [comment]
@gmsecrieru, thanks for the PR, I've accepted it and published new version of UFS packages (now also include the MIT LICENSE I forgot to add). I'm glad to see my work used and fixed by others ;-)

**Comment by gmsecrieru** [comment]
@jalik :+1: thanks for accepting it and thank you as well for your work!
