### ISSUE TITLE
RocketChat iOS App can't connect to Server running on Plesk

### ISSUE THREAD

**Issue by ejschenck** [RocketChat/Rocket.Chat#10618]
### Description:

This may be a repeat of #6465 but when I try to connect the iOS app to our server (running on Docker in Plesk) it says it can't connect.  When I follow the instructions for the nginix directives in the KB:  https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy/ it ends up making the app work but breaking the web version of Rocket Chat.

The only way to get the web version back was to flip on the docker proxy to the rocketchat instance, but that then disconnected the iOS app.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.0
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): Docker
* Number of Running Instances: 1
* Node Version: 8.9.3

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @ejschenck 

I am closing this issue because we think there is no actual bug in Rocket.Chat in what you're describing. Here's why:

* [FREE TEXT]

We use Github mainly for discussing bugs though. We understand, that setting up and operating a Rocket.Chat server is not trivial, yet we do not have the woman/man-power to help everybody. That is unfortunate, but simply a limitation of time. If it should turn out from your feedback to this message, that there is a bug involved, we will try to fix it with you.

That being said, we are very thankful that our community also does a great job in helping each other. I would therefore like to point you to some places where you can try asking for help. Usually, some friendly human being has time for you and your issue:

* **The Rocket.Chat Community Support Channel**:
https://open.rocket.chat/channel/support (for general support)
* **The Rocket.Chat Community Dev Channel**:
https://open.rocket.chat/channel/dev (for development-focussed support)
* **The Rocket.Chat Community Support Forum**:
https://forums.rocket.chat/c/community-support

If you don't find a solution to your problem there, don't fret, as we also offer paid support: https://rocket.chat/support

You could, of course, spare yourself the hassle entirely and just choose the hosted version, where we provide you with a running Rocket.Chat instance: https://rocket.chat/cloud

Cheers
Thomas
