### ISSUE TITLE
Creating multiple instances in Rocket Chat

### ISSUE THREAD

**Issue by lakhandewnani** [RocketChat/Rocket.Chat#10622]
Requirement :- 
We have an app build in Ios/Android which is meant for patient recovery process in which his entire recovery process is being analysed for a particular hospital. A single patient can be admitted to multiple hospitals too. This site contains multiple site feature i.e. we have different back-end databases setup for different hospitals available.

We want to implement Rocket Chat in our app using its API's available.I have downloaded the code for Rocket Chat from GitHub and its working fine . Currently we are facing several issues as below  :- 

1) Can we have multiple instances of Rocket Chat for our multiple site feature  - We are planning to have multiple Rocket Chat instances having multiple Mongo Db's on back-end for each hospital type. But I am unable to start over this requirement as this feature is not mentioned in documentation part . Can someone help me over this issue  or confirm if this is possible using Rocket Chat ?
 
2) Using Rocket Chat E2E Encryption feature - I read the articles for E2E Encryption and found the code in Encryption branch available in GitHub. I need to confirm here that if currently the API's for E2E encryption are available to be utilised in my app ?

Please let me know your opinion over these issues asap.

**Comment by lakhandewnani** [comment]
@rafaelks  :- Can you please help me over this issue

**Comment by rafaelks** [comment]
@lakhandewnani I'm not aware of the usage of Mongo DB in the application, but I can help you with questions regarding the mobile apps if you need to. Are you developing native apps?

**Comment by lakhandewnani** [comment]
@rafaelks  - Thanks for your response. The app is already built for us . We are just in-process of integrating Rocket Chat application in your app . Can you please assign this issue to someone who could help me over this issue.

**Comment by lakhandewnani** [comment]
@mrinaldhar  - Can you help me over this issue ?

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @lakhandewnani 

I am closing this issue because we think there is no actual bug in Rocket.Chat in what you're describing.

We use Github mainly for discussing bugs though. We understand, that setting up and operating a Rocket.Chat server is not trivial, yet we do not have the woman/man-power to help everybody. That is unfortunate, but simply a limitation of time. If it should turn out from your feedback to this message, that there is a bug involved, we will try to fix it with you.

That being said, we are very thankful that our community also does a great job in helping each other. I would therefore like to point you to some places where you can try asking for help. Usually, some friendly human being has time for you and your issue:

* **The Rocket.Chat Community Support Channel**:
https://open.rocket.chat/channel/support (for general support)
* **The Rocket.Chat Community Dev Channel**:
https://open.rocket.chat/channel/dev (for development-focussed support)
* **The Rocket.Chat Community Support Forum**:
https://forums.rocket.chat/c/community-support

If you don't find a solution to your problem there, don't fret, as we also offer paid support: https://rocket.chat/support

You could, of course, spare yourself the hassle entirely and just choose the hosted version, where we provide you with a running Rocket.Chat instance: https://rocket.chat/cloud

Cheers
Thomas
