### ISSUE TITLE
No admin user after activating ldap

### ISSUE THREAD

**Issue by Tharnas** [RocketChat/Rocket.Chat#1066]
Hi, 

After ldap is enabled and the (local) admin logs out there is no way to log in again with administrator privileges. (as local users are disabled when ldap is activated)

The local admin probably would need to grant the admin role to an ldap user before he logs out but if he doesn't I think the only way is to grant it through database.

**Comment by ninja-** [comment]
:+1:

**Comment by Theaxiom** [comment]
+1

**Comment by emcguinness** [comment]
Some kind of hard to ignore warning before you enable the feature would be good. One that contains instructions, or links to some, would definately help. A good starting point could be a warning at the top of the LDAP wiki page, with how to fix it if you screw up would be a good start.

**Comment by geekgonecrazy** [comment]
Absolutely or at the very least always allow initial admin to login unless the account is deleted (which only an admin could do)

**Comment by hameno** [comment]
So, how do I change a user to be admin when this happened? I'm the docker image...

**Comment by Dbzman** [comment]
@hameno 
If you're locked out you can change your user to be an admin in mongo db directly.

**Comment by hameno** [comment]
Yeah, figured that out. Wasn't easy or documented though, the wiki article is also outdated, as it shows an "admin" field while I had to change the roles.

**Comment by gmsecrieru** [comment]
Thanks for pointing that out, @hameno . Could you please update the mentioned wiki article in order to reflect up-to-date, reproducible steps?

**Comment by saigop** [comment]
While following the above step, while executing meteor, its building application and stopping at,
Errors prevented startup:

   While processing files with templating (for target web.browser):
   bundle/programs/web.browser/app/fonts/fontello.html:1: Expected one of: <body>, <head>, <template>
   bundle/programs/web.cordova/app/fonts/fontello.html:1: Expected one of: <body>, <head>, <template>

   While processing files with templating (for target web.cordova):
   bundle/programs/web.browser/app/fonts/fontello.html:1: Expected one of: <body>, <head>, <template>
   bundle/programs/web.cordova/app/fonts/fontello.html:1: Expected one of: <body>, <head>, <template>

even though if i change the file and add the DOCTYPE still it stuck here, and am not able to disable LDAP. Because of this not able to edit any admin settings.

**Comment by saigop** [comment]
Hi,

Somehow i fixed this. From the mongo command line, I disabled the ldap "db.rocketchat_settings.update( { _id: "LDAP_Enable"}, { $set: {value: false} } )"

And logged into the general authentication, post gave ADMIN rights to one of the LDAP user, finally again activated LDAP settings from the web console. 

:)

**Comment by geekgonecrazy** [comment]
Maybe we can add support for an environment variable? Something like DISABLE_LDAP=true or DEBUG_LDAP=true that would enable the site admin still.

**Comment by saigop** [comment]
Yes, that would be nice, And the second time, have done something like this, in the chrome browser I have created the first admin user and left intact as logged in. In parallel i activated the LDAP.

And from the windows client, I logged as LDAP user, and went back to the browser where first logged in, there i marked the LDAP user as admin. So now without going to mongodb I did something like this. 

It will be useful for some one viewing this. 

Thanks.

**Comment by rwakida** [comment]
Does Meteor support multiple authentication schemes?  i.e. check LDAP first then check local.

**Comment by geekgonecrazy** [comment]
@rwakida That's a great question... If not this maybe an improvement / hack worth looking into.

**Comment by engelgabriel** [comment]
Fixed, now LDAP logins will fall back to regular password accounts when no user is found.

**Comment by rikmendes** [comment]
Fix for when using Cloudron (but the mongodb commands should work for any instance of Rocket.chat I guess : 

https://git.cloudron.io/cloudron/rocketchat-app/issues/1#note_3432
