### ISSUE TITLE
Is there any way to know whether a message is delivered or not?

### ISSUE THREAD

**Issue by mrqbmrqb** [RocketChat/Rocket.Chat#10682]
I know that "read receipts" is useful to check the "read" status of the message, but I want to know when the message is delivered especially in direct messages.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hey @mrqbmrqb 

this is no bug, that's why I'm closing your issue. Concerning your question: currently (I think) this is handled by the client. The web-client, for example, greys out your message until it has been successfully delivered to the server. For further questions, please refer to the forums: http://forums.rocket.chat :)

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
Mhhhh I see. But I'm currently not quite sure, whether there is a technical way to do this. I think currently, indeed, what comes closest to what you mean is the "read" thing. I see your point, that this is technically not the same as "has been delivered" ... not sure where to go from there...

Cheers
Thomas

**Comment by mrqbmrqb** [comment]
So @TwizzyDizzy  should I request a new feature for this issue?

Mohanad

**Comment by mrqbmrqb** [comment]
But just to be clear, what I mean with "delivered" is like "Whatsapp" when grey double check is showed next to the message, indicating that the other user received the message

**Comment by graywolf336** [comment]
Then yes, we have that via the read receipt.

**Comment by mrqbmrqb** [comment]
Excuse me @graywolf336 but as I understood from #9717 issue, read receipt indicates when the user "read" the message not "receive" it. 

If this thing is already included in read receipt could you please help me with that, how to know when the other user in direct chat received my message depending on read receipt.
