### ISSUE TITLE
Uploaded file URL

### ISSUE THREAD

**Issue by tomac** [RocketChat/Rocket.Chat#1076]
Hello,
I've managed to have RocketChat working nginx and SSL but when I upload a new file, the download URL is pointing to the meteor app (http://rocketchat:3000/ufs/...) instead of the SSL port in nginx. Is there any option I should configure?

Thanks

**Comment by emcguinness** [comment]
This is set by the following environment variable:

`ROOT_URL=https://$HOST`

with the address being the https://address you use to access the server. One thing to be aware of, and this could of changed since I last looked, but the URL was getting saved on upload. So old files uploaded with the root url set wrong will still be wrong but newly uploaded files should be correct.

**Comment by tomac** [comment]
Thanks, my fault, I have the meteor URL in the ROOT_URL variable instead of the https nginx one.
