### ISSUE TITLE
[INVESTIGATE] Android 7.x Users Unable to Use Rocket.Chat App

### ISSUE THREAD

**Issue by rneef183** [RocketChat/Rocket.Chat#10953]
### Description:

Our company recently updated its on-prem installation of Rocket.Chat to 0.64.1. Users were instructed to download and install the latest version of the Rocket Chat app (version 2.2.0) for Android and iOS. However, upon doing so and entering the URL, the message “An error has occurred while checking your server version, please try again” is pushed for mobile users with Android 7.x. Using the experimental app yields the message “[chat server URL] is not a valid Rocket Chat instance.” This does not appear to be an issue with Android 8.x users.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.1
* Operating System: CentOS 7
* Deployment Method(snap/docker/tar/etc): Manual installation
* Number of Running Instances: 4
* DB Replicaset Oplog: Enabled
* Node Version: 8.9.3
* mongoDB Version: 2.6.12

### Steps to Reproduce:

1. The user installs the latest version of Rocket.Chat or Rocket.Chat Experimental for Android via the Play Store.
2. The user enters our company's URL.
3. The user is given an error.

### Expected behavior:

The app loads the service as normal and downloads all relevant files.

### Actual behavior:

The message "An error has occurred while checking your server version, please try again" when using the standard Rocket.Chat app.

With Experimental, "not a valid Rocket.Chat instance" is shown instead.

### Relevant logs:

No relevant logs to my knowledge, but logs are available on request.

**Comment by graywolf336** [comment]
@rafaelks this is for the native mobile apps

**Comment by rafaelks** [comment]
@rneef183 The Android Native application works with Android 5.0+. Can you provide me the URL of your server please?

**Comment by rneef183** [comment]
Sure, our server URL is https://chat.stratacache.com

Also, to clarify, we have 4 running instances as opposed to 1, my mistake. I've edited to reflect such.

**Comment by luciofm** [comment]
@rneef183 this issue is due to a problem with the Intermediate Certificates for your backend
![screen shot 2018-06-01 at 10 10 53 am](https://user-images.githubusercontent.com/224255/40842449-4e091f4c-6584-11e8-90a5-32c5eb00c6ba.png)

Please refer to http://nginx.org/en/docs/http/configuring_https_servers.html#chains
https://www.godaddy.com/help/nginx-install-a-certificate-6722
http://mikegrouchy.com/blog/2010/12/setting-up-ssl-with-nginx-and-godaddy.html

**Comment by graywolf336** [comment]
Closing due to the above comment.

**Comment by sewebster87** [comment]
Hi,

I manage this server and am wondering if you have more information about the intermediate cert not being trusted?  What tool did you use to find that the SSL was not trusted?

I ran the site through Qualys and HTBridge's SSL tools and both report the site is A+ and PCI DSS compliant, so it seems they are missing something that this tool you are using was able to pull up.

If you can let me know so I can do my own testing to try and fix this that'd be great.  I will probably start with re-issuing the cert since it was dragged from another server as this was recently rebuilt.

Thanks for your help, and sorry this appears to be a simple SSL issue.

**Comment by luciofm** [comment]
Hi @sewebster87,

I used https://www.sslchecker.com/sslchecker to test the certificate.

The strange thing is that using other tools, they say the certificate is OK.

Can I send you a test/debug app, to gather more information on the connection failure?

**Comment by sewebster87** [comment]
Hi @luciofm ,

That would be great.  I just got a new LG G7 w/ Android 8.0 and am able to successfully connect to chat.stratacache.com, but not to my personal server chat.odinweb.co - same error "Error while checking server version".  

The crazy thing is that this works just fine on chat.stratacache.com.  I am starting to feel like this is something I am doing wrong, however there is inconsistent behavior across these 2 servers and the are the same version.  Chat.stratacache.com uses a GoDaddy cert, while Chat.odinweb.co uses a LetsEncrypt cert.

Is there a paid subscription for rocket.chat support?  We love the product, but having support for it would be even better for issue like this as our Galaxy S6/S7 users are all locked out. I'd be willing to subscribe to a support system if there is one.

**Comment by luciofm** [comment]
@sewebster87 the sales people will enter in contact... Meanwhile, I'll bake a special version of the app for gathering more information of this problem. I'll try to have it for tomorrow, or Friday.
