### ISSUE TITLE
Login issue in rocketchat

### ISSUE THREAD

**Issue by ramjiplay** [RocketChat/Rocket.Chat#10972]
### Server Setup Information:

* Version of Rocket.Chat Server: 0.63
* Operating System: ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): Manual installation
* Number of Running Instances: 1
* DB Replicaset Oplog: no
* Node Version: v8.9.3
* mongoDB Version: db version v3.2.19

### Steps to Reproduce:

1. 
2. 
3. 

### Actual behavior:

 Hi,
I have configured rocket.chat with above configurations. After increasing number of users to 1000, rocketchat application only works when users were already login. If a new user trying to login into rocket.chat, It is showing loading symbol or login button changed to please wait. I used PM2 to alive the application. For login , I have used LDAP.  I have also checked logs. I am unable to find the problem. Any solution for this problem?

RAM: 4 GB
CPU cores: 2

Thank you.

**Comment by robertwessen** [comment]
not a dev, but this sounds normal for RC default out of box settings.

Administration>LDAP>User Settings

What is your Search Size Limit set to?

**Comment by MartinSchoeler** [comment]
@ramjiplay Hey, looks like you seem to be looking for support. You will have a better chance of getting help if you go to one of the places listed in [here](https://rocket.chat/docs/getting-support/#community-support) since github is not the best place to ask for support, as we keep it for bugs and feature requests. For now i will be closing this issue, as it does not fit our issue guidelines. Thanks!
