### ISSUE TITLE
Refused to display 'https://myfqdn/livechat' in a frame because it set 'X-Frame-Options' to 'deny'.

### ISSUE THREAD

**Issue by possebon** [RocketChat/Rocket.Chat#10977]
### Description:

I'm trying to use the LiveChat in my web application (OTRS) and the widget is not displayed. When I take a look on the Chrome Dev Tools console, I'm getting this error message:

Refused to display 'https://mydomain.com/livechat' in a frame because it set 'X-Frame-Options' to 'deny'.

The Rocket.Chat is installed on a different server of OTRS. I'm using HTTPS and this is configured in a nginx reverse proxy.

If I use only the Rocket.Chat via web interface or via Desktop App, it works fine.

I already changed the configuration on LiveChat to allow my domain, and did not work. I leave it empty, did not work either.

I saw some information on Google regarding a configuration on nginx, using the option 
`proxy_hide_header X-Frame-Options;` 

I put this setting on Rocket.Chat nginx config file (reverse proxy).

### Server Setup Information:

* Version of Rocket.Chat Server: 0.65.1
* Operating System: CentOS Linux release 7.5.1804
* Deployment Method(snap/docker/tar/etc): downloading using the curl command from documentation
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* Node Version: v8.9.3
* mongoDB Version: v2.6.12

### Steps to Reproduce:

1. Does not work on any other web application. I tried even on a Wordpress site, using the Rocket.Chat LiveChat plugin, and the error is the same.

### Expected behavior:

Widget of LiveChat work.

### Actual behavior:

Does not work on any other web application. I tried even on a Wordpress site, using the Rocket.Chat LiveChat plugin, and the error is the same.

Refused to display 'https://mydomain.com.br/livechat' in a frame because it set 'X-Frame-Options' to 'deny'.

**Comment by geekgonecrazy** [comment]
I believe you have to actually add the domain in the livechat settings

**Comment by possebon** [comment]
I already did that, without success.

**Comment by geekgonecrazy** [comment]
@renatobecker any ideas on this?  Is this a bug or a configuration thing?

**Comment by renatobecker** [comment]
Hi @possebon and @geekgonecrazy.

What you have reported is a quite strange behaviour. The `'X-FRAME-OPTIONS', 'DENY'` is only applied in Livechat side if there is at least one entry in `Livechat Allowed Domains` and the `Livechat URL host` is not found in that list.
But in this case, you wouldn't get the error you mentioned because a `404` error would be generated.
When there is not even one entry in the `Livechat Allowed Domains`, the follow `HTTP response header` will be set(using your domain sample):

`X-FRAME-OPTIONS: ALLOW-FROM https://myfqdn`

So, I think there is some setting in your nginx that is not allowing Livechat to be reached.
I would like to help you in this case, so let me know if you need any other information from Rocket.Chat/Livechat environment.


There is an old issue very similar to your case, if you are interested to see how it was resolved, please take a look here: https://github.com/RocketChat/Rocket.Chat/issues/8517

I'll be waiting for you feedback.
Thanks.

**Comment by possebon** [comment]
Hi @renatobecker 

I already saw that #8517 and tried without success. Anyway I double checked again and I identified that when I copied my ssl config of nginx there was a specific line

`add_header X-Frame-Options DENY;`

Of course that after removing this line, LiveChat started to working.

Sorry @renatobecker and @geekgonecrazy and thanks to point me to the right direction.

**Comment by ggruber4711** [comment]
I am having a similar problem, I am getting
Refused to display 'https://chat.workflow.at/livechat' in a frame because it set multiple 'X-Frame-Options' headers with conflicting values ('SAMEORIGIN, ALLOW-FROM https://personalwolke.at'). Falling back to 'deny'.

This is really strange, as it has worked 1 week ago on our 2 production websites and now it stopped working in all browsers.

**Comment by izaacmenezes** [comment]
Já vi aquele # 8517 e tentei sem sucesso. De qualquer forma, verifiquei novamente e identifiquei que quando copiei minha configuração SSL do nginx havia uma linha específica

add_header X-Frame-Options DENY; 

@possebon 
Qual caminho voce encontrou o arquivo do ssl pra apagar essa linha?
