### ISSUE TITLE
[REGRESSION] Mobile apps depending on settings again to show the OAuth options

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#11064]
### Description:

After this PR https://github.com/RocketChat/Rocket.Chat/pull/10724, the WordPress authorization option differs based in a setting of the server. This information needs to come on the OAuth services API. The client should not need both Settings + OAuth APIs to present the OAuth options.

On mobile, we're forcing the WordPress to use this URL to authorize the user:

> https://public-api.wordpress.com/oauth2/authorize

We've two options: 

1. Return the correct authorization URL to the API;
2. Return some information on the API that allow us to choose between different URLs in the clients;

**Comment by geekgonecrazy** [comment]
Can we maybe switch all oauth to use the exact same custom oauth?  This way when the mobile teams call the api they will get all values needed and not have to depend on settings for some and the api for others?

I think this is going to be extremely important, especially since in the future we might be moving to adding in oauth providers via Rocket.Chat Apps.
