### ISSUE TITLE
Display Rocket Chat Version Number

### ISSUE THREAD

**Issue by MuhClaren** [RocketChat/Rocket.Chat#1111]
Are there any plans to introduce a version number somewhere in the UI? It'd be greatly helpful to have at-a-glance the current version running. Takes the guess work out of wondering if it's the latest docker image or not. Thanks for considering this.

**Comment by storrgie** [comment]
It'd be very nice to know version-build as I re-deploy via docker. I have noticed several things I'd like to have reported as issues, but I can't attribute them to a specific build without slogging through the docker build IDs.

**Comment by gmsecrieru** [comment]
This should be possible with the efforts related to #961.

**Comment by geekgonecrazy** [comment]
@MuhClaren I think this is very much the plan.  We're working on our build flow.  It should be available very soon.

**Comment by Sing-Li** [comment]
100% accurate.

**Comment by MuhClaren** [comment]
A build number would be just as good; if it can be derived from the result of #961, that'd be excellent. Thanks for all your time and effort on this project. Cheers.

**Comment by Sing-Li** [comment]
@MuhClaren   thanks.

Every new build now includes a  version +  build number.  

For now, it can be accessed directly via :   `http://<your server name>/buildinfo/buildinfo.txt`

Other tickets will be created to 'read and display' this version information in  more UI/UX friendly way across clients and servers - including mobile, Electron, web, and so on.

There is a minor bug  #1117  which should be fixed shortly.

I am closing this case for now.

**Comment by MuhClaren** [comment]
Great work! Thanks!

**Comment by JackDragon** [comment]
I couldn't find information on this, but this url does not work anymore. Instead, you can go to `<your server>/api/info` instead now to view your version info.

**Comment by geekgonecrazy** [comment]
![image](https://user-images.githubusercontent.com/51996/162268379-da1054c0-3065-41d9-8ec9-27a4f3f8603f.png)
has been here for a while

**Comment by HoldOffHunger** [comment]
![not-working](https://user-images.githubusercontent.com/14262061/165303931-885a5749-0cfb-4f7c-b84f-bd002460230f.jpg)

How do you get to the "Info" page you're linking there?  Because I have clicked every link in the top-left corner and nothing shows the version number.  For example, I'm looking at: https://rchat.example.com/home .  There is no version here at all.

**Comment by dudanogueira** [comment]
@HoldOffHunger 
If you are the ADMIN of that instance, you can go to your avatar, then ADMIN > INFO

If you are not... you can check under the API:

https://open.rocket.chat/api/info

**Comment by HoldOffHunger** [comment]
Oh, yeah, that works.  But I mean, is there a way to just show the version number in the documentation/main/page/whatever page?  It can't be hidden because it's a "security issue," if I can just look it up in the API.

Most applications show their version number in the doc/main/page/whatever page.  So they don't have to have their sys admins hunt down version numbers and figure out whether an application is out of date or not.  I don't see why this information isn't just displayed normally?
