### ISSUE TITLE
Auto-hide livechat room on close

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat#11118]
### Expected Behaviour

When closing a livechat room, the room should be removed from the room list in the left sidebar. This option was available in past releases.

### Actual Behaviour

Livechat rooms are not removed when closing a room. It does not matter if you close the room via the Smarti widget nor the info panel. 

### Steps to Reproduce

1. Open new Livechat
2. Write anything
3. Close room by clicking on the button in the Smarti UI (or the close button in the info panel)
4. Room is still listed in the sidebar

**Comment by mkwong04** [comment]
I found that there are 2 updates on the **Subscriptions** model, which overwrite the value of "open" depends on the sequence of call

1. packages/rocketchat-livechat/server/lib/Livechat.js
setting the "open" to false (hide the closed livechat room)
```javascript
if (room.servedBy) {
  RocketChat.models.Subscriptions.hideByRoomIdAndUserId(room._id, room.servedBy._id);
 }
```
2. imports/message-read-receipt/server/hooks.js
setting the "open" to true, when setAsReadByRoomIdAndUserId() is invoked during "afterSaveMessage" 
```javascript
	// skips this callback if the message was edited
	if (message.editedAt) {
		return message;
	}

	// set subscription as read right after message was sent
	RocketChat.models.Subscriptions.setAsReadByRoomIdAndUserId(room._id, message.u._id);
```

if 1. occur after 2., then closed livechat room properly "removed", otherwise (1. before 2.) it remain in the listing.

I temporary work around by changing the return message condition to skip the override of "open" to true
 ```javascript
	if (message.editedAt || message.t==='livechat-close') {
		return message;
	}
```
**Note:** am not sure any other side effect of not invoking setAsReadByRoomIdAndUserId() and markMessageAsReadBySender() for closing an opend Livechat room. Hope a proper fix can be in place.

**Comment by knrt10** [comment]
On it, fixing this
