### ISSUE TITLE
Settings does not save

### ISSUE THREAD

**Issue by joseftw** [RocketChat/Rocket.Chat#11126]
### Description:
When updating a setting, it is not persisted.

### Steps to reproduce:

1. Go to Preferences
2. Change Offline Email Notifications to Disabled
3. Click Save Changes

### Expected behavior:

The Offline Email Notification setting should be Disabled

### Actual behavior:

The Offline Email Notification setting is not Disabled.
![rocketchat](https://user-images.githubusercontent.com/1232096/41353361-556d8bc8-6f1c-11e8-9ce5-aa5d33cf3904.gif)

**Comment by TwizzyDizzy** [comment]
I cannot confirm this on Rocket.Chat (`0.66.0`). Please update and verify that this is still true. If it is, please get back to me and I will reopen this issue. Before getting back to me though, please provide all the information we require in the issue template, otherwise we cannot help you.

Cheers (+close)
Thomas

**Comment by gillbates** [comment]
this is still true using 0.74.0 docker fresh install
