### ISSUE TITLE
Snap auto ssl with caddy does not work 

### ISSUE THREAD

**Issue by eszeus** [RocketChat/Rocket.Chat#11123]
### Description:

We are using a subdomain to connect to our rocket.chat
sub.domain.com points to our PUBLIC IP:3000, which is redirected via NAT to our internal LOCAL IP:3000.
After enabling caddy with auto ssl, it just doesnt redirect to https and if I try to use https, it shows an error in webbrowser.

My caddy file looks like:
**sub.domain.com
tls self_signed
proxy / localhost:3000 {
   websocket
   transparent
}**

journalctl -xe tells me after restarting caddy service:
**...rocketchat-caddy25385): Activating privacy features... done.
...rocketchat-caddy25385): https://sub.domain.com:2015
...rocketchat-caddy25385): WARNING: File descriptor limit 1024 is too low for production servers. at least 8192 is recommended. Fix with "ulimit -n 8192".**
Thats all

### Expected behavior:

redirect http adresses to https auto

### Actual behavior:

chat is still only accessible through http

### Server Setup Information:

- Version of Rocket.Chat Server: stable version from snap
- Operating System: ubuntu 16 LTS x64
- Deployment Method: SNAP
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: SNAP
- MongoDB Version: SNAP

### Relevant logs:

Description above

**Comment by eszeus** [comment]
push

anybody here who could help solving this?

**Comment by kodai2199** [comment]
Hi, remember that you set up a proxy in Caddy that **redirects to localhost:3000**. 
This means Caddy is now listening on port 2015 (because you are using `tls self_signed`) and will automatically redirect all requests on that port to your Rocket.Chat server on port 3000.

So, on your router, you will have to forward `PUBLIC IP:2015` to `LOCAL IP:2015`. Then you should be able to access to `https://LOCAL IP:2015`, even if that will give you a security error because you are using a self-signed certificate.
_________
The final solution is to forward ports **80** (standard HTTP) and **443** (standard HTTPS) to your local IP, and remove the `tls self_signed` to automatically obtain a real certificate from Let's Encrypt.

Forward table will look like this:

| Incoming Port | Destination IP Address | Destination Port |
| :---------------: | :-------------------------: | :---------------: |
| 80 | SERVER LOCAL IP | 80 |
| 443 | SERVER LOCAL IP | 443 | 

while your **Caddyfile**:
```
sub.domain.com
proxy / localhost:3000 {
     websocket
     transparent
}
```

Now Caddy will also redirect requests from port 80 (HTTP) to port 443 (HTTPS) automatically.

**Comment by hupptechnologies** [comment]
I'm having pretty similar issue, here's my Caddyfile  : 
`https://sub.domain.com:8080 {
  proxy / localhost:3000 {
    websocket
    transparent
  }
}`
I've installed rocketchat on Ubuntu 16.04 DO droplet with snap and followed detailed step here on [enabling SSL](https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/autossl/)

I want this to run on a subdomain and the specified port number.
I've made sure to restart the service after above changes to Caddyfile but still the server fails to load when access over https and port 8080.
Quick note : Rocketchat works fine when access via non HTTPS path and port 3000

Any idea's what could be wrong here ?

**Comment by geekgonecrazy** [comment]
Thanks for all the great responses here.  More then enough info to consider this resolved 👍

**Comment by Ernat** [comment]
Hi! Let's Encrypt has [revoked](https://community.letsencrypt.org/t/2022-01-25-issue-with-tls-alpn-01-validation-method/170450) the certificate on which Rocket.Chat worked, now how to reissue the certificate on the Caddy snap. I tried [this](https://docs.rocket.chat/quick-start/installing-and-updating/snaps/auto-ssl-with-snaps) option, certificate reissue didn't work.
