### ISSUE TITLE
:football: emoji shows a weird oval ball not a real round football ball

### ISSUE THREAD

**Issue by bog-dan-ro** [RocketChat/Rocket.Chat#11196]
In the spirit of the World **football** cup, can someone pretty please fix this very important issue ?

**Comment by tsukiRep** [comment]
:soccer::soccer::soccer::white_circle::soccer::white_circle::soccer:
:soccer::white_circle::soccer::white_circle::soccer::white_circle::soccer:
:soccer::white_circle::soccer::white_circle::soccer::soccer::white_circle:
:soccer::white_circle::soccer::white_circle::soccer::white_circle::soccer:
:soccer::soccer::soccer::white_circle::soccer::white_circle::soccer:

`:soccer:` will answer your prayers

**Comment by bog-dan-ro** [comment]
I know but the naming is wrong ...

**Comment by tsukiRep** [comment]
@bog-dan-ro :us:

**Comment by bog-dan-ro** [comment]
@tsukiRep football is used by 🌍 - 🇺🇸 ;-)

**Comment by tassoevan** [comment]
Unfortunately, this is an [EmojiOne](https://github.com/emojione/emojione) issue.

**Comment by vynmera** [comment]
We'll have to page @DonaldTrump and @TheresaMay for a debate on this. You see, this has always been a large-scale issue not so much with Rocket.Chat, but with the entire English language.

When the US detached from the UK, the US decided to change the language a little, and developed what is now known as US English. With this, people also developed their own culture.

In that culture, a new sport was also born. Of course, the Americans wanted to spite the UK just one more time. So they called the sport "football", even though there was already such a sport. The original sport was renamed to "soccer".

Why, might you ask? Well, the reason is simple. When you write "football" in Scrabble, you get 13 points. Furthermore, you use your whole deck of tiles - a great feeling. Not only that, but since the word is large, there is a good chance you'll hit a double word value - or even a triple!

Soccer however, only gives you 10 points, and leaves you with 2 tiles. It's simply disappointing. Hence the reason why the Americans renamed the old football to soccer and created their own football.

The rest of the world later retaliated by copying American football and calling it rugby - an easy to write word that allows you to git rid of the pesky Y tile, and still keep 11 points. Furthermore, they reference American football as "American", to make it unwritable in Scrabble.

Of course, EmojiOne is an American team. So they will side with their country to defeat the UK in the endless match of Scrabble. However, it's time to put an end to this silent war.

Together, we can start a future. Together, we can finally unify the words and link our languages. May, Trump, let's make up. Times have changed. We need to all be able to Scrabble together. Thank you Rocket.Chat team, for giving the world the opportunity to unite once again. And thank you @bog-dan-ro, for starting this discussion.
