### ISSUE TITLE
Closing an IM room (im.close) doesn't remove it from im.list

### ISSUE THREAD

**Issue by vdimitrieski** [RocketChat/Rocket.Chat#11234]
Hi, 

I am looking for a way to close an IM room (or delete it if it is possible) via REST API. If I invoke im.close as described in the REST API documentation i get `success:true` in the response but the IM room is still returned via call to im.list. Have I overlooked some role or (I am doing this as a IM room owner)?

I would expect both users in the room to be able to close it and consequently remove it from im.list result.

Can anyone prove some answers of what might be wrong here or if I am doing something wrong?

Best regards.

P.S. Using docker with RocketChat `"version": "0.65.1"`

**Comment by MarcosSpessatto** [comment]
Hello @vdimitrieski, when you call endpoint `im.close`, you just "hide" the room, because in the case of a DM, even if you close the room, it will remain open to the other participant, so when the other participant sends you a message it reappears in your room list in the sidebar. In your case, when you want to know if a room you are part of, is open or closed you can use this [endpoint](https://rocket.chat/docs/developer-guides/rest-api/subscriptions/getone/) and check the `open` property.

**Comment by MarcosSpessatto** [comment]
Closing this issue once it was answered in the above comment. Thanks.
