### ISSUE TITLE
block active directory/ LDAP users outside company

### ISSUE THREAD

**Issue by vfxpandit** [RocketChat/Rocket.Chat#11242]
We use rocket chat application inside our company for communication and file sharing.
All user accounts fetch from LDAP (Microsoft server 2012 Active Directory).

We hosted rocket chat in our company internal server and every user can access the chat server by `(https://our_rocketchat_hostname)`.

Now, We want some users can access the chat server from outside company.
for this we host the same server on internet `(https://our_rocketchat_hostname.com)`

**The problem is now every LDAP user can login and access chat on internet. 
How we can block eveyone and allow only selected users to login and access to chat server on internet ?**

> A suggestion for new feature:
> Block all LDAP user on internet and allow manually created user on internet.
> LDAP users can only login in LDAP environment or local network inside company.

**Comment by TwizzyDizzy** [comment]
Currently, you cannot. My suggestion would be to limit the outside access via firewall and only allow those IPs (yes - dynamic IPs is a problem) you want to have access. Weird workaround, but I do not think this is something that's going to be implemented in Rocket.Chat.

Cheers
Thomas

**Comment by magicbelette** [comment]
Hey !

In case it can help, here is our workaround cause we really need this feature too. 

We tagged the `user-agent` header with reverse-proxy when the connection comes from the Internet. Then modify `<ROCKET.CHAT_HOMEDIR>/programs/server/packages/rocketchat_ldap.js` line 619 :

```
//  if (RocketChat.settings.get('LDAP_Enable') !== true) {
  if (RocketChat.settings.get('LDAP_Enable') !== true || this.connection.httpHeaders['user-agent'].indexOf('internet') !== -1) {
    return fallbackDefaultAccountSystem(this, loginRequest.username, loginRequest.ldapPass);
  }
```

We choose `user-agent` as there's no much choice in accessible http headers. 

The problem is that with this workaround the Rocket.Chat Android client complains about undefined `this.connection.httpHeaders`...

**Comment by vfxpandit** [comment]
@magicbelette I tried your method, But still LDAP users can access rocketchat from internet.
