### ISSUE TITLE
Please Update SNAP

### ISSUE THREAD

**Issue by tjaoc** [RocketChat/Rocket.Chat#11324]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vynmera** [comment]
IIRC, snap deployments are delayed because it's more appropriate to test everything (does it all work?) before publishing, so that people aren't stuck with a broken installation (after all, snaps update automatically).

That said, this snap has been notably late, and even the blog post hasn't been made yet to announce 0.66.0. So it might be good to check what's going on (however, I noticed that a 0.66.1 is being established, so we might need to wait for that)

**Comment by mydoghasworms** [comment]
@geekgonecrazy Looking at the repo it seems that you last worked on the snap definition files for a much older release of RC. Do you know where the current definitions are maintained and who maintains them?

I've been to open.rocket.chat to enquire and it seems a number of users are asking about an updated snap.

**Comment by geekgonecrazy** [comment]
As @vynmera said the big thing is snaps have to under go a manual QA to make sure it at the least doesn't break in our test install.  This is because snaps auto update.  

That being said 0.66.2 is now out :)
