### ISSUE TITLE
[Improvement] IP Anonymization in Livechat

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat#11427]
**Is your feature request related to a problem? Please describe.**
The Rocket.Chat livechat stores the IP addresses of customers. But IP addresses are privacy-related data and should be handled carefully. A way to avoid special treatment of those data is to anonymize the data. Data analytics tools like Google Analytics are aware of this issue and ship special IP anonymization features.

**Describe the solution you'd like**
I suggest to allow IP anonymization (e.g. like https://support.google.com/analytics/answer/2763052?hl=en) for all livechats. Thereby no IP addresses are stored and Rocket.Chat providers do not have to deal with such privacy-related customer data. 

Rocket.Chat admins should be able to turn anonymization on/off.

**Comment by reetp** [comment]
Anyone working on this? it has a bearing on GDPR compliance.
There is zero need for the IP to be stored/displayed.
At the least there should be an 'off' switch to disable collection/storage.

**Comment by alf-FS** [comment]
I've been discussing this with **reetp**  (@ not working) in your support channel. since we're hosting RC for councils in the UK this is an urgent requirement for us, we'll need to hack some workaround in the meantime. 

Not to be overly critical but I'm unsure why it is included in the first place, as I can't see why it would ever be useful in a LiveChat support context (though there may of course be valid reasons that I can't think of)

An update on the scheduled time for delivery would be much appreciated

**Comment by alf-FS** [comment]
We've hacked our way around it for now by putting the following in our Dockerfile:
```
RUN sed -i -r -e    \
    's/^(\s*userData\.ip\s*=\s*).*/\1"IP address not collected";/g'  \
    /app/bundle/programs/server/packages/rocketchat_livechat.js 
```

Aaron Ogle in RC Support channel suggested I add it to the ticket

**Comment by renatobecker** [comment]
Hi @alf-FS!

The IP address has been stored inside the `visitors` collection, only.
We're discussing internally aiming to provide a better solution for this case.
What I can say now is that it's a WIP, already.

Thanks.

**Comment by renatobecker** [comment]
Hi @wreiske.
Yeah, it's an optional feature as you can see below.
Thanks.

![screen shot 2019-01-17 at 15 22 36](https://user-images.githubusercontent.com/2067649/51336490-cc204300-1a6b-11e9-86a2-651ae93bcae9.png)
