### ISSUE TITLE
Multi-file upload

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat#11444]
**Is your feature request related to a problem? Please describe.**
Uploading a couple of files one-by-one is tedious. You have to add them one-by-one. 

**Describe the solution you'd like**
There shall be an option to select multiple files. One solution might be to drop multi-files directly in the chat window. Another way could be to select multiple files via the upload window.

I know that there a plenty of ways to handle this issue. Thereby I like to use this issue to discuss different approaches. If there are already some discussions in place, please close this issue. I have not found any other issue about this topic.

**Comment by tassoevan** [comment]
> One solution might be to drop multi-files directly in the chat window. Another way could be to select multiple files via the upload window.

Actually, you can do that.
Since an __Upload file?__ modal dialog will be shown for each file, should I assume this is the main issue?

**Comment by janrudolph** [comment]
okay, thanks! I will close this issue

**Comment by chevalierv** [comment]
Hello, 

I'm configuring a Rocket.Chat Server with Amazon S3 and I have an issue with the upload files functionality. 

We frequently share multiple pictures and, on web version, the server ask for confirmation with a modal for each picture. That's impossible to handle when you upload more than 10 pictures. Worse, on iPhone, you have to select the pictures one-by-one. Could you make anything about this ?

Also, you might want to check iOS14's file picking mechanisms because Apple has restrict this functionality.

Thanks for your consideration :)
