### ISSUE TITLE
Implementing Rocket Chat in our own native apps

### ISSUE THREAD

**Issue by shorabhd** [RocketChat/Rocket.Chat#11510]
Hi All,

Has anyone came across this issue where you want to integrate rocket chat in your own app? 

Is there a way to do it or any guidelines on how to do it? 

Our company is ready for any contractors who has experience in doing this. 

Regards,
Shorabh

**Comment by MartinSchoeler** [comment]
@shorabhd Github is not the best place to ask these kind of questions, since we use it for feature requests and bug reports.

Please see our [guidelines for support](https://rocket.chat/docs/getting-support). 

You will probably have more success asking in our [forums](https://forums.rocket.chat/)

Thanks!
