### ISSUE TITLE
Support sending pushes to mobile apps even if desktop/web app is open

### ISSUE THREAD

**Issue by sergiorykov** [RocketChat/Rocket.Chat#11517]
When I use several clients (mobile/web/desktop) my desktop app can be hidden in tray, or I went from laptop away, I don't receive any pushes to my mobile app till I close desktop app. I miss important messages from my teammates. It blocks us from using it throughout our company. If I will not be shure that push will find it's receiver - I will have to duplicate channels - whatsapp, fb messenger, whatever.

Find out whether the user works in desktop app or not, away or not, and switch channel for sending pushes from desktop/web to mobile, if mobile app is installed (I assume that almost all who use it daily will install it).

ENV:
server 0.66.3, ios app 3.0.1 (199), windows desktop client 2.11.0

Server Settings: pushes go thru gateway, test push comes to my iphone app.
Personal Settings: pushes enabled for all types of messages

When desktop client is closed - all pushes go to my iphone app. When desktop client is open - all notifications goes to desktop client and ios app doesn't receive any pushes....

**Comment by kaiiiiiiiii** [comment]
You can activate “Always notify mobile” (Administration -> General -> Notifications) to  achieve that behavior. But IMHO this should be a user setting, not a global defined one :)

**Comment by stickboy06** [comment]
I have the same problem where push notifications don't get sent unless you close all your desktop clients and web browser sessions.  It used to work when the desktop client/browser would go inactive after 5 minutes and set your status to away.  Then push notifications would be sent out.  I believe my status is still set to away after 5 minutes of inactivity on the desktop clients/browsers, but I'll have to double check.

Server version: 0.69.1
Desktop clients: All tested versions from 2.10.5 up to 2.13.3
Phone apps: many different versions tested for phone clients on iOS and Android

**Comment by stickboy06** [comment]
This may help people with Push notification problems, as I had to piece it together from multiple bug posts.
RocketChat updates have been changing settings that I have set, which then breaks functionality.  Push notifications for example stopped working after an update.  I searched for two months and updated to two different server versions during that time, but still they were broken.  One month I found that an update disabled and removed the Gateway server in the Push settings.  I enabled that and set it to https://gateway.rocket.chat, which then allowed my test Push notifications to work.  I still couldn't get push notifications to work naturally. After hours of testing, I found out the push notifications only worked when I closed out all other desktop/browser clients.  I then received push notifications that my according to my user account settings.  A month later, I found that the setting for Accounts > Default User Preferences > Enable Auto Away was set to False instead of True.  Push notifications are only sent when the user status is away or offline, so this setting broke notifications the way I had them setup before for our users.  I hope this helps some people "fix" their Push notification problems.

**Comment by sandys** [comment]
This is a HUGE blocker for us. 
Concept of idle must be per client interface (web vs android vs ios vs others). Desktop being open on a laptop which has been idle for a long time must be considered as such.

If this bug exists, it pretty much means all mobile apps are effectively unusable

**Comment by jthomae1** [comment]
I think it's really important to receive pushes on mobile, even if desktop is open! 
More and more teammates complaining that behavior, because they don't receive push notifications if their desktop apps are open.

**Comment by jthomae1** [comment]
I can also confirm that users don't receive push notifications on moblile devices even if their status on the desktop app is away (orange) or busy (red). This is really a huge blocker.

**Comment by ankar84** [comment]
Totally agree with that issue!
Here is my relevant issue https://github.com/RocketChat/Rocket.Chat/issues/15995
Server version is up to date, but no PUSH notifications if desktop client is open.

**Comment by rodrigok** [comment]
I can't reproduce the issue. Please ensure your profile settings are correct and check if you don't have any client with your account open and online. We just send push if the user has no online connections at all.

Be in mind that we are working to improve how we deliver notifications and this logic may change.

Thanks
