### ISSUE TITLE
Cannot receive notifications from channels and private groups

### ISSUE THREAD

**Issue by Occhioverde** [RocketChat/Rocket.Chat#11559]
### Description:

Once a message is sent to a channel, none of the users, all using an Android RC client (Experimental version), receives a push notification, which happens when private messages or test notifications are sent to these same users (From Rocket.Chat web Panel).

### Steps to reproduce:

1. Send a message to a channel with all offline users (Who, therefore, should receive notifications)
2. See that the latter have received no push notification, despite the message being delivered without any problems

### Expected behavior:

The notification should arrive at all users with the status  "Offline"

### Actual behavior:

No notification is received for messages sent to channels or groups, which happens if the message is sent privately.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.65.2
- Operating System: Ubuntu 18.04 on Raspberry PI 3 Model B (ARMHF)
- Deployment Method: Snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v8.11.1
- MongoDB Version:

**Comment by kaiiiiiiiii** [comment]
You’ll never get a push notification for a normal message (no mentions in it) as long as you don’t define it that way in your notification preferences.

Or do I misunderstand you?

**Comment by Occhioverde** [comment]
I do not think the problem is that, since the preferences for notifications are set to "All messages", as you can see in this screenshot...
![Notification preferences screenshot](https://user-images.githubusercontent.com/18429412/43154876-1969286a-8f76-11e8-9cef-e39ba28f2de4.png)
("Tutti i messaggi" means  "All messages")

**Comment by cdhowie** [comment]
I'm not sure if it's related, but I'm experiencing the same thing with both the "standard" Android app an the experimental one.  A test push notification is successfully delivered through both apps.

However, I have not received a message notification in months, through any channel, group, or private message.  My settings are configured for default (mentions) push notifications.  There are some channels I have set to push notifications for all messages, and I still don't get notifications on those.

**Comment by piotrkochan** [comment]
Maybe related https://github.com/RocketChat/Rocket.Chat/issues/12063

**Comment by stickboy06** [comment]
This may help people with Push notification problems, as I had to piece it together from multiple bug posts.
RocketChat updates have been changing settings that I have set, which then breaks functionality.  Push notifications for example stopped working after an update.  I searched for two months and updated to two different server versions during that time, but still they were broken.  One month I found that an update disabled and removed the Gateway server in the Push settings.  I enabled that and set it to https://gateway.rocket.chat, which then allowed my test Push notifications to work.  I still couldn't get push notifications to work naturally. After hours of testing, I found out the push notifications only worked when I closed out all other desktop/browser clients.  I then received push notifications that my according to my user account settings.  A month later, I found that the setting for Accounts > Default User Preferences > Enable Auto Away was set to False instead of True.  Push notifications are only sent when the user status is away or offline, so this setting broke notifications the way I had them setup before for our users.  I hope this helps some people "fix" their Push notification problems.

**Comment by GoetheG** [comment]
Is it possible to make all this notification stuff a little bit easier?

**Comment by reetp** [comment]
Much has changed. Please keep up with github and blogs to see what is happening.

https://rocket.chat/2019/09/27/push-notification/
https://whimsical.com/Bngw3kot3wWPMAAJTebDUJ

> Starting at Rocket.Chat version 2.1.0, the value for Desktop Notification Default Alert and Mobile Notifications Default Alert will be All Messages. When updating to version 2.1.0 or later the servers that were still using the previous default value Mentions, will have the value updated to All Messages.

> Rooms with more than 100 members are still prevented from sending notifications on all messages. There is a setting that can be changed to increase this number called Maximum Channel Size for ALL Message (under Admin > Message) but please use this setting with caution as it may cause performance issues.

This can probably be closed.

**Comment by Occhioverde** [comment]
Of course, surely, I had forgotten to do it...
