### ISSUE TITLE
Rocket Chat auto login

### ISSUE THREAD

**Issue by lewizho99** [RocketChat/Rocket.Chat#11596]
Hello I have been searching and i have not found a seamless solution to this. A simple auto login to rocket chat from my site so the user will not need to login to rocket chat again. 

I am thinking of 
1) getting a user token via the api {done that already}
2) now with this token is there a way to set the cookies and mark that user as authenticated... so it the user enters the rocket chat address they do not need to login again

**Comment by MarcosSpessatto** [comment]
Hey @lewizho99, I think [this PR](https://github.com/RocketChat/Rocket.Chat/pull/11638) can solve your issue. Please let me know what do you think.

**Comment by mbrodala** [comment]
@MarcosSpessatto I'm not sure this would help here. From what I can see the point of Personal Access Tokens is to replace username/password for API login. While this is great it doesn't help with the topic mentioned here.

Right now I'd need to authenticate with the API (username/password or Personal Access Token) and then my app would need to set the `rc_` cookies instead of RC to that the client is automatically logged in once he opens RC. Of course, domain handling also needs to be taken care of here.

A different approach would be using custom auth providers in the RC login screen (e.g. OAuth) but that's not really autologin as users would expect.

**Comment by mbrodala** [comment]
Just FYI: I went with implementing a custom OAuth2 provider by now.
