### ISSUE TITLE
SVG logo not resizing after update to 0.68.3

### ISSUE THREAD

**Issue by chatnl** [RocketChat/Rocket.Chat#11791]
### Description:

I am using a SVG logo which was resizing fine in 0.66.3. Now my version is updated to 0.68.3 and the logo is too small in the side bar and too big in the responsive version above the login form. Setting the max-width to 100% of the logo class is not working too.

### Steps to reproduce:

1. use logo.svg
2. check logo in sidebar
3. check logo above login form on smartphone
### Expected behavior:

The logo would normally fill out the available space of the div

### Actual behavior:

The logo is too small in the sidebar and too big above the login form (only half is visible)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.68.3
- Operating System: Debian 9
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: included in snap
- MongoDB Version: included in snap

### Additional context

changing the css of the logo class has no effect

**Comment by tassoevan** [comment]
What are the image dimensions from the logo?

**Comment by chatnl** [comment]
it is 300px x 88px. The logo on the sidebar is extremely small and the one on the web loginform is only part visible on a smartphone. I am now experimenting with media / viewport settings in the custom css, but that should not be necessary. It should use the space that is available automatically.

**Comment by gabriellsh** [comment]
I just tested this on 3.0.0-develop. The reason the logo looks small on the sidebar is because of its height. No image will stretch past the size of the container. The height of the container for the sidebar footer logo is around 21px (depends on window size). The same goes for the logo on the Desktop app sidebar. If it is too large (height or width) it'll shrink the image until it fits.

Now, for the login image, I tested a SVG with the same size you mentioned and it looks ok.

If this still happens, please send some pictures or maybe the image so we can test. Thanks for your contribution!
