### ISSUE TITLE
Having trouble connecting the live url to port address

### ISSUE THREAD

**Issue by chan1di** [RocketChat/Rocket.Chat#11818]
![screenshot from 2018-08-17 18-47-58](https://user-images.githubusercontent.com/13073412/44268087-1350a080-a24e-11e8-9f20-3a527e85c852.png)

when i run my appliction i get this error "Network error: wss://https://asd.io:443/websocket: getaddrinfo ENOTFOUND https https:443"

plz help me  out with this.

**Comment by MartinSchoeler** [comment]
Hey, looks like you seem to be looking for support. You will have a better chance of getting help if you go to one of the places listed in [here](https://rocket.chat/docs/getting-support/#community-support) since github is not the best place to ask for support. For now i will be closing this issue, as it does not fit our issue guidelines
