### ISSUE TITLE
username not set in register user

### ISSUE THREAD

**Issue by asadi110** [RocketChat/Rocket.Chat#11890]
registerUser method in Realtime API create users without username : 
{
    "msg": "method",
    "method": "registerUser",
    "id":"42",
    "params": [{
        "email": "String",
        "pass": "String",
        "name": "String",
        "secretURL": "String" // Optional
    }]
}
these users are inaccessible because they haven't username.

**Comment by j2l** [comment]
Same issue for me.
I tried with "user" then "username", both are ignored.

**Comment by fasttrackhost** [comment]
Hapened to us too, while trying to register user via REST API. It happens when username it's composed of 2 words or more, for example: "User Name" and not "UserName".

If you try to create a user using gui accesing https://url.of.your.server:3000 you get a error saying username its not valid, but if you register a new user using REST API you only get a RESPONSE saying "bad request", the user its partially created whithout a username (empty username).

System REST API should not create a user at all. When blank username, email its ocupied and the real user cant create his user manualy, so a Admin has to be online and delete that partiall user.

Please fix it and add to documentation how the username should be, like for example: 
a) if you finaly decide to allow usernames composed of 2 or more words
b) if system REST API simply blocks the user registration
c) if system REST API auto STRIPS OUT blank spaces and notifies it in response
d) whatever else you decide to do 👍 

The solution for now its not strip out blank spaces in "username" before passing the REST API request, and it will register user without a problem.

Server Setup Information:

Version of Rocket.Chat Server: 0.74.2
Operating System: Linux x64, Ubuntu 18.04
Deployment Method: snap
Number of Running Instances: 1
NodeJS Version: v8.11.4

**Comment by MartinSchoeler** [comment]
Closing this due lack of updates, if you experience this on the latest release, feel free to open a new issue.

Thanks!
