### ISSUE TITLE
Wrong permalink when running RocketChat in subdir

### ISSUE THREAD

**Issue by ura14h** [RocketChat/Rocket.Chat#11922]
### Description:

When running RocketChat in subdirectory, permalink get wrong URL.
This issue is as to reopen #10732 .

### Steps to reproduce:

1. Start rocketchat with environment: `ROOT_URL=http://localhost:3000/chat`
2. Login and post any message in general channel
3. Select permalink for the message
4. Paste the permalink

### Expected behavior:

The permalink should be "http://localhost:3000/chat/channel/general?msg=..."

### Actual behavior:

The permalink shows like "http://localhost:3000/chat/chat/channel/general?msg=...."

The head of subdirectory as "/chat" repeated twice.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69.0
- Operating System: CentOS 7.5 and macOS 10.13.6
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: 

### Additional context

#10732 has been closed by applied #11543 and #11781.
#11543 which fix the directory page is working correct, but #11781 is not working.

And links by replying message is incorrect too.

### Relevant logs:

N/A

**Comment by thaim** [comment]
I found that when I configure Administration > General > Site URL
as `http://<mydomain>` (not `http://<mydomain>/chat`) and access via `http://<mydomain>/chat`,
permalink works correctly as `http://localhost:3000/chat/channel/general?msg=...`

This is similar behavior to #11924

**Comment by ura14h** [comment]
@thaim Thanks for your comment. But it is that  I receive a configuration alert when display the page first.

**Comment by trunderw** [comment]
If you change the SITE_URL to contain the subdir (e.g. /chat) then the channel icons load (yay). However, then links and other items (e.g. those sent in an email that direct to the site) don't work.  For now, I'm hacking it with a 'logged in user' script:

```javascript
    setInterval(function() {
	document.querySelectorAll(".avatar-image.lazy-img").forEach(function(el){
		if (el.classList.contains('patcheditalready'))
			return;
		tmpSrc = el.getAttribute('data-src');		
		el.setAttribute('data-src', tmpSrc.substr(0,34) + tmpSrc.substr(39));
		el.setAttribute('src', el.getAttribute('data-src'));
		console.log( tmpSrc.substr(0,34) + tmpSrc.substr(39));
		el.className += 'patcheditalready';
	});
    }, 1000)
```

In my case I know my URL length so what I'm doing is pulling /chat (which is 5 characters) out of the middle of the avatar URL. You'll have to adjust to make it work with your own URL length. Because it's running over and over I just added a new class to the element so I didn't affect it again. It's probably running too frequently but works for now until this one and the numerous issues with sub-directory hosting are ironed out.

Interesting note, these all load fine without modification on the mobile apps.

**Comment by ura14h** [comment]
There seem to be many problems. So, I think that it is better for the QA team to add all tests which use subdirectory environment to the CI and to checks its result.
