### ISSUE TITLE
Upload any type of file

### ISSUE THREAD

**Issue by gabrielcsapo** [RocketChat/Rocket.Chat#1193]
Is there an issue that introduces the ability to add any type of file / be able to specify possible upload types from the admin panel. Right now the default is /images, if there are other options could someone point to where those options are in the wiki?

**Comment by gmsecrieru** [comment]
You should be able to setup whatever you with under Admin Settings: logged with an admin user, click on your avatar > Administration > File Upload. You should see something like this:

![screen shot 2015-10-21 at 18 39 04](https://cloud.githubusercontent.com/assets/190883/10649460/107feab2-7823-11e5-8263-913a89440b42.png)

At this very moment you need to restart application after changing, due to a known limitation/issue (see #913)

**Comment by gabrielcsapo** [comment]
Is there a way to make this more accessible from someone who doesn't know which media types a certain file might belong to?

**Comment by gabrielcsapo** [comment]
Having something like this on that page to help users figure out which to add would be useful (http://www.sitepoint.com/web-foundations/mime-types-complete-list/ )

**Comment by gmsecrieru** [comment]
I thought you would just leave the field empty, but it turns out there were a little more changes needed. I just pushed those changes to #1192 , and as soon as it is merged you should be able to allow all types of file.

Thanks for the feedback!

**Comment by gabrielcsapo** [comment]
:+1: Glad I can help. 

> I came to find some work to get started contributing

**Comment by gmsecrieru** [comment]
Jump in, we have tons of things to do and a great community! :) Feel free to reach us on the [demo server](https://demo.rocket.chat).

**Comment by gabrielcsapo** [comment]
@gmsecrieru Thanks!

**Comment by allanregistos** [comment]
Hi,

after doing the update docker pull rocketchat/rocket.chat
then docker-compose up
I am still at ancient version:
v0.6.1853
# Meteor packages used by this project, one per line.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

What's wrong with my update?
Additional info:
directory: ~/Rocket.Chat

Was it because of user permissions?

Thanks,
Allan


On Thu, Oct 22, 2015 at 5:42 AM, Gabriel Csapo <notifications@github.com>
wrote:

> @gmsecrieru <https://github.com/gmsecrieru> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RocketChat/Rocket.Chat/issues/1193#issuecomment-150033632>
> .
>



-- 
God is love and God is just.

**Comment by gmsecrieru** [comment]
@allanregistos could you please post this in a related issue or open a new one?

**Comment by gmsecrieru** [comment]
Closed by #1192
