### ISSUE TITLE
unable to delete user because user is last owner of some room

### ISSUE THREAD

**Issue by himpierre** [RocketChat/Rocket.Chat#11941]
### Description:

I just tried to delete a user but was not able to do so because the user seems to be the last owner of one or more channels / rooms / groups. This is a bit of a problem because the error message does not say *which* rooms. How do i find those rooms? I have hundreds of them.

### Steps to reproduce:

1. Try to delete user (user is last owner of some rooms)
2. Error message: error-user-is-last-owner

### Expected behavior:

It should be possible to delete a user. Maybe the rooms, where the to be deleted user is last owner should be shown?

### Actual behavior:

User cannot be deleted.

### Server Setup Information:

- Version of Rocket.Chat Server:  0.69.1
- Operating System: Linux
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog:  yes
- NodeJS Version:  8.11.3
- MongoDB Version: 3.6

**Comment by Gummikavalier** [comment]
As a workaround to this problem we've been using this command on the server to find out the ownership of rooms by the user (youruser in the command):

`mongo rocketchat --eval "db.rocketchat_room.find({'u.username':'youruser'},{'name':1}).forEach(function(y){print(y.name);})"`

This prints a list of channels the user is owner in.

Should the channel be a private one, you have to make it public for so long that you can join into it as admin and demote user status from the owner to the normal user, and then switch the channel back to private.

So far so good, but we have also encountered some users that still cannot be deleted, even when they are not owners on any existing channels any more. We assume that these user accounts have been created in the beginning of our service while there was some additional bootstraps to the user base because of the early LDAP problems.

**Comment by himpierre** [comment]
@Gummikavalier although I'm using
`
mongo rocketchat --eval "db.rocketchat_room.find({'u.username':'youruser'},{'name':1}).forEach(function(y){print(y.name);})"
`

it happens the message error-user-last-owner remains for some users. Can you think of an explanation for that behaviour?

thanks and cheers

**Comment by Gummikavalier** [comment]
@himpierre Unfortunately not. I'm struggling with the same issue with one of our old users. I think those are very old and may have some old cruft from the time when we still were honing our LDAP configuration and had to manually drop and recreate users. It also seems that the original owner of the channel will always be listed as an "owner" on that channel, even though such privileges were removed. At least for this one problematic user.

**Comment by himpierre** [comment]
Thanks.

Am 14. Februar 2019 17:47:34 MEZ schrieb Gummikavalier <notifications@github.com>:
>@himpierre Unfortunately not. I'm struggling with the same issue with
>one of our old users. I think those are very old and may have some old
>cruft from the time when we still were honing our LDAP configuration
>and had to manually drop and recreate users. It also seems that the
>original owner of the channel will always be listed as an "owner" on
>that channel, even though such privileges were removed. At least for
>this one problematic user.

**Comment by tassoevan** [comment]
Is this similar to #12978?

**Comment by ntesteca** [comment]
Hello,

On our instance, we encounter a similar problem an we found that an ownership was defined in a subscription (maybe from a older version).

```
{
	"_id" : "XXXXX",
	"open" : false,
	"alert" : false,
	"unread" : 0,
	"ts" : ISODate("2016-11-07T13:31:03.200Z"),
	"rid" : "XXXXX",
	"name" : "bluff",
	"t" : "p",
	"u" : {
		"_id" : "XXXXX",
		"username" : "XXXXX"
	},
	"ls" : ISODate("2016-11-07T15:11:21.268Z"),
	"_updatedAt" : ISODate("2018-08-29T12:38:08.853Z"),
	"roles" : [
		"owner"
	],
	"archived" : true,
	"emailNotifications" : "mentions",
	"emailPrefOrigin" : "user",
	"userHighlights" : [ ]
}
```

Similar to the previous commad, you can use `mongo rocketchat --eval "db.rocketchat_subscription.find({\$and:[{'u.username':'<username>'},{'roles': 'owner'}]},{'name':1}).forEach(function(y){print(y.name);})"` to find it.

**Comment by tars21** [comment]
Are there other workarounds beside "making channel public"? We don't want to join private groups due to privacy.

Via API request [groups.listAll](https://rocket.chat/docs/developer-guides/rest-api/groups/listall/) I can have a look at all private groups including the first owner - It looks like there is just one owner listed, even if the group has multiple.
I could ask a group member if there is an other admin to remove the prevoius owner. But as admin I have not the possibility to get a user list from the channel if I'm not a member ([groups.members](https://rocket.chat/docs/developer-guides/rest-api/groups/members/))
`"errorType": "error-room-not-found"`

If someone knows a workaround or a solution here it would be very nice :-)

**Comment by ggazzo** [comment]
we are planning to close this issue asap.

btw, I'm closing this one, but please fell free to continue the discussion here https://github.com/RocketChat/Rocket.Chat/issues/12978
