### ISSUE TITLE
Private group don't have owner after last owner left the group

### ISSUE THREAD

**Issue by dzienisz** [RocketChat/Rocket.Chat#11947]
### Description:

Private group don't have owner after last owner left the group.

### Steps to reproduce:

1.  Create private group
2.  Add members
3.  Leave the group
4. Other members can't manage this group

### Expected behavior:

There should be a popup where you can (and also require to do) choose new group owner.

### Actual behavior:

You just leave the group.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69.0
- Operating System: MacOS
- Deployment Method: 
- Number of Running Instances:
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: 

### Additional context

I'm currently a "Leader" of this group, but I can't do anything.
There is also bug with translation. There is lack of space in group users sidebar.

![bugs](https://user-images.githubusercontent.com/3521624/45036593-2f7d7b80-b05d-11e8-9f6c-61b20f340a6d.png)

**Comment by MartinSchoeler** [comment]
Hello @dzienisz , this issue has been fixed in the latest versions, now we ask the owner to appoint someone else as owner before leaving the room 
<img width="1525" alt="Screen Shot 2019-10-21 at 11 23 31" src="https://user-images.githubusercontent.com/20868078/67214137-9858bc00-f3f5-11e9-952e-4ead27669a1c.png">
Thanks!

**Comment by dzienisz** [comment]
yes, but what about legacy private groups without owner?
