### ISSUE TITLE
High Cpu Usage

### ISSUE THREAD

**Issue by fuzunspm** [RocketChat/Rocket.Chat#11944]
### Description:

main.js is always at 100% cpu usage and it makes all clients laggy between channel switching or bots waiting 3-4 seconds to get data

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69.0
- Operating System: Ubuntu 18.04
- Deployment Method: snap
- Number of Running Instances: 1
- NodeJS Version: 8.11.3

**Comment by piotrkochan** [comment]
Try to disable message indexing and provide more details about your system (free/total memory). Maybe some iotop?

**Comment by fuzunspm** [comment]
How do i disable message indexing?

OS Load Average | 3.31, 2.64, 2.12
Total Memory: 3.85 GB
Free Memory: 192.18 MB

iotop screenshot: 
<img width="1202" alt="untitled" src="https://user-images.githubusercontent.com/12132746/45030226-d2c99300-b053-11e8-8412-7ee909ed2cb6.png">

**Comment by beranPro** [comment]
Hi @fuzunspm ,
see Documentation:

`You may find that Rocket.Chat slows down once you have a lot of concurrent users. When this sluggishness begins, you will likely see Rocket.Chat node process approaching 100% CPU (even if the host CPU load is low). This is due to the single-threaded nature of Node.js applications; they can’t take advantage of multiple cores natively.`

https://rocket.chat/docs/installation/manual-installation/multiple-instances-to-improve-performance/

**Comment by fuzunspm** [comment]
how do i check my mongodb URL?

**Comment by reetp** [comment]
This appears to be a support issue and not really a bug. Please check the documentation or visit the forums for more information.
Closing notabug. Please reopen if you have further issues.

**Comment by reetp** [comment]
@rocket-cat close
