### ISSUE TITLE
REST API authentication questions

### ISSUE THREAD

**Issue by AmShaegar13** [RocketChat/Rocket.Chat#11987]
When I do `POST /api/v1/login` there are **two** auth tokens created in the database. One that has a `when` attribute and one that does not. I assume, the first one does expire after certain time (probably, what I configured in Administration). However, the second one does not expire and is included in the API response.

**Questions**
* Why are two tokens created when logging in using the REST API?
* Is there an API for `Log out from other logged in locations`? We use API-only accounts for bots which cannot revoke lost tokens otherwise.
* When using LDAP authentication **withouth** `Login Fallback` enabled, why can't I login using `username,password` but have to use the undocumented `username,ldapPass,ldap:true,ldapOptions:{}`-method?

**Comment by MartinSchoeler** [comment]
Hey, looks like you seem to be looking for support. You will have a better chance of getting help if you go to one of the places listed in [here](https://rocket.chat/docs/getting-support/#community-support) since github is not the best place to ask for support. For now i will be closing this issue, as it does not fit our issue guidelines.

**Comment by AmShaegar13** [comment]
My apologies. I rephrased my issue into a bug report which it basically is and created #12045.
