### ISSUE TITLE
How to push notification to 2 Rocketchat iOs app which have diffirent bundle ID

### ISSUE THREAD

**Issue by thekingbk90** [RocketChat/Rocket.Chat#12014]
**Is your feature request related to a problem? Please describe.**
How to push notification to 2 Rocketchat iOs app which have diffirent bundle ID from 1 server

**Describe the solution you'd like**
Our company have 2 brands, so we create 2 apps (clone from rocketchat) and submit them to apple store.
We can create 2 notification.pem file. However on admin configuration, there is only one field to input APN information
http://prntscr.com/kt16o2

Therefore, I suggest a new feature which help admin can enter more than one APN infomration and server can use them to push notification to exact ios app.

**Comment by MartinSchoeler** [comment]
Hey, looks like you seem to be looking for support. You will have a better chance of getting help if you go to one of the places listed in [here](https://rocket.chat/docs/getting-support/#community-support) since github is not the best place to ask for support. For now i will be closing this issue, as it does not fit our issue guidelines. Thanks!
