### ISSUE TITLE
Exception in delivering result of invoking 'login': TypeError: e is not a function

### ISSUE THREAD

**Issue by gakuba** [RocketChat/Rocket.Chat#12137]
When I reload an embedded page it works. but after a few seconds, the integration tries to verify the token and then it redirects me to the homepage instead of keeping me on the channel that I want the user to access. I checked the logs in my browser and found this:

Exception in delivering result of invoking 'login': TypeError: e is not a function
    at Object.userCallback (c029a6b2088014967102f8efaaf260dc7e0d3df5.js?meteor_js_resource=true:297)
    at c029a6b2088014967102f8efaaf260dc7e0d3df5.js?meteor_js_resource=true:89
    at c029a6b2088014967102f8efaaf260dc7e0d3df5.js?meteor_js_resource=true:71
    at c (c029a6b2088014967102f8efaaf260dc7e0d3df5.js?meteor_js_resource=true:89)
    at e._callback (c029a6b2088014967102f8efaaf260dc7e0d3df5.js?meteor_js_resource=true:1)
    at e [as _maybeInvokeCallback] (c029a6b2088014967102f8efaaf260dc7e0d3df5.js?meteor_js_resource=true:59)
    at e [as dataVisible] (c029a6b2088014967102f8efaaf260dc7e0d3df5.js?meteor_js_resource=true:59)
    at c029a6b2088014967102f8efaaf260dc7e0d3df5.js?meteor_js_resource=true:59
    at c029a6b2088014967102f8efaaf260dc7e0d3df5.js?meteor_js_resource=true:59
    at Array.forEach (<anonymous>)

can anyone please help?

**Comment by localguru** [comment]
What RC, nodejs versions? More details :)

**Comment by gakuba** [comment]
Rocket Chat Version 0.69.2
commit 7df98181051061163e2ab4439b56659e841a0c72
Tag: 0.69.2
Nodejs Version v8.11.3
Running on GCP Linux

**Comment by JLueke** [comment]
I think we have the same problem.
@gakuba do you use the Iframe Authentication?

We did and currently have the problem, that the user is redirected to the home page after 5 minutes have passed (independent of access via website or iframe).

We implemented it with the [usage of the Rocket.Chat API](http://rocketchat.github.io/docs/developer-guides/iframe-integration/authentication/) and thus sending the "loginToken" instead of the "token".

There's a fix if you access the token directly in the mongo db ( was suggested in #6839 ).
We can't do it thus still having the issue with the redirection to home.

RocketChat Version 0.66.3
Nodejs Version v8.12.0

**Comment by JLueke** [comment]
I did some further tests and noticed that the issue doesn't accour if you access the chat via the Electron app.
It also works when you create a new Electron app with a BrowserWindow that loads the chat.
Maybe this reconnecting is handled in a different way in electron. Even the iframeUrl is different.
Sadly simple changing the iframeUrl [here in the iframe_client](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-iframe-login/iframe_client.js#L66) didn't help.

**Comment by guijun13** [comment]
It's working properly on the latest version, but if it is still happening to you, please open a new issue with more details. Thank you very much!
