### ISSUE TITLE
Add proper support for right-to-left languages

### ISSUE THREAD

**Issue by gmsecrieru** [RocketChat/Rocket.Chat#1214]
For [example](https://css-tricks.com/almanac/properties/d/direction/): 
![screen shot 2015-10-22 at 18 33 47](https://cloud.githubusercontent.com/assets/190883/10677597/24be143a-78ec-11e5-9fa5-0b36df1dd868.png)

**Comment by engelgabriel** [comment]
@shahar3012 can you still help us with that?

**Comment by fduraibi** [comment]
@engelgabriel What kind of help do you need?

**Comment by engelgabriel** [comment]
@fduraibi Test the system in a right-to-left language and tell us if there is anything broken o not property aligned.

**Comment by fduraibi** [comment]
Here is the result from the first test:

1- Fix direction of the user status, should be `rtl` instead:
```
.account-box .options > .wrapper {
    direction: ltr;
}
```
2- The markdown `formatting-tips` is not aligned correctly and covers the "user typing" status, should be aligned to the left side
3- Upload Icon need to be flipped
4- The text area ```Message``` should be on the right side (`dir="auto"` need to be changed to `dir="rtl"`, since auto keeps it on the left even when using Arabic word instead of `Message`)
5- The `flex-tab-bar` is totally missing in Arabic interface
6- Allow using Arabic (non-English) to display names of users and rooms

![rocketchat-bug4](https://cloud.githubusercontent.com/assets/432460/11477954/5ac21182-9758-11e5-8dd2-34c12781c7b5.png)

**Comment by fduraibi** [comment]
7- Fix alignment of message staring:
![rocketchat-bug5](https://cloud.githubusercontent.com/assets/432460/11479523/75dbd554-9760-11e5-9fa6-2a742e40bb23.png)

**Comment by fduraibi** [comment]
8- Other fixes need to be done in the Administration pages, e.g. room management:

![rocketchat-bug7](https://cloud.githubusercontent.com/assets/432460/11512420/f8df2b1e-983b-11e5-89f8-72bac9c7f2dd.png)

* Missing name is a bug that happened after I renamed one of the rooms. The room was created with an english name, then I enabled using Arabic characters in the UTF8 regex, renamed the room to an arabic name, it accepted the name but it disappeared! (see picture below also)
![rocketchat-bug8](https://cloud.githubusercontent.com/assets/432460/11512504/6a83601e-983c-11e5-8203-88fdbd7f4d5c.png)

* This is on a fresh installed server with latest updates

**Comment by fduraibi** [comment]
All of the listed problem are fixed in https://github.com/RocketChat/Rocket.Chat/pull/1538 or https://github.com/RocketChat/Rocket.Chat/pull/1569

Except the last problem of missing room name, but that is more of a general bug and doesn't seem to be RTL related.

@engelgabriel I suggest closing this issue.

**Comment by engelgabriel** [comment]
Does the room name goes missing only on after renaming? If you create it properly it shows ok, right?

**Comment by engelgabriel** [comment]
Closed, and the remaining issue was created https://github.com/RocketChat/Rocket.Chat/issues/1571
