### ISSUE TITLE
Download uploaded attachments twice

### ISSUE THREAD

**Issue by piotrkochan** [RocketChat/Rocket.Chat#12200]
### Description:

Problem occurs always when I download attachment uploaded by someone in chat window.
System prompts me to select target directory, I click save and after that same window displays again.

### Steps to reproduce:

1. Click download file
2. Select location
3. Click choose
4. File is saved and window opens again.

### Expected behavior:

One propmp

### Actual behavior:

Two prompts

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69.1
- Operating System: Ubuntu 18
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 0
- NodeJS Version: 8.11.4
- MongoDB Version:  4

**Comment by Ufoton** [comment]
Same Issue with 0.70.0. 
Operating System: Centos 7
Deployment Method: tar
Number of Running Instances: 1
DB Replicaset Oplog: 0
NodeJS Version: 8.11.4
MongoDB Version: 4

**Comment by piotrkochan** [comment]
Sorry, I'll stay with 0.69.2 while 0.70 have a lot of bugs.

**Comment by piotrkochan** [comment]
moved to https://github.com/RocketChat/Rocket.Chat.Electron/issues/930

**Comment by reetp** [comment]
Well, if it is with 0.69.x it won't get fixed if it is a server error, and you have provided no evidence that it is.

I'm not sure what 'lots of bugs' you are referring too. Rocket is still effectively beta as it is < 1.0.0 so bugs are to be expected I'm afraid.

It also seems more likely that this is a client issue rather than a server issue.

Closing notabug unless you have anything to suggest it is.

**Comment by reetp** [comment]
@rocket-cat close

Please reopen if you have further issues and logs to support it.
