### ISSUE TITLE
`canAccessRoom` validation is weak

### ISSUE THREAD

**Issue by timkinnane** [RocketChat/Rocket.Chat#12310]
The auth handling for `canAccessRoom` processes an array of handlers and allows access if **any** of them return true. Shouldn't it return false unless **all** of them return true?

Example here: https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-authorization/server/functions/canAccessRoom.js#L25

> The some() method tests whether at least one element in the array passes the test implemented by the provided function.

**Comment by Hudell** [comment]
The first handler checks if the room is a channel and in that case checks if the user has permission to read it. The second one will return true if the user is already subscribed to the room. Either one returning true means the user can access the room, even if the other one does not return true.

An example: For a public channel that the user has never joined, there'll be no subscription, so the second handler would not return true. Meanwhile the first handler would not return true for any non-public room.

It could be changed so that the handlers always return true when they don't need to block access and then a single negative result would mean the access needs to be blocked, but with the current conditionals there's no need for that.

**Comment by timkinnane** [comment]
@Hudell Thank Pierre but I'm thinking of cases outside the default validators.

The intention of `RocketChat.authz.addRoomAccessValidator` seems to be for adding additional logic that might deny users access to a room.

The logic might work with the existing default validators, but that's not enough to ensure security. I'm looking specifically the effectiveness of the `addRoomAccessValidator` method.

After the default checks give a pass, all the additional validators are run. At the moment if the default checks pass, the whole thing will pass, even if the additional validators return false. So the whole utility is ineffective.

The solution is to change `.some` to `.every` - I just wanted to post the problem first to point it out in case I'm missing something.

**Comment by Hudell** [comment]
You're right, I failed to notice the `addRoomAccessValidator` method.

We need to change the `.some` to an `.every` and change the default handlers to always return true when they don't need to block access.
