### ISSUE TITLE
Upload Stuck 

### ISSUE THREAD

**Issue by MCIT07** [RocketChat/Rocket.Chat#12334]
Hello,

I have installed RocketChat on Centos 7.
My upload stuck to 0% for files,audio,video.. : https://ibb.co/nM3cML

Can someone help pls ?

Thank's

**Comment by reetp** [comment]
This is most likely a support/configuration issue rather than a bug.

For support issues please go to the forums https://forums.rocket.chat/ or #support here https://open.rocket.chat

If you have found a bug please reopen this issue with proper information and logs. See here for a template:
https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

How to report an issue:
https://rocket.chat/docs/contributing/reporting-issues/

**Comment by reetp** [comment]
@rocket-cat close
