### ISSUE TITLE
503 Server Unavailable

### ISSUE THREAD

**Issue by qtechsandesh** [RocketChat/Rocket.Chat#12332]
### Description:

Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
### Steps to reproduce:

1. 
2. 
3. 

### Expected behavior:

It should Run 
### Actual behavior:
Rocket.chat Server is running at backend but not able to connect the server from any client. 

### Server Setup Information:

- Version of Rocket.Chat Server:  
- Operating System: Ubuntu Server 16.04 LTS
- Deployment Method:  snap/rocketchat.server
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v6.12.3
- MongoDB Version: 2.6.10

**Comment by piotrkochan** [comment]
Make sure you're really try to connect rocket chat and nothing else, also paste some logs.

**Comment by reetp** [comment]
This is most likely a support issue rather than a bug. If you have found a bug please reopen this issue.

Please read here on how to debug your installation and provide proper information:

https://github.com/RocketChat/docs/tree/master/installation/manual-installation/ubuntu/snaps

For support issues please go to the forums https://forums.rocket.chat/ or #support here https://open.rocket.chat

**Comment by reetp** [comment]
@rocket-cat close
