### ISSUE TITLE
When typing the text field increases its size

### ISSUE THREAD

**Issue by punkr0ck** [RocketChat/Rocket.Chat#12393]
https://imgur.com/a/mkh2cZw

Several users reported this weird bug on Lisk.Chat on version 0.70.4

**Comment by ledainam** [comment]
+1 i have same issue on version 0.70.0

**Comment by reetp** [comment]
@rocket-cat label add duplicate

https://github.com/RocketChat/Rocket.Chat/issues/12183

This should have been fixed in 0.70.0

If you have further issues please post on #12183 with full server and client details - use this as your guide please:

https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

**Comment by reetp** [comment]
@rocket-cat close
