### ISSUE TITLE
Channel name does not support Chinese.

### ISSUE THREAD

**Issue by wm20111003** [RocketChat/Rocket.Chat#12446]
When I wanted to create a chat room, I found that I could not input Chinese；
Hope PM could improve as soon as possible, thanks!

![image](https://user-images.githubusercontent.com/10558850/47600904-fb8a5b00-d9fa-11e8-9975-8b58c56a31ae.png)

**Comment by ura14h** [comment]
If you are Administrator, You may customize at "Allow Special Characters in room names" and "UTF8 Names Validation". Try it.

**Comment by wm20111003** [comment]
I tried it, and now I can input Chinese. After the creation, the project will be paralyzed, and I cannot create a new room！

**Comment by ura14h** [comment]
In fact, I think it is difficult to customize the "UTF 8 Names Validation" parameter to use CJK characters.
Related Info: https://en.wikipedia.org/wiki/CJK_Unified_Ideographs

**Comment by achilles-kosun** [comment]
@ura14h 
I think the problem is here, not only for Chinese：
https://github.com/RocketChat/Rocket.Chat/blob/57eb4d5531eef6e88b8a8190f09dceec2aa65b35/packages/rocketchat-lib/lib/getValidRoomName.js#L16

When enable `UI_Allow_room_names_with_special_chars`, and set a Chinese name like `中文名`, `s.slugify('中文名') === ''`, then slugifiedName became blank string`''`

So, anywhere assign `name` by  `RocketChat.getValidRoomName` will give a blank string, and can be saved to DB without any validation warning.

Than in the UI side, the room list in the left slider, this room have a bad url: "/channel", the page(Desktop) show 404 error.

**Comment by ura14h** [comment]
@achilles-kosun. Great.

I have read the code you pointed out.
Certainly, it seems to be a problem of 'underscore.string'.

By the way, if "UI_Allow_room_names_with_special_chars" is set to false and "UTF8_Names_Validation" is specified as a regular expression permitting CJK characters, I feel that the method will work ...

**Comment by achilles-kosun** [comment]
@ura14h 
Yeah, it works. thanks for remind.

**Comment by 2efPer** [comment]
Where can I find room_names_with_special_chars option ?

**Comment by 564064202** [comment]
but how to resolve it?

**Comment by 564064202** [comment]
> @ura14h
> Yeah, it works. thanks for remind.

but how to resolve it?
