### ISSUE TITLE
 Heroku one-click deploy didn't work

### ISSUE THREAD

**Issue by rtarantelli** [RocketChat/Rocket.Chat#12588]
A lot of errors happens when I try to Heroku deploy, and crash during **Building Meteor** step. 

After 1 hour running it, timeout happens...

```
-----> Timed out running buildpack Node.js
 !     Timed out compiling app (60 minutes)
 !     See https://devcenter.heroku.com/articles/slug-compiler#time-limit 
```

Log file attached [log.txt](https://github.com/RocketChat/Rocket.Chat/files/2568847/log.txt)

**Comment by FriendlyUser** [comment]
I have the same issue :)

**Comment by MartinSchoeler** [comment]
Hey, looks like you seem to be looking for support. You will have a better chance of getting help if you go to one of the places listed in [here](https://rocket.chat/docs/getting-support/#community-support) since github is not the best place to ask for support. For now i will be closing this issue, as it does not fit our issue guidelines

**Comment by rtarantelli** [comment]
@MartinSchoeler, too bad the reply you gave to the issue that I opened has 18 days. If Github is not the best channel, should close to open new issues, not? In relation to not fit with the guideline, where is described this? Could you show me which document in this repository describes how and when I have to open an issue?
