### ISSUE TITLE
Help to Modify Channel

### ISSUE THREAD

**Issue by suarezkrac** [RocketChat/Rocket.Chat#12673]
HI, I need modify the architecture to Create a new Type of Channel. Do you have a class or entity to change the model? Because I review all documentation but don´t find a function to create other type of channels

**Comment by MartinSchoeler** [comment]
Hey, looks like you seem to be looking for support. You will have a better chance of getting help if you go to one of the places listed in [here](https://rocket.chat/docs/getting-support/#community-support) since github is not the best place to ask for support. For now i will be closing this issue, as it does not fit our issue guidelines
