### ISSUE TITLE
Rocket.Chat Windows Client doesn't include URL's Query String in automatically recognized Hyperlink

### ISSUE THREAD

**Issue by arminlinzbauer** [RocketChat/Rocket.Chat#12749]
### Description:

Rocket.Chat Windows Client doesn't include URL's Query String in automatically recognized Hyperlink. The part after the '?' isn't clickable and, ergo, the hyperlink doesn't point to the correct site.

### Steps to reproduce:

Send or receive message with URL containing a query string.

### Expected behavior:

Full URL is recognized and turned into hyperlink.

### Actual behavior:

![2018-11-28 14_28_58-clipboard](https://user-images.githubusercontent.com/22785446/49155009-2af1f780-f31a-11e8-83dd-bcb2db709e8c.png)

(The blue box is because I have added php to my hotwords list.)

### Additional context

Up-to-Date Windows 10 1803
RC 2.14.1

**Comment by arminlinzbauer** [comment]
@tassoevan Why is such a major (but probably quite easily fixable) UX issue not taken care of? Tell me where to look and I'll try fixing it myself and do a pull request. Since my work requires me to send and receive links very frequently, this makes the whole RC experience very unpleasant for me.

**Comment by tassoevan** [comment]
@arminlinzbauer Currently, Rocket.Chat runs a series of transformations to the message text (if I remember well, via `RocketChat.callbacks.run('renderMessage', message)`) that sometimes conflict with each other because they were supposed to run over HTML code; there are similar issues for Markdown, KaTeX etc. It's a hard technical debt to solve... Your specific issue is related to https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-highlight-words/client/client.js
