### ISSUE TITLE
have option to name and edit when upload

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#1279]
when we upload an image or any file, it would be a great idea to be able to rename it or put some comments, similar to Slack.. right now if we post a clip everything will be clipboard or audio
##

**Comment by IQ2022** [comment]
![capture](https://cloud.githubusercontent.com/assets/12454319/10803826/a78422d0-7d9a-11e5-93d1-2ab3642bfeed.PNG)

**Comment by emcguinness** [comment]
:+1: One I had been thinking myself, just not got around to posting it. One that I had been wanting to get around to seeing if I could fix this myself but gotten busy(that and I am horrible at code).

**Comment by gmsecrieru** [comment]
+1

**Comment by blaskovicz** [comment]
:+1:

**Comment by deviousgeek** [comment]
+1 so much.

**Comment by IQ2022** [comment]
also would be cool to have an option for ADMIN to click Delete or archive (Zip to download) or whatever to manage all those uploaded files

**Comment by snaiperskaya96** [comment]
Hello, i've honestly did not notice that the issue was closed since now ( Coming from https://www.bountysource.com/issues/27781984-have-option-to-name-and-edit-when-upload 😛  ) perhaps I developed a solution to add a description (and to alter the name) of an uploaded file.

If you want to have a look check it out here https://github.com/snaiperskaya96/Rocket.Chat/tree/Add-upload-file-description 
otherwise just never mind

**Comment by snaiperskaya96** [comment]
A few examples:
![screen shot 2017-01-10 at 10 31 01 am](https://cloud.githubusercontent.com/assets/5279281/21802994/f43000f6-d71f-11e6-8586-a9c11092d4e1.png)
![screen shot 2017-01-10 at 10 31 09 am](https://cloud.githubusercontent.com/assets/5279281/21802998/f663240c-d71f-11e6-9ab3-64ab31d3ff07.png)
