### ISSUE TITLE
Update 0.71.2 to 0.72.2 stops working

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat#12907]
I upgraded from 0.71.1 to 0.71.2 (using tar archive) which worked quiet well. Then I tried to update to 0.72.2, but when trying to run RC, there is no output on the console like normal (even when starting with export + direct command instead of using systemd).

**Comment by zenjabba** [comment]
I had a database upgrade fail on 0.72.2 so had to revert back to 0.71.2

**Comment by ohmonster** [comment]
Have you checked the logfile itself? For example, I use Ubuntu, and snagged the default values when creating my .service files for systemd, so rocketchat is logging to syslog (/var/log/syslog).

you can also ask systemd for status after a start/stop, though it will tail an arbitrary number of lines from the log. Could be too much or too little.

**Comment by zenjabba** [comment]
The error I got was unable to find `migration 136` and then "blam"

**Comment by tarator** [comment]
@zenjabba I had the same problem. Do you use the Docker image? Then this might have been your problem: https://github.com/RocketChat/Rocket.Chat/issues/12919

I used the `latest`-tag on the docker container which fetched the version `0.70.5` instead of `0.72.2`.
I reimported a backup of mongo db and don't use concrete version in my `docker-compose.yml` now instead of the `latest` tag.

**Comment by MartinSchoeler** [comment]
Please move this topic to https://forums.rocket.chat/ as there could be various variables on how the server was installed that could cause a issue.

If after some debugging you find out this issue is being caused by a bug, please reopen this and add information following our [Issue Guidelines](https://rocket.chat/docs/contributing/reporting-issues/)

Thanks!
