### ISSUE TITLE
Can't start MongoDB

### ISSUE THREAD

**Issue by dpunk3** [RocketChat/Rocket.Chat#12987]
I am running Ubuntu 14.04 LTS on a VM and trying to install Rocket.Chat. I have gotten to the last point where I need to run the MongoDB service through systemctl and every time I get a "Failed to issue method call: No such file or directory". 

I am really new to all this so after troubleshooting for 5+ hours I've turned up pretty much nothing. Thought maybe someone here could help?

**Comment by reetp** [comment]
This is most likely a support issue rather than bug in Rocketchat. 

You haven't really provided enough information either. No details on installation type, logs, what you have done, guides you have followed etc.

Please ask in the forums https://forums.rocket.chat/ or in the chat here https://open.rocket.chat/channel/support

Read this first:
http://rocketchat.github.io/docs/contributing/reporting-issues/

And this is a template to follow when reporting things (and that applies in the forums or chat)
https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

Thanks

**Comment by reetp** [comment]
@rocket-cat close

Please reopen or create a new issue if you actually find a bug.
