### ISSUE TITLE
No emoji autocomplete should happen if you have emojis disabled

### ISSUE THREAD

**Issue by mitar** [RocketChat/Rocket.Chat#1318]
Even with emojis disabled for my account, there is still emoji autocomplete which is opened. Which makes it sometimes complicated because it selects some other emoji you didn't want, and also adds an extra space.
##

**Comment by gwillen** [comment]
Yeah, totally agree; also, the fact that autocomplete sometimes selects the wrong emoji seems to be a race condition bug of some kind, which I'm going to report if there's no report already open for it.

**Comment by mitar** [comment]
Yea, the wrong emoji thing is really annoying.

**Comment by gwillen** [comment]
Actually, I realized the most annoying thing about this issue: When something autocompletes at the end of a line, pressing <ENTER> completes it instead of sending the message. That's horribly annoying because I often end my messages with emoji and I never want to autocomplete them.

(If I type some :fancy-emoji:, I probably _do_ want to autocomplete and emojify it, but never if I type an ordinary emoticon like :-). So probably they should be controlled separately.)

**Comment by SeanPackham** [comment]
Closing issue, emojis can't be disabled in more recent versions of Rocket.Chat.

**Comment by vitamindck** [comment]
This is still a huge problem and should be fixed.

Any time I end a message with :P (which, in my era means "silly face") it sends two dudes kissing to the recipient, and in most cases that's my boss.

![image](https://github.com/RocketChat/Rocket.Chat/assets/10766587/b8cf3acc-a04c-4196-bdca-aef612981709)
![image](https://github.com/RocketChat/Rocket.Chat/assets/10766587/e65eddcb-5b31-4943-a388-e6d2c67a2610)
