### ISSUE TITLE
Bounties? Needed? Wanted?

### ISSUE THREAD

**Issue by neurobe** [RocketChat/Rocket.Chat#1336]
I guess if users want features implemented that is specific to their special needs, the Core team can always be DMed and negotiations entered into. But separately, when it comes to prioritorising the agreed work plan, is there a role for bounties?  Views?

[The current alternative for bumping issues seems to be harassing tactics on the General channel.]

**Comment by capensisma** [comment]
I agree with you, this seems to be a good idea to solved the increasing number of feature requests :)

**Comment by garg** [comment]
I've love to contribute towards a bounty for an active ticket that is in the planned list but not in-progress just yet. Would posting something on bountysource be acceptable? Any feedback from the core-team about this?

**Comment by geekgonecrazy** [comment]
@RocketChat/core guys thoughts?

**Comment by engelgabriel** [comment]
I've created https://www.bountysource.com/teams/rocketchat

We need to start promoting it...

**Comment by geekgonecrazy** [comment]
Is this decided on I guess?  Was just looking around, doesn't look like that particular site is all that active.

Also is this a good fit for our community?  Will this ruin some of the hard work some of us put in when someone comes in and snipes the bounty with a hacky little fix?

Just thoughts.  Really wanted to make sure its a good fit for our community.

**Comment by garg** [comment]
I created a bounty but I set it so that it donates to the project even if the ticket does not get solved. I read the bountysource [FAQ](https://github.com/bountysource/core/wiki/Frequently-Asked-Questions) and it seems like we're protected against hacky little fixes because the bounty is not released until it is approved by the backer. And hopefully all backers will be diligent and wait for the fixes to be properly approved and merged.

The one question I still have is what happens when there are multiple developers working to fix the bug/issue. How does the bounty get divided between them?

**Comment by Sing-Li** [comment]
I have some very strong opinion [not unusual :-)  ] on bounties.

History and raw stats suggest that they don't  work in conjunction with open source.   And it might actually backfire and undermine the 'spirit' of a growing strong open source community.  

It can also have negative impact on possible customization and contract opportunities, moral of paid staff; and even deter well-intentioned 'pure open source spirited' contributors.

Some case in point - a bug on a familiar tool that still plague us today after 13 YEARS on bountysource:

https://www.bountysource.com/issues/1335023-wishing-for-history-brush

(perhaps because of low bounty value?  perhaps OS devs just felt down right insulted)

And another one with more bounty on a famous OS project that just sat and sat... (there are MANY MANY others if you search)...

https://www.bountysource.com/issues/5393282-double-split-view-of-the-same-file

The overall picture is not bright... Googling reveals ZERO open-source bounty success stories ..zilch!  And bountysource's own stats, AFTER FIFTEEN YEARS of operations, speaks for itself:

https://www.bountysource.com/stats

Why is this?   Who knows... perhaps this is actually true:

https://www.youtube.com/watch?v=u6XAPnuFjJc

I think we should re-consider.

JMHO.

**Comment by neurobe** [comment]
Example...
I want a functioning mid-tier Role ("moderator"). Most of the code is done (i think about 80%, mostly just needs a UI and testing). My choice is to wait for it to happen sometime or to hack around a solution that would probably work but because I am an amateur the code I generate would not be fit for public consumption. But they are the two choices I have at this point.

**Comment by neurobe** [comment]
oh... 
choice number 3: harass and harass on the General channel :-)

**Comment by garg** [comment]
I do understand the concerns about introducing this method of contributing to rocketchat. Regarding gimp:history brush - the issue was created 13 years but the $30 dollar bounty was set 2 years ago. Re:  gedit - issue was created 11 years ago but bounty was set 1 year ago. It's a bountysource UI problem which does make it seem like the bounty was created 13 years ago but that's not really the case. 

I humbly respect the concerns - I personally think that this should just be considered just another form of contributing to RC. If it is determined that we don't want to go this route, I will gladly just change my bounty to a donation to RC. In my case, I don't expect the issue I care about to be expedited in a significant way at all. I guess it's a way for me to vote for it.  Cheers :)

**Comment by capensisma** [comment]
@neurobe Right :D hahahha

Wanna help me? it would be remunerated!

**Comment by Sing-Li** [comment]
Actually, IBM is a great example of what might 'work' -  basically, a customization/contracting job that would cost $100k in-house; with similar cost  for professional external contractors - but bounty'd for $7k.

In the same vein, the ENTIRE Rocket.Chat team have regular day-job work to support their passion and accepts contracting ops - and we are really only a PM away - if all you really want is to pay for a feature to be implemented ahead of others.    Many have already gone this route.

**Comment by neurobe** [comment]
@Sing-Li  In the original posting on this issue I did mention the DM option which is recommended for Coding for a client specific use.

Maybe the question as to whether Bounties is _wanted_ or not has been answered in the negative. Still a question though in my mind whether they are _needed_. I think though, a minimum bounty of say $250 is a good idea. The system setup seems to allow a minimum of $5. (It does also allow donates though.

So there are now two bounties posted, both for $250.
Mine is for a UI to the alanning:roles code already baked in to RC, under issue #1063, Roles and Permissions.

I would encourage all to go to 
https://www.bountysource.com/teams/rocketchat ,
go through the issues and up-vote the issues of importance to you. This too is needed imo.

**Comment by engelgabriel** [comment]
OK, maybe it looks like it was premature to create the team there without a proper discussion with the team here, but I've actually did that back in September, and I didn't even create the team myself, someone had already done that in October and I just claimed ownership. I found out about it when I was studying the idea after a few requests for that.

I agree with @Sing-Li in a few points, but not all:

1. Why do you say "AFTER FIFTEEN YEARS of operations" if they started just TWO years ago?

2. I know of a few success cases, like:
http://robomongo.org/backlog
https://www.mozilla.org/en-US/security/bug-bounty/
https://wiki.mozilla.org/MOSS

3. The negative impact on possible customization and contract opportunities should be small, as the bounties are aimed at small bug fixes, and not major features and customizations.

4. Low bounty value should not insult anyone. It is just what the specific person/org is willing to contribute to get something done. It's not what they think the work is worth... it is more like a donation/vote for a cause they care about.

5. We won't accept hacky little fixes.

6. I don't believe this can undermine the 'spirit' of a growing strong open source community. This is just another channel for contribution. Developers can easily work on what features they care about, but non developers have a hard time getting involved. This is a way for them to contribute not just for the project in general, but for the features that they care about.

I also really wanted to make sure it's a good fit for our community, but the best way to do so, seems to be testing it for some time. Data will speak louder than conjectures :)

Let's open for votes/comments?

**Comment by capensisma** [comment]
I agree with @engelgabriel :D about everything he said

I vote YES for bounties!

**Comment by Sing-Li** [comment]
@engelgabriel 

1.  our mods crossed - I was just updating the facts per @garg's post - as you were composing your piece

Absolutely - let's test it for some time.

**Comment by engelgabriel** [comment]
Sounds like a plan.

**Comment by marceloschmidt** [comment]
I'm not 100% confident about the bounty-program. I think what could happen is that instead of working on things we think are more important, some collaborators might start working on things that pay more. Instead, I would like to see some work done in this direction: http://rfc.zeromq.org/spec:22 and defining each collaborator's participation in the project.

**Comment by engelgabriel** [comment]
@marceloschmidt the two things are unrelated. Collaborator's participation in the project is a *long term* commitment with much stricter rules. Bounties are just another channel for *short term* contribution from non developers. The team seems to be both worried about too much bounty and too little bounty at the same time. Let's the data show us.

We already have developers submitting PRs to fix issues or create features that we would not have prioritised ourselves, but is what they or their employers care about.

This is just the same... sure there will be people working on bugs or issues we don't think should be a priority, but that's already the case, and that's the beauty of free open source software.

We will still organize what the core team works on, so there is no change.

**Comment by neurobe** [comment]
Bounties might also drive people away from an issue for fear of being seen as mercenary - a traitor to the cause. Those individuals can always donate the money to the project's consolidated revenue fund.

@marceloschmidt  if Issues are scrutinised by the core team before Feature Request or Bug Report tags get applied - scrutinised for consistency with project direction - then your concerns are addressed. If the Feature is adjudged as too parochial, then the Issuer can be advised to DM a core team member to progress the particular feature outside the open source arena.

Currently, there are a few issues left dangling, such as Roles and Pinning Messages, that might usefully have Bounties applied to get the work finished. I have placed a bounty on the former. 

Lastly, by way of full disclosure, I intend to place a bounty on new feature request "Calendar" if the team agreed to grant it a Feature Request tag. I need to have satisfied you that that feature is of wide applicability (even tho the Calendar idea was not progressed when considered 6 months ago) .

**Comment by engelgabriel** [comment]
@neurobe are you refering to https://github.com/RocketChat/Rocket.Chat/issues/1366?
I am OK with it, if it will be done via an optional package, at least until it gets stable and well understood. It is definitely a nice to have, but not the focus of our core team, so a bounty may help you getting that done. 

Alternatively, when people really need something done, they can contact me and get a quote for the work directly.

I'll close the issue and let's monitor how things evolve.
