### ISSUE TITLE
Unsolicited email invitation to join Rocket.Chat Cloud

### ISSUE THREAD

**Issue by GJKrupa** [RocketChat/Rocket.Chat#13543]
### Description:

I received an unsolicited email to the address of the admin account on my self-hosted instance, inviting me to register the instance with Rocket.Chat Cloud.

### Steps to reproduce:

1. Install a self-hosted instance
2. Do not configure an SMTP server
3. Add an admin user with a valid email address

### Expected behavior:

No emails are received relating to the instance

### Actual behavior:

An email is sent to the admin account with the following content:

```
From: Rocket.Chat Cloud <cloud AT rocket.chat>
Date: Fri, 22 Feb 2019 01:41:01 +0000
Subject: Rocket.Chat Register Workspace

Welcome aboard!
Your workspace: ADDRESS:PORT is ready to be registered!
By registering your workspace with Rocket.Chat Cloud, you will be able to use:

Mobile push notification gateway
Livechat omnichannel proxy
OAuth proxy for social network
Apps Marketplace
Click here to finish registering your workspace!
If this clicking the link does not work:

Navigate to Administration section of your workspace
Click Cloud
Paste this token: GUID in the token field
Click Connect
If you still have issues registering, please contact: support@rocket.chat
```

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.2
- Operating System: Ubuntu 16.04
- Deployment Method: Docker Compose
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.3
- MongoDB Version: 

### Additional context

No unsubscribe link or method was provided in the email.
https://rocket.chat/2018/05/20/gdpr/

### Relevant logs:

N/A

**Comment by bkraul** [comment]
I received this unsolicited email as well:
![image](https://user-images.githubusercontent.com/14616851/53309957-482e5780-3870-11e9-9ea9-ab24ed28bff4.png)
 What's up with this?

**Comment by geekgonecrazy** [comment]
The missing of the unsubscribe link is an oversight.

This email how ever is sent as a result of the option chosen at the setup of Rocket.Chat where you choose to either register your server and be able to use the push gateway and the other options listed in the email or the option to configure your self.

So I would argue not entirely unsolicited.  For a while we did not send these because the registration system wasn’t finished.  

If you choose not to register.. no follow up emails will be sent if you did not check the marketing email box during setup.  Marketing emails 100% for sure will have unsubscribe link.

I will definitely add a link to unsubscribe.

---

Note not subscribing your push notifications if using our official apps will stop working in coming months.

**Comment by bkraul** [comment]
@geekgonecrazy Thanks for the explanation. I'd disagree with the unsolicited, because as you are saying, if the registration system was not finished, no email would have been sent when setting up the server. I set up my server months ago, so therefore receiving the email out of the blue was unexpected (thus unsolicited). 

Honestly the first thing I thought of was "great so is this going to be one of those deals where I can no longer use my Rocketchat instance unless I connect to their systems?". I hope that helps with understanding why this seemed like an issue.

**Comment by bkraul** [comment]
@geekgonecrazy So, from what I understand from your message is that if we want to continue to use push notifications we have to register to rocket.chat cloud? Are you guys going to start charging for use of the push notification gateway? Also, how do I register if I no longer have the registration email? Can't seem to be able to do so. The interface does not have a way to have the email re-sent.

**Comment by geekgonecrazy** [comment]
This forum post might be best way to continue regarding push notifications: https://forums.rocket.chat/t/push-notification-gateway-pricing/3044

For the register email we are going to add the ability to request it again and a few other things.  But currently will have to shoot an email to support@rocket.chat or shoot me an email [myfirst.lastname]@rocket.chat or aaron.ogle on open.rocket.chat

**Comment by geekgonecrazy** [comment]
Going to go ahead and close.  If any others come across this and have more questions please feel free to contact

**Comment by immanuelfodor** [comment]
This is the current data flow as I see:
`Button click in RC settings -> Payload 1 to rocket.chat -> Email sent with token -> Token entered in RC settings -> Unknown action/payload on save -> Unknown Payload 2-N to rocket.chat on push/app install`
My questions:
- What data leaves the server in Payload 1?
- What happens when the token is saved (action/payload)?
- How is the token later used on e.g. push notifications, app installs from Marketplace, etc?
- If the token is not saved, when will the push service stop working?
- Is there any way to install a free app manually bypassing the marketplace (and so the token)?

**Comment by geekgonecrazy** [comment]
1. The wizard info you choose to register
2. Wizard is finished and wizard info is sent to register
3. Email sent with token to finish register
4.  Rc passes token and gets back client id and secret
5. It uses those to get an access token that it passes to any cloud service you communicate with.  This allows you access.  Example push gateway, market play, federation hub, Omni, etc

**Comment by immanuelfodor** [comment]
Thank you for the explanation!
Could you point me in the right direction for sideloading apps? I could not come up with it how to do it, are there any docs on it?
