### ISSUE TITLE
Domain whitelist not restricting

### ISSUE THREAD

**Issue by intositeme** [RocketChat/Rocket.Chat#1360]
The allowed domains is not restricting registration with emails not in the list.

**Comment by geekgonecrazy** [comment]
@RocketChat/core are there caveats to this?  Does it need restarted before it takes effect?

**Comment by intositeme** [comment]
tried restarting the containers but did not help.

**Comment by geekgonecrazy** [comment]
@intositeme I responded on the PR #1053

But you restart using what ever name you gave the container when starting it.  If you don't know what it is do: `docker ps`  
Find the name by the one that is using the rocketchat/rocket.chat image.   Then do: `docker stop {container_name}` and `docker start {container_name}`

This may not be an issue where restart is needed.  But I know some are.  That's why I asked all core devs about caveats.  I'm not aware of any.  But that was my first guess.

**Comment by cdomergue** [comment]
Hello; it still don't working after many reboots.

**Comment by internalfx** [comment]
Noticed the same issue...

**Comment by geekgonecrazy** [comment]
So it looks like this throws an internal server error.  But it creates the account anyways.
