### ISSUE TITLE
UI for Mandatory 2FA broke

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#13645]
### Description:

![image](https://user-images.githubusercontent.com/51996/54034584-da8dff80-417c-11e9-9990-3375475ad5cf.png)

### Steps to reproduce:

1. Force 2FA
2. Login with a user on web that doesn't have 2FA
3. Cringe

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0 - beta 0

**Comment by fliptrail** [comment]
I am working on it.

**Comment by fliptrail** [comment]
![Screenshot from 2019-03-09 02-38-02](https://user-images.githubusercontent.com/40834245/54055934-8a627c00-4214-11e9-920e-9fe80e3b64d7.png)
![Screenshot from 2019-03-09 02-38-50](https://user-images.githubusercontent.com/40834245/54055935-8a627c00-4214-11e9-86a4-99f967d7f09b.png)
This error arises because these two pages use the same CSS styling
