### ISSUE TITLE
Discussion Deletion

### ISSUE THREAD

**Issue by reetp** [RocketChat/Rocket.Chat#13689]
1.0.0-develop-beta.1

1. Create Discussion

2. Delete Discussion. 
- Discussion still appears in channel/Discussion. 
- 'No replies' shows under original comment. 
- Clicking No Replies shows 'Not Allowed'

3. Cannot appear to rename discussion after creation

Related:
https://github.com/RocketChat/Rocket.Chat/issues/13664
https://github.com/RocketChat/Rocket.Chat/pull/13541

**Comment by reetp** [comment]
Curiously I can see the room creation in the logs, but nothing for deletion.

And no idea how to remove the lingering thread artefacts either.

**Comment by engelgabriel** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/13644

**Comment by itsarectangle** [comment]
I find myself running into a wall with regards to getting rid of Discussions in the left sidebar.  I can't leave them because I'm the last owner.  How can I get rid of them?  Thanks

**Comment by itsarectangle** [comment]
Checking in again, wondering how I can keep a tidy left sidebar, by deleting Discussions that are no longer being discussed.  This is borderline dealbreaker for our use case.  Are Discussions designed to live forever?  Will the left sidebar continue to fill up with new Discussions because nobody knows who to assign as another owner for a discussion that's finished.  Thanks
