### ISSUE TITLE
[sandstorm] Desktop notifications are not shown, even when @-mentioned or DM'd

### ISSUE THREAD

**Issue by zarvox** [RocketChat/Rocket.Chat#1374]
To reproduce:

* Run RocketChat under Sandstorm (both the app market version 0.6 and current git master appear to have this issue)
* User is prompted to grant the browser permission to show desktop notifications.  User clicks allow.
* No desktop notifications are ever shown, even when user is @-mentioned or sent a DM.

This appears to be specific to RocketChat under Sandstorm in some way; I do receive desktop notifications when running RocketChat with `meteor run` and on https://demo.rocket.chat

There's a related Sandstorm feature request motivating this https://github.com/sandstorm-io/sandstorm/issues/919 that I'm hoping will make desktop notifications and permissions smoother under Sandstorm, but since RC isn't even trying to show notifications for whatever reason, I can't test that the integration I've written works when minified and concated and so on, which I'd like to do before throwing up a PR.

**Comment by rophy** [comment]
I can confirm that latest rocket.chat from master failed to show notification in the following 2 deployment scenarios:

1. docker
2. IBM bluemix

**Comment by zarvox** [comment]
@jparyani do you mind writing down what you found when you were looking into this issue some days ago?  I vaguely remember you saying it had to do with the meteor-streams package being buggy, and that that package appears to be unmaintained?

**Comment by jparyani** [comment]
I think there's multiple problems preventing notifications from working correctly in Sandstorm, but the major one is due to https://github.com/arunoda/meteor-streams/issues/39. Essentially, you have to refresh the page to workaround this meteor-streams bug, and it's nearly impossible to refresh a Sandstorm grain without also changing it's domain and starting fresh, re-triggering the bug in the process. In my experience, it also seems to randomly fix itself after 5-10 minutes of the app being up.

**Comment by engelgabriel** [comment]
@rodrigok any ideas?

**Comment by neynah** [comment]
Hi @engelgabriel, this is definitely an issue that causes a lot of discomfort with Oasis users (including the Sandstorm team) using Rocket.Chat. Has there been any progress on finding a solution to this issue? We'd love to cooperate to try and get this fixed ASAP. :smile:

**Comment by engelgabriel** [comment]
This is a major problem, even for the mobile apps to work. Is there a way to get a static URL for an app+user combination at all?

**Comment by kentonv** [comment]
@engelgabriel No, it is an important part of our security model that the hosts change for every session. To avoid prompting the user for permission on every load, we'll need some support on the Sandstorm side, which we do plan to add.

However, the current bug is bigger than that. Currently, even if the user accepts notifications every time they open rocket.chat on Sandstorm, they still never get any notifications.

As Jason points out, it appears to be a bug in a package, but refreshing the app works around the problem. Perhaps a work-around, then, would be to automatically refresh Rocket.Chat immediately after the user accepts notifications? It would be ugly, but would get the job done.

**Comment by kentonv** [comment]
Better yet, if the bug is in meteor-streams, maybe it would work to delay initializing meteor-streams until notifications have been accepted and the user has fully logged in (I have a theory that part of the problem is setting up the collection observer before login, but I'm not sure). This seems like it should be an easy change?

**Comment by kentonv** [comment]
Unfortunately I'm finding I still don't get notifications, and now I don't even get them after refreshing the frame. @jparyani reports sometimes seeing notifications on the first try, though sometimes not.

**Comment by engelgabriel** [comment]
Can you invite me to the grain where you are testing it?

**Comment by kentonv** [comment]
@engelgabriel https://oasis.sandstorm.io/shared/Q5VlbuCM74Sd3huczpVccPS-F3qJir6vX5bKQtetMoH

**Comment by engelgabriel** [comment]
Uncaught SecurityError: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

**Comment by engelgabriel** [comment]
Also need to look into https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-ui/lib/notification.coffee#L16

**Comment by kentonv** [comment]
The problem is that Same-Origin Policy rules state that you normally aren't allowed to read back images from other domains. You can embed those images in your site, but you cannot read the pixels from Javascript. HTML5 canvas extends this rule by saying that if you render an off-site image into a `<canvas>` tag, then you are no longer allowed to read back the content of the canvas.

It looks like `getAvatarAsPng` tries to render the avatar into a canvas in order to produce a PNG for a data URL. But since Sandstorm avatars come from a separate domain, this is not allowed.

First question: Why convert to a PNG data URL at all? Can't you use the original avatar URL here? I don't see any documentation online claiming that `Notification.icon` needs to be a data URL nor a PNG. I think you can pass the original avatar URL for the icon and skip the whole `getAvatarAsPng` call.

But if it truly needs to be a data URL or a PNG for some reason, what you'd need to do is download the file via XHR (which is allowed, because we enable CORS on avatars), and then create a data URL from that by base64'ing it (no need for the canvas). But I think this won't be necessary because I think notification icons don't need to be data URLs.

**Comment by rodrigok** [comment]
@kentonv we do that because if you don't have avatars we return a SVG containing your initials and some systems don't support SVG as icon for notifications.

**Comment by kentonv** [comment]
@rodrigok: Ah hah. Hmm. In that case, it seems like the solution is to use the canvas trick only in the case that the user doesn't have a sandstorm-assigned avatar. Sandstorm-assigned avatars are never SVGs (IIRC) so won't require the trick.

**Comment by engelgabriel** [comment]
NOt sure how hard/easy would be to convert our SVG generated initial to PNG on the server side to avoid this at all.

**Comment by engelgabriel** [comment]
http://eng.wealthfront.com/2011/12/22/converting-dynamic-svg-to-png-with-node-js-d3-and-imagemagick/

**Comment by kentonv** [comment]
Looks like this is fixed (yay!). FWIW I also just discovered that there is a way to make cross-origin images not taint the canvas provided that the image server is CORS-enabled (which Sandstorm's is):

https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image

But not useful now.

**Comment by kentonv** [comment]
Can we get a release with this fix?

**Comment by engelgabriel** [comment]
@kentonv Is it not working on the current version at Sandstorm?

**Comment by kentonv** [comment]
@engelgabriel You pushed a release a few days ago, so yes, it works now. :)
