### ISSUE TITLE
[BUG] Show Setup Wizard Setting can lock users outside the server

### ISSUE THREAD

**Issue by MartinSchoeler** [RocketChat/Rocket.Chat#13840]
### Description:

If you change the setting `Show Setup Wizard` to `pending`, every user that tries to log in the server, will see the first page of the setup wizard. Since there is already admin users, the first page of the setup wizard will throw an error, locking out any user that needs to log in. If the last admin logs out, the server will be piratically locked down and it will need to be restarted with the appropriate ENV_VARS to undo the setting.

### Steps to reproduce:

1. Set Show Setup Wizard to `pending`;
2. Log out;
3. Go to your server url.
4. Profit!

### Expected behavior:

Admins should not be able to change that setting. I suggest hiding it and only allow changes from ENV_VARS.

### Actual behavior:

Admins can lock down the server with the click of 2 buttons.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.0-develop
- Operating System: MacOS
- Deployment Method: Using Localhost

**Comment by geekgonecrazy** [comment]
To quote uncle ben:

> With great power comes great responsibility

Should we not just wack a wontfix?  Or add a description under it?  I remember most php apps where if a install.php file existed this type of thing happened and it was kinda up to the admin to make sure this didn't happen.  If it showed up the app assumed it was intentional.

Kinda feel like the same sort of thing here.  

Unless we truly don't want them to go back through the wizard and instead change the values in the admin UI.

**Comment by ggazzo** [comment]
closed by #15623
