### ISSUE TITLE
Outdated Dependencies present in project !

### ISSUE THREAD

**Issue by sudipt1999** [RocketChat/Rocket.Chat#13866]
<pre><u style="text-decoration-style:single">Package</u>                     <u style="text-decoration-style:single">Current</u>   <u style="text-decoration-style:single">Wanted</u>   <u style="text-decoration-style:single">Latest</u>  <u style="text-decoration-style:single">Location</u>
<font color="#C4A000">@accounts/graphql-api</font>         0.2.3    <font color="#4E9A06">0.2.3</font>   <font color="#75507B">0.13.0</font>  Rocket.Chat
<font color="#C4A000">@accounts/mongo</font>              0.0.12   <font color="#4E9A06">0.0.12</font>   <font color="#75507B">0.13.0</font>  Rocket.Chat
<font color="#C4A000">@accounts/server</font>             0.0.18   <font color="#4E9A06">0.0.18</font>   <font color="#75507B">0.13.0</font>  Rocket.Chat
<font color="#CC0000">@babel/runtime</font>                7.2.0    <font color="#4E9A06">7.4.2</font>    <font color="#75507B">7.4.2</font>  Rocket.Chat
<font color="#CC0000">@google-cloud/language</font>        2.0.0    <font color="#4E9A06">2.1.0</font>    <font color="#75507B">2.1.0</font>  Rocket.Chat
<font color="#CC0000">@google-cloud/storage</font>         2.3.1    <font color="#4E9A06">2.4.3</font>    <font color="#75507B">2.4.3</font>  Rocket.Chat
<font color="#C4A000">@google-cloud/vision</font>         0.23.0   <font color="#4E9A06">0.23.0</font>   <font color="#75507B">0.25.0</font>  Rocket.Chat
<font color="#CC0000">@octokit/rest</font>                16.1.0  <font color="#4E9A06">16.20.0</font>  <font color="#75507B">16.20.0</font>  Rocket.Chat
<font color="#CC0000">@slack/client</font>                 4.8.0   <font color="#4E9A06">4.12.0</font>   <font color="#75507B">4.12.0</font>  Rocket.Chat
<font color="#CC0000">acorn</font>                         6.0.7    <font color="#4E9A06">6.1.1</font>    <font color="#75507B">6.1.1</font>  Rocket.Chat
<font color="#CC0000">apollo-server-express</font>         1.3.6    <font color="#4E9A06">1.4.0</font>    <font color="#75507B">2.4.8</font>  Rocket.Chat
<font color="#CC0000">autolinker</font>                    1.8.1    <font color="#4E9A06">1.8.3</font>    <font color="#75507B">3.0.5</font>  Rocket.Chat
<font color="#CC0000">autoprefixer</font>                  9.4.1    <font color="#4E9A06">9.5.0</font>    <font color="#75507B">9.5.0</font>  Rocket.Chat
<font color="#CC0000">aws-sdk</font>                     2.368.0  <font color="#4E9A06">2.427.0</font>  <font color="#75507B">2.427.0</font>  Rocket.Chat
<font color="#CC0000">bcrypt</font>                        3.0.2    <font color="#4E9A06">3.0.5</font>    <font color="#75507B">3.0.5</font>  Rocket.Chat
<font color="#C4A000">blockstack</font>                   18.1.0   <font color="#4E9A06">18.1.0</font>   <font color="#75507B">19.0.0</font>  Rocket.Chat
<font color="#CC0000">bson</font>                          4.0.0    <font color="#4E9A06">4.0.2</font>    <font color="#75507B">4.0.2</font>  Rocket.Chat
<font color="#C4A000">busboy</font>                       0.2.14   <font color="#4E9A06">0.2.14</font>    <font color="#75507B">0.3.0</font>  Rocket.Chat
<font color="#C4A000">chai</font>                          3.5.0    <font color="#4E9A06">3.5.0</font>    <font color="#75507B">4.2.0</font>  Rocket.Chat
<font color="#CC0000">chart.js</font>                      2.7.3    <font color="#4E9A06">2.8.0</font>    <font color="#75507B">2.8.0</font>  Rocket.Chat
<font color="#CC0000">codemirror</font>                   5.42.0   <font color="#4E9A06">5.45.0</font>   <font color="#75507B">5.45.0</font>  Rocket.Chat
<font color="#CC0000">core-js</font>                       2.5.7    <font color="#4E9A06">2.6.5</font>    <font color="#75507B">3.0.0</font>  Rocket.Chat
<font color="#CC0000">cors</font>                          2.8.4    <font color="#4E9A06">2.8.5</font>    <font color="#75507B">2.8.5</font>  Rocket.Chat
<font color="#CC0000">csv-parse</font>                     4.0.1    <font color="#4E9A06">4.3.4</font>    <font color="#75507B">4.3.4</font>  Rocket.Chat
<font color="#CC0000">eslint</font>                        5.9.0   <font color="#4E9A06">5.15.3</font>   <font color="#75507B">5.15.3</font>  Rocket.Chat
<font color="#CC0000">express-session</font>              1.15.4   <font color="#4E9A06">1.15.6</font>   <font color="#75507B">1.15.6</font>  Rocket.Chat
<font color="#CC0000">file-type</font>                    10.6.0   <font color="#4E9A06">10.9.0</font>   <font color="#75507B">10.9.0</font>  Rocket.Chat
<font color="#C4A000">filesize</font>                      3.6.1    <font color="#4E9A06">3.6.1</font>    <font color="#75507B">4.1.2</font>  Rocket.Chat
<font color="#C4A000">googleapis</font>                   25.0.0   <font color="#4E9A06">25.0.0</font>   <font color="#75507B">38.0.0</font>  Rocket.Chat
<font color="#CC0000">grant-express</font>                 3.8.0    <font color="#4E9A06">3.8.2</font>    <font color="#75507B">4.5.0</font>  Rocket.Chat
<font color="#C4A000">graphql</font>                      0.13.2   <font color="#4E9A06">0.13.2</font>   <font color="#75507B">14.1.1</font>  Rocket.Chat
<font color="#C4A000">graphql-subscriptions</font>         0.5.8    <font color="#4E9A06">0.5.8</font>    <font color="#75507B">1.0.0</font>  Rocket.Chat
<font color="#CC0000">graphql-tools</font>                 3.0.2    <font color="#4E9A06">3.1.1</font>    <font color="#75507B">4.0.4</font>  Rocket.Chat
<font color="#CC0000">highlight.js</font>                 9.13.1   <font color="#4E9A06">9.15.6</font>   <font color="#75507B">9.15.6</font>  Rocket.Chat
<font color="#CC0000">husky</font>                         1.2.0    <font color="#4E9A06">1.3.1</font>    <font color="#75507B">1.3.1</font>  Rocket.Chat
<font color="#C4A000">image-size</font>                    0.6.3    <font color="#4E9A06">0.6.3</font>    <font color="#75507B">0.7.2</font>  Rocket.Chat
<font color="#C4A000">jschardet</font>                     1.6.0    <font color="#4E9A06">1.6.0</font>    <font color="#75507B">2.1.0</font>  Rocket.Chat
<font color="#CC0000">juice</font>                         5.0.1    <font color="#4E9A06">5.2.0</font>    <font color="#75507B">5.2.0</font>  Rocket.Chat
<font color="#C4A000">katex</font>                         0.9.0    <font color="#4E9A06">0.9.0</font>   <font color="#75507B">0.10.1</font>  Rocket.Chat
<font color="#CC0000">lokijs</font>                        1.5.5    <font color="#4E9A06">1.5.6</font>    <font color="#75507B">1.5.6</font>  Rocket.Chat
<font color="#CC0000">mailparser</font>                    2.4.3    <font color="#4E9A06">2.5.0</font>    <font color="#75507B">2.5.0</font>  Rocket.Chat
<font color="#C4A000">marked</font>                        0.5.2    <font color="#4E9A06">0.5.2</font>    <font color="#75507B">0.6.1</font>  Rocket.Chat
<font color="#C4A000">mem</font>                           4.1.0    <font color="#4E9A06">4.1.0</font>    <font color="#75507B">4.2.0</font>  Rocket.Chat
<font color="#CC0000">merge-graphql-schemas</font>         1.5.2    <font color="#4E9A06">1.5.8</font>    <font color="#75507B">1.5.8</font>  Rocket.Chat
<font color="#CC0000">mime-db</font>                      1.37.0   <font color="#4E9A06">1.38.0</font>   <font color="#75507B">1.38.0</font>  Rocket.Chat
<font color="#C4A000">mocha</font>                         5.2.0    <font color="#4E9A06">5.2.0</font>    <font color="#75507B">6.0.2</font>  Rocket.Chat
<font color="#CC0000">mock-require</font>                  3.0.2    <font color="#4E9A06">3.0.3</font>    <font color="#75507B">3.0.3</font>  Rocket.Chat
<font color="#CC0000">moment</font>                       2.22.2   <font color="#4E9A06">2.24.0</font>   <font color="#75507B">2.24.0</font>  Rocket.Chat
<font color="#CC0000">node-rsa</font>                      1.0.3    <font color="#4E9A06">1.0.5</font>    <font color="#75507B">1.0.5</font>  Rocket.Chat
<font color="#CC0000">photoswipe</font>                    4.1.2    <font color="#4E9A06">4.1.3</font>    <font color="#75507B">4.1.3</font>  Rocket.Chat
<font color="#CC0000">postcss</font>                       7.0.6   <font color="#4E9A06">7.0.14</font>   <font color="#75507B">7.0.14</font>  Rocket.Chat
<font color="#CC0000">postcss-nested</font>                4.1.0    <font color="#4E9A06">4.1.2</font>    <font color="#75507B">4.1.2</font>  Rocket.Chat
<font color="#CC0000">progress</font>                      2.0.2    <font color="#4E9A06">2.0.3</font>    <font color="#75507B">2.0.3</font>  Rocket.Chat
<font color="#CC0000">prom-client</font>                  11.2.0   <font color="#4E9A06">11.2.1</font>   <font color="#75507B">11.2.1</font>  Rocket.Chat
<font color="#C4A000">sharp</font>                        0.21.3   <font color="#4E9A06">0.21.3</font>   <font color="#75507B">0.22.0</font>  Rocket.Chat
<font color="#CC0000">simple-git</font>                  1.107.0  <font color="#4E9A06">1.109.0</font>  <font color="#75507B">1.109.0</font>  Rocket.Chat
<font color="#CC0000">stylelint</font>                     9.9.0   <font color="#4E9A06">9.10.1</font>   <font color="#75507B">9.10.1</font>  Rocket.Chat
<font color="#CC0000">stylelint-order</font>               2.0.0    <font color="#4E9A06">2.1.0</font>    <font color="#75507B">2.1.0</font>  Rocket.Chat
<font color="#CC0000">subscriptions-transport-ws</font>   0.9.11   <font color="#4E9A06">0.9.16</font>   <font color="#75507B">0.9.16</font>  Rocket.Chat
<font color="#CC0000">supertest</font>                     3.3.0    <font color="#4E9A06">3.4.2</font>    <font color="#75507B">4.0.2</font>  Rocket.Chat
<font color="#C4A000">tar-stream</font>                    1.6.2    <font color="#4E9A06">1.6.2</font>    <font color="#75507B">2.0.1</font>  Rocket.Chat
<font color="#CC0000">turndown</font>                      5.0.1    <font color="#4E9A06">5.0.3</font>    <font color="#75507B">5.0.3</font>  Rocket.Chat
<font color="#CC0000">twilio</font>                       3.25.0   <font color="#4E9A06">3.29.2</font>   <font color="#75507B">3.29.2</font>  Rocket.Chat
<font color="#CC0000">webdav</font>                        2.0.0    <font color="#4E9A06">2.6.0</font>    <font color="#75507B">2.6.0</font>  Rocket.Chat
<font color="#CC0000">webpack</font>                      4.29.3   <font color="#4E9A06">4.29.6</font>   <font color="#75507B">4.29.6</font>  Rocket.Chat
<font color="#CC0000">wolfy87-eventemitter</font>          5.2.5    <font color="#4E9A06">5.2.6</font>    <font color="#75507B">5.2.6</font>  Rocket.Chat
<font color="#CC0000">xml-crypto</font>                    1.0.2    <font color="#4E9A06">1.2.0</font>    <font color="#75507B">1.2.0</font>  Rocket.Chat
<font color="#C4A000">xmlbuilder</font>                   10.1.1   <font color="#4E9A06">10.1.1</font>   <font color="#75507B">11.0.1</font>  Rocket.Chat
</pre>

there are many dependencies in the project that are outdated or not being maintained any more ! Updating them would be great!

**Comment by fasttrackhost** [comment]
Great job recompilating the info. As I wrote in #13861 would be great to have Markdown upgraded, and other plugins that interpret and manipulate the elements in chat: text, images, sound, video, etc.

Integrations are great but since this is a Chat Server Software,  at least from our point of view, the most important integration is the ability to integrate RocketChat in other webs and the ability to communicate with RocketChat Server, to give each user a unique chat experience.
I have the feeling that there is a great effort to integrate IN RocketChat third-party software, and little effort to what a Chat Server should be, and that is, **a seamless integration of RocketChat in other webs**.

My humble opinion is that **is very time consuming to continuously adapt to third party software, and make corrections and update your own software every time the others update their own**. RocketChat has great potential and we consider it to be the best, is very useful (and we don't use any integrations besides API). If the integration of RocketChat in third-party software/webs is easy, maybe **others will waste time adapting to RocketChat** and there would be a great gain of time and resources.

We know CORS issues are hard to understand for most of Internet users, but if you make a good step-by-step tutorial and give the "hole code" needed for integrating RocketChat, many problems would end, and efforts could be driven to make RocketChat`s **Chat** system more advanced. 

Iframes are great, but giving the ability to integrate RocketChat without Iframes, for example using pure Javascript (like the LiveChat but a lot more configurable), would be a great step forward. Look for example how easy is to integrate Youtube Player in any web, and adapt it to to any needs. [Google Youtube API](https://developers.google.com/youtube/v3/docs/videos) for example lets you integrate Youtube page using [API](https://developers.google.com/youtube/v3/docs/) in any web, in many software languages, and lets you adapt it to your page needs 100%

And **RocketChat already has REST-API and REAL-TIME-API** but there are important drawbacks that make it hardly accessible for most users. CORS websocket communication with RocketChat server is buggy, and not easy to deploy. If RocketChat can be fast deployed in other webs with a fast learning curve, many would integrate it. 
Maybe one day RocketChat could be launched in any web just writing something like this:
```
playerApi = new YT.Player('ventana_reproductor_1', {
					height: '270',
					width: '480',
					videoId: video_id,
					playerVars: {controls: '0',
								fs: '1',
								enablejsapi: '1',
								listType: 'playlist',
								list: playList_id,
								loop: '1',
								origin: 'https://example.url',
								modestbranding: '1',
								autoplay: '1'
								},
					events: {
						'onReady': onPlayerReadyReproductor1,
						'onStateChange': onPlayerStateChangeReproductor1
					}
			});
```

You simply call a script, wait for confirmation that it has loaded, and then create: "new RC.Window". Script handles silently CORS and websocket and all the rest. Things that web developers don't need to worry about, could and can be done by a script of RocketChat.

As many Big Companies like Google and Facebook demonstrate every day, Free software can bring a lot of income to their owners. The only thing they offer to their users, is the ability to let each one of them focus in what they know best to do. Google grows because it gives to developers something useful, that can be integrated very very easy and 100% customizable. Developers take advantage of Google resources, a lot are for free (you have to be a big Company with a lot of traffic to need to pay for using Google services), and Google monetizes it a lot more than it could by directly putting a price to its services and software. Just saying that if RocketChat can be very easily integrated in other software / services /webs, there would be no need to make, develop and maintain many third party integrations inside RocketChat. A chat service is great if you can have it everywhere easily, you can write cool looking text, easy share of images, videos and sound. RocketChat does that and more, **but** it's trying to have everybody inside and it's not making a easy way to be inside everyone. Again just a opinión.

Was going to write just a few lines and ended up writing  all this. Big thanks to RocketChat team, great work, and big thanks to all the info from RocketChat users.

**Comment by sampaiodiego** [comment]
thx the effort. we're now tracking outdated dependencies using dependabot and sneaky
