### ISSUE TITLE
Migrating rocketchat from snap to docker on new host

### ISSUE THREAD

**Issue by macmandr197** [RocketChat/Rocket.Chat#13943]
Alright, so. I'm reconfiguring how I want to run my server and have decided to go from running snaps on ubuntu, to a docker container on unRAID. How would I go about migrating my data/configurations over? Is it the same as the proposed solution in this issue: https://github.com/RocketChat/Rocket.Chat/issues/4297

**Comment by reetp** [comment]
This is a support question rather than a bug. You can ask questions in the forums or https://open.rocket.chat #support for community support.

The most important thing is to make sure you import the DB to the same version of Rocket that you backed it up from.  Do NOT try and save from one version and import to another.

**Comment by reetp** [comment]
@rocket-cat close

Closing notabug
