### ISSUE TITLE
User autocomplete not loading suggestion from current room

### ISSUE THREAD

**Issue by rodrigok** [RocketChat/Rocket.Chat#14124]

**Comment by myteksp** [comment]
Hey there.
Could you elaborate on version where the issue was resolved?

<img width="1645" alt="Screenshot 2020-03-23 at 22 45 07" src="https://user-images.githubusercontent.com/16536796/77361681-66f36c00-6d58-11ea-9feb-a736ce243e66.png">

<img width="532" alt="Screenshot 2020-03-23 at 22 45 34" src="https://user-images.githubusercontent.com/16536796/77361707-72df2e00-6d58-11ea-9fa9-a88531799684.png">

<img width="1144" alt="Screenshot 2020-03-23 at 22 46 13" src="https://user-images.githubusercontent.com/16536796/77361717-7a063c00-6d58-11ea-9dca-e3f9c2f30335.png">
