### ISSUE TITLE
User cannot send message direct 

### ISSUE THREAD

**Issue by sophornsna** [RocketChat/Rocket.Chat#14205]
Dear rocket chat team,

I have a problem user cannot send a message it shows ignore and the option conversation is lost.
![Selection_001](https://user-images.githubusercontent.com/16955446/56455799-753d4900-638d-11e9-96c6-9a687cda0732.png)

**Comment by knrt10** [comment]
@sophornsna If you are the administrator of your server, go to **Administration -> Permissions** and check whether`Create Direct Messages` is enabled for your server. Otherwise, your administrator might have disabled it for users. Fifth block is for user permissions

![Permission](https://user-images.githubusercontent.com/24803604/56469859-d122d300-645c-11e9-9617-77d43bdb5f64.png)

**Comment by sophornsna** [comment]
Thanks, now it is working fine.

**Comment by knrt10** [comment]
Cool, feel free to close the issue
