### ISSUE TITLE
View mode Compact no longer has timestamp and text on a single line

### ISSUE THREAD

**Issue by krf** [RocketChat/Rocket.Chat#14322]
### Description:

We just got upgraded to 1.0.1. The view mode setting inside the user preferences stopped working. If I understand correctly, then no matter what the setting is, "Normal" is used.

### Steps to reproduce:

1. Go to Profile -> My Account -> Preferences
2. Set View Mode to "Compact"

### Expected behavior:

View mode changes to "Compact" mode, which is one line per chat entry.

### Actual behavior:

View mode stays at "Normal" mode, with separate lines for username/date and chat message.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.1
- Operating System: Linux
- Number of Running Instances: Multiple
- NodeJS Version: n/a
- MongoDB Version: n/a

**Comment by krf** [comment]
Bump? The current default view mode is eating up lots of vertical space...

**Comment by mvanbokhorst** [comment]
It seems that Compact is still a unique setting, as it shows multiple messages by the same user as different messages.
In Normal and Cozy these are consolidated into one.

I suspect that the problem is with view mode Compact no longer having timestamp and text on a single line, rather than view modes being ignored.

Some screenshots to show the differences.
Normal:
<img width="138" alt="normal" src="https://user-images.githubusercontent.com/12971324/57750277-e8fb1900-76e1-11e9-93b7-ea75dc63797c.png">
Cozy:
<img width="156" alt="cozy" src="https://user-images.githubusercontent.com/12971324/57750265-df71b100-76e1-11e9-9831-9668be3333e7.png">
Compact:
<img width="140" alt="compact" src="https://user-images.githubusercontent.com/12971324/57750325-1ba51180-76e2-11e9-9a5e-699a9d2c9ada.png">

**Comment by krf** [comment]
> I suspect that the problem is with view mode Compact no longer having timestamp and text on a single line, rather than view modes being ignored.

Right... And that combined with the fact it shows multiple messages by the same user as different messages does not really make it more "Compact" than any other view mode, does it? :)

**Comment by krf** [comment]
Thanks for the screenshots, by the way. Should/Could have done this myself... :)

**Comment by krf** [comment]
Bump. Is anyone taking care of this?

**Comment by Sylordis** [comment]
Bumping this ticket, for the compact mode was very useful.

**Comment by Exordian** [comment]
Threading looks also quite broken

**Comment by MartinSchoeler** [comment]
@krf @mvanbokhorst  Should it look something like this?

![image](https://user-images.githubusercontent.com/20868078/65050954-9dca6e80-d93e-11e9-8533-2b6c84a97e19.png)

**Comment by mvanbokhorst** [comment]
> @krf @mvanbokhorst Should it look something like this?
> 
> ![image](https://user-images.githubusercontent.com/20868078/65050954-9dca6e80-d93e-11e9-8533-2b6c84a97e19.png)

That looks like the compact mode I had grown attached to.
A 'yes' from me!

**Comment by krf** [comment]
:+1:

**Comment by Sylordis** [comment]
@MartinSchoeler without any spacing between paragraphs, new messages after the first at the beginning of the line, nickname is displayed only on the first message if in rapid succession, and edit icon at the beginning of the line (after nickname and if applicable). The one you're showing seems more like the "Cozy" version.

**Comment by MartinSchoeler** [comment]
@Sylordis About removing the spacing between paragraphs, that might cause problems, since you can add multiple paragraphs for spacing on a message, removing this could break a message that is desired to have spacing for formatting reasons.

**Comment by MartinSchoeler** [comment]
I was thinking of something like this.
![Screen Shot 2019-09-18 at 16 06 04](https://user-images.githubusercontent.com/20868078/65178398-0133c980-da2f-11e9-9f9f-3177dc0df196.png)

On multiline messages, I don't see the point on having the message on the first line, since the message will already disrupt the rest of the messages. And with the new organization of the message components, we would have to break it to add the first line of the multiline message to the side of the name and timestamp.

it might not be the most elegant solution, but In my opinion is better than the way that the old RC was doing it

Also the old behaviour did have the username/avatar on each message:
![image](https://user-images.githubusercontent.com/20868078/65179128-908dac80-da30-11e9-86ff-cb7eee25ff5b.png)

**Comment by Sylordis** [comment]
@MartinSchoeler Makes sense indeed for multi-line messages. When I said paragraphs, I meant messages, sorry: less spacing between two messages. I didn't have the nickname repeated though, and it was still last year. I mean... we know who's speaking by checking the first message.
I saw there were some css classes/styles which were hiding the nickname for following messages (or is it "non first messages"? I don't remember exactly).
