### ISSUE TITLE
Support of snapcraft.io stopped?

### ISSUE THREAD

**Issue by lazyants** [RocketChat/Rocket.Chat#14366]
there are for a while no update available, even not for the 0.74.x

<img width="992" alt="image" src="https://user-images.githubusercontent.com/249065/57133083-048d2800-6da2-11e9-9614-b42d602d8b6f.png">

**Comment by graywolf336** [comment]
As per our documentation, snaps are delayed in receiving updates due to them being our biggest installation base. As such, we would like to prevent breaking thousands of installations due to an oversight or unforseen bug. With the massive update of v1, there were several issues identified early in the release which further emphasised the need to delay updating snaps until we know that it won't break the majority of them. https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/#when-will-my-snap-installation-get-the-latest-release
