### ISSUE TITLE
How to upgrade RocketChat docker without getting MongoDB broken from 0.74.3 (Mongo 3.2.9) to 1.0.3 (Mongo 4.0)

### ISSUE THREAD

**Issue by LXSysadmin** [RocketChat/Rocket.Chat#14574]
### Description:

I have upgraded RocketChat dockerized version from 0.74.3 to 1.0.3 and it's can't get data from MongoDB.
So, i try to create new server, install latest RocketChat and MongoDB, but when i import data from Mongo 3.2.9, i get error about "MongoError: E11000 duplicate key error collection: rocketchat.rocketchat_cron_history index: intendedAt_1_name_1 ."

So, what would be the correct way to upgrade dockerized RocketChat 0.74.3 to 1.0.3 version? Is there also required MongoDB upgrade from 3.2.9 to 4?

Also without DB upgrade, RocketChat stops working after upgrade 0.74.3 to 1.0.3. Till now every upgrade was perfect. 

### Server Setup Information:

- Operating System: Ubuntu 16
- Deployment Method: docker
- Number of Running Instances: 1
- NodeJS Version: v8.11.4

**Comment by LXSysadmin** [comment]
Also, is it safe to dump Mongo 3.2.9 and restore to next version like Mongo 3.4, 3.6?

**Comment by LXSysadmin** [comment]
> Also, is it safe to dump Mongo 3.2.9 and restore to next version like Mongo 3.4, 3.6?
**3.2->3.4** i get error in mongorestore process: Failed: parties.rocketchat_uploads.files: error creating indexes for parties.rocketchat_uploads.files: createIndex error: The field 'w' is not valid for an index specification. Specification: { name: "filename_1", ns: "parties.rocketchat_uploads.files", w: 1, key: { filename: 1 } }

**Comment by reetp** [comment]
@rocket-cat close

This seems to be a support issue rather than a bug.

Please ask in the forums or open.rocket.chat #support 

Some notes for you to read up on before you ask questions there.
 
- Before doing anything take some **good DB backups** at each stage
- Make sure you add replicasets/oplog to the DB before upgrading Rocket - see docs
- Then upgrade Rocket and let it update the internal Mongo DB version
- Once settled look at upgrading Mongo itself

**Comment by LXSysadmin** [comment]
Where can i found correct step-by-step upgrade documentation? (with all your mentioned steps, oplog and e.t.c)
