### ISSUE TITLE
Federation without HUB

### ISSUE THREAD

**Issue by disaster123** [RocketChat/Rocket.Chat#14640]
Hello,

this is more a feature request than a bug. I hope this is the right place.

I would like to have two RocketChat Servers (one internal, one external) and want to connect both. What is important is, that the messages of the internal server never went to the external ones but alle from internal can communicate with everybody on the external chat.

The idea is to store internal communication in our internal office cloud and public talk with customers on the external one. Using federation needs the HUB which means both servers are registered externally.

Greets,
Stefan

**Comment by alansikora** [comment]
Hey @disaster123! Just so I understand it better:

```I would like to have two RocketChat Servers (one internal, one external) and want to connect both.```

Good, federation can help you with that.

```What is important is, that the messages of the internal server never went to the external ones but alle from internal can communicate with everybody on the external chat.```

I don't quite get that, which side is getting messages and which side is not getting messages?

```The idea is to store internal communication in our internal office cloud and public talk with customers on the external one. Using federation needs the HUB which means both servers are registered externally.```

Cool, that works. I just want to make sure you are aware that messages exchanged using federated rooms will be saved on both servers, ok?

**Comment by disaster123** [comment]
Sorry i might be not accurate enough. And may be it already works but i did not find the information.

I would like to have a Rocket Chat Server running in our intranet for internal communications - those Messages should be saved only on that system.

Than i would like to have an additional Rocket Chat Server which has a public IP. Our customer should be able to connect to that one.

The idea is that all employees only need to connect to the internal one but can still communicate with the external one. For those messages it would be OK to be saved on both systems.

**Comment by alansikora** [comment]
Yup, that use case is covered @disaster123!

You need a way to access that internal instance tho. The Hub might help. Just as a reminder, the Hub is solely for discovery purposes, no messages are exchanged using it. It is an easy way to replace DNS entries.

You basically need this:

 1) Make sure you have a route to your internal Rocket.Chat instance, the internet needs to reach that instance somehow;
 2) Register that internal instance using the Hub or with DNS entries;

The Hub and the DNS entries work exactly the same way, it is just a way to find your server. Everything else, the entire communication, goes through a double encrypted between the servers, not middle men.

**Comment by disaster123** [comment]
Ideally great but this is not the case. The internal and the external one are only connected through an ipsec tunnel. So the internal one is NOT reachable via DNS or public internet.

**Comment by alansikora** [comment]
@disaster123 now I understood your use case. The thing is, federation is not supposed to work that way, it is supposed to be fully internal or fully external. What you need is a tunnel.

You have two option tho:

1) allow `https://hub.rocket.chat` to be accessible by your internal instance (so you can find other servers, and other servers can find you);

2) hack your way out of it :) It should work with a few simple steps but remember, this is not a supported feature!

You will have to create two `federation_dns_cache` entries on each server's mongo, which are:

```{
    "domain" : "internal.yourdomain.com",
    "public_key" : "<the full public key as shown on the INTERNAL server's federation admin panel",
    "url" : "https://hub.rocket.chat"
}```

```{
    "domain" : "external.yourdomain.com",
    "public_key" : "<the full public key as shown on the EXTERNAL server's federation admin panel",
    "url" : "https://hub.rocket.chat"
}```

The `domain` will be your identifier. Use something like `internal-chat.mydomain.com` and `external-chat.mydomain.com`, but that could be anything you like, as long as they are different.

What you are doing here is tricking the system to believe you know where a given server is. If one of your servers goes down, then Rocket.Chat will try to find new information.

Clicking "Test your setup" should work, because you are adding your own server (internal or external) to the DNS cache.

This is not tested, but let me know how it goes.

**Comment by alansikora** [comment]
@disaster123 I will close this issue for now, ping me if you need any extra help
