### ISSUE TITLE
Implement SAML SSO in Univention UCS Server

### ISSUE THREAD

**Issue by SibeeshVenu** [RocketChat/Rocket.Chat#14672]
### Description:
I am working with Univention UCS server and I had installed [univention RocketChat app ](https://www.univention.de/produkte/univention-app-center/app-katalog/rocketchat/). Everything was quite good until I had planned to use the SAML Single Sign On with UCS as I had already done for the Nextcloud by following [this article](https://www.univention.de/blog-de/2019/02/how-to-sso-nextcloud/). I understand that there is related General SAML documentation available [here](https://rocket.chat/docs/administrator-guides/authentication/saml/). But that doesn't help well for me as in Univention UCS server the things are different, so I am looking for a documentation which explains how to do this as it is here for [nextcloud](https://www.univention.de/blog-de/2019/02/how-to-sso-nextcloud/). 

### Expected behavior:

Should have a documentation.

### Actual behavior:

There is specific documentation for Univention Rocket Chat application.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.2
- Operating System: Linux, UCS (4.4-0 errata0 (Blumenthal))
- Number of Running Instances: 1
- NodeJS Version: v8.11.4
- MongoDB Version: 3.6.12

### Additional context

Please let me know if rocket chat have separate GitHub repository for Univention Rocket Chat.

**Comment by fbartels** [comment]
In the changelog for the 1.0.3 app on UCS I was able to find the following:

> 4. With the installation the configuration for single sign-on via SAML is
       made. The appropriate SAML settings in Rocket.Chat are deactivated. In
       UCS the Rocket.Chat service provider is created and activated.

Seems this will be auto configured in the future?

cc @ngulden

**Comment by ngulden** [comment]
For fresh installations of Rocket.Chat on UCS, the Rocket.Chat App in Univention App Center already takes care of the necessary settings for SAML in Rocket.Chat and in UCS.

For installations of Rocket.Chat < 1.0.3 the settings have to be filled out manually. See the [README](https://appcenter.software-univention.de/univention-repository/4.3/maintained/component/rocketchat_20190507145915/README_EN) file.

The Rocket.Chat documentation is sufficient from my point of view, because it was possible to configure SAML in Rocket.Chat with UCS as identity provider.

I recommend to close this issue.

**Comment by SibeeshVenu** [comment]
Thanks for the responses. I have configured the SSO in UCS with external DNS not the `ucs-sso` domain. @ngulden Are you suggesting me to reinstall the RocketChat application (1.0.3) so that the SAML entries will be automatically generated with my external domain?
