### ISSUE TITLE
Move reply preview above the reply

### ISSUE THREAD

**Issue by john-light** [RocketChat/Rocket.Chat#14689]
### Description:

Currently, when you reply to a message, the original message replied to shows up _below_ the reply.

### Steps to reproduce:

1. Reply to a message
2. See that the original message shows up below the reply

### Expected behavior:

I would like (at least an option for) the original message to be moved _above_ the reply, since that is the logical order we read the message: first the original context, then the reply.
 
### Actual behavior:

The original message shows up below the reply.

![testreply](https://user-images.githubusercontent.com/9424721/66041841-276f6400-e51b-11e9-8359-4eaf2cb0dde2.png)

### Server Setup Information:

- Version of Rocket.Chat Server:  1.3.1

related: https://github.com/RocketChat/Rocket.Chat/pull/10086, https://github.com/RocketChat/Rocket.Chat/issues/9912

**Comment by reetp** [comment]
As far as I can see that was fixed in the referenced bug/PR. And as far as I can tell it works like this now.

Current stable is 1.0.3 and 1.1.0 has just been released (snap version will follow in about 2 weeks)

You haven't filled in a bug template so it is hard to know which version you are on.

https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

Noone can really help you until they know this information. An image may hep as well.

**Comment by john-light** [comment]
@reetp that's a good point about checking the version, I'm going to close this until I can verify we're up to date. Thank you for the reminder and sorry for any trouble!

**Comment by john-light** [comment]
Updated to a newer version of Rocket Chat, have completed the issue template above and filled with more info.
