### ISSUE TITLE
LDAP sync Error Exception in callback of async function: TypeError: text.replace is not a function     at module.exports 

### ISSUE THREAD

**Issue by nixmomo** [RocketChat/Rocket.Chat#14786]
### Description:

LDAP Sync and LDAP Login dont work

### Steps to reproduce:

Setup a LDAP Server and connect it with Rocketchat latest docker image

### Expected behavior:

i would expect that logins are working and sync jobs suceeds

### Actual behavior:

It ends with a error

### Server Setup Information:

latest Mongo and Rocketchat Docker Image on a fresh install with this guide
https://rocket.chat/docs/installation/docker-containers/systemd/

### Relevant logs: (Trace Logs enabled)

I20190611-17:15:26.545(0) Exception in callback of async function: TypeError: text.replace is not a function     at module.exports (/app/bundle/programs/server/npm/node_modules/limax/lib/limax.js:18:15)     at slug (app/ldap/server/sync.js:23:9)     at ldapUsers.forEach.ldapUser (app/ldap/server/sync.js:307:16)     at Array.forEach (<anonymous>)     at ldap.searchUsersSync.Meteor.bindEnvironment (app/ldap/server/sync.js:294:13)     at runWithEnvironment (packages/meteor.js:1356:24) 
I20190611-17:15:58.963(0) Exception while invoking method 'login' TypeError: text.replace is not a function     at module.exports (/app/bundle/programs/server/npm/node_modules/limax/lib/limax.js:18:15)     at slug (app/ldap/server/sync.js:23:9)     at MethodInvocation.<anonymous> (app/ldap/server/loginHandler.js:104:14)     at tryLoginMethod (packages/accounts-base/accounts_server.js:460:31)     at tryLoginMethod (packages/accounts-base/accounts_server.js:1294:14)     at AccountsServer._runLoginHandlers (packages/accounts-base/accounts_server.js:458:22)     at AccountsServer.Accounts._runLoginHandlers (app/lib/server/lib/loginErrorMessageOverride.js:7:35)     at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:518:31)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43

**Comment by jbekkema** [comment]
I can confirm we're also seeing this since the latest update. Same exception in the log when an LDAP user attempts to log in.

`I20190612-11:25:21.768(10) Exception while invoking method 'login' TypeError: text.replace is not a function     at module.exports (/snap/rocketchat-server/1377/programs/server/npm/node_modules/limax/lib/limax.js:18:15)     at slug (app/ldap/server/sync.js:22:9)     at MethodInvocation.<anonymous> (app/ldap/server/loginHandler.js:103:14)     at tryLoginMethod (packages/accounts-base/accounts_server.js:460:31)     at tryLoginMethod (packages/accounts-base/accounts_server.js:1294:14)     at AccountsServer._runLoginHandlers (packages/accounts-base/accounts_server.js:458:22)     at AccountsServer.Accounts._runLoginHandlers (app/lib/server/lib/loginErrorMessageOverride.js:7:35)     at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:518:31)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43 `

**Comment by nixmomo** [comment]
did you tried to empty the username field in the sync options? if i empty this or if i use something else then uid in this field, it works.  
![image](https://user-images.githubusercontent.com/8502506/59322935-cbb56c80-8cd8-11e9-9101-dcd722e2d5b0.png)

im really confused about it

**Comment by MarcosSpessatto** [comment]
I think [this PR](https://github.com/RocketChat/Rocket.Chat/pull/14644) should fix the error.

**Comment by jbekkema** [comment]
A workaround for this bug is to set "UTF8 Names Slugify" to "False" under Administration->General->UTF8.

**Comment by benito89** [comment]
This is an issue again in version 4.2.2. 
Since then the content of the [mentioned PR](https://github.com/RocketChat/Rocket.Chat/pull/14644) has been reverted.
Setting "UTF8 Names Slugify" to false can be a workaround.
