### ISSUE TITLE
Protection of Discussions: Locking with PW not working

### ISSUE THREAD

**Issue by kokotko1337** [RocketChat/Rocket.Chat#14798]
### Description:
When i make a new Discussion and I set PW, Members of channel are not asked for PW

### Steps to reproduce:

1. Create Discusion go inside
2. Click on Info and Edit setttings protected with PW
3. Members of channel where id Discussion can access it without PW

### Expected behavior:

When Discussion is PW protected, it should be PW protected for all

### Actual behavior:

Members of channel can access PW protected Discussions without typing PW

### Server Setup Information:

- Version of Rocket.Chat Server: latest
- Operating System: Ubuntu Server
- Deployment Method: manual
- Number of Running Instances: 1
- DB Replicaset Oplog: y

**Comment by geekgonecrazy** [comment]
Hm... by design if they can access the channel the discussion is a child of the channel.

I think the real issue is that you can even set a password on a discussion...  it should not even allow this.  Discussions are kind of like private groups that can be accessed by all in the parent channel or group.
