### ISSUE TITLE
Discussions: Create private discussions

### ISSUE THREAD

**Issue by kokotko1337** [RocketChat/Rocket.Chat#14799]
### Description:

Example:

Channel XXX have Users 1,2,3,4,5,6,7,8,9

User 1 starts discussion ich channel XXX and invite users 2,3,4,5
Users 6,7,8,9 are able to read this discussion.

It is somehow possible to make it private discussion for users 1,2,3,4,5 ?
Wanted behavior: 6,7,8,9 are not able to read the discussion, because they are not invited, but still in channel for other discussions or chat.

Server Setup Information:
Version of Rocket.Chat Server: latest
Operating System: Ubuntu Server
Deployment Method: manual
Number of Running Instances: 1
DB Replicaset Oplog: y

**Comment by MartinSchoeler** [comment]
Not enough information provided.  Please check our [issue guidelines](https://rocket.chat/docs/contributing/reporting-issues) again for help on providing additional information.

**Comment by kokotko1337** [comment]
which part is not clear ?

**Comment by aaron-lmy** [comment]
I have the same troubles.

**Comment by ers81239** [comment]
Same here.... I am new to RocketChat.  I created a discussion, and marked it Private in its settings.  The UI Says "Private" "Just invited people can access this channel".  However, someone who wasn't invited quickly joined the Channel.  I think the issue is that the UI looks the same for Discussions and Channels but Discussions can't really be private.
