### ISSUE TITLE
clicking on thread link pushes up content and top section gets lost

### ISSUE THREAD

**Issue by rockneverdies55** [RocketChat/Rocket.Chat#14863]
When I click on thread link it opens up right sliding drawer containing the thread messages. However all the content gets pushed up so I lost the top section area. I can't close the thread messages and get back to the normal channel view anymore. I have to reload/refresh to get out this state so very annoying. I see extra blue section at the bottom which gives me the feeling of the content was pushed up unnecessarily.

This is happening on the latest version of rocketchat which is `1.1.3`

![image](https://user-images.githubusercontent.com/4588562/60070685-2d85c580-9720-11e9-96b5-b0d9efc3ccee.png)

**Comment by rockneverdies55** [comment]
I can replicate this in `1.2.0` as well. Weird, no body else is having the issue?

**Comment by rockneverdies55** [comment]
Feels like I'm talking to myself here but anyways. Just caught a new behavior on this.

If I first go to threads list view in right drawer via clicking on Threads icon on the top right, and select the target thread from the list of the threads, this weird ui behavior doesn't happen. 

However if I click on the blue (linked) message within the chat window to directly go to the target thread immediately in the right drawer, the ui gets messed up as in the screenshot above.

**Comment by ggazzo** [comment]
@rockneverdies55 I'm afraid you are the first (and maybe the one 😢) could you provide me which browser you are using?

we use threads quite frequently here and I never saw that problem happening...

looking at the image... do you have a custom build? or at least a custom css?

**Comment by ddoron** [comment]
@rockneverdies55 You're not the only one! I was getting the same issue, but I fixed it.

I'm on Version 1.2.4, and we have been migrating our database since versions earlier than 1.0.

The issue was in the **footer**.

### Modifying the Side Navigation Footer
In the admin panel, click the **Label** sidebar category. In the categories to the right of the sidebar, choose **Layout**. **Side Navigation Footer** is there. That has the HTML stored inside the `<footer>` tag.

### Fix
Previously, we had the following HTML inside that footer tag (and of course, inside **Side Navigation Footer**:

```html
<div>
<a href="https://github.com/RocketChat/Rocket.Chat" class="logo" target="_blank"> 
	<img src="/images/logo/logo.svg?v=3" />
</a>

<div class="github-tagline">
	<span class="icon-pencil" style="color: #994C00"></span> with 
	<span class="icon-heart" style="color: red"></span> on 
	<span class="icon-github-circled"></span>
</div>
</div>
```

At the time of writing, the defaults are:
```html
<a href="/home"><img src="assets/logo"/></a>
```

I pressed the ↩️button to revert to defaults, and pressed **Save changes**.

**Comment by rockneverdies55** [comment]
Sorry guys no more updates from me on this because we ended up shutting off threads functionality all together since we found it confusing a bit to follow.
