### ISSUE TITLE
can not upload file more than 2.6 mb (test by apache2 , nextcloud ,owncloud , ngnix)  

### ISSUE THREAD

**Issue by leyawialltempmail** [RocketChat/Rocket.Chat#14943]
in several time i test configure rocket with webDav ,
first i use apache2 and nextcloud, every thing was ok but file more 2.6 m can not upload ,
i increase (i increase nextcloud max upload size and rocket max upload size)
so in this case i have error ( UnHandledPromiseRejection ===
 { Error: Request body larger than maxBodyLength limit)

after this i configure nginx and next cloud but in this case i have this error ( Exception while invoking method 'ufsComplete' { Error: Request failed with status code 404}  ) i should say in this case file bigger 2.6 m cant upload ,

after this i use ngnix and owncloud that configure for different app and work well , but i have that error ,
in final time i configure rocket with an free cloud that provide free file share that site is [https://www.opendrive.com/webdav](url)
in this case i have same error

**Comment by MartinSchoeler** [comment]
Hey, looks like you seem to be looking for support. You will have a better chance of getting help if you go to one of the places listed in [here](https://rocket.chat/docs/getting-support/#community-support) since github is not the best place to ask for support. For now i will be closing this issue, as it does not fit our issue guidelines.
