### ISSUE TITLE
regarding analytical report downloading

### ISSUE THREAD

**Issue by anchu-simplecrm** [RocketChat/Rocket.Chat#14961]
hello how can we download analytical reports of live agent console...is there any option

**Comment by MartinSchoeler** [comment]
Hey, looks like you seem to be looking for support. You will have a better chance of getting help if you go to one of the places listed in [here](https://rocket.chat/docs/getting-support/#community-support) since GitHub is not the best place to ask for support. For now, I will be closing this issue, as it does not fit our issue guidelines
