### ISSUE TITLE
User presence status description not updated

### ISSUE THREAD

**Issue by moerks** [RocketChat/Rocket.Chat#15007]
### Description:
When switching status from a custom status to one of the 4 predefined ones the description is not updated. 
Same applies when editing the status message on the fly and then switching back to "online" for example.
![grafik](https://user-images.githubusercontent.com/629566/61283767-f0ac6c00-a7bd-11e9-9122-be574925b829.png)

### Steps to reproduce:

1. Create a Custom Status -> yellow - description: "out for lunch"
2. Switch your Status to "out for lunch"
3. Switch your Status back to "online"

### Expected behavior:
I'd expect my description to say "online"

### Actual behavior:
Description is still "out for lunch" while the color changes from yellow to green.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.2.1
- Operating System: Linux
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.4
- MongoDB Version: 3.4.20

**Comment by wreiske** [comment]
This is by design. If you have a status that says "free cake in the break room" and have it set to busy, you will want to keep your status when you switch it to online. 

If you want to change your presence back to online, just edit your status, clear it, and whatever your presence is set to will become your status. 

You can also just type `/status ` without any text and it will clear your status message. This works in mobile too.

**Comment by moerks** [comment]
Thanks. I can live with both answers ;)
