### ISSUE TITLE
https problem

### ISSUE THREAD

**Issue by wanghongqing2008** [RocketChat/Rocket.Chat#15010]
their are some questions about me 
1 my server is centos ,where is the postion about the rocket.chat log?
2 when i add https certification ,pc can use normally,ios can't connect the server ,andriod can connect but can't send and receive messages.

**Comment by reetp** [comment]
@rocket-cat close

These are support questions, not bugs. Your questions are answered in the documentation.

Please ask in:
https://forums.rocket.chat/
https://open.rocket.chat/channel/support

> 1 my server is centos ,where is the postion about the rocket.chat log?

It depends how you installed rocketchat and which version of CentOS. Usually somewhere in /var/log/.... and can be viewed with tail or journalctl. Please read about general CentOS administration.

> 2 when i add https certification ,pc can use normally,ios can't connect the server ,andriod can connect but can't send and receive messages.

Most likely because you have not configured Rocket.Chat to use SSL and a reverse proxy. Please read the documentation. https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy/
