### ISSUE TITLE
Can't access livechat room from the Android app

### ISSUE THREAD

**Issue by theblazehen** [RocketChat/Rocket.Chat#15087]
### Description:

I get a `The required "roomId" or "roomName" param provided does not match any channel [error-room-not-found]`

### Steps to reproduce:

1. Go to your website with the livechat widget
2. Start the livechat
3. Try and open the livechat on your Android device

### Expected behavior:

You should be able to view that chat and interact with the visitor to your website.

### Actual behavior:

You get an error message. 
![WhatsApp Image 2019-07-31 at 03 17 56](https://user-images.githubusercontent.com/3276410/62226135-fe671180-b3b9-11e9-91af-e6e7fe0adddb.jpeg)

### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.3
- Operating System: Ubuntu 18.04
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: default snap setting
- NodeJS Version: default from snap
- MongoDB Version: default from snap

**Comment by reetp** [comment]
@rocket-cat close

Please follow the guidelines for issues. Always test on the later versions of software first.

I believe this issue is due to lack of livechat support in the Android app, not with Rocket. Chat server

Please follow up in the Android repos.... have a search as there are probably issues open on this already as support is already planned.

https://github.com/RocketChat/Rocket.Chat.Android

https://github.com/RocketChat/Rocket.Chat.ReactNative
