### ISSUE TITLE
Rocket.Chat could Use Sharded Cluster MongoDB?

### ISSUE THREAD

**Issue by zzl221000** [RocketChat/Rocket.Chat#15273]
MongoDB is sharded cluster with keyfile authentication.User could connect mongos.What is MONGO_OPLOG_URL?

**Comment by himpierre** [comment]
Allthough it's not really worth a github issue here is what i have:

```
MONGO_URL=mongodb://localhost:27017/rocketchat?replicaSet=rs0
MONGO_OPLOG_URL=mongodb://localhost:27017/local?replSet=rs0
```

**Comment by zzl221000** [comment]
hey @himpierre
I can only connect to the mongodb cluster via mongos. local database is stored in mongod instance.

**Comment by migueltg** [comment]
Is possible use Rocket.Chat in a Sharded Cluster? Is code prepared to use Shard Keys?
Thanks

**Comment by emikolajczak** [comment]
Hi,
Any information about possibilty to use mongo sharded cluster with Rocket.Chat?

**Comment by AvivBenShoham** [comment]
Any updates???

**Comment by y377** [comment]
I'm trying, but I can't connect at the moment

**Comment by zzl221000** [comment]
I don’t think this issue should be closed. Rocket.Chat still cannot use the sharded MongoDB cluster so far. @rodrigok

**Comment by ankar84** [comment]
> I don’t think this issue should be closed. Rocket.Chat still cannot use the sharded MongoDB cluster so far. @rodrigok

Totally agree with you!

**Comment by ankar84** [comment]
Related forum thread https://forums.rocket.chat/t/how-to-spread-mongodb-load-across-few-servers/11240

**Comment by debdutdeb** [comment]
Hey everyone, sharded clusters are **not** supported by Rocket.Chat right now, unfortunately.

Quote from @sampaiodiego -

"""
this is due to a technical difference on how oplog behaves when using sharded clusters, as described here https://www.mongodb.com/blog/post/tailing-mongodb-oplog-sharded-clusters we still don't have the ability to listen to multiple oplog streams and I'm afraid we might stop using oplog before we ever consider supporting shard clusters. but for now there is no plans to do either. :/
"""
