### ISSUE TITLE
high load loading/uploading images with gridfs

### ISSUE THREAD

**Issue by cortex3** [RocketChat/Rocket.Chat#15276]
### Description: After upgrading, loading images and uploading images is very slow and causes load on the system.
So i have a staging and production system, my production system is currently on 0.73.2 and i upgraded my staging system to 1.3.2. I've imported the database from live to the staging system and upgraded in major increments. But now all my file uploads and the loading of images is super slow using gridfs. I've tried changing to filesystem storage which sped up uploading the files but since old files won't be migrated to the filesystem the slow loading problem still persists. If i click on more -> files and try clicking on a couple images the load on my staging system goes up to 8 or 9. The hardware on both systems is identical since they're using the same ressources on the same hypervisor.
### Steps to reproduce:
1. updating to 1.3.2
2. attempting to load files using gridfs

### Expected behavior:

no load problems, fast loading times. like I'm experiencing it currently on my production system.

### Actual behavior:

Load problems, high disk times, slow loading of files.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.3.2
- Operating System: CentOS 7
- Deployment Method: manual
- Number of Running Instances: 2
- DB Replicaset Oplog: ?
- NodeJS Version: 8.11.4
- MongoDB Version: 4.0

### Additional context
The actual uploading was pretty fast using gridfs, it just got stuck on 100% for like half a minute or minute.

I'm using Nginx as a reverse proxy and both instances are running on the same server along with the Mongodb.
### Relevant logs:
nothing suspicious in the server debug log.

**Comment by cortex3** [comment]
Issue persists when testing on 2.0.0.

**Comment by cortex3** [comment]
If it helps, this is my reverse proxy config:
`upstream backend {
        server 127.0.0.1:3001;
        server 127.0.0.1:3002;
}

server {
    listen 80;
    server_name NAME;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    server_name NAME;
    include /etc/nginx/conf.d/ssl/ssl.conf;

    access_log /var/log/nginx/rocketchat.access.log;
    error_log /var/log/nginx/rocketchat.error.log;

    ssl_certificate /etc/nginx/conf.d/ssl/cert.crt;
    ssl_certificate_key /etc/nginx/conf.d/ssl/cert.key;

    server_tokens off;
    add_header X-Content-Type-Options nosniff;
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Robots-Tag none;
    add_header X-Download-Options noopen;
    add_header X-Permitted-Cross-Domain-Policies none;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;


    location / {
        proxy_pass http://backend/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forward-Proto http;
        proxy_set_header X-Nginx-Proxy true;

        proxy_redirect off;
    }
}
`

**Comment by cortex3** [comment]
So I've managed to solve this problem myself.
When importing the database dump into my staging System I've received the Error:
 `The field 'w' is not valid for an index specification`
Google told me that using `--noIndexRestore` to restore the dump would solve the problem. The issue with this is that Rocketchat won't rebuild the Indexes again which is why everything was so slow. 
To solve this I removed the database and tried restoring again. To resolve the invalid field error I ended up removing the "w" field from the 
`rocketchat/rocketchat_uploads.chunks.metadata.json` 
and 
`rocketchat/rocketchat_uploads.files.metadata.json`
file of my backup.
I'm not sure if the "w" field used to do anything important or if this causes further issues down the line but at the moment everything is working fine.

I hope this resolves the Issue to everyone that stumbles upon this. 
Sadly the Community Support was of not much help here and I spend way too much time on this..

**Comment by reetp** [comment]
Just seen this.

> Sadly the Community Support was of not much help here and I spend way too much time on this..

It is what it is. People there don't always have all the answers. It's how Open Source works. Give a bit, take a bit, but no guarantees of anything. 

NB - I spent quite a bit of MY valuable time trying to help.

Too many people just 'pop in' to get an answer thinking it is 'a free help service', then disappear. 

Most don't bother staying around to help anyone else themselves because **their** time is too valuable - but then they do expect help on tap and other people to be there to help them.

I'm sure now you have your solution you won't be seen again. Until you have another issue.

That is both frustrating and annoying.

If you want guaranteed support and if you want to save time then pay someone to do it for you.
https://rocket.chat/docs/getting-support/

As far as your issue goes quite of lot of this was of your own making.

You had left your installation to get extremely out of date. That is naive with such a fast moving application, and creates problems later when you try and upgrade, as you found out.

You continued to use the gridfs filesystem to store files even though there is plenty of info around to suggest that is not a good idea for large amounts of files.

As far as your error was concerned, now I have read some more, I suspect that you also changed your DB version here somewhere which was never mentioned.

In any event, as far as indexing goes, I believe that this is to do with Mongo rather than Rocket.

https://docs.mongodb.com/manual/reference/program/mongodump/

>mongodump output only captures the documents in the database and does not include index >data. mongorestore or mongod must then rebuild the indexes after restoring data.

https://stackoverflow.com/questions/36854566/why-mongodump-does-not-backup-indexes

I'm not sure how and what you backed up, and how you restored, but somewhere there lay your problem.

If you restore from backup always restore to an identical setup first before trying to upgrade anything or you may face issues. Then upgrade your DB, or your Rocket, in small steps after.

**Comment by cortex3** [comment]
@reetp 
> NB - I spent quite a bit of MY valuable time trying to help.
My remark was in no way meant as a dig at you or anyone else who helped me try to fix this issue. I'm very thankful for the help you provided since it pointed me in the right direction at the end of the day. The remark was just out frustration for putting in so much time to debug this issue.

> You had left your installation to get extremely out of date. That is naive with such a fast moving application, and creates problems later when you try and upgrade, as you found out.
I've always had the most recent version installed on my test system. Sadly I was unable to update my production system because of bugs that would've affected my users. 0.73.2 was the only version with almost no bugs for me except for the memory leak I've been experiencing.  My problems were not related to the update process and I always made sure to update the system in small increments.

> You continued to use the gridfs filesystem to store files even though there is plenty of info around to suggest that is not a good idea for large amounts of files.
Prior to my issue I've never heard of problems concerning gridfs. If this is a known issue this should probably be mentioned in the documentation regarding file storage since gridfs is the current default.

> As far as your error was concerned, now I have read some more, I suspect that you also changed your DB version here somewhere which was never mentioned.
My MongoDB Version was throughout the entire process 4.0 on both my test and production system.

> In any event, as far as indexing goes, I believe that this is to do with Mongo rather than Rocket.
Yes this problem was caused by MongoDB. Without any knowledge of how RocketChat works I was hoping that the Rocketchat code would ensure that all required indexes are present at the process start. 

> If you restore from backup always restore to an identical setup first before trying to upgrade anything or you may face issues. Then upgrade your DB, or your Rocket, in small steps after.
Thanks for the tip! But this is how I've always updated the system.

Thank you for your contributions to this project and for your patience to help me debug this issue! I'm a big fan of the Rocketchat project itself. I'm just hoping that in the future there will be a bigger focus on stability rather than new features. So that I can manage to stay up to date without issues for my users.
