### ISSUE TITLE
Unable to find user rocketchat when trying to get shell in Docker container

### ISSUE THREAD

**Issue by tholu** [RocketChat/Rocket.Chat#1530]
I'm trying to get a shell in the rocketchat Docker container (to run meteor commands to reset the password of a user, since this is not yet possible in administration and password reset is currently broken https://github.com/RocketChat/Rocket.Chat/issues/1502):

``docker ps``

gives me

``[...]``
``<<container id>>        rocketchat/rocket.chat:develop   "node main.js"           6 days ago          Up About a minute   0.0.0.0:3000->3000/tcp   rocketchat_rocketchat_1``
``[...]``

However, this fails:

``docker exec -t -i <<container id>> /bin/bash``
``Unable to find user rocketchat``

Any ideas?

**Comment by marceloschmidt** [comment]
I'm not sure why this is failing to you, for me it logs into the shell nicely. Although, even if you could log in, you'd not be able to run meteor commands in a meteor shell, because meteor is not running inside the container. What runs inside the container is the compiled nodejs program. If you need to do anything to the deployed version, you have to access the database directly. Now for the logging in the shell part, how did you start your rocketchat container? Thanks.

**Comment by tholu** [comment]
@marceloschmidt That's weird. I used ``docker-compose up -d rocketchat`` to start the rocketchat container. And I used the docker-compose.yml (with modifications) from the repository.

**Comment by tholu** [comment]
@marceloschmidt Which kernel version are you using? I just found out that docker generally supports only > 3.8 (and I'm still running 3.2 - without any other issues).

**Comment by engelgabriel** [comment]
The MongoDB is running on another container, you should access the DB on that container directly.

**Comment by engelgabriel** [comment]
Please ping us at https://demo.rocket.chat/channel/support is this is still an issue.
