### ISSUE TITLE
Federation breaks on updating to 2.0.0

### ISSUE THREAD

**Issue by navigateitservices** [RocketChat/Rocket.Chat#15363]
### Description:

When updating Rocket Chat from 1.3.2 to 2.0.0 Federations breaks completely.
Users cant find each other, existing chats via Federation are not usable.

### Steps to reproduce:

1. Update Rocket Chat via official updating guide of manual installation

### Expected behavior:

Update to 2.0.0. without breaking Federation

### Actual behavior:

Update goes smoothly, no errors there.
Existing Chats via federation are no longer usable, without an error message displayed.
Users cant find each others via Federation any more.
Federated users are now renamed to old-XXX in settings->Users and deactivated, but no new users are added to replace those

### Server Setup Information:

- Version of Rocket.Chat Server: 1.3.2
- Operating System: Ubuntu 18.04 bionic
- Deployment Method: tar
- Number of Running Instances: 2
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.3
- MongoDB Version: 3.6.12

**Comment by sampaiodiego** [comment]
Hi @navigateitservices .. Thanks for reporting this.

I'm sorry if the message wasn't spread accordingly, but this is the expected behavior, since we changed Federation a lot and a migration wan't possible.

Please take a look at this post on our forums where I explain it a little bit and also other breaking changes of the release: https://forums.rocket.chat/t/rocket-chat-2-0-0-release/4550

I'll update the release notes including a link to the post as well, so people can know about it.

Thanks again and I'm sorry the inconvenience.
