### ISSUE TITLE
Caddy can't resolve DNS Query to generate SSL cert

### ISSUE THREAD

**Issue by husim0** [RocketChat/Rocket.Chat#15447]
### Description:

When activating HTTPS on caddy, it replies that DNS query cannot be resolved, where as it's working properly using dig.

### Steps to reproduce:

1. Set URL : `sudo snap set rocketchat-server caddy-url=https://rocketchat.xxx.fr`
2. Activate https  `sudo snap set rocketchat-server https=enable`

### Expected behavior:

A SSL certifcate is properly generated after DNS challenge succeeded.

### Actual behavior:

I take some time to reply but then output : 
```Can't resove DNS query for rocketchat.xxx.fr, check your DNS configuration, disabling https ...)```

Dig output : 
```
dig rocketchat.xxx.fr

; <<>> DiG 9.11.3-1ubuntu1.8-Ubuntu <<>> rocketchat.xxx.fr
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 60838
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;rocketchat.xxx.fr.          IN      A

;; ANSWER SECTION:
rocketchat.xxx.fr.   3441    IN      A       163.172.191.XXX

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Thu Sep 26 07:46:47 UTC 2019
;; MSG SIZE  rcvd: 65
```

### Server Setup Information:

- Version of Rocket.Chat Server: 1.3.2
- Operating System: Ubuntu server 18.04
- Deployment Method: Snap
- Number of Running Instances: 1
- DB Replicaset Oplog: "Activated"
- NodeJS Version: v8.11.4
- MongoDB Version: 3.4.20

### Additional context

I use a Scaleway's VPS.

### Relevant logs:

I don't know how to find proper logs for that.

Thank you !

**Comment by reetp** [comment]
I think this is a setup issue rather than a bug.

https://rocketchat.github.io/docs/contributing/reporting-issues/
https://rocketchat.github.io/docs/getting-support/

Read this on how to setup caddy - you seems to have missed a step.

https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/autossl/

```
sudo snap set rocketchat-server caddy-url=https://<your-domain-name>
sudo snap set rocketchat-server caddy=enable    <<<< this
sudo snap set rocketchat-server https=enable
sudo rocketchat-server.initcaddy
```

If you read that page you will also see how to read Caddy logs.

And if you read this page you will see how to read Rocket logs

https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/

**Comment by reetp** [comment]
@rocket-cat close

And closing
