### ISSUE TITLE
the messages are not pruned on mobile after retention

### ISSUE THREAD

**Issue by gillbates** [RocketChat/Rocket.Chat#15522]
### Description:

We had set the RetentionPolicy and the outdated messages got pruned on the desktop.
But all the messages remains on the mobile.

### Steps to reproduce:

1, our RetentionPolicy settings
<img width="1834" alt="msg" src="https://user-images.githubusercontent.com/783547/66278909-1e4a1280-e8e0-11e9-8f49-d202eb9e75c4.png">

### Expected behavior:

the messages on mobile app should be pruned automatically also.

### Actual behavior:

currently the messages on iOS remains.

### Server Setup Information:

Server Configure :

<img width="1018" alt="server" src="https://user-images.githubusercontent.com/783547/66278945-741eba80-e8e0-11e9-924f-68146783bb29.png">

### Additional context

We have used this docker-compose file and steps for this environment.
https://rocket.chat/docs/installation/docker-containers/docker-compose/

**Comment by gillbates** [comment]
anyone from the team?

**Comment by reetp** [comment]
> anyone from the team?

Someone from the team has labelled it so it has been noted.

It will get looked at in due course but remember that this is Open Source.

It may be important to you, but not necessarily to them. It may get fixed, subject to their priorities.

Of course you can pay for support. Alternatively your pull request with a fix will always be welcomed.

Otherwise you will just have to be patient.
