### ISSUE TITLE
snap still on Version 1.3.2

### ISSUE THREAD

**Issue by jpaechnatz** [RocketChat/Rocket.Chat#15537]
snap refresh // snapcraft.io are still on Version 1.3.2

FAQ/Documentation 
"Updated Snaps are usually released around the 15th of the month - around 2 weeks after a new release." https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/

So what is the roadmap for snap Releases?

Thanks ;-)

**Comment by reetp** [comment]
@rocket-cat close

Closing notabug.

> So what is the roadmap for snap Releases

This:

> usually

So not every month necessarily, and there are a lot of changes to test between 1.x and 2.x

> This gives us time to look for issues so you don’t have to.

So IOW when it is ready. Snaps will never be 'bleeding edge'. That is because the majority of users use snaps and they don't want to go and break all the installs on an upgrade. It's for your own good.

If you want faster updates use Docker or manual installs.
