### ISSUE TITLE
Please add a config flag to disable the MongoDB Deprecation notice

### ISSUE THREAD

**Issue by b-** [RocketChat/Rocket.Chat#15538]
### Description:

Because the Snap package is stuck on MongoDB 3.4.20 for the time being, administrators of the Edge channel Snap package receive a message every 24 hours from @rocket.cat saying, "MongoDB Deprecated…" about this. Additionally, there's a big banner on the web ui and admin panel stating that the version of Mongo in use is deprecated.

### Steps to reproduce:

1. Install Rocket.Chat from Snap on the Edge channel including its own MongoDB
2. Get spammed with messages that this (included) MongoDB server version is deprecated.

### Expected behavior:

I expect the snap to include a later version of Mongo, however I know I read somewhere (pardon, I forget where) that there's a reluctance to update the included Mongo in the Snap package for various (good) reasons. So there should be a way to at least suppress the warning for Snap users, please.

### Actual behavior:

>@rocket.cat:
>>MongoDB Deprecated
>>MongoDB version 3.4.20 is deprecated, please upgrade your installation.
>>https://rocket.chat/docs/installation

### Server Setup Information:

- Version of Rocket.Chat Server: HEAD 92c00dc3c2cff601d6a01c9088f51e3ddcda70cb
- Operating System: Linux 5.0.0-13-generic (x64) via Ubuntu 19.04 Snap
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: n/a
- NodeJS Version: 8.15.1
- MongoDB Version: 3.4.20

**Comment by geekgonecrazy** [comment]
Please stop using edge channel.  At least move to the beta channel.  Before final release of the snap to stable channel we do manual review of the snap.

**Comment by reetp** [comment]
> ### Steps to reproduce:
>     1. Install Rocket.Chat from Snap on the Edge channel including its own MongoDB
>     2. Get spammed with messages that this (included) MongoDB server version is deprecated.

IOW as per Aarons comment Edge is really a development version for bleeding edge testing ONLY, and problems can and will be encountered.

Snaps are designed to be the most stable versions once released. They are not meant to be the most "up to date" versions.

If you want to track the current release then use Docker or a manual install instead of snaps which will always lag behind.

**Comment by b-** [comment]
This all makes sense, but it makes me have to wonder why there's an Edge channel in the first place for the Snap, then.

My instance has two users, both of us are Admins and programmers — if it coughs up blood and dies I'm not going to cry a river, and I wouldn't say this is a "production system" in any sense further than that it's actually used regularly. I'm okay with the occasional problem, and really this has been the most intrusive issue I've had so far on the Edge channel having used it for months if not longer.

Let me ask this: should I expect a manual install from master/HEAD to be any more stable than the Edge Snap? I have no idea what your build process is like…

**Comment by reetp** [comment]
> This all makes sense, but it makes me have to wonder why there's an Edge channel in the first place for the Snap, then.

Because they need somewhere to test new snaps....... not just internally but externally too. These are developer channels, not for users. Hence they are not widely talked about because then every man and his dog will try upgrade to get some funky new feature and disaster will ensure in short order.

It doesn't come with any warranty whatsoever. Expect it to break and act accordingly

It should be renamed 'bleeding-edge-beware-dragons-and-lost-data-live-here'

> Let me ask this: should I expect a manual install from master/HEAD to be any more stable than the Edge Snap? I have no idea what your build process is like…

I think the answer is YMMV because they may be at different points. You'd need to compare, and remember snaps have a DB included....

I'd suggest unless you are really testing and developing you stick to Beta at best on snap. I am not sure which version that is at.

Docker makes a lot of this pretty easy to do (more flexible than snaps)

Master points to the latest stable. Avoid RCs unless you want to test something - they are the next Stable and are really Betas. Develop is wherever it is.

**Comment by geekgonecrazy** [comment]
Based on silence closing cause not much interest in it
