### ISSUE TITLE
App <-> DB connection error after update DB from v. 3.4 to 3.5

### ISSUE THREAD

**Issue by MathiasRenner** [RocketChat/Rocket.Chat#15571]
### Description:
I use docker-compose to run Rocket Chat (RC). After following the hint that MongoDB version 3.4 is deprecated, upgrading to 3.5 breaks the app.

### Steps to reproduce:

1. Use a Docker compose file similar to the [official example](https://github.com/RocketChat/Rocket.Chat/blob/develop/docker-compose.yml)
1. Use as DB Tag 3.4, bring the project up and running
2. Change DB tag to 3.5
-> error occurs, see log output below:

```
root@...# docker-compose logs -f app
Attaching to backendrocketchat_app_1
app_1  | /app/bundle/programs/server/node_modules/fibers/future.js:313
app_1  |                                                throw(ex);
app_1  |                                                ^
app_1  | 
app_1  | MongoNetworkError: failed to connect to server [db:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 172.21.0.2:27017]
app_1  |     at Pool.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:564:11)
app_1  |     at emitOne (events.js:116:13)
app_1  |     at Pool.emit (events.js:211:7)
app_1  |     at Connection.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:317:12)
app_1  |     at Object.onceWrapper (events.js:317:30)
app_1  |     at emitTwo (events.js:126:13)
app_1  |     at Connection.emit (events.js:214:7)
app_1  |     at Socket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:246:50)
app_1  |     at Object.onceWrapper (events.js:315:30)
app_1  |     at emitOne (events.js:116:13)
app_1  |     at Socket.emit (events.js:211:7)
app_1  |     at emitErrorNT (internal/streams/destroy.js:66:8)
app_1  |     at _combinedTickCallback (internal/process/next_tick.js:139:11)
app_1  |     at process._tickCallback (internal/process/next_tick.js:181:9)
backendrocketchat_app_1 exited with code 1
```
### Expected behavior:

DB upgrade should not break connection to DB.

### Actual behavior:

DB connection is broken. I started another mongo container next to the mongo 3.5 DB container (same docker network) - no problem to connect to the mongo 3.5 DB container. I wonder why the App cannot connect any more.

### Server Setup Information:

- Version of Rocket.Chat Server: latest tag in docker compose
- Operating System: official docker image
- Deployment Method: docker
- Number of Running Instances: 1 
- DB Replicaset Oplog: 1
- NodeJS Version: please see latest rocket chat server version
- MongoDB Version: 3.4 resp. 3.5

**Comment by reetp** [comment]
You have got some number confusion here...

> 3. Change DB tag to 4.5
 
?

Check your mongo logs.

I think you should be moving 3.4 -> 3.6

Can you test that?

**Comment by MathiasRenner** [comment]
@reetp Thanks for your feedback. It must be "3.5", of course. Just fixed it in the description.
I'll test with 3.6. now.

**Comment by MathiasRenner** [comment]
Test done. DB seems to have problem running migration scripts. Logfile: https://pastebin.com/WVs42Y9y

Consequently, the app has same error: https://pastebin.com/pgMK8XwR

**Comment by franckadil** [comment]
Hi I ran trough the same problem this weekend while migrating our stack to a new server. This error is not related with versions of Mongodb, but instead in our case we had the exact same issue but the culprit is the docker network that is changing the IP address for new containers.

If you look closely at the prompt messages when doing a docker-compose up, you will see clearly an indication that the database can't find the host with your previous container IP address.

I have tried to change the system Network IP as suggested but without success. And looking at it for future deployments this is not an adequate solution. 

There is a way though to access the services or containers through hostnames, instead of  IP's. As IP addresses will change upon new containers creation or just simple migration to new hosts. 

The actual docker-compose do a mongo `--host: localhost:27017 ` 

I have found this answer that seems to do what we need, but I need time to be able to test and adapt.

https://stackoverflow.com/questions/25407434/how-to-configure-a-docker-container-to-be-reachable-by-container-ipport-from-ou

**Comment by reetp** [comment]
The error is most likely this:

> IMPORTANT: UPGRADE PROBLEM: The data files need to be fully upgraded to version 3.4 before attempting an upgrade to 3.6; see http://dochub.mongodb.org/core/3.6-upgrade-fcv for more details.

That is unrelated to Rocket per se - it is related to upgrading the underlying mongo DB.

```backendrocketchat_db_1 exited with code 62```

You need to fix your Mongo migration so Mongo starts and then Rocket should be OK.

https://stackoverflow.com/questions/47850004/mongodb-shutting-down-with-code62

I have a sneaking suspicion this started with 3.2 or even earlier?

And the Issue name should probably be:

> ...... error after update DB from v. 3.4 to 3.6

Note with docker. It is a more advanced install and as such an admin should be checking things before just upgrading. I'm not sure what else Rocket can do to assist in that part of the upgrade.

If you want an easier install with less hassle then you should use snaps.

**Comment by rmcnabb3** [comment]
> The error is most likely this:
> 
> > IMPORTANT: UPGRADE PROBLEM: The data files need to be fully upgraded to version 3.4 before attempting an upgrade to 3.6; see http://dochub.mongodb.org/core/3.6-upgrade-fcv for more details.
> 
> That is unrelated to Rocket per se - it is related to upgrading the underlying mongo DB.
> 
> `backendrocketchat_db_1 exited with code 62`
> 
> You need to fix your Mongo migration so Mongo starts and then Rocket should be OK.
> 
> https://stackoverflow.com/questions/47850004/mongodb-shutting-down-with-code62
> 
> I have a sneaking suspicion this started with 3.2 or even earlier?
> 
> And the Issue name should probably be:
> 
> > ...... error after update DB from v. 3.4 to 3.6
> 
> Note with docker. It is a more advanced install and as such an admin should be checking things before just upgrading. I'm not sure what else Rocket can do to assist in that part of the upgrade.
> 
> If you want an easier install with less hassle then you should use snaps.

I had the same issue when upgrading via Snap... once it attempted to update the Mongo instance to 3.6, the Mongo instance actually wouldn't even start. I had to downgrade, realized that as Mongo was running v3.4 it actually was set to compatibility mode for 3.2 (which won't allow for a successful upgrade to 3.6). 

I connected to the Mongo instance and ran this:
db.adminCommand( { setFeatureCompatibilityVersion: "3.4" } )

After that, the Snap upgrade worked fine. Although I'm not sure why this is happening (I've been running a Rocket.Chat snap since 0.57, which I'm guessing has something to do with it after numerous Snap refreshes), that was at least how I had to fix it.

**Comment by reetp** [comment]
> I had the same issue when upgrading via Snap... once it attempted to update the Mongo instance to 3.6, the Mongo instance actually wouldn't even start. I had to downgrade, realized that as Mongo was running v3.4 it actually was set to compatibility mode for 3.2 (which won't allow for a successful upgrade to 3.6).
> 

Please note that this was a docker install, and not snap. Please don't conflate issues unless you are absolutely sure they are related. IT can just make things worse.

Snaps do their own thing with their Mongo db so I'm not sure what you would be doing attempting to modify Mongo unless you had been seriously hacking about in your snap, and I'm not sure what it has to do with this particular installation.

**Comment by rmcnabb3** [comment]
> Please note that this was a docker install, and not snap. Please don't conflate issues unless you are absolutely sure they are related. IT can just make things worse.
> 
> Snaps do their own thing with their Mongo db so I'm not sure what you would be doing attempting to modify Mongo unless you had been seriously hacking about in your snap, and I'm not sure what it has to do with this particular installation.

I received the exact same error from Mongo during my Snap upgrade that OP got in their Mongo logs, which caused Rocket.chat to fail in connecting to the Database...

"db_1   | 2019-10-13T18:08:09.241+0000 F CONTROL  [initandlisten] ** IMPORTANT: UPGRADE PROBLEM: The data files need to be fully upgraded to version 3.4 before attempting an upgrade to 3.6; see http://dochub.mongodb.org/core/3.6-upgrade-fcv for more details."

**Comment by reetp** [comment]
> I received the exact same error from Mongo during my Snap upgrade that OP got in their Mongo logs, which caused Rocket.chat to fail in connecting to the Database...

You may have have done but it does not mean it is exactly related here, strangely enough.......

(I'm not sure what you are doing with snaps because I believe current stable is on 3.4.x so I can only presume that if you have comments about Mongo 3.6 you have been playing with Beta or Edge in which case you may well get issues. Upgrading the DB can be tricky. I am also not sure why you would be messing about with Mongo regardless on a snap - a snap should sort out Mongo itself. All of which is totally OT for this users issue which relates to docker based Mongo)

> Additionally you specifically recommended use of snaps to reduce hassle, which I've found not to be the case.

Because that is the recommended policy of Rocket.Chat and which works without issues for the vast majority of users - remember that the significant a majority of Rocket users use snaps. YMMV.

https://rocket.chat/docs/installation/manual-installation/ubuntu/

If you have issues with snaps then ask in https://open.rocket.chat/channel/ubuntu-snap

**Comment by MathiasRenner** [comment]
@reetp Thanks for your pointers! @rmcnabb3 Esp. with your tip, I got it fixed, thank you!
> I connected to the Mongo instance and ran this:
> db.adminCommand( { setFeatureCompatibilityVersion: "3.4" } )

Then I did the following in a while loop, I am now running Mongo v4 latest!
- mongo --repair
- db.adminCommand( { setFeatureCompatibilityVersion: "3.4" } ) (in next loop -> 3.6)
- restart DB and App

**Comment by clauded** [comment]
Here's how I fixed it with a snap installation:

`service snap.rocketchat-server.rocketchat-server stop
service snap.rocketchat-server.rocketchat-mongo stop

cd /snap/rocketchat-server/current/bin
./mongo --version # should report 3.6
./mongod --repair --dbpath=/var/snap/rocketchat-server/common/
snap list --all rocketchat-server
snap revert --revision=1416 rocketchat-server
cd ../../1416/bin/
./mongo --version # should report 3.4
./mongo
db.adminCommand( { setFeatureCompatibilityVersion: "3.4" } )
exit
snap revert --revision=1414 rocketchat-server
`
