### ISSUE TITLE
Is there a way to refresh the loginToken to force re-login from the browser?

### ISSUE THREAD

**Issue by nullbio** [RocketChat/Rocket.Chat#15788]
We're using the embedded form of RocketChat in our website. Basically using it as a chat server so registered website users can talk to other users who they've been given access to communicate with. When using the rocketchat iframe and the `API URL` and `API Method` as documented here: https://rocket.chat/docs/developer-guides/iframe-integration/authentication/ - we're able to log the website user into their rocketChat user, and allow them to communicate in chats, by passing along the `loginToken` from our backend server. 

The problem is that a users website session can expire automatically if they haven't visited the website in a little while, and then when they log in again, if they log in as another user, since the sessionStorage still has the old users `loginToken` then it logs the old user into the chat, instead of the new user. This is an issue for people who share a PC or have multiple accounts of our website, for example.

We were trying to think of ways to clear the `loginToken` from the sessionStorage when a person logs in to the website, so that it would force rocketChat to create a new one, and therefore log in the correct user if need-be. One of the big issues we're finding is the fact that our rocketChat is hosted on a different port, so we can't easily clear the sessionStorage from the parent domain due to cross-site restrictions such as CORS. We tried to use `document.domain` to work around this problem, but then we found the problem that we can't clear the `loginToken` from the sessionStorage unless an active iframe is present from the rocketChat domain, otherwise the browser can't find `loginToken` in the sessionStorage. Embedding an iframe just so we could clear it seemed to have issues too, as that iframe would then try and log in itself, and it would seem to cause multiple login attempts and "invalid user" errors inside the iframe.

We also tried to embed a `"src=rocketchaturl.com/logout"` iframe on website login, to kick the old user off so that rocketChat would request a new token, but apparently this also does not clear the sessionStorage, so it did not work because it would continue to use the old `loginToken` and not attempt to get a new one.

Does anyone know of a solution to this problem?

**Comment by reetp** [comment]
Admin-> Accounts
Login Expiration
Forget User Session on Window Close

Note that this really seems to be a support issue and not a bug. You should really be asking elsewhere:

https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md
> Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues
> If you have questions or are looking for help/support please see: https://rocket.chat/docs/getting-support

**Comment by nullbio** [comment]
Did you want me to move it there? Since you've responded, that setting does not help us. It's possible for a users session to expire without them closing the browser window, which takes them back to the login screen. If they were then to log in again but with a different user it'd still have the old `loginToken`.

**Comment by nullbio** [comment]
Just wanted to add that this is also an open issue here and hasn't received any activity: https://github.com/RocketChat/Rocket.Chat/issues/15064

**Comment by aarondl** [comment]
@reetp Could you possibly tell us how to proceed here? Sorry we didn't follow your issue template. This particular issue is not exactly a bug, but more of a gap in functionality in one of the features.

https://rocket.chat/docs/developer-guides/iframe-integration/authentication/

We already found and were experimenting with the feature you pointed us at (Forget User Session on Window Close) unfortunately this doesn't solve the issue as users will not always close their window (many times they'd just close the tab) and therefore it's not sufficient to be able to reliably log them out.

The main problem of course is that there's no way for us to clear this login token that Rocket Chat has put into local storage. Meaning that when a user logs out/expires of the main website session, the Rocket Chat token still persists and when they log in to the main site again (as a different user) Rocket Chat doesn't even attempt to get a new token, it simply uses the one it already has which belongs to the old user.

This seems like a fairly serious issue that I believe affects every user of iframe auth API (unless we've somehow implemented it incorrectly?) and presents a security risk.

I'd be happy to file a new bug with excruciating detail and proper version numbers if that makes this process easier. If necessary I could create a contained demo that demonstrates the issue as well. Just let us know how you'd like us to continue here and we'll help out as best as we can.

**Comment by reetp** [comment]
> Could you possibly tell us how to proceed here? 

I'm not a dev. I just help triage.

> Sorry we didn't follow your issue template. 
> I'd be happy to file a new bug with excruciating detail and proper version numbers if that makes this process easier. If necessary I could create a contained demo that demonstrates the issue as well. Just let us know how you'd like us to continue here and we'll help out as best as we can.

You don't need a new bug as there is 15064 already, and now this. Nor do you need to give excruciating details to start with.

The first thing to do to attract attention is fill out a template with some basic details. It helps sort the wheat from the chaff.

Knowing your server version & deployment type tells the devs whether this is a situation on the current versions or one from 2 years ago that may have been fixed (plenty of people report 'bugs' from old versions that have already been fixed).

So my suggestion is to do that first.

**Comment by aarondl** [comment]
### Description:

There is no mechanism to invalidate a Rocket Chat user who is logged in via the use of the iframe auth API.

This leaves a security hole where even if the client's main-site session it used to retrieve a Rocket Chat token expires or is otherwise destroyed the Rocket Chat token persists in local storage.

The reason this is a security hole is that on a new log in to the main-site as a different user, Rocket Chat remains logged in to the old Rocket Chat session and the newly logged in main-site user can now interact with the old user's chats instead of his own.

### Steps to reproduce:

1. Set up project with iframe auth integration
2. Log user in to site
3. Open Rocket Chat iframe (this will make a call to iframe auth API URL to get Rocket Chat token)
4. Delete your main-site session cookie in any way (logout, session expiry, manual deletion)
5. Log user in to site again
6. Open Rocket Chat iframe (this will already be logged in as the previous user)

### Expected behavior:

By some mechanism (unsure what yet) the user should be logged out of the Rocket Chat session.

Keep in mind the "logout when window is closed" option in Rocket Chat is not sufficient as it does not cover important scenarios like closing a tab, or main-site session expiration.

### Actual behavior:

Newly logged in user keeps the old user's Rocket Chat session, enabling the new user to access the chats of the old user.

### Server Setup Information:

- Version of Rocket.Chat Server: 6a88d449855f (Docker Tag: latest, about 8 weeks ago)
- Operating System: N/A
- Deployment Method: Docker
- Number of Running Instances: N/A
- DB Replicaset Oplog: N/A
- NodeJS Version: See Docker image tag
- MongoDB Version: mongo:4.0 (Docker, about 7 weeks old)

### Client Setup Information

- Desktop App or Browser Version: Tested on Firefox/Chrome
- Operating System: Linux

### Additional context

This is less of a bug, and more functionality that's missing to be able to somehow invalidate the Rocket Chat session inside local storage for when the session has gone away.

### Relevant logs:

None are required afaict, but would be happy to provide them if necessary.

**Comment by reetp** [comment]
OK, thank you for the comprehensive description, but please fill in the missing details correctly as asked.

> (Docker Tag: latest, about 8 weeks ago)

So which version is that??

"Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues"

> Before reporting a new issue
>    Read the Documentation carefully all the way through.
>    **Make sure you are running the latest version of Rocket.Chat**. It’s very likely simply updating will resolve your issue.

Now, I know it probably **won't** fix your issue, but there is a method you need to follow. Rocket moves very fast and there will be a lot of changes even in 8 weeks. So, please confirm this happens on 'latest' - as of today that is v2.3.0

Just do as asked, give all the right info (don't just put N/A because you think it is irrelevant) , and let the devs then figure it out.

**Comment by aarondl** [comment]
Hi @reetp. Thanks for getting back to me. I amended the report above.

**Comment by salviof** [comment]
já existe uma solução para este problema?

**Comment by rajm** [comment]
> @reetp Could you possibly tell us how to proceed here? Sorry we didn't follow your issue template. This particular issue is not exactly a bug, but more of a gap in functionality in one of the features.
> 
> https://rocket.chat/docs/developer-guides/iframe-integration/authentication/
> 
> We already found and were experimenting with the feature you pointed us at (Forget User Session on Window Close) unfortunately this doesn't solve the issue as users will not always close their window (many times they'd just close the tab) and therefore it's not sufficient to be able to reliably log them out.
> 
> The main problem of course is that there's no way for us to clear this login token that Rocket Chat has put into local storage. Meaning that when a user logs out/expires of the main website session, the Rocket Chat token still persists and when they log in to the main site again (as a different user) Rocket Chat doesn't even attempt to get a new token, it simply uses the one it already has which belongs to the old user.
> 
> This seems like a fairly serious issue that I believe affects every user of iframe auth API (unless we've somehow implemented it incorrectly?) and presents a security risk.
> 
> I'd be happy to file a new bug with excruciating detail and proper version numbers if that makes this process easier. If necessary I could create a contained demo that demonstrates the issue as well. Just let us know how you'd like us to continue here and we'll help out as best as we can.

You need to store the login token in your application and user login rest api call to invalidate the token, and also try to use logout iframe commands...

right now these two optoins are only available.. it mostly logs you out... sometimes not..

**Comment by aarondl** [comment]
Hi @rajm. The main problem that we have is that we don't have a way of knowing when the user has been logged out of the application (session expiry) and so there's no actions we can perform when the expiry occurs.

We can't rely on storing the token to invalidate because the session expires meaning all our session data is gone, and we can't store it in the database because there's no session to help us locate those records in the database (because it's a different user logging in the second time, not the same one which is what makes it tricky).

The logout iframe commands occur too late in the lifecycle of the iframe and makes for an undesirable user experience.

We thought of some potential solutions:
1. Clear the client side Rocket Chat tokens on login (with some new API)
    * Perhaps an additional query string parameter `/group/somename?layout=embedded&resetlogins=true` could force the reset of the credentials.
    * This could be done by accessing a special iframe that rocket chat could serve `/destroyalltokens` that would essentially do a `localStorage.clear(); sessionStorage.clear();`
2. Make Rocket chat optionally authenticate each time with the `API_URL` and do not store the token in localStorage/sessionStorage at all. This effectively ties the rocket chat token to the life of the iframe and that's much more manageable.

**Comment by romansidorov** [comment]
@nullbio @aarondl @rajm Hey everyone! Does somebody have a proper solution for this issue?

**Comment by julienchabanon** [comment]
Hello guys! 
I am in the same situation, I am not in a monolithic environment. My front-end and my back-end API do not share the same session. Because of this, I can't use the IFrame API auth endpoint in order to authenticate as it should rely on cookies as this is mentionned in the doc: "2. The API should validate your own session via cookies"
[https://docs.rocket.chat/guides/administrator-guides/misc.-admin-guides/authentication/single-sign-on-iframe](url)

Does someone have a workaround for this? Thank you

**Comment by johncrisp** [comment]
Please see here here you were answered.

https://github.com/RocketChat/Rocket.Chat/issues/22630

**Comment by julienchabanon** [comment]
Hello guys! I am the one that opened the issue #22630.

Here is how I managed to work around this:

> It seems that I managed to work around this and get rid of this API URL thing.
> 
> In rocket IFrame URL, under accounts/Iframe, my backend now respond with:
> <script> window.parent.postMessage({ event: 'try-iframe-login' }, '#{RocketChatHelper::ROCKET_URL}');</script>
> This does not require a valid session as it does not need to call current_user to get a token or something.
> Still under accounts/Iframe, API URL can now be blank.
> In my IFrame src URL in my frontend app, I am now passing resumeToken as a GET parameter as found here:
> https://docs.rocket.chat/guides/administrator-guides/misc.-admin-guides/authentication
> Before passing this resume token (authToken), I query my backend using oauth where I use rocketchat API in order to login my user, get this rocketchat authToken and send it back to my frontend.
> 
> So far it works well. I saw some people having the same issue as me so I hope it will helps :)
> Rocketchat team, a proper documentation would be appreciated.
> 

I hope it will helps! Thank you!
