### ISSUE TITLE
Auto Updating Rocket.Chat Deployment

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#1581]
Been looking at how different platforms auto update.  Trying to see what we would need to do to accomplish this.  We want to make the process as simple as possible.

Chrome seems to kind of kick this whole Evergreen thing off.  They use Update Channels.

Here are a couple of examples of some auto updating.

CoreOS does this at the OS level: https://github.com/coreos/update_engine
Atom (our very own desktop client shares electron in common with): https://github.com/atom/electron/blob/master/docs/api/auto-updater.md

I would love for Rocket.Chat to be deployed once and be able to auto update its self.  Of course with user interaction if need be. 

I'd like to see thoughts and ideas.  Maybe spec this out, see how feasible this is?

Tag: @RocketChat/core 
##

**Comment by Sing-Li** [comment]
:+1:   

Our good friends over at Sandstorm has one of the smoothest, most maintenance free, Meteor app auto-update I've ever seen.   Basically I've only ever installed my Sandstorm server once in my life - and (50 gazillion versions and almost two years later) it is still up and running the latest.   

I'm sure things are not quite as smooth underneath the hood. @kentonv, @jparyani and  @paulproteus - do  you mind sharing some design and best practices tips with us?   TIA

**Comment by geekgonecrazy** [comment]
Ah sandstorm as well that one slipped my mind.  I'd be super curious to see how they do this as well

**Comment by kentonv** [comment]
Hmm.

Well... First I should point out that users running Rocket.Chat *on* Sandstorm already get auto-updates (of both Sandstorm and Rocket.Chat). So I recommend people use Rocket.Chat on Sandstorm and be done with it. ;)

But to answer the technical question: Sandstorm really sees itself as an operating system. You can install it on an existing Linux server running some other distro, but what Sandstorm does here is essentially set up its own little world in a corner and self-containerizes into it. Sandstorm downloads all its own dependencies -- even its own libc -- to avoid any dependence on the local system. This makes auto-updates easy because Sandstorm owns its whole directory structure and can steamroll the thing whenever it likes.

Probably, though, it doesn't make a whole lot of sense for every app to behave this way. Sandstorm is trying to bootstrap everything from a very low level because Sandstorm is itself a platform. It is a package manager, and it is a container engine. So it wouldn't make sense to have Sandstorm itself require, say, Docker, since that would mean every Sandstorm user ends up with two container engines running on top of each other, which would be rather silly.

But for a higher-level app like Rocket.Chat, I would argue that you really should aim to be a good citizen of the platform you are targeting. If you're trying to ship as a Docker image, for example, then I would look for existing tools for auto-updating Docker apps (I'm not sure what that is but I imagine it exists). If you want to ship as a Debian package, then provide an apt source so that people can update via apt-get upgrade. Etc.

If you find that there aren't good tools for auto-updating on some platforms, that is the fault of those platforms, and I would argue that you shouldn't try to make it your job to solve the problem specifically for Rocket.Chat.

But that's my opinion. If you really want to see Sandstorm's approach to auto-updates, it's mostly found here:

https://github.com/sandstorm-io/sandstorm/blob/master/src/sandstorm/run-bundle.c++

Also relevant is our install script:

https://github.com/sandstorm-io/sandstorm/blob/master/install.sh

Unfortunately, this stuff isn't very reusable as-is. Perhaps a reusable tool could be factored out of it with a bunch of work, but I wouldn't think it's something you guys would want to spend your time on.

**Comment by geekgonecrazy** [comment]
@kentonv thank you for taking the time to write such a well written reply.  I really appreciate it.  

I definitely agree that if ran with docker, we need a docker approach to updating.  If we deploy via debian package we should update via a repo.  Etc.

I personally am very interested in taking a peek at the work you guys have done.  I find it very fascinating, and well done. But, I don't think we need something that complicated for updating Rocket.Chat :grin:

Maybe a wordpress style updating would be fitting.  Polls every so often to see if there is an update.  Alerts them, and if we can pull it off execute another script to download the update.  Then do a process kill / spawn.  Or just simply tell them to open command line and do `./update.sh`

**Comment by rasos** [comment]
Just some feedback from a provider perspective: We do not really like the auto-update features of Wordpress - you never know when it breaks with all the themes and plugins customers apply. Sysadmins prefer the rather conservative apt-get upgrade way. The  Ansible auto-update option for RocketChat way was also not clear to our syadmin, he did it manually recently.

**Comment by geekgonecrazy** [comment]
I think we now have the evergreen case covered.  Snaps auto update.  We also now have update available alerts for admins.  So I think this can be closed
