### ISSUE TITLE
Transfering message to an offline livechat agent

### ISSUE THREAD

**Issue by klaus96** [RocketChat/Rocket.Chat#15875]
Hello,
I would like to transfer a livechat message to an offline livechat agent. Because till now when I go to transfer message, it  only shows the agents who are online.
Thanks in advance

**Comment by renatobecker** [comment]
I'm not sure I got it, could you give a bit more context about your request?
I mean.. Do you want to send a message to an agent who was attending a conversation and goes offline?

Thanks!

**Comment by klaus96** [comment]
Hi, Assuming an agent receives a message through the livechat and he does'nt have knowledges about the message's topic and then wants to transfer it to another agent, who might be offline.
 So far the app shows only online agents when it is about transfering a livechat message.
 I hope I could make myself more understandable. Thank you

**Comment by renatobecker** [comment]
> Hi, Assuming an agent receives a message through the livechat and he does'nt have knowledges about the message's topic and then wants to transfer it to another agent, who might be offline.
> So far the app shows only online agents when it is about transfering a livechat message.
> I hope I could make myself more understandable. Thank you

Yeah, I got it.
The fact is we don't agree that it would be a good idea to forward conversations to offline agents, mainly because there is a Livechat user(guest or visitor) waiting for a reply and offline agents might not be able to answer.
To ensure the best Livechat user experience, we need to continue allowing the forwarding chats to online agents only.

**Comment by klaus96** [comment]
Hi, alright thank you . Now I have to find a way to explain it to my boss :sweat_smile:
