### ISSUE TITLE
RocketChat team does not react to bug reports

### ISSUE THREAD

**Issue by DmytroPuzhay** [RocketChat/Rocket.Chat#15924]
### Steps to reproduce:

1. Report a bug

### Expected behavior:

Bug is reacted on by the team, analyzed/prioritized and planned to be fixed

### Actual behavior:

6 moths since reporting bug stays in the following state:

Assignees No one assigned
Labels None yet
Projects None yet
Milestone No milestone

**Comment by reetp** [comment]
@rocket-cat close

This is repo is reserved for bugs in Rocket.Chat

If you have comments to make then use the appropriate channels - eg forums and open.rocket.chat

Please note that this is Open Source. There is no guarantee of anything, and the dev team are under no more compunction to fix something than you are.

They have their own priorities which may not align with yours. They do fix Issues, but in their own time with their own priorities to their paying customers (see the releases page for bugs fixed with each release). That is the nature of Open Source.

If you have a support contract you can contact support for their assistance.

If you don't like the way things are you can fork and work on your own version and fix all the bugs you want - that's the great thing about Open Source.
