### ISSUE TITLE
"Hide roles" not working

### ISSUE THREAD

**Issue by Perflyst** [RocketChat/Rocket.Chat#15931]
### Description:

Setting "Hide roles" in user preferences to "True" is not working.

### Steps to reproduce:

1. Add roles to users
2. Go into user preferences and set "Hide roles" to "True"

### Expected behavior:

Roles should be hidden in the chat window.

### Actual behavior:

Roles are shown, same as if "Hide roles" would be disabled.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.3.0
- Operating System: Debian 9.11
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v8.11.3
- MongoDB Version: 3.6.16

### Client Setup Information

- Desktop App or Browser Version: Desktop and Firefox
- Operating System: Arch / Ubuntu

### Relevant logs:

No errors are logged about this issue.

**Comment by aashaypalliwar** [comment]
Hi! I would like to work on this.

**Comment by sairajsawant** [comment]
Can I work on this? I already made some progress.

**Comment by sairajsawant** [comment]
@ggazzo can you please review my PR?

**Comment by rodrigok** [comment]
@Perflyst the **hide roles** setting will affect the messages rendering only since it's under the **message's section** in the user's preference panel.

![Screen Shot 2019-12-09 at 9 12 06 AM](https://user-images.githubusercontent.com/234261/70435141-cb6a1400-1a64-11ea-99ae-837317d436be.png)

Is this issue related to a but where the roles are still be shown in messages, or you expect to hide the roles in other parts of the application?

**Comment by Perflyst** [comment]
The roles are shown behind the name in the chat window (group, private message etc)
This was not the case before the update to latest version.

**Comment by rodrigok** [comment]
@Perflyst can you add a screenshot here demonstrating the issue?

**Comment by Perflyst** [comment]
Of course, see the screenshot below
![rc_roles_bug](https://user-images.githubusercontent.com/26308977/70847727-8f1d2600-1e5f-11ea-903d-a88d77dee458.png)

**Comment by subham103** [comment]
Can anybody explain to me what is the real issue here? I have tested it and the behavior I came up with was:
* when `hide roles` is true for a user (say user1 **role1**) then he can't see anybody's role in the chat area but he can see the roles of other users (say user2 **role2**)in the side panel.
* But again in side-panel, strange behavior is, he can't see the role of himself i.e. **role2** but can see other's role **role1**.

**Comment by Perflyst** [comment]
This issue appears to be fixed after updating to 2.4.1

The issue was that if "Hide roles" in user settings was set to "True" all the roles behind a username were still shown. It looked the same, doesnt matter if this user settings was set to True or False.
