### ISSUE TITLE
how to custom field ui on register page

### ISSUE THREAD

**Issue by jasonz1987** [RocketChat/Rocket.Chat#15971]
Q1: i've add custom filed in admin page ,and it's shown on register page.

but the ui is not same as the other fields?

![image](https://user-images.githubusercontent.com/7090036/70765147-d2f72900-1d94-11ea-9dc5-8f9772a7b0b3.png)

Q2: can i disable email filed for user auth/register?

i want to use my own custom filed?

**Comment by MartinSchoeler** [comment]
Hey, looks like you seem to be looking for support. You will have a better chance of getting help if you go to one of the places listed in [here](https://rocket.chat/docs/getting-support/#community-support) since github is not the best place to ask for support. For now i will be closing this issue, as it does not fit our issue guidelines
