### ISSUE TITLE
Drag n' Drop doesn't go away after uploading to thread

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat#15980]
### Description:
When dragging and dropping to a thread after dragging over the main channel, the main channel never goes away.

### Steps to reproduce:

1. Drag a file over the main channel into a thread.
2. Upload the file

### Expected behavior:

The drag to upload goes away.

### Actual behavior:

Drag to upload is stuck on the screen and requires reloading.
![drag-upload-doesnt-close](https://user-images.githubusercontent.com/6295044/70842413-62322a00-1df1-11ea-91c6-93be25684aa4.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.3.1 dde5b16dbe00cc4c5e88527e725773f78c0ced66
- Operating System: CentOS 7

**Comment by aKn1ghtOut** [comment]
If nobody is working on this, I'll take this up

**Comment by aKn1ghtOut** [comment]
This one is not exactly a bug, but it's more of a browser issue since the "dragleave" event isn't getting fired when you hover over the partition area like that. We can however, still implement a solution to this that might not be very efficient by catching mouseenter and mouseleave events if dragover class is enabled, and processing those too as long as the dragover class is active. In this case, since it is not directly Rocket.Chat that the problem originates from, is an additional check warranted though?

**Comment by wreiske** [comment]
I would say once a dragleave has been fired, or when the attachment box pops up, it should close out all the ope drag dialogs. That way even if the dragleave doesn't fire, one the attachment popup fires, it could close the dialog.
