### ISSUE TITLE
Password option missing while create any local user or edit local user.

### ISSUE THREAD

**Issue by jowhor** [RocketChat/Rocket.Chat#16011]
### Steps to reproduce:

1. Go To Administrator
2.  Select User
3. Create a user or edit any user

### Expected behavior:

Password set input option should be available.

### Actual behavior:

Password input box missing.

![image](https://user-images.githubusercontent.com/59007667/71073751-66b46500-219a-11ea-8fc6-5166ff936723.png)

![image](https://user-images.githubusercontent.com/59007667/71073839-906d8c00-219a-11ea-80be-0903738d99b4.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.3.2
- Operating System: Ubuntu 16.04.6 LTS
- Deployment Method: Manual Installaion
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: v8.11.3
- MongoDB Version: 3.6.16

### Client Setup Information

- Desktop App or Browser Version: Desktop App 2.17.1, Chrome Browser Version 79.0.3945.88 (Official Build) (64-bit)
- Operating System: Windows 10

**Comment by MartinSchoeler** [comment]
This is intentional (done in https://github.com/RocketChat/Rocket.Chat/pull/15818), now you should use the `set random password` option, that will create a random password and send it to the user. I will be closing this now. If you want to discuss the feature functionality, please use our [forums](forums.rocket.chat) or [open server](open.rocket.chat). Thanks!
