### ISSUE TITLE
We need translators

### ISSUE THREAD

**Issue by dudizilla** [RocketChat/Rocket.Chat#16106]
We need people interested in translating the button to change the language in login/register page.

When the page is in English, on the button is written 'English Version' in the selected language. We need to change this to '*Selected Language* Version'
![Screen Shot 2019-12-30 at 9 58 45 AM](https://user-images.githubusercontent.com/42151808/71583160-0a333d00-2aec-11ea-8394-48321b0a6b9c.png)

**Comment by mhaluska** [comment]
Czech version: Česká verze

**Comment by MartinSchoeler** [comment]
we can simply add the name of the language before the "version" word, we should have that already translated since the language names on the language list are already translated to the right language

**Comment by kaiiiiiiiii** [comment]
> we can simply add the name of the language before the "version" word, we should have that already translated since the language names on the language list are already translated to the right language

Nope, you shouldn’t do that. It’s maybe fine for most of the languages, but there’s for example german, where the wording is a bit different.

German = Deutsch
German Version = Deutsche Version

**Comment by TheG0dfath3r** [comment]
Hindi - 
हिंदी संस्करण

**Comment by Gummikavalier** [comment]
Finnish version: "Suomenkielinen versio"

Finnish as in person = "Suomalainen"
Finnish as in language = "Suomenkielinen"

**Comment by ashwaniYDV** [comment]
@mariaeduardacunha @MartinSchoeler  I am not getting the issue. Do we need a select tag instead of the button so that a user can come and select the language of their choice and then proceed?
The current action is that if Admin selects the language of the server to French (for example), then when user visits the login page, they'll see the "English Version" written there. When they click on english version, "Version Anglaise" is written on the button.

I want to work on it.
