### ISSUE TITLE
Frontend doesn't update user's Role after "setting/removing" the role in members list

### ISSUE THREAD

**Issue by marianotribuj** [RocketChat/Rocket.Chat#16124]
The issue can be reproduced on open.rocket.chat:

- Go to members list of a group
- Choose a user, and click on "Set As Owner"
- The green toast is shown saying that the users was set as Owner, and the message in the room appears saying "The user .... was set owner....".
- When you open the contextual menu again on the same user, it allows you the set him as owner "again", and the toast shows an error "error-user-already-owner".

**Comment by marianotribuj** [comment]
The same thing happens when you go to User Info through the Members list, and click Set As Owner/Remove as Owner. The link doesn't update.

The strange thing is that a local version running on my computer (with meteor npm start) works well...

**Comment by cprice-kgi** [comment]
would it be possible to re-open this issue? we are experiencing the same effects. this functionality works fine when the server is deployed on localhost, but once in our dev environment (using same version of Meteor), these actions operate as described above. the only difference i can think of is our DEV environment runs behind an nginx reverse proxy. i'm certain it's a caching issue in the browser, since a CTRL-SHIFT reload does update the options in the action menu correctly. however, without the force refresh, the options get our of sync with the current owner/moderator/leader settings.

none of this is an issue in using localhost and the same exact codebase and version of meteor. any suggestions?

**Comment by cprice-kgi** [comment]
one more thing to mention. we are also using the methods described here to run multiple instances (only in DEV, not localhost obviously):
https://docs.rocket.chat/installation/manual-installation/multiple-instances-to-improve-performance

perhaps a setting in here could be affecting the caching. i have a feeling it's either in here or the nginx conf since these are the only differences between localhost and DEV.
