### ISSUE TITLE
SMTP not working

### ISSUE THREAD

**Issue by citylocalpro** [RocketChat/Rocket.Chat#16125]
I am using rocket chat version 2.3.1 on Ubuntu 18.04.3 LTS. I have configured SMTP with Cpanel email service that was working fine from 1 month. But now SMTP not sending email. I have checked all configuration i also have checked with gmail SMTP. I am not getting any error. When i send test mail, i got notification that email sent successfully but i am not getting the email.

**Comment by MartinSchoeler** [comment]
Hey, looks like you are looking for support. You will have a better chance of getting help if you go to one of the places listed in [here](https://rocket.chat/docs/getting-support/#community-support) since github is not the best place to ask for support. For now i will be closing this issue, as it does not fit our issue guidelines
