### ISSUE TITLE
HXXP and HXXPS linkification

### ISSUE THREAD

**Issue by ajkerzner** [RocketChat/Rocket.Chat#16146]
### Description:

hxxp://<url> and hxxps://<url> should not be linkified.

### Steps to reproduce:

1. Enter any URL, like hxxps://www.google.com , in chat

### Expected behavior:

The URL should NOT be linkified.

### Actual behavior:

The URL is linkified.

### Notes

HXXP and HXXPS are commonly used to send a URL as plaintext and prevent linkification. Common use cases are websites with malware, or known invalid websites.

**Comment by ashwaniYDV** [comment]
I would like to work upon it

**Comment by ajkerzner** [comment]
I created https://github.com/markedjs/marked/issues/1596 .

**Comment by UziTech** [comment]
I don't think this is an issue in marked since it only auto links `ftp://`, `http://`, and `https://` links.

[demo](https://marked.js.org/demo/?text=ftp%3A%2F%2Fexample.com%0A%0Ahttp%3A%2F%2Fexample.com%0A%0Ahttps%3A%2F%2Fexample.com%0A%0Ahxxp%3A%2F%2Fexample.com%0A%0Ahxxps%3A%2F%2Fexample.com%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

**Comment by ajkerzner** [comment]
I concur. Something else is probably going on.... Does RocketChat do anything else around Marked?
