### ISSUE TITLE
Global search across channels

### ISSUE THREAD

**Issue by gwillen** [RocketChat/Rocket.Chat#1615]
As far as I can tell, search right now functions on a per-channel basis. Is that true? Is there a way to search all chat history globally? This seems extremely useful, and probably not hard to implement.
##

**Comment by jjayala1** [comment]
I was going to ask the same... It's really a must.

**Comment by bsdcon** [comment]
+1 Most of the competing products offer this useful feature.

**Comment by miscs** [comment]
+1

**Comment by erikap** [comment]
+1

**Comment by mattbk** [comment]
+1

**Comment by clorichel** [comment]
Same here ! We've been asking ourselves "where it could be" without even thinking it was not an existing functionality...

That's a real drawback I'm pretty sure the awesome team here will take care of ! Many thanks for your good work guys ;)

**Comment by Floyd25** [comment]
+1

**Comment by hkuich** [comment]
+1

**Comment by hvma** [comment]
+1

**Comment by rkje** [comment]
+1

**Comment by heppstux** [comment]
+1

**Comment by rore** [comment]
Seems like a pretty important feature... I'm surprised it doesn't exist.

**Comment by twhiting** [comment]
+1

**Comment by vladimirralev** [comment]
+1

**Comment by jmccaughey** [comment]
+1

**Comment by xmassacre** [comment]
+1

**Comment by CeeDubbVA** [comment]
+1

**Comment by pablojavier** [comment]
+1

**Comment by Ankhesa** [comment]
+1

**Comment by naw3l** [comment]
+1

**Comment by deblike** [comment]
+1

**Comment by KoAi** [comment]
Just looking for how to activate this functionality, I find this issue. So please, think about it :)

**Comment by rammjet** [comment]
+1 - Really, really need this function.

**Comment by davidlevy** [comment]
+1

**Comment by salamachinas** [comment]
+1

**Comment by derekblankmccoy** [comment]
+1

**Comment by LeDistordu** [comment]
+1

**Comment by danpospisil** [comment]
+1

**Comment by sabahaghighi** [comment]
+1

**Comment by Eloo** [comment]
+1

**Comment by JensvdHeydt** [comment]
As much as I appreciate all the +1 it doesn't seem as if a developer is willing to introduce this feature, right?

**Comment by tarnover** [comment]
+1

**Comment by gspees** [comment]
+1

**Comment by grohin** [comment]
What will be cost of developing global search feature.

**Comment by rammjet** [comment]
Maybe it would help for us to clarify WHY we want a global search.  I have a use case that is probably different from everyone else.  I am using the chat app as a digital notebook.  Accessible across devices.  Interactions can add clips of data.  Replace Evernote and the ilk.  I am a team of one.  Each room/channel is another subject.  Posts to that subject contain text, video, audio, images and files.  Currently I am using Mattermost but I think RocketChat would be better.  But only if I can get global search.  Otherwise, it won't work.  The model I'm using is based on the blog post by Tarun Gangwani titled "Using Slack as a Digital Notebook".  http://www.tarun.info/prototype/2015/11/06/using-slack-as-a-digital-notebook/

**Comment by timandovo** [comment]
+1

**Comment by RuizPierreC** [comment]
+1

**Comment by msbentley** [comment]
Another +1. Sometimes a message is put in the wrong channel, or it could have been in one of several channels. Having to click each plausible channel and search each one is not a usable solution when the number of channels is more than a handful...

**Comment by nebnes** [comment]
+1

**Comment by timandovo** [comment]
+25  I ran it past our team of 25 who are using RocketChat and our combined opinion is that the lack of a global search is a 'deal breaker'.

**Comment by AndreyAntipov** [comment]
I'd like to implement that feature, that bounty is still relevant?

https://www.bountysource.com/issues/28998888-global-search-across-channels

**Comment by timandovo** [comment]
I would be happy to pay a bounty of $200 to get this feature implemented.

**Comment by snaiperskaya96** [comment]
@timandovo Feel free to increment the bounty :)
I'm looking forward to work on this

**Comment by timandovo** [comment]
Is there anybody else in this thread willing to contribute towards the bounty?
There are a huge number of us who see this as a vital feature, let's get it sorted!!!

**Comment by mjmst74** [comment]
+1

**Comment by timandovo** [comment]
This is such a fundamental feature that causes daily pain.  Is there anyone else able to join me in offering a bounty in order to get this job completed?

**Comment by ryepdx** [comment]
Likewise would like such a feature. Have been considering just writing a utility to handle it. What's the blocker here?

**Comment by timandovo** [comment]
I am getting to the point of desperation now.  I am incredibly happy with RocketChat, it's superb in so many ways, but I have a team of 25 and I am getting almost daily complaints about the lack of a global search with people telling me it is costing them a huge amount of time as they search through multiple channels one by one looking for a particular message.  This problem only gets worse the more we use the program and the more channels and messages we have.
I will increase my bounty offer if someone will sort this.
Surely there are some other people out there who would be willing to join me in offering a bounty?

**Comment by dirkmueller** [comment]
+1

**Comment by toabctl** [comment]
+1

**Comment by alankessler** [comment]
+1

**Comment by pshute** [comment]
+1

Been with Rocket.Chat a week, and we're starting to need this already.

If implemented, it would be nice to have a way of restricting the search to one channel too.

**Comment by heppstux** [comment]
thus, not using rocket chat anymore.

**Comment by lukaszniemkiewicz** [comment]
+1

**Comment by jusfeel** [comment]
I guess this feature is delayed is because it is not easy as it is in terms the word involved which more than 5 days in my estimation. 

1- 2 Days for the underneath part where you verify what channels the current users have access to, then just loop all the channels based on the keyword to do the search which is already implemented. I think the hard part is the User Interface. This search bar might just reside at the top then, another page to present the results, and you can jump into the resulted channel where the message is in history. I will give another Day for testing. 

For these amount of work, let alone the idea about the framework and wiring things around the existing code base,  I would say current 500 USD bounty is too low. Anyone would want to take it on is a hero.

**Comment by pshute** [comment]
If this feature is difficult to program, what would be useful would be if the search string persisted across channel changes. Then it would be as hard to search several channel manually. I don't know if that's difficult to do.

**Comment by JensvdHeydt** [comment]
It guess it's pointless to write "+1" for this issue. There are around 1800 open issues for rocketchat am and only 6 of them have slightly more comments than this one.

**Comment by mixvoip** [comment]
+1 and I added some dollars to the bounty. Gogogo

**Comment by johappel** [comment]
+1 and I added some dollars to the bounty too.

**Comment by timandovo** [comment]
Anyone else willing to add some dollars to the bounty so that we can finally get this implemented?

https://www.bountysource.com/issues/28998888-global-search-across-channels

**Comment by cyberhck** [comment]
@jusfeel actually it's not a big deal, I tried this just now, apart https://github.com/meteor/meteor/issues/8057 issue, everything else is very straightforward.

The way it's currently done is: client sends roomId to server, I changed it to send null in this case (of course without breaking existing stuff by using optional parameter), on server it's checking if user has access to that channel (which might be null in our case).

When searching for entire conversation, I first select all room user has access to, then search for the messages in those rooms.

It's pretty straightforward upto now. What remains is: when we display the result, right now we can just click on hand arrow and it shows in that channel, now it should navigate away from that channel, since this is the first time I've touched meteor, I'll need a little time for this part :)

Any suggestions are welcome :)

**Comment by cyberhck** [comment]
searching and displaying is done, now all I need to do is to show the message when clicked.

This is my first time trying to do meteor and this template, if someone familiar with this, I just need to change the current room. any suggestions welcome :)

**Comment by Cu57arD** [comment]
Anybody else willing to upgrade the bounty, I just added $200 - https://www.bountysource.com/issues/28998888-global-search-across-channels

**Comment by dmoldovan123** [comment]
+1

**Comment by savikko** [comment]
I have somehow-working solution on my fork (https://github.com/savikko/Rocket.Chat.git), please clone and test and share your experiences with that.
Comments to PR #7628.

**Comment by Marx1st** [comment]
+1

**Comment by timandovo** [comment]
@Marx1st 

Thanks for adding your vote.  If you can, please add to the bounty so that we can finally get this in place - [Bountysource](https://www.bountysource.com/issues/28998888-global-search-across-channels?utm_campaign=plugin&utm_content=tracker%2F16890630&utm_medium=issues&utm_source=github)

**Comment by pshute** [comment]
The bounty is now nearly $800, and someone has had a solution ready for testing since August. Can someone please tell me what's stopping this from happening?

**Comment by savikko** [comment]
Reason for not happening from my side has been global busyness :)
But, I have to look at this (again), what this now needs is to merge current development to my branch and then implement global_search_enabled -type boolean to admin settings. I'll look at this in coming days, first thing is to find out how settings are implemented on Rocket.Chat.

**Comment by timandovo** [comment]
Hi Savikko
Great to get such a positive response from you.
You should talk to Rodrigo Nascimento and Theo Renck from the RocketChat team, Rodrigo has told me that they would like to add global search as soon as possible now.

**Comment by savikko** [comment]
Thanks for your kind words.
And just to add, while I deeply understand that global search (with its current implementation) can cause major performance issues in some environments, it should be decideable by admin to enable it or not.

**Comment by tkurz** [comment]
Hi all!
As you can see I created a Pull reqeuest which allows to use either the current Mongo Search or an external Search Service based on Solr (which can be used either as Service or as on-site installation).
It is just a first test but I'd love to improve it based in your feedback!

**Comment by pshute** [comment]
I just tried the beta, seems to work ok, but our team is small, so not likely to have performance issues. Thank you for doing this, @savikko .

**Comment by pshute** [comment]
@savikko Bug: If I scroll through the list of global search results, if I scroll to the very end, the list suddenly reverts to the current channel only.

**Comment by pshute** [comment]
@savikko Feature: The search results are updated as I type the search string. Should they also update if I tick or untick the Global Search option?

**Comment by savikko** [comment]
@pshute : I'm not alone here doing this, thanks @cyberhck for starting this and @rodrigok for getting it running.
I have tried this on our rather small environment (about 100 users, 200k total messages), performance hasn't been an issue.

Search update (un)ticking option is not implemented at the moment, it should be done at the same time as layout of the checkbox would be changed. I wouldn't mind if there would be "loading" spinner when searching.

I can confirm that when scrolling (until the paging triggers) to the bottom, paging does not recognize that global search was chosen.

**Comment by rcmorano** [comment]
Aloha! 

Firstly, I want to thank everybody that worked on this great feature, I'm using it and it works like a charm.
I'll be posting info about performance once my msgdb gets big enough to considerate it. BTW, regarding to performance, @savikko could you comment what hardware is supporting your installation (~100 users/ 200k msgs)?

In second place, I wanted to make a consideration that is also related somehow to performance but it's more about usability...
By default when you enable global search, and hit the search button in any channel, the checkbox to search globally is ticked, woudln't make more sense to have it disabled by default? 
I guess you usually expect to search in current channel instead of globally; and it could save a lot of computing resources that might be used by miseducated users :)

**Comment by savikko** [comment]
Our current setup: 
app server: 4cores, 8G RAM.
mongodb: Mongo Atlas (mongo as a service), 2G RAM, 0.2vCPUs.
