### ISSUE TITLE
Audio recording not sending

### ISSUE THREAD

**Issue by ugintl** [RocketChat/Rocket.Chat#16249]
When I try to send audio message via direct message, It just stays at 0%. I see this
![rocket-audio](https://user-images.githubusercontent.com/12570802/72368748-79ca3e80-3720-11ea-9247-1dddadd77f80.png)

![screenshot](https://user-images.githubusercontent.com/12570802/72368689-628b5100-3720-11ea-9873-248c4ab501ad.png)

**Comment by gabriellsh** [comment]
Just tested 2.5.0-develop, Chrome 79.0.3945.117, macOS Catalina 10.15.2 and it Works fine, please test again.

Also, not enough information provided.  Please check our [issue guidelines](https://rocket.chat/docs/contributing/reporting-issues) again for help on providing additional information.

We need browser versions and OS versions to correctly triage bugs.

**Comment by ugintl** [comment]
Rocket Chat 2.4 installed on ubuntu 18 Bionic. Firefox 72.0.2, Chrome 79.0.3945.130 and I have windows 10 on my laptop. May be this is the problem. I am using 2.4 and you tested on 2.5 dev version.

Should I try updating RC? How to update?

**Comment by gabriellsh** [comment]
It depends on the way you deployed it. You could refer to the [Update docs](https://rocket.chat/docs/installation/updating/) for some help.

If you're running RC in production, I recommend you don't update to develop, but to the latest stable version.

Try testing the client on other devices and on the server, if possible report these tests. Thanks really much for your contribution!

**Comment by ugintl** [comment]
Would you be so kind to reply to this? https://forums.rocket.chat/t/how-to-integrate-whiteboard/5582

**Comment by ugintl** [comment]
I followed this to install rocket chat. https://linuxize.com/post/how-to-deploy-rocket-chat-on-ubuntu-18-04/ 

Can you please edit and paste the edited version of the update process for me?

**Comment by ugintl** [comment]
@gabriellsh I updated it successfully. Rocket Chat service is running. However, in the admin console, it is still showing version 2.4.0.

**Comment by gabriellsh** [comment]
Does your issue still happen? If it says 2.4.0 it is probably still on the same version. You could try restarting the server.

**Comment by ugintl** [comment]
Yes issue is there. I restarted rocket chat server twice. Are you talking the whole machine? I mean ubuntu server?

**Comment by gabriellsh** [comment]
I don't know if restarting the whole machine would do something, but you can try.

You can try using the client inside your ubuntu server as well, as I suspect this is some sort of connection issue between the server and client.

Most important of all, you have to test the latest version. There's no point in trying to find a bug that is fixed in a newer version (if it is indeed a bug). Also, as much as I like to help, this is not our support channel, I've searched a lot and didn't find any other record of this happening, even at 2.4.0, so I'll be closing this.

Please, refer to our [Support Channel](https://open.rocket.chat/channel/support) for additional help if updating your server doesn't work. Thanks for your contrib man!
