### ISSUE TITLE
how should I config for two lan

### ISSUE THREAD

**Issue by BI3QXJ** [RocketChat/Rocket.Chat#16306]
I set up a server with rocketchat running with docker. The server is behind a router with two lan connected. If rc use addr within LAN_1 in GENERAL -- Site URL, only LAN_1 users can upload attachments, upload by users in LAN_2 will stuck in 0%.
how should I config the URL or reverse proxy to make both two lan worked. thx!

**Comment by apaarfus** [comment]
Please follow the post guidelines when reporting bugs/issues.

**Comment by MartinSchoeler** [comment]
Hey, looks like you seem to be looking for support. You will have a better chance of getting help if you go to one of the places listed in [here](https://rocket.chat/docs/getting-support/#community-support) since github is not the best place to ask for support. For now i will be closing this issue, as it does not fit our issue guidelines
