### ISSUE TITLE
Installation of Client 2.17.2 on Win10 Aborts

### ISSUE THREAD

**Issue by inon-peled** [RocketChat/Rocket.Chat#16323]
### Description:

When running the setup wizard, either as administrator or not, installation aborts by itself and the wizard reads: "Installation Aborted. Setup was not completed successfully".

### Steps to reproduce:

Try to install on Win10.

### Expected behavior:
Installation should finish successfully.

### Actual behavior:

Screenshot:
https://pasteboard.co/IRtLRHW.png

### Client Setup Information

- Desktop App or Browser Version: 2.17.2
- Operating System: Win 10

**Comment by apaarfus** [comment]
This really should be posted in the [Rocket.Chat.Electron repository](https://github.com/RocketChat/Rocket.Chat.Electron/issues), as this is the issue tracker for the server-side of Rocket.Chat.

Furthermore, additional information on your system, environment, and background applications (like AntiVirus) may be requested for additional context.  On that last one, for example, our company's solution of AVG business has been known to spontaneously kill false-positive installers and otherwise; and therefore completely break them.
