### ISSUE TITLE
Unable to start the app on ubuntu

### ISSUE THREAD

**Issue by aryamanpuri** [RocketChat/Rocket.Chat#16399]
Can anyone help with building the project
[![Screenshot from 2020-02-01 02-30-45](https://user-images.githubusercontent.com/43513114/73574243-36e7c500-449b-11ea-853d-b7891d247117.png)

**Comment by Rishgod** [comment]
okay, you can fix this by uninstalling node-modules and reinstalling all the node modules, 

**Step 1: $ npm cache clean --force**

Step 2: Delete node_modules by **$ rm -rf node_modules** folder or delete it manually by going into the directory and right-click > delete / move to trash. Also, delete package-lock.json file too.


**RESTART your computer**

**Step 3: meteor npm install**

To start again, $ meteor npm start

**Comment by MartinSchoeler** [comment]
Hey, looks like you are looking for support. You will have a better chance of getting help if you go to one of the places listed in [here](https://rocket.chat/docs/getting-support/#community-support) since GitHub is not the best place to ask for support. For now, I will be closing this issue, as it does not fit our issue guidelines
