### ISSUE TITLE
can not login to Rocketchat using Freeipa LDAP creds

### ISSUE THREAD

**Issue by cattussapiens** [RocketChat/Rocket.Chat#16432]
server.js:204 LDAPHandler ➔ error Error: User not Found     at MethodInvocation.<anonymous> (app/ldap/server/loginHandler.js:60:10)     at tryLoginMethod (packages/accounts-base/accounts_server.js:460:31)     at tryLoginMethod (packages/accounts-base/accounts_server.js:1294:14)     at AccountsServer._runLoginHandlers (packages/accounts-base/accounts_server.js:458:22)     at AccountsServer.Accounts._runLoginHandlers (app/lib/server/lib/loginErrorMessageOverride.js:7:35)     at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:518:31)

what does go wrong? what settings should be fixed by me?

**Comment by nicexe2e4** [comment]
Can you write your settings? I use freeipa in prod, everything is OK.

**Comment by naymic** [comment]
It could be that my issue with my ldap is relatet to this.
1 It makes a correct search and finds 1 result.
2. Authenticates the user
3. Fails because of an replace undefined.

`I20200223-20:08:21.671(1) server.js:204 LDAP ➔ Connection.info LDAP connected 
I20200223-20:08:21.674(1) server.js:204 LDAP ➔ Bind.info Binding UserDN cn=root,ou=users,o=testldap 
I20200223-20:08:21.680(1) server.js:204 LDAP ➔ Search.info Searching user test.user 
I20200223-20:08:21.685(1) server.js:204 LDAP ➔ Search.debug searchOptions { filter: '(&(cn=test.user))',   scope: 'sub',   sizeLimit: 1000 } 
I20200223-20:08:21.687(1) server.js:204 LDAP ➔ Search.debug BaseDN ou=users,o=testldap 
I20200223-20:08:21.737(1) server.js:204 LDAP ➔ Search.info Search result count 1 
I20200223-20:08:21.740(1) server.js:204 LDAP ➔ Auth.info Authenticating cn=test.user,ou=users,o=testldap 
I20200223-20:08:21.973(1) server.js:204 LDAP ➔ Auth.info Authenticated cn=test.user,ou=users,o=testldap 
I20200223-20:08:21.980(1) server.js:204 LDAPHandler ➔ info Querying user 
I20200223-20:08:21.983(1) server.js:204 LDAPHandler ➔ debug userQuery { 'services.ldap.id': '6d69636861656c2e6d65696572' } 
I20200223-20:08:21.987(1) Exception while invoking method 'login' TypeError: Cannot read property 'replace' of undefined     at module.exports (/snap/rocketchat-server/1422/programs/server/npm/node_modules/limax/lib/limax.js:18:15)     at slug (app/ldap/server/sync.js:49:9)     at MethodInvocation.<anonymous> (app/ldap/server/loginHandler.js:104:14)     at tryLoginMethod (packages/accounts-base/accounts_server.js:460:31)     at tryLoginMethod (packages/accounts-base/accounts_server.js:1294:14)     at AccountsServer._runLoginHandlers (packages/accounts-base/accounts_server.js:458:22)     at AccountsServer.Accounts._runLoginHandlers (app/lib/server/lib/loginErrorMessageOverride.js:7:35)     at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:518:31)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43 `
