### ISSUE TITLE
zapier integration error

### ISSUE THREAD

**Issue by mart8mart8** [RocketChat/Rocket.Chat#16507]
Hello all, 
i would like to know if someone  can explain how can i fix this problem when i try to make the integration with zapier in my RC.

![image](https://user-images.githubusercontent.com/18290688/74006856-2ec7d380-493a-11ea-9dd6-3c98235c1cf9.png)

i try with the ip too and was the same problem.

thanks!

**Comment by MartinSchoeler** [comment]
Hey, looks like you are looking for support. You will have a better chance of getting help if you go to one of the places listed in [here](https://rocket.chat/docs/getting-support/#community-support) since github is not the best place to ask for support. For now i will be closing this issue, as it does not fit our issue guidelines
