### ISSUE TITLE
How can i update from 2.4.8 to 3-rc?

### ISSUE THREAD

**Issue by krchavdarov** [RocketChat/Rocket.Chat#16525]
Hello guys,

I apologize for my bad English and congratulations on the most amazing communication project.

Can you help me to install/ or upgrade/ to the new RC-4 version?

**Comment by MartinSchoeler** [comment]
Hey, looks like are looking for support. You will have a better chance of getting help if you go to one of the places listed in [here](https://rocket.chat/docs/getting-support/#community-support) since github is not the best place to ask for support. For now i will be closing this issue, as it does not fit our issue guidelines
