### ISSUE TITLE
Remove user from all groups that she joined 

### ISSUE THREAD

**Issue by aceaceace30** [RocketChat/Rocket.Chat#16524]
is it possible to remove the user in the groups where she joined without doing it one by one? thanks

**Comment by MartinSchoeler** [comment]
Hey, looks like you are looking for support. You will have a better chance of getting help if you go to one of the places listed in [here](https://rocket.chat/docs/getting-support/#community-support) since github is not the best place to ask for support. For now i will be closing this issue, as it does not fit our issue guidelines
