### ISSUE TITLE
BigBlueButton Feature Request

### ISSUE THREAD

**Issue by lifeofdan** [RocketChat/Rocket.Chat#16553]
My school uses rocket.chat and bigbluebutton. My only complaint with the integration is that you really have to full-screen bigbluebutton to use it for screen-sharing/video conferencing. This is an issue if you only have one monitor. I would like to request that there is a toggle button (exactly like the one in the jitsi integration) to allow bigbluebutton to launch in a new tab/window. 

![image](https://user-images.githubusercontent.com/1669918/74201075-5e693980-4cb4-11ea-8367-a569b15b4785.png)

Thank you for reading my request. :)

**Comment by einhirn** [comment]
Well, actually, "always open in new window" should be the default and perhaps doesn't even need to be configurable, because opening BBB in an iframe like it is done now causes a lot of issues with the media access - at least for me:
 - Screen Sharing doesn't work at all (allow lacks 'display-capture' right)
 - Doesn't work at all when using a load balanced BBB setup (you get redirected from BBB-API URL to one of the servers, so the origin changes from the 'src' tag...)
 - Even when 'hot patching' the allowed origins in the 'allow" tag, it only sometimes work (again Firefox worse than Chrome)...

**Comment by jsalatiel** [comment]
"always open in new window" should be the default.

**Comment by slater0013** [comment]
Hi, 
At least could we have the possiblity to resize the sidebar ? The frame is too small and we can only see the participants, unless you click on the caracter icon a the top.

Thanks,
GS
