### ISSUE TITLE
Latest avatar image isn't shown unless you clear your browser cache.

### ISSUE THREAD

**Issue by hifihedgehog** [RocketChat/Rocket.Chat#16738]
### Description:

Latest avatar image isn't shown unless you clear your browser cache.

### Steps to reproduce:

1. Log in to account. Attempt to change profile image. Updated image isn't reflected until browser session is cleared.

### Expected behavior:

1. See new profile image as soon as it is uploaded.

### Actual behavior:

1. The old image persists until the browser session cache is purged.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.2
- Operating System: CentOS 7.7
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.6.1
- MongoDB Version: 4.2.3

### Client Setup Information

- Desktop App or Browser Version: Edge/Chrome/Safari iOS
- Operating System: Windows, iOS

### Additional context

To be clear, I thought my profile images weren't uploading. It turns out they are there in the file store but they are not reflected until the user's browser cache is cleared.

### Relevant logs:

Not applicable.

**Comment by hpsaturn** [comment]
I don't if this issue has relation with the next: I changed my avatar many times, but ever the other platforms like Twitter, Telegram, etc, find my first avatar, don't matter if I clean my browser cache, or third party cache, all time the Github service get my first avatar, it is insane:

## Telegram preview
![image](https://user-images.githubusercontent.com/423856/102825573-505d6c80-43df-11eb-957f-99abadb49f1b.png)

The first image is my current avatar, the second image is my old avatar.

Thanks

**Comment by cs35-owncloud** [comment]
Hello,

it seems the problem comes from the fact that the avatar URL is not consistent.
Sometimes the URL would be https://xxx/avatar/my_user
But sometimes it's https://xxx/avatar/my_user?etag=CaACNMvTTCQcE4sz7
The latest is the current avatar (the etag changes each time you set your avatar).
Could it be fixed to use only the etag URL ?
The JWT token created by Rocket.Chat to Jitsi is always the one without the etag, so avatars are not show will the current version.
Thanks.
