### ISSUE TITLE
Allow muting threads that started from a message posted by myself.

### ISSUE THREAD

**Issue by sknorr** [RocketChat/Rocket.Chat#16938]
### Description:

Sometimes there are situations where a thread that started from a post by yourself goes wildly off-topic or someone starts ranting. In these cases, you may not be all that interested in getting desktop notifications for all of the responses from "your" thread.

However, currently, Rocketchat (web client) does not allow muting threads that started below your own message. Most frustratingly, it does not even tell you properly that this doesn't work: You can "Mute" and you get the struck bell icon, but as soon as someone writes another message in the thread, this setting is reverted, you get a notification and the bell icon goes back to normal.

### Steps to reproduce:

0. Have a channel that has some prio for you, where desktop notifications are turned on. 
1. Write a message there
2. Have someone else Reply in Thread to it.
3. Click the bell icon next to the blue message, so it becomes struck out.
4. Switch contexts.
5. Have the other person write more messages in the thread.
6. Rageclose Rocketchat because you become annoyed, then watch mail in your mail client pile up.

### Expected behavior:

Don't override my mute setting. Maybe continue to show the unread indicator in the sidebar but definitely don't give me notifications.

### Actual behavior:

Rocketchat automatically unmutes the thread as soon at (5.).

### Server Setup Information:

- Version of Rocket.Chat Server: 2.2.0

### Client Setup Information

- Browser Version/Linux

**Comment by gabriellsh** [comment]
I just tested this in develop 3.1.0 and unfollowing messages works fine. What you might be experiencing is that when you start a thread in a channel, if you receive notifications from that specific channel, even if you stop following the main message, you'll still receive notifications because there is a new message in the room.

You can manage per-room notifications if you want by clicking the 3 dots in the room header and going to `notification preferences`. Also, if email notifications annoy you, you can disable them clicking on your profile pic > My account > Preferences > Notifications (this will change notifications globally).

If things do not go as I described, try updating your server, lots of things changed since 2.2.0. Thanks for your help!

**Comment by sknorr** [comment]
Thanks for checking!

My co-worker is better at searching the bug and it seems this was fixed with https://github.com/RocketChat/Rocket.Chat/pull/15740.
