### ISSUE TITLE
How do I update to 3.1.0-rc.0?

### ISSUE THREAD

**Issue by hifihedgehog** [RocketChat/Rocket.Chat#17037]
I saw you just published 3.1.0-rc.0 in the releases section. However, I can't seem to download a precompiled version anywhere. Please help. Thanks! :)

**Comment by gabriellsh** [comment]
The `rc.0` part means it's a release candidate, not necessarily a final release yet. Release candidates are not necessarily stable, that's why it's a candidate. There could be multiple of those (eg. rc.1, rc.2, etc) before the final 3.1.0 is released. You'll have to wait just a little more.

If you want, you can always clone the repo and update to whatever version you want.

Just a friendly notice, if you have questions related to RC that are not an actual issue (bug, feature request, etc.), we ask that you go to [our Support Channel](https://open.rocket.chat/channel/support). Thanks for your comprehension!

**Comment by gabriellsh** [comment]
It should accept any email. I'll check it out.

**Comment by gabriellsh** [comment]
Did you try to log in with your email? If your email is not confirmed yet it should provide you with a link to resend the email. Could you check that out?
