### ISSUE TITLE
https://open.rocket.chat/ So embarrassing BUG,Nobody resolve this old bug(all versions)

### ISSUE THREAD

**Issue by 564064202** [RocketChat/Rocket.Chat#17258]
![image](https://user-images.githubusercontent.com/12368358/79037094-ca0e4b00-7c00-11ea-8cde-62f176a31768.png)

https://open.rocket.chat/

when you login the system ,you we see it (all versions)

**Comment by 564064202** [comment]
https://open.rocket.chat/

**Comment by 564064202** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/17170

**Comment by luixxiul** [comment]
> So embarrassing

if you feel that why wouldn't you try to resolve the bug?

I feel it's awful to create a duplicate ticket just to humiliate developers here.

**Comment by 564064202** [comment]
@luixxiul Oh,My God,You misunderstood me。I'm just surprised why such an obvious bug can persist for almost all versions.I respect every developer because I am also a developer. I posted the same question just to get everyone's attention.I apologize for the misunderstanding I brought

**Comment by 564064202** [comment]
@luixxiul I think many people will be surprised at such obvious issues that haven't attracted attention for a long time. Wouldn't you be surprised?

**Comment by luixxiul** [comment]
> Wouldn't you be surprised?

Based on the number of issues and pull requests pilling up, I would rather imagine that the team have been overwhelmed by many tasks, not only fixing a bunch of bugs and releasing new features but also maintaining forums here and https://forums.rocket.chat/ 😞 I assume fixing a cosmetic bug (which doesn't break the instance) is a low priority task for now.

Since you are also a developer I think you can try to fix that. Creating a PR with a clear and tidy description will help the team directly 😄

**Comment by pierre-lehnen-rc** [comment]
Closing this one in favor of #17170
