### ISSUE TITLE
Purging anonymous users accounts with retention period of chat

### ISSUE THREAD

**Issue by Gill-Bates** [RocketChat/Rocket.Chat#17263]
My installation of Rocket.Chat allows writing as an anonymous user.  Every guest will be stored as a new unique user in the database forever, thus creating data garbage.  Furthermore the user name is occupied for the future.
It would be great if the users can be coupled with the retention period of the chat.  If I purge the channels after a week, then the guest user accounts can also be deleted.

**Comment by cchbr** [comment]
A feature such as this is greatly needed. I have over 150000 accounts in my db currently that are just garbage since they can't be used anymore. I can't remove them in an efficient way either because removing more than a handful accounts in a short time freezes the server completely making in unusable.
