### ISSUE TITLE
Ibus 

### ISSUE THREAD

**Issue by lioaslan** [RocketChat/Rocket.Chat#17303]
Hi, I'm a user from Viet Nam
I'm using rocket chat on ubuntu 18.04 and use ibus to type VietNamese. Some time I cann't type on rocket app so I have to ```ibus restart``` to type. It's so inconvenience so I hope that you can fix it soon.
Thanks.

**Comment by luixxiul** [comment]
My colleagues told me they experience a similar issue, which apparently is related with IME. They say sometimes they cannot see the cursor on the input bar and cannot tell if they are able to input characters. The issue is experienced on my side too. I am not sure steps to reproduce the issue, while I see the issue is "fixed" by opening devtool.

**Comment by gabriellsh** [comment]
Not enough information provided.  Please check our [issue guidelines](https://rocket.chat/docs/contributing/reporting-issues) again for help on providing additional information.
