### ISSUE TITLE
Webhook script editor panel is empty

### ISSUE THREAD

**Issue by achowd20** [RocketChat/Rocket.Chat#17313]
### Description:

The webhook script editor panel shows empty script. However the webhook script is returning via api.

### Steps to reproduce:

1. Go to admin panel.
2. Click on Integrations
3. Go to any incoming or outgoing webhook.
4. Scroll down and the script editor shows empty.

### Expected behavior:

The editor should show the webhook script.

### Actual behavior:

Empty script editor.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.9
- Operating System: RHEL 7
- Deployment Method:  tar
- Number of Running Instances: 16
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.14.0
- MongoDB Version: 4.0.5

### Client Setup Information

- Desktop App or Browser Version: Both Desktop App and Browser
- Operating System: Windows 10

**Comment by mblo** [comment]
Same here with Desktop App 2.17.9 on Mac and server on 3.1.1.

However, there is a simple workaround: Simply open the desired webhook details page (which shows the empty script editor), and then reload the Desktop App (cmd-R on the Mac), so that everything loads again. Then you will see the script. 

I **cannot** reproduce the bug on the browser (Edge) version.
