### ISSUE TITLE
Owner can't write messages and manage Read-Only broadcast channel on open.rocket.chat

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#17343]
### Description:

I don't know maybe it's a permissions on open.rocket.chat or issue of server version 3.1.1, but if user create a Read-Only broadcast channel he can't write messages and manage that channel

### Steps to reproduce:

1. Create Read-Only Broadcast channel
2. Try to write a message
3. Try to change some channel settings

### Expected behavior:

Channel owner should have rights to manage channel and write a messages there

### Actual behavior:
![ro](https://user-images.githubusercontent.com/4023037/79585531-25a57080-80fa-11ea-833a-1645081b761b.gif)

### Server Setup Information:
open.rocket.chat

### Client Setup Information

- Desktop App or Browser Version: 2.17.0
- Operating System: Windows 10

**Comment by ggazzo** [comment]
We decided to froze the broadcast flag, so its not a bug its intentional (at least until now), there are some issues talking/complaining about that...
About the behavior 'not allowed' I couldn't reproduce actually... could you run on your localhost? open.rocket.chat sometimes uses alpha or non-official code so its hard to check only by this info...


btw: we have images-preview that allow us/you to test very easy each version(has a builtin database)...
if you are used with docker: `docker run -it --rm -p 3000:3000 rocketchat/rocket.chat.preview:3.2.0`
