### ISSUE TITLE
Don't send every single message as an email

### ISSUE THREAD

**Issue by huzaifahj** [RocketChat/Rocket.Chat#17490]
# Description

When selecting `All Messages` in `Channel menu > Notification Preferences > Email > Alerts`, I don't want to be emailed about every consecutive message sent by the same person. Results in too many emails, when the main reason is to notify of some activity in the channel.

# Steps to reproduce

**John says:** Hey guys, just wanted to update you on the latest report
**John says:** Here's the attachment
**John says:** It's not looking very good
**John says:** We must change things if our business is to survive
**Marie says:** John, I agree and have been saying this for a while!

# Expected behaviour

**Email notification:** [John] Hey guys, just wanted to update you on the latest report
**Email notification 2:** [Marie] John, I agree and have been saying this for a while!

## Extra question

Once this is fixed, why can't I make the default setting in `Administration > Accounts > Default User Preferences > Offline Email Notifications` to `All Messages`? It would notify them of all the messages in all the channels they are in, by default.

Thanks for your time.

**Comment by sampaiodiego** [comment]
One of our oldest open issues is requesting an email digest with all messages you lost, this is something we're closer to start working on since we changed how notifications are sent in latest versions.

I'll be closing this issue as duplicated of https://github.com/RocketChat/Rocket.Chat/issues/854 since they talk about the same thing.. but I wanted to let you know we're close to solve it.

regarding your second question:
> Once this is fixed, why can't I make the default setting in Administration > Accounts > Default User Preferences > Offline Email Notifications to All Messages? It would notify them of all the messages in all the channels they are in, by default.

the reason is this option also doesn't exists on the user preferences and emails are costly, for the server to send and paying for an email provider as well.. but as you mentioned, once we have digests, we can have this setting to "all", and all messages will be included in the digest 👍
