### ISSUE TITLE
Notification Email sent albeit online

### ISSUE THREAD

**Issue by port22** [RocketChat/Rocket.Chat#17492]
I'm not sure if this is anyhow connected to https://github.com/RocketChat/Rocket.Chat/issues/17490
but although I'm continuously online (via browser), I constantly receive email notifications that someone sent me a message. I switch to the browser tab, and the status icon is green (not that it switches to green in any visible way, to exclude that my status changes after inactivity.) 
This happens when the browser tab is not active, I suspect.

There only seem to be room based notify settings, but not global and not in the way my problem could be solved.

**Comment by jazztickets** [comment]
The problem seems to be new to 3.2.x. I don't remember having this problem before.

**Comment by port22** [comment]
me neither., indeed this is happening since 3.2.x

**Comment by hogthrob** [comment]
We have just upgraded and experience the same. This is super annoying and users complained immediately about this. 

It is obviously a result of #17357 which was released with 3.2.0. It clearly states that a notification is sent now regardless of the user being online or not, it sufficient to not read the messages for 120 seconds. 

This defeats entirely the notion of "Offline Email notifications". I consider this to be a defect, as a normal user would expect that an "offline notification" is sent only if you are indeed offline and not just not reading your message for 2 minutes. This time is supposed to be configurable but I could not find where.

I understand that some users may remain logged in but are in reality offline since they are far away from their laptop for instance.  But for that it could be coupled (as before) to the away or offline state.

**Comment by jazztickets** [comment]
After looking at the code, it seems they set it up to be configurable as a environment variable, though ideally it would be part of the Admin section. As a workaround for now you could set it to a large timeout value (set this in your rocketchat.service file or wherever ROOT_URL is):

NOTIFICATIONS_SCHEDULE_DELAY=10000000

I would like to see something like this though:

NOTIFICATIONS_SCHEDULE_DELAY_ONLINE=-1
NOTIFICATIONS_SCHEDULE_DELAY_AWAY=120
NOTIFICATIONS_SCHEDULE_DELAY_OFFLINE=0

-1 meaning disabled.

**Comment by port22** [comment]
not to be misunderstood: Notifications indeed should be sent. But ONLY in case the recipient user is OFFLINE.

The problem is, they're being sent on every message, the app / browser app page is not directly active, yet opened.

**Comment by hogthrob** [comment]
For now setting the NOTIFICATIONS_SCHEDULE_DELAY (like an hour or so) would reduce the problem but not fix it. Thanks @jazztickets for digging through the code to at least have a kind of a workaround. 

I also would want the 3 different timeouts with an "disable" entirely. And I don't think an environment variable is appropriate for this (should become part of the admin settings, and potentially also user profile settings.

**Comment by port22** [comment]
wouldn't setting NOTIFICATIONS_SCHEDULE_DELAY just delay the messages, but being sent anyways, just later?
for now I admit I did just set the smtp server to something stupid ^^

**Comment by jazztickets** [comment]
Yes, only if the user hasn't read them. From the pull request:
> When the user reads a channel all the notifications for that user are removed (clear queue)

You can test this in mongo by running:
`db.rocketchat_notification_queue.find()`

Which shows the scheduled date of when the message will be sent. So if you set it to a high number like I did, AND the user didn't read them, then currently yes they'd get a flood of emails in 100 days or whatever.

**Comment by morticah** [comment]
We upgraded yesterday to 3 and face the same problem.
Offline notifications are super sweet we want them, but we only want them if the user is really offline.
And yes delaying the notification isn't a solution.

**Comment by bbrauns** [comment]
This issue is an upgrade blocker. Not resolving it would confuse all of our users and lead to high support demand.

**Comment by mhow2** [comment]
This is a problem for us too.

**Comment by jazztickets** [comment]
I created a pull request that adds the aforementioned environment variables. You can download a build from the 'Build and Test' section under the Checks page.

**Comment by photoninger** [comment]
PLEASE send offline email only if user is really offline!

**Comment by Beeez** [comment]
I think the reasoning behind the new notification changes this was due to inconsistent notifications being sent. I'd rather be over notified than under notified and potentially miss messages. It does defeat the purpose of Offline Email notifications, but again, prior to these new notification changes there were times where I would not get messages despite still being offline. 

Splitting this off into a new Admin setting or variable I am all for. 

For me personally I think maybe a 5 minute delay for Online and Away would be best. There are times where I am focused on a project and will not check my notifications until i am at a good break point - and this is where the notification spam comes in. 
![image](https://user-images.githubusercontent.com/46723579/83045979-57bcc300-a014-11ea-9d00-a26ffaaa8d32.png)

**Comment by rodrigok** [comment]
Thank you all for your feedbacks. Let's find the best behavior or settings for this.

I guess we can fix this email issue and back to the check of connection status.

Unfortunately we can't make it to the 3.3 version, but for sure we can solve it for 3.4

**Comment by port22** [comment]
>  I'd rather be over notified than under notified and potentially miss messages

I just want to add (because that's really important to me), that this is potentially raising grumpy users, not only because overnotification (lets call it spam) potentially results in missing important mails ... and in my case, it almost led to the decision of abandoning Rocketchat, which I only could stop because of this issue and hoping for a change.

**Comment by bbrauns** [comment]
This issue is a major concern for us as well. We will skip releases until it is fixed.

**Comment by AgentTNT** [comment]
While not directly related to email, another one of the outcomes due to the changed notification logic - https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/2102

**Comment by densik** [comment]
Occuring for me a 3.3.3 using latest electron.

**Comment by port22** [comment]
Still occuring in 3.4.0
