### ISSUE TITLE
3.2.1 version not working on a sub-directory with Docker.

### ISSUE THREAD

**Issue by axerosolutions** [RocketChat/Rocket.Chat#17515]
### Description:

We are using RocketChat install on Docker (Ubuntu). It was working fine and our local URL was HTTP://localhost:3000/chatrc/home.

We were installing RC in a sub-directory named "chatrc". But with the latest 3.2.1 release, after installing, the setup-wizard page keeps reloading, as if some JS code is refreshing the page continuously.

If we install it without a sub-directory, it works fine.

This issue is only happening in 3.2.x. It was working fine in 3.1.x.

### Steps to reproduce:

1. Download RocketChat 3.2.1 
2. Install it using Docker.
3. In the YML file, set the instance to run inside a subdirectory named "chatrc". 
4. Run docker-compose.

### Expected behavior:

1. Setup Wizard should load.

### Actual behavior:

Setup wizard pages keeps reloading again and again. 

### Server Setup Information:

- Version of Rocket.Chat Server: 3.2.1
- Operating System: Ubuntu 18.04
- Deployment Method: Docker
- Number of Running Instances: 1

### Client Setup Information

- Desktop App or Browser Version: Chrome/FF
- Operating System: Ubuntu/Windows

**Comment by raghav-khunger** [comment]
We are facing the same issue while running it with 3.2.1 version. Here is the video of flickering screen we are getting while running it in the browser:

https://www.screencast.com/t/ebGVNaw2s

Setup wizard pages keep reloading again and again. There is no error in the Console of the developer tools in the browser. We have tested the same with multiple browsers. The same steps worked for 3.1 version though.

**Comment by engelgabriel** [comment]
Hi guys, please see the forum thread https://forums.rocket.chat/t/support-for-installation-in-subdirectory-will-be-discontinued/6371

We would till welcome fixes from the community, but we don't be working actively to fix the problem.

**Comment by serviceman** [comment]
> Hi guys, please see the forum thread https://forums.rocket.chat/t/support-for-installation-in-subdirectory-will-be-discontinued/6371
> 
> We would till welcome fixes from the community, but we don't be working actively to fix the problem.

I understand if you don't want to support sub directories, I'll post why I think this is a bad idea in the forum. I do feel that this issue should be fixed, considering the announcement in the forum says you will drop support for sub directories starting in 4.0, not 3.2.1. There are those of us who depend on the monthly fixes for bugs, etc, and to give zero warning of not supporting sub directories as of 3.2.1 is not very professional, nor responsible, in the middle of a world wide pandemic, when many companies simply do not have the resources or employees on site to make such radical changes to their system, if they are running in a sub folder.

No longer supporting sub directories will make me question of I want to continue using Rocket Chat in the long term. I have used Rocket Chat for over year and have 75,000 users on my install with hundreds active at one time. In my use case, it would simply be impossible to move Rocket Chat over to a non sub directory install at this time.

**Comment by gabriellsh** [comment]
Sorry if I didn't take all aspects into consideration @serviceman, but just to make sure we're all on the same page:

This does not mean that you would have to change your system install at all, it's just a matter of making the server accessible through a subdomain. Let's say you have `https://mydomain.com/chat`, this could be turned into `https://chat.mydomain.com/`. Your server install wouldn't even have to move from where it's currently at. (I worked at a hosting company for some time and this kind of procedure used to be really that simple).

Again, sorry if I misunderstood your concern, and if that's the case, I'd love to hear why this wouldn't work for you.

**Comment by serviceman** [comment]
I have heavily integrated rocket chat into my system with the api, In fact, I spent months integrating it. I host many websites off one instance with this structure, simply by using /foldername/ in the chat settings in the admin panel. I have no need for the email or the invite links to work, or direct linking to a room. 

domain1.com/chat
domain2.com/chat
domain3.com/chat 
and on and on.

I use rocket chat as the chat for a chat & dating network. I offer white labels to other programers and it's all powered under 1 database. It is plug and play, they fill out a form and the site is launched seconds later. 

In order for me to move to sub domains I would have to spend weeks, or even months coding my system to support sub domains, if it's even possible. It is not as easy as just changing the domain over to a sub domain. I have to have session control that is also linked to the domain the user is chatting from, I added profile links that are relative to the domain the user is chatting from etc. I use the api heavily in my platform as well.

I don't mean to sound rude, but wouldn't it make more sense to just test the changes to Rocket Chat and make sure they won't be broken in a sub directory? We already have to add a domain or URL path in the settings, why can't the code just use that for the url path?  I'm sure there are plenty of other users of Rocket Chat that have cases that will not work with sub domains. At the very least, support sub directories up until the time you said you would in the forum. That would give users that can't use a sub domain, for various reasons, to move to another platform.

With all do respect, users who are using Rocket Chat is a sub directory are probably doing it for a reason and chose Rocket Chat simply because they could run it in a sub directory. I have used Rocket Chat for 2 years and chose it because I could use a sub directory. If I am forced to spend weeks or months coding my site to work with sub domains, if it's even possible, I may as well look at other platforms that may work with my current site structure. Changing over to sub domains will require a complete rewrite of my platform, due to how I need to have multiple domains be able to be used, on the fly.

**Comment by Sing-Li** [comment]
> I don't mean to sound rude, but wouldn't it make more sense to just test the changes to Rocket Chat and make sure they won't be broken in a sub directory? We already have to add a domain or URL path in the settings, why can't the code just use that for the url path? 

For the same reasons we mentioned.  Complexities in maintaining it long term is way beyond just respecting "replacement or substitute path"   Testing for all deployment scenarios is also a very big baggage for us.

If you do get enough community members interested and can come up with the changes that are required with every subsequent release - we welcome those changes.   We will not remove the support immediately. 

> At the very least, support sub directories up until the time you said you would in the forum.

This is a fair statement.   And we should be working to fix the existing problems for a release prior to 4.x  - although it is unlikely to be on a high priority after our public deprecation statement.

Thank you for your response  @serviceman
