### ISSUE TITLE
Clear OS install: Mobile push notifications - how?

### ISSUE THREAD

**Issue by maugli13** [RocketChat/Rocket.Chat#1762]
Hello, I'm installed rocket chat, from master, and unfortunately can't understand how mobile notifications could be enabled, should I compile specific application for android and ios

When I'm testing push notifications from "Send a test push to my user" I'm getting "Success. Your push was sent to 1 devices", but nothing happens on mobile

Thank you in advance.

**Comment by geekgonecrazy** [comment]
@maugli13 what method are you using to deploy? Also do you have the gateway configured?

**Comment by maugli13** [comment]
Hmm, honestly, I have no idea and I couldn't find any working example how it should work, I just installed clear OS, and compiled rocket chat using manuals, tested basic functionality, which is working pretty well. I didn't configure any options in Push -> Cerificates and Keys

I'll be very grateful if you could describe me principles how to make it work, or give me link where I can read about it.

**Comment by Sing-Li** [comment]
Maybe @cmacrae can help with this.

**Comment by cmacrae** [comment]
Not sure how I'd be of help here, @Sing-Li! Did you perhaps mean to tag someone else? :)

**Comment by lvh1** [comment]
I can help you a bit to get it working for android. I assume you'll be using the rocket.chat gateway for this.
* Go to https://console.developers.google.com/ and create a project there.
* Go to API Manager, and enable "Google Cloud Messaging for Android"
* In API Manager, open the "Credentials" tab, click 'New credentials -> API key. In the windows that pops up, choose "Server key"
* Fill in the correct IP address from your server and Click Create
* Fill in the obtained API key in your rocket.chat administrator panel (GCM API Key)
* The GCM Project Number which you also have to fill in on rocketchat can be found on the dashboard of your Google developers project, first block that shows up . (https://console.developers.google.com/home/dashboard, http://i.imgur.com/3DXHEKy.png) 

For iOS you need an apple developer account which I don't have, and don't plan on getting because it costs 99$ per year and so I haven't looked into it much, but maybe this can help: https://github.com/raix/push/blob/v3.x/docs/IOS.md

**Comment by Sing-Li** [comment]
@cmacrae - my apologies for the interruption.  But thanks for the lightning response :smile:   I was not sure how Clear OS specific this issue might be.   

@lvh1 - Thank YOU!   Hopefully that helps @maugli13.   Your instruction is very useful - I will add it to our Wiki.  (our wiki is usually public access, but recently closed due to the construction of a new documentation site)   TA!

**Comment by lvh1** [comment]
@Sing-Li My pleasure :smile:

**Comment by Sing-Li** [comment]
@maugli13  - if you still need more assistance, talk to core team member or any knowledgable community member on #support or #general  at  https://demo.rocket.chat   

Closing this now.

**Comment by maugli13** [comment]
I'm sorry for late response, thak you very much @Sing-Li, @lvh1 thank you for detailed instruction, I could check it in a couple of weeks. Thank you one more time!

P.S. By the way, in my response clear OS is not real Clear OS, I just mean "clear/new operating system", in my case it was Ubuntu server 14.04.3

**Comment by VasudhaMathur** [comment]
Hi!
What does "rocketchat administrator panel" refer to in "Fill in the obtained API key in your rocketchat administrator panel (GCM API Key)"?

**Comment by ctel** [comment]
Hey! I have the same issue as @maugli13 here. Android 7.0.0. If I manually trigger the "notification test" from within the app settings (=local test) on the phone, everything works as expected; also the server administration setting tells me that 2 devices had been pushed (I already cleared the app data on the phone once and relogged in after that "clean-slate-state"; so thats why two devices: my old session must still be active, but thats NOT the problem; everything fine with that...) after I triggered "SEND A TEST PUSH TO MY USER" (before wipe I saw "1 devices pushed", so I guess at least there is information about the mobile session).
But the phone does not show any push notification, even after one hour of waiting.
My administrative settings withing "Push":
Enable: True
Debug: False (if I enable that, I see Push: "Send message "@_myuser_" via query { userId: '_someid_' }" and used gcm ids)
Enable Gateway: False
Gateway: https://gateway.rocket.chat
Production: True

I already have restarted the server. Please note: I did NOT generate a key on the google page, because I assume, your playstore app uses your gcm key and so only your server can push your app (that was the reason, why I assumed no own key is needed?). How do you protect the public gateway from "malicious" use? (=What hinders 3rdPartyServerX on pushing user@3rdPartyServerY through your gateway?)

I suspect I must have missed something here...
