### ISSUE TITLE
Received push notification even when logged out

### ISSUE THREAD

**Issue by marceloschmidt** [RocketChat/Rocket.Chat#1763]
I logged out from the mobile app and I kept receiving push notifications.

**Comment by geekgonecrazy** [comment]
:+1: I've had this happen as well

**Comment by maxlinux2000** [comment]
Hi all, I can confirm that the push notifications now works fine. 
I have setup a rocket.chat server in a vps (digitalocean), and  configured the GCM key and proj# from console.developers.google.com.
I have disable too the gateway from Admin/Push/gateway

Using the R.Chat client from playstore I can receive the test push message when I press the test button in the Admin panel.

So it works!  But, but... Ho can a user send a push message to another?
I want to use Rchat with my friends like I'm using whatsapp, so when I sent them a message, and hi/she is not online, hi will receive a push message soon.

Is that possible? 

I have tried to write "@nameuser: message"  but the user can't receive the push notification. 
It's wrong my assumption? Or it's a bug? Or there is another way to have push message for all in order to use Rchat like whatsapp?

regards
MaX

**Comment by geekgonecrazy** [comment]
@maxlinux2000 the user will only get the push notification if they are considered offline.  So if the app is up on the phone they will not get a message.  If they have the app up on the desktop, they will not receive the notification.

Direct Messages / Mentions are currently the only thing you will get notified for once the above condition is met.

**Comment by maxlinux2000** [comment]
mmm... today nothig is working :(

I have reinstalled the server (ubuntu 14.04 using the wiki tutorial) and delete the cache to the rochet.chat app (from playstore) in my android phone.

Today I can't receive the push messages in any way.

There is a way to check the logs in order to see if the phone send the imei ID and the engine resend it to google?

My server is a VPS with ubuntu 14.04 64bit  installed without docker:
https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-Rocket.Chat-without-docker

**Comment by marceloschmidt** [comment]
This is fixed now.
