### ISSUE TITLE
Embedded Iframe "go" command adds parts to the url resulting in a page not found error

### ISSUE THREAD

**Issue by avalentino98** [RocketChat/Rocket.Chat#17658]
### Description:

I have a problem with the iframe integration of rocketchat.
My situation is the following:
The rocketchat application is exposed on my server under https://domain.com/im
For simplicity i am calling `https://domain.com` the domain and `/im` the subdomain.
In my web application i have an iframe with embedded rocketchat in it, and from my web page i send commands to the iframe in order to change room and navigate the chats.
This worked fine in versions previous to 3.x but when i upgraded my rocketchat to any version equal to or above 3.0.0, whenever i use the "go" command with the path equal to `/direct/username` the iframe navigates to the correct url but **doubling** the subdomain.

### Example in versions older than 3.x:

I send the following command to the iframe to open a direct chat:
```
{
    externalCommand: 'go',
    path: '/direct/' + username,
}
```
The iframe navigated to the url 
`https://domain.com/im/direct/username`

### Behaviour in versions >= 3.x:

I send the following command to the iframe to open a direct chat:
```
{
    externalCommand: 'go',
    path: '/direct/' + username,
}
```
The iframe navigated to the url 
`https://domain.com/im/im/direct/username`

### Expected behaviour 
What i expect is the same behaviour i had in previous versions, so the final iframe url should be
`https://domain.com/im/direct/username`

I checked the source code and operated a bit in the compiled javascript file where the method is called and figured that the actual command that is passed to rocketchat contains the path as 
`/im/direct/username`
instead of the path i specified in the command, which was
`/direct/username`
This causes the iframe to show the 404 error page

The file source that i looked into was [this](https://github.com/RocketChat/Rocket.Chat/blob/fec3800f6fd1347e244d990a9693e5deb47287f4/app/ui/client/lib/iframeCommands.js)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.2.2
- Operating System: Centos (linux x64)
- Number of Running Instances: 1
- NodeJS Version: 12.16.1
- MongoDB Version: 4.0.18

### Client Setup Information

- Desktop App or Browser Version: Latest version of chrome ( 81.0.4044.138 (Official Build) (64-bit) )
- Operating System: Windows

### EDIT:
After further research, i figured that the command passed is correct and that the URL object constructed [here](https://github.com/RocketChat/Rocket.Chat/blob/fec3800f6fd1347e244d990a9693e5deb47287f4/app/ui/client/lib/iframeCommands.js) at line 17, splits the url `https://domain.com/im/direct/username` into `origin = https://domain.com` and `pathname = /im/direct/username`, and rocketchat somewhere in the code concatenates the site name `https://domain.com/im` with the URL path name resulting in the wrong url that is causing me the problem (`https://domain.com/im/im/direct/username`)

**Comment by vitamindck** [comment]
This is still an issue in the current version. The bug report is accurate and identifies the line of code that directly causes the issue.

**Comment by yalanyali** [comment]
> This is still an issue in the current version. The bug report is accurate and identifies the line of code that directly causes the issue.

This is still very much accurate, I don't see why this issue should be closed.

**Comment by vitamindck** [comment]
This is still an issue in 3.14. Below is the fix I implemented in the rocketchat docker container as part of a custom startup script, instead of creating a custom docker image with the fix. It's flimsy and I don't expect it to work forever and neither should you. :)

`# use sed to remove the extraneous m+t.path near `path` not defined which causes externalcommands issued to rocketchat through iframe integration to double up on path. see issue below for more details
# https://github.com/RocketChat/Rocket.Chat/issues/17658

cd /app/bundle/programs/web.browser && sed -i -e 's/console.error("`path` not defined");\(const\|var\) \(.\)=new URL(\(.\)+\(.\)\.path/console.error("`path` not defined");\1 \2=new URL(window.location.origin + \4\.path/' *.js
cd /app/bundle/programs/web.browser.legacy && sed -i -e 's/console.error("`path` not defined");\(const\|var\) \(.\)=new URL(\(.\)+\(.\)\.path/console.error("`path` not defined");\1 \2=new URL(window.location.origin + \4\.path/' *.js`

**Comment by johncrisp** [comment]
See this and other issues on the same subject.

https://forums.rocket.chat/t/support-for-installation-in-subdirectory-will-be-discontinued/6371/25
