### ISSUE TITLE
E2E encryption of mobile push messages

### ISSUE THREAD

**Issue by subesokun** [RocketChat/Rocket.Chat#17753]
I'd like to know if messages that are being sent via the mobile push gateway are E2E encrypted and if not, can this feature be added? I.e. I want to avoid that anybody in between can read the message content. I know there is this policy section where you can disable sending the message content but this is not very convenient. Using a custom [APM or FCM](https://docs.rocket.chat/administrator-guides/notifications/push-notifications#push-gateway) is for us also not really an option.

Especially I'd like to know what happens in the following situations:

- Direct room with OTR session
- Direct rooms with E2E encryption enabled
- Group channels with E2E encryption enabled

In any of these situations, will the gateway receive the messages in clear text? If not, how will the mobile client decrypt those messages? Or is the push message body always empty?

### Server Setup Information:

- Version of Rocket.Chat Server: 3.2.2
- Deployment Method: docker

**Comment by ankar84** [comment]
I thinks that RC.RN mobile application do not support E2E for now https://github.com/RocketChat/Rocket.Chat.ReactNative#current-priorities

**Comment by subesokun** [comment]
I guess the answer to the E2E encrypted direct rooms and group channel is https://github.com/RocketChat/Rocket.Chat/blob/ead78d7061dff1887068d1830d5348278c7f156d/app/lib/server/functions/notifications/index.js#L23 or? I.e. the mobile client will receive a notification with the message `Encrypted message`. 

Now, if E2E encryption enabled becomes the default at some point in Rocket.Chat this means also that every user gets from there on only the message `Encrypted message` as notification which could be a surprising side-effect for most users.

**Comment by subesokun** [comment]
Sorry one more question: Can I find somewhere the source code of the push gateway? I found this repository https://github.com/RocketChat/push but since August 2018 no changes has been committed to that repository so I wonder if that is your currently used gateway.

**Comment by subesokun** [comment]
What confuses me more is that I've disabled now the push feature via the Admin panel (and restarted Rocket.Chat) but still I do see the messages `server.js:204 Push ➔ debug Sent message "#channelname" to 3 ios apps 0 android apps` in my logs. I guess this logs are generated by the "native push". https://github.com/RocketChat/Rocket.Chat/blob/8084de841ed6380ba525ab071f5408d02f361e4f/app/push/server/push.js#L73 What exactly is that and how does it work?

**Comment by subesokun** [comment]
I've created a dedicated bug issue for the push disabling behaviour https://github.com/RocketChat/Rocket.Chat/issues/17765

**Comment by subesokun** [comment]
No feedback at all from the RC team 😞?

**Comment by rodrigok** [comment]
@subesokun no, the messages sent from RC servers to the mobile apps are not encrypted. But in our Enterprise version, the push notifications send only the message's id and the app requests the content directly to the server.

Regarding the push disabling we are working to fix the message, the push is added to the queue to be sent but when preparing to send it's rejected since the push is disabled, we are changing to prevent it to be even added to the queue.

**Comment by subesokun** [comment]
Thanks for the feedback. I suppose the background fetching of RC messages via the message ID received in the push message will remain an enterprise feature or?

**Comment by 2disbetter** [comment]
Wouldn't the messages being encrypted help mitigate the issue of them being sent plain text to the respective push server? I mean it would just look like scrambled text, and wouldn't be decipherable. In this way, as long as the messages are E2E you have some mitigation. The enterprise secure push is the ultimate solution though.

**Comment by rodrigok** [comment]
Thanks for your feedback.

Our mobile apps are supporting E2E Encrypted messages now on days, so when using this feature messages will not be readable by our gateway.

If you are not using the E2E Encryption for the message the message will pass through our gateway unless you are running the Enterprise version which includes a security feature for it sending only the message's id to the mobile which requests the message's contetent directly from the server.

So I'll close this issue by now since the features are available.
