### ISSUE TITLE
Sir,Docker How to upgrade a 2.* version to 3.* version?

### ISSUE THREAD

**Issue by codeneno** [RocketChat/Rocket.Chat#17957]
Sir,Docker How to upgrade a 2.* version to 3.* version?

**Comment by frdmn** [comment]
You basically just have to make sure that you met the engine version requirements for the given release that you want to upgrade to. You can find the version info [below each release](https://github.com/RocketChat/Rocket.Chat/releases/tag/3.3.3). 

Since we try to keep the GitHub issues exclusive to product related bugs/issues, feel free to join us in the community #support channel on our open Rocket.Chat instance in case you need further assistance on this: https://open.rocket.chat/channel/support

**Comment by codeneno** [comment]
@frdmn if we upgrade 2.1.12 to 3.3.3 does it support

**Comment by codeneno** [comment]
@frdmn if we upgrade 2.1.12 to 3.3.3 does it support
