### ISSUE TITLE
Facebook chat integration no attachments (images)

### ISSUE THREAD

**Issue by dazoot** [RocketChat/Rocket.Chat#17952]
### Description:

When using rocket chat with the omnichanel facebook page messenger integration our staff is not getting any of the pasted attachments (images / files) our user send us from facebook messenger.

### Steps to reproduce:

Send an image from Facebook Messenger.

### Expected behavior:

The image to show up in rocket chat.

### Actual behavior:

The image not sent to rocket chat.
ALSO it's not working the other way around either (Ex: when our rocket chat staff is sending attachments to a facebook messenger chat - omnichannel).

### Server Setup Information:

- Version of Rocket.Chat Server: 3.3.3
- Operating System: Debian 8
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.16.1
- MongoDB Version:3.6.5

### Client Setup Information

- Desktop App 
- Operating System: Windows 10

**Comment by renatobecker** [comment]
@dazoot the behaviour you described isn't an issue since the current version of the Facebook integration doesn't support file sharing.
If you don't mind, please, open/create an issue on our [Feature Request Repo](https://github.com/RocketChat/feature-requests), it's the right place to request new features.

Thanks.

**Comment by dazoot** [comment]
I see we have it already in request repo.
We can close it here.
