### ISSUE TITLE
HelpDesk

### ISSUE THREAD

**Issue by FarzinZaker** [RocketChat/Rocket.Chat#1797]
hi

can anyone explain for me, how rocket chat can be used for a website online support? I did not find any documentation about this

**Comment by sampaiodiego** [comment]
hey @FarzinZaker , at the moment you have to add the meteor package `rocketchat:livechat` and build rocket.chat manually.
in the future versions, the livechat package will be included by default on our builds.

**Comment by infinitnet** [comment]
Is there an ETA for this? I also only tried Rocket.Chat because live chat was mentioned as a feature on your website, only to find out it's not included in the dev branch yet.

**Comment by infinitnet** [comment]
PS: Also seems to have design glitches with latest Chromium browser: http://i.imgur.com/qyC06rg.png

**Comment by k0nsl** [comment]
@infinitnet it works fine on my personal instance.
![selection_048](https://cloud.githubusercontent.com/assets/2517921/12121895/33367cf6-b3d8-11e5-999a-ff30eb885b98.png)

**Comment by infinitnet** [comment]
@k0nsl I assume you installed the livechat meteor package? Probably going to try that then, but I had hoped for a default integration of a live chat considering it's mentioned on the official website as a feature.

**Comment by k0nsl** [comment]
@infinitnet,
Hi. Yes, I added it manually to my `.meteor/packages` by uncommenting it.

**Comment by k0nsl** [comment]
@infinitnet 
now that I look into it more closely I see that the live chat looks fine on the page and the pop-out looks fine as well, and messages "appear" to be sent. However, me as the only "agent", didn't receive any messages when I just tested it twice.
So there is a problem. I will try to see what it could be and report my results later.

My code is like one or two pulls out of date.

**Comment by sampaiodiego** [comment]
@infinitnet and @k0nsl the package **is** already added by default on `develop` branch.
@infinitnet yes, that visual glitch is a bug.. the message shown was `Sorry, no online agents`..
you also asked by an ETA, but since there is no "full feature set list" there is no ETA yet.

**Comment by k0nsl** [comment]
@sampaiodiego yep, I know it is included by default now, but my instance is outdated by maybe two or three pulls.
I will update it later today when there's less people on it.

**Comment by infinitnet** [comment]
@sampaiodiego This achive doesn't seem to be updated though: https://s3.amazonaws.com/rocketchatbuild/rocket.chat-develop.tgz Any chance on updating this build so I can use it with the Ansible role provided by @cmacrae ?

**Comment by sampaiodiego** [comment]
yes @infinitnet , unfortunately the build files on S3 were not updated automatically on the lasts commits. @Sing-Li was working on it..

**Comment by infinitnet** [comment]
Would sure be nice to get this fixed so I can try an up to date version the way I intended to (Ansible managed) and that your documentation promotes amongst others.

Also about the design glitch: as you can see on my earlier screenshot (http://i.imgur.com/qyC06rg.png) the message "test" was lost after switching to the popout window and the rollout window then in turn wasn't updated with the message I entered into the popout window. I can imagine that if there is an ongoing chat and if the visitor enables the popout to read it more conveniently only to see that this removes the whole history, it could create some frustration which should obviously be avoided during any sales interactions.

**Comment by sampaiodiego** [comment]
@infinitnet that happens only because the message was **not** successfully sent.
if there is a "working conversation" in the small attached window when you pops out the whole conversation will be available in the popup aswell.

**Comment by Sing-Li** [comment]
@infinitnet  A more limited version of LiveChat has been included as Rocket.Chat for a very long time.  This one that @sampaiodiego is an ambitious, more comprehensive version with many more features.

LiveChat  _installation_ had always required dev level intervention (re-building with Meteor, and so on).   We are only starting to make it a standard part of the distribution.  

And yes, very soon, you will be able to use it with the Ansible role provided by @cmacrae  (thanks Calum!) - this particular work is complicated recent changes in the way we bundle and distribute our releases.

Thanks for your understanding and please bear with us.  We're a _very_ fast moving FOSS project, and things _do_ break sometimes.

**Comment by infinitnet** [comment]
Thanks for the heads-up guys. We started testing Rocket.Chat because as a sort of "hybrid" it would allow us to merge Slack and tawk.to (our current solution) into a single platform for more efficiency. Now with the live chat part not being production ready yet, it's just a replacement for Slack at the moment and that's not what we were looking for - hence my impatience and questions about that part of your software.

Generally this looks very promising though and we'll keep using it as a Slack replacement for a while and hope to soon be able to replace both Tawk and Slack with it.

That's probably not the right place, but a few thoughts about what I'm missing so far:

Slack replacement:
===
- `/remind` feature to have the bot send a DM to oneself or someone else after or at a certain time
- OTR for person to person DMs to make private messages actually private
- Show full names instead of handles in rooms
- Set default room to join upon sign-in

Tawk.to replacement:
===
- Detailed visitor tracking (current page, referrer, UA, time on site, IP, country, browser/OS, # of visits)
- Triggers with lots of conditions (like send message if chat request is not served for 2mins)
- Shortcuts to be able to just send `/hi` for example which turns into `Hello, how can I assist you today?`

Some of these might be already there and I just missed them or they are planned for future releases. Just wanted to let you know my first impressions trying your project after being on Slack for a long time.

Keep up your great work, I'll contribute where I can (mostly testing and sysadmin parts of the Ansible role) and keep testing this with our team for a while until we decide whether we can replace Slack/Tawk with it or not.

Thanks!

**Comment by Shelnutt2** [comment]
@infinitnet Rocket chat supports hubot, so you can create a bot, or edit the default preview one, and add [remind me support](https://www.npmjs.com/package/hubot-remind-at).

**Comment by infinitnet** [comment]
I was thinking to have a reminder feature without having to add Hubot. But thanks for pointing that out, I'll probably add Hubot then and see how that goes.

**Comment by sampaiodiego** [comment]
so, @FarzinZaker the livechat package is already added as default in `develop` .. we're still working on updating artfacts on S3 build files.
when the package goes to our stable build I'll write some docs on how to use it ;)

**Comment by dsdharam91** [comment]
i want to implement rocket chat  in  our own website.is there anyone who have used it earlier. i have cloned the rocket chat Repo and installed all packages and it working very well on localhost. But it is working different post and i want to implement this on inner screen. how can i do it .Is t here any API that i can use.i have spent whole day but did'nt get any solution.please help. Thanks

**Comment by Ajith4697** [comment]
@infinitnet In my organization, I installed Rocket chat successfully with help of official Rocket chat documents.. All SMTP settings are done , but I didn't receive Email notification And I can't invite new user , If I click a ( send test mail to user) option, In User interface shows ( mail sent Successfully) but I didn't receive any mail from Rocket chat . kindly ,please help me out on this....
