### ISSUE TITLE
3.5.0 Issues

### ISSUE THREAD

**Issue by ubergeekzone** [RocketChat/Rocket.Chat#18089]
Description:

I cloned RC from the repo for version 3.5.0, as I need to pull that version into a different project. my browser is showing these errors

Steps to reproduce:

git clone https://github.com/RocketChat/Rocket.Chat.git
cd Rocket.Chat
meteor npm install
meteor npm start

Expected behavior:
chat should load

Actual behavior:
chat does not load correctly.

Server Setup Information:
Version of Rocket.Chat Server: 3.5.0-develop
Operating System: Ubuntu
Deployment Method: github pull
Number of Running Instances: 1
DB Replicaset Oplog: 1
NodeJS Version: 12.14.0
MongoDB Version: 3.6
Client Setup Information
Desktop App or Browser Version: Chrome Latest
Operating System: MacOS

Additional context
none

Relevant logs:

Discarding message with invalid JSON undefined
meteor.js?hash=857dafb4b9dff17e29ed8498a22ea5b1a3d6b41d:1061 
discarding invalid livedata message null
meteor.js?hash=857dafb4b9dff17e29ed8498a22ea5b1a3d6b41d:1061 
Discarding message with invalid JSON undefined
meteor.js?hash=857dafb4b9dff17e29ed8498a22ea5b1a3d6b41d:1061 
discarding invalid livedata message null

**Comment by Greenjam94** [comment]
I think I'm seeing the same issue but I did a manual setup following the website:

### Description:

I followed the following blogs successfully, well for the most part except for this current issue at the end of the process.
https://docs.rocket.chat/installation/manual-installation/ubuntu
I just used `apt install mongodb` since I upgraded to Ubuntu 20.04 focal

https://docs.rocket.chat/installation/manual-installation/configuring-ssl-reverse-proxy#running-behind-an-apache-ssl-reverse-proxy
I am using a letsencrypt cert and apache config

### Steps to reproduce:

Follow website for fresh manual install onto ubuntu, from here Rocketchat works at http:<IP>:3000

Next follow website to configure SSL with apache2. DNS should be for a subdomain of a site. Use letsencrypt certificates newly generated for new subdomain.

### Expected behavior:
chat should load

### Actual behavior:
site loads partially, login prompt does not, console errors that websocket can't connect and returned json / livedata messafes are invalid (maybe null?)

### Server Setup Information:
Version of Rocket.Chat Server: 3.4.1 (https://releases.rocket.chat/latest/download)
Operating System: Ubuntu 20.04 Focal
Deployment Method: Manual
Number of Running Instances: 1
DB Replicaset Oplog: 1
NodeJS Version: v12.14.0
MongoDB Version: db version v3.6.8

### Client Setup Information
Desktop App or Browser Version:

- Chrome 83.0.4103.116 
- Firefox 76.0.1

Operating System: MacOS Mojave 10.14.6

### Additional context

connecting to http://68.183.154.156:3000/ works as expected
Trying to configure SSL proxy for https://chatwith.hackerunder.dev subdomain is lot loading at all

ufw is disabled, so 80,443,3000 and all other ports are accessible from anywhere as I test this.

Files:
apache domain config

        <IfModule mod_ssl.c>
        <VirtualHost *:443>
        ServerAdmin webmaster@localhost
        ServerName chatwith.hackerunder.dev

        Include /etc/letsencrypt/options-ssl-apache.conf

        LogLevel info
        ErrorLog /var/log/chatwith.hackerunder.dev_error.log
        TransferLog /var/log/chatwith.hackerunder.dev_access.log

        <Location />
            Require all granted
        </Location>

        AllowEncodedSlashes On
        RewriteEngine On
        RewriteCond %{HTTP:Upgrade} =websocket [NC]
        RewriteRule /(.*)           ws://68.183.154.156:3000/$1 [P,L]
        RewriteCond %{HTTP:Upgrade} !=websocket [NC]
        RewriteRule /(.*)           http://68.183.154.156:3000/$1 [P,L]

        ProxyPass        / http://68.183.154.156:3000/
        ProxyPassReverse / http://68.183.154.156:3000/

        SSLCertificateFile /etc/letsencrypt/live/hackerunder.dev/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/hackerunder.dev/privkey.pem
        </VirtualHost>
        </IfModule>


### Relevant logs:
Firefox Browser console (Google had similar results)

        Discarding message with invalid JSON undefined 002b3fae15d3958aa1d6574fb40fc3507e33d688.js:1:6771
        discarding invalid livedata message null 002b3fae15d3958aa1d6574fb40fc3507e33d688.js:1:6771
        Firefox can’t establish a connection to the server at wss://chatwith.hackerunder.dev/sockjs/875/htvfr_jf/websocket. 
        002b3fae15d3958aa1d6574fb40fc3507e33d688.js:145:22896
        Discarding message with invalid JSON undefined 002b3fae15d3958aa1d6574fb40fc3507e33d688.js:1:6771
        discarding invalid livedata message null 002b3fae15d3958aa1d6574fb40fc3507e33d688.js:1:6771


rc_error.log

        [Fri Jul 10 03:54:07.951725 2020] [ssl:info] [pid 7665] AH01914: Configuring server chatwith.hackerunder.dev:443 for SSL protocol
        [Fri Jul 10 03:54:07.952174 2020] [ssl:info] [pid 7665] AH02568: Certificate and private key chatwith.hackerunder.dev:443:0 configured from /etc/letsencrypt/live/hackerunder.dev/fullchain.pem and /etc/letsencrypt/live/hackerunder.dev/privkey.pem


rc_access.log

        MyClientIP - - [10/Jul/2020:03:54:40 +0000] "GET /sockjs/info?cb=efpcm_mpcp HTTP/1.1" 200 78
        MyClientIP - - [10/Jul/2020:03:54:40 +0000] "GET /images/manifest.json HTTP/1.1" 304 -
        MyClientIP - - [10/Jul/2020:03:54:40 +0000] "GET /assets/favicon_192.png HTTP/1.1" 304 -
        MyClientIP - - [10/Jul/2020:03:54:40 +0000] "GET /_timesync HTTP/1.1" 200 13
        MyClientIP - - [10/Jul/2020:03:54:40 +0000] "POST /api/v1/method.callAnon/public-settings%2Fget HTTP/1.1" 200 81233

**Comment by Greenjam94** [comment]
Updated today to 3.5.2, no other changes. Issue seems resolved. https:// url is loading correctly.
