### ISSUE TITLE
Profile does not change immediately.

### ISSUE THREAD

**Issue by cds1503** [RocketChat/Rocket.Chat#18196]
### Description:
If you edit the profile and click the "Save Changes" button, the loading will continue and change in about 2 minutes.

### Steps to reproduce:

1. Login
2. Click Profile -> My Account
3. Change profile info
4. Click Save Changes
5. Loading... few Minute
6. save

### Expected behavior:
It seems to take a timeout in a certain part.

### Actual behavior:
Should be changed immediately

### Server Setup Information:

- Version of Rocket.Chat Server:  3.2.2
- Operating System:  CentOS 7.5
- Deployment Method:  tar
- Number of Running Instances: 1
- DB Replicaset Oplog:  
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: 
- Operating System: CentOS 7.5
- Not connect Internet Syetem.

**Comment by cds1503** [comment]
please help me

**Comment by MartinSchoeler** [comment]
Thanks for reporting this issue. We value your time in helping us to make Rocket.Chat great. We always try to fix confirmed problems as quickly as we can, and it appears that the issue you reported might already be fixed in the latest release. Can you please help us test it against current latest release? Much appreciated. And please remember to backup your data before upgrading, just to be safe. Cheers!

**Comment by cds1503** [comment]
I solved this problem.
The cause was port 443. For security reasons, the 443 port was blocked by the firewall, but it seems that the packet was not transmitted.
Opening port 443 will work normally. Thank you.
