### ISSUE TITLE
No option to hide "Invite user" functionality

### ISSUE THREAD

**Issue by emikolajczak** [RocketChat/Rocket.Chat#18220]
### Description:

I do not see any option to hide/disable "Invite user" functionality. I want to disable it because by default use external link https://go.rocket.chat/invite?host=
There is any possibility to hide it or change default link?

### Steps to reproduce:

1. Go to room
2. Click users list
3. "invite users" button exists

### Expected behavior:

Any possibility to configure this function

### Actual behavior:

No possibility to configure this function

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.0
- Operating System: Centos7
- Deployment Method: docker-compose
- Number of Running Instances: 25
- DB Replicaset Oplog: YES
- NodeJS Version: v12.16.1
- MongoDB Version: 4.0.16

### Client Setup Information

- Desktop App or Browser Version: 2.17.7
- Operating System: Windows 10

### Additional context

![image](https://user-images.githubusercontent.com/50440047/86730633-09e1a480-c02f-11ea-8b6f-095412a687a3.png)

**Comment by sephwalker56** [comment]
I couldn't find a way to disable deeplinks but I could at the very least break them. In the meantime, before someone actually helps solve your issue, in Administration -> General: DeepLink_URL change this to be empty. This will remove the go.rocketchat.com DeepLink prefix... but I'm not sure how to replace this with one of your own. I believe the idea here is that if someone clicks this link on mobile, they'll be redirected to the app store if they don't have the app, or directed to the mobile client.

Is this DeepLink code available anywhere? I'd much prefer to host this myself, rather than have it go through a third party server. One of the main reasons we decided to use RocketChat is the privacy element of self-hosting. Nobody else should get ahold of any of the data sent to and from my server, including who's being invited to what room. In the meantime, I'll just break it by removing that bit, but it would be great to have this feature functional. Thanks!

**Comment by bseclier** [comment]
Hello,
I order to disable the invite users button, you just have to uncheck the "ID: create-invite-links" for everyone in the "Permission" menu.
If you disable deeplink URL, it will be replaced by your hostname/invite/xxxx.
Cheers,

**Comment by pierre-lehnen-rc** [comment]
To change the URL, use the setting "Invite URL Type" under Accounts/Registration.
To disable the feature, remove the `create-invite-links` permission.
