### ISSUE TITLE
Subchannel messages no longer show up in main channel window

### ISSUE THREAD

**Issue by achimbitzer** [RocketChat/Rocket.Chat#18302]
### Description:

I'm using the channel display mode "normal". Until a few days ago all messages in subchannels/threads where displayed in the main channel window, too, with smaller letters. When clicking on one of these messages, the subchannel was displayed in a separate column on the right side of the window.

A few days ago this behaviour changed: 
Now, Only the first message in a subchannel is displayed in the main channel window. Further messages don't show up there. When I want to know if there are new messages in a subchannel I have to look for the first subchannel message. This usually requires lots of scrolling.

I think this is really confusing for me. I've completely lost the overview over the messages in the subchannels. 

### Steps to reproduce:

1. Set channel display mode to "normal"
2. Join a channel
2. Write a message
3. reply to this message with a subchannel / thread
4. write more replies in this subchannel

### Expected behavior:

All messages, either sent directly in the main channel or in the subchannel, are displayed in the main channel window. The subchannel messages are distinguishable vom channel messages because they are rendered in a smaller font.

### Actual behavior:

Only the first subchannel message is shown in the main channel window. All other subchannel messages are missing.

### Server Setup Information:

- Version of Rocket.Chat Server: ???
- Operating System: Ubuntu 18
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: singelnode
- NodeJS Version: v12.16.1
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: current Chromium and Vivaldi 3.1
- Operating System: Kubuntu 18.04

**Comment by achimbitzer** [comment]
Why was this closed immediately? I **DID** use an issue template, namely the bug template!

**Comment by lyz-code** [comment]
We've also encountered this issue, please reopen it.

**Comment by sampaiodiego** [comment]
I'm sorry the inconvenience.. the bot closed the issue because it was missing `Version of Rocket.Chat Server`.. I'm improving the message the bot uses when closing and issue to explain better what caused it to be closed (see https://github.com/RocketChat/Rocket.Chat/pull/18420)

I've added the missing bullet point and am reopening the issue 😉

**Comment by gabriellsh** [comment]
If you want the previous behaviour, you can check this option in `My account > preferences`
![image](https://user-images.githubusercontent.com/40830821/94707962-6e548d00-031a-11eb-8192-93da8a1b41a4.png)

This was an intended change, so channels can look cleaner.  You can check all threads at once by clicking here:
<img width="356" alt="Screenshot 2020-09-30 at 12 44 49" src="https://user-images.githubusercontent.com/40830821/94708370-e4f18a80-031a-11eb-9c67-409f5f548182.png">

Also,  you can mark the checkbox `Also send to channel` while writing inside a thread so that the message is sent inside the channel even to people without the preference checked.

If something regarding what I said is not working, please, comment below explaining it. Thanks!
