### ISSUE TITLE
LDAP auth works with zimbra

### ISSUE THREAD

**Issue by sureshdba2003** [RocketChat/Rocket.Chat#1835]
Hi,

I ma new for rocket,chat. it is possible to authenticate zimbra ldap?

**Comment by marceloschmidt** [comment]
It should be possible, like with any other LDAP, if properly configured. You should check this wiki page: https://github.com/RocketChat/Rocket.Chat/wiki/LDAP-Authentication

**Comment by sureshdba2003** [comment]
hi,

Thanks for your reply. Its now working,

Also, let us know how connect to my own Rocket.Chat Server through android
apps?

Regards, Suresh

**Comment by sureshdba2003** [comment]
i have created a private server & its getting error on loading,

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While processing files with templating (for target web.browser):
   lib/Rocket.Chat.Cordova/www/index.html:1: Can't set DOCTYPE here.
(Meteor sets <!DOCTYPE html> for you)
   Rocket.Chat.Cordova/www/index.html:1: Can't set DOCTYPE here.  (Meteor
sets <!DOCTYPE html> for you)

=> Your application has errors. Waiting for file change.


Kindly help us to solve this?

Suresh

**Comment by StephanieSunshine** [comment]
I managed to make Zimbra work with Rocket Chat, but I had to change a few things.

set ```Domain Search User ID``` to ```zimbraMailDeliveryAddress``` because email aliases were really messing up Rockets ability to login.

set ```Unique Identifier Field``` to ```zimbraId```

set ```User Data Field Map``` to ```{"cn":"name", "zimbraMailDeliveryAddress":"email"}```

I also set ```Username Field``` to ```description```.  Rocket chat wouldn't let users set their username after login, so I used description to hold it instead.

Make sure you go into Rocket Chat and set a user as an admin before you delete the two non LDAP accounts.

**Comment by RaNd250** [comment]
Since version 59.x there are some issues and the fields seems to have changed.

I get constant failures 

`rocketchat_logger rocketchat_logger.js:375 #033[31mLDAPSync ➔ error#033[39m Error creating user { [Error: Match error: Expected string, got object in field email]
Jan  8 15:00:57 rocket rocketchat: message: 'Match error: Expected string, got object in field email',
`

**Comment by RaNd250** [comment]
@StephanieSunshine did you manage to solve the issue that each alias is created as a new user ?
