### ISSUE TITLE
rocketchat could not be updated 3.5.1

### ISSUE THREAD

**Issue by hotho1011** [RocketChat/Rocket.Chat#18484]
I can not update despite everything I have done, please help me, my current version rocketchat 3.4.2 I want rocketchat version 3.5.1, please

### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.2
- Operating System: ubuntu 18.04
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.16.1
- MongoDB Version:4.0.19

### Client Setup Information

- Desktop App or Browser Version:2.17.1
- Operating System:UBUNTU 18.04

### Relevant logs:

![image](https://user-images.githubusercontent.com/22590268/89397108-9e781900-d739-11ea-964e-dbfad1426a6f.png)

**Comment by geekgonecrazy** [comment]
You didn’t include any info on how to reproduce.. what you tried and didn’t work.  Logs of the failure etc.  also you didn’t include deployment method

If snap.. https://docs.rocket.chat/installation/snaps#when-will-my-snap-installation-get-the-latest-release

Going to close since not enough info to call a bug.
