### ISSUE TITLE
Incorrect handling of headers in the REST API

### ISSUE THREAD

**Issue by smcardle** [RocketChat/Rocket.Chat#18492]
### Description:

The Auth Headers passed to the REST API are handled as case sensitive.
The spec specifically states that headers should be handled case "insensitive" .
This means that for RecketChat sending the headers "X-Auth-Token" and "X-User-Id" work but "x-auth-token" and "x-user-id" do not.

### Steps to reproduce:

1. 
2. 
3. 

### Expected behavior:

Sending "X-Auth-Token" or "x-auth-token" in the headers should result in both working.
### Actual behavior:

Lowercase "x-auth-token" and "x-user-id" are not recognised as valid headers.

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by FelipeParreira** [comment]
Hi @smcardle! Thank you for the issue. 👍 

I have some questions for you that may help us find where the problem is:

1) Can you provide some sample request(s) that are able to reproduce this behavior?

2) Are you using any proxy to make your requests? 
(It may be the case that the proxy is what is not allowing you to make the requests with case insensitive headers.)

3) Did you try to make your requests to different servers running Rocket.chat?

**Comment by smcardle** [comment]
Hi. 
I have no proxy in the way.

Sending requests to RC with headers defined in UpperCase work. Sending the same headers in lowerCase does not.
This is an issue on the RC side. I suspect it's how NodeJS has been configured

**Comment by FelipeParreira** [comment]
Hi @smcardle!

I have tested it on the latest version (3.6.0), and the bug is not reproducible.

Not sure which version of Rocket.Chat you are using, but, if you upgrade it to 3.6.0, it should work for you.
