### ISSUE TITLE
User can enable email 2FA, but it is disabled in backend

### ISSUE THREAD

**Issue by fdellwing** [RocketChat/Rocket.Chat#18501]
### Description:

Disabling 2FA via email does not work.

I setup 2FA for our RC server:

- Enable TOTP
- Delta: 2
- Disable email
- Leave everything else on default

### Steps to reproduce:

1. Open "My Account"
2. Click on "Security"
3. Click on "Enable two-factor authentication via Email"

### Expected behavior:

Either the button not being present at all or disabled or an error message to be shown.

### Actual behavior:

It enables it.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.5.1
- Operating System: Ubuntu 18.04
- Deployment Method: docker
- Number of Running Instances: 3
- DB Replicaset Oplog: enabled
- NodeJS Version: 12.16.1
- MongoDB Version: 3.6.9

### Client Setup Information

- Desktop App or Browser Version: Dektop App
- Operating System: Kubuntu 18.04

**Comment by FelipeParreira** [comment]
Hi, @fdellwing! Thank you for the issue 👍 

We have already fixed this issue for version 3.6.0.

The PR that addresses this issue is [here](https://github.com/RocketChat/Rocket.Chat/pull/18473).

You can check our change log [here](https://github.com/RocketChat/Rocket.Chat/blob/develop/HISTORY.md#-bug-fixes).

So, updating to the newer version should solve it for you. :)
