### ISSUE TITLE
Rocketchat-Server Failed to Start

### ISSUE THREAD

**Issue by Sensuz** [RocketChat/Rocket.Chat#18809]
### Description:

Failed to start Service for snap application rocketchat-server.rocketchat-server

### Steps to reproduce:

1. Turning On server
2. Entering login details
3. Start the server

### Expected behavior:

Rocketchat must be actively running after starting the server

### Actual behavior:
![error](https://user-images.githubusercontent.com/70786977/92298445-8505ff00-ef7b-11ea-9538-663c00d5de0b.jpg)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1
- Operating System: Ubuntu 18.04.3 LTS
- Deployment Method: Snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v.8.17.0
- MongoDB Version: 3.6.14

**Comment by MartinSchoeler** [comment]
Hey, looks like you are looking for support. You will have a better chance of getting help if you go to one of the places listed in [here](https://rocket.chat/docs/getting-support/#community-support) since github is not the best place to ask for support. For now i will be closing this issue, as it does not fit our issue guidelines
