### ISSUE TITLE
[sandstorm] Warning: Site URL configuration

### ISSUE THREAD

**Issue by neynah** [RocketChat/Rocket.Chat#1882]
Seems to only occur for owners of the grain (when starting up).
@paulproteus and @jparyani can provide more context.
![image](https://cloud.githubusercontent.com/assets/855341/12276581/7997b2de-b92b-11e5-94c2-69d2e7b0760f.png)

**Comment by geekgonecrazy** [comment]
@neynah I think we added this because this is often misconfigured in other deployment situations.  We had many support cases where changing that was the fix.

On sandstorm does the site URL need to be http://127.0.0.1:8000 ?  Or rather... do file uploads etc show up with the site URL set to: `http://127.0.0.1:8000` ?

If the the url suggested is completely incorrect we may need to detect if sandstorm and disable the suggestion?

@Sing-Li your expertise here might be useful also.  :smile:

**Comment by Sing-Li** [comment]
:+1:    We already detect if running in Sandstorm.  So it is just a matter of bypassing the warning.  Thx.

**Comment by paulproteus** [comment]
Agreed, just not displaying the warning is A-OK from the Sandstorm
perspective. The existing Rocket.Chat logic for handling uploads/showing
links to uploads/etc. seems to work fine as far as I can tell! (-:

**Comment by neynah** [comment]
You guys are awesome. Thanks for fixing this! :D

**Comment by Sing-Li** [comment]
@neynah   ...    @marceloschmidt  ==  AWESOME   :smile:

@paulproteus  - please if you get a chance, download  "the BETA SPK" here (not the latest one) to verify that the bug has been fixed.

https://rocket.chat/releases

Thanks!

**Comment by paulproteus** [comment]
@neynah can I humbly request that you follow SingLi's instructions to see
if the bug has been fixed?

**Comment by neynah** [comment]
@paulproteus @Sing-Li I can verify that the bug as been fixed. Yay! :)

**Comment by Sing-Li** [comment]
Thank you!    @neynah    -> Have a great evening !
