### ISSUE TITLE
Accept SMTP server with no logins

### ISSUE THREAD

**Issue by improvethings** [RocketChat/Rocket.Chat#1883]
I have postfix running on localhost port 25. 

In Rocket.Chat /admin/SMTP I have localhost, port 25, no user or password and rocketchat@MYDOMAIN.example.com. 
In /admin/users in the top right, if I click on the + symbol to add a user, it says "In order to send invitation emails you first must configure SMTP settings".

When I choose to send a test email, I get a popup saying, "Success! An email was sent to me@MYDOMAIN.example.com" but an email never arrives. How do I debug this? Nothing seems to hit my postfix mail.log. 

Also, what is the purpose of /mailer, there doesn't seem to be an option to save settings there.

**Comment by bgomelsky** [comment]
Take a look at line 3 of packages/rocketchat-lib/server/startup/settingsOnLoadSMTP.coffee, it only sets process.env.MAIL_URL when host, username and password configurations are set.  To fix it, try removing ` and RocketChat.settings.get('SMTP_Username') and RocketChat.settings.get('SMTP_Password')` from the if statement.

**Comment by Sing-Li** [comment]
@bgomelsky - thanks!   @improvethings - or just add a username and password to your `postfix` if you don't want to change code.

**Comment by Sing-Li** [comment]
@fduraibi - pls submit PR

**Comment by fduraibi** [comment]
PR https://github.com/RocketChat/Rocket.Chat/pull/1904

**Comment by fduraibi** [comment]
There is another issue related to this one when an admin is trying to invite users they will get a message saying they cannot since SMTP is not set. And that because `emailEnabled` is false.

That value is set here: https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-ui-admin/admin/users/adminInviteUser.coffee#L4

```coffeescript
emailEnabled: ->
		console.log 'emailEnabled', RocketChat.settings.get('MAIL_URL') or (RocketChat.settings.get('SMTP_Host') and RocketChat.settings.get('SMTP_Username') and RocketChat.settings.get('SMTP_Password'))
		return RocketChat.settings.get('MAIL_URL') or (RocketChat.settings.get('SMTP_Host') and RocketChat.settings.get('SMTP_Username') and RocketChat.settings.get('SMTP_Password'))
```
It still mandates the username and password but I thought the previous fix will at least set the "MAIL_URL" value and that would be enough but it seems both sides return false or nothing!

* The console returns "emailEnabled" only without false or true
