### ISSUE TITLE
Twitter tweets not unfurling

### ISSUE THREAD

**Issue by shoqvalue** [RocketChat/Rocket.Chat#18933]
We are new to rocket and was hoping it could help us with a crunch project that must be launched this Monday, We have it all running fine, but were dismayed to see that Tweets are not rendering as an oembed should.  This year old post by @geekgonecrazy suggests it's a known issue: 

https://github.com/RocketChat/Rocket.Chat/issues/15144#issue-478549960

Can anyone tell us how to fix this?  Our entire effort is kinda dead without it.  For example, what do I tell my host admin what he needs to do to "support web access" by rocket? (He's away until Sunday and can't answer).

I would be happy to contribute to documentation and explain this and other issues, if someone can explain it to me.

**Comment by rzaSF** [comment]
Ok, so I stumbled on this (https://github.com/RocketChat/Rocket.Chat/issues/12924#issuecomment-646759538) and added Twitter's script as discussed in the #12924 comment above.  That seemed to do the right thing.  It should just be rolled into Rocket.Chat as a configurable default IMHO.  This is too much work for expected behavior (as we see in virtually any collaboration package today).
