### ISSUE TITLE
node-gyp rebuild error

### ISSUE THREAD

**Issue by volo723** [RocketChat/Rocket.Chat#18984]
Ubuntu 18.04 LTS
followed this guid 
https://docs.rocket.chat/guides/developer/quick-start
but 

meteor npm install 

> canvas@1.3.12 install /home/ubuntu/chat/osp-chat-web/node_modules/node-sprite-generator/node_modules/canvas
> node-gyp rebuild

./util/has_lib.sh: line 30: pkg-config: command not found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/ubuntu/.meteor/packages/meteor-tool/.1.11.1.nmm7cg.gs54++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.3.0-1035-aws
gyp ERR! command "/home/ubuntu/.meteor/packages/meteor-tool/.1.11.1.nmm7cg.gs54++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node" "/home/ubuntu/.meteor/packages/meteor-tool/.1.11.1.nmm7cg.gs54++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/chat/osp-chat-web/node_modules/node-sprite-generator/node_modules/canvas
gyp ERR! node -v v12.18.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN @rocket.chat/eslint-config@0.3.0 requires a peer of eslint@^4.19.1 || ^5.16.0 but none is installed. You must install peer dependencies yourself.

![image](https://user-images.githubusercontent.com/65486138/93852020-9299e380-fcf4-11ea-9f9a-5b1a4f30e80f.png)

**Comment by dkoo761** [comment]
Having the same issue. The problem appears to be that node-sprite-generator depends on an old version of canvas which doesn't seem compatible with newer versions of node. I tried using the latest version of node-sprite-generator (npm installing from their Github master branch) and the error is still there even though their master branch is using a slightly newer version of canvas. node-sprite-generator is no longer maintained so this error will not be getting fixed in that package.

Since canvas is an optional dependency, we can ignore the error for now. However, I think the long term solution would be to either:

1) Fork node-sprite-generator, update it's dependencies and publish the updated version on npm
2) Replace node-sprite-generator with a different sprite package that doesn't have build errors and is actively maintained
