### ISSUE TITLE
Can't disable email verfications

### ISSUE THREAD

**Issue by axkibe** [RocketChat/Rocket.Chat#18992]
### Description:

I don't want verification emails to be send out.
I disabled "Verify Email for External Accounts" and I tried to set template empty.
they are still send out. (I still want to keep SMTP configured tough for password recovery)

### Steps to reproduce:

1. Disable "Verify Email for External Accounts"
2. Configure SMTP (for password recovery)
3. Optionally even restart the server
4. Register a new account
5. You'll get a verification email

### Expected behavior:

5. Not get a verification email 

### Actual behavior:

5. You'll get a verification email

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.2
- Operating System: debian buster
- Deployment Method: ta
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.14.0
- MongoDB Version: 4.4.1

### Client Setup Information

- Desktop App or Browser Version: Browser
- Operating System: debian

### Additional context

No.

### Relevant logs:

Not relevant I suppose

**Comment by dkoeh** [comment]
Any news on this - can email verification be successfully turned off?

**Comment by jpalmers** [comment]
I have the same issue,.

**Comment by battosai30** [comment]
Hi,

Nearly the same issue : email verification is disabled, but can't get email notification if email is not verified. With a test user I got no email notification until I manually send a verification email and email address got verified

**Comment by lebkayn** [comment]
I've got the same problem: I don't want to notify users and ask them to verify their email-address. Is there any way to disable that completely?

**Comment by 9joshua** [comment]
The year: 2024
The issue: Remains
![image](https://github.com/RocketChat/Rocket.Chat/assets/20234985/637ed51a-e7b8-4b14-a238-2660ffaf4f3c)
![image](https://github.com/RocketChat/Rocket.Chat/assets/20234985/752fa88f-94c0-418c-adbe-d85566ce27e1)
![image](https://github.com/RocketChat/Rocket.Chat/assets/20234985/24bc11a6-1631-4589-8625-838a8e0c0926)

**Comment by reetp** [comment]
> The year: 2024 The issue: Remains !

I think your issue is unrelated.

This issue relates to verification emails being sent to users.

admin/settings/Accounts 

Probably this setting:
Mark Email for External Accounts Verified

No idea if it still exists as this bug was against version 3.6.2 and we are now on 6.8.x

I think your issue relates to the requirement for 2FA for certain admin functions (Yes I hate it too). I think some of that can be overridden - check the forums for "twofactor"

Closing as this is a very old bug - please ask for support in the forums or https://open.rocket.chat/channel/support

If there is a something broken please raise a new issue.

**Comment by 9joshua** [comment]
Thank you @reetp - This setting was changed as well, still an issue...
![image](https://github.com/RocketChat/Rocket.Chat/assets/20234985/66f0ad1a-2965-41f4-9aac-579d64283647)
Will try to raise elsewhere however.

**Comment by axkibe** [comment]
FYI: I'm no longer using RocketChat so I can't say what happened to the original issue.

**Comment by reetp** [comment]
> Thank you @reetp - This setting was changed as well, still an issue...

> Currently RC requires authentication for new users when they sign in for the first time regardless of all these settings. 

In which case write a proper bug report on the latest version and open a new issue please (we are starting to close off the mountain of old bugs which are often irrelevant)

Thanks.

**Comment by 9joshua** [comment]
So I can wait four more years?

**Comment by reetp** [comment]
> So I can wait four more years?

You can, or you can do as I suggested.

Rocket.Chat is open source. If you want immediate support and fixes you can pay for it.

There are many things you are unaware of behind the scenes. I have suggested what you should do. Please take the advice I offered. It is probably in your best interest.

Thanks.

**Comment by 9joshua** [comment]
> Rocket.Chat is open source
RockectChat has become the most freemium software I know. I used to recommend it to everyone. Now I'm on the "Starter" plan, they want all my data and removed features I relied on to charge for them. I have been using RocketChat for many years and have created multiple issues that were never addressed. I know its history and it is a shadow if what it could have been.

**Comment by reetp** [comment]
`#metoo` and I was Community Manager here for a while as well. I know exactly how it works.

Regrettably, like it or not, Rocket has to make some money somehow, or you will have no software at all, or it will be totally paid for. I have recently seen too many projects close or go private because everyone wanted something for nothing. There are no easy answers.

I digress. Take my advice. Do what I have suggested. It isn't for fun.

If you wish to discuss the merits of open source/ Rocket etc then please use the forums or open where you can find me. 

Thanks.
