### ISSUE TITLE
Quotes in E2E chats are missing

### ISSUE THREAD

**Issue by rusty1281** [RocketChat/Rocket.Chat#19110]
### Description:

There seem to be missing quotes when chatting in an encrypted channel 

### Steps to reproduce:

01. click the "Quote" icon (opens a quote above the chat window, that works)
02. write a response
03. post

### Expected behavior:

As in a normal channel, expected response with a nested quote

### Actual behavior:

Considering it is a private encrypted chat, no screen, but the fact is that the result is only response gets posted, like a regular reply

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7
- Operating System: Linux
- Deployment Method: docker
- Number of Running Instances: 1 
- DB Replicaset Oplog: 
- NodeJS Version: v12.18.4
- MongoDB Version: 4.2.3

### Client Setup Information

- Desktop App or Browser Version: 2.17.9
- Operating System: macOS Catalina

**Comment by ankar84** [comment]
Confirm that issue

**Comment by baltazorbest** [comment]
Hello. Any news about fix?

**Comment by rusty1281** [comment]
True, but the regular quote is still not presenting itself.

**Comment by olafmertens** [comment]
I can confirm the bug. quoting doesn't work in our private channels.

**Comment by fanecovi** [comment]
Hello,

I can confirm this too.
In the preview, when you write a message it is visible. Probably it is not posted, as normally a link to the original message is used, what is not working in this case. Maybe there need to be a change to repeat it instead of link it? Even if the data in the database then grows more then with a link. This could be the price to pay for using E2EE.

On the other hand, in other situations, like threads, it is also working fine. And I guess, that Rocket.Chat is there also working with links to messages and not with copies. Maybe it is worth, to check, if it can not made work for quotes in the same way too?

From my experience point of view, quotes are important. If you just have one answer to a previous message, a thread is to much. Threads are good for small discussions or topic separations, where a discussion room is too much. But quotes are perfect for just an answer or two. Often you mix topics in a chat, especially in a chat with more people.

So I guess it could be worth to check, if it is not possible to improve the quotes (=make it working) for E2EE rooms.

Thanks!

/fanecovi

**Comment by Platt123** [comment]
It's been a while, but the issue still exists in 3.14
Afaik it was always there since e2e was introduced

**Comment by Guile17** [comment]
Did anyone get it fixed? Just wondering since I'd like to start using E2E.

**Comment by xcrone** [comment]
any update about this?

**Comment by undallesoyeah** [comment]
Would be very cool to get an update on this open issue. :)

**Comment by yash-rajpal** [comment]
Quotes for E2EE channels were implemented in #26303 and it will be available in 5.4.0 release.
