### ISSUE TITLE
Error: Mail command failed: 500 reset too many times. #ERR_REST_MANY

### ISSUE THREAD

**Issue by codeneno** [RocketChat/Rocket.Chat#19232]
### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server: 3.3.3
- Operating System:  ubuntu
- Deployment Method: docker
- Number of Running Instances: 20
- DB Replicaset Oplog: enabled
- NodeJS Version: 12.*
- MongoDB Version:4.*

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Additional context

Error: Mail command failed: 500 reset too many times. #ERR_REST_MANY

**Comment by MartinSchoeler** [comment]
Hey, looks like you are looking for support. You will have a better chance of getting help if you go to one of the places listed in [here](https://rocket.chat/docs/getting-support/#community-support) since github is not the best place to ask for support. For now i will be closing this issue, as it does not fit our issue guidelines
