### ISSUE TITLE
LDAP-Group-Sync not working and breaking login

### ISSUE THREAD

**Issue by Furragen** [RocketChat/Rocket.Chat#19461]
### Description:

When we enabled the LDAP-Group-Sync in our RocketChat to map ldap-groups to rocketchat-groups/channels it does not work.
We also got reports of users not being able to login anymore until we disable the feature.

### Steps to reproduce:
1. Setup working LDAP-Auth
2. Enable LDAP-Group-Sync
3. See that it is not working
4. Have users report that they cannot login anymore

### Expected behavior:

Ldap-groups get mapped to rocketchat-groups and users can still login.

### Actual behavior:

The mapping does not work and additionally some users can not login.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.1
- Operating System: CentOS 7
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.19.0
- MongoDB Version: 4.0

### Client Setup Information

- Desktop App or Browser Version: Client 2.15.1
- Operating System: Fedora 32

### Additional context

It might be important to note, that the ldap-server is active directory. Also, the mapping worked for some time, until it did not anymore.
The users who can not login also seem to change every time we enable the feature to try and test stuff. On login RocketChat gives these users an error saying their user can not be found.
It might also be worth noting, that our active directory is rather big (more than 1000 Users and a lot of groups also).
Maybe that is a problem.

### Relevant logs:

Sadly, the logs do not provide anything when this error occurs.

**Comment by PlusaN** [comment]
I see the same problem on versions 3.7.1 and 3.8.0. I tried to synchronize users on the test server by enabling LDAP-Group-Sync and realized what the problem was.
After synchronization, the user was created successfully, but when trying to log in, the chat was loaded endlessly:
![image](https://user-images.githubusercontent.com/61884717/99146670-54cd9180-268b-11eb-8081-c2b3c014cda2.png)
I got numerous errors in the browser console:
![image](https://user-images.githubusercontent.com/61884717/99146722-aaa23980-268b-11eb-9352-888809a3a686.png)
After that, I decided to take another look at the new user and saw that he was given a group without a name:
![image](https://user-images.githubusercontent.com/61884717/99146746-e3421300-268b-11eb-8899-b9806de2cb0b.png)
After deleting this group, I was able to log into the chat :)

**Comment by battosai30** [comment]
Linked to this issues ?
https://github.com/RocketChat/Rocket.Chat/issues/15621
https://github.com/RocketChat/Rocket.Chat/issues/15069

**Comment by Furragen** [comment]
I guess this is not relevant anymore, since this feature basically moved to RocketChat Enterprise and we nowadays use the Teams-Feature to map new users to multiple channels.
