### ISSUE TITLE
Rocket.chat in sharing production server?

### ISSUE THREAD

**Issue by maxlinux2000** [RocketChat/Rocket.Chat#1949]
Imagine you want to install Rocket.chat on a server where you already have other web services ... with a domain administrator, like CP or VestaCP or other similar. On the same server you have multiple domains, with phpbb, wordpress, bbPress, mysql, php ....

How to install rocket.chat in a subdomain within a server like this?

For example, I assign the DNS domain "chat.example.org" and VestaCP, automatically creates the subdomain /home/admin/web/chat.example.org

How To install mongodb rocket.chat with, and all you need in this directory without annoy the other domains, databases and web pages?

**Comment by djeber** [comment]
you can't you will need a vps server to get root access to install mangodb and nodjs

**Comment by Sing-Li** [comment]
@djeber  -  thanks.

**Comment by maxlinux2000** [comment]
No me he explicado bien. 
Yo tengo un VPS, y soy root, pero no puedo dedicar todo este VPS solo para Rocket.chat.
Esta claro que tengo que instalar nodej y mongodb, y no es un problema.
Pero he intentado crear un VPS en ubuntu14.04 con VestaCP como gestor de dominios, un wordpress en un dominio y rocketchat en un subdominio (los dos en el puerto 80 con el mismo IP:

www.example.org  para wordpress
and
chat.example.org para rocket.chat

Pero al final no me funcionaba nada.

Alguien tiene idea de como hacerlo?

**Comment by victornewman** [comment]
I have smilar question and I think many others. I have web site for this I have vps server and installed virtualmin, I can reach root I can create subdomain and I want to install rocket chat just for live chat.
Is it possible to setup on subdomain or we should forget about it?
If topic is closed so fast I think answer is no, we need to buy another vps server for chat but you know instead of paying for another vps it is look like better to pay one of solution partner and remove their powered xxxx part. right?
