### ISSUE TITLE
[3.8.0] Empty scrollbar trough appearing in channel list when using Firefox

### ISSUE THREAD

**Issue by jazztickets** [RocketChat/Rocket.Chat#19711]
### Description:

After updating to 3.8.0, there is now an empty scrollbar that appears in the channel list, though only on Firefox. The scrollbar is highlighted in red in the screenshot below.

### Steps to reproduce:

The bug always appears in 3.8.0 and still exists in 3.9.0.

### Expected behavior:

Works fine in chromium:
![good](https://user-images.githubusercontent.com/425930/100519879-e04d2500-3157-11eb-9f6a-085a4ef0b0a0.png)

### Actual behavior:

![bad](https://user-images.githubusercontent.com/425930/100519872-dc210780-3157-11eb-8807-fad6993587dd.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.0
- Operating System: Arch Linux
- Deployment Method: https://releases.rocket.chat/3.9.0/download
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.19
- MongoDB Version: 4.4.2

### Client Setup Information

- Desktop App or Browser Version: Firefox 83.0, running XFCE with Greybird theme.
- Operating System: Arch Linux

### Additional context

I was able to fix it by removing the overflow property as shown here:
![fix](https://user-images.githubusercontent.com/425930/100519950-69645c00-3158-11eb-878e-3d8e74859fb4.png)

**Comment by ggazzo** [comment]
hey, I'm sorry,  but the scroll was there since the beginning (for long lists), you never notice because your list has only 2 items...I would not consider a proper bug... but... good news! your problem was solved here: https://github.com/RocketChat/Rocket.Chat/pull/19701

It will be released at 3.10.0 ;) 

we implemented a custom scrollbar that should guarantee the same behavior for all browsers. Thanks for your time
