### ISSUE TITLE
Retention Policy settings not working correctly in channels

### ISSUE THREAD

**Issue by EnCz** [RocketChat/Rocket.Chat#19730]
### Description:

It seems like the retention policy configuration which you can overwrite in channels is a bit buggy. Sometimes the maximum message age doesn't work, then sometimes there is a maximum age of "30" even though nothing is configured.

I post example images to show what I mean.

**Our Retention Policy settings in Admin:**
![image](https://user-images.githubusercontent.com/7642122/100802407-b3d02c00-3429-11eb-884f-2d4f08399793.png)
![image](https://user-images.githubusercontent.com/7642122/100802438-c6e2fc00-3429-11eb-98ef-0386be663afd.png)

### Steps to reproduce:

1.  Create new private room
2. Open Room-Info -> **1st error: wrong Information:**
![image](https://user-images.githubusercontent.com/7642122/100802528-ec700580-3429-11eb-9d4d-c02fadb3a571.png)
I didn't set any retention policy settings yet so I don't expect a warning that something gets deleted here.

3. Click Edit -> Prune
4. Tick "Automatically prune old messages" and "Override global retention policy"
5. Set "Maximum message age in days (default: 30)" to 1
6. Click "Save"
7. Reload RocketChat and open Room Info again

### Expected behavior:

See retention policy info box with maximum age 1

### Actual behavior:

**2nd error:** Sometimes saw "30" again, sometimes saw "NaN".
If I repeat the steps above sometime it starts working again, cannot reproduce exactly though.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.0
- Deployment Method: docker

**Comment by cprice-kgi** [comment]
I noticed something quirky about this that might relate to your issue (and is probably a separate issue of its own). When the cron processes rooms with "custom" retention policies set, it does a query that looks to identify them by retention.overrideGlobal = true, retention.maxAge > 0, and retention.enabled = true. The first two checks are fine, but it seems retention.enabled is never set to true by default, so the "custom" portion of the cron doesn't ever locate rooms with overridden retention ages to process. (This is in 3.6.0, mind you, so it could be fixed by now).

That being said, what you can do is perform a save on the room info/prune screen (no need to change values). This initial save will set the enabled value of the record to true (initially it is undefined for some reason). Now, you can go back to the room info/prune area and override the maxAge value and save. Now, overrideGlobal and enabled will be set to true (correctly) and the cron will pick up and process the custom retention policy.

All of this is to say that maybe this "workaround" to setting the enabled flag properly could be something you could try that might resolve the issue you're seeing. I do also recall seeing the NaN on that page, but I never went back to check it again after I had figured out the problem with the initial setting of retention.enabled.

**Comment by brunobertoldi** [comment]
Thanks @cprice-kgi! I did something similiar and it worked!
The enabled/disabled for `retention.overrideGlobal` and `retention.enabled` were toggled multiple times at my server and nothing happened. But when I increased the `retention.maxAge` it worked properly!

I noticed a strange behavior in multiple channels with this retention policy.
When I tried to increase the default value, `1`, the value "changed back" to `1` again. After clicking one more time in the up arrow, the value changed to `2` correctly.
Maybe `retention.maxAge` was `undefined` as well as the other record you analyzed.

**Comment by saschaludwig** [comment]
Still the same problem in Version 6.3.7

Also, when I set the default retention to 365 days, the channels info shows that the messages will be deleted after 86342635 Years.

**Comment by marco-websource** [comment]
I see the same problem in 6.6.4: Setting a retention.maxAge in the channel settings UI does not work. The value always stays NaN.

I looked at the setting directly in MongoDB. There it is set to null/none. I could change it directly in the DB and then the correct number shows up in the UI. The pruning, however, does not seem to work. I set the maxAge to 2, but older messages in the channel remain there.

Is there a way to debug this, i.e. check that the pruning cronjob is actually running and see what it tries to do?
