### ISSUE TITLE
Other people still see emoticons in my messages when I disable them

### ISSUE THREAD

**Issue by kentonv** [RocketChat/Rocket.Chat#1980]
I'm one of those people who really dislikes emoticon graphics. In particular, I feel that a grinning yellow face communicates a different meaning than I intended with my `:)`, and it embarrasses when my messages are mangled in this way. However, I understand that I'm unusual in this opinion.

Currently, it is possible to disable emoticons in Rocket.Chat, but doing so does not do what I want. Disabling emoticons means _I_ don't see them in chat logs -- either in my own text or anyone else's. However, everyone else still sees emoticons appearing in _my_ messages, if they have them disabled. The result is that my meaning is still being mangled in ways that I don't like, but the mangling is being hidden from me.

I actually don't care what I see. I primarily care what other people see when reading my messages.

Therefore, I think disabling emoticons should mean that no one sees emoticons in my messages. Conversely, I should still see emoticons in other people's messages if they have them enabled, because for them the emoticon is what they intended. In other words, everyone sees exactly the same chat log, but the setting determines how my messages look in said log.

**Comment by kentonv** [comment]
Data points:

* Google Hangout's "convert text to emoji" option does what I want: converts outgoing text, not incoming.
* I am told, though I haven't confirmed myself, that Slack's "Convert my typed emoticons to emoji" also does the right thing.

**Comment by engelgabriel** [comment]
You win... :+1:  I'll investigate how we can do this :)

**Comment by engelgabriel** [comment]
:smile: :)

**Comment by kentonv** [comment]
Thanks!

FWIW, I would think the best thing to do would be to convert smiley sequences into actual Unicode emoji characters on the sending side, and then replace those emoji characters with graphics on the display end (but don't do any other replacement). That way you capture the sender's intent in a standardized and concise way. :)

**Comment by rvalles** [comment]
As a workaround, a global way to disable text to emoji conversion could be implemented.

This is seriously annoying, as code oneliners do turn into an emoji mess in the other end.

**Comment by geekgonecrazy** [comment]
@rvalles do you not normally surround like this `one line code snippet` ?  I've found this as standard on most platforms.  If its replacing inside of those then we have a bug.

**Comment by rvalles** [comment]
@geekgonecrazy, while I could succeed at remembering to do that, getting all the devs to do it at all times is harder than getting them to disable emoticons altogether.

The issue is that, even with text to emoji transformations disabled (so things look fine in your end), the transformations do happen in the receiver end. This is very frustrating behaviour.

All of this could be avoided if text to emoji transformation disabled at source delivered untransformed text regardless of receiver end's setting. Or if there was a global option to disable the transformation. Or if there was a global option to disable emoji altogether, a feature we don't need or enjoy in any manner.

**Comment by geekgonecrazy** [comment]
Understood.  Thanks for the clarification around your use case!  :+1:
