### ISSUE TITLE
missing / wrong emoticon

### ISSUE THREAD

**Issue by prohde** [RocketChat/Rocket.Chat#2013]
Rocket.Chat (version 0.14.0) lists the emoticon mapped to `:cry:` also for `:'(` but after sending the message it remains `:'(`.
I would appreciate removing `:'(` from the list or mapping it to the listed emoticon.

**Comment by graywolf336** [comment]
I vote for mapping it to the listed emoticon.

**Comment by prohde** [comment]
There are some other standard ones which are not even listed like `;)`

**Comment by graywolf336** [comment]
@prohde that one is mapped, I just tried it myself on the demo instance.

**Comment by prohde** [comment]
@graywolf336 Tried it on my own instance right now. It is mapped but there is no list showing this emoticon while writing.

**Comment by barnardm** [comment]
Confirmed, there is a mapping for :'( to sad but it is not being processed correctly. It looks like the root of the issue is that any emoji shortcut with a single quote is being html escaped. Once the single quote has been converted into &#39; it doesn't match the string in the emoji package. I'm working on a PR for this.

**Comment by graywolf336** [comment]
@barnardm How's the pull request coming along?
