### ISSUE TITLE
Cannot "meteor npm start" Rocket.Chat

### ISSUE THREAD

**Issue by Joey-Nguyen** [RocketChat/Rocket.Chat#20150]
### Description:

Hi @ALL,

I have followed the correct steps on guides for Win 10 (https://docs.rocket.chat/guides/developer/developing-on-windows-10). But it's showing error like image below:

![PermissionDenied](https://user-images.githubusercontent.com/64880211/104172600-1e1bb980-5437-11eb-8e7d-d06c35429267.png)

Can someone help me to solve this issue? Thanks

### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by dougfabris** [comment]
@Joey-Nguyen We strongly recommend you to use WSL 2 instead of the Windows PowerShell.

Please, follow the pre-requisites before you start:
- Make sure you have Windows 10, version 2004 or later
- Install and configure WSL 2 by following Microsoft documentation,  making sure to select Ubuntu 20.04 LTS distribution as your choice of Linux
- Download and install the latest Linux Kernel Updates

**Comment by Joey-Nguyen** [comment]
I did but it still didn't work. I switched to Ubuntu
Thank for your support

**Comment by dougfabris** [comment]
@Joey-Nguyen Well, I'm running Rocket.Chat on windows right now! If you need more help, feel free to send me a private message on our open server!

**Comment by Joey-Nguyen** [comment]
@dougfabris : I sent you a private message on https://open.rocket.chat/. Please help me
Thanks
