### ISSUE TITLE
Chat won't show again after clicking 'show' on tray icon

### ISSUE THREAD

**Issue by JamieVampire** [RocketChat/Rocket.Chat#20206]
### Description:

I have just updated my Rocket.Chat client from v. 2.15.3 to v. 3.1.1 and now it shows a very weird reaction when using the tray icon. The chat window won't come back up again, so that I'll have to invoke Rocket.Chat by using Alt + F2 (I'm on Linux), which is the same that I usually do to open a program - not that Rocket.Chat is closed at any time, just the chat window won't show. 

### Steps to reproduce:

1. Updated Rocket.Chat client to v. 3.1.1 
2. Opened my client and then first tried to click on the 'x' to send the chat window to the trayicon
3. Couldn't get the tray icon to show my chat window again
4. New try: minimized the chat window to the taskbar (and tray icon, it's both there) and try to show my chat window again by clicking on the tray icon

### Expected behavior:

So, if I click on the 'x' in the upper right corner of Rocket.Chat, the chat window closes and there's only the tray icon left. Usually, when I click on the tray icon and then subsequently on the option 'Show', the chat window just comes back up. The same happens for when I click on the minimize Button in the upper right corner of the program and have the tab in my taskbar and the tray icon. I just click on the 'Show' of the tray icon and the chat window will come back up.

### Actual behavior:

Now, when I click on the 'x', the chat window closes and I can still see the tray icon. But when I click on the option 'Show', nothing happens, the chat window won't open up again. What's even worse is that when I only minimize the chat window and still have my tab in my taskbar, then click on 'Show', the tab vanished completely and all I see is the tray icon, with which I can't open up the chat window again. If, after minimizing the chat window, I directly click on the tab in my taskbar, my chat window will come up again.  

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.1
- Operating System: CentOS Linux release 7.9.2009
- Deployment Method: .tgz file
- Number of Running Instances: 1 
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.14.0 - x64
- MongoDB Version: 4.0.21

### Client Setup Information

- Desktop App or Browser Version: 3.1.1. (installed with the rocketchat-3.1.1.x86_64.rpm)
- Operating System: Fedora 33

### Additional context

Since I'm not 100% sure that I'm using all the correct terms (and I'm reporting a bug for the very first time), I've made some small pictures. 
![rocketchat_taskbar_trayicon](https://user-images.githubusercontent.com/52073901/104609005-d7ba9a80-5682-11eb-96ec-be9f29b92a32.png)
![rocketchat_trayicon_show](https://user-images.githubusercontent.com/52073901/104609021-dc7f4e80-5682-11eb-96af-1ae095838341.png)

### Relevant logs:

I haven't really found any relevant information in the logs that I could find. Certainly not on the server (saw that everything is working correctly by checking the service and having a look at the journalctl) but I can't really find any errors when logging into the client with an admin and having a look at the log messages there.

**Comment by vimu86** [comment]
I think I have the same or a related issue.

I am on Ubuntu and moved from the outdated snap version 3.0.x to  3.1.1 from repository.

After a few days of normal operation, I have now the problem, that rocketchat-desktop appears after launch only in the tray icon. But if I click on "show" in the tray icon menu, nothing happens. So, I can not see any rocketchat window.

**Comment by adocampo** [comment]
I forgot to add my +1 here a while ago.

I ended unchecking the View --> Tray Icon so when I close RC it really closes, because if the tray icon is shown, when I close RC, it closes, but I can't even open it back. So disabling the tray icon is the only workaround, if you close accidentally the chat, at least you need simply to open it back, yet it's a bit annoying to lose messages in the meanwhile.

The worst part is, closing the application and opening it back, it starts directly iconified, so I can't show the GUI no matter what I do. The only way to restore it back is by deleting the `~/.config/Rocket.Chat/` directory and configuring the application from the start, by entering server data and credentials.

Others didn't specify their desktop, I'm on Arch Linux with Plasma Desktop 5.21.2, but this issue has been happening for a while now, perhaps since the 3.1.1 update, I'm not pretty sure because I didn't remember exactly when, but months ago for sure.

Tired of this situation, I've found a native desktop application developed by KDE, [ruqola](https://github.com/KDE/ruqola). It's not as fancy as RC, nor it has all the bells and whistles, but it has it own good parts: it's _native_, not a webapp embedded and CPU (0% usage) and RAM (70MB) usage is far lower than this RC electron-or-whatsoever-webapp engine uses RC client, which just starting consumes 300MB RAM (and can grow up to 2GB and CPU in "idle" is 3% in linux -in mac is even worse, like a 10%-) . Besides, it's written in pure C++ and with the QT toolkit, so it's portable to any platform, including mobile devices.

**Comment by agilecontent-bassani** [comment]
Same problem here.

> The only way to restore it back is by deleting the ~/.config/Rocket.Chat/ directory

It seems that the 'show' action from the tray icon menu is not setting rootWindowState.visible to true. You can edit  ~/.config/Rocket.Chat/config.json and set it manually.

**Comment by cesarrew** [comment]
Same problem here. Using Pop OS 20.04 and the 3.1.1 flatpak version. I've downgraded to 3.0.7 version using the code below and now it worked.

`
flatpak update --commit=7d9596d1712a91407e0e99cd9b1e029e055b0efa6a3dafdd223c1253cfc5af57 chat.rocket.RocketChat
`

**Comment by itkfm** [comment]
Same here. Snap version. App is completely lost in tray.
Quiting it in tray and re-opening it doesn’t make it show up again. It goes straight into tray again.

**Comment by JamieVampire** [comment]
Alright, after just updating to Version 3.2.2 (using the rocketchat-3.2.2.x86_64.rpm package) it seems like the problems have vanished. I'll keep an eye on that and make sure that it's working, if everything's fine,I'll report back in a few days.

**Comment by Blueshawk** [comment]
I can verify that it works now on Artix(arch)/cinnamon/runit.  I'd like to add a plug for an enhancement on this issue though. 

It would be great if we could click toggle the tray icon like other icon apps instead of the drop down.

**Comment by JamieVampire** [comment]
Wanted to quickly report back. We're not having trouble anymore with the 3.2.2. Version, so from my point of view this Issue can be closed (don't know exactly if I'm supposed to do that, since I haven't done this before?).
