### ISSUE TITLE
Regression of 19052: User Info shows email 'Not Verified' when it actually is verified

### ISSUE THREAD

**Issue by nooblag** [RocketChat/Rocket.Chat#20249]
### Description:

Regression of #19053 in RC 3.10.3.

In Administration -> Users, in User Info panel, it is shown that user email address is 'not verified' when it is known for certain that the user's email address IS verified.

### Steps to reproduce:

1. Open Administration -> Users
2. Select a user with a known verified email address
3. User Info panel displays email address 'not verified'

### Expected behavior:

Panel displays correct information

### Actual behavior:

Panel displays incorrect information

![1](https://user-images.githubusercontent.com/1122344/94523376-693d0280-0274-11eb-96d9-59ae28769e76.PNG)
![2](https://user-images.githubusercontent.com/1122344/94523379-6b9f5c80-0274-11eb-9b2f-8ad31ce6ab62.PNG)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.3
- Operating System: Ubuntu 18.04.5 LTS
- Deployment Method:  TAR, manual
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.18.4
- MongoDB Version: 4.0.22

### Client Setup Information

- Desktop App or Browser Version: Firefox 84.0.2
- Operating System: Linux Mint 19.3, 20.1; and Windows 10

### Additional context

Not at the moment.

### Relevant logs:

No relevant logs.

**Comment by hans4rc** [comment]
Same in 3.9.4 and 3.10.4

**Comment by muditjuneja** [comment]
I just took the latest develop and found that it is showing me the email as verified. I created a new user and marked his email as verified but when I tried logging in with the new user then, it asked for the verification code. Is this the expected behavior? I checked the logs and found the code for the new account. Are those emails required if I am marking a user as verified?

**Comment by muditjuneja** [comment]
And, I am seeing the email status as verified for the new user.

**Comment by mgelde** [comment]
I am seeing this in 3.10.5. It seems to happen regardless of whether admin verified users by marking the email as verified (as above) or user self-verifying via link. It's quite annoying.

Some users do not receive notification and I suspect it is because they are 'not verified'; what I have a hard time debugging now is who is really not verified vs. falsely not verified.

**Comment by nooblag** [comment]
Closing, as gave up on Rocket Chat many years ago.
