### ISSUE TITLE
No user roles displayed in the thread replies

### ISSUE THREAD

**Issue by zdumitru** [RocketChat/Rocket.Chat#20282]
### Steps to reproduce:

A user with special role, e.g. `Admin` that is displayed next to his username needs to do the following:
1. Go to any public or private channel or direct message
2. Find a message
3. Write a thread reply
4. Check that there is no role e.g. `Admin` displayed next to the username. --> a bug

In the regular messages, all user roles are displayed correctly.

### Expected behavior:

Display user roles next to the username in the thread replies, the same way it is done in the main messages.

### Actual behavior:

![image](https://user-images.githubusercontent.com/11751017/105184141-4c804f80-5b2f-11eb-988f-bfe0b4aaad66.png)
_Note the user roles `Admin` and `M` in the main thread for the user `dumitru`. And no roles in the thread reply message for the user `dumitru`._

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.3
- Operating System: Linux
- Deployment Method:  snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.18.4
- MongoDB Version: 3.6.14
--

### Client Setup Information

- Desktop App or Browser Version: browser version
- Operating System: Ubuntu

**Comment by pratyaksh123** [comment]
Hey, Can I work on this?

**Comment by zdumitru** [comment]
> Hey, Can I work on this?

Sure

**Comment by dougfabris** [comment]
@zdumitru Unfortunately, we're skipping this functionality for now. We have concerns about UI because of the contextual bar space. For example, users with bigger username lengths and the same for the role's length. We're reporting to our design team to help us with a better solution to this case. For us, it's not a big problem for now since we can just click on the user's profile and see the roles quickly. Thanks for your help!
