### ISSUE TITLE
Android APP high battery usage

### ISSUE THREAD

**Issue by florian-shellfire** [RocketChat/Rocket.Chat#2030]
The rocket chat Android APP eats a lot of battery on my one plus one:
![screenshot_2016-01-25-22-43-16](https://cloud.githubusercontent.com/assets/12492529/12565660/c80821e4-c3b5-11e5-9e56-117b9fa452cd.png)

**Comment by himbeere** [comment]
The android app does not work at all on my phone. I'm getting "Waiting for server connection..." allthough connection to https://myserver is possible via browser. Any hints for solving this?

**Comment by philipwhiuk** [comment]
Same here @florian-shellfire (Nexus 6P)

Does anyone know why - is it constantly polling the server for updates?

I'll see if it's spamming the logs or something by attaching ADB this evening. Maybe there's some quick-fix bugs that can resolve some of it.

**Comment by griiot** [comment]
same here  @florian-shellfire (galaxy S6)
it's crazy how it just eats the battery.

**Comment by gcassel** [comment]
This is an important issue:  can any devs comment please?

**Comment by cjanietz** [comment]
@himbeere Do you have a http proxy in front of your Rocket instance? If so, your mobile device wont fallback to regular polling. For the browser this usually works. You need to configure your proxy to handle HTTP upgrade for websocket connections.

As to the issue of this, I see repeated requests of /_timesync, this is most likely related to the Javascript background thread having timing issues when the device is locked. I'm looking into fixing this right now, but as of now I'm not 100% sure this is the only problem.

**Comment by cjanietz** [comment]
I seem to have resolved the issue by disabling timesync when the app is put in background mode. The issue here is that when your app is put in background mode, the javascript eventloop runs on a non deterministic schedule, meaning even though the timesync wants to check every second whether your computer/phone delay has a bigger difference of 5 seconds since last check.This will most likely happpen as the device is not woken up that often. Further it causes the app to call /_timesync on your server very often, draining your battery by initiating regular net connectivity.
As much as I would like to offer a patch, it's an issue related to a non Rocket package meteor-timesync and I will open an issue there.

**Comment by geekgonecrazy** [comment]
@cjanietz can you link us to the issue you created there?  Thanks 👍

**Comment by simopaasisalo** [comment]
Any update on this? On my devices this seems to only happen quite randomly. Sometimes when I leave the chat application open for the night, my battery is drained radically due to this bug.

**Comment by Nirkus** [comment]
The RocketChat Android app also drains the battery of my FP2. Any way to support root-causing the symptom?

**Comment by TheReal1604** [comment]
https://github.com/RocketChat/Rocket.Chat.Cordova/issues/112 Opened an issue some months ago..

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

The problem seems to have been fixed by RocketChat/Rocket.Chat.Cordova#112. Therefore I#m closing this issue.

Cheers
Thomas
