### ISSUE TITLE
Question about security hot fix in 3.9.7 version

### ISSUE THREAD

**Issue by emikolajczak** [RocketChat/Rocket.Chat#20438]
### Description:

Hi I have a question about versions released today with security hotfix. What exactly is root cause of this fix and how serious is vulnerability?

### Steps to reproduce:

1. n/a

### Expected behavior:

n/a

### Actual behavior:

n/a

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.4
- Operating System: Centos7
- Deployment Method: docker-compose
- Number of Running Instances: 30
- DB Replicaset Oplog: YES
- NodeJS Version: 
- MongoDB Version: 4.0.14

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Additional context

n/a

### Relevant logs:

n/a

**Comment by xoxys** [comment]
Publishing a release flagged as security hotfix without further information isn't really good communication. Especially as neither the commit message nor the reflecting PR has additional information. So, right now there is a fix available for an unknown security vulnerability with unknown impact...

**Comment by xcpdq** [comment]
> Publishing a release flagged as security hotfix without further information isn't really good communication. Especially as neither the commit message nor the reflecting PR has additional information. So, right now there is a fix available for an unknown security vulnerability with unknown impact...

I agree. What about users who until 9 hours ago were using the 3.10.4 "latest" release? 3.10.5 was also released but it's not tagged as "latest".

**Comment by mhow2** [comment]
It seems the page at https://docs.rocket.chat/guides/security/security-updates has been updated

**Comment by xoxys** [comment]
What the heck... do you mean all `fixed at 2020-01-26` entries?

1. Wrong year
2. **Nine** security issues including high and critical are fixed in a single release with a release note like "Security Hotfix"?
3. Security fixes are announced in a nested, not easy to find page in the **docs**?

Nothing to add :zipper_mouth_face:

**Comment by Gummikavalier** [comment]
While rest of the updated notes for different versions said only hotfix, rc3.11.rc.1 release notes mentioned this:
https://github.com/RocketChat/Rocket.Chat/pull/20430

**Comment by makibras** [comment]
> What the heck... do you mean all `fixed at 2020-01-26` entries?
> 
> 1. Wrong year
> 2. **Nine** security issues including high and critical are fixed in a single release with a release note like "Security Hotfix"?
> 3. Security fixes are announced in a nested, not easy to find page in the **docs**?
> 
> Nothing to add 🤐

a couple of things went wrong with the infos on that release, apologies for that. We will improve.

About the points you made:
1) fixed
2) we will better integrate the security fix explanations to the release notes. it is called security hotfix because these releases only contain security hotfix(es). but i hear your criticism that the additional infos are not on the release notes. noted and we will change that accordingly.
3) no. we want to point them out better in the release notes and collect a history of fixes in this docs page.

as the original question of this issue was answered in the docs page, I will close this issue. (but the improvements mentioned will be put in place)

**Comment by georgschoelly** [comment]
The [snap version](https://snapcraft.io/rocketchat-server) of rocket.chat is still at version 3.9.3, is there an expected date for the release of a new snap version? Maybe a special version 3.9.3.1 with the security bugs fixed?

After all, [they are](https://docs.rocket.chat/installation/snaps#when-will-my-snap-installation-get-the-latest-release)

> [...] one of our biggest install base. They are also auto updating.

and afaik Snap has been the recommended installation method [until recently](https://github.com/RocketChat/docs/commit/53b7b1a01a1377ee6348c85343d7bb8f0e925b93#diff-68ec918fb1f84d3f1af207433e304009f3aaa357de5840d3198eff1611dedc67) (now it seems to be docker).
