### ISSUE TITLE
Add Gender selection and specific gender channels only

### ISSUE THREAD

**Issue by djeber** [RocketChat/Rocket.Chat#2048]
it would be nice to let users select their gender during signup and existing users can select it by editing their profile and also make the username color for female purple and for male blue or something like that and the ability to make a channel accessed by a specific gender only

**Comment by onigoetz** [comment]
I can see how this feature looks like a good idea but will be abused in every possible way ...

Looks very sexist to me.

**Comment by Ya-Ri** [comment]
Hi,

i find also that it will be a good idea, we use rocket chat at the french "nuit debout" movement
https://chat.nuitdebout.fr/
Many have subscribed but there is a lack of informations on their profile.
It will be nice to have the gender(with a special color), the city and the age or any custom fields to fill
By the way, jarvis bot has been replaced by aiva.

I am glad to use your product, you look like a dynamic and brillant team, thank you for rocket.chat

Regards,

YaRi

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

I am closing this because, as it is described here, there is no actual use in implementing this, as you're trying to build and access restriction to channels that is based on a setting that is controllable by the user him-/herself, so this is actually no enforcable access restriction.

I won't go into the implications of separating genders and whether this is something one wants, as it is beyond the scope of this issue.

Cheers
Thomas
