### ISSUE TITLE
[BUG] Name field under Add New User section in Admin doesnt work as expected

### ISSUE THREAD

**Issue by Ashray123** [RocketChat/Rocket.Chat#20610]
### Description:

While adding a new user through admin, it happens so that the "Name" field also accepts numeric values, which must be restricted because here the "Name" field should only contain the "Full Name" of the user, and Full name cannot contain any numeric characters.

### Steps to reproduce:

1. Click on your profile picture on your left.
2. Select Administration from the list.
3. Select Users from the list. 
4. On your right, click on "+ New" .
### Expected behavior:
There should be a Placeholder that tells the admin to input the "Full Name" of the user or a warning message should be displayed with the text "alpha-numeric characters are not allowed" and under the Full Name field, there should be only Full Name of the user displayed, for ex: Michael Jackson and not Michael1234.

### Actual behavior:

https://user-images.githubusercontent.com/40429213/106949046-80c05680-6752-11eb-820b-2d03ef66e36f.mov

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0-develop
- Operating System: Mac os
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Browser Version
- Operating System:

**Comment by Ashray123** [comment]
I am working on it .

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Closing this one because it's not a proper issue, we cannot block users from adding numbers to their names. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
