### ISSUE TITLE
Choose Rtl Or Ltr

### ISSUE THREAD

**Issue by hooramin** [RocketChat/Rocket.Chat#2072]
hello
RTL version of theme has some bugs that i don't think they'll be fix soon or completely at all!
and maybe some one don't like to change direction of page in rtl based languages !
it better to make an option in theme setting to choose rtl or ltr theme !
thank you

**Comment by marceloschmidt** [comment]
Could you please list the bugs found? It sure makes it easier for us to track them down if we know which bugs you're talking about. If there are open issues for them, list them here and we can create a label to group them into one category... we could use the help of "rtl developers".

**Comment by fduraibi** [comment]
I use the RTL interface and I don't see any problem with it, at least nothing obvious.

@hooramin Can you share with us what are the bugs that you see/have?

**Comment by hooramin** [comment]
the first and most important bug that is in #editor !
in rtl mode you can not type in ltr mode, even if you want to type english !
Ctrl + shift is not working too !
in rocketchat demo i use an rtl language but every time i chat english , and have so many problem for moving text marker backward and forward
---------------------------------------
i know that there are other annoying bug but i can't remmeber now ... every time i faced them i will share it here ...

**Comment by fduraibi** [comment]
I am afraid that what you are talking about is not a Rocket Chat specific bug or problem, instead it is an issue in any application when you mix RTL and LTR together. And Ctrl + shift is not a general control, it is application/OS specific.

I use Rocket Chat, Slack, Whatsapp, Twitter, LibreOffice, Android Studio....etc and they all have the same issue because RTL and LTR do not mix in a friendly way they are naturally opposite of each other.

In regard to Facebook, the only enhancement they have (I just tested it) is that they detect the first letter and switch the direction based on that, and they use a script to accomplish this task since you cannot do it with just CSS and HTML. But other than that mixing RTL in LTR in facebook editor is a miss just like every other app/site.

For Rocket Chat, if you use an LTR language the editor direction will work fine, since it is set to auto
`
dir="auto"
`
and with that the browser will check the first letter and switch the direction automatically.

However, when you use an RTL language you need to change the default text alignment to Right, otherwise the browser will default to Left. `text-align: right;`
And that statement misses up hte `dir="auto"` and makes it ineffective.

The other problem, let say we implemented a script that switches the direction based on the first letter, should that be done only in the editor but in the chat list have every thing shown in one direction? I think that would be useless since what you see in the editor will be different from what you get after sending the message.
The other solution is to match the direction between the editor and the chat list, however, this one creates a bigger problem, the conversation (chat list) will become a miss, keep in mind that numbers (0, 1 ,2 ...etc) are going to be considered LTR, so if I ask about a price in RTL language and someone reply with just a number the the reply will be treated as LTR and shown on the left side.
Following such conversation will be very complicated specially with a very wide chat window. (Facebook has very narrow message boxes so you don't see this as an issue) check this picture to see what I mean:

![rocket](https://cloud.githubusercontent.com/assets/432460/14933230/02556c90-0e56-11e6-90e1-ab2b8a918403.png)

I would love to find a true solution for this problem since I suffer from it myself but I didn't see any way to implement it since as I say LTR and RTL are naturally opposite. If you know of any chat application similar to Rocket that have implemented this correctly then tell me about it and I will try to find out how they solved it.

**Comment by hooramin** [comment]
thank you for your complete answer ...
i got what you mean , editors always had problem with ltr and rtl ... i'll search and think about a solution! but i think it will be completely solved in HTML 6!! :laughing: 

but now at least we can put a separate class for editor style that keep text alignment just for editor to left , then auto direction will work fine ! ( i'll try this now on my fork for test )

but about messages that shown in chat list , most of messengers like whatsapp web or telegram web and ... solve the messiness of conversations with bubble around the messages ! (you can see in this image )
![untitled-25](https://cloud.githubusercontent.com/assets/13273931/14933458/22115b76-0ea5-11e6-8354-e1fe2cea9821.jpg)
unfortunately i don't think rocket chat developers like this design and we should wait until a new unknown solution will be find.

**Comment by fduraibi** [comment]
Since Rocket chat now supports custom CSS and Javascripts, I think you might be able to change the look of the chat to be what you like ;)

**Comment by hooramin** [comment]
Hello Mr. @marceloschmidt  
I will list bugs of rtl version in this thread , so please change this thread's title to a relative sentence.

1 : I Told first bug at previous post in this thread and that was about editor , the bug is still alive ! :)
2 : You can easily find some bugs in rtl mode  just with two clicks : 
When you are in a conversation (Direct or public channel ) Click on any of leftside icons to open left sidebar ,
Now click again on that icon to close the sidebar again ! , You will see messages go under right panel menu !

**Comment by SafaAlfulaij** [comment]
@hooramin #3714

**Comment by hooramin** [comment]
@SafaAlfulaij Thank you for your response and attention .
This thread is not related to just one issue  , As @marceloschmidt  asks, i will list all of RTL bugs in one place .
so help me to do this if you found more bugs ! :wink: 
-------------------------------
@marceloschmidt @engelgabriel I Repeat my request now , please add an option in admin panel to switch rtl and ltr mode until issues be solved.

**Comment by SafaAlfulaij** [comment]
> This thread is not related to just one issue

That one provides a fix for:

> 3 : You can easily find some bugs in rtl mode just with two clicks : 
> When you are in a conversation (Direct or public channel ) Click on any of leftside icons to open left sidebar
> Now click again on that icon to close the sidebar again ! You will see messages go under right panel menu !

**Comment by engelgabriel** [comment]
@MartinSchoeler can  you take a look at this?

**Comment by engelgabriel** [comment]
Guys, were those issues addressed by https://github.com/RocketChat/Rocket.Chat/pull/3730 ?

**Comment by engelgabriel** [comment]
Hi @fduraibi @hooramin and @SafaAlfulaij what do you think about #3730 ? Does it fixes some of the issues?

**Comment by fduraibi** [comment]
I believe this solved the first issue, the second one was solved earlier by another patch.
