### ISSUE TITLE
3.12.x Jitsi integration broken (Jitsi gets reloaded every few seconds)

### ISSUE THREAD

**Issue by fdellwing** [RocketChat/Rocket.Chat#20946]
### Description:

Since updating to 3.12.0 the jitsi integration broke. You can still start new calls and join them, but the jitsi site (or panel) will be reloaded every few seconds resetting the connection.

### Steps to reproduce:

1. Start a call
2. Watch how RC triggers the call every few seconds resetting the established connection

### Expected behavior:

Work as in 3.11.x

### Actual behavior:

Jitsi gets reloaded every few seconds

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.0
- Operating System: Ubuntu 18.04
- Deployment Method: docker-compose
- Number of Running Instances: 3
- DB Replicaset Oplog: enabled
- NodeJS Version: 12.18.3
- MongoDB Version: 3.6.9 (WT)

### Client Setup Information

- Desktop App or Browser Version: Chrome 88
- Operating System: Win10 / Linux

### Additional context

We use our own jitsi instance and JWT is enabled.

### Relevant logs:

No error in log.

**Comment by xi67** [comment]
Same Here

**Comment by jcmerg** [comment]
same issue here, bug occurs only within 1:1 calls ... calls opened in groups or channels are not affected

**Comment by archiekennedy** [comment]
This is happening to us too. Closing rocketchat seems to fix the problem.

**Comment by EpSch** [comment]
Same here

**Comment by mokilcde** [comment]
Same here

Question: Is it possible to use 3.11 again? There are any problems with the MongoDB?

**Comment by NecatiMeral** [comment]
This happens even in group channels for us.

**Comment by Tal810** [comment]
same here

**Comment by HiveMindNet** [comment]
> Same here
> 
> Question: Is it possible to use 3.11 again? There are any problems with the MongoDB?

We ended up restoring from backup to roll back I'm afraid. It's pretty painful when Jitsi gets broken; it's an essential feature of daily work for us.

**Comment by johnypeterson** [comment]
The same behaviour

**Comment by miko007** [comment]
we also experience this on macos, but with jitsi opening in the main rocket.chat window and/or spawning tens of windows all over the place.

i really do not understand the issues with stuff that already worken getting broken by an official update. do you guys not test the software before releasing an update?

the last update broke links, that then opened in the main rocket.chat window, which i think should not even be possible, so someone disabled the sandbox on electron thus allowing it to arbitrarily open links to other websites in the app, which is a major security concern.

this update explicitly fixed that issue and now jitsi integration is broken once again.

a lot of people are deeply dependent on those core features in this cov-sars-2 pandemic and a rollback is not even possible without losing all data since the last backup. i would really appreciate you taking more care in preparing an update and releasing it to the public.

We could easily deal with bugs in any part of the system, if at least the core functions "chat" and "videochat" would be working consistently.

**Comment by knordsiek** [comment]
Same problem here. If you close the right frame you can join the jitsi meet without failure.

**Comment by adocampo** [comment]
Just called a workmate, and instantly 6 jitsi windows appeared. I'm on Linux 

![imagen](https://user-images.githubusercontent.com/2266612/109648468-f0abdc00-7b5a-11eb-943d-636a1b1747e9.png)

he's on windows, and not much better
![imagen](https://user-images.githubusercontent.com/2266612/109648807-58622700-7b5b-11eb-8a65-9dce28209565.png)

It happens both in the desktop app and browsers, tested on chrome and firefox and on Linux and Windows.

**Comment by xi67** [comment]
I think the not test this functionality at all. They think it's optional. Sorry but in 2020 video cal is a requirement for a chat solution.
It's the second realease which break this functionality. which is testable on https://open.rocket.chat/ ...

**Comment by HamzaKhait** [comment]
Hello,
Same problem here. We use Jitsi+Rocket.Chat with JWT integration. is there any patch to fix this problem ?

**Comment by miko007** [comment]
@HamzaKhait unfortunately not. it probably will get fixed in the next release, but usually that takes a few weeks...

i wonder if the paid service is affected by this, too...

**Comment by felipetomm** [comment]
> i wonder if the paid service is affected by this, too...
Yes @miko007. That's the point here.. the bug are present in our enterprise server.

**Comment by fdellwing** [comment]
I'm pretty sure this has to be fixed with a hotfix asap, but so far no member has commented on this at all.

**Comment by Tal810** [comment]
I just had a meeting going on for 6-7 minutes and no prompts.
Is this resolved or are you still seeing this in your instances?

**Comment by cuchipkg** [comment]
same here

**Comment by ankar84** [comment]
@sampaiodiego @rodrigok @ggazzo hey team!
I think it's a really critical issue for a large amount of user (and I'm in that scope too).
So, please, fix it ASAP in hotfix version.
Thanks!

**Comment by ankar84** [comment]
Somehow https://rc.server.com/api/v1/method.call/jitsi%3AupdateTimeout is the reason for that issue

**Comment by yash-rajpal** [comment]
I feel the reason why this happens is the because of a dependency passed to useMemo which initiates jitsi calls. This dependency triggers useMemo function for no apparent reason according to me, due to which jitsi is reloaded or a new window appears.

If any of you are using Jitsi call in new window, a temporary work-around can be after initiating a jitsi call, close the video conferencing tab bar. If the tab bar is closed the call jitsi component is no longer called solving the problem temporarily.

**Comment by ankar84** [comment]
> If any of you are using Jitsi call in new window, a temporary work-around can be after initiating a jitsi call, close the video conferencing tab bar. If the tab bar is closed the call jitsi component is no longer called solving the problem temporarily.

Confirm that workaround! Works for me!
Just close that panel in right
![image](https://user-images.githubusercontent.com/4023037/109783457-126c9800-7c1b-11eb-8e91-400a91ad24bb.png)

**Comment by fdellwing** [comment]
Another question, why is the panel even opening if "open in new window" ist active? It did not do that with 3.11.x.

**Comment by corrigac** [comment]
Same issue seen on Mac(Big Sur 11.2.2)  - Client  V3.0.7 , RC Server V3.12.0 and also on Windows client V 3.1.1 with the same backend.

**Comment by adocampo** [comment]
Let's hope the [bugfix](https://github.com/RocketChat/Rocket.Chat/pull/20973) release will be released ASAP, 3.11.0 and 3.12.0 bugs are very annoying and boss is getting mad with RC. IT team have been testing RC for a year and _precisely_ when we put it in production bugs began to spread...

**Comment by miko007** [comment]
can @rodrigok or some other maintainer at least comment on this?

**Comment by tassoevan** [comment]
@miko007 There is not so much to add beyond confirm that @yash-rajpal nailed the bug and the fix will land on 3.12.1. A rocketeer is working on keeping the unnecessary contextual bar closed. At the moment, there is no integration test I'm aware that is capable to catch this kind of error -- specially considering that Jitsi is integrated as a _service_ rather than a 3rd-party _library_ --, but @damian-centrone is leading the efforts to mitigate insidious situations like this one.

**Comment by miko007** [comment]
@tassoevan well, i was shooting for more of an ETA of a possible bug fix release or something.

i really did not imply any unit or integration tests missing, i am aware that this can not be reasonably covered by them, but don't you just "user test" the app before a release? just trying all the major functions, clicking around and stuff?

as the bugfix release is out now, we will thoroughly test it.
