### ISSUE TITLE
Closing menu by clicking the 3 dot meu doesn't occur 

### ISSUE THREAD

**Issue by sk044** [RocketChat/Rocket.Chat#20968]
### Description:

Closing menu by clicking the 3 dot meu doesn't occur 

### Steps to reproduce:

1. Go to a particular channel
2. Click on the 3 dot menu on the top right corner 

### Expected behavior:

After expanding menu , by clicking the three dot menu should close 

### Actual behavior:

The above doesn't happen and closes after clicking anywhere else .

![Screenshot (216)_LI](https://user-images.githubusercontent.com/54908788/109752845-26a69a00-7c07-11eb-9435-2ed86b9c4fbd.jpg)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0-develop
- Operating System: Ubuntu
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version:  12.18.1
- MongoDB Version: 4.2.8

### Client Setup Information

- Desktop App or Browser Version:Chrome
- Operating System:Ubuntu

### Relevant logs:

**Comment by sk044** [comment]
I am working on it .

**Comment by aditya-mitra** [comment]
@sk044 This could be nice improvement!

I think you should raise this issue in [Rocket.Chat.Fuselage](https://github.com/RocketChat/Rocket.Chat.Fuselage) because the component that is being used is a `<Menu/>`. See [/client/views/room/Header/ToolBox/ToolBox.tsx#L82](https://github.com/RocketChat/Rocket.Chat/blob/develop/client/views/room/Header/ToolBox/ToolBox.tsx#L82).

You can also see the [Menu Component (that is being used) here](https://rocketchat.github.io/Rocket.Chat.Fuselage/fuselage/master/?path=/story/misc-menu--default-story)

Happy Solving! :100:

**Comment by sk044** [comment]
Thanks a lot . I'll do the above  surely . :)

**Comment by dougfabris** [comment]
Closing this one, as @aditya-mitra said it is a fuselage issue already fixed [here](https://github.com/RocketChat/Rocket.Chat.Fuselage/pull/389)
