### ISSUE TITLE
Getting full blue screen in browser

### ISSUE THREAD

**Issue by PeaceGeeks** [RocketChat/Rocket.Chat#2100]
perhaps because losing connectivity with server? 

why is this happening? what can the user do to resolve? 

I have tried this in multiple browsers

**Comment by improvethings** [comment]
Is there a way to turn on debug logging?

**Comment by improvethings** [comment]
I have a client getting this in their browser right now (blue screen only instead of login screen, they are using Chrome). I'm also getting it in Firefox currently, but am logged in successfully in Chrome.

**Comment by improvethings** [comment]
Killing it and restarting it fixes the problem. I would love advice on how to debug this reoccurring issue.

**Comment by defib** [comment]
+1

Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.1.25&pv=6.0.1&source=email_footer_2] On Wed, Feb 24, 2016 at 12:51 PM, improvethings < notifications@github.com [notifications@github.com] > wrote:
Killing it and restarting it fixes the problem. I would love advice on how to
debug this reoccurring issue.

—
Reply to this email directly or view it on GitHub
[https://github.com/RocketChat/Rocket.Chat/issues/2100#issuecomment-188379343] .[https://github.com/notifications/beacon/AAvmVPXJ0eJ5le028Yon6aNmrjuBnpX-ks5pneU7gaJpZM4HRHzO.gif]

**Comment by Valiantiam** [comment]
I'm also getting this with a new install. It working great, and then all of a sudden, it stopped. Anyone who isn't already logged in, gets a big blank screen that uses the primary background color. 

I dont see any logs in my chrome debugger tool. It's like it just doesn't load any additional elements beyond the tooltip.

**Comment by Shaquille-Kings** [comment]
I'm also having the same problem here.

**Comment by tassoevan** [comment]
Is this still happening in the latest version?

**Comment by mklenk** [comment]
Yes I'm getting the same problem. It was running fine for two days and now anyone who isn't already logged in just sees a blank screen instead of the login form. There's no error output in neither the browser console or the RC debug log.

Setting "Allow Anonymous Read" to true allows me to see and read the public channels. But I get the same blank screen when trying to login.
I've also tried to disable the ldap login but with the same, blank result.

This is also a completely fresh docker install (v66.3) so there were no database updates or anything like that.
