### ISSUE TITLE
[Bugbounty: $400] Possible regression of #21004 / Call already ended

### ISSUE THREAD

**Issue by fdellwing** [RocketChat/Rocket.Chat#21055]
$400 bounty for solving this issue: https://www.bountysource.com/issues/97216131-possible-regression-of-21004-call-already-ended

---

### Description:

After updating from 3.12.0 to 3.12.1 we get "call already ended" a few seconds after someone started a call. This might be a regression of #21004.

### Steps to reproduce:

1. Start a new call in a new windows
2. Wait 10sec
3. Click on "click to join" with another user

### Expected behavior:

The running call should open.

### Actual behavior:

"Call already ended"

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.1
- Operating System: Ubuntu 18.04
- Deployment Method: docker-compose
- Number of Running Instances: 3
- DB Replicaset Oplog: enabled
- NodeJS Version: 12.18.4
- MongoDB Version: 3.6.9

### Client Setup Information

- Desktop App or Browser Version: Linux App/Chrome
- Operating System: Kubuntu/Win10

### Additional context

We use a self hosted Jitsi instance with Ubuntu 18.04 and Jitsi Meet 2.0.5390-3.

### Relevant logs:

None

**Comment by dvydruk** [comment]
Same with snap version.

**Comment by klepptor** [comment]
Same here with docker RC and native Jitsi Meet.

**Comment by bognerf** [comment]
Same here, after updating from 3.11.x to 3.12.1 running on Ubuntu 18.04 we experience identical issues as thread starter does.

**Comment by yash-rajpal** [comment]
@fdellwing and all others suffering from this, I am very sorry that closing tab bar after initiating a call is having such serious problems, and I am looking into it. I tested this but didn't tested for this issue or thought this could be a possible regression of #21004 
That said, in earlier versions the tab bar used to automatically close after connecting the call and this issue wasn't there. Also I think there is a much bigger underlying issue, the mentioned pr just closes tab bar automatically, but what if user decides to close tab manually, after initiating call, it would still have the same effect. I will try to fix this asap. :)

**Comment by fdellwing** [comment]
Yeah, initially the issue is surely to be found in the react rewrite of the component. But closing the sidebar has an impact on it, so I mentioned it here. Thanks @yash-rajpal.

**Comment by HiveMindNet** [comment]
Anyone know of a temp fix we could implement while we wait for a proper fix in a pull please?

**Comment by fdellwing** [comment]
Just click on the call symbol again. It's a bit of spam in a large group, but works perfectly fine.

**Comment by HiveMindNet** [comment]
> Just click on the call symbol again. It's a bit of spam in a large group, but works perfectly fine.

Thanks - That's what we've been doing. Actually, if it helps anyone else, we created this which we need to keep posting.

![Trouble Joining Video Call - READ THIS](https://user-images.githubusercontent.com/19346725/111455385-a2c3d600-870d-11eb-9ea8-7a717c3761a7.png)

I was more hoping for some code to tweak though in the meantime, so that we can quick-fix before the real fix is in a pull.

Thanks :)

**Comment by dvydruk** [comment]
If RC uses the same URL every time we press "call" button than I miss the purpose of all this "call already ended".
Shouldn't it generate different room URL every time?
Now if some one manage to get a URL he can join all the meetings...

**Comment by fdellwing** [comment]
Congratulations, you understood how Jitsi works. If you have the link you can join. That is the reason you setup authentication.

**Comment by dvydruk** [comment]
I know how Jitsi works. I thought that RC generates different URL over time. But now it is the same url for RC channel for days.

**Comment by arpsyapathy** [comment]
Hi all!

I have the same problems after upgrade!

**Comment by ankar84** [comment]
It could be related to **jitsi:updateTimeout** method that exist in that **Call contextual bar** and now it's not executed because **Call contextual bar** is closed right after call is started.
Bat anyway that fix massive **Click to Join!** buttons creation issue described here https://github.com/RocketChat/Rocket.Chat.Electron/issues/1847#issuecomment-813365558

**Comment by emikolajczak** [comment]
Issue still exists in 3.13.0.

**Comment by emikolajczak** [comment]
Hi, there is any chance that this Jitsi bug will be fixed in 3.13.1? 
Broken Jitsi blocks upgrade to latest versions. Working Jitsi is crucial for users.

**Comment by emikolajczak** [comment]
Hi, same issue in 3.13.1
@yash-rajpal could you tried to fix this bug?
It looks like Jitsi integration is abandoned. Sad, it is very important and key functionality for most of users.

**Comment by fdellwing** [comment]
@emikolajczak You are aware of the fact, that Jitsi work fine in 3.12.x and 3.13.x?

Yes the "call already ended" is annoying, but not a big problem. So it is absolutly logical, that it has not that high of a prio.

**Comment by emikolajczak** [comment]
In my opinion it not fine. It will be very hard to explain my users that in previous version they had almost good solution, and now they have to start call again when need to join.

**Comment by fdellwing** [comment]
It's ok if that is your opinion, you have three possibilities:

1. Fix it yourself
2. Pay someone to fix it for you
3. Wait until someone fixes it

But please stop posting here after every update that it still does not work. If it is fixed, this issue will be closed (and the bugfix will be present in the changelogs). If this issue is not closed, it is not fixed. No need to spam (currently) 8 persons with an absolut useless information.

**Comment by pawcykca** [comment]
@fdellwing 
> "Yes the "call already ended" is annoying, but not a big problem. So it is absolutly logical, that it has not that high of a prio."

This is only your opinion, because you probably don't use JITSI integration on a daily basis. If someone is actively reporting a problem on a thread, rather mean that it is a big problem for him.
Discouraging someone from reporting bugs is not a professional approach, so it's worth considering.

**Comment by fdellwing** [comment]
> This is only your opinion, because you probably don't use JITSI integration on a daily basis.

We use Jitsi in our company very activly and it is not a big problem. It was literally **one** message describing the problem and how to work around it.

> Discouraging someone from reporting bugs is not a professional approach, so it's worth considering.

The bug already got reported, otherwise this issue would not exist. Writing 3 posts in less than 2 days without adding any meaningfull information to the topic is "not a professional approach".

**Comment by sandrotanner** [comment]
@yash-rajpal Were you able to find the time to work on this issue? Or do you have any ideas that might help someone else to work on it?

**Comment by HiveMindNet** [comment]
Does anyone know if this workaround works? I tried but it didn't for me but I couldn't restart the server as people were using it.

https://github.com/RocketChat/Rocket.Chat/issues/11649#issuecomment-618026563

If it does after a restart, I'll apply it after hours.

Thinking that this "it is not a big problem" is a UX joke. We don't mind paying for fixes if there's a way to do it that doesn't involve buying an enterpriser license. This has surely gone on for too long.

Is there no way to pay for expedited fixes that benefit everyone anyway??

**Comment by fdellwing** [comment]
You can always post a bounty here: https://www.bountysource.com/

Sadly the RC developers itself do not care much about Jitsi.

**Comment by HiveMindNet** [comment]
$400 Bounty posted.

https://www.bountysource.com/issues/97216131-possible-regression-of-21004-call-already-ended

**Comment by HiveMindNet** [comment]
Apparently I need to be a 'public member of the GitHub organization to enable the plugin' I need to highlight that I've posted a bounty on this issue. Anyone know how I do that? 🤣🤣🤣

**Comment by fdellwing** [comment]
I can only edit it into the issue itself, but that should make it at least a bit more visible.

**Comment by yash-rajpal** [comment]
@fdellwing @HiveMindNet I have implemented the basic solution. Please have a look at it and test it, also please let me know about this. :)

Please reach out to me at [open rocket chat](https://open.rocket.chat/direct/yash.rajpal) and we can discuss and review solution.

Thanks :)

**Comment by HiveMindNet** [comment]
Hi @yash-rajpal - I'm running a docker based instance. Until that's pushed I guess I can test by just replacing the files you worked on? I've dropped you a note as you suggest on open rocket chat and maybe you can point me at files I need to replace?

Happy that everyone using Jitsi benefits from this :)

Thanks

**Comment by HiveMindNet** [comment]
@fdellwing - @yash-rajpal has fixed the issue as far as I'm concerned so it's fair we should give him the bounty - however as I added the bounty on an issue you created, you need to please close the issue. He has also already posted his solution. As it's your issue, I can't close it and release the payment to him. I will also email the guys at bounty source an ask them to release the payment.

If you wouldn't mind - I'd also like to cc you on the email I'm sending the about guys so that you can confirm to them. If you're ok with that, please share your email with me here https://open.rocket.chat/direct/HiveMindNet

Thanks very much @yash-rajpal

**Comment by fdellwing** [comment]
Sure I'll close the issue. Thank you @yash-rajpal for solving the issue. Lets hope it gets merged into RC soon.

**Comment by yash-rajpal** [comment]
@HiveMindNet @fdellwing Thank You very much. :) 

@HiveMindNet is already running the fix on his self hosted Rocket Chat server and it works for him. 

If anyone wants the fix for this urgently for their server, you can reach out to me at - https://open.rocket.chat/direct/yash.rajpal - and I can help you with the fix ( by providing a docker image for the fix or some other workaround ).

Hoping the PR gets reviewed soon. :)

**Comment by pjsft** [comment]
@yash-rajpal @sampaiodiego Do you have any amendment deadline? The problem occurs for nearly 3 months. :/

**Comment by ankar84** [comment]
> @yash-rajpal @sampaiodiego Do you have any amendment deadline? The problem occurs for nearly 3 months. :/

#21808 merged today and will be available in 3.15
