### ISSUE TITLE
Unread threads not displayed on top.

### ISSUE THREAD

**Issue by Darshilp326** [RocketChat/Rocket.Chat#21088]
### Description:
In a channel with many users, we need to scroll to find all our unread threads.

### Steps to reproduce:

1.  Make a thread
2. Reply on a previous thread from a new account.
3. Make a new thread 

### Expected behavior:
Unread threads should be displayed on top

### Actual behavior:
Unread threads are not displayed on top.

https://user-images.githubusercontent.com/55157259/110916013-5871dc00-833e-11eb-8102-d8d9e5a4b72a.mp4

### Server Setup Information:

- Version of Rocket.Chat Server:3.13.0-develop 
- Operating System: Ubuntu
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4
- MongoDB Version:4.2.8

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: Ubuntu

### Additional context
Working

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

It's not the expected behavior but you can see your unread threads by the room contextual menu

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
