### ISSUE TITLE
Unread Notification do not dissapear

### ISSUE THREAD

**Issue by christianreiss** [RocketChat/Rocket.Chat#21154]
### Description:

The unread counter in the left menu bar is not disappearing. Hitting "Mark all read" or "escaping" does not help, nor does updating the server. We also tried to logout & login. We are unsure on how this came to be. We assume this was due to one person replying in a thread and then deleting the message without the other participants having a chance to read it.

### Steps to reproduce:

(assumed)
1. Open a thread with at least two people.
2. Have person a reply in it, then without giving Person b a chance, delete the message.
3. Person b has the unread counter that does not go away.

### Expected behavior:

If you mark "all read", then it's all read.

### Actual behavior:

I think we all know whats actually happening :)
We get a (1) new message in the left menu bar,
We get a (1) new message in the thread button in the top right,
We have zero actually unread messages.

Here is a screenshot: https://misc.alpha-labs.net/unread.png

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.1
- Operating System: CentOS 8 (sigh)
- Deployment Method: tar
- Number of Running Instances: 4
- DB Replicaset Oplog: yes
- NodeJS Version: v12.18.4
- MongoDB Version: 4.0.23 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: multiple
- Operating System: multiple

### Additional context

- none

### Relevant logs:

- none

**Comment by ankar84** [comment]
> We assume this was due to one person replying in a thread and then deleting the message without the other participants having a chance to read it.

I think one of my users have same extraordinary situation. I didn't get to reproduce that, but looks like it was deletion of thread simultaneously with other users answer in it.

**Comment by kosmas-formulatrix** [comment]
Also happen to me. The problem is happening especially when the admin prune message. There is no way to see the removed message after that and leave the unread notification. Also, mark as read didn't clear the number (if the mark as cleared can clear this, it should be enough ).

![image](https://user-images.githubusercontent.com/5257848/111726509-b13ff800-889b-11eb-8ebe-5531e672cb32.png)

**Comment by caesarcxiv** [comment]
Same issue after prune - channels have unread counters that cannot be reset.

**Comment by renancleyson-dev** [comment]
I reproduced it with different steps. Instead of sending a message on a thread and then delete it, I deleted the whole thread with prune. 

### New steps to reproduce
- Open a thread with at least two persons
- Person A sends a message
- Admin prune messages of Person A and B
- Person B with permanent unread counter

**Comment by caesarcxiv** [comment]
I see the fix but it doesn't solve all of the unread counters that are permanently incorrect on the instance. Is there a rails query or something that can be run?

**Comment by paulopera** [comment]
> Also happen to me. The problem is happening especially when the admin prune message. There is no way to see the removed message after that and leave the unread notification. Also, mark as read didn't clear the number (if the mark as cleared can clear this, it should be enough ).
> 
> ![image](https://user-images.githubusercontent.com/5257848/111726509-b13ff800-889b-11eb-8ebe-5531e672cb32.png)

I saw the same happening here, If I prune the messages and there was an unread thread the badge icon will keep the unread counter. I updated the server today and the problem still persists but I found a workaround.
Go to the Admin > Rooms > search the conversation and then delete it. It worked for me because I pruned all the messages, but if you did only to some it will delete all the messages. So do it cautiously.

**Comment by mddvul22** [comment]
We are running version 3.15.2.  This issue is not resolved for us.

**Comment by mddvul22** [comment]
![image](https://user-images.githubusercontent.com/6833993/124658660-a7053200-de69-11eb-9922-7d316036b99c.png)
