### ISSUE TITLE
WebRTC over two lan segments 

### ISSUE THREAD

**Issue by tdhz77** [RocketChat/Rocket.Chat#2136]
We have two locations. Each location has its own DHCP server. We share data a lot between our offices. 

We have the following ranges: 
192.168.60.1..X
192.168.5.1..X

All users on the 60/5 range can use webrtc if they are on the same range (60 with 60, 5 with 5), however we cannot communicate between or across 60 & 5 or between the two. Is this on purpose or is this a bug?

**Comment by engelgabriel** [comment]
Not on purpose.. the free STUN server we use is probably getting confused or your own network was restrictions on the traffic between subnets.

**Comment by Sing-Li** [comment]
New solution testing now on:

https://demo.rocket.chat

New solution testing this week.

On https://demo.rocket.chat

When you are in a Direct Message or Private Group. You will notice a new video button on the toolbar , just click it anytime to start a video conference with all those in the room

**Comment by geekgonecrazy** [comment]
A lot has changed in Rocket.Chat since the opening of this issue.  Please give our jitsi integration a try as suggested.

If you have any further questions please join our community server in the [#support](https://demo.rocket.chat/channel/support) channel or ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat)
