### ISSUE TITLE
unable to connect to valid url in version > 2.17.7

### ISSUE THREAD

**Issue by Ghanimaid** [RocketChat/Rocket.Chat#21460]
Tried to connect to our running server , always get invalid url

**Comment by fdellwing** [comment]
Sound like a client issue, please take a look here: https://github.com/RocketChat/Rocket.Chat.Electron/issues/1743

**Comment by reetp** [comment]
Hi,

Can you please help the developers by filling out a proper bug report? They can't really help without this information.

Use this link: https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md 

Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues
 
If a browser works and your issue is with the Electron client only use this repo:

https://github.com/RocketChat/Rocket.Chat.Electron

Thanks.

**Comment by johncrisp** [comment]
No further information.

Please ask in https://open.rocket.chat #support if you need more assistance.

Thanks.
