### ISSUE TITLE
Memberlist shows max 25 entries

### ISSUE THREAD

**Issue by chaperonRose** [RocketChat/Rocket.Chat#21505]
### Description:

In a channel with many members, memberlist shows at the very most 25 members.

### Steps to reproduce:

1. Go to a channel with more than 25 members.
2. Open memberlist.
3. Force scrollbar to show itself by switching connected/all menu (bypassing other bug, cf. https://github.com/RocketChat/Rocket.Chat/issues/21282).
4. Select (if not already set) to show all members.
5. Results : Text says "Showing: 25 Total [yournumber]" and list shows only 25 persons, even if scrolling down.

### Expected behavior:
See all members when scrolling and have correct counting in text.

### Actual behavior:

See "Steps to reproduce".

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13.1
- Operating System: Linux

### Client Setup Information

- Desktop App or Browser Version: Firefox ESR and Chromium

**Comment by Jeanstaquet** [comment]
I think that i found something

**Comment by Jeanstaquet** [comment]
I solved the same problem for threads because it was easier to prove, I take care of proving the fix with users.

**Comment by cprice-kgi** [comment]
I can still get this to happen if the browser window is tall enough to show all 25 entries at once. To reproduce, make browser height enough so that at 25 or more member names can fit in the right hand menu. Go to a channel with more than 25 members. On initial load, it works fine and the scrollbar appears as expected. Toggle the online/all filter to online. The list updates to show online users only. Now, click back to "All" and 25 member names appear, but no scroll bar.
