### ISSUE TITLE
Threads - "Also send to channel" not wrok

### ISSUE THREAD

**Issue by emikolajczak** [RocketChat/Rocket.Chat#21529]
### Description:

"Also send to channel" check/uncheck work not correctly. In account preference i have set  `Show thread messages in the main thread` true. Regardless if "Also send to channel" is set or unset, messages from thread are presented in main channel.

### Steps to reproduce:

1. Set `Show thread messages in the main thread` true in user preferences
2. Go to thread and uncheck "Also send to channel"
3. Send a message in thread
4. Message is presented also in main channel

### Expected behavior:

When "Also send to channel" is unchecked messages from thread not send to main channel

### Actual behavior:

Message is presented also in main channel

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.7 / 3.13.1
- Operating System: Centos 8
- Deployment Method: docker-compose
- Number of Running Instances: 33
- DB Replicaset Oplog: YES
- NodeJS Version: v12.21.0
- MongoDB Version: 4.0.13

### Client Setup Information

- Desktop App or Browser Version: booth
- Operating System: Windows 10

### Additional context

![image](https://user-images.githubusercontent.com/50440047/114355198-79149800-9b6f-11eb-982d-4aaf899a925c.png)

**Comment by ankar84** [comment]
> "Also send to channel" check/uncheck work not correctly. In account preference i have set `Show thread messages in the main thread` true. Regardless if "Also send to channel" is set or unset, messages from thread are presented in main channel.

I think it is **by design workflow for that option** `Show thread messages in the main thread`
But you right that if that `Show thread messages in the main thread` option **is enabled**, then behavior of **Also send to channel** checkbox should be different - for example **always enabled and gayed-out** showing that it can't be unchecked.

**Comment by ksrx** [comment]
Is there a way to hide the option "Also send to channel"? I'd like to keep the threads messages only on threads.

**Comment by ggazzo** [comment]
there is no bug or problem, it works exactly as we planned. The setting is about how YOU want to see it (including all messages on the main thread), the checkbox is if you want to be sure that others will see the message on the main thread (they may not have enabled the setting in their profile).

We did this because in the past all messages were displayed on the main thread. However, it was very messy. When we removed it, believe me, some people missed it. but believe me they are two totally different things.
