### ISSUE TITLE
Up arrow should only take you to edit the most recent message in your history.

### ISSUE THREAD

**Issue by bgupta** [RocketChat/Rocket.Chat#2153]
Allowing up and down arrow to move through history indiscriminately, allows one to discard partial edits without any warning. (I've been hit by this so many times as it breaks my expectations, as I am used to the way Skype and Slack handle it, in that up arrow just takes you to your last message, and if you want to go further back you need to select it and click the edit icon.)

**Comment by mitar** [comment]
+1

**Comment by mitar** [comment]
Especially once you already start editing a message and you want to go to the beginning of a message and press up it goes to edit a message before.

**Comment by mccambridge** [comment]
I liked the convenience at first, but then I see the issue: accidentally nuking your edits. Since you can still edit messages via the gear icon, I'm reluctantly a +1 on this.

**Comment by adamonline45** [comment]
+1 here as well...  I have the annoying habit of moving my cursor down each line as I proofread my edit, meaning I nuke my edits pretty reliably... Sometimes more than once on the same editing attempt!

I would love to see some compromise, though, as I do like the scrolling through all past messages. Maybe once you edit a message, or hit left/right/home/end, it doesn't change the current message anymore; but that's still a bit problematic...

**Comment by martinvonwittich** [comment]
I for one absolutely hate the current behavior where up arrow will scroll into sent messages. I often type long messages with multiple line breaks (for example when pasting code) and when I want to scroll to the first line, I'm used to just pressing and holding the up arrow which now causes me to unintentionally end up in some sent message. (I only found out today about Ctrl+Home works).

I'd prefer the behavior that most other clients like Pidgin and Skype have, where Up/Down Arrow only move the cursor in the current message, and Ctrl+Up/Down Arrrow allows to edit sent messages.

**Comment by SeanPackham** [comment]
This is the intended behaviour of editing messages.

**Comment by flaviovs** [comment]
Is it possible to disable this feature?

Current UX is not good, as the UI clues that one is editing an already sent message is too subtle, and the mode switch from "post a new message" to "edit an old message" happens without any feedback.

This cause problems when users copy and paste a message to tweak and resend, accidentally press <kbd>↑</kbd>, select the message with the same content, edit, and post, just to find out that they actually edited an old message -- which means nobody gets notified of the "new" message and, worst, original message text is lost forever.

It is happening here all the time. :-(

I understand that this is the intended behaviour, but the discussion here is about changing it, mostly because it is an odd behaviour, different from all other similar chat clients users are accustomed to use, and most importantly it is allowing users to very easily change chat history forever by accident.

To be honest, being a keyboard addict I like the idea of editing previous message using just the keyboard. However, binding the same key to two different purposes ("previous line" and "select previous message") was not a very good choice, IMHO. Perhaps changing to, say, <kbd>Control</kbd>+<kbd>↑</kbd> is the way to go?

**Comment by flaviovs** [comment]
Current behaviour, as explained above, use the same keystroke for two different purposes. It is pretty much like having gas and brake on the same pedal in your car. :-)

@SeanPackham any chance to consider this change?

**Comment by sarrala** [comment]
@marceloschmidt would it be possible to consider reopening this issue and maybe even taking a second look at it. Maybe this could be resolved through separate configuration option?

Even if this actually is "_the intended behaviour of editing messages_" maybe you could still make it optional so that editing older messages could only be done through context menu.

Personally I would also like to be able to "clone" last message somehow using arrow keys instead of editing it but that's probably too off topic here.

**Comment by adamonline45** [comment]
Intended behavior is to delete a multi-line edit when you want to cursor to
a higher line of that message?

Guess I can't argue with the product owner, but when I used this software
that was downright aggravating and certainly not a standard behavior for
any other messaging app...

**Comment by engelgabriel** [comment]
https://github.com/RocketChat/Rocket.Chat/issues/14621

**Comment by engelgabriel** [comment]
We have updated the behavior so that the arrow up key first navigate to the beginning of the fields first, and only after pressed again it will switch to edit the previews message. We've also saved the text of the input field while you navigate, so you will not lose your message if you switch by mistake, as you just need to move back.

**Comment by LizhangX** [comment]
It is annoying that scrolling through history is gone. It kinda became my muscle memory. Please bring it back... At least give us the option to turn it on. Not just remove it completely. Thanks a lot.

**Comment by Anguel** [comment]
I find the current behavior still very annoying. There must be a way to completely turn off this strange "feature". I have never seen a thing that is so confusing.
