### ISSUE TITLE
New user permission/role for *approval* of messages

### ISSUE THREAD

**Issue by RichardFoxworthy** [RocketChat/Rocket.Chat#2161]
A new permission/role that forces all messages sent to a moderated room to first go to the moderator(s) for approval.

Moderators can:
- approve - the message gets published to room as normal. 
- reject - the message originator gets notified and the message does not get published
- edit - the edited version is published to the moderated room

This is necessary for public forums hosted by brands/companies who need to make sure that no offensive material gets posted to their forum.

It is not enough that moderators already can delete an offensive message. This new model can prevent the offensive message being visible to other users at all.

**Comment by rychken** [comment]
I picked this up as a feature for me to learn the platform on. Lots more to adjust than I initially thought since usually a user is allowed to see any message in a given room, and not at the message level.

I have a working, 80-90% feature-complete branch.

In case my responsibilities lead me elsewhere and I am no longer able to work on it, I will link what I have so far.

For now, I plan to continue working on it.

https://github.com/rychken/Rocket.Chat/tree/2161-message-approval

![messageapproval](https://cloud.githubusercontent.com/assets/22598174/19200026/7bb530a2-8c8c-11e6-904d-162558231906.jpg)

**Comment by sampaiodiego** [comment]
Although this is a nice feature to have we don't have plans to do this.

Please feel free to open a detail feature request on our [forums](https://forums.rocket.chat) where we can review and decide if we plan to implement. Feel free to also link to this ticket for historic. The better layed out we can get the request the easier it is for us to make definitive decision on whether we plan to implement or not.

**Comment by wajeeh-devsinc** [comment]
Is this feature implemented or not yet..?

**Comment by sampaiodiego** [comment]
@wajeeh-devsinc no, it was not implemented.. we do consider accepting a PR though
