### ISSUE TITLE
Make emoji suggestions optional

### ISSUE THREAD

**Issue by ostapski** [RocketChat/Rocket.Chat#21693]
### Description:

Follow up to the ticket #16616 posted by @standev

I'm too not happy being forced to see images that are against my religion.

To remedy the problem - one can open the **bladibla.js** file (where bladibla is a long **hash name**)
it is located in 2 places: (do change in both ...legacy browsers are not out yet)

**/opt/Rocket.Chat/programs/web.browser/
/opt/Rocket.Chat/programs/web.browser.legacy/**

something like this:

![202104214QFUzwW9](https://user-images.githubusercontent.com/2835357/115478865-59ecc900-a247-11eb-812d-9c9eb81aa614.png)

locate this text **popupEmojiConfig: function() {**
and replace it with **popupEmojiConfig: function() {return {};**

This will effectively remove any gay suggestions while you type.
Problem solved - and nobody is insulted by being showed into the throat the new "today"
(If RocketChat has problems with different people views - than it should take it somewhere else - 
GitHub is for programmers - kapish ?)

Although of coz - this wont work in the windows app ... - i've not digged that far yet...
Would appreciate any tips

### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by robbyoconnor** [comment]
What the hell?

**Comment by robbyoconnor** [comment]
What?

**Comment by robbyoconnor** [comment]
@MartinSchoeler may want to close this one too.

**Comment by ostapski** [comment]
take  your mask off ....

**Comment by ostapski** [comment]
@MartinSchoeler  - Who ever you you are - i guess a team leader
plz read it before closing ....

There are people who YOU and everyone should respect as those you try to promote 
Do not make it a political statement - be a programmer and let it go !! 
Acknowledge both sides !!!

**Comment by robbyoconnor** [comment]
👬🏻

**Comment by robbyoconnor** [comment]
@johncrisp @Sing-Li May want to close this -- just another troll. 

Take it up with the Unicode Consortium.

**Comment by ostapski** [comment]
@robbyoconnor  dude ...are you pissed ?

**Comment by ostapski** [comment]
@johncrisp , @Sing-Li 
Hi ... no idea who you are - but i'm asking you to review this and previous ticket !!
before you close it 

Not trolling or anything - i'm asking same question - to remove or at least make optional unwanted mems

**Comment by robbyoconnor** [comment]
@ostapski 👬🏻

**Comment by ostapski** [comment]
lets keep it generic ?

**How to remove unwanted emojis**

**Comment by ostapski** [comment]
Or ...even better - keep the emojis ...
allow to turn ON/OFF suggestions - that as you can see above isnt that difficult ....just tie it up to new parameter in admin config

**Comment by ostapski** [comment]
there we go

**Comment by standev** [comment]
Glad I'm not the only one annoyed by this. 👍 Thanks for the helpful suggestions, man.

**Comment by johncrisp** [comment]
Hi,

I'm the Community Manager for Rocket.Chat and also work on Issue triage here.

This is clearly a divisive issue and we really need to think carefully about the language that we use so no one is offended.

Rocket.Chat does have a code of conduct which we would be grateful if everyone read and followed.

https://docs.rocket.chat/contributors/code_of_conduct

If it isn't the issue will just get closed, and your voices will not be heard.

Moving forward, as you are aware this is Open Source. No one actually 'owns' it. If you don't like what you see you are welcome to take the code and modify as you see fit. We even have documentation on how to build your own version.

https://developer.rocket.chat/guides/developer

That could get you around your immediate issues. You could even add your own emoji sets.

And we are more than happy to accept your PRs and patches if you want to try and help make this a more feature rich experience.

As far as Rocket.Chat providing potential solutions this is really a 'feature-request' rather than a bug - the code isn't actually 'broken' and there are no errors - it just doesn't work the way you want it too.

Distilling this down there are a couple of suggestions that could be looked at here:

- Turn on/off Emoji suggestions as you type
- Turn on/off Emojis altogether
- Allow alternative Emoji sets

I am not sure what effect this would have on the mobile app or the electron client. That would need investigation.

I will leave this Issue open for the time being and the developers will take a look.

If you have additional ideas or suggestions that fit with our CoC then please follow up. Kindly note that you do not need to @ anyone - the people who need to know see all the Issues.

If you want to talk to me me directly you can find me on https://open.rocket.chat

Thanks.

**Comment by TimLewis-byte** [comment]
Hi @Ostapski,

I specifically created my Github account today in order to thank you from the bottom of my heart,
I am a member of a Christian group and we originally intended to use Rocketchat for our online discourse.
After some testing we decided against it because we where unable to remove same sex emojis as primary suggestions which many of us found extremely off putting. It would not have been a big deal if they would not have been top of the list, but whenever someone typed fast, the suggestion script could not keep up and yet another kissing gay couple would appear (why should they be the first suggestion instead of common ones, like a smiley, wink etc), and this simply goes against what we believe to be the will of God.

The alternatives where all lacking functionality and so I am extremely happy and thankful to see that someone took up the matter and shared with us a method that allows us to set it up the way we feel comfortable with. 

I definitely think this should become an official feature. Emoji suggestions as they are right now not only force views on us that might be perceived as offensive, but it also slows down the chat. I would very much like to be able to just turn off suggestions all together.

@robbyoconnor. I am offended by you calling ostapski a troll. He clearly is not, and his contribution is much appreciated. yet you definitely are, at least in this thread, while even requesting for cancelation of his contribution. Despicable. Have some respect for others. Not everyone shares the same views, and neither should we.

**Comment by robbyoconnor** [comment]
I am offended by your warped version of Christianity to justify your bigotry.

**Comment by robbyoconnor** [comment]
@TimLewis-byte I am offended by your warped version of Christianity to justify your bigotry. 

I doubt you follow everything in the Bible because your bigotry runs counter to some of its teachings.

**Comment by robbyoconnor** [comment]
@TimLewis-byte have some respect for people living their lives as God intended. Despicable behavior from a so-called "Christian"
