### ISSUE TITLE
Sorting on status not working on channels.members api 

### ISSUE THREAD

**Issue by simmyK1788** [RocketChat/Rocket.Chat#21805]
As per the documentation https://developer.rocket.chat/api/rest-api/methods/channels/members should support sort parameters but when sorted on status it doesnt work.

Using Latest docker release

Request URl:-
/api/v1/channels.members?roomId=r6EtRHWe5hmM2hdqj&sort={"status":-1}

**Comment by johncrisp** [comment]
Hi,

Note that Github is for bugs in the code rather than support and you are much better to ask your question in open.rocket.chat or forums.rocket.chat first rather than here. If we find a bug we can then open an issue.

You really need to fill out a proper bug template from here making sure you complete ALL the information. Logs are particularly useful in debugging:

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

Thanks

**Comment by KevLehman** [comment]
Hey! Thanks for bringing up this issue. This was a de-sync between the docs and the code. The endpoint in question supports currently sorting by `username` only, as you can see in `app/api/server/v1/channels.js L583 & L594`. I'll update the docs with this change :)

**Comment by KevLehman** [comment]
@johncrisp @simmyK1788 documentation was updated: https://developer.rocket.chat/api/rest-api/methods/channels/members

**Comment by johncrisp** [comment]
Many thanks @KevLehman 

And closing.
