### ISSUE TITLE
Ability to invite new users with /invite friend@email.com

### ISSUE THREAD

**Issue by rchikballapur** [RocketChat/Rocket.Chat#2181]
Allow any user (Permission to be managed) to invite non-users to a specific channel or private group with /invite friend@email.com command. Or something similar.

**Comment by javaning** [comment]
+1, multiple invited is better.

**Comment by hvma** [comment]
+1

**Comment by Iksn** [comment]
+1

**Comment by simonpie** [comment]
+1

**Comment by ehginanjar** [comment]
+1

**Comment by dyoungdevfactory** [comment]
I know this thread is over a year old, but, just to clarify: Rocket.Chat still does not support users inviting other users to join a team or a specific channel OOTB?

**Comment by konovalcev** [comment]
+1.
Hello team. Is there any update?

**Comment by felipeolcav** [comment]
bump... this would be nice

**Comment by alenkovich** [comment]
+1

**Comment by milaniez** [comment]
+1

**Comment by seyedali** [comment]
+1

**Comment by unrealps** [comment]
+1

**Comment by bizzbyster** [comment]
It would also be nice if Rocket.chat could access the local contacts when inviting. Is that a possibility? Seems like an important way to spread Rocket.chat.

**Comment by bizzbyster** [comment]
I think the best implementation is just the "share" action that you find in your web browser. I think it is a system level action. But at least on Android it results in a list of the apps on your phone that you can share to...

![image](https://user-images.githubusercontent.com/4001792/37868874-56276d5e-2f84-11e8-8d42-65d8aefe2682.png)

And then there would be a pre-formatted message that would include a link to download and install Rocket.chat. This seems like a really important feature to increase Rocket.chat adoption.

**Comment by rasos** [comment]
I have put a simple E-Mail invite link in the footer:
```
<a href="mailto:?subject=Say%20hello%20with%20hellochat&amp;body=I%20use%20hellochat,%20join%20this%20great%20messenger.%20Register%20at%20https%3A%2F%2Fhellochat.com%20%0A%0A">
  <button><i class="icon-mail"></i> Invite</button>
</a>
``` 
Next step: include my user name in the link: 'https://hellochat.net/direct/mynickname' so that users are connected with me after signing in.

However, when I click on such a direct link anonymously, I get: 'No user with username "mynickname" was found!' - instead of getting presented a login button. This bug has been already reported #8535 

Similar issue to #1324

**Comment by piotrkochan** [comment]
Are there any plans to develop this?

**Comment by bizzbyster** [comment]
We have implemented this in our Android fork -- https://github.com/WideChat/Rocket.Chat.Android/commit/cb786166fc6ad45199bcbc0cf25fdc65c7cebce9. But it would be great if the functionality (or some variant of it) were upstreamed.

**Comment by FaizanZahid** [comment]
+1 this will be super cool to have and rocket chat will become viral then +1+1+1

**Comment by tripflex** [comment]
+1 .. or even something similar to Discord with the 1-click invite link that auto joins that user to a specific room

Use case example:
I have numerous open source projects, instead of using gitter i would like to use my own self-hosted rocketchat instance, but those users would only need to be apart of a specific channel/room, not all the other channels (so it does not make sense to set them all as  "default" )

**Comment by bizzbyster** [comment]
We are working on a PR for the upstream now. Look for it in the next couple weeks.

**Comment by adubovskoy** [comment]
+1

**Comment by mdehollander** [comment]
> We are working on a PR for the upstream now. Look for it in the next couple weeks.

What is the status of this PR? Do you have a link to it? 

And what is currently the recommended approach to invite new users that are not registered yet?

**Comment by ndroo** [comment]
Man thats been a long week :P We also want this.

**Comment by geekgonecrazy** [comment]
Closing since we now have this and invite links
