### ISSUE TITLE
Participants are not invited to direct voice/video calls

### ISSUE THREAD

**Issue by sharklaseru** [RocketChat/Rocket.Chat#2191]
I've configured a Rocket.chat 0.16.0 server using Ubuntu 14.04 and AWS, having followed [this guide.](https://github.com/RocketChat/Deploy.to.Cloud/tree/master/AWS#7-set-up-docker-containers).

Everything is working wonderfully, with one exception. When I first booted the server I could initiate one direct video/voice call. The receiving user received the invite notification to accept this conversation and we had our voice chat no problem.

However, any subsequent voice calls that were initiated, by any user/IP/configuration on the application, were not successful. The initiating user would start the call and the audio/webcam was turned on as expected, however participants never receive the invite notification. The logs also do not mention any issues unfortunately.

My server is a dual-core with 8Gb and plenty of resources otherwise. I'm running Rocketchat 0.16.0 through Docker and Nginx as used in the installation guide mentioned earlier.

**Comment by popiolek** [comment]
Same thing here on v0.24. Sometimes connection breaks and one of the participants does not receive an invitation. Restart on the computer that does not see a pop-up helps. All the logs are totally empty and I guess that the root of that issue is some resource allocation problem - same thing happens when there is no mic connected to the PC. 

The real problem tho, that would help to take any actions is that there are no logs for calls. Suggestion of things that could help:
* Show user info when he is being called with some error instead of showing nothing at all when there is no mic / other problem occur.
* Log all actions relating call initiation that would help track issues.

**Comment by asthomasdk** [comment]
I would like to add to this that we need to get notifications when audio / viode calls are started - or you are invited to call. 

Inviting someone to a call does not give the caller any feedback that the call is being made - and the person being called may get a popup, but without any notifications. 

This means that it is very easy to miss calls.

**Comment by asthomasdk** [comment]
Are there any plans to implement audio notifications on calls ? 

Currently we have to send PMs to each other so that the user knows he is getting a call.

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
