### ISSUE TITLE
 Error opening room

### ISSUE THREAD

**Issue by ductinhkzz** [RocketChat/Rocket.Chat#21925]
### Description:

I open direct room and click user info. Then I click other rooms except direct room. App will not show
It just works again when I reload

### Steps to reproduce:

1. Go any direct room
2. Click on user info in that room
3. Click on any room except direct room

### Expected behavior:

It can show room 

### Actual behavior:

Not working

https://user-images.githubusercontent.com/54934640/116955362-89c2b480-acbc-11eb-8d8f-0b3d275630a6.mp4

**Comment by johncrisp** [comment]
Please note that if you are using open.rocket.chat this is the latest code being tested and errors may occur. Sometimes this is due to the server being updated and you can experience a loss of connectivity

If you are going to report issue please fill in a template form properly.

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

I am currently using open.rocket and have no issues.

If you experience further problems please in https://open.rocket.chat #support first and we can take a look there.

https://open.rocket.chat/channel/support
