### ISSUE TITLE
Create a Slack app to provide channel sharing between apps.

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#2197]
We should use our integrations and Slack APIs to be able to do what people to with https://sameroom.io/ but directly.

**Comment by bott0r** [comment]
Sounds fantastic :)

**Comment by SeanPackham** [comment]
I like the sound of it but think the audience is limited and the effort great.

**Comment by patcon** [comment]
Oops. Forgot about this. It already exists and is a work in progress ;)

Here's our instance (code is opinionated due to architecture, so much fork):
http://github.com/edgi-govdata-archiving/matterbridge-heroku

And though not complete, there's a feature branch to auto-generate documentation like this:
https://edgi-matterbridge.herokuapp.com/#organizing-canada

**Comment by patcon** [comment]
An alternative in case anyone comes across this thread later:
http://github.com/edgi-govdata-archiving/matterbridge-heroku
