### ISSUE TITLE
Browser version's tablet size is missing the chat panel/menu button. 

### ISSUE THREAD

**Issue by MiskaRantala** [RocketChat/Rocket.Chat#22087]
When stretching the browser version of Rocket.chat to tablet size, the side menu disappears and doesn't bring the burger-button in, preventing the change of chats. 

Issue found on Chromium-based browsers, Google Chrome and Brave (image from Brave). Chats and URL is hidden from the image. 

<img width="759" alt="Screenshot 2021-05-20 at 12 25 09" src="https://user-images.githubusercontent.com/31501140/118955375-509a6d80-b967-11eb-9978-5c706c09848e.png">

**Comment by johncrisp** [comment]
Hi and thanks for reporting this.

Can you please use a template when reporting bugs as we can't help you without that information.

Also make sure you read the 'reporting issues' link there and always test on the latest version - lots of things change between versions and this may have already been fixed. 

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

**Comment by jimmy09140456** [comment]
I have the same issue and the following is the issue report:

---

### Description:

The conversations list button (Hamburger button) on the top left corner will be disappeared on the mobile UI, in the direct message only, so far as I have seen.

### Steps to reproduce:

1. Go to RocketChat mobile UI
2. Open direct message to somebody
3. Trying to go back to the conversations list
4. And the Hamburger button on the top left corner is missing

### Expected behavior:

Click on the Hamburger button on the top left corner and go back to the conversations list.

### Actual behavior:

The Hamburger button on the top left corner is missing

### Server Setup Information:

- Version of Rocket.Chat Server: 3.15.0
- Operating System: Gentoo system
- Deployment Method: Build from source code
- Number of Running Instances: 1
- DB Replicaset Oplog: Yes
- NodeJS Version: v12.18.4
- MongoDB Version: v4.4.1

### Client Setup Information

- Desktop App or Browser Version: Firefox 88.0.1
- Operating System: Windows 10

- Desktop App or Browser Version: Safari (iOS 14.5.1)
- Operating System: iOS

**Comment by jimmy09140456** [comment]
#22211 This PR supposed will fix this issue.
