### ISSUE TITLE
A chat with 7,000 messages works too slow

### ISSUE THREAD

**Issue by mohemiv** [RocketChat/Rocket.Chat#22124]
### Description:

In a chat with 7,000 messages, 50 attachments, and 150 screenshots, you cannot easily jump to the start of the conversation in order to read everything in the chat or just find a single message by looking. It may take you 15-20 minutes to scroll to the start of the conversation, both in web and desktop version. In a bigger conversation it may be even impossible to do so.

In addition, if you switch to another chat after scrolling to the start, all fetched data will be vanished, and you will need to scroll to the start for 15-20 minutes again after you return.

I suggest it will bee good to store all the chat data on the client side in order to momentarily display it, and also provide an option to expand fetch limits on a client side. 

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.0
- Operating System: Linux
- NodeJS Version: v12.22.1
- MongoDB Version: 4.0.24

**Comment by wrivendell** [comment]
I have the same issue. I have about 10 users. Its a private hosted server. My wife and i use it all day every day since we work in different areas. We have a mix of photos screenshots cat videos and tons and tons of chat......  this convo when i open rocket chat (windows client) it takes a good 4 seconds to be responsive. It's also frozen on a day or two ago and tthen snaps to the latest when it unfreezes. 

All other users I dont have this issue with but the convo is def not as large. 

I'm running a snap server on a dedicated VM 
![image](https://user-images.githubusercontent.com/77513899/135177900-8aec3dbf-dafd-4ec3-8c71-866bbc7c7807.png)

This is the only error I'm seeing. and I dont really know where to check for others. Like i said, nothing is FAILING its just really slow for that one convo. I suspect more convos will end up this way as they grow. Which makes this not scalable. I'm hoping it is a config issue... 
![image](https://user-images.githubusercontent.com/77513899/135177938-d1821509-7f3f-4d1a-8c43-e6ca1fce82bd.png)


Any suggestions on what to look for or monitor to help report this bettter? 
thanks.

**Comment by thankstipscom** [comment]
I have the same issue. I have about 10 users. Its a private hosted server. My wife and i use it all day every day since we work in different areas. We have a mix of photos screenshots cat videos and tons and tons of chat......  this convo when i open rocket chat (windows client) it takes a good 4 seconds to be responsive. It's also frozen on a day or two ago and tthen snaps to the latest when it unfreezes. 

All other users I dont have this issue with but the convo is def not as large. 

I'm running a snap server on a dedicated VM 
![image](https://user-images.githubusercontent.com/77513899/135177900-8aec3dbf-dafd-4ec3-8c71-866bbc7c7807.png)

This is the only error I'm seeing. and I dont really know where to check for others. Like i said, nothing is FAILING its just really slow for that one convo. I suspect more convos will end up this way as they grow. Which makes this not scalable. I'm hoping it is a config issue... 
![image](https://user-images.githubusercontent.com/77513899/135177938-d1821509-7f3f-4d1a-8c43-e6ca1fce82bd.png)


Any suggestions on what to look for or monitor to help report this bettter? 
thanks.

**Comment by Vringe** [comment]
Same problem here. Opening a chat makes it unresponsible for several seconds.

Could be related to #31

**Comment by hugocostadev** [comment]
After the Room Rewrite to React and Blaze removal in **6.x Release** this is not happening anymore. Closing it
