### ISSUE TITLE
Spoiler tag

### ISSUE THREAD

**Issue by epatpol** [RocketChat/Rocket.Chat#2248]
I think it would be nice to have spoiler tags. These would show either on click or hover. Our team would often use highlighting on irc to spoiler out some comments, and that is something we miss a bit on rocket.chat (also unavailable on slack and mattermost).

**Comment by geekgonecrazy** [comment]
I think i've seen this feature primarily on forums.  I would agree this would be a nice improvement.  Especially for huge code dumps.


How would you foresee this being implemented?  I would think you wouldn't necessarily want to auto add this spoiler tag.  Because some larger bodies of text you don't want hidden behind a tag.

**Comment by patoupatou** [comment]
I don't know what's the best way to implement it, I think they have a code snippet button on Slack, and when it's posted on the channel, you can hide/show it. Maybe spoiler tags could be implemented the same way?

Otherwise maybe it could be two separate features, one for code snippets (i.e made especially for code) and another one for inline spoilers (using similar tags to  ~strike~ or _italic_). In the case of spoilers, maybe simply hovering on the text would make them appear?

**Comment by bott0r** [comment]
How about Black Ink on Black Background so that you you have to mark/select the text to see it :)

```css
test    // #ff0000
```

**Comment by patoupatou** [comment]
Yes that's one of the way I was thinking about. In irc, we change text background/foreground color to be the same, forcing people to highlight in order to see the text. 

In Rocket.chat, it could be like this, or it could be a collapse/expand type of spoiler for spoiler "blocks". The only problem I can think of with this solution is that inline spoilers wouldn't work (unless the collapse/expand button is also inline?)

**Comment by BackIsBachus** [comment]
Maybe that using [this library](https://www.npmjs.com/package/spoiler-alert) may be useful for the inline spoilers. It blurs the section and you can un-blur them by clicking on them (which may be nice for the mobile version because you may just need to tap on the section).

**Comment by ebxm** [comment]
Hello, I am interested as well.

**Comment by SeanPackham** [comment]
Closing as this feature is not on our short term roadmap, we will revisit once other priorities have been addressed.

**Comment by mkasprz** [comment]
Right now it can be done with KaTeX: `\[\color{black}\colorbox{black}{Han Solo Shot First}\]`.
