### ISSUE TITLE
Can you build the latest version of rocketchat on the snap?

### ISSUE THREAD

**Issue by phanmduong** [RocketChat/Rocket.Chat#22551]
I checked version of rocketchat on the snap. The current version is 3.15.0. It has some problem about resumeToken, I see that it fixed at version 3.16.0.
Can you update it?

![Screen Shot 2021-07-02 at 15 32 13](https://user-images.githubusercontent.com/18007936/124245969-b07d5a00-db4a-11eb-88a4-0187938bd2b5.png)

**Comment by debdutdeb** [comment]
Hi!

We hold back snap releases for about 2 weeks for QA. 3.16.0 was released 4 days ago and 3.16.1 yesterday. You can expect to see the snap released in mid July.

In the future please ask these kinds of questions either on the forum or our open server.

https://open.rocket.chat
https://forums.rocket.chat

GitHub is only for bugs and feature requests. 

Closing this since it's not an issue. Thanks!!
