### ISSUE TITLE
Attachment links have truncated domain name

### ISSUE THREAD

**Issue by jlivschitz** [RocketChat/Rocket.Chat#22604]
### Description:

Files attached to the messages get a broken link with the last character of the domain name removed, e.g. my.host.com -> my.host.co. If I go to the tab which lists all attachments of this page then the links are correct however.

### Steps to reproduce:

1. Go to a discussion or a channel
2. Upload a file
3. Verify the link of the attached file

### Expected behavior:

Link should include correct domain name

### Actual behavior:

Last character of the domain name is truncated 

### Server Setup Information:

- Version of Rocket.Chat Server: 3.16.1
- Operating System: Ubuntu 20
- Deployment Method: docker
- Number of Running Instances: 1 
- DB Replicaset Oplog: 
- NodeJS Version: 12.22.1
- MongoDB Version: 4.0.25 / mmapv1 (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Chrome 91.0.4472.114
- Operating System: Mac OS Catalina

**Comment by jlivschitz** [comment]
Issue appears only when running in a sub folder behind nginx reverse proxy. Since running in a sub folder is going to be deprecated, I withdraw the issue.

**Comment by rmaksimov** [comment]
Truncating a domain and running RC in a subfolder are two different things that should not be interconnected. The issue still persists in 3.16.2

**Comment by johncrisp** [comment]
Please do not @ people - it is unnecessary and will get you ignored rather than listened too. The Community Team is watching all bugs now so just add your comments and we will see. Thanks.

> Issue appears only when running in a sub folder behind nginx reverse proxy. Since running in a sub folder is going to be deprecated, I withdraw the issue.

In actual fact we are going to continue to support this now. See my post here:

https://forums.rocket.chat/t/support-for-installation-in-subdirectory-will-be-discontinued/6371/26?u=john.crisp

> Truncating a domain and running RC in a subfolder are two different things that should not be interconnected.

I am unsure of what you mean here.

If I understand this correctly this issue only appears to happen with attachments when you are running ins subfolder? It does not appear to happen otherwise? If it does can you please demonstrate this?

Please post some setup info - we are going to test this ourselves and if we can repeat it we will re-open this Issue.

**Comment by jlivschitz** [comment]
Correct: this issue only happened with attachments when our RocketChat installation was running in a subfolder (/chat). We've moved it to the root then and now it works fine. It was a simple setup with bitnami RocketChat docker container behind the nginx reverse proxy. No specific setup was done apart from what is written in the documentation for the reverse proxy with nginx. I don't have the setup anymore since we just relocated it back to root, so can't rerun it and check what are the conditions to reproduce the problem.

**Comment by rmaksimov** [comment]
I have the same installation type of RC (in a subfolder with nginx as a reverse proxy), but I have no idea how this might affect a domain name. As I mentioned before, the issue persists in the following versions: 3.15.4, 3.16.1, 3.16.2, 3.16.3, while versions 3.14.6 and below work as expected

After upgrading from 3.14.2 to any version of higher branches all attached images look as follows:
![image](https://user-images.githubusercontent.com/2904679/125623912-006ff18b-2027-45c1-81cb-391b5ac701e3.png)
which is a result of an incorrect domain name (last character of the domain name is truncated)

**Comment by johncrisp** [comment]
> I have the same installation type of RC (in a subfolder with nginx as a reverse proxy), but I have no idea how this might affect a domain name.

Because there is likely some code somewhere in Rocket.Chat that is chopping off a character too many when adding the subdirectory.

So you have say:

www.mydomain.com

Then want to add /mydirectory

You might need to check for a trailing / on the domain before adding your subdirectory eg

www.mydomain.com/

Depending on your code it might 'always' remove the last character, or it might remove it if it is '/' or some other rule.

If it mistakenly automatically removes 'the last character' without checking that this is a '/' you will end up with

www.mydomain.co

And then add your subdir

www.mydomain.co/mydirectory

And there is your error.

I happen to know there was scenario like this already. We need to check if this is still there, or another problem.

**Comment by rmaksimov** [comment]
Yeah, I know how it works. I also tried to change the domain name in RC settings, but it didn't help
