### ISSUE TITLE
SPK Link in README is 404'ing

### ISSUE THREAD

**Issue by jeremiah** [RocketChat/Rocket.Chat#2261]
The link to https://rocket.chat/releases/latest/spk in the README seems to end up here: https://cdn-download.rocket.chat/build/rocket.chat-0.18.1.spk?48877563617b0bbd2f538d2ce16db285-5 which is "page not found."

**Comment by engelgabriel** [comment]
Its because of this commit: https://github.com/RocketChat/Rocket.Chat/commit/dcea9e648b9089d18a711bbd1acc32397e2763ce

We want to use travis new building infrastructure, that doesn't allow root user, so we need to find a way to automate the SPK build without having root privileges on the builder container. 

@kentonv @jadeqwang @Sing-Li @jparyani ideas?

**Comment by kentonv** [comment]
Technically, building an SPK doesn't require root, but `vagrant-spk` requires running Virtualbox, which I'm guessing isn't available. If we could find a way to run [`meteor-spk`](https://github.com/sandstorm-io/meteor-spk) directly (skipping Vagrant), it should work OK. @zarvox might be able to come up with the right command-line. It will require installing a copy of Sandstorm locally to get the dev tools, but it can be installed without root privileges for this purpose.

All that said, I think it would be best if the readme linked to the app market listing:

https://apps.sandstorm.io/app/vfnwptfn02ty21w715snyyczw0nqxkv3jvawcah10c6z7hj1hnu0

IIRC, the auto-built SPKs end up with a different app ID every time, which means that if someone were to install one of them, they'd never get updates. People probably should stick to the app market to avoid that fate.

**Comment by engelgabriel** [comment]
We currently use Travis CI to do our builds.

The entry point to generate the develop SPK was:

https://github.com/RocketChat/Rocket.Chat/blob/develop/.travis/sandstorm.sh

And the scripts I use on my own machine are here:

https://github.com/RocketChat/Rocket.Chat/tree/develop/.sandstorm

Do you have an example of someone that uses `meteor-spk` in a Docker container so we can take a look?

**Comment by kentonv** [comment]
Switching away from vagrant-spk would be a big change and probably not the best thing to do since most of our tooling work focuses on vagrant-spk. Unfortunately vagrant-spk requires the ability to start a VM, so will not run without root privileges.

Unless, maybe, if you were to use a software VM like qemu? It would be slow, but for a CI maybe that doesn't matter. @zarvox, is that possible?

**Comment by engelgabriel** [comment]
But our Travis CI was building the SPK files without vagrant IIRC when we had SUDO enabled, it was just not submitting it to Sandstorm.

**Comment by zarvox** [comment]
I'm confused - the script linked which (previously) did Travis builds doesn't appear to require root privileges at all.

What are the properties of the thing you want to have here?

**Comment by engelgabriel** [comment]
I'll re enable it see the error log

**Comment by MartinSchoeler** [comment]
Closing this due lack of updates, if you still experience this issue please open a new issue with updated details. Thanks!
