### ISSUE TITLE
IFrame authentication in a non monolithic environement

### ISSUE THREAD

**Issue by julienchabanon** [RocketChat/Rocket.Chat#22630]
Hi there!

I am trying to integrate rocketchat in a IFrame in my vue.js app but my front-end and my back-end are separated and do not share the same cookie session. However, it appears that the rocketchat IFrame API URL expect to be authenticated by cookies as the doc mention. My front-end talks to my back-end using oauth. However, I did do a quick prototype a rails app, monolithic so, and it was working like a charm.
![image](https://user-images.githubusercontent.com/5224704/125117390-3013a780-e0bc-11eb-97af-9039fd5f84fb.png)
![image](https://user-images.githubusercontent.com/5224704/125117713-9c8ea680-e0bc-11eb-95b2-db4166b58f81.png)

Am I missing something? Thanks

**Comment by djcruz93** [comment]
@julienchabanon once a user sign-in to your web app, the iframe will automatically make a request to `API URL` to get that user signed-in to the rocket chat as well. Now in order to establish the identity of that user, you need the session/token, right? Then only you'll be able to verify that user if it is signed-in or not. So in the `API URL` request, the iframe automatically passes the cookies. Now your controller/handler on the backend which is handling requests on `API URL` will use that cookie to establish the identity and verify if the user is signed in. If the user is signed in, then the controller will make login API request to rocket chat and return the loginToken in the same format as specified in the [documentation](https://developer.rocket.chat/guides/developer/iframe-integration/what-is-iframe-auth).

I think it is not about monolithic/non-monolithic setup, the developer is free to decide his auth flow. I hope it helps.

**Comment by johncrisp** [comment]
Thanks for the comment Dhruv!

Julien, I think this is a support query rather than a bug.

if you have further queries do please ask in the https://forums.rocket.chat or https://open.rocket.chat

Closing it for now - if you have evidence of a bug we can re-open this.

**Comment by julienchabanon** [comment]
Thank you for your answer. Howver, that did not solve my problem regarding API URL because:

- It rely on a cookie session in my backend
- My frontend cannot serve json like rocketchat API URL is expecting
- Request is made by rocketchat backend so its behaviour can't be changed to include an oauth access_token

But it seems that I managed to work around this and get rid of this API URL thing.
1) In rocket IFrame URL, under accounts/Iframe, my backend now respond with:
`<script>
        window.parent.postMessage({
          event: 'try-iframe-login'
        }, '#{RocketChatHelper::ROCKET_URL}');</script>`

2) Still under accounts/Iframe, API URL can now be blank.
3) In my IFrame src URL in my frontend app,  I am now passing resumeToken as a GET parameter as found here:
[https://docs.rocket.chat/guides/administrator-guides/misc.-admin-guides/authentication](url)

Before passing this resume token (authToken), I query my backend where I use rocketchat API in order to login my user and get this rocketchat authToken.

So far it works well. I saw some people having the same issue as me so I hope it will helps :)

Thank you!
