### ISSUE TITLE
Images - Enable zoom on mobile

### ISSUE THREAD

**Issue by Johann-Snapp** [RocketChat/Rocket.Chat#2278]
It would be quite great if, on mobile, we could zoom on images once opened.

**Comment by soenkef** [comment]
+1

**Comment by soenkef** [comment]
Hey, what is about this issue? This would be a great feature!

**Comment by xenithorb** [comment]
This should be retitled, because:

- It would likely affect both mobile and browser
- It is also necessary on the desktop. 
    - As it stands today, it's only possible to view the image at the width of the browser, this causes issues with a smaller sized browser or Electron window, since one cannot zoom the image currently
- The use should be able to use the scroll wheel to zoom into an image that is currently being displayed (post clicking on it, lightbox I think it's called) 
- Owncloud/nextcloud presently has this in the [**Gallery+** extension](https://github.com/interfasys/galleryplus). Perhaps look their for clues, simply click on the image, pops up, scroll to zoom in. Makes reading text and other things easy.

**Comment by xenithorb** [comment]
https://github.com/interfasys/galleryplus/blob/master/js/slideshowzoomablepreview.js

**Comment by istanleyyaw** [comment]
any update on this？waited one year foe this great feature

**Comment by engelgabriel** [comment]
@karlprieb is already working on this.

**Comment by Molle500** [comment]
@engelgabriel now you got 2 of the same issue on 0.50 maybe close one of them? :)
#5123
