### ISSUE TITLE
Bug in search with cyrillic alphabet 

### ISSUE THREAD

**Issue by reinaldonetof** [RocketChat/Rocket.Chat#22833]
### Description:

Hi guys!

Well, there was an issue on mobile about Russian alphabet search, which we are already solving. However, we noticed that the spotlight does not return any rooms when searching with Cyrillic alphabet, only users. So I created a public channel on `open.rocket.chat` with the name: `ЩДФЩДФ` to test the request

#### Endpoint
`POST` https://open.rocket.chat/api/v1/method.call/spotlight

#### Data Sent
```json
{
  "message": "{\"method\":\"spotlight\",\"params\":[\"ЩДФЩДФ\",[],{\"users\":true,\"rooms\":true}]}"
}
```                    

#### Data Received
```json
{
  "message": "{\"msg\":\"result\",\"result\":{\"users\":[],\"rooms\":[]}}",
  "success": true
}
```

### Steps to reproduce:

1.  Click on `Search`
2.  Write `ЩДФЩДФ`, or with any case type

### Expected behavior:

- Expect that the room is returned from API
### Actual behavior:

- Doesn't return the room from API

### Server Setup Information:

`open.rocket.chat`

**Comment by ankar84** [comment]
I have some additional detail on this issue.
`ЩДФЩДФ` not show in result in Spotlight if you not in that public channel - **it's a bug** (because I believe public channels search should work)  **and need to be fixed.**
But if user joins that channel - `ЩДФЩДФ` is shown in result in Spotlight
![image](https://user-images.githubusercontent.com/4023037/127961688-91a04baa-a40a-4802-8fe7-138658d2efc1.png)

**Comment by debdutdeb** [comment]
Hmm, thanks for reporting this Reinaldo. Also thank you Anton for confirming. Will add this to our list for the next product meeting.
