### ISSUE TITLE
3.17.0 Mobile App BlackScreen

### ISSUE THREAD

**Issue by LaurenceJJones** [RocketChat/Rocket.Chat#22843]
We upgraded to 3.17.0 yesterday but now when we sign new users up by putting in the workspace URL it no longer connects. We get entry in logs saying a request was made but nothing loads within the app.

Anyone else getting this?

Mobile version: 4.18

**Comment by debdutdeb** [comment]
Hi Laurence,

Please follow our guidelines for reporting issues:

https://rocket.chat/docs/contributing/reporting-issues

Please understand that GitHub is reserved only for bugs. I'd suggest you to go for one of the following - 

https://open.rocket.chat/channel/support
https://forums.rocket.chat

Someone there (I might be one of them 🙌🏼) will surely help you. And if it turns out to be an actual bug, open an issue! This way you should also have more than enough information to fill up the bug report 😉 

Help us help you! Thank you 🙂

**Comment by LaurenceJJones** [comment]
---
name: Bug report
about: Create a report to help us improve

---



### Description:

We have upgraded to 3.17.0 and a new user has tried to enter the URL within the app stated they receieve a "black screen".
I don't use the mobile app personally so I downloaded the app fresh and entered the URL to which I got the same effect.

### Steps to reproduce:
Here are the steps we taken from upgrading to 3.17.0
1. 3.16.0 Upgraded from 3.13.0 we took each gen leap 13-14-15
2. Upgraded to 3.17.0
3. Users try to login by putting the workspace URL as the domain.
4. Nothing seems to load but we get request via a log service with the correct user agent.

### Expected behavior:

Application to load the information we have stored within rocket chat and offer the user to login.

### Actual behavior:

Users is offered a black screen instead of login prompt.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.17.0
- Operating System: Ubuntu
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.22.1
- MongoDB Version: 4.0.23

### Client Setup Information

- Desktop App or Browser Version: 14.8
- Operating System: IOS

**Comment by LaurenceJJones** [comment]
Self resolved. Note for anyone that has similar issues but no idea, Administration > General > Api: Dropping Max Record Amount below 50 and Default Count below 15 does not allow the mobile app to gather all the settings it needs to show the login form. Will report this as a bug?
