### ISSUE TITLE
Move message between channels

### ISSUE THREAD

**Issue by jmatsushita** [RocketChat/Rocket.Chat#2300]
Your Rocket.Chat version: 0.18.1

It would be useful to be able to move messages between channels.

**Comment by andreas-bulling** [comment]
I support this feature request/idea. It happens quite often that people post into the wrong channel and being able to move (directly multiple) messages instead of deleting and submitting them again would be great

**Comment by bios-ben** [comment]
I came here to request this, as well as the feature within the move dialog to move to an entirely new channel. It's important to be able to select a set of messages at once, and click move channel on them and they just sit in the new channel with the same original timestamps, ordering, etc ... like they were in the right place the first time.

**Comment by bigsmoke** [comment]
I'm not sure if “me too!”-type comments are welcome here, but I too would like this. :-)

**Comment by aydancoskun** [comment]
I'd love that too, if its OK to say that here

**Comment by pshute** [comment]
I'd like this too, for the same reasons as above (people posting to wrong channel, including me).

What do we do when someone posts to the wrong channel, and people reply there? Move them all? How do we identify everything that needs to move? Certainly we could move messages that link to the message we want to move.

Do we want to move them and leave their dates intact, as bios-ben suggests? If they're not new, they might never be seen when they arrive in the new channel if there are more recent messages. And people who have been replying in the wrong may assume the message has been deleted.

I think there should be a "stub" left in the original channel, with the original message's date/time, and a link to the new location, with an explanation about where its gone, and who moved it.

Perhaps I'm overcomplicating things? Perhaps if there was a global search function, this suggestion would become mostly obsolete (see https://github.com/RocketChat/Rocket.Chat/issues/1615).

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

I am closing this in favour of #9615 which concerns itself with forwarding messages to other channels.

In general, I think this is a thing that not neccessarily can be fixed by the software. Of course, the UI needs to be so good as to prevent a larger amount of people from "not knowing where they are", but I think this needs to be discussed rather under the hood of UI improvements rather than moving messages which only gets necessary because of a maybe not so good UI.

Improving the UI to prevent this should be the major approach here. I invite you to discuss this over at https://forums.rocket.chat/c/feature-requests and open a new request based on these discussions as soon as all the aspects become more clear.

Cheers & thanks for your understanding
Thomas

**Comment by reitzig** [comment]
@TwizzyDizzy I agree, but I think you're missing a use case. A new topic may emerge in an existing channel. After creating a new one, migrating the pertinent messages in the old one over would be a nice thing to have.

**Comment by tomhung** [comment]
In our office it is very common for a user to post in #employees instead of #random or #general.  As admin, I would love to move posts from one channel to another.  It would be great if it pushed a link to the new location and just say that the post was moved.  Maybe say who it was moved by. 

This will allow us to maintain organization and to encourage proper organization of posts.

**Comment by sukamare** [comment]
Any news on this?
