### ISSUE TITLE
Message Auditing Panel

### ISSUE THREAD

**Issue by Lucas-Simoes-SI** [RocketChat/Rocket.Chat#23005]
Hello,

Is there on rocketchat the option to audit the messages, have a history of each room?

**Comment by debdutdeb** [comment]
Hi Lucas,

Can you please ask this question on our open community server?

https://open.rocket.chat/channel/support

That's the most appropriate place for questions like these. 

We reserve GitHub only for bugs. 

I'll close this one since it's not exactly an issue - nor a bug.

When asking this question on open, please also include wdym by "history of each room". I'm not entirely sure about that.

Thanks.
