### ISSUE TITLE
Use Real Names

### ISSUE THREAD

**Issue by ddv88** [RocketChat/Rocket.Chat#23051]
This problem has not been fixed for more than 2 years..
Maybe you should remove the setting with names altogether?
Let the full name always be used by default. If the account does not have a full name only then use the username.

<details>
  <summary>SHOW</summary>

![Rocket Chat - httpsrocket-chat unictech r2u](https://user-images.githubusercontent.com/8138405/131099231-e9f94b29-70ee-4c1e-bd13-6791572d2746.png) ![Rocket Chat - httpsrocket-chat unictech ru](https://user-images.githubusercontent.com/8138405/131099038-8b97dd35-1ae0-4d16-849f-b061456debf3.png)

</details>

```
Deployment
Version
3.17.2
Apps Engine Version
1.27.1
Node Version
v12.22.1
Database Migration
228 (август 27, 2021 10:40)
MongoDB
4.0.26 / mmapv1 (oplog Enabled)
Commit Details
HEAD: (fe0e5e435)
Branch: HEAD
```

**Comment by debdutdeb** [comment]
Hi 

The "use real name" setting seems to be working, is it not? If it's turned on, and some one is mentioned in a room, the full name is showed instead of username.

Or are you talking about the quoted messages?

> This problem has not been fixed for more than 2 years..

Can you please put a hyperlink to that issue here? I have a meeting with the product team today, I'll see if I can bring it up then.

One final thing, please try to **always** fill the bug template. I know sometimes it might seem unnecessary, but that's not the point. It's about making it a habit, a practice. If you don't (no matter the necessity), someone else will see and follow without really understanding why you did what you did. I'm just trying to make this issue list as uniform and presentable as possible. 

Thank you.

**Comment by lebkayn** [comment]
one place comes to my mind: on starting a new direct message with another user. on top of it it says "You have joined a new direct message with user_name", not using the real name

**Comment by ddv88** [comment]
Hi!

> Or are you talking about the quoted messages?

Yep. Quotes, Threads, Resend messages etc.
I saw, that on public test server there no issue with this. I thought that problem is on our server, but now i ran absolutely clean install in Docker and the problem is still exist.

> Can you please put a hyperlink to that issue here?
I have not started a thread before, but I have seen already created topics for the same problem.

> I'm just trying to make this issue list as uniform and presentable as possible.
I've got it. Sorry for this

**Comment by dmonn** [comment]
@debdutdeb +1 on this issue. At several places, the usernames are shown even though 'Use Real Names' is enabled. This can have security implications if the username is a user's email, for example. Places include:

- Quotes
- Threads
- "You have joined a new direct message with ...."

**Comment by TBG-FR** [comment]
> @debdutdeb +1 on this issue. At several places, the usernames are shown even though 'Use Real Names' is enabled. This can have security implications if the username is a user's email, for example. Places include:
> 
> * Quotes
> * Threads
> * "You have joined a new direct message with ...."

Looks like sometimes even some people's name in sidebar's "room list" are displayed using username instead of realnames, and it's "random"
