### ISSUE TITLE
overflow of text on button multiple times

### ISSUE THREAD

**Issue by shubhangi013** [RocketChat/Rocket.Chat#23112]
At https://rocket.chat/,  there is an overflow of text multiple times for the button 'Schedule demo ' and at a place, there is also inefficient stying. I've attached the relevant screenshots.
![Screenshot from 2021-09-04 22-44-18](https://user-images.githubusercontent.com/78342516/132103164-d7260b90-9aa2-44de-ba3d-62d1f5c7f981.png)
![Screenshot from 2021-09-04 22-44-03](https://user-images.githubusercontent.com/78342516/132103167-2627035e-d77f-47ff-b8be-b3159e80ea70.png)
in the below attached screenshot  'communication' isn't visible.
![Screenshot from 2021-09-04 22-42-36](https://user-images.githubusercontent.com/78342516/132103171-aceacfaf-7efc-467b-b1cc-ca7191341797.png)

**Comment by debdutdeb** [comment]
Hi, thanks for taking time into reporting this. Can you tell me which browser you're currently using? Everything seems to be fine in my end, using latest Chrome.

**Comment by shubhangi013** [comment]
I'm using Firefox latest version

**Comment by debdutdeb** [comment]
Hi, tried that as well (and a couple other browsers), seems to be working fine. Probably some issue client side on your end. Please follow up on https://open.rocket.chat/channel/support of start a thread on our forum and someone might be able to help you on this.

I'm closing this now since it isn't a bug. Thanks.
