### ISSUE TITLE
Gmail / Google Apps blocking Rocket.Chat emails

### ISSUE THREAD

**Issue by improvethings** [RocketChat/Rocket.Chat#2312]
Your Rocket.Chat version: 0.19.0

Has anyone else noticed that gmail or Google Apps emails don't get the initial emails upon signup? 
Test SMTP works, and sign up emails also seem to work when testing with my personal email server. 

Possible issue: Does it need reverse DNS?

**Comment by engelgabriel** [comment]
What SMTP settings are you using?

**Comment by santhosh9** [comment]
I am using an email hosted at hostgator for smtp and it sends emails to only those emails that are related to my domain, none of the emails or forgot password or verification mails go to gmail accounts, any user signed up with gmail does not get any emails, does anyone know how to fix this???

I installed rocketchat in digital ocean centos server and using the IP to access the rocket chat. Installed rocket chat recently by following instructions on the rocket chat docs, so the versions used are recent ones...

Anyone else facing same issue? can someone help me with this?
Note : Whenever I click on test mail from smpt, it does say its successful and sent email to my gmail account, however no email comes to my gmail inbox or to the spam folder.
Thanks!

**Comment by Triloworld** [comment]
Reopen
Problem with setting : Less Secure Apps
https://support.google.com/a/answer/6260879?hl=en
How to configure so we can force Rocket.Chat to be more than less secure apps visible for Gmail.

For GSuite: It need to be enabled for organisation, then by user must be done separately. 
Before: Work just fine because no forcing of that settings by Google.

Can someone add to documentation some info about that? And of course maybe some example settings for that case ;/

Settings work just fine after I switch "ON" for "Enable less secure apps"
