### ISSUE TITLE
https://releases.rocket.chat/latest/download returns 4.0 version

### ISSUE THREAD

**Issue by jadanah** [RocketChat/Rocket.Chat#23137]
### Description:

When using the https://releases.rocket.chat/latest/download url to get the latest release it downloads a 4.0.0 version not the 3.18.1 version expected.

### Steps to reproduce:

1. Go to https://releases.rocket.chat/latest/download
2. Downloaded file is rocket.chat-4.0.0.2f33bd78960706bc033d77cbc26bd107a75597cb.tar

### Expected behavior:

To return 3.18.1 version

### Actual behavior:

Downloads undocumented 4.0.0 version

### Server Setup Information:

N/A

### Client Setup Information

N/A

### Additional context

N/A

### Relevant logs:

N/A

**Comment by kbondarev** [comment]
The rocketchatctl tool also displays version 4.0.0, I assume it is all connected:

```
# rocketchatctl check-updates
Current update available for RocketChat server: from 3.10.3 to 4.0.0branch
```

**Comment by wreiske** [comment]
![image](https://user-images.githubusercontent.com/6295044/132381708-2ff660fb-c204-4c29-ad59-de610e541425.png)

I don't see a 4.0.0 tagged release 🤔 https://github.com/RocketChat/Rocket.Chat/releases

**Comment by geekgonecrazy** [comment]
Fixed.  Still digging into what exactly happened here.

**Comment by ankar84** [comment]
> I don't see a 4.0.0 tagged release 🤔 https://github.com/RocketChat/Rocket.Chat/releases

Indeed, but open.rocket.chat already on 4.0.0

**Comment by sampaiodiego** [comment]
I'm sorry about that.. What happened is that of bumping the version to `4.0.0-develop` on this PR https://github.com/RocketChat/Rocket.Chat/pull/23086 we bumped to `4.0.0` which then caused the releases.rocket.chat to think it was the final 4.0 version being published.. 

but we never tagged a version 4.0.0 .. I'm sorry about any confusion caused by this.. everything is correctly pointing to 3.18.1 now.
