### ISSUE TITLE
Deprecated MongoDB <= 4.0 - update docker-compose.yml

### ISSUE THREAD

**Issue by sephentos** [RocketChat/Rocket.Chat#23341]
`docker-compose.yml` should be updated accordingly to changed mongo dependency on 4.0.0

**Comment by SoulEater45** [comment]
I faced the issue too.
One big bummer, is the removal of the `mmapv1` storage engine. So a migration needs to be done (I guess, I am not experienced with databases). So a small guide on that would be nice too.

**Comment by sephentos** [comment]
> I faced the issue too. One big bummer, is the removal of the `mmapv1` storage engine. So a migration needs to be done (I guess, I am not experienced with databases). So a small guide on that would be nice too.

You can find a migration guide here: https://docs.rocket.chat/installing-and-updating/manual-installation/mongodb-mmap-to-wiredtiger-migration

I've followed these steps and managed to upgrade to Mongo 4.2 within docker.
After migrating you can change the 4.0 tags in docker-compose.yml to 4.2.

**Comment by maeries** [comment]
Thanks for the link, but what am I supposed to to after that? Switch back to the docker-compose.yml I used before or should I keep using the one with the migrator?

**Comment by SoulEater45** [comment]
@sephentos thanks a lot for the link! I just did the migration successfully and should probably keep the database up-to-date I guess!

@maeries I switched to my previous docker-compose and just changed the version from `4.0` to `4.2` and the previous mongo command, to the one provided in the migration compose file `mongod --oplogSize 128 --replSet rs0 --storageEngine=wiredTiger`. I guess you can also leave the migration file, but comment the migration part out, since I would also guess you dont want the migration container to run every time you recreate your stack
