### ISSUE TITLE
German (and possibly other) translations of user activity wrong since 4.1.0

### ISSUE THREAD

**Issue by chotaire** [RocketChat/Rocket.Chat#23593]
### Description:

German translation of user activity is wrong since 4.1.0:

`$USER is schreibt` should be: `$USER schreibt`
`$USER1 und $USER2 are schreiben` should be: `$USER1 und $USER2 schreiben`

This may very well be broken in other translations too.

### Steps to reproduce:

1. Install Rocket.Chat 4.1.0 and switch to German
2. Add three users
3. Watch one and/or two users writing on channel

### Expected behavior:

See description

### Actual behavior:

See description

### Server Setup Information:

- Version of Rocket.Chat Server: 4.1.0
- Operating System: Linux
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: active
- NodeJS Version: v12.22.1
- MongoDB Version: 5.0.3 / wiredTiger

### Client Setup Information

- Desktop App or Browser Version: Any
- Operating System: Any

### Additional context

None

### Relevant logs:

None

**Comment by chotaire** [comment]
According to https://github.com/RocketChat/Rocket.Chat/commit/428d70ae5f3c3d58686d683f0dca635c8f191440 this is not a problem with the actual translation, the problem lays somewhere inside the code.

**Comment by Karting06** [comment]
I agree with you.
Starting with this [PR](https://github.com/RocketChat/Rocket.Chat/pull/22392), the translation isn't linked to the action anymore. 
It's like this: `is/are + action` and both are translated as 2 distinct words which lead to strange things in other language (same problem in French & Dutch). (And "is" & "are" aren't present in the English translation file, so the translations are missing for all languages...)


I'm also a translator on the Lingohub project. When translating, you don't have a context for the words which doesn't help (especially in this case). For French & Dutch, I changed the translation in order to correct it. 
But I don't think that there is an alternative in German (something like `ist + action`)? (in Dutch, I used `is aan het typen`)

**Comment by hexabinaer** [comment]
@Karting06 thanks, you comment has been very helpful for me. I'd already been halfway through the on-boarding process to Lingohub just for this issue.

We've already come up with creative interpretations like informal/dialect interpretations in our internal team channel. 
>"is am Schreiben dranne"

Thanks for taking care of German translations, very much appreciated (several people maintaining Drupal translations say hello).

**Comment by Karting06** [comment]
Hi @hexabinaer 
Just to be clear, I don't do the German translations. Only the Dutch & French ones ;)

**Comment by TBG-FR** [comment]
> [...] For French & Dutch, I changed the translation in order to correct it. [...]

When will this be used in RocketChat ? Any clue on the version number ? We still see this on 4.4.2

**Comment by ketsyrk** [comment]
Same problem - Polish translation. 
There is: USER is pisanie...
should be: "USER pisze..." or "User1 i USER2 piszą..."

**Comment by chotaire** [comment]
Is anyone coming back to this? It's been broken since October and users have started to use the broken phases in real life as a running gag, I hope it will not ruin their education. ;)

**Comment by ankar84** [comment]
@dudanogueira old issue and still not fixed. Please address that to product team.

**Comment by ankar84** [comment]
5.1.0
still an issue
![image](https://user-images.githubusercontent.com/4023037/190338719-fe2d7763-486c-4f71-8ade-8d6177eeffba.png)

**Comment by m-hew** [comment]
I'm pretty sure it is related to the code in [userActionIndicator.html](https://github.com/RocketChat/Rocket.Chat/blob/develop/apps/meteor/app/ui-message/client/messageBox/userActionIndicator.html).

The line:
`{{_ "is" }}&nbsp;{{_ action}}{{#unless end}},{{/unless}}`
seems to add a translation of "is" in front of the action. I couldn't find any language file that considers this or added a translation for "is", so the code defaults to the English term "is".
Same applies to "are" which is handled in the same file.

**Comment by TBG-FR** [comment]
> I'm pretty sure it is related to the code in [userActionIndicator.html](https://github.com/RocketChat/Rocket.Chat/blob/develop/apps/meteor/app/ui-message/client/messageBox/userActionIndicator.html).
> 
> The line: `{{_ "is" }}&nbsp;{{_ action}}{{#unless end}},{{/unless}}` seems to add a translation of "is" in front of the action. I couldn't find any language file that considers this or added a translation for "is", so the code defaults to the English term "is". Same applies to "are" which is handled in the same file.

Thanks for the investigation ! I'll take a look at this, how do you think we should handle that ? Totally remove `{{_ "is" }}` ? Find a more appropriate combination ?

**Comment by Mugros** [comment]
I think #23597 isn't a good fix though, since as the first comment says, not all languages feature that tense. Present Progressive is something from English grammar, likely not featured in all languages. At least in German you can construct a fitting sentence, but it sounds worse. ("ist/sind am Schreiben"). But it looks like no one checked all other languages if this construction makes even sense. It likely doesn't.  
IMO it should've stayed one term so that every language can use their own best term for performing the action. Now it has to fit the English grammar structure. RocketChat's vocabulary likely won't increase significantly. I don't see the need to break up the terms. It's easier to add more terms than to try to add grammar rules and language specific exceptions.   
Also, the key words likely have to change too. And, like someone already remarked, chopping it up will lead to translations issues, because context is missing.
