### ISSUE TITLE
RocketChat slow performance on MongoDB wiredTiger (4.2-5.0)

### ISSUE THREAD

**Issue by theoprata** [RocketChat/Rocket.Chat#23721]
### Description:

This is not exactly a bug per se, but I thought I should create an entry for it. RocketChat has been running way slower after the migration from MMAP to wiredTiger. Both windows desktop app and web version seems to be affected. It takes a good 3-5 minutes for the RC to load. Sending a message has a second delay. Every so often the server will give a "too many requests" causing a longer delay for that one message and showing it greyed out. 

Performance on Mongo 5.0 seems to be a lot better than 4.2, but nowhere to how 4.0 mmapv1 performance was.

### Steps to reproduce:

1. Upgrade RC 4.1.0
2. Use mmapv1 then migrate to wiredTiger
3. Run the instance 

### Expected behavior:

Based on MongoDB documentation, wiredTiger is supposedly better and faster than mmapv1.

### Actual behavior:

Sometimes sending a message becomes grey and delayed due to "too many requests" caused by all current users sending multiple messages. Sometimes send a picture over fails.

Even TOTP fails and it doesn't provide the option to enter the 2FA codes. It just comes up with a red TOTP Required alert.

### Server Setup Information:

- Version of Rocket.Chat Server:  4.1.0
- Operating System: Ubuntu 20
- Deployment Method:  Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.22.1
- MongoDB Version: 5.0.3 / wiredTiger 

### Client Setup Information

- Desktop App or Browser Version: Both
- Operating System: Windows 10/11

### Additional context

https://forums.rocket.chat/t/mongodb-v4-2-wiredtiger-slower/12566

### Relevant logs:

https://forums.rocket.chat/t/mongodb-v4-2-wiredtiger-slower/12566/4

**Comment by ankar84** [comment]
I'm on WiredTiger since 4.0 I guess, and now I'm on 4.2.17 and performance all the way good enough.
I think you need consider to check and optimize mongodb performance and here is a good start point https://github.com/RocketChat/Rocket.Chat/issues/21182#issuecomment-821142212
"too many requests" is a DDP Rate Limit and you can try to tweak it a bit or temporary disable it to get it's impact to performance.
And another good thing - you can install [RocketChat Metrics](https://github.com/RocketChat/Rocket.Chat.Metrics) to better understand what is going on with your RC deployment.

**Comment by theoprata** [comment]
Ohhhh metrics! I didn't know that existed. 

I don't have any experience with MongoDB before this and only a little with docker and docker-compose so I'll have to review those.

**Comment by dudanogueira** [comment]
Closing. This is more a devops/sysadmin issue.
