### ISSUE TITLE
Can't install on Ubuntu 21.10 

### ISSUE THREAD

**Issue by AbhJ** [RocketChat/Rocket.Chat#23810]
### Description:
I can't install the app on Ubuntu 21.10. I am following installation instructions from [link](https://docs.rocket.chat/quick-start/installing-and-updating/manual-installation/ubuntu).

### Steps to reproduce:

1. Go to [link](https://docs.rocket.chat/quick-start/installing-and-updating/manual-installation/ubuntu).
2. Follow the instructions till 'tar -xzf /tmp/rocket.chat.tgz -C /tmp'. 

### Expected behavior:
Installation to proceed.

### Actual behavior:
❯ tar -xzf /tmp/rocket.chat.tgz -C /tmp
tar (child): /tmp/rocket.chat.tgz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

![Screenshot from 2021-11-28 01-09-44](https://user-images.githubusercontent.com/48042655/143720204-f3755df6-d2a0-431d-9adb-7c3663dc7960.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 4.1.2
- Operating System: Ubuntu 21.10
- Number of Running Instances: 1
- NodeJS Version: v12.18.4
- MongoDB Version: v4.0.27

### Client Setup Information

- Operating System: Ubuntu 21.10

**Comment by Denkneb** [comment]
Hi, is the file rocket.chat.tgz in a folder tmp?

**Comment by AbhJ** [comment]
Yes it is

**Comment by Denkneb** [comment]
then something with permissions

**Comment by dudanogueira** [comment]
hi @AbhJ are you aware about docker and snaps deploy?

They are way more easy and convenient than tar installs.
https://docs.rocket.chat/quick-start/installing-and-updating/docker-containers

I'll close this issue, as this doesn't seem to be a bug.

Please, refer to our forums in order to get general support.
https://forums.rocket.chat/

Also, you can hang at our open server:
https://open.rocket.chat/

**Comment by AbhJ** [comment]
> then something with permissions

no, permissions doesnt seem to be an issue
