### ISSUE TITLE
Logging out

### ISSUE THREAD

**Issue by khodge281** [RocketChat/Rocket.Chat#23994]
I get 3-4 calls a day with techs who are "logged out of rocket chat." I pay good money for this program, for every user i have. This crap is unacceptable and is costing me money. Either you fix it or i will drop my subscription.

**Comment by geekgonecrazy** [comment]
@khodge281 Make sure to reach out to the support team with this.  The issues here are answered best effort by community team.  You're going to need a more personalized deep dive into what's happening.  With information about your setup and integrations etc.


My best guess based on previous experience with this issue is that the users might have some sort of integrations setup using their user accounts and the api.

What happens behind the scene here is for every web login and every api login a token is generated.  For performance issues the total number of tokens is capped.  So a first in first out sort of thing happens.  

So when a user has maybe an integration that logs in over and over again it will basically cause their web or mobile token to get pushed out the other side.  

Typically switching to using personal access tokens in those cases solves it.

-- 

Again.. this is just a general thing I've seen happen.  Talking to support and utilizing that relationship to talk more specifics is going to be your best bet.

Thanks,

**Comment by khodge281** [comment]
I thought I was doing that. This is where it sent me. Do you have contact info for the support team you mentioned.

 

 

Keith f. hodge, owner

9018 ooltewah-georgetown rd, ste 118

Ooltewah, tn 37363

(423) 591-5651

**Comment by dudanogueira** [comment]
Hi @khodge281!

For enterprise support, please, send an email to support@rocket.chat in order to create a ticket.

Thanks!
