### ISSUE TITLE
New request for notifications on every Sandstorm grain

### ISSUE THREAD

**Issue by mrdomino** [RocketChat/Rocket.Chat#2407]
Your Rocket.Chat version: 0.19

Every time I open a rocket.chat tab, it asks to show desktop notifications for the current Sandstorm ephemeral domain name.

**Comment by engelgabriel** [comment]
There is no way around this, because the ephemeral domain name.

**Comment by mrdomino** [comment]
It seems like there are plenty of ways around this. E.g. a setting to not ask for desktop notifications, just relying on the bell sound, would be a great workaround. Also in the long run perhaps there's something sandstorm or rocket.chat could do to make desktop notifications work with grains. I think it's worth having this open as a known issue, even if there's no short-term fix for it, even just so people can refer back to it when talking about Sandstorm design in the future.

I don't mean to be rude, and also I really appreciate you working on this at all -- rocket.chat on sandstorm has been a significant improvement to my life.

**Comment by engelgabriel** [comment]
OK

**Comment by zarvox** [comment]
I agree this one is firmly in Sandstorm's court at the moment.

I paused work on https://github.com/sandstorm-io/sandstorm/issues/919 until Rocket.Chat's desktop notifications worked on the ephemeral subdomain - for a while, https://github.com/RocketChat/Rocket.Chat/issues/1374 kept this from working, so I couldn't really test if my implementation actually worked or not.

Happily, #1374 is fixed now, so we should probably think about finishing implementing Sandstorm's postMessage API for notifications.  My vision is that I would build a JS library which replaces `window.Notification` with a full replacement of the standard Notifications API which instead of using the browser's API directly, sends the appropriate `postMessage()` calls.

Then, RC would just need to add that notifications shim, and do the appropriate patch at startup time if it's running inside Sandstorm.

I'll follow up here when I have more to show. :)

**Comment by engelgabriel** [comment]
Thanks @zarvox

**Comment by kentonv** [comment]
This was fixed by #3743.

**Comment by engelgabriel** [comment]
Thanks @kentonv
