### ISSUE TITLE
My Account >> Profile - Failed to update avatar

### ISSUE THREAD

**Issue by anvo1205** [RocketChat/Rocket.Chat#24085]
### Description:

I can't update my avatar, it keeps displaying the default avatar after reloading the page

### Steps to reproduce:

1. Sign in as admin
2. Go to My Account >> Profile
3. Upload a new avatar
4. Click Save Changes
5. Enter current password to verify
6. Reload the page

### Expected behavior:

New avatar should be displayed

### Actual behavior:

Default avatar still displays

Please open this link to see additional information including video, console errors, technical info and system info:
https://app.birdeatsbug.com/sessions/fa2DXBhQQFwOV-L-z9yin

**Comment by AbhishekJamhoriya** [comment]
Hi @anvo1205 i would like to work on this issue can you please assign me this issue.

**Comment by anvo1205** [comment]
@AbhishekJamhoriya Looks like I don't have permission to assign this issue to you

**Comment by sandrotanner** [comment]
Seems to me as this was an issue with password auto-fill.

My theory: it not only fills it in the pup-up but also further down in the section where you can change your emails and password.
That would explain why you get a Error telling you "Entered password same as current password".

Try disabling auto-filling of passwords and manually enter the password.

**Comment by kulkarnigaurav38** [comment]
Hey, so around 0:11 in the video, 'save changes' button is already enabled before making any changes in that page, so it's the password input field( lower in the same page) which got changed due to your password auto-fill in browser.
So you can just empty out that password field and 'save changes' button becomes disabled( like it should be when no changes are there) and then you can upload a new avatar and save it and it should work :)

**Comment by sandrotanner** [comment]
@anvo1205 if this is resolved, please close the issue. thanks :)
