### ISSUE TITLE
My Account - Keep getting error "Entered password same as current password" when updating profile

### ISSUE THREAD

**Issue by anvo1205** [RocketChat/Rocket.Chat#24084]
### Description:

When I try updating my profile, after I enter password to verify account to save the changes, I keep getting that error. It makes me confused whether my changes were successfully saved or not

### Steps to reproduce:

1. Sign in as an admin
2. Go to My Account >> Profile
3. Edit an information in Profile page (e.g. bio or nickname)
4. Click Save Changes
5. Enter current password to verify

### Expected behavior:

I should get a confirmation saying that my changes were successfully saved

### Actual behavior:

Getting error "Entered password same as current password", but the changes were actually saved (except the avatar, will be reported in another ticket)

Please open this link to see additional information including video, console errors, technical info and system info:
https://app.birdeatsbug.com/sessions/plhxVEynvw7BEKk7kBXAn?

**Comment by AbhishekJamhoriya** [comment]
Hi, @d-gubert I would like to work on this issue. so please assign me this issue.

**Comment by dougfabris** [comment]
Hey @anvo1205 thanks for reporting. As I can see your browser is filling the password field automatically, because of that it seems you're changing your password and the Confirm Password will be shown to double-check your new password. When you click to save it, shows the error because you did not enter the password there. Please, try to erase the password field before saving changes. Looking into your problem I think we have a UX issue here, so I'm going to talk with the design team about that. Thanks again!

**Comment by anvo1205** [comment]
Hi @dougfabris Thanks for your explanation. Yes, from user's POV, I didn't know that that field is auto filled by my current password which it shouldn't and it's confusing. It should only auto fill when I login IMO

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest version and it was fixed here: #31361
---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
