### ISSUE TITLE
Additional user statuses

### ISSUE THREAD

**Issue by rockneverdies55** [RocketChat/Rocket.Chat#2422]
Possible solutions: 
- let user define the status with a brief text
- have admins define some additional global user statuses
- or (least preferred) add few more options to rocket.chat  
  (such as _"In a meeting", "Extended Busy", "Be Right Back", "Do Not Disturb", "With a client", "Working From Home"_ etc... )

**Comment by acaronmd** [comment]
I'd love to see all these options. I'd also love to have this available in the API.

**Comment by giray** [comment]
:+1:

**Comment by joshuacoty** [comment]
:+1:

**Comment by Steak054** [comment]
+1

**Comment by DustinWoods** [comment]
:+1:

**Comment by tristanflorcb** [comment]
+1

**Comment by rauhmaru** [comment]
+1

**Comment by JohnDorianMD** [comment]
+1

**Comment by justinreock-roguewave** [comment]
+1

**Comment by spathare21** [comment]
+1

**Comment by Flickster42490** [comment]
+1

**Comment by agentlol** [comment]
+1

**Comment by Bobs13** [comment]
+1

**Comment by davidmason** [comment]
This is particularly needed in the browser because my status is automatically set to `Away` when I do not have that tab focused. I would prefer that the client not claim I am away unless I lock my screen, but if it does happen I need my team to be able to distinguish between when I am on a different tab and when I am actually AFK.

I can post in every channel every time I get up, but that information gets out of date as soon as I return and post that I am back. At the moment it is the only way to let my team know whether I'm just away for 5 minutes making a cup of tea, or if I'm taking a longer break.

**Comment by steve-a-ihtsdo** [comment]
+1

**Comment by dmoldovan123** [comment]
+1

**Comment by jbarrere** [comment]
Status could also be automatically updated when user is on a meeting (according to an outlook calendar or ical)

**Comment by trax44** [comment]
![+1](http://chambers.vic.edu.au/wp-content/uploads/2015/05/I-approve.jpg)

**Comment by cyclops24** [comment]
+1

**Comment by acteru** [comment]
+1

**Comment by MatthewTrout** [comment]
+1

**Comment by TomaszKorwel** [comment]
+1

**Comment by maxpen** [comment]
why hasn't this been added yet? ;o

**Comment by localguru** [comment]
+1

**Comment by g3org3y** [comment]
+1

**Comment by skral** [comment]
+1

**Comment by mfraiss** [comment]
+1

**Comment by mrmnmly** [comment]
+1

**Comment by cyrilferte** [comment]
+1

**Comment by m2u-84** [comment]
+1

**Comment by mbrgm** [comment]
**Please** use the thumbs-up button on the original post instead of filling peoples' inboxes with '+1' emails. Github added this feature for that reason.

If you have additional use cases to share and/or want to elaborate on why this feature would be useful, that's a reason for a comment. If you just want to say 'I want this', please use the thumbs-up button. Thank you!

**Comment by 42robots** [comment]
Hi all!
In the meantime, does anyone have experience using a custom javascript? We have this option to add custom scripts and i wonder if that would work, too.
Best

**Comment by KervyN** [comment]
> rodrigok moved this from Desireable to Review/QA in June/2018 7 days ago

Oh yeah!

**Comment by Super-Baleine** [comment]
+1

**Comment by btorellALTA** [comment]
So, what ended up happening with this feature in the June 2018 Review? Is this still simply "planned" or is there any chance PR #9353 might be worked on to be mergeable?

**Comment by marcus-no** [comment]
/away <optional time in minutes, remove away status when passed> <optional away message> would be sweet.

**Comment by taenzerme** [comment]
What's the current status on this? We're considering moving to Rocket Chat but would need a custom user status feature. Is this implemented already?

**Comment by krispayne** [comment]
It is not, as far as I know. I work remote so having a status is really necessary. Especially with the ability to mute notifications.

**Comment by bjump85** [comment]
+1

**Comment by Loki-Afro** [comment]
Whats the status of this feature?

**Comment by reetp** [comment]
> Whats the status of this feature?

Try open.rocket.chat

It is coming but it is still buggy. Looks like Custom Status is covered here:

https://github.com/RocketChat/Rocket.Chat/pull/13933

**Comment by Hudell** [comment]
I'm gonna close this since the feature was already implemented. If anybody finds any errors or wants to add something, please register a new issue.
