### ISSUE TITLE
Security release v3.18.5 not available for download

### ISSUE THREAD

**Issue by didierm** [RocketChat/Rocket.Chat#24349]
### Description:

Contrary to previous v3.18.4 and latest v4.4.0, security release v3.18.5 is not available for download.

### Steps to reproduce:

`curl -L https://releases.rocket.chat/3.18.5/download`

### Expected behavior:

Download the security update

### Actual behavior:

**{"error":"not found"}**

### Server Setup Information:

not relevant

### Client Setup Information

not relevant

### Additional context

not relevant

### Relevant logs:

not relevant

**Comment by CvH** [comment]
Obviously there is also no update at snaps too, so the release is just imaginary. But that is sadly to expect, the whole release train is completely broken since a long time already.

I have no idea about internals, but from the outside it looks like that nobody from the team cares about releases (also not security releases), everything is done manually - and nobody does it. Also if someone does anything, there is no expected behaviour - role the dice every time :( .

**Comment by debdutdeb** [comment]
I've notified the respective person to fix this issue. Looks like some tests were failing so the bundle upload got skipped.

**Comment by debdutdeb** [comment]
@CvH snap release is due Monday.

**Comment by CvH** [comment]
@debdutdeb tx for investigating, 3.18.4 was also not released at all at snaps, and the releases before where similar not released
for a long time everything stuck at some random version, similar for docker releases and then someone updates everything just to stuck at some random version again ...

no idea if this is the target behaviour :/

**Comment by debdutdeb** [comment]
For snaps we are working on automating the whole process. 

As for docker, those are already automated, unless something in the pipeline fails (like in this case, 3.18.5) there shouldn't be any delays.

**Comment by debdutdeb** [comment]
3.18.5 is now available under releases and Docker :) Closing this now.
