### ISSUE TITLE
Export list of users

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#2436]
it would be nice if we Admin have the ability to download email list for all users from Admin section, without accessing MongoDB.. also not sure if this information can be used as a form of backup, if they wanted to use in a different chat app?

**Comment by engelgabriel** [comment]
It is impossible to download passwords, there are encrypted.

**Comment by IQ2022** [comment]
@engelgabriel 
In addition to download user list (user name/email) 
Personally i think a must have there should be an option to backup entire DB from within the Rocket.Chat Admin area, and ability to build a new instant from a backup or revert to  previous issue..

**Comment by FibreFoX** [comment]
Maybe some documentation about backup-recommendations would be nice, as this seems to be the core-idea of this issue (as far as I understood this).

**Comment by mass10** [comment]
+1

**Comment by flantascience** [comment]
+1

**Comment by flantascience** [comment]
Is there a way to simply export the emails (without passwords)?   It would be nice to be able to send all users an announcement if something urgent comes up.

**Comment by lhaig** [comment]
+1

it seems my DB has been corrupted after an upgrade to 0.47.1 and my server won't start.
I still have access to the DB so could export rooms etc. I just don't know how best to do that.

**Comment by jspeigner** [comment]
A export to CSV or a mailchimp  connector would be great here.

**Comment by localguru** [comment]
You could try to get the users with mongo shell and convert the result to a csv e.g. using jq

```
// Total Users
db.users.aggregate( [
   {
     $group: {
        _id: null,
        TotalUsers: { $sum: 1 }
     }
   },
   { 
     $project : {
        _id : 0,
        TotalUsers : 1,
     }
   }
] )


// Users
db.users.find({},{
    "_id": 0,
    "name": 1,
    "username": 1,
    "roles": 1,
    "emails": 1,
    "roles": 1,
    "statusConnection": 1,
   }
);
```

**Comment by Julianoe** [comment]
I revive a little this thread to add a **+1** on that feature.
Allowing users to export their users (lel) in a single document, CSV etc.., would be a nice addition.

For me one of the worst thing companies (non-free software) do is preventing you to go to another product with your data. Allowing RocketChat admins to export their users database easily would be a nice touch.

As @FibreFoX is pointing out in general for now the software lacks usable backup solution for non technical users. I'd gladly contribute if my knowledge of javascript was not so bad :(

**Comment by TwizzyDizzy** [comment]
Hi @Julianoe 

> As @FibreFoX is pointing out in general for now the software lacks usable backup solution for non technical users. I'd gladly contribute if my knowledge of javascript was not so bad :(

I have to disagree with you on this. A manual backup "via a button" cannot be considered a backup, as it's not happening regularly and not without user interaction. That being said Rocket.Chat builds on Open Source components like `mongodb`. If you are an admin of a Rocket.Chat instance and you are not able to do a backup without a button in the software, you probably shouldn't be an admin of a Rocket.Chat instance. This might sound harsh, but when you're running a server you should be independant of those "buttons" and simply automate your backup, e.g. with https://github.com/micahwedemeyer/automongobackup in this case.

Getting a simple list can also be done via mongo-shell or GUI tools for mongodb.

If nobody brings up a really good reason for having this button, I'd like to close this issue. In the end it's rather identical to #3600 that you (@IQ2022) also opened.

Cheers
Thomas

**Comment by Julianoe** [comment]
@TwizzyDizzy i might have not previously agreed with you before but since my last comment i greatly improved my understanding of server side management, Docker among others in my case. I've successfully exported my list of users through the command line etc...

I can totally understand your point. Although i still think that allowing a users database export from the admin could be a good addition because to promote the use of free software like Rocket.Chat i think it'd be a good thing to limit the technical knowledge needed to run an instance. 

When i started to run my RocketChat server i had never used Docker before, i just learned how to use a docker-compose file and a `docker-compose up -d` command and it was up. If i was not a web developer and tech curious guy in nature i would not have gone further and it would have been ok. We would not have had backups.

Now that our instance approaches almost 70.000 messages sent i try to advocate in my social circles to convince people to launch their instance with their own friends (as an alternative to Messenger for example). Those people are not tech saavy and if it takes too long to manage they won't have the time to learn it. Adding backup option in the front end would empower those users to take a leap into free messaging.

**Comment by TwizzyDizzy** [comment]
Hi @Julianoe 

sorry, took me a while to reply, but here we go :)

> because to promote the use of free software like Rocket.Chat i think it'd be a good thing to limit the technical knowledge needed to run an instance.

I heavily disagree with this argument. Not the spirit of it, because I myself to promote FOSS and encourage others to do so, too, but: running a software on the net is a security risk. Given the nature of the software and assuming that those chats should stay private, I advocate for running a secure server. To do that, you have to have knowledge about all the $TECH involved. When you say "limit the technical knowledge needed to run an instance", the first thing that comes to my mind is documentation. You have to read it and you have to understand it. There's no way around it. And of course: was my knowledge what it is today, when I bought my first root server? No probably not. I still did have to learn a lot (and fortunately wasn't forced to learn it "the hard way" of getting exploited)...

That being said: it's not the task of Rocket.Chat to "make the life easy" of people who don't know how to operate the software. I still stand by that argument. And I find it highly irritating to tell people "who are not tech savvy" to run their own server. In my eyes this is just irresponsible.

Those are my final thoughts, I think. **In the end I have no heart feelings about this backup button and it surely wouldn't hurt (only developers time of course), but I don't share your reasoning when it comes to why you think it should be implemented.**

Cheers :)
Thomas

**Comment by FibreFoX** [comment]
Just my thoughts: RocketChat still lacks a proper instruction/way to creating some backup.

But as this was about just exporting some users, this might be closed and should get followed with another ticket specificly being about "a rocket way of having a proper and solid backup" (even including uploaded files and other stuff not sitting inside the MongoDB).

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

> Just my thoughts: RocketChat still lacks a proper instruction/way to creating some backup.

To my knowledge, this is true. I guess you could open an issue in the docs for that: https://github.com/RocketChat/docs

As for the initial issue: I'm closing this - see my reasoning above.

Cheers
Thomas

**Comment by Julianoe** [comment]
@TwizzyDizzy thanks for your extended response on that issue. It made me think and changed my mind on certain things.

You might be right on this matter and thus i agree a lot with @FibreFoX about the need for more and better documentation. 
I guess instead of making it easy for non tech savvy people the goal for opening libre software to more people is through education... so writing more articles, docs and such so we can help those people to get interested and help them acquire the needed skill to gain independence. 

In that spirit, since your last response, i started writing and publishing on my personal blog articles about Docker, and soon will be posting more about hosting a Rocket.Chat (and other services) but also Git and how to use a server to host those services and do it in a secure way, with backups etc... Those articles are in french but i hope they will help some folks on the path of learning.

**Comment by TwizzyDizzy** [comment]
Folks! Good news for tou, @frdmn got you covered: https://forums.rocket.chat/t/rocket-chat-userlist-exporter/470

You may praise his efforts and give him feedback over there :)

Cheers
Thomas
