### ISSUE TITLE
Can't install Rocket.Chat Server 4.4.0 due to conflicting Node versions (12 vs 14)

### ISSUE THREAD

**Issue by abruening-iwt** [RocketChat/Rocket.Chat#24412]
### Description:

Rocket.Chat will only install successfully with Node 12 being used but then refuses to actually start because Meteor requires at least Node 14

### Steps to reproduce:

1. Install Node 12 via n on Debian
2. Follow the instructions for manually setting up Node
3. Attempt to start the server

### Expected behavior:

Server should start

### Actual behavior:

When trying to run the server the following error is displayed and Node exits. Nothing else happens.

`Meteor requires Node v14.0.0 or later.`

### Server Setup Information:

- Version of Rocket.Chat Server: 4.4.0
- Operating System: Debian Stable
- Deployment Method: Tar (manual installation)

### Additional context

Version 4.3.3 deploys and runs fine on the same VM.

**Comment by dudanogueira** [comment]
Hi! Version 4.4.0 has upgraded meteor version.

As this is a manual installation, you should handle dependencies yourself.

I do not suggest you to run a manual installation, unless you have a great reason to do so.

Please, consider using docker instead. Closing as this may not be considered a bug.

**Comment by waldo323** [comment]
I was using: https://docs.rocket.chat/quick-start/installing-and-updating/manual-installation/centos 

While installation instructions for CentOS (and similar) does state "As from Rocket.Chat 4.4.0, NodeJS version 14.x.x is used.", it would be helpful if the instruction page also included the updated information for installing nodejs 14 instead of 12. 

More specifically the following lines should be updated: 
sudo yum install -y curl && curl -sL https://rpm.nodesource.com/setup_12.x | sudo bash -  
and
sudo npm install -g inherits n && sudo n 12.18.4 should be directed at the 14 branch.

for the first line:
For CentOS 7, as a guess(not tested), it should be something like: 
sudo yum install -y curl && curl -sL https://rpm.nodesource.com/setup_14.x | sudo bash -
For Rocky 8: sudo yum install -y nodejs

For the second line:
sudo npm install -g inherits n && sudo n 14

**Comment by abruening-iwt** [comment]
> I apologize for the additions, someone is saying the docs are deprecated #20256 so that would probably be my first problem. I will check the github repo to see if more recent instructions are there.

They mean outdated, surely.

**Comment by ali-alhaidary** [comment]
@waldo323 would you please advice the correct commands for ubuntu

**Comment by waldo323** [comment]
> @waldo323 would you please advice the correct commands for ubuntu

which version of Ubuntu? I haven't tried yet but can try with a vm and add updates if I'm able to install successfully.

**Comment by waldo323** [comment]
> @waldo323 would you please advice the correct commands for ubuntu

@ali-alhaidary which version of Ubuntu? I haven't tried yet but can try with a vm and add updates if I'm able to install successfully.

**Comment by ali-alhaidary** [comment]
> > @waldo323 would you please advice the correct commands for ubuntu
> 
> @ali-alhaidary which version of Ubuntu? I haven't tried yet but can try with a vm and add updates if I'm able to install successfully.

Thank you @waldo323 we are using 18.04 LTS

**Comment by ali-alhaidary** [comment]
@waldo323 https://github.com/RocketChat/Rocket.Chat/issues/24446
