### ISSUE TITLE
Camera not shut down after closing video call

### ISSUE THREAD

**Issue by jykae** [RocketChat/Rocket.Chat#2452]
Your Rocket.Chat version: 0.19

OS: Ubuntu 14.04 LTS
Browser: Chrome 48.0.2564.116 (64-bit)
Laptop: Dell Latitude E6410
## Behaviour

Laptop camera is not shut down when stopping video call. Only when I close the tab, camera will be turned off.
## Expected

When closing call, all the resources used should be freed/turned off, also camera.

**Comment by jclabaugh** [comment]
Rocket.Chat version: 0.20.0

OSX v10.11.3
Browser: Chrome 48.0.2564.116 (64-bit)

**Comment by jykae** [comment]
Related to WebRTC main task: https://github.com/RocketChat/Rocket.Chat/issues/933

**Comment by xadhoom** [comment]
confirmed also in 0.32.0 
Also, if you do more than "X" calls, then calling button stops working until the page is refreshed, because of this:

51f1caa….js?meteor_js_resource=true:403 Uncaught NotSupportedError: Failed to construct 'AudioContext': The number of hardware contexts provided (6) is greater than or equal to the maximum bound (6).

**Comment by n30ngruu3n** [comment]
confirmed also in 0.52.0 
Also VideoCall wouldn't be removed from chathistory after closed the call. Still able to "enter" the empty video call...

**Comment by Shaverdoff** [comment]
0.70.0 the same bug... after jitsi video chat and webrtc channel video calls

**Comment by damian-centrone** [comment]
Cant reproduce this issue, tested on 3.9.0
