### ISSUE TITLE
[IMPROVE] Not Showing Message In Quote Section For File

### ISSUE THREAD

**Issue by nishant23122000** [RocketChat/Rocket.Chat#24591]
### Steps to reproduce:

1. Go to any room
2. Quote some messages
3. If you Quote a file then you will only see the username inside the quote section, not the file name.

### Expected behavior:

If the user quotes any file, then we should show the file name inside the quote section.

### Actual behavior:

Showing black inside quote if we mention any file.

https://user-images.githubusercontent.com/53515714/155328708-10bf31c6-bb89-4789-b1c2-02839aff0f5c.mp4

### Server Setup Information:

- Version of Rocket.Chat Server:  4.5.0
- Operating System: Windows 10
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 14.18.3
- MongoDB Version: 4.4.4

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by hugocostadev** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this was fixed in the latest releases

![image](https://user-images.githubusercontent.com/20212776/230364716-fc8bfffc-298c-4e71-a170-03aec7355821.png)

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
