### ISSUE TITLE
Unable to re-enter e2e password on mac desktop app

### ISSUE THREAD

**Issue by b1ll1ngsl34** [RocketChat/Rocket.Chat#24681]
### Description:

I am not getting prompted for my e2e password from my mac desktop client (v 3.0.0). This is causing messages to remain encrypted in some rooms.

It was working, but we recently updated/moved the server. My mobile app continues to work and so does desktop browser access (after a cookie removal).

I assume it was cached and just needed re-entry, but cannot find a way to enter it.
My Account=>Security only includes 2fa options.
I tried deleting ~/Library/Containers/chat.rocket.
I tried reinstalling the app.

### Expected behavior:

Hoped to see banner to re-enter e2e password.

### Actual behavior:

Encrypted room shows as ciphertext. No e2e password entry option.

If you can at least tell me where this information is cached, I can manually delete it.

**Comment by dudanogueira** [comment]
Hi!

Can you install the latest version directly from the .dmg? Last I heard is that we are facing some new requirements from Apple Store, and because of that, we was not able to publish new version there for now.

You can get the latest app here:

https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/3.7.8

**Comment by b1ll1ngsl34** [comment]
This fixed it, really appreciate the quick turnaround!
