### ISSUE TITLE
Omnichannel Facebook Messenger Integration seems broken

### ISSUE THREAD

**Issue by rsgodinez** [RocketChat/Rocket.Chat#24780]
### Description:

Facebook Pages are not listed, so conversations are only "complete" in rocket.chat but not in Facebook Messenger.

### Steps to reproduce:

1. Just chatting via Facebook Messenger.

### Expected behavior:

Guests can chat via Facebook Messenger.

### Actual behavior:

Guests won't receive the reply in Facebook Messenger.

### Server Setup Information:

Version of Rocket.Chat Server: 4.3.2
Operating System: Ubuntu
Deployment Method: systemd
Number of Running Instances: 1
DB Replicaset Oplog: yes
NodeJS Version: v12.22.8
MongoDB Version: 4.0.13

### Client Setup Information

Facebook Messenger

### Additional context

Seems it stopped working as expected, on March 2, 2022.

No pages listed:

![image](https://user-images.githubusercontent.com/62675312/157477472-b1c96451-e4ca-4822-87b3-27a4cb3edde5.png)

Chat is "complete" in rocket.chat:

![image](https://user-images.githubusercontent.com/62675312/157478604-aa447f4c-d404-4c51-9b66-a6d1daf9371d.png)

Chat is incomplete in Facebook Messenger:

![image](https://user-images.githubusercontent.com/62675312/157478754-949f725d-97d0-477e-baa3-d795af0be330.png)

### Relevant logs:

This log shows something related to not listing Facebook pages, so making impossible to complete the conversation:

I20220302-10:57:20.563(-6) Exception in defer callback: Error: failed [400] {"success":false,"error":{"message":"Invalid page"}}     at Object.exports.makeErrorByStatus (packages/http.js:177:10)     at Request._callback (packages/http.js:141:24)     at Request.self.callback (/home/aspel/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:185:22)     at Request.emit (events.js:315:20)     at Request.EventEmitter.emit (domain.js:483:12)     at Request.<anonymous> (/home/aspel/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1161:10)     at Request.emit (events.js:315:20)     at Request.EventEmitter.emit (domain.js:483:12)     at IncomingMessage.<anonymous> (/home/aspel/Rocket.Chat/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1083:12)     at Object.onceWrapper (events.js:421:28)     at IncomingMessage.emit (events.js:327:22)     at IncomingMessage.EventEmitter.emit (domain.js:483:12)     at endReadableNT (_stream_readable.js:1220:12)     at processTicksAndRejections (internal/process/task_queues.js:84:21) {   response: {     statusCode: 400,     content: '{"success":false,"error":{"message":"Invalid page"}}',     headers: {       'content-length': '52',       'content-type': 'application/json; charset=utf-8',       date: 'Wed, 02 Mar 2022 16:57:20 GMT',       connection: 'close'     },     data: { success: false, error: [Object] }   } }

**Comment by arrayown** [comment]
I can't even set up FB Messenger because the gateway seems to blank out. I wouldn't outsource FB Messenger to any apps and keep it native because none of the integrations seem to be on point, likely due to FB constantly changing things.

**Comment by luison** [comment]
I have a similar issue. Trying to still understand if my self-hosted installation is capable of integrating FB messenger or this is only a cloud feature. Documentation not clear to me. I understand the Facebook App con only be installed via cloud (paid) account but I was in the understanding that activating omnichannel and authorizing pages it could be integrated.

I requested and obtained the API key fairly quick (thanks Rocket Chat support), I authorize FB pages via my FB account but then get the same "No pages" error as on this first entry.

Just not sure if it's not suppose to work, or I have something missing on my setup

**Comment by luison** [comment]
Hi again. Can someone clarify or point me to any documentation. Thanks.

**Comment by wokawoka** [comment]
Has this problem been resolved?
The issue have been opened one year ago

**Comment by renatobecker** [comment]
Hey everyone! In order to give you all visibility into how we're dealing with the core FB Messenger integration, lemme share important notes here:

1) The legacy feature set has been deprecated a couple of releases back as seen on the feature doc page -> https://docs.rocket.chat/use-rocket.chat/omnichannel/facebook-messenger-managers-guide

2) The core/legacy FB Messenger integration needs a proxy/gateway to operate. The proxy sends and receives messages on behalf of end-users. Turns out, our security team came across a bunch of vulnerability issues during auditing sessions and a red flag was raised. In front of the problems that we'd need to somehow solve, we decided to officially shut down the legacy gateway as we also have another similar service that handles the communication of other social message integrations available as Apps in our marketplace, such as WhatsApp, Instagram Direct, Twitter, FB Messenger App, etc. More details can be found here https://forums.rocket.chat/t/legacy-facebook-messenger-integration-being-deprecated/16269

3) As Rocket.Chat really cares about our community, we've implemented a migration-plan for community workspaces to replace the old/deprecated FB Messenger integration with the brand new FB Messenger App available in marketplace and also benefit for even more features available in the App. Although the FB Messenger App is only available for Enterprise Customers, we're giving community workspaces access to the App for free, without any additional cost, however workspace owners must follow the instructions shared with them via email and then proceed with the App acquisition for free.

Best,

Renato Becker - Omnichannel Product Manager

**Comment by luison** [comment]
> 

Meaning that only those that somehow register to it get access to that upgrade?  
I understand the requirements of paid apps but leaving important features like these completely out of the open source community is rather dissapointing.

**Comment by renatobecker** [comment]
> > 
> 
> Meaning that only those that somehow register to it get access to that upgrade? I understand the requirements of paid apps but leaving important features like these completely out of the open source community is rather dissapointing.

The feature is not completely out of the open source community, the item #3 explains how the action plan for community workspaces to continue using not just the same, but a much better product that will continuously be improved and operating at the highest security levels. That's the real outcome and how we keep committed to deliver high quality products for all users.
