### ISSUE TITLE
Option to send messages with geo-location or just current location

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#251]
##

**Comment by engelgabriel** [comment]
Lique Facebook Messenger and WhatsApp

**Comment by kenlane33** [comment]
Geo-location would be a great feature. 
It potentially could also be used to help users find each other when they are geographically near each other or near to a geolocated channel. And who doesn't love geo-located channels? ;]
-Ken =]

**Comment by engelgabriel** [comment]
@MartinSchoeler this was not done.

**Comment by Epicanis** [comment]
Even enabling the prepending/appending of geo: URIs ( https://tools.ietf.org/html/rfc5870 ) would suffice for message geolocation, I think. Geolocated channels would be nifty, too, but I'm guessing that's slightly more involved to implement.

(I saw "geolocation" as a supported feature, spent too long trying to figure out why it wasn't working for me and where the "geolocation" feature toggle was before realizing it was really just "proprietary Google Maps support" requiring a Google Maps API key. Instead of disabling geolocation if Google Maps [or, hopefully in future, other maps providers e.g. openstreetmap] isn't available, could Rocket.Chat default to simply adding a geo: URI? Optionally, _also_ include the geo: URI even if a map is also available?)

**Comment by sampaiodiego** [comment]
we have this already
![image](https://user-images.githubusercontent.com/8591547/38094877-6bb91ab8-3345-11e8-8593-09273ee9b6bd.png)
