### ISSUE TITLE
Unread message after deleting an unread message in a thread

### ISSUE THREAD

**Issue by knordsiek** [RocketChat/Rocket.Chat#25656]
User A is sending a message within a thread
User B doesn t read the message
User A deletes the message
User B have now an unread message which not could be deleted

### Server Setup Information:

- Version of Rocket.Chat Server: 4.7.1
- Operating System: Rocky Linux 8
- Deployment Method: Stand alone
- Number of Running Instances: 2
- DB Replicaset Oplog: enabled
- NodeJS Version: v14.18.3
- MongoDB Version: 4.2.20 / wiredTiger

### Client Setup Information

- Desktop App or Browser Version: 3.8.6
- Operating System: Ubuntu 20.04 also on 22.04

**Comment by imedia3** [comment]
Same problem. We are using Snap installation.

Unread message badge visible on all devices (web/mobile/windows client), and these things didn't help: 
- Clicking "Mark Read" on a user where Unread message badge frozen
- Surfing over all available threads to be sure there is no unread message
- Reloading without cache
- Full restart of the server

**Comment by Magelo** [comment]
1. User A is sending 4 messages
2. User B do a quote reply on the 4th message from A
3. User A do a thread reply on message from user B 
4. User B do a quote reply on the 1st message from A,  was a more appropriate choice vs 4th message
5. User B delete is own message from step 2
6. User A send the reply started in step 3

I now have 1 unread message that I can't mark as read, because the thread reply is linked to a now deleted message.

and now I have this in the logs
[2022-08-04_23-43-40.pdf](https://github.com/RocketChat/Rocket.Chat/files/9265128/2022-08-04_23-43-40.pdf)

**Comment by jonathansmit** [comment]
I have the same issue. A user sent a message and then replied in a thread on the same message and subsequently deleted the whole thread before I had a chance to read it. Now the "Unread" indicator persists on both the user's name and on the thread icon for the user. This is both on web and on the app.

I have tried Shift + Esc to try and "Clear all unreads" but it doesn't work.

Any assistance in trying to clear this very annoying issue would be appreciated.

**Comment by StevenSeifried** [comment]
Seems to be fixed since Server 5.4
