### ISSUE TITLE
the "unread" attribute doesn't existe in the new version

### ISSUE THREAD

**Issue by BahrouniYousra** [RocketChat/Rocket.Chat#25740]
When I ask this api as admin to get user information:
"http://localhost:3000/api/v1/users.info?userId=BsNr28znDkG8aeo7W&fields={"userRooms": 1}"

In his rooms I got just "_id", "rid", "name" and "t" but there is no "unread" attribute :

 "rooms": [
        {
            "_id": "PoffwDEebAwcmS5A8",
            "rid": "GENERAL",
            "name": "general",
            "t": "c"
        },
             ...]
??

**Comment by dudanogueira** [comment]
Hi, we need to know more information, as requested on the open issue template.

Please, take a look on this doc in order to learn [how to ask for help](https://docs.rocket.chat/getting-support/asking-for-help)

Also, are you following any doc? can link it here for convenience?

I am closing this one, please, open a new after going thru the provided doc.

**Comment by BahrouniYousra** [comment]
Sorry for my late response, I would like to know how can I add unread property inside rooms object when I use this api "/api/v1/users.info" as administrator, it return just 

"rooms": [
            {
                "_id": "blabla",
                "rid": "GENERAL",
                "name": "general",
                "t": "c"
            }
        ]
