### ISSUE TITLE
Username problems: uniqueness, case-sensitivity, security

### ISSUE THREAD

**Issue by vinniefalco** [RocketChat/Rocket.Chat#26034]
I have observed some problems with the Username field:

1. If you try to change your Username to a string that only differs in upper/lowercase, it says "Username already exists:"
![image](https://user-images.githubusercontent.com/1503976/176004199-bab14fe6-32de-40c7-bfec-13f5d093476e.png)

2. It seems like the Username has to be globally unique. That means two people named John cannot both have the name "John" as their Display Name.

3. Because the Usernames are globally unique, and because the UI provides immediate feedback if the name is taken (see above), an attacker can probe the database to find out if particular individuals are likely to be members. This is a security vulnerability for people who want to remain anonymous. Does this respect the GDPR?

**Comment by dudanogueira** [comment]
Hi!

Thanks for your input!

The attacker would be better served if using the Directory or [it's API for that.](https://developer.rocket.chat/reference/api/rest-api/endpoints/core-endpoints/miscellaneous-endpoints/directory) :see_no_evil: 

This will all depend on the server. If it allows anonymous read/write (**ADMIN > ACCOUNT > Allow Anonymous Read or Allow Anonymous Write**), a user can interact anonymously.

If not, the user must register (if **ADMIN > ACCOUNT > REGISTRATION > Registration Form** is enabled) and will need to accept the terms and privacy policy for the server it's is registering, considering the admin should define those in ADMIN > SETTINGS > LAYOUT > CONTENT

The username needs to be unique. Just like an email, you can't have two john.doe@gmail.com or even john.Doe@gmail.com, they should be the same.

So I see no problems here, and because of that, closing the issue. Please, let me know if you have any other questions/inputs regarding this.

Thanks!
