### ISSUE TITLE
Status of cve-2022-32211 and fixed versions

### ISSUE THREAD

**Issue by cun-dp** [RocketChat/Rocket.Chat#26316]
### Description:
**This is not a bug**, but rather an inquiry about the fixes for cve-2022-32211, as announced here: https://docs.rocket.chat/guides/security/security-updates/cve-2022-32211

We interpreted the announcement to mean that the versions 3.18.7, 4.4.5, and 4.7.4 are affected by the CVE.
We are still on v3.18.7, and there is no new 3.18.x release yet.

1. Are these versions affected, or do these (and later) versions already contain the fix for the CVE?
2. If not, which RocketChat versions (will) contain fixes for cve-2022-32211? And for when is the fixed release planned?

Thank you for your time, and thank you very much for RocketChat!

### Steps to reproduce:
- not applicable

### Expected behavior:
- not applicable

### Actual behavior:
- not applicable

### Server Setup Information:

- Version of Rocket.Chat Server: rocketchat-server  3.18.7 rev 1521  
- Operating System: Ubuntu 20.04.4 LTS 
- Deployment Method:  snap
- Number of Running Instances: 1

- DB Replicaset Oplog: not applicable
- NodeJS Version: not applicable
- MongoDB Version: not applicable

### Client Setup Information

- Desktop App or Browser Version: not applicable
- Operating System: not applicable

### Additional context
- not applicable

### Relevant logs:
- not applicable

**Comment by xxxmadxxx** [comment]
Hi,

Thanks for your question, we applied the patch for the versions that we mentioned in this announcement but I highly recommend that you upgrade your instance for our latest versions since we're constantly applying patches in our product. 

We're releasing the version 5.0 now that will contain new patches for new vulnerabilities and you will see the updates in the following page: https://www.cvedetails.com/vulnerability-list/vendor_id-17468/Rocket.chat.html

As you can see in this following page https://docs.rocket.chat/getting-support we end the support for version 3.18.x in mar/2022 but for this vulnerability we have applied the patch for this version.

**Comment by ulope** [comment]
There's still no mention of CVE-2022-32211 on that page.

Doesn't exactly inspire confidence in the internal processes that a vulnerability is announced and then almost a month passes without details being made available.

**Comment by ulope** [comment]
Anyone here? Now it's a month since the announcement...
