### ISSUE TITLE
Avatar emoji in Incomming webhooks no longer work since 5.0.0

### ISSUE THREAD

**Issue by skeleton55** [RocketChat/Rocket.Chat#26374]
### Description:

The emoji or icon_emoji parameter in incoming WebHooks no longer work, neither does the Emoji option in the GUI setup of the WebHook. The message just shows the default profile picture of the "post as" user.

### Steps to reproduce:

1. Create Incoming WebHook that has the "Emoji (optional)" field set(e.g. to :ghost:)
2. Test the WebHook with a curl(or any other tool), preferably with the emoji option set

### Expected behavior:

Message appears with emoji as avatar icon.

### Actual behavior:

Message appears with default "post as" user avatar.

### Server Setup Information:

- Version of Rocket.Chat Server: Rocket 5.0.0 
- Operating System: Debian Buster
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 14.19.3
- MongoDB Version: 4.4.15

### Client Setup Information

- Desktop App or Browser Version: Tested with Firefox, chrome and desktop app
- Operating System: Win 10

**Comment by jadanah** [comment]
I have the same issue when posting a message via the api https://github.com/RocketChat/Rocket.Chat/issues/26388

**Comment by saschafoerster** [comment]
Same here.

**Comment by ivanbratovic** [comment]
This issue seems to be related to the new message template. Enabling the "Use legacy message template" setting, as explained in [this comment](https://github.com/RocketChat/Rocket.Chat/issues/26475#issuecomment-1222291767) in #26475 also fixed the avatar emoji for me.

**Comment by skeleton55** [comment]
The Option "Use legacy message template" no longer seems to work in the new update and the issue persists. So now there is unfortunately no workaround.

**Comment by saschafoerster** [comment]
@murtaza98 this is a S O S call from a quickly solved issue with a big negative impact on sharing any link on RocketChat. 🚀 PLZ help! 😇

**Comment by jadanah** [comment]
Yep 5.1.0 fails to render any messages now when I have use legacy messages enabled

**Comment by scrivna** [comment]
+1 
When provided an "emoji" value in a message object it is not rendered in the UI, the default user image is loaded. The "avatar" property (providing a url) does seem to work.

**Comment by bognerf** [comment]
Still, I'm experiencing the same behaviour with RocketChat 5.4.1 and most recent client.
When posting a message via REST API, the emoji is not rendered but the standard avatar of the posting user is displayed.
The Android app, though, behaves as expected and shows the intended emoji on a per-message basis.

**Comment by smaragd** [comment]
In the company I wok for, we have an Enterprise subscription for RocketChat with paid support. I asked the same question there in a support ticket and was told that they're "re-working the message template" and we'd have to wait for the release of RocketChat 6.0 sometime in Q1-2023 for the fix. Not the reply I was hoping for, but at last it seems to be in the pipeline.

We held back the upgrade from RocketChat 4.x to 5.x at work because of this because we make heavy use of different avatar images for incoming web hooks to classify the type of message.

**Comment by smaragd** [comment]
@pefeigl , I asked for an update in my previous support ticket last week, and their answer was to keep an eye on this pull request that deals with the broken avatar using the `emoji` property (https://github.com/RocketChat/Rocket.Chat/pull/28416), and that it will probably go into version 6.2. Since 6.1 was released today, I'm hoping that it will be soon. :crossed_fingers: :pray:
