### ISSUE TITLE
username initials

### ISSUE THREAD

**Issue by amitmeyraz** [RocketChat/Rocket.Chat#2644]
Your Rocket.Chat version: (23)
hi,
when a user name join rocket he is getting initials.
when a user use not latin letters there is no initials, just a clear coloured box.
![no init](https://cloud.githubusercontent.com/assets/5375635/14040617/f0217764-f279-11e5-81cc-5f833cfd62d8.jpg)

**Comment by MartinSchoeler** [comment]
@amitmeyraz  Thanks for reporting this issue. We value your time in helping us to make Rocket.Chat great. We always try to fix confirmed problems as quickly as we can, and it appears that the issue you reported might already be fixed in the latest release. Can you please help us test it against current latest release? Much appreciated. And please remember to backup your data before upgrading, just to be safe. Cheers!

**Comment by MartinSchoeler** [comment]
Closing this due lack of updates.
