### ISSUE TITLE
Add support for alternative Amazon S3 providers

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/Rocket.Chat#2648]
It would be great to have support for alternatives to Amazon S3 (e.g Delimiter’s ObjSpace). I have an account and active service with them and could lend out the credentials for the core team to use, in order to make it work with Rocket.Chat.
This service works fine for other programs and is for example fully compliant with `s3cmd`.

This is something I already spoke about in Rocket.Chat with some of the core team members.

**Comment by Sing-Li** [comment]
Yes. We may have to look at this sooner or later. Because not everyone can afford the (expensive!) S3.

Delimiter, along with other lower cost alternatives, will only work with the REST APIs of S3 - initiated server-side. Slingshot uses a client-side POST request that is not compatible. We can enable a server mediated upload (if the admin enables it) and support these third party object services.

**Comment by jspeigner** [comment]
What about Google Cloud Storage support since slingshot has support for it already? Cost is lower than AWS S3 at this time.

**Comment by yomura** [comment]
Did anything come of this? I am happy to setup some accounts to help people get started on it.

**Comment by k0nsl** [comment]
I just wanted to give this issue a bit of a bump in case somebody have done any tests with alternative S3 providers/solutions (e.g self-hosted `minio`).
If needed, I can provide a test instance which runs `minio` and this instance is fully operable and configured for production use on the Internet. I would have loved to be able to use that instead of Amazon S3! 😍

**Comment by k0nsl** [comment]
**UPDATE:** Alright, I am making progress. The file is uploaded from Rocket.Chat to my `minio` instance and the file isn't corrupted -- I tested by opening it and it displayed properly.

However, the file (a screenshot in PNG format) is not displayed properly in the channel. It shows up like this:
![alt text](https://k0nsl.img-cdn.ru/2017-03-02_11-59-56.png "k0nsl-failed-s3")
URL: [https://k0nsl.img-cdn.ru/2017-03-02_11-59-56.png](https://k0nsl.img-cdn.ru/2017-03-02_11-59-56.png)

When trying to click on the file in order to make it download it takes a bit of time then it begins to download and the filename is the same one which got uploaded to the `minio` instance, e.g:
```
root@relay01:~# ls /cloud01/k0nsl/k0nsl.org/GENERAL/MugJ4Cacjz2XrPWPp/
[2017-03-02 05:53:44 EST]  28KiB 9eMD6dDRAqzfAkp3u
```
...OK, hold on! I just discovered what the issue is. I had filled `CDN domain for downloads` with the functional domain of my `minio` instance -- something like `s3.domain.tld`. I just removed it and re-tried by uploading a new file....and voilá! S3-functionality is now working perfectly.
So now it uploads from Rocket.Chat to the S3 instance (powered by `minio` as you may have guessed by now, lol) and properly displays the uploaded file in the channel, like so:
![alt text](https://k0nsl.img-cdn.ru/chrome_2017-03-02_12-07-38.png "k0nsl-success-s3")
URL: [https://k0nsl.img-cdn.ru/chrome_2017-03-02_12-07-38.png](https://k0nsl.img-cdn.ru/chrome_2017-03-02_12-07-38.png)

Now I'm very satisfied ! Simply awesome. 😎

**Comment by apiontek** [comment]
I'm having a similar, but distinct issue. I just set up both minio and rocket.chat, the latter in a snap running on a linode VPS at brap.73k.us, the former running on a home server at ac3.73k.us. Both are running behind separate nginx SSL proxies.

The minio service works, I can get to my subdomain ac3.73k.us with both cli, browser, and on windows, S3 Browser. I can upload from cli, browser, and S3 Browser, and see files uploaded, and delete them.

But I must have my settings for S3 on Rocket.Chat wrong because it looks like it works, but nothing gets uploaded.

Trying to upload looks ok:
![image](https://user-images.githubusercontent.com/7383293/29147556-d1d4af18-7d35-11e7-81b3-423f841953d1.png)

It sits like that for a while, and then drops the file message into the chat as if it completed:

![image](https://user-images.githubusercontent.com/7383293/29147716-c78f5700-7d36-11e7-8c4d-9127fdd33910.png)

But the minio server shows nothing, the file doesn't actually get uploaded. Clicking the link to download goes to the minio server, with the path where it thinks it uploaded, but there's nothing there.

And I see nothing in the rocket.chat logs or Chrome console about the process.

My settings:

Bucket name: 73k.brap
Acl:
Access Key: KEYKEYKEYKEYKEY
Secret Key: SKEYSKEYSKEYSKEYSKEYSKEY
CDN domain for downloads:
Region: us-east-1
Bucket URL: https://ac3.73k.us/minio/
Signature Version: v2
Force Path Style: True
URLs expiration timespan: 0

I've tried it without Sig Ver v2 & Force Path Style, same result. I tried adding the bucket name to the end of the bucket URL, same result except the path it thinks it uploaded to has the bucket duplicated in the path.

Any ideas?

**Comment by apiontek** [comment]
on the minio nginx proxy I'm seeing a bunch of 

```
sendfile() failed (104: Connection reset by peer) while sending request to upstream
sendfile() failed (32: Broken pipe) while sending request to upstream
readv() failed (104: Connection reset by peer) while reading upstream
```

on PUT requests from the rocket.chat server. So odd though since uploads work from other clients.

**Comment by apiontek** [comment]
Nevermind. Works without minio/ on the Bucket URL. I blame my lack of familiarity with Amazon S3.

**Comment by Lawri-van-Buel** [comment]
Make sure your service is up and running and resolvable. Also why on earth would you want to run minion without tls?  Put it behind a reverse proxy with tls.

**Comment by ashepelev** [comment]
@Lawri-van-Buel as I've told before, I have reverse proxy and it works with HTTP, but with HTTPS it works only one-side (download). During uploads - I have described problems (exceptions)

**Comment by tompinzler** [comment]
Support for OpenStack Object Storage called [Swift](https://wiki.openstack.org/wiki/Swift) would also be nice. It's similar to S3 but not (always?) compatible. There are quite cheap offers out there that are half the price of S3 (e.g. from OVH).

**Comment by jhmk** [comment]
Support for S3 Accelerate Buckets would also be nice.
It makes a big performance step when you have multiple server worldwide and fix is very simple.
In the S3 Settings you just need to allow a Config for S3 Accelerate because of a different URL Scheme:
normal Rocket.Chat S3 URL:
https://BUCKET.s3.REGION.amazonaws.com

url for s3 with acceleration:
https://BUCKET.s3-accelerate.amazonaws.com/

**Comment by geekgonecrazy** [comment]
Unless specifically tried and confirmed to not work... has worked with every s3 campat object store I’ve tried.

Including minio
