### ISSUE TITLE
Discussion: Fixing bugs or adding new features, priorities?

### ISSUE THREAD

**Issue by urosino** [RocketChat/Rocket.Chat#26944]
It's clear that the Rocket.chat team is working hard to help people have a better experience using their platform.

However, with the latest releases, we can see that new bugs sometimes appear. 

Instead of fixing them in the further releases, we keep seeing more features instead.

I understand that not all issues/bugs can be taken care of, but occasionally, I get a mixed feeling about priorities between problems and features.

I wonder if anyone else has noticed this behavior, or if this is considered standard practice in the development space?

**Comment by mr-karan** [comment]
Every Rocketchat update unfortunately is a breaking and disappointing UX. There's no point in reporting issues anymore because they don't even get acknowledged (Like how I was asked to create a separate issue for [this](https://github.com/RocketChat/Rocket.Chat/issues/23638#issuecomment-1014587279) and it's been 8 months, yet to see someone [ack it](https://github.com/RocketChat/Rocket.Chat/issues/24113#issuecomment-1027653886)) 

I upgraded from 4.8x to 5.1.x and these are the issues I am seeing already (sharing here in case others are also seeing):

- Send to channel is automatically disabled after sending message in a thread.
- Messages are getting blackholed in the frontend, especially in DMs. Write a message, enter and it's disappeared. Do a full reload and the message re-appears.
- Emjois in threads are rendering as `:` in the main UI.

Old issues keep on lingering around, new features keep getting added. I really wished the maintainer team of RC took these issues a bit more seriously, despite many many disgruntled users already having pointed this out in the past in numerous GitHub issues.

**Comment by urosino** [comment]
I get similar feelings. We are an enterprise paying customer, and it looks like some newly appeared bugs are just ignored, such as:

https://github.com/RocketChat/Rocket.Chat/issues/26798

**Comment by hugocostadev** [comment]
Hi @urosino , thank you for your feedback.

We have been on a mission to improve code quality and stability by refactoring so many components into TypeScript and the focus for the next quarters is all about QA, code test coverage, and Quality.

We understand and we are so sorry for your frustrations! We are working hard to improve the product quality and deliver the fixes for all pending issues. We will be focusing more on quality instead of the new features from now on. 

We also would like to invite you to help us test all this before the releases. For that, please join our [Beta Testers program/channel](https://open.rocket.chat/channel/beta-testers)

Thanks!

**Comment by geekgonecrazy** [comment]
@mr-karan 
> Messages are getting blackholed in the frontend, especially in DMs. Write a message, enter and it's disappeared. Do a full reload and the message re-appears.

Does this happen on mobile too or just the web client?

My gut feeling here is you have an issue with either web sockets.  Or you need to check your permissions in mongo and make sure it has proper permissions for change streams to work properly.

https://docs.rocket.chat/quick-start/deploying-rocket.chat/rapid-deployment-methods/docker-and-docker-compose/docker-containers/high-availability-install#install-mongodb-replicaset

This is a good reference for what permissions to make sure you have.

---

Regarding the original item here.  As you can imagine it takes a bit of time to stop that forward momentum in the feature train.  Especially when things are in the pipeline already.

But based on all conversations I've seen and been a part of.  Both Product and Engineering definitely have their eye on quality and your thoughts and concerns definitely align with our goals.  Its just taken a bit of time to redirect the inertia :smile: 

Appreciate you taking the time to vocalize your concern with us.  :pray:

**Comment by ulope** [comment]
> We have been on a mission to improve code quality and stability by refactoring so many components into TypeScript and the focus for the next quarters is all about QA, code test coverage, and Quality.
> 
> We understand and we are so sorry for your frustrations! We are working hard to improve the product quality and deliver the fixes for all pending issues. We will be focusing more on quality instead of the new features from now on.

We've heard all this before. 
This pattern (constantly add new stuff, break old features, no response to reasonable bug / feature requests or issues just being closed without good reason) has been in evidence since the very start of the project. There are multiple fundamental UX / functionality issues that have been open for years (some since 2017)!

I even once (2 - 3 years ago probably) got contacted by some new "head of quality" or whatever (after taking part in a similar discussion) - obviously nothing has changed.

I'm getting really tired of being ignored and have largely stopped reporting bugs.
