### ISSUE TITLE
Administration > Workspace is visible for usual users

### ISSUE THREAD

**Issue by krenuser** [RocketChat/Rocket.Chat#27081]
### Description:

`Administration > Workspace` menu item is visible and available for usual users, though contents of this page are not loading:

![image](https://user-images.githubusercontent.com/32645945/196028762-99611686-b767-4af4-867c-f113b84b238f.png)

### Steps to reproduce:

1. Login as usual user on RC 5.2.0
2. Open `Administration > Workspace` menu item

### Expected behavior:

Neither `Administration`, nor `Administration > Workspace` item should not be visible to usual users.

### Actual behavior:

Menu item is visible for usual users, contents of opened page aren't loading.

### Server Setup Information:

- Version of Rocket.Chat Server: **5.2.0**
- Operating System: **Linux Ubuntu 20.04**
- Deployment Method: **docker**
- Number of Running Instances: **1**
- DB Replicaset Oplog: **Enabled**
- NodeJS Version: **v14.19.3**
- MongoDB Version: **5.0.13 / wiredTiger**

### Client Setup Information

- Desktop App or Browser Version: **Desktop 3.8.12 / Browser**
- Operating System: Windows 10

### Additional context

_none_

### Relevant logs:

No relevant logs neither in DevTools, nor on server side.

**Comment by IKrendelev** [comment]
![image](https://user-images.githubusercontent.com/103184392/196198722-e8f01d9f-178d-40dd-a320-8f5f58b7130f.png)
Found out that this behavior was caused by "Omnichannel settings" menu availability, due to `livechat-manager` role that user actually has. This item makes [ ⁞ ] ("Administration") button visible along with "Workspace" item (that shouldn't be visible).

**Comment by krenuser** [comment]
> @krenuser are you working on it?

No, I haven't set up fully functional dev environment for that yet. 
Maybe, I can take some of my future bug reports.

**Comment by nishant23122000** [comment]
ok, can I work on that?

**Comment by mani-rsg** [comment]
Hi @nishant23122000 , is this issue being worked on? if not I could work on it, please confirm

**Comment by ankar84** [comment]
> ![image](https://user-images.githubusercontent.com/103184392/196198722-e8f01d9f-178d-40dd-a320-8f5f58b7130f.png) Found out that this behavior was caused by "Omnichannel settings" menu availability, due to `livechat-manager` role that user actually has. This item makes [ ⁞ ] ("Administration") button visible along with "Workspace" item (that shouldn't be visible).

Regular user with only `user` role don't have any administrations menu.
Guess that menu comes from `bot` or one of `livechat` roles, which is bug definitely.

**Comment by rksingh2001** [comment]
Can I take up this issue?

**Comment by Barrylimarti** [comment]
Hey @dudanogueira, the livechat manager role should offer the omnichannel option in the administration menu and not the workspace option right? Doing this is failing the unit test cases created for the AdministrationModelList as the test cases are searching for workspace option always and thus,  I think the test case needs to be modified in order to solve this issue.

**Comment by dudanogueira** [comment]
hi @Barrylimarti! you are right!. 

However, before that, there are failing tests that I am not sure it is related:
https://github.com/RocketChat/Rocket.Chat/actions/runs/3393376349/jobs/5640641602#step:42:6

I have pinged our good friend @filipemarins that can help us here :)
