### ISSUE TITLE
Standardize how error messages are sent from the server

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat#2727]
Today error messages thrown from the server are not standardized. For example:

* with the [error message translated](https://github.com/RocketChat/Rocket.Chat/blob/6157e7763cb7fb3c0b068c9f67d1144383abda49/server/lib/accounts.coffee#L104)
* with a `[method]` [prefix of an untraslated message](https://github.com/RocketChat/Rocket.Chat/blob/088ac81d10eb93f7babe3385ab00655391b1cf7a/packages/rocketchat-lib/server/methods/setRealName.coffee#L4)
* with an [error code like the HTTP ones](https://github.com/RocketChat/Rocket.Chat/blob/088ac81d10eb93f7babe3385ab00655391b1cf7a/packages/rocketchat-lib/server/methods/saveSetting.coffee#L7)
* with the [error code being a translated message](https://github.com/RocketChat/Rocket.Chat/blob/ec36e66d14614f2344133ea7d4bb8e75024193e3/packages/rocketchat-file-upload/globalFileRestrictions.js#L6)
* with [only the error code](https://github.com/RocketChat/Rocket.Chat/blob/ec36e66d14614f2344133ea7d4bb8e75024193e3/packages/rocketchat-livechat/server/methods/removeTrigger.js#L4)

I propose we thrown errors like the following:

* the "error code" should be a hiphenized translatable message, like: `invalid-username`, `not-authorized`. This way our interface will take care of showing the correct translation for the error
* the error message should be written in english and being human readable. This way, any interface (other than our web interface, like REST APIs) will have a printable message

@RocketChat/core thoughts?

**Comment by engelgabriel** [comment]
I agree, just thing that erro codes code start with "error-" so they will be grouped on the i18n.json files.
Does this applies only to erros or to all messages returned to method calls?

**Comment by sampaiodiego** [comment]
To any exception thrown with Meteor.Error

**Comment by marceloschmidt** [comment]
I agree we start using "error-..." on error codes, eg. error-invalid-room. Error message should be english and without any reference to the method being called. So, instead of "[method] archiveRoom -> Invalid Room.", we should use "Invalid Room.".

**Comment by engelgabriel** [comment]
If we can pass more debug information as a 3rd parameter, I agree in removing the "[method] name ->" from the API messages.

**Comment by marceloschmidt** [comment]
We can pass a 3rd parameter. I'll add { method: 'methodName' } to the error details. Can anyone think of any other info to get into details object? eg.: `throw new Meteor.Error('error-not-authorized', 'Not authorized', { method: 'archiveRoom' })`.

**Comment by marceloschmidt** [comment]
We should define some standards, such as what error to throw when user is not logged in, or when the operation is not allowed because the user lacks permission, or when the user doesn't belong to the room, etc.

So, I vote for:

1. User is not logged in: `error-user-logged-out: The user is logged out`
2. Operation is not allowed: `error-not-allowed: Not allowed` (instead of not-authorized)
3. Not belonging to room: `error-invalid-room: Invalid room`

Any other suggestions?

**Comment by marceloschmidt** [comment]
Or maybe using proper error codes could be better.
So, instead of `throw new Meteor.Error('error-user-logged-out', 'The user is logged out', { method: 'methodName' });`, we could call `throw new Meteor.Error(403, 'Forbidden', { method: 'methodName' }); 

That would also be the case for not being allowed or not belonging to room... in whichever case, the user is **forbidden** to do that action. Any specific errors would still use the `error-*` pattern, so `error-name-is-required` would translate to `Name is required`

**Comment by engelgabriel** [comment]
I dont think http error codes are clear enough for our use cases.
