### ISSUE TITLE
critical error in 3.8.13 - 3.8.14

### ISSUE THREAD

**Issue by trash739** [RocketChat/Rocket.Chat#27400]
![221125_RC_error_ret](https://user-images.githubusercontent.com/45266374/204513825-ad134d84-84b2-4511-969d-a540bfbb2d7c.jpg)

**Comment by trash739** [comment]
It happens at Windows shutdown, always.

**Comment by dudanogueira** [comment]
Hi! Thanks for pointing it out!

You already opened an [issue here](https://github.com/RocketChat/Rocket.Chat.Electron/issues/2552), and that's the best place, as this issue is more likely to be happening on the App Client side.

However, again, without following the template. :cry: 

Consider that we cannot easily reproduce, and then fix this kind of errors without the information we required on those templates.

So, I will be close both issues, and ask you to [repoen it here](https://github.com/RocketChat/Rocket.Chat.Electron/issues/new/choose) and providing the information required.

Thanks!
