### ISSUE TITLE
showing variable name instead of text

### ISSUE THREAD

**Issue by sourav-k7** [RocketChat/Rocket.Chat#27442]
### Steps to reproduce:

1. create new account
2. try to login
3. on email confirmation page

### Actual behavior:

![image](https://user-images.githubusercontent.com/70101213/205430177-f0391d2c-28ac-461b-ae22-02d4c5e4d31e.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by raghavpatidar** [comment]
Can I work on this issue?
Please Assign it to me.

**Comment by dvnkln** [comment]
Running into the same issue. There are also some spaces missing and the footer including privacy policy etc. doesn't get replaced by our custom text anymore.

![Unbenannt](https://user-images.githubusercontent.com/33687762/206641627-1ce7abe9-cf5a-467b-95f9-d84b35669f66.png)

**Server Setup Information:**

- Version of Rocket.Chat Server: 5.4.0
- Operating System: deb11
- Deployment Method: manual
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 14.19.3 - x64
- MongoDB Version: 4.4.17

**Comment by dvnkln** [comment]
Still happening with `5.4.1` even though the changelogs hints at a fix.

**Comment by hugocostadev** [comment]
fixed by: https://github.com/RocketChat/Rocket.Chat/pull/28156

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
