### ISSUE TITLE
Open the web page,, go in, and then just do something like this ..... And then what?

### ISSUE THREAD

**Issue by cancundeyingzi** [RocketChat/Rocket.Chat#27586]
![image](https://user-images.githubusercontent.com/73635883/208689532-62c21015-30f9-4b36-9554-72f783ece8a9.png)
Open the web page,, go in, and then just do something like this ..... And then what?

**Comment by dudanogueira** [comment]
Hi!
we will need more information in order to help you.

[Please, check this docs before opening an issue.](https://docs.rocket.chat/getting-support/community-resources)

This is certainly a deployment issue, so without knowing the version, how you deployed, etc, is really hard to help you.

I will close it for now, and suggest you to check our Community Resources.

Thanks!
