### ISSUE TITLE
Room/Channel/Group Membership based on LDAP group membership

### ISSUE THREAD

**Issue by rhysxevans** [RocketChat/Rocket.Chat#2759]
Your Rocket.Chat version: 0.24.0

Hi

I would like the ability to assign membership to a Room/Channel/Group via a group in a LDAP directory. This way we can set the membership once and not update it every time someone new comes on board.

I think this would be particularly useful for Private Groups, where we have people come and go within the organization. 

Thanks

**Comment by IQ2022** [comment]
could we also have sign-ups on the front page home page. ? 
as an example we can do something like this

![image](https://cloud.githubusercontent.com/assets/12454319/14321241/6a3eb1e0-fbe6-11e5-8683-a92e58c2b755.png)

**Comment by mkretzer** [comment]
Is there any new info about this? This feature is extremely important for us...

**Comment by JT089** [comment]
*bump* We also are highly interested in this feature

**Comment by PPPBerlin** [comment]
This would be awesome! +1

**Comment by teha75** [comment]
+1

**Comment by JigSawFr** [comment]
+1

**Comment by amaranto** [comment]
+1

**Comment by monspid** [comment]
+1

**Comment by nicofreaksout** [comment]
+1

**Comment by diegoluisi** [comment]
+1

**Comment by jvacek** [comment]
+1

**Comment by christianprim** [comment]
+1

**Comment by engelgabriel** [comment]
Hi all, can you please share with us your use cases so we can start planing how to best design this feature? @mrsimpson @JSzaszvari do you have some use for this feature too?

**Comment by engelgabriel** [comment]
@TheReal1604 do you also use LDAP on your deployment?

**Comment by TheReal1604** [comment]
Yes, since yesterday.  @engelgabriel

**Comment by mkretzer** [comment]
We have a rather big callcenter. When there is new staff or staff gets sent to new teams  (which happens quite often) all the permissions are given via LDAP groups. We also have chat groups for every team. Adding / removing staff from the groups would mean much work if we need to do this with every staff member manually...

**Comment by TheReal1604** [comment]
Yes, it’s a bit manually at the moment. We resolve this with a content / user administrator for the important channels.

**Comment by jvacek** [comment]
XWiki has a decent implementation for this via their plugin called LDAP Authenticator.
An XWiki group (or a rocket chat room in this case) can have an LDAP query associated with it, or simply an AD OU or a Group membership.
When a user logs in, all of these conditions are checked, and groups are allocated. I think the entire AD is also re-checked for all the existing users every user-defines amount of hours, in cases there’s been any changes.
For us, we would like to map departments with approx 100 users each to an announcement room (mapped using OUs), as well as small project groups to open rooms for approx 12 users (mapped using group memberships).
It would also be nice to associate permission groups to allow domain admins (group memberships) to automatically get admin privileges.

**Comment by christianprim** [comment]
We use Rocket.Chat at our school. Every class needs a room. It would be wonderful, if we could fill the room automatically from our LDAP-Groups (every student belongs to a ldap-group for his class). If a student has to change class, it would be nice, if he would chage room automatically. That's our use case.

**Comment by mrsimpson** [comment]
@engelgabriel we’re not using LDAP in RC at all, since the maintenance of groups via the ldap UI is way more complicated. Thus, I cannot provide more ideas or practices here. Still, I believe this was a useful feature for many

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by janrenz** [comment]
We would also like to use it for schools. every class has a room, plus every school has a room. it should support multiple schools in one instance.

**Comment by kremer-io** [comment]
+1

**Comment by kamilzadora** [comment]
+1

**Comment by hannoterhaseborg** [comment]
+1

**Comment by semperor** [comment]
+1

**Comment by eliasp** [comment]
I think the following approach would make sense:

- Expose per channel admin UI options, which allow to define the requirements for the LDAP-based channel membership
  - **LDAP Group:**
    - **simple mode:** allows to define the group DN (leaves figuring out the required search filter to RocketChat internally) 
    - **advanced mode:** allows to define a custom search filter
  - **Mandatory Join:** `true`/`false` - either forces all users of the defined AD group to join the channel or otherwise allows them to join the channel if they want to
  - **Open Membership:** (available when **Mandatory Join** is `true)`: `true`/`false`: allows further users besides just those matched by the LDAP filter to join the channel, to realize setups where the group is used to enforce a mandatory channel membership, but should also allow further users to join this channel on their own

Regarding the LDAP search filter, there are a few things which should be taken into account:

In case the LDAP is a Microsoft AD, an [`ExtensibleMatch`](https://ldapwiki.com/wiki/ExtensibleMatch) filter using a forward-lookup `memberOf:1.2.840.113556.1.4.1941:=(CN=group-foo,ou=department,dc=company,dc=tld)`-style filter should be used which is far more performant in case it is supported.

In case of an LDAP setup not providing those capabilities, a traditional `(&(objectClass=posixGroup)(memberUid=%s))` has to be used which doesn't resolve nested groups - this would require additional effort (which would be fantastic to have :smile: ).

Regarding the "LDAP Type" it could be either configured globally or alternatively determined during runtime by attempting an `ExtensibleMatch` lookup first and fall back to a regular filter in case of failure.

**Comment by haperu** [comment]
I'm in the edu environment, too. Due the yearly class changes, this feature is a must-have for us, too.
-> +1
:)

Thanks

**Comment by ChrissW-R1** [comment]
We need this feature, too. But it would much better, if we could use Atlassian Crowd, which shades our OpenLDAP.

**Comment by haperu** [comment]
And - as I'm just in "demanding mode* :grinning: 
Please think of the leaver-changer-mover issues in general!

**Comment by nemhods** [comment]
If anyone is desperate for this feature and **not running in any kind of production environment**, i threw together a quick-and-dirty python script to sync LDAP users to channels/rooms using the REST API:
https://github.com/nemhods/rc-ldap-sync

**Comment by andyhoffman12** [comment]
So typically at my business employees are given AD Security groups that dictate their access to some system or file share. Typically a user is a member of corp-SG-Engineering or corp-SG-Sales.
In some cases i'll make custom security groups for an app like corp-SG-RocketChat-Allowed or corp-SG-RocketChat-Engineering, corp-SG-RocketChat-Announce, corp-SG-RocketChat-Office, corp-SG-RocketChat-Shop

I'm likely to nest the Rocket Chat groups into an employee's department security group. 

I'd like to force members of specific security groups to specific rooms. I also don't specifically want users to be able to join any of these department level rooms. I however wouldn't mind some free join of other rooms for sub groups like Marketing-Sales....

**Comment by Zegorax** [comment]
Is there any news about this feature ? It would be really useful for our company.

**Comment by wreiske** [comment]
Pull request is in: https://github.com/RocketChat/Rocket.Chat/pull/14278
