### ISSUE TITLE
Sometimes LiveChat inquiries generate Push notifications to incorrect users

### ISSUE THREAD

**Issue by didacroyo** [RocketChat/Rocket.Chat#27605]
### Description:

New Livechat inquiries created with ['/api/v1/livechat/room' API endpoint](https://developer.rocket.chat/reference/api/rest-api/endpoints/omnichannel/livechat-endpoints/livechat-room/livechat-room-info) and assinged to the corresponding department using ['/api/v1/livechat/room.transfer'](https://developer.rocket.chat/reference/api/rest-api/endpoints/omnichannel/livechat-endpoints/livechat-room/livechat-room-transfer) sometimes (not always) generate incorrect push notifications. Push notifications are generated (and sent) to mobile and desktop livechat-agents, who are online, but are not members of the department.

### Steps to reproduce:

1. New livechat conversation is created using API /api/v1/livechat/room
2. Livechat conversation is assigned to a particular department 'X' using API /api/v1/livechat/room.transfer

### Expected behavior:

A livechat agent with status = 'online' **who does not belong to that department 'X'** does not receive a push notification when the new message is available to be taken in the livechat department 'X'

### Actual behavior:

A livechat agent with status = 'online' **who does not belong to that department 'X'** sometimes (not always) receive a push notification of incoming livechat conversation.

### Server Setup Information:

- Version of Rocket.Chat Server: 5.3.5
- Operating System:  Ubuntu Server
- Deployment Method: docker
- Number of Running Instances: 2 
- DB Replicaset Oplog: Enabled
- NodeJS Version:  v14.19.3
- MongoDB Version: 5.0.13 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: not relevant
- Operating System: not relevant

### Additional context

- Have custom mobile app
- Have 2 rocketchat instances in a dockerized environment
- API integration to create new livechat inquiries is production more than 2 years.
- We have tested removing roles 'admin' and 'livechat-manager' and the issue still appears from time to time.
- "Use REST instead of websocket for Meteor calls" switch: disabled

- Maybe related to [realtime-api/subscriptions/stream-notify-user](https://developer.rocket.chat/reference/api/realtime-api/subscriptions/stream-notify-user) (is it possible that when a user has access and visits a particular livechat conversation this triggers some kind of subscription to changes with the corresponding notifications?) ?

- Maybe related to [inquiries.queuedForUser](https://github.com/RocketChat/Rocket.Chat/pull/27086) ?

### Relevant logs:

not relevant

**Comment by dudanogueira** [comment]
Hi! Thanks for poiting it out.

Does this happens if you [register the visitor already with the department](https://developer.rocket.chat/reference/api/rest-api/endpoints/omnichannel/livechat-endpoints/visitor/register-a-new-livechat-visitor)?

Also, just noted that this parameter is not documented [yet it is allowed](https://github.com/RocketChat/Rocket.Chat/blob/50b252b4d26961cb3e99e641ba2ca9667bff4bfe/apps/meteor/app/livechat/server/api/v1/visitor.ts#L19)

I believe that, while creating a room without a department, it might trigger some other user or manager, as a fallback. So defining a department from the beginning may solve this, as RC will know exactly what department agents to notify.

Let me know if this helps. I will update the API Docs to reflect all their arguments.

**Comment by didacroyo** [comment]
Thanks Duda!  we'll try it and let you know!

**Comment by didacroyo** [comment]
Hi Duda, we applied the fix as per your suggestions and after a week in production I can confirm the issue disappeared. Thank you very much.
