### ISSUE TITLE
Rocket Chat Automation using Pabbly

### ISSUE THREAD

**Issue by OBI-Bella** [RocketChat/Rocket.Chat#27804]
Hi Team,

I am creating automation for RocketChat, that if there's new data added in the Google Sheet, a Notification will be sent to RocketChat using Pabbly Connect. An account is already connected to RocketChat, the Action event is "Send Private Group Message (Without Bot Image)". Under the dropdown, Private Group, I can't find the Private Group that I need to send the notification to. I am an Admin of the workspace btw.  I checked all the groups under that Dropdown, and I can see the groups that were created by me and the other Admin. However, I can't find the group that I need to send the notification.

Do you have any suggestions or ideas about why this happens?

Thank you,

**Comment by dudanogueira** [comment]
Hi! Please, fill in the template so we can better help you. This is more a support request, that deals with a third party service than a Rocket.Chat issue.

Here are some guide on how to better use our Community Resources: 
https://docs.rocket.chat/getting-support/community-resources

I suggest that you increase the log verbosity, and monitor it in order to understand what APIs they are consuming in order to get the channel list.

I will close this issue for now. Please, feel free to [create a thread in our forum](https://forums.rocket.chat/) so we can continue debugging this.

Thanks!
