### ISSUE TITLE
@ autocomplete also match on Name

### ISSUE THREAD

**Issue by giray** [RocketChat/Rocket.Chat#2785]
Your Rocket.Chat version: 0.24.0

Currently autocomplete when mentioning a user via '@' only matches usernames.  It would be great if the lookup would also take into account the "Name" of the user.

**Comment by pescobar** [comment]
this was working in previous versions but since version 0.25.0 I have also noticed that autocomplete stopped working on "name" and only matches "username"

it would be nice to get the previous behaviour back when autocomplete works for bot "name" and "username"

**Comment by pescobar** [comment]
is there any plan to get this feature back?

**Comment by pescobar** [comment]
@engelgabriel is there any plan to get this feature back? It was working with previous releases and it was really convenient

**Comment by engelgabriel** [comment]
Yes, we will bring the full names back as an option to be used across the whole system, to display everywhere instead of usernames.

**Comment by pescobar** [comment]
thanks @engelgabriel . This would be really useful for us. 

In our rocket chat instance we use ldap for authentication and we automatically assign the ldap uid as rocketchat username. The problem is that ldap uid is not always descriptive enough to know who is who in the rocketchat channels. Being able to autocomplete also on name (which we also get automatically from ldap) is really convenient in our setup.

**Comment by Mte90** [comment]
Any news for that? is an important feature that broke the UX

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

I cannot confirm this to be true in 0.61.0. I just verified that I can mention `thotest` which is my LDAP handle as well as my username, which is `thomas.test`. Also independant of case. If you still see this, please describe all the surrounding aspects, maybe post a screenshot of your profile and a little GIF of you trying to mention yourself.

Cheers
Thomas
