### ISSUE TITLE
LDAP - user field map - gather name from multiple LDAP fields

### ISSUE THREAD

**Issue by pandel** [RocketChat/Rocket.Chat#2816]
Hi!

Would it be possible to extent the user field map to let the name (not the username used for login) to be constructed out of multiple LDAP fields? We don't have some kind of "fullname" field in our AD configuration, but "givenName" and "surname". So we'd like them to be combined to the full name.

I tried combinations like this, but it surely didn't work:
{"givenName sn":"name", "mail":"email"}
{"sn, givenName":"name", "mail":"email"}

Also, it would be nice if it could be made configurable, that the menu should show this name besides the avatar (and not the login username) and be used for user name search as well, as we have really cryptic LDAP logins, so the person's real name would be much easier to identify during a conversation and search for.

Besides keep up the amazing work! It's such a lovely piece of software working flawlessly so far!

Regards,
Holger

**Comment by ChanningMorris** [comment]
What version are you on?  I've only played with 0.24 and 0.25, but pretty much everything you've listed there is something I'm doing with it already.

**Comment by pandel** [comment]
I'm on current git version. How do you do it???

**Comment by ChanningMorris** [comment]
In our LDAP, the unique key is employee number which is in our LDAP as sAMAccountName, but employee number is virtually useless to anyone besides that employee.  It's only used for login.

So in the LDAP settings, I have sAMAccountName for "Domain Search User ID".  For the LDAP setting "Username Field", I have #{givenName}.#{lastName} - this generates everyone's user name (the one displayed in chat) as "given.last" using their given and last names from LDAP.

And then for "Unique Identifier Field" I put "mail" so email address is shown in the person's details instead of their employee number since our email addresses aren't always obvious from the person's name due to people having the same name and whatnot.

**Comment by pandel** [comment]
Wow! Many thanks! I did not know that something like "#{givenName}.#{lastName}" is possible. Is there some kind of documentation somewhere, where I can see how to build these field combinations?

**Comment by ChanningMorris** [comment]
Honestly, I only know you can do that because right under the text box for the "Username Field" setting it says

Which field will be used as *username* for new users. Leave empty to use the username informed on longin page.
You can use template tags too, like `#{givenName}.#{sn}`.
Default value is `sAMAccountName`.

**Comment by pandel** [comment]
Ah ok! My german translation doesn't include these information.

Right at the moment I tried the following, but it doesn't work:

{#{givenName}.#{sn}:"name", "mail":"email"}

How did you write the field content exactly?

**Comment by ChanningMorris** [comment]
I believe the syntax is just #{ldapFieldName} with whatever punctuation you want around it.

So if you want the LDAP field "givenName" and the LDAP field "sn", it would just be "#{givenName}.#{sn}" and you can replace the "." between them with whatever you wish.

**Comment by pandel** [comment]
Yes, thanks! As I thought, this is only possible in the username field, but not valid for the user data mapping field.

**Comment by ChanningMorris** [comment]
If it helps, here's the "User Data Field Map" help text:

Configure how user account fields (like email) are populated from a record in LDAP (once found). 
As an example, `{"cn":"name", "mail":"email"}` will choose a person's human readable name from the cn attribute, and their email from the mail attribute.
Available fields include `name`, and `email`.

**Comment by pandel** [comment]
Thanks again!

What I did not know is that the username you actually use for the login page is somewhat different from the _username field_. So what I did now was to configure sAMAccountName for login user search and #{givenName}.#{sn} for the _username field_!

Works absolutely great! Many thanks for pushing me in thew right direction!
