### ISSUE TITLE
App crashes on toggling between the themes modes

### ISSUE THREAD

**Issue by Pheewww** [RocketChat/Rocket.Chat#28174]
### Description:

On changing the themes modes, the app crashes.

### Steps to reproduce:

1.  open desktop app
2.  open left menu 
3. change themes modes

### Expected behavior:

light modes should change

### Actual behavior:

[Recording_1677397505713.webm](https://user-images.githubusercontent.com/67512605/221398701-3d92bdf8-186e-4489-90d3-5045c5694f1e.webm)

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: desktop app
- Operating System: win 10

**Comment by Pheewww** [comment]
Inspecting the event handlers that are triggered when the theme modes are changed can be a way to correct this. Pls assign this issue to me.

**Comment by dudanogueira** [comment]
Thanks for all you efforts!! 

However...

This was fixed and already merged in https://github.com/RocketChat/Rocket.Chat/pull/28161

As you can see, there is a lot going on when it comes to 6.0.0 issues/regressions. Our team is working non stop to make it ready to release.

Please, instead of going ahead and producing PRs, take your time and align, specially if the issue was introduced in 6.0.0

I'll close this for now, but please, consider that we really appreciate all your interest and efforts!
