### ISSUE TITLE
Automatic translation has a bug

### ISSUE THREAD

**Issue by JakeGi** [RocketChat/Rocket.Chat#28232]
web端，自动翻译显示不出来

**Comment by JakeGi** [comment]
On the web side, the automatic translation cannot be displayed

**Comment by hugocostadev** [comment]
Sorry, you need to give more information, follow the Issue template

**Comment by meinrecht** [comment]
I created this issue a while ago: maybe you could check, if yours is the same:
#27949

**Comment by hugocostadev** [comment]
This was fixed in this PR: https://github.com/RocketChat/Rocket.Chat/pull/27317. 
Could you try to update it to our [latest release 6.0.0](https://github.com/RocketChat/Rocket.Chat/pull/28345) and let us know? 

If you still face this issue, please, reopen it and provide us with more info about the server and browser, and providers

Thanks a lot for contributing
