### ISSUE TITLE
[BUG] Showing undefined Instead of RocketChat Logo on Footer-SideNav in Dark Mode

### ISSUE THREAD

**Issue by Nabhag8848** [RocketChat/Rocket.Chat#28282]
### Description:
- When using darkmode on the top bottom left (side nav bar footer) there is problem rendering the brand logo there should be brand logo but it shows undefined in the version of rocketchat in which open rocketchat server is running.

### Steps to reproduce:

1.  Go to Open Server RocketChat
2.  Click on Dark Mode
3.  See on the top bottom left.

### Expected behavior:
- RocketChat Logo

### Actual behavior:
- Showing Undefined

### Screenshot / Video: 

![LogoNotRendered](https://user-images.githubusercontent.com/65061890/222978493-6a3556ea-d02d-4784-b171-256a9fa5c5a1.gif)

**Comment by AdityaSingh-02** [comment]
hey @Nabhag8848 i was able to reproduce this bug in the latest official release but i am not facing any such issue on the 6.0.0-develop 
![dark](https://user-images.githubusercontent.com/94185167/223042431-0cd6ef07-0611-4e21-85cf-de2584d03562.png)

**Comment by chinma-yyy** [comment]
Hey so the issue is in serving the ```logo_dark.png``` file to the client .
### You can see here that when the server is run locally the assets directory has the ```logo_dark.png``` file

![Screenshot from 2023-03-06 14-51-54](https://user-images.githubusercontent.com/112387862/223069718-6253f6fe-3dd4-4763-8d04-6dfc195027e7.png)

### But on the Open Rocket chat server the file is not getting served so it cannot load it and is sending the undefined response

![Screenshot from 2023-03-06 14-52-21](https://user-images.githubusercontent.com/112387862/223069477-5ec99223-710b-4401-9922-b1ad1d37c413.png)

The file exists but is not getting served to the client you can verify it [here](https://open.rocket.chat/assets/logo_dark.png)

I tried to resolve it but couldn't. Thank you!

**Comment by Nabhag8848** [comment]
<div align="center">
    <img src="https://user-images.githubusercontent.com/65061890/223355684-5679c3c0-efd9-4852-b2b9-2381f569cd23.png">
</div>
- I see now this issue has been solved closing it. there would be an internal discussion about changing the logo color thus, was showing undefined previously. Thanks all who were part of this discussion.
