### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by chiragnahata** [RocketChat/Rocket.Chat#28353]
I am unable to install Rocket Chat on docker - Deployment error
failed to deploy a stack: time="2023-03-10T08:13:43Z" level=warning msg="The \"REG_TOKEN\" variable is not set. Defaulting to a blank string." Network chat_default Creating Network chat_default Created Container chat-mongo-1 Creating Container chat-mongo-1 Created Container chat-rocketchat-1 Creating Container chat-mongo-init-replica-1 Creating Container chat-rocketchat-1 Created Container chat-hubot-1 Creating Container chat-mongo-init-replica-1 Created Container chat-hubot-1 Created Container chat-mongo-1 Starting Container chat-mongo-1 Started Container chat-rocketchat-1 Starting Container chat-mongo-init-replica-1 Starting Container chat-mongo-init-replica-1 Started Container chat-rocketchat-1 Started Container chat-hubot-1 Starting Error response from daemon: driver failed programming external connectivity on endpoint chat-hubot-1 (d9eb8c2873d08cc89240ba57db9a62106c41cc3ce81dd7911d7361e3a203e6b9): Bind for 0.0.0.0:3001 failed: port is already allocated

I am using https://raw.githubusercontent.com/TheLustriVA/portainer-templates-Nov-2022-collection/main/mlva-templates-2.0-deduped.json template

**Comment by chiragnahata** [comment]
It is showing 
![image](https://user-images.githubusercontent.com/63905783/224302227-e7c51600-0697-4772-a53f-20c89d94983e.png)
But then also not accessible

**Comment by chiragnahata** [comment]
https://desk.rocket.chat/portal/en/ticket/413244000101003237

**Comment by dotty37** [comment]
Hi Chirag,, do you have specific requirements for using a json template? Have you tried with a yml file and docker composer? I have a composer file that launches Mongo, Traefik, and Rocket, you just need a domain name.

**Comment by chiragnahata** [comment]
> Hi Chirag,, do you have specific requirements for using a json template? Have you tried with a yml file and docker composer? I have a composer file that launches Mongo, Traefik, and Rocket, you just need a domain name.

I am having the domain name. Can you please help me set up Rocket chat. I tried with the yml file given in the documentation please it is not working for me. It would be great if you can help me. Mine is Oracle Free Tier arm based Ubuntu vm. Please help

**Comment by dotty37** [comment]
Ok,, here is my compose.yml file, it works with Traefik instead of nginx, but you can launch, see how it works and use it as template for nginx later.
Im running on CentOS 7, but if you work on any Linux with Docker.
As minimum, you will need:
1- A domain name
2- An email address
3- Firewall open to ports 80 and 443 (port 8080 is for the Traefik Dashboard, and should be allowed only internally, or at least from trusted IP addresses)

Just replace INSERT_DOMAIN_HERE with your domain and INSERT_EMAIL_HERE with your email.
Respect the quote marks, if they are on the yml file, leave them, if they are not, then dont add them. 

There is a setting for using a test SSL from lets encrypt, I recommend you use this at the beginning and intent to launch, delete, launch delete, etc, because if you use Production SSL (the default on this yml file) lets-encrypt might throttle you and stop issuing SSLs.
I hope this helps you.

`volumes:
  mongodb_data: { driver: local }

services:
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:6.0.1
    restart: on-failure
    labels:
     traefik.enable: true
     traefik.http.routers.rocketchat.rule: Host(`INSERT_DOMAIN_HERE`)
     traefik.http.routers.rocketchat.entrypoints: http
     traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
     traefik.http.routers.rocketchat.middlewares: redirect-to-https@docker
     traefik.http.routers.rocketchat-secured.rule: Host(`INSERT_DOMAIN_HERE`)
     traefik.http.routers.rocketchat-secured.entrypoints: https
     traefik.http.routers.rocketchat-secured.tls: true
     traefik.http.routers.rocketchat-secured.tls.certresolver: le
    environment:
      MONGO_URL: mongodb://mongodb:27017/rocketchat?replicaSet=rs0
      MONGO_OPLOG_URL: mongodb://mongodb:27017/local?replicaSet=rs0
      ROOT_URL: http://INSERT_DOMAIN_HERE
      PORT: 3000
      DEPLOY_METHOD: docker
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
  mongodb:
    image: docker.io/bitnami/mongodb:4.4
    restart: on-failure
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_PORT_NUMBER: 27017
      MONGODB_INITIAL_PRIMARY_HOST: mongodb
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: 27017
      MONGODB_ADVERTISED_HOSTNAME: mongodb
      MONGODB_ENABLE_JOURNAL: true
      ALLOW_EMPTY_PASSWORD: yes
  traefik:
    image: docker.io/traefik:v2.9.8
    restart: unless-stopped
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --certificatesresolvers.le.acme.email=INSERT_EMAIL_HERE
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      # This line below is to get a testing SSL cert, just uncomment it and thats it.
      #- --certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
    ports:
     - 80:80
     - 443:443
     - 8080:8080
    volumes:
      - ./letsencrypt:/letsencrypt:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro`

**Comment by dotty37** [comment]
Ok,, here is my compose.yml file, it works with Traefik instead of nginx, but you can launch, see how it works and use it as template for nginx later.
Im running on CentOS 7, but if you work on any Linux with Docker.
As minimum, you will need:
1- A domain name
2- An email address
3- Firewall open to ports 80 and 443 (port 8080 is for the Traefik Dashboard, and should be allowed only internally, or at least from trusted IP addresses)

Just replace INSERT_DOMAIN_HERE with your domain and INSERT_EMAIL_HERE with your email.
Respect the quote marks, if they are on the yml file, leave them, if they are not, then dont add them, same with parenthesis.

There is a setting for using a test SSL from lets encrypt, I recommend you use this at the beginning and intent to launch, delete, launch delete, etc, because if you use Production SSL (the default on this yml file) lets-encrypt might throttle you and stop issuing SSLs.
I hope this helps you.

[https://github.com/dotty37/rocketchatyml/blob/f494743b6b01a9f5539c8376aef69ec68916d450/compose.yml](url)

**Comment by hugocostadev** [comment]
Hi there, thanks for raising the issue! 🚀 💯 

Sorry, but GitHub is only for issues/bugs related to the repository project.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
