### ISSUE TITLE
LDAP authorization

### ISSUE THREAD

**Issue by marat2222** [RocketChat/Rocket.Chat#28381]
Good afternoon, tell me how to set up authorization via AD, I have a domain tree, how do I make all the users from subdomains work! if you specify the upper domain, then only users from the upper domain work!

**Comment by dudanogueira** [comment]
Hi! 

Please, before opening an issue, read this:
https://docs.rocket.chat/getting-support/community-resources

This is not an issue :( but a question on how to properly configure LDAP.

You'll need to figure out the correct query in order to limit what users you want authenticating. You can use some ldap tools for that.

I'll close it for now, but feel free to ask for help both on our [forums](https://forums.rocket.chat/) and [community support channel](https://open.rocket.chat/channel/support)

Thanks!
