### ISSUE TITLE
Should be able to access privated apps on free edition

### ISSUE THREAD

**Issue by juzser** [RocketChat/Rocket.Chat#28409]
### Description:

I see RC moving the marketplace and public apps as enterprise features.
But we've been using RC for years, and have some privated apps that have been developed by us or we hired some freelancers to build, but now I see we cannot access those apps.

I think that's not fair, I agree with the marketplace as an enterprise feature, but with private apps, that does not make sense.
I hope RC should consider and bring it back soon.

**Comment by yash-rajpal** [comment]
Hey @juzser! You need not worry about your private apps that you were using before 6.0.0 release, we have implemented a grandfathering policy (more news will follow in upcoming days) for community workspaces, under which workspaces can continue to use private apps which were installed before new release, so it should not be any problem for your case.

Also going forward new community workspaces will be allowed upto a maximum of 3 private apps, so you can continue to use your private apps even on new installations.

Since the GitHub is only for issues, If you still have some doubts or want to discuss more it, please
- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
OR
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there.

Thanks!

**Comment by juzser** [comment]
Ok so there are 2 issues (1 critical) with the private apps in 6.0.0
1. There is no navigation item to navigate to private apps page if you're free workspace. I have to access via finding the url in browser history. 
2. When I tried to save the settings of an private app, there is a critical issue when the server's CPU gonna 100%, and the workspace crashed. Anytime I go to marketplace or private app page, the CPU is running high, and after settings, it's crashed.
And beside that, after save the settings, the settings page is also gone...
