### ISSUE TITLE
[Feature Request] React by clicking an emoji

### ISSUE THREAD

**Issue by CarrollDiehl** [RocketChat/Rocket.Chat#28412]
Hi,
while using Rocket.Chat I had an idea for a simple but handy feature for reaction polling.
Usually, when I create polls, I react with all polling options in advance, so noone has to go through all emojis and search for the one used for their favourite option. This is sometimes unhandy because it (1) creates extra steps, (2) 'inflates' the votes and (3) makes me unable to vote in the poll myself.
So I wondered, if it could be implemented, that a simple click on an emoji used in the message could add it as a reaction to the post. This would be a quite elegant way to solve it.
It might lead to some unintended reactions, but since you can simply clear them with a second click, I don't see this as a major problem. 

What do you think?

Best regards and thanks for the great application
Carroll

**Comment by hugocostadev** [comment]
Hey @CarrollDiehl , since we don't support polls by default I don't think we can create this feature. But this is a good scenario for creating an app for it your own needs! 

By the way, we already have some apps for polls in our marketplace, check it out:
https://www.rocket.chat/apps/poll-plus
https://www.rocket.chat/apps/poll

**Comment by CarrollDiehl** [comment]
Thanks for the hint, we actually have poll-plus installed on the instance I am using. Great! (:
