### ISSUE TITLE
start call

### ISSUE THREAD

**Issue by godlikewangjun** [RocketChat/Rocket.Chat#28439]
### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by yash-rajpal** [comment]
Hey @godlikewangjun! This issue is kinda fixed in the new 6.0.0 release. We only show call action on user card if the DM with the other user already exists. If you remove create-d permission then it won't allow users to create dms and won't show the call action.

I hope this helps. I will close this issue for now and I will ask you to check this on latest release or on our open server, I will also initiate a conversation with the appropriate team to check if we can improve this behavior. 

Thanks for reporting, feel free to reopen if you have more concerns.
