### ISSUE TITLE
Jitsi not enabled

### ISSUE THREAD

**Issue by neverh8me** [RocketChat/Rocket.Chat#28594]
### Description:

Jitsi not enabled after update

### Steps to reproduce:

Go to Setting -> Marketplace -> Installed -> Jitsi (disabled)

### Actual behavior:

If you click on enable - nothing changes and the module is turned off

### Server Setup Information:

- Version of Rocket.Chat Server: 6.0.1
- Operating System: Rocky Linux 8.7
- Deployment Method: docker
- Apps Engine Version: 1.37.1
- NodeJS Version: v14.21.2
- MongoDB Version: 5.0.15 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App and Browser in any OS

### Additional context

If we click on a call in personal messages or in the channel - a message is displayed about the absence of any communication modules
![photo_2023-03-24_14-04-30](https://user-images.githubusercontent.com/36151767/227516547-3d12e56e-5ed7-4433-ae01-1bbb84edca0e.jpg)

**Comment by jacotec** [comment]
Same here ... any apps are disabled after update to 6.0.1 :-(

Did you find a solution?

**Comment by mlongmiresqa** [comment]
Uninstalling and reinstalling Jitsi fixed the issue for me.

**Comment by hugocostadev** [comment]
Yep, if you uninstall this and install again should work, also just check if you have the provider Jitsi selected in settings

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by TipiT** [comment]
Reinstall didn't solve my issues. I'm just set up the hosted version and tried to set Jitsi.

![not-working](https://user-images.githubusercontent.com/1223414/232464082-5724f169-a193-4860-94df-ce4d7e7a2971.png)

I tried 1:1 calls and group calls and different configurations, but the service is not there. Because it loses the setting in here: ![jitsi-not-there](https://user-images.githubusercontent.com/1223414/232464208-d53cafe2-e307-46d5-986f-5e85bbde57fa.png)


Here it doesn't find Jitsi before refresh of the browser page, then I can choose Jitsi as a provider, but the calls don't work.

I also could see the settings before, meaning before reinstalls, but not anymore.

![settings-vanish](https://user-images.githubusercontent.com/1223414/232463946-a823a4cd-d14f-44d6-a55f-902b4e4361d0.png)

I tried to set the configuration in Chrome, Firefox, and Desktop app and the behavior is the same.

The most ironic thing is that it actually worked the very first time ONCE.

![worked-once](https://user-images.githubusercontent.com/1223414/232463822-f4afe354-7e81-412b-ad64-94f147157ae3.png)
