### ISSUE TITLE
username already in use bug

### ISSUE THREAD

**Issue by eolynyk** [RocketChat/Rocket.Chat#288]
works fine on localhost, but once deployed to meteor.com, I keep getting an error like 

REGISTER USERNAME
The username is used to allow others to mention you in messages.
eve988886 is already in use :(

No matter which username, the same bug keeps popping up.

http://eve-fcc3.meteor.com/home

**Comment by rodrigok** [comment]
Hi @eolynyk. Unfortunately the meteor.com use mongodb 2.4 and we are using APIs that only exists in mongodb 2.6+

The problem is related with $sort with $each (https://github.com/RocketChat/Rocket.Chat/blob/fd7c3b7bd7b4e3553c493ee31f557ea186a7befb/server/methods/setUsername.coffee#L24)

We are thinking how to solve this problem.

**Comment by sampaiodiego** [comment]
duplicated of #259
