### ISSUE TITLE
Windows Firewall blocking Conferencing without errors

### ISSUE THREAD

**Issue by jhiswin** [RocketChat/Rocket.Chat#2880]
Your Rocket.Chat version: (make sure you are running the latest)
//demo.rocket.chat

I've had this replicated on a couple new computers (in China).
Most likely due to 360safe enforcing strict firewall rules.

No errors are shown, and no incoming conferencing requests pop up.
If you initiate a group conference, you only see yourself and nobody else can connect to you (although others will see the request).

If this can't be solved, it would be better to at least have an error pop up.
Better would be to give a troubleshooting error message recommending changing firewall settings, and a KB support request.

**Comment by MartinSchoeler** [comment]
@jhiswin  Thanks for reporting this issue. We value your time in helping us to make Rocket.Chat great. We always try to fix confirmed problems as quickly as we can, and it appears that the issue you reported might already be fixed in the latest release. Can you please help us test it against current latest release? Much appreciated. And please remember to backup your data before upgrading, just to be safe. Cheers!
