### ISSUE TITLE
Secret URL Registration: logo is missing

### ISSUE THREAD

**Issue by doctorlard** [RocketChat/Rocket.Chat#2897]
Latest stable tgz. I suspect the defaultUrl for logo.svg should have a leading slash (currently missing), in programs/server/packages/rocketchat_assets.js
Or, there needs to be an allowance that the registration page is not always one level from the root (so assets with relative URLs won't work as expected), or that the asset URLs need to be absolute paths rather than relative.

**Comment by doctorlard** [comment]
Example: https://rocketchat.myserver.com/register/<randomhash>/

**Comment by rodrigok** [comment]
Was fixed in develop by https://github.com/RocketChat/Rocket.Chat/commit/0721d48ca3b23749ca1b95b5a2e566aedffec2dd, since we are always using the tag `base` we should keep the relative path without the leading slash to keep working for subfolder installations like `http://myserver.com/chat/`

This fix will be public available as stable on the next release.
