### ISSUE TITLE
Markdown Tables & HTML no longer render in messages 

### ISSUE THREAD

**Issue by KarolKski** [RocketChat/Rocket.Chat#28990]
### Description:

We updated to 6.0.0 today and somehow neither markdown tables render correctly in messages nor HTML formatted messages. 
Before, we used HTML on some bot messages to highlight parts of messages or display formatted tables with information. 

We saw some settings removed from the old renderer, does the new one no longer support markdown tables or html rendering? 

### Server Setup Information:

- Version of Rocket.Chat Server: 6.0.0
- Operating System:  - 
- Deployment Method: docker
- Number of Running Instances: 1 
- DB Replicaset Oplog: 
- NodeJS Version:  14.21.2
- MongoDB Version: 5.0.16

### Client Setup Information

- Desktop App or Browser Version: Desktop
- Operating System: Windows

**Comment by hugocostadev** [comment]
Hi @KarolKski , you are correct, since 6.0 is the default and the only parser changed by our internal one. 

Currently we do not support table and HTML rendering. 

Could you explain what it's the exact use case for HTML rendering? Maybe there is some options that you can replace the previous behavior. 

Since GitHub is only for issues/bugs related to the repository project, I'll close it for now

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by KarolKski** [comment]
Hi @hugocostadev , thank you for your reply.

We primarily use HTML to render tables in Rocket.Chat.
These tables are generated by various bots/tools, enabling us to present data in a more structured manner than with basic markdown.
We have monitoring/notification channels that display order data from our system, and we've been using tables to format this order information.

If you have any alternative suggestions for achieving this with version 6.0, I would be happy to hear them.

Best regards,

Karol
