### ISSUE TITLE
FB Messenger api integration.

### ISSUE THREAD

**Issue by mrkrumhausen** [RocketChat/Rocket.Chat#2924]
How hard would it be to build something like Zendesk Messenger for Rocket Chat? Customs integrations could be FB Messenger, Kik, Telegram, etc.

https://www.zendesk.com/blog/customer-messaging-introducing-zendesk-message/

**Comment by bott0r** [comment]
I integrated telegram within rocket chat it works fairly nicely. However it has some limitations but you can check it out here https://rocket.chat/docs/master/server-management-1-integration-and-webhooks-telegram

**Comment by mrkrumhausen** [comment]
@bott0r The links doesn't work for me :/

The new Messenger api looks fairly well documented. Do you have any idea on how would I go about integrating it? https://developers.facebook.com/docs/messenger-platform/quickstart

**Comment by bott0r** [comment]
dunno where the 1 came from ! but its fixed now

**Comment by bott0r** [comment]
https://rocket.chat/docs/master/server-management/integration-and-webhooks/telegram

**Comment by dalchand** [comment]
@mrkrumhausen a simple facebook messenger integration with rocket chat https://github.com/dalchand/rocketchat-facebookbridge

**Comment by HammyHavoc** [comment]
0.60.0 brings Facebook Messenger support for Facebook Pages. [https://github.com/RocketChat/Rocket.Chat/pull/8807](https://github.com/RocketChat/Rocket.Chat/pull/8807)

**Comment by graywolf336** [comment]
Hey everyone, as @HammyHavoc has said, we actually did add Facebook messenger support to our Livechat features. So, as a result of that I am going to close this.

However, if @mrkrumhausen feels like it doesn't satisfies what he wanted (I'm assuming it does since he linked to Zendesk's and that's what our feature is like), then he is free to open this issue back up again with an updated description. :)
