### ISSUE TITLE
SlackBridge error receiving messages but sending is fine

### ISSUE THREAD

**Issue by dmotors** [RocketChat/Rocket.Chat#29319]
### Description:

Server is running on Snap installation.

Ever since 5/17/23 no messages from Slack has been received. When I send a message from Rocketchat it goes to Slack fine. No settings has been altered in the SlackBridge settings.

### Steps to reproduce:

Send message from Slack.

### Expected behavior:

Messages sent from Slack should be sent to Rocketchat channel with invited bot user.

### Actual behavior:

No messages received.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.2.2
- Operating System: Windows 11
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v14.21.2
- MongoDB Version: 5.0.15

### Client Setup Information

- Desktop App or Browser Version: 3.9.4
- Operating System: Windows 11

### Additional context

Things that can trigger error logs:
- Adding/Removing user
- Sending message from Rocket
- Enabling/disabling SlackBridge

### Relevant logs:

```
{"level":50,"time":"2023-05-22T18:52:24.359Z","pid":24455,"hostname":"rocket.chat","name":"SlackBridge","section":"Slack","msg":"Unhandled error onMessage","err":{"type":"TypeError","message":"Users.findOneByImportId is not a function","stack":"TypeError: Users.findOneByImportId is not a function<br>    at app/slackbridge/server/RocketAdapter.js:336:34<br>    at /snap/rocketchat-server/1557/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40<br> => awaited here:<br>    at Function.Promise.await (/snap/rocketchat-server/1557/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at app/slackbridge/server/SlackAdapter.js:847:7<br>    at /snap/rocketchat-server/1557/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40<br> => awaited here:<br>    at Function.Promise.await (/snap/rocketchat-server/1557/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at app/slackbridge/server/SlackAdapter.js:460:4<br>    at /snap/rocketchat-server/1557/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40<br> => awaited here:<br>    at Function.Promise.await (/snap/rocketchat-server/1557/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at app/slackbridge/server/SlackAdapter.js:115:6<br>    at /snap/rocketchat-server/1557/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40"},"msg":"Users.findOneByImportId is not a function"} 
```

```
AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Cannot await without a Fiber
    at awaitPromise (/snap/rocketchat-server/1557/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:75:12)
    at Function.Promise.await (/snap/rocketchat-server/1557/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at Callbacks.runOne (lib/callbacks.ts:311:20)
    at lib/callbacks.ts:326:17
    at lib/callbacks.ts:334:5
    at lib/callbacks.ts:342:12
    at Callbacks.run (lib/callbacks.ts:454:10)
    at app/lib/server/functions/addUserToRoom.ts:115:14
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

**Comment by himpierre** [comment]
Same problem here. Please fix that as soon as possible.

**Comment by Jernau** [comment]
Exact same thing here. 
I tried re-running an export from slack and re-import and that doesn't work either.

**Comment by himpierre** [comment]
Someone tried 6.2.3? Is it fixed with that version?

**Comment by himpierre** [comment]
Good to know. Thanks!

Am 6. Juni 2023 18:44:49 MESZ schrieb dmotors ***@***.***>:
>> Someone tried 6.2.3? Is it fixed with that version?
>
>Sending to Slack is still working but receiving from Slack is broken same as before.
>
>Removing the bot and re-adding still get the awaiting fiber message too.
>

**Comment by Jernau** [comment]
Same with 6.2.5 for me too.

**Comment by Jernau** [comment]
Hi, Sorry if this is a stupid question but does that mean it should fixed soon?

**Comment by himpierre** [comment]
Currently it seems to be added to milestone 6.4.0 only which is months away i guess.

cheers, t.

Am 23. Juni 2023 19:32:44 MESZ schrieb Jernau ***@***.***>:
>Hi, Sorry if this is a stupid question but does that mean it should fixed soon?
>

**Comment by Jernau** [comment]
Thanks. At least I know now :).

**Comment by Vladlysenko75** [comment]
> Here a maybe more comprehensive error message;
> 
> {"level":50,"time":"2023-05-25T14:21:50.820Z","pid":1,"hostname":"rocketchat-nodejs","name":"SlackBridge","section":"Slack","msg":"Unhandled error onMessage","err":{"type":"TypeError","message":"Users.findOneByImportId is not a function","stack":"TypeError: Users.findOneByImportId is not a function\n at app/slackbridge/server/RocketAdapter.js:336:34\n at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n at app/slackbridge/server/SlackAdapter.js:847:7\n at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n at app/slackbridge/server/SlackAdapter.js:460:4\n at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n at app/slackbridge/server/SlackAdapter.js:115:6\n at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40"},"msg":"Users.findOneByImportId is not a function"}

I got the same error, this error occur because channel name in Slack and channel name in Rocket Chat should be equal.
But even with that, it doesn't works. I got this error now:

`{"level":50,"time":"2023-08-09T12:08:19.048Z","pid":1,"hostname":"88a629dc2107","name":"SlackBridge","section":"Slack","msg":"Unhandled error onMessage","err":{"type":"errorClass","message":"Match error: Match error: Expected string, got object in field msg","stack":"Error: Match error: Match error: Expected string, got object in field msg<br>    at check (packages/check/match.js:36:17)<br>    at app/lib/server/functions/sendMessage.js:143:2<br>    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40<br> => awaited here:<br>    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at app/lib/server/functions/sendMessage.js:211:2<br>    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40<br> => awaited here:<br>    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at app/slackbridge/server/RocketAdapter.js:507:5<br>    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40<br> => awaited here:<br>    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at app/slackbridge/server/SlackAdapter.js:859:5<br>    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40<br> => awaited here:<br>    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at app/slackbridge/server/SlackAdapter.js:460:4<br>    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40<br> => awaited here:<br>    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at app/slackbridge/server/SlackAdapter.js:115:6<br>    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40","path":"msg","sanitizedError":{"type":"errorClass","message":"Match failed [400]","stack":"Error: Match failed [400]<br>    at errorClass.<anonymous> (packages/check/match.js:91:27)<br>    at new errorClass (packages/meteor.js:718:17)<br>    at check (packages/check/match.js:36:17)<br>    at app/lib/server/functions/sendMessage.js:143:2<br>    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40","isClientSafe":true,"error":400,"reason":"Match failed","errorType":"Meteor.Error"},"errorType":"Match.Error"},"msg":"Match error: Match error: Expected string, got object in field msg"} `

So there is parsing error, because it receives HTML, not string. Will try to fix it.
But for me it doesn't works in Slack, as you wrote. I've created Bot, added him to channel, but he never posts a messages. How you set up to make this work ?

**Comment by c0gnize** [comment]
On my side I fixed it as follows:
```
From 067964fb319666a693eedb0e5760da20e4231642 Mon Sep 17 00:00:00 2001
From: Aleksandr Grigorev <cognize6@gmail.com>
Date: Fri, 23 Jun 2023 10:23:00 +0300
Subject: [PATCH] fix: unhandled exception when joining a room

---
 apps/meteor/app/lib/server/functions/addUserToRoom.ts | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/apps/meteor/app/lib/server/functions/addUserToRoom.ts b/apps/meteor/app/lib/server/functions/addUserToRoom.ts
index 914faf775c..fad525a391 100644
--- a/apps/meteor/app/lib/server/functions/addUserToRoom.ts
+++ b/apps/meteor/app/lib/server/functions/addUserToRoom.ts
@@ -107,7 +107,7 @@ export const addUserToRoom = async function (
        }

        if (room.t === 'c' || room.t === 'p') {
-               process.nextTick(function () {
+               Meteor.defer(function () {
                        // Add a new event, with an optional inviter
                        callbacks.run('afterAddedToRoom', { user: userToBeAdded, inviter }, room);

--
2.39.2 (Apple Git-143)
```

**Comment by himpierre** [comment]
I totally agree. Even we as enterprise customers are left alone with this bug for over three months now. Let's hope 6.4.0 is out soon.

Am 5. September 2023 07:30:17 MESZ schrieb "Son Nguyen H." ***@***.***>:
>Why this issue was marked as completed?
>I'm using 6.3.3 and the issue is still occur.. 
>
>This should be a hotfix, not stick with version releases.
>

**Comment by juzser** [comment]
I had to create a private app that provide an incoming hooks, and a Slack app bot to trigger the hook on message received (via Slack). But it's not able to get the user information from Slack, but for now, it's good as temporary for me.

Just one thing, currently, RC limits 6 private apps as maximum, that does not make sense, when you develop apps and they do not let you use them as free... why...? (My server is also self-hosted)
