### ISSUE TITLE
in forward search field, user cannot be found by name (Full Name) 

### ISSUE THREAD

**Issue by MrPoint1400** [RocketChat/Rocket.Chat#29328]
### Description:
in forward search field, user cannot be found by name (Full Name). just search by id.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.2.2
- Operating System: centos 7
- Number of Running Instances: 1
- NodeJS Version: latest
- MongoDB Version: latest

### Client Setup Information

- Desktop App or Browser Version: google chrome
- Operating System: windows 11

**Comment by debdutdeb** [comment]
Hi ther, which field are you referring to as "forward search field"? I am not sure.

**Comment by Aadarshprajapati777** [comment]
hey, can you send the screenshot, which search field has the error.

**Comment by shevchukma** [comment]
> hey, can you send the screenshot, which search field has the error.

There is no error. Just searching by display name doesn't work. Here I was trying to find Karlan (such display name exists) on open.rocket.chat.
![image](https://github.com/RocketChat/Rocket.Chat/assets/104189570/76f94092-0196-46ab-a775-a5db6e195617)
![image](https://github.com/RocketChat/Rocket.Chat/assets/104189570/58d1855e-ea7e-4ab6-aef8-9d515b1bd003)

**Comment by hugocostadev** [comment]
Just for reference, it's a bug, you can only select people that you talked to because it filters by the direct message that you already had, that's why the component `UserAndRoomAutoCompleteMultiple.tsx` just filters by room. 

Check the mentioned component for some contributor who wants to work on this. (no need to ask for permission to contribute)

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by adityagarg06** [comment]
@hugocostadev in the above mentioned file i have removed the condition if (isDirectMessageRoom(room) && (room.blocked || room.blocker)) from the filter function in the rooms array and updated the options useMemo function to include all rooms and users without any additional filtering.
But still it is not working

**Comment by Rottenblasters** [comment]
@hugocostadev I have a question about this issue. 

Basically right now what is happening is that we can only search for users that we have a direct message with. But in the search it only filters with the `username` and not the `name`.

So do we want to solve this issue such that we can search for any user (even though we have no direct message with them) or just solve the filtering bug where a person can search for both the `username` and `name` ?

**Comment by MrPoint1400** [comment]
User must be able to search by **name/fullname** or **username**
