### ISSUE TITLE
Cannot Delete Messages

### ISSUE THREAD

**Issue by Sx3** [RocketChat/Rocket.Chat#29370]
Did anyone noticed that,when we delete old messages some times it says "undefined" and some times it deletes.

### Server Setup Information:

- Version of Rocket.Chat Server: Version 6.2.2
- Operating System: Ubuntu 20.04
- Deployment Method: snap
- Number of Running Instances: 25
- NodeJS Version: v14.21.2
- MongoDB Version:5.0.1

### Client Setup Information

- Desktop App or Browser Version: Both
- Operating System: All

### Additional context

Cannot Delete Old messages.

**Comment by suryapts007** [comment]
Hi @Sx3, I was trying to do the setup on my local and it seems `version 6.2.2` uses NodeJS Version: v14.21.3 and not v14.21.2. 
Would you be able to verify it?
<img width="797" alt="Screenshot 2023-05-26 at 11 41 53 AM" src="https://github.com/RocketChat/Rocket.Chat/assets/77022877/a2656f4f-04fe-4b8a-87c1-154164df5fa7">

**Comment by suryapts007** [comment]
Also, after I switched to Node v14.21.2, seems like I was able to build the project partially with the dependencies, but it fails at Link Step
<img width="1441" alt="Screenshot 2023-05-26 at 11 47 32 AM" src="https://github.com/RocketChat/Rocket.Chat/assets/77022877/7615d339-0355-47f2-a6c7-687a73b5faaf">


I checked the generated error log files and I see that fiber is looking for node-gyp, but it can not find it. 
<img width="1465" alt="Screenshot 2023-05-26 at 11 53 18 AM" src="https://github.com/RocketChat/Rocket.Chat/assets/77022877/9ee0bacf-2902-440a-98ac-2f64a128b91c">

So I added it as a dependency in package.json and did `yarn install` again and it build successfully!

Now it makes me wonder why it happened with me because you guys already are working on it and if this was a common issue, you would have already identified it. 
Can I get any insights on this from your end?

**Comment by suryapts007** [comment]
Also, can you be more specific about the bug? Do you have any idea how old messages are usually which on deletion shows undefined? 
And how can I replicate it?

I have been trying to send messages and delete them and till now I did not encounter that specific error.
