### ISSUE TITLE
usersInRole.toArray(...).forEach is not a function

### ISSUE THREAD

**Issue by pishgam-rayan** [RocketChat/Rocket.Chat#29387]
hi
Version of Rocket.Chat Server: 6.2.2
when i try to add new user the error " usersInRole.toArray(...).forEach is not a function " occurred

**Comment by ofel011-hub** [comment]
### Description:

An error occurs when trying to register a new user

### Steps to reproduce:

Admin Panel > Users > New > input user info > Save

### Expected behavior:

Save New User

### Actual behavior:

'usersInRole.toArray(...).forEach is not a function'

### Server Setup Information:

- Version of Rocket.Chat Server: 6.2.2
- Operating System: Ubuntu 22.04.1 LTS (GNU/Linux 5.19.0-41-generic x86_64)
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 294
- NodeJS Version: v14.21.3
- MongoDB Version: 5.0.5 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: 3.9.4
- Operating System: Windows 11

### Additional context

![image](https://github.com/RocketChat/Rocket.Chat/assets/63985218/867aff66-f2c2-42f2-806e-054a17814bde)

### Relevant logs:
![image](https://github.com/RocketChat/Rocket.Chat/assets/63985218/1309e4b9-f628-4043-96b9-ee2c709a9a2a)

**Comment by hugocostadev** [comment]
fixed in this PR: https://github.com/RocketChat/Rocket.Chat/pull/29293
