### ISSUE TITLE
Emoticon doesn't show when another mark isn't spaced

### ISSUE THREAD

**Issue by PatrykKorz** [RocketChat/Rocket.Chat#29602]
1. Run any conversation
2. Type anything with emoticon, don't use space between last mark and emoticon, for example ?:cry:
3. Hit enter

Expected result:
Emoticon is displayed.

Actual result:
Emoticon isn't displayed, instead there are only colons and letters.

Perhaps it works as intended but just sayin' :)

**Comment by hugocostadev** [comment]
Hi @PatrykKorz , thanks for raising the issue 🚀  

Could you give a practical example? 

Is it like that? 
e.g: `Lorem ipsum:smile: `

If so, we created a rule to just show emojis that it's side by side with another emoji or with space around, because we had several complains about having emojis inside normal texts

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
