### ISSUE TITLE
Autolinker shows page title automatically

### ISSUE THREAD

**Issue by andreas-bulling** [RocketChat/Rocket.Chat#2961]
Your Rocket.Chat version: 0.27.0

Not sure if the Autolinker is the right module for this but it'd be nice if Rocket.Chat would automatically fetch and insert the corresponding page title if a URL is pasted into the chat, maybe with a format like $title: $URL

**Comment by marceloschmidt** [comment]
If you have Embed turned on, it will fetch the website information:

![image](https://cloud.githubusercontent.com/assets/1986378/14677060/5345aaec-06e6-11e6-9e98-e0d8542a7b95.png)

**Comment by andreas-bulling** [comment]
That's good to know - thanks!

**Comment by LittleStan** [comment]
@marceloschmidt how to cancel the function？because gitlab needs certificate。I hope it dont show the title.

**Comment by dhergert** [comment]
@stanxing if you want to turn off embedding of certain URLs, either due to cert errors , authentication requirements or some other reason, you can add hostnames to the "Administration > Message > Embed Ignored Hosts" section.  Then those URLs won't be fetched.
After you add them, set the "Embed Cache Expiration Days" to 1 and click Clear Cache Now.
