### ISSUE TITLE
Possible to swipe flex-tab-bar

### ISSUE THREAD

**Issue by lunitic** [RocketChat/Rocket.Chat#2970]
Your Rocket.Chat version: 0.26

On a mobile UI the flex-tab-bar takes up a lot of space..
Has there been any thought to make it "swipe-able" 

I guess that not many users uses it that frequently..

**Comment by Molle500** [comment]
Could have similar to Slack. When you press the triple dots the bar appear. The bar takes up too much space on mobile units.

![example](https://cloud.githubusercontent.com/assets/17712562/14688357/835e7dce-0742-11e6-8732-14916bbcdd57.png)

**Comment by frdmn** [comment]
👍

**Comment by maxlinux2000** [comment]
+1...+2!!!

**Comment by steven-tib** [comment]
+1

**Comment by RichardFoxworthy** [comment]
We need more than just a swipe-able flex tab interface. There are severe usability issues with it on mobile where flex tabs consume the entire screen and it is not obvious how to get back to the normal interface. 

The UX needs to make it very obvious to the user that this is a panel sitting on top of the main interface and there also needs to be a very obvious control to collapse the tab.

We've had plenty of users who accidentally launch a flex tab and then cannot collapse it again, and sometimes on mobile they cannot find their way back to the main app at all - one of them actually deleted and reinstalled the mobile app because she thought she'd hit a catastrophic bug of some kind
