### ISSUE TITLE
Help with username and name issues for non-english users

### ISSUE THREAD

**Issue by etcy** [RocketChat/Rocket.Chat#2974]
Hi, 

My team (about 150 members) has been testing mattermost for a few weeks but respond is not so good because they have no japanese localizations. Before this we were testing some XMPP chat server/clients.

I found rocket.chat and I think its a great piece of work. It has multi-language support out of the box and most of the features we are looking for.

However, after testing locally, I could not push it out for a team test because I cannot find a way to allow the name to be displayed.

I think this has been discussed somewhere before but the issue does not seem to be solved. It really makes sense for any chat program to display a name/nick that is user defined. skype, openfire(xmpp), mattermost all feature this. Without this, non english speakers find it impossible to find the people. Not to mention too many duplicates in username if we use their full names. eg tanaka ryo1, tanaka ryo2, tanaka ryo3...doesn't make sense.

I read in previous post somewhere that username is unique and therefore preferred but you can achieve the same goals with a user defined nick or name. 

for asians, many people have the exact same spelling but different Kanji characters
tanaka ryo1 = 田中リョ
tanaka ryo2 = 田中侶
tanaka ryo3 = 田中虜

also for my team, on my existing chat, we have a rule for nickname as such:
name-subteam/role-extension number
with this simple rule, even when full name/kanji is exactly the same, we can tell whos whos
 田中リョ-CG-1234
 田中リョ-PRG-3245

Sorry for the long post. I hope someone can advice on this.

Thank you!

**Comment by marceloschmidt** [comment]
Hello @etcy! We're happy to support you on this one.

Since we have no asians on our team, it is very difficult to solve problems such as this one, so if you could stay with us and guide us through, that will be awesome!

Have you tried changing the `UTF8 Names Validation` setting under Administration / General? 

![image](https://cloud.githubusercontent.com/assets/1986378/14932510/c87510dc-0e4d-11e6-9f73-3ccbdd8189a4.png)


This setting was created to allow people to set their usernames based on a specified regular expression.
Ours is currently set to `[0-9a-zA-Z-_.]+` but you could set yours to `[^\x00-\x7F]+` for example.

Let me know if that solves it, or if we need to further work on this.

**Comment by etcy** [comment]
Thank you for the reply. For a while, I have given up on rocket.chat.

I was out of office and could not try this until today.
The settings you suggested works well. Now I can enter Japanese names into Username field!

This has given me new hope to pushing rocket.chat as the team chat....
just have to figure out how to setup the following:
1. Jenkin send info to rocket.chat
2. Able to start jobs from rocket.chat
3. Redmine send ticket update info to rocket.chat

Once I get those done, I can replace mattermost server that we are using now ^^

**Comment by graywolf336** [comment]
@etcy When you say "start jobs from rocket.chat" are you talking about starting them in Jenkins from Rocket.Chat? If so, how do you imagine being authenticated? Or will all of your users be able to queue up builds?

**Comment by graywolf336** [comment]
Ah never mind, found #3097. Moving discussion over there.
