### ISSUE TITLE
webdav upload error

### ISSUE THREAD

**Issue by xmsama** [RocketChat/Rocket.Chat#29944]
i use alist for webdav 
alist use alibaba cloud oss 
when i send big than 1mb file to channel 
channel will not show message but oss uploaded successfully

**Comment by hugocostadev** [comment]
Sorry, you need to follow the issue template in other to provide necessary information to make it the possible to investigate the possible issue.

We are waiting for a update, otherwise this issue is going to be closed, thanks! 

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
