### ISSUE TITLE
Room not found page after clicking on direct message in user info card 

### ISSUE THREAD

**Issue by amirAlamian** [RocketChat/Rocket.Chat#29960]
Hi Iam using latest version (6.2.11) of the rocketchat server on ububtu 22.04 and when I open a user info card in a channel and click on send direct message button, first you show a room not found page and then it will be redirected to user direct message page.
![image](https://github.com/RocketChat/Rocket.Chat/assets/65771812/9ae56e72-217b-4c07-98ec-e1c735f3ffb3)

**Comment by amirAlamian** [comment]
any comments?

**Comment by hugocostadev** [comment]
Sorry, you need to follow the issue template in other to provide necessary information to make it the possible to investigate the possible issue.

We are waiting for a update, otherwise this issue is going to be closed, thanks! 

I could not reproduce it in the latest version

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by amirAlamian** [comment]
Ok I will check this again on the latest version and I will send a video to show you how to reproduce it.

**Comment by amirAlamian** [comment]
https://github.com/RocketChat/Rocket.Chat/assets/65771812/e82720b0-5222-4a05-97b6-2173efc1db69

**Comment by nmagedman** [comment]
This issue was addressed recently by PR #30157
