### ISSUE TITLE
Self Hosted version not able to run on M1 MacBook Air.

### ISSUE THREAD

**Issue by paragcopods** [RocketChat/Rocket.Chat#29967]
### Description:
I tried all the possible ways as mentioned in [this link ](https://developer.rocket.chat/open-source-projects/server/server-environment-setup/mac-osx#troubleshooting) to get the project up and running, however the documentation doesn't addresses the probable issues that comes while setting up the project locally. 

I am still not able to run the project on arm64/i386 versions in my Mac. 

Can anyone assist me this?

My system: M1 MacBook Air | 16 GB

**Comment by hugocostadev** [comment]
Sorry but what is your problem exactly? I'm running on an M1 Macbook... 

Sorry, you need to follow the issue template in other to provide necessary information to make it the possible to investigate the possible issue.

We are waiting for a update, otherwise this issue is going to be closed, thanks! 

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
