### ISSUE TITLE
Re Register Rocketchat Server to Cloud Rocketchat Workspace

### ISSUE THREAD

**Issue by Conrado916645** [RocketChat/Rocket.Chat#29994]
### Description:

Can't Sync Rocketchat Workspace. After i removed my rocketchat server accidentally to my rocketchat cloud i tried to re register it by sync my workspace.

### Steps to reproduce:

1. got Cloud.Rocket.chat
2. click Workspace 
3. remove server
4. goto yourRocketchat.com
5. Administration > Registration > Manage > Sync

### Expected behavior:

It wil re re-register my server and sync all features

### Actual behavior:

having an error ion sync 

### Server Setup Information:

- Version of Rocket.Chat Server:  6.2.11
- Operating System:  Linux
- Deployment Method: snap

- NodeJS Version: v14.21.2
- MongoDB Version: 5.0.15

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

![Untitled](https://github.com/RocketChat/Rocket.Chat/assets/36912212/1fa2bece-c634-4b52-9012-a33dff8d7d5e)

**Comment by hugocostadev** [comment]
What error are you facing?  I could not reproduce it here... 

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by monerisq** [comment]
Issue:

After upgrading the Rocket.Chat server from version 6.1.5 to 6.3.2, a significant issue with workspace registration has arisen. It appears to be related to changes in the registration policy.

In version 6.1.5, I utilized the "Register self-manage" option via [cloud.rocket.chat](https://cloud.rocket.chat/), which successfully registered my workspace. However, after the upgrade to 6.3.2, I decided to remove my workspace from [cloud.rocket.chat](https://cloud.rocket.chat/) and attempt to use the automatic registration feature provided by the new version.

The problem manifests when, despite the "Workspace registered" message being displayed in the "Registration" section of the server, an error occurs with the message "An error occurred syncing your workspace" when attempting to synchronize through "Manage/Sync." This presents significant challenges, as this issue prevents me from registering the workspace, thus denying me access to push notifications on mobile devices.

I have attached screenshots of the error, setup wizard settings, and server logs for a more detailed diagnosis of the problem.

This issue is critical as it affects the functionality of my Rocket.Chat server and the availability of push notifications on mobile devices. Additionally, you can read about the changes in the registration policy [here](https://docs.rocket.chat/use-rocket.chat/workspace-administration/registration).
![setup_wizard](https://github.com/RocketChat/Rocket.Chat/assets/137060675/c5a3a7a0-60bb-47b2-89c5-be9b083c5be6)
![Registration](https://github.com/RocketChat/Rocket.Chat/assets/137060675/170f8275-9d99-45f8-baf7-abfbf1c13817)
![Sync Error](https://github.com/RocketChat/Rocket.Chat/assets/137060675/e05824e3-f18b-423f-9f9b-d55ec733f89d)
![push](https://github.com/RocketChat/Rocket.Chat/assets/137060675/4a532c74-7f01-4eb1-8bc0-5eee8a2f0eee)
![info](https://github.com/RocketChat/Rocket.Chat/assets/137060675/d5a7e3c0-4740-4016-a190-58a8e62b792b)


Docker-compose logs:
```
rocketchat_1          | {"level":50,"time":"2023-09-11T14:59:06.952Z","pid":10,"hostname":"2c55d5b61ed4","name":"Rocket.Chat Apps","msg":"Error getting the app requests stats from marketplace 'failed to aggregate seen app requests due to a database error'"}
rocketchat_1          | {"level":40,"time":"2023-09-11T15:00:21.907Z","pid":10,"hostname":"2c55d5b61ed4","name":"DeprecationWarning","section":"API","msg":"The parameter \"query\" in the endpoint \"/api/v1/settings.public\" is deprecated and will be removed on version 7.0.0"}
rocketchat_1          | {"level":40,"time":"2023-09-11T15:00:43.545Z","pid":10,"hostname":"2c55d5b61ed4","name":"DeprecationWarning","section":"API","msg":"The parameter \"query\" in the endpoint \"/api/v1/settings.public\" is deprecated and will be removed on version 7.0.0"}
rocketchat_1          | {"level":50,"time":"2023-09-11T15:01:41.053Z","pid":10,"hostname":"2c55d5b61ed4","name":"Rocket.Chat Apps","msg":"Error getting the app requests stats from marketplace 'failed to aggregate seen app requests due to a database error'"}
rocketchat_1          | TypeError: Cannot read property 'authRequired' of undefined
rocketchat_1          |     at packages/rocketchat:restivus/lib/route.js:199:16
rocketchat_1          |     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
rocketchat_1          |  => awaited here:
rocketchat_1          |     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
rocketchat_1          |     at packages/rocketchat:restivus/lib/route.js:155:13
rocketchat_1          |     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
rocketchat_1          |  => awaited here:
rocketchat_1          |     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
rocketchat_1          |     at packages/rocketchat:restivus/lib/route.js:57:18
rocketchat_1          |     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
rocketchat_1          | {"level":50,"time":"2023-09-11T15:04:58.551Z","pid":10,"hostname":"2c55d5b61ed4","name":"Rocket.Chat Apps","msg":"Error getting the app requests stats from marketplace 'failed to aggregate seen app requests due to a database error'"}
rocketchat_1          | {"level":50,"time":"2023-09-11T15:26:05.814Z","pid":10,"hostname":"2c55d5b61ed4","name":"Rocket.Chat Apps","msg":"Error getting the app requests stats from marketplace 'failed to aggregate seen app requests due to a database error'"}
rocketchat_1          | {"level":50,"time":"2023-09-11T15:26:34.886Z","pid":10,"hostname":"2c55d5b61ed4","name":"Rocket.Chat Apps","msg":"Error getting the app requests stats from marketplace 'failed to aggregate seen app requests due to a database error'"}
rocketchat_1          | {"level":50,"time":"2023-09-11T15:26:38.837Z","pid":10,"hostname":"2c55d5b61ed4","name":"Rocket.Chat Apps","msg":"Error getting the app requests stats from marketplace 'failed to aggregate seen app requests due to a database error'"}
rocketchat_1          | {"level":40,"time":"2023-09-11T15:30:32.029Z","pid":10,"hostname":"2c55d5b61ed4","name":"DeprecationWarning","section":"API","msg":"The parameter \"query\" in the endpoint \"/api/v1/settings.public\" is deprecated and will be removed on version 7.0.0"}

```

**Comment by monerisq** [comment]
Hello,

I want to emphasize that this issue remains relevant and is hindering the normal operation of my Rocket.Chat server. Unfortunately, I currently have no idea how to thoroughly diagnose and resolve this problem. Additionally, with the new workspace registration system, I am unable to track the number of push messages used, making it even more challenging to analyze.

It would be great if someone from the community could provide a solution or suggest possible steps to address this issue. I am ready to provide any additional information that may be helpful in resolving this problem. I hope for your assistance and look forward to when push notifications will work again.

Thank you!

**Comment by luismalmonte** [comment]
I have the same issue

**Comment by andarouler** [comment]
Hi, same here got this error after an upgrade to version `6.4.4`. 

Log-Message:
```log
"Error getting the app requests stats from marketplace 'failed to aggregate seen app requests due to a database error'"
```

When i visit the `/admin/registration`-page i get a blank page.

**Comment by geidsonc** [comment]
> Hello, I have same issue with same message "An error occured syncing your workspace" after upgraded to version 6.4.5

I fixed my problem with the steps described here: https://github.com/RocketChat/Rocket.Chat/issues/30946
