### ISSUE TITLE
глючит приложение

### ISSUE THREAD

**Issue by elizavetakursevich1** [RocketChat/Rocket.Chat#30002]
Добрый день! Не могу увидеть чаты. 
![2023-08-03 (7)](https://github.com/RocketChat/Rocket.Chat/assets/140593608/920cae36-8e7f-4343-93d2-5fcb1f24ff1b)

**Comment by bulkinav** [comment]
@elizavetakursevich1 it is better to write here in English.

Also, it seems that your issue does not relate directly to the backend side of Rocket.Chat. Please note that discussion of the desktop version of Rocket.Chat is located here - https://github.com/RocketChat/Rocket.Chat.Electron/releases

I also recommend that you first check the working of Rocket.Chat through the browser. Most likely, there will be no problems with the display there (as on you screenshot). In this case, try to log out of the account from the desktop version and log in again.

**Comment by hugocostadev** [comment]
Sorry, you need to follow the issue template in other to provide necessary information to make it the possible to investigate the possible issue.

We are waiting for a update, otherwise this issue is going to be closed, thanks! 

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
