### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by rhinton-hash** [RocketChat/Rocket.Chat#30068]
Update will not perform as intended. The request to install now comes up however, when it reloads it is at the old version and the request process happens again.

**Comment by hugocostadev** [comment]
Sorry, you need to follow the issue template in other to provide necessary information to make it the possible to investigate the possible issue.

We are waiting for a update, otherwise this issue is going to be closed, thanks! 

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
