### ISSUE TITLE
Valid concerns on Rocket.Chat updates

### ISSUE THREAD

**Issue by khodge281** [RocketChat/Rocket.Chat#30761]
Maximum amount of seats, so i clear a seat, THEN i get maximum amount of users. WHAT THE HELL< you people are screwing this thing up faster than you fix anything. Cant export chat logs so i can have hard records, i pay you a lot of money and everytime you "UPDATE" something it seems to get worse.

**Comment by urosino** [comment]
Even though this is not professionally written, I agree, with every release we seem to deal with more annoyances / bugs, such as:
- random logouts on App upgrade
- UI / UX problems, such as cut off names
- top message, running out of seats even though we are an enterprise customer, you don't need to remind me of that on every update
- outdated apps from Marketplace like Google Meet, Zoom (it used to work well)

**Comment by casalsgh** [comment]
@urosino @khodge281 thanks for the feedback and very valid concerns. 
We do understand sometimes we add to the complexity and do not meet our users quality standards from time to time, but we are working to build a better OSS, with more quality and better overall UX.
 
Zoom will receive updates very soon. I understand last update on Google Meet was 3 months ago, but we'll revisit it. 
UI/UX problems noted and we have different initiatives and internal teams working to fix them, as well as on other problems mentioned.  

In case there is anything specific you are not seeing a solution for and has been representing a bug/annoyance, please send me a direct message on open server (gabriel.casals), and I see how I can be of help. 

Again, really appreciate the feedback with valid concerns comments. 
PS: Changed the issue title, hope you don't mind.

**Comment by engelgabriel** [comment]
@urosino @khodge281 The refactoring has improved our platform's coding standards and technology stack. However, due to the insufficient automated testing, it has also introduced a noticeable number of bugs. We are shifting our focus from developing new features to stabilizing the codebase and ensuring it has adequate test coverage to prevent such issues in the future. I personally apologize for any inconvenience this may have caused, and I want to assure you that we have taken your feedback seriously. We are committed to doing better in this regard.

**Comment by engelgabriel** [comment]
@khodge28 I understand you are a enterprise customer. Have you opened support tickets? If so, may I ask the numbers to help prioritise?
