### ISSUE TITLE
Rocketchat Community Version not allowing more than 200 concurrent Users

### ISSUE THREAD

**Issue by harish751995** [RocketChat/Rocket.Chat#30978]
-->

After I upgraded to 6.3.10 from 4.8.7.Now When the concurrent users is more than 200 then Status is disabled.

It Required Manually to enable the Status again if the concurrent users is less than 200

Expected Behaviour:

1.Is there any option to allow the concurrent users more than 200 in Rocketchat Community Edition
2.Orelse It should atlease automatically turn on the user status if it goes less than 200 concurent users.

Comments:

Rocketchat Forcing us to update to Latest version.But when we update the Latest version they are restricting in these critical features to makes us move towards enterprise version.

**Comment by fbernhard** [comment]
This limit is defined here:

https://github.com/RocketChat/Rocket.Chat/blob/develop/ee/packages/presence/src/Presence.ts#L9

However, this file is in the "ee" directory. Therefore, this file "[...] may only be used in production, if you (and any entity that you represent) have agreed to, and are in compliance with, the Rocket.Chat Subscription Terms of Service [...]"

**Comment by vajnaivik** [comment]
I'm sorry if the answer is obvious and for being a bit off-topic, but was that move legal?
Isn't that basically revoking the MIT license for some of the code?

**Comment by hugocostadev** [comment]
Hi @vajnaivik it's legal,  you can still use the version that this part of the code was open source under MIT if you like.

Regarding that decision, we made like that because we can face a lot of issues due to the presence service, and 200 sessions was the cap that we found ideal. 

That said, this is not a bug, it's expected

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
