### ISSUE TITLE
Help with integrations: Jenkins

### ISSUE THREAD

**Issue by etcy** [RocketChat/Rocket.Chat#3097]
Your Rocket.Chat version: (0.27.0)

Sorry for the noob question. 

I have been searching the web about "rocket.chat jenkins integration" for more than 2hrs.
To my surprise, I cannot find a single help on this.

Can someone be so nice as to point me the right direction?

My guess:
1. Install plugin on jenkins
1. Create incoming webhook
2. Input info of incoming webhook to Jenkins... viola!

**Comment by graywolf336** [comment]
Right now I don't believe there is a Rocket.Chat integration for jenkins. I've never made a plugin for Jenkins so I'm a little uncertain where to start, but I use Jenkins myself so I'd like to see this happen.

You mentioned in the other issue you'd like the ability to start jobs, how do you envision authentication for setting who created the job or for allowing certain people to start jobs?

**Comment by etcy** [comment]
I have been conducting trial with part of my team (30 people out of 100+).
So far I have tried
1. Open fire server (centos), Jitsi Client (windows)
2. Mattermost server (centos), Mattermost client (windows)

On both setup, 
a. Jenkins plugin is installed. Job notification is sent to chat room. 
b. Job can be started from chat. I have no system to restrict people from starting jobs. 
However, we do have rules on who, when, why we should start a job.
c. Redmine has a plugin installed too, that notifies chat room on ticket changes.

I am not satisfied with both implementations for various reason which is why im trying to push next team trial to be rocket.chat. I personally think this might be it! 

But i cannot push out a trial until I get the jenkins, redmine stuff settled.

And yes, I see you point about authentications for starting jobs. I think it would be nice to have that.

**Comment by chkal** [comment]
Hey all,

I was also looking for some nice Rocket.Chat Jenkins integration because we are using Jenkins in your team and recently switched to Rocket.Chat for team communication.

There are some basic Jenkins plugins out there like [rocket-chat-notifier](https://github.com/baloise/rocket-chat-notifier) and [rocketchat-plugin](https://github.com/CheggEng/rocketchat-plugin). However, both didn't really fit our needs. Therefore I forked the one created by [baloise](https://github.com/baloise) and enhanced it to support the requirements of small to medium sized development teams.

You can find the plugin here:

**https://github.com/chkal/rocket-chat-notifier**

The plugin supports:

  * Configuration of a single Rocket.Chat server for the entire Jenkins instance
  * Send chat notification to a Rocket.Chat room if any build starts failing, is still
    failing or gets back to stable state.
  * Allows to notify all users by including `@all` in the notify message.

The plugin does NOT support:

  * Different notification settings for individual jobs

I hope that this plugin is useful for other teams too. Any kind of feedback is highly welcome. :-)

**Comment by mmiranda** [comment]
Just an update about this topic, I'm using this one https://github.com/Backelite/rocketchat-notification, which is really simple but at least let me split notifications in differents jobs and rooms.

**Comment by FibreFoX** [comment]
Just to update this thread a bit: the [rocketchat-notifier-plugin from JenkinsCI-repository](https://github.com/jenkinsci/rocketchatnotifier-plugin) works with current Rocket.Chat-versions since 0.4.5 and includes individual settings per job, even is callable inside custom Jenkinsfile pipeline scripts.

Maybe as a lot of other "Integrations" are there, this might push some google rankings when finding "Jenkins" as term inside the docs.

**Comment by graywolf336** [comment]
@FibreFoX Mind adding that to our documentation? That way we can redirect users to that when they ask for Jenkins.

Closing this in favor of: https://plugins.jenkins.io/rocketchatnotifier

**Comment by Rohlik** [comment]
@graywolf336 I will create documentation for this soon. Expect my pull soon 😉

**Comment by ssbarnea** [comment]
Sorry to say it but the current implementation of the plugin is utterly useless: **no support for API keys and WebHooks**, which renders any enterprise level deployment impossible (2FA and SSO = no passwords).

Even once the support for webhooks and tokens will be sorted we will still not be able to configure notifications per job, which means that any team of more than 10 people will not able to use it because they will not be able to tune it : sending the right messages to the right groups.

**Comment by Rohlik** [comment]
@ssbarnea This plugin is not development by RC team. But You can setup different notification settings for different job in Jenkins.
