### ISSUE TITLE
Admin Info Page is not loading in 6.3.10 Rocketchat Version

### ISSUE THREAD

**Issue by harish751995** [RocketChat/Rocket.Chat#30979]
After upgrading to 6.3.10 Version.When I try to Load Admin info page it is not loading with Message Error Loading Pages.Why this is happening?

Screenshot is provided below

![image](https://github.com/RocketChat/Rocket.Chat/assets/107982362/fad6900d-d12e-4302-b63b-52322254e3a9)

**Comment by Karan-Palan** [comment]
I'd like to work with this issue, setting up this project on my laptop

**Comment by ishak-aksuenger** [comment]
**Server Setup Information:**
Version of Rocket.Chat Server:
Operating System: 
Deployment Method: 
Number of Running Instances: 
DB Replicaset Oplog: 
NodeJS Version:
MongoDB Version: 


**Client Setup Information**
Desktop App or Browser Version: 
Operating System: 

Can you fill this out and say how you deployed it

**Comment by Karan-Palan** [comment]
I am currently learning docker, will setup soon and answer

**Comment by hugocostadev** [comment]
Sorry, you need to follow the issue template in other to provide necessary information to make it the possible to investigate the possible issue.

We are waiting for a update, otherwise this issue is going to be closed, thanks! 

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
