### ISSUE TITLE
No preview for animated gifs from tweets

### ISSUE THREAD

**Issue by ulope** [RocketChat/Rocket.Chat#3113]
Your Rocket.Chat version: 0.29.0

Normally the inline preview shows images linked in tweets. This doesn't work for animated gifs.
It seems that twitter converts animated gifs to mp4 so it's probably similar to #1040.

**Comment by marceloschmidt** [comment]
#1040 has been fixed on Oct 22nd. You can try it with https://i.imgur.com/F4XcrVK.gifv for example. 
Could you provide a link that won't work as expected, please? 
Thank you.

**Comment by ulope** [comment]
It's basically any tweet that contains an animated gif. Here is an example:

* Tweet: https://twitter.com/soffes/status/727296267324264448
* Actual mp4 file: https://pbs.twimg.com/tweet_video/ChfgGbdUUAEb8dh.mp4

**Comment by marceloschmidt** [comment]
That looks like how twitter handles their links... If you paste the link on FB, for instance, here's the output: 
![image](https://cloud.githubusercontent.com/assets/1986378/14983301/c0717e8a-1112-11e6-9249-7369a3b73dab.png)

That's because twitter will use the user picture as og:image, which is what we'll get for preview.
![image](https://cloud.githubusercontent.com/assets/1986378/14983316/d94a7e16-1112-11e6-8f99-c3958c575e5d.png)

**Comment by ulope** [comment]
Hm, thats unfortunate. 

As a comparison slack somehow manages to extract a preview of the video: ![image](http://cl.ly/3k0I3t1j3i0y/Image%202016-05-03%20at%202.46.01%20PM.png)

**Comment by marceloschmidt** [comment]
This is doable via Twitter API probably. I'll put that on a nice-to-have milestone so we can work on that someday, or someone may create a PR for this.

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!
