### ISSUE TITLE
Facebook and Instagram app are not working, even though I am on the new "starter plan": "Workspace service record does not have the instagram service account enabled"

### ISSUE THREAD

**Issue by saschafoerster** [RocketChat/Rocket.Chat#31176]
I tried to connect to the support via the support portal, but they said, I am not an a paid support plan. But I still think this is an issue of RocketChat Cloud, not of RocketChat itself. 

I tried to connect Facebook Messenger and Instagram Direct, I reinstalled the apps and waited some days, but even though I am on the "Starter" level, it doesn't work. 

```
Instagram Direct @instagram.bot

Sorry!! Couldn't perform the operation since we're experiencing some issues while connecting to Instagram

Details:

*Error Code:* 103

*Error Message:* Error! Workspace service record does not have the instagram service account enabled. To resolve this issue, please reinstall the Instagram Direct app via Rocket.Chat's Marketplace. If the error still persists, please contact Rocket.Chat's support

*Error Details:* workspace service record with workspaceID: [OBFUSCATED] does not have the instagram service account enabled

```
### Description:

Instagram app and Facebook app can't be used, even though I am on a starter plan. I tried installing, uninstalling and re-installing, without any success. 

### Steps to reproduce:

1. Install Instagram app
2. Try to connect via "connect button" in Chat
3. Error message (see above)

### Expected behavior:

Connection to Instagram via Login 

### Actual behavior:

Error message in the chat

### Server Setup Information:

- Version of Rocket.Chat Server: 6.5.0
- Operating System: Debian 11
- Deployment Method: docker 
- Number of Running Instances: 1
- DB Replicaset Oplog: -
- NodeJS Version: -
- MongoDB Version:-

**Comment by renatobecker** [comment]
Hi @saschafoerster this is Renato from the product team at Rocket.Chat. First of all, thanks for sharing the issue you're running into, I want to let you know that our team is working on definitively fixing this to avoid future problems when configuring Apps and integrations. In the meantime, I'd like to propose a different path to quickly solve the issue but I need to share some instructions with you so please email me(renato.becker@rocket.chat) and I'll promptly help you out.

 In case other members face the same issue, please follow the same path as shared above until the issue is gone.
