### ISSUE TITLE
Grey screen in browser

### ISSUE THREAD

**Issue by kingdsand** [RocketChat/Rocket.Chat#31276]
### Search before asking

- [X] I had searched in the [issues](https://github.com/RocketChat/Rocket.Chat.Electron/issues?q=is%3Aissue) and found no similar issues.

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

### Operating System Version

Ubuntu 22.04

### It happens on the web browser too?

Yes, it happens on the web browser too

### Rocket.Chat Desktop App Version

3.9.10

### Rocket.Chat Server Version

6.5.0

### Describe the bug

el problema es al ejecutar el servidor en el navegador no termina de cargar la pagina, se queda en una pagina gris y de ahi no pasa
![Screenshot_20231206_110841](https://github.com/RocketChat/Rocket.Chat.Electron/assets/5050663/82d563e0-5eff-4e9e-a8d7-14c9903a8a54)

![Screenshot_20231206_103510](https://github.com/RocketChat/Rocket.Chat.Electron/assets/5050663/43752918-a687-476a-979d-1022f69ca65f)

### How to Reproduce

![Screenshot_20231206_110841](https://github.com/RocketChat/Rocket.Chat.Electron/assets/5050663/c1d1e4e0-fdfb-44bd-a3ae-a843311886fd)

### Are you willing to submit a code contribution?

- [X] Yes, I am willing to submit a Pull Request!

**Comment by hugocostadev** [comment]
Sorry, you need to follow the issue template in other to provide necessary information to make it the possible to investigate the possible issue.

We are waiting for a update, otherwise this issue is going to be closed, thanks! 

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by yeshili** [comment]
![image](https://github.com/RocketChat/Rocket.Chat/assets/24773628/aaded4d2-d876-4370-9a20-7ae002a61eed)
我的问题和你一样，这bug！！
