### ISSUE TITLE
SignUp Page is not working properly 

### ISSUE THREAD

**Issue by pankaj-2503** [RocketChat/Rocket.Chat#31285]
** When you go to signup on rocket.chat  cloud , in the form if the user give inputs due to this form get's bigger in size and touches the border of screen .Also background image shrinks and zooms out when giving inputs . This needs to be fixed as it is not good for user experience. **

See the issue ; 
![image](https://github.com/RocketChat/Rocket.Chat/assets/90036864/75af42ce-eaa2-45a3-9dff-a2167809e3fc)

If you have questions or are looking for help/support please see: https://rocket.chat/docs/getting-support

If you are experiencing a bug please search our issues to be sure it is not already present: https://github.com/RocketChat/Rocket.Chat/issues

-->

### Description:

<Form is shrinking and zooming when giving inputs -->

### Steps to reproduce:

1. Go to rocket.chat signup via cloud  method and then try to fill the inputs of signup form you would get the issue.

### Actual behavior:
Should be stable at fixed position

<
![image](https://github.com/RocketChat/Rocket.Chat/assets/90036864/ffed3991-5410-44b7-8c19-c2d2c1b77cfc)
>

**Comment by LalitDeore** [comment]
Hii @pankaj-2503 , I saw the issue on website. White div of the register page was touching to the lower screen and whole page is not adjustable to screen. we have to fix the height of the div and also backgroud of the registration is getting bigger we have to solve this If i am going in right way could you please assign this task to me so can start working on it.

**Comment by Sahil-Shadwal** [comment]
I see no problem there , just scroll the page .

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Come on guys, this is not an issue. When validating the fields we have to add more information below the fields and the form will increase the size consequently if there's not enough size the user has to scroll down. 

Closing this one because there's nothing to be fixed here.

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
