### ISSUE TITLE
Can parameters be used in the URL to pass user information?

### ISSUE THREAD

**Issue by Iamahao** [RocketChat/Rocket.Chat#31316]
Question:
https://${url}/livechat?mode=popout
I need to directly use URL parameters on the website.

Currently, by using 'mode=popout,' I can directly open the chat room for users, but I'm unable to identify the user.
Is there a way to achieve this?
https://${url}/livechat?mode=popout&setGuestName=CuteGuest&fromUrl=rocket.chat

I am currently using this method:
RocketChat(function() {
    this.setGuestName('Guset_Name_Tom');
});
Is there a way to achieve this directly through URL parameters?

**Comment by MartinSchoeler** [comment]
Hello @Iamahao Currently there is no way to achieve this via URL parameters, even the pop out mode is not something designed to be used standalone (it is part of the functionality of one of the livechat header buttons)

You can use the method [`registerGuest`](https://developer.rocket.chat/reference/api/livechat-api#register-visitor) to have more control over the guest data and [`maximizeWidget`](https://developer.rocket.chat/reference/api/livechat-api#register-visitor) to open the widget to the visitor

We do not plan on supporting direct url parameters since most of the time the widget is embedded on an iframe, making it difficult to pass dynamic parameters to it's url.

**Comment by Iamahao** [comment]
Got it. Thank you for your reply.
