### ISSUE TITLE
Recieving messages one day later

### ISSUE THREAD

**Issue by RenathaMachado** [RocketChat/Rocket.Chat#31321]
Prezados,

Recebo mensagens apenas no dia seguinte ou com muito atraso.

**Comment by Sayan4444** [comment]
Can you please come up with a video?

**Comment by hugocostadev** [comment]
Sorry, you need to follow the issue template in other to provide necessary information to make it the possible to investigate the possible issue.

We are waiting for a update, otherwise this issue is going to be closed, thanks! 

Also, try to write in English. Thanks

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository
