### ISSUE TITLE
application gui keeps crashing

### ISSUE THREAD

**Issue by tashalee991** [RocketChat/Rocket.Chat#31504]
i have logged into the application many times and it keeps crashing. is there something specific i need to have on my computer in order for it to work and run? do i need to have a special video app or service? how do i keep it from crashing?

**Comment by zahidhussain998** [comment]
plase send the images of this issue that your are facing thanks

**Comment by udham2710** [comment]
pls send the images of this issue that your are facing so then i can solve only

**Comment by azevedo-joao** [comment]
Having the same issue for days now. Not able to log in on Rocket.chat. Tried reloading the App, disabling GPU, restarting the App, re-installing it. Nothing works. Happens with Windows and macOS. Even on Safari/Firefox. Using the latest version of the App 3.9.11. Keep getting this screen. Username and passwords are correct since the error for bad credentials is different.

<img width="1112" alt="image001" src="https://github.com/RocketChat/Rocket.Chat/assets/40271272/07920a81-8d03-45a5-a8a7-1700d40479b1">
<img width="1341" alt="image002" src="https://github.com/RocketChat/Rocket.Chat/assets/40271272/76b45212-88b0-4d34-b831-430243219535">

**Comment by MartinSchoeler** [comment]
Hello @azevedo-joao @tashalee991 can you [open the browser devtools](https://rocket.chat/docs/contributing/reporting-issues#gathering-logs) and check the console for any errors? Thanks!

**Comment by tashalee991** [comment]
Yes, I will check.

**Comment by gabriellsh** [comment]
Hi, any chance you could include the required information from the issue template? It is very important for us to debug issues. Mainly for this case it would be really nice to now the server version and if there's any specific login settings that were changed (configured OAuth, Ldap, password policy, etc).

Thanks for reporting the issue, I'm waiting on your response.

**Comment by Nissulya** [comment]
> Hi, any chance you could include the required information from the issue template? It is very important for us to debug issues. Mainly for this case it would be really nice to now the server version and if there's any specific login settings that were changed (configured OAuth, Ldap, password policy, etc).
> 
> Thanks for reporting the issue, I'm waiting on your response.

Hi, in the case of @azevedo-joao it is the snap installation version 6.5.2:
Version: 6.5.2
Deployment ID: Qv4RERTtmkYyeFJXn
Apps Engine Version: 1.41.0
Node Version: v14.21.2
Database Migration: 304 (January 23, 2024 10:18 PM)
MongoDB: 5.0.15 / wiredTiger (oplog Enabled)

**Comment by tashalee991** [comment]
I never got the app to work. It just connected through website

**Comment by rocha-joshua** [comment]
Hello! I've been encoutering the same problem with the exact same error in console. Has a solution been found?

**Comment by Nissulya** [comment]
For our user there was a problem with a change in his ldap attributes. His first name was changed to a double name and this produced the error that the user couldn't be mapped to the existing user. We map our user on attributes mail, sn and givenName. Also a change of the name (=givenName+sn) of the mail in the mongodb didn't helped to map the existing user properly. We had to rename/remove the existing user and he got a new user after a new login.

**Comment by tashalee991** [comment]
I never got the app to work. I just did it online

**Comment by Nissulya** [comment]
In the case of joao there was also a change in the spelling of his name in ldap ( "ã" changed to "a") and although we changed the name (=givenName+sn), username und the ldap "importIds" : to "CN=Azevedo\\, Joao etc. rocketchat still refused to map him to the existing user on login and throws the error: 'errorClass","message":"Username already exists. [403]","stack":"Error: Username already exists'. I suspect, this is because of the ldap-id:

"ldap" : {
                        "id" : "417a657665646f2c204a6fc3a36f20284241503435393029",
                        "idAttribute" : "name"
                },
because it seems to be built from the name attribute, but I don't know how exactly this id is built
