### ISSUE TITLE
Profile Updatation Toast 

### ISSUE THREAD

**Issue by Praashh** [RocketChat/Rocket.Chat#31529]
When I was Updating My profile details, got some weird toast, can see above 

![Screenshot from 2024-01-25 00-47-20](https://github.com/RocketChat/Rocket.Chat/assets/99237795/93dff0e2-4abf-410f-8b3f-6bab5c382262)

**Comment by rique223** [comment]
Hey Praashh, thanks for your contribution. These toasts are expected if you changed your avatar. What do you believe to be wrong with them?

**Comment by Praashh** [comment]
You are right but instead of 2 toast can we use just 1 toast which is Profile Update Successfully !

**Comment by rique223** [comment]
I believe not. The avatar update and profile update are handled separately. Therefore, we need separate messages to handle errors for each save and make it clear which operation has failed or succeeded so that the User Experience is as complete as possible. Right now I don't believe it is possible to refactor this flow as well.
