### ISSUE TITLE
Add cross button in mobile view

### ISSUE THREAD

**Issue by AnshuPathak-88825** [RocketChat/Rocket.Chat#31536]
### Description:
I would like to propose the addition of a close button in the mobile view to allow users to easily minimize the sidebar on the website. Currently, there is no convenient way to collapse the sidebar on smaller screens, and a close button would improve the user experience.

### Steps to reproduce:

1. Identify the Sidebar Component:
2. Add State for Sidebar Visibility:
3. Create a Close Button Component:
4. Integrate Close Button in Sidebar Component
### Expected behavior:
 addition of a close button in the mobile view to allow users to easily minimize the sidebar on the website

### Actual behavior:
![image](https://github.com/RocketChat/Rocket.Chat/assets/78332454/fb1d1cc4-e424-440b-8155-0d50c3470a35)
close button is not there in mobile button

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Brave:
- Window 10:

**Comment by Sayan4444** [comment]
Hi @dougfabris @hugocostadev do you want this issue to be addressed? If yes can you provide me guidance or figma so that I can work on this

**Comment by hugocostadev** [comment]
Hey guys, I'm going to check with UX/UI team, there is a sidebar redesign in place, maybe the new sidebar will cover that

**Comment by jsdgdo** [comment]
Hey @Sayan4444 , appreciate you taking the time to suggest this. I'll relay this message as a possible improvement in out upcoming sidebar changes, for my teammate working on it. 

For now however, we don't se a pressing need to make a change. Since the focus on mobile should be around touch, the solution we currently have is actually better than a dedicated close/X button would be, since the touch target (the overlay) is much bigger and comfortable, and it's also a known pattern.
