### ISSUE TITLE
Update is not possible....

### ISSUE THREAD

**Issue by AntoninHL** [RocketChat/Rocket.Chat#31564]
It looks like something has changed in the structure of what we need to download to update Rocket.Chat...

The documentation here is now false and no longer allows you to update Rocket.Chat:
`https://docs.rocket.chat/deploy/deploy-rocket.chat/updating-rocket.chat`

URL `https://releases.rocket.chat/latest/download` returns an error and therefore no more tarball...
`{"error":"not found"}`

so I can't use my auto update script

What is going on ?

**_Pro version / 6.5.2_**

**Comment by paulchen** [comment]
Releases API is broken as well, mentioned at https://docs.rocket.chat/setup-and-configure/environment-configuration/mongodb-configuration/supported-mongodb-versions

https://releases.rocket.chat/latest/info

```
{"error":"release not found"}
```

It seems to be the problem is only related to the tag `latest`, as https://releases.rocket.chat/6.5.3/info works as expected:

```
{"tag":"6.5.3","commit":"726574cfe3e15cafcad5730b399a3f78e3acc5b3","key":"build/rocket.chat-6.5.3.tgz","etag":"fefad2fc850fcbebce6f26fe88e2f2f3-37","count":248,"nodeVersion":"14.21.3","compatibleMongoVersions":["4.4","5.0","6.0"]}
```

@AntoninHL until this is fixed, you can use the link https://releases.rocket.chat/6.5.3/download to download the Tarball for 6.5.3.

**Comment by AntoninHL** [comment]
Thanks for this @paulchen!
Works for me at the moment.

**Comment by debdutdeb** [comment]
endpoint is fixed for now. We're looking into why it happened and make a permanent fix soon. Please feel free to reopen if this resurfaces.

Thank you for the reports :)
