### ISSUE TITLE
iOS app - typing a message in landscape mode and posting cuts channel chat in half when returning to portrait

### ISSUE THREAD

**Issue by rusty1281** [RocketChat/Rocket.Chat#3164]
Your Rocket.Chat version: (iOS 2.3.1)

as the title says, when i go to landscape mode and post a message, after returning to portrait mode the chat is cut in half (bottom half is missing).

**Comment by MartinSchoeler** [comment]
@rusty1281  Thanks for reporting this issue. We value your time in helping us to make Rocket.Chat great. We always try to fix confirmed problems as quickly as we can, and it appears that the issue you reported might already be fixed in the latest release. Can you please help us test it against current latest release? Much appreciated. And please remember to backup your data before upgrading, just to be safe. Cheers!

**Comment by MartinSchoeler** [comment]
Closing this due lack of updates
