### ISSUE TITLE
After updating from 6.5.3 to 6.6.0 workspace version status is unsupported

### ISSUE THREAD

**Issue by Dog1ch** [RocketChat/Rocket.Chat#31706]
### Description:

After updating from 6.5.3 to 6.6.0 workspace version status is unsupported and cant connect with my self made mobile app

### Expected behavior:

The workspace status is supported

### Actual behavior:

The workspace version is uunsupported

### Server Setup Information:

- Version of Rocket.Chat Server: 6.6.0
- Operating System: Rocky linux
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: 6

### Relevant logs:

![image](https://github.com/RocketChat/Rocket.Chat/assets/56313496/d0ee2369-f3a3-46c8-88b6-fd81dd8f3800)

**Comment by Gummikavalier** [comment]
I confirm this too

**Comment by rrmt23** [comment]
I have same problem

**Comment by sampaiodiego** [comment]
is this still happening? I tried spinning up a local instance using Docker version 6.6.0, and after cancelling the start plan subscription I got a community version working:

<img width="581" alt="image" src="https://github.com/RocketChat/Rocket.Chat/assets/8591547/2ca2b074-bcd1-4c70-a385-905a3a3501bf">

**Comment by Gummikavalier** [comment]
Yes, this is still happening. Might affect error messages on the client side too, if the client reads the status of the workspace from the server itself, and not just version numbers.

**Comment by Gummikavalier** [comment]
@sampaiodiego Today we have started getting this message in our mobile apps (downloaded from the official AppStore). I hope the native mobile app does not cut us off just because the server end thinks that the latest version is unsupported. :cold_sweat:

![Screenshot from 2024-02-22 19-17-03](https://github.com/RocketChat/Rocket.Chat/assets/6958942/5b06aa00-23be-4aec-ab4d-90c1eb5ce5eb)

**Comment by Gummikavalier** [comment]
@sampaiodiego I think the issue is that RC node cannot check the validity of the license when there is no connectivity to cloud.rocket.chat or go.rocket.chat. That triggers 'unsupported version' as a blanket solution in the check.

I am also able to reproduce this server side version support issue in airgapped systems that have an offline license.
(Actually our test system had been used to test the offline license before putting it into the production, and it still has one.)

I was able to workaround the issue in our test system by allowing the access to `cloud.rocket.chat`, `go.rocket.chat` and `gateway.rocket.chat`. I could not repeat the issue after the check had succeeded, and I assume cloud.rocket.chat out of these three.

What clearly needs fixing is the requirement for support check of offline/airgapped licensed servers. Some may have (somewhat limited) access with mobile devices via local networks, for instance, and currently this may disable those completely in two weeks.

**Comment by Trapulo** [comment]
same problem with 6.6.1 (not RC!)

**Comment by nkeilar** [comment]
Same issue here. I found out that its not syncing with the cloud. I tried to get it to sync with the cloud, also tried removing cloud registration. Nothing worked. Furthermore even if I want to upgrade to a paid model now, there seems no way to actually update. Not sure why cloud syncing isn't working but I have a pretty good idea, when I logged into the cloud console where my instance was listed, I checked the date the instance was active on the Community version. it said January 2023, to November 2023, I think this is when I did a trial of the starter account. I didn't proceed with the paid plan, do to the way users are calculated, but it seems that the community edition date was never extended past November 2023, Not sure if this is related, but sharing in case it helps isolate the issue. Anyway, I've wasted several hours on this today and not super happy about the community edition being tied to a licensing server like this, if there isn't a change from Rocket.Chat to respect communities desire to stay with Open Source Community edition without interference then we will have no option to leave, as it doesn't make economic sense for me to waste hours on this, but on principle we won't be able to move ahead with Rocket.Chat. Hopefully the embrace the community support rather than alienate us.

**Comment by sampaiodiego** [comment]
thanks @Gummikavalier .. I'm talking with internal teams to see how see how we can handle these scenarios.

**Comment by Trapulo** [comment]
same with 6.6.2

**Comment by astrale67** [comment]
> same with 6.6.2
Same

**Comment by Gummikavalier** [comment]
The issue was somewhat tricky to workaround with our premium offline license key by:

1. Allowing access to cloud.rocket.chat temporarily
2. Removing the offline premium license (by typing randon string, simply resetting does not work)
3. Restarting
4. Bypassing register setup wizard using ENV-setting/database edit
5. Setting up the offline license key again
6. Restarting again
7. And finally cutting access to cloud.rocket.chat again.

Possibly one step before pasting in the offline license key again was to online reregister for a trial version, but I cannot be sure because I tried so many things. I was able to get the offline key recognized only by points 2, 3, 5 and 6, though.

I suspect the issue may trigger again after the next update.

**Comment by Gummikavalier** [comment]
The issue did not trigger again after the update from RC 6.6.2 to 6.6.3 at least.

A look at the database hints that the registering compares and updates keys, and when those have been updated, the logic remains happy. (For now at least.)

**Comment by Trapulo** [comment]
my env reports:

Version 6.6.3
Outdated

**Comment by nkeilar** [comment]
> 4\. Bypassing register setup wizard using ENV-setting/database edit

@Gummikavalier would you mind to elaborate on this step please. Our mobile apps stopped working today. Official Rocket.Chat support seems unable/unmotivated to resolve.

**Comment by Gummikavalier** [comment]
@nkeilar There has been mentions regarding the env-variable elsewhere, but other method to set registration wizard as completed is running under mongo shell:
`db.rocketchat_settings.update({"_id":"Show_Setup_Wizard"}, {$set: {"value" : "completed"} });`

Note that this will not fix the mobile client issue. Only online registering does.

Setting the wizard as completed only allows you to get back to admin settings again, if you lost it after allowing access to cloud.rocket.chat temporarily. (This happened for me on our offline registered setup immediately after this connection was allowed.)

**Comment by nkeilar** [comment]
Updating to the latest mobile apps, seems to fix the mobile app issue. I assume something was changed, as my community edition instance still isn't syncing with the cloud licence server.

**Comment by mddvul22** [comment]
We are getting this on 6.6.3 with an up-to-date Enterprise license.  Please fix this ASAP!

**Comment by mddvul22** [comment]
We were able to resolve this by going to Administration > Subscription and clicking the “Sync license update” button.

**Comment by Trapulo** [comment]
my reports "Error during workspace sync"

**Comment by Gummikavalier** [comment]
I too got the error with "Sync license update" button. It is possible that our existing old entries (manual removal fails) at cloud.rocket.chat played into that issue.

**Comment by Gummikavalier** [comment]
Just for the record, RC 6.7.0 triggered `version not supported` on our offline registered test Enterprise setup. This did not cut off the use of the latest mobile client.

**Comment by Gummikavalier** [comment]
@diegolmello @sampaiodiego 

Our Electron RC desktop clients (3.9.14) started complaining of getting out of support in 1 day in our offline licensed production Enterprise setup.

Not  sure if it is a coincidence where the info page also falsely claims that our license ends in one day: `Version supported until Sat, 13 Apr 2024.`

We got Enterprise/Premium offline license for this particular setup this year, but it was built in April 2017 originally.

We have to sit through this, and see whether the electron client's warning actually fails to operate or not.

**Comment by Trapulo** [comment]
Our 6.7.0 has stopped working with any client yesterday, only PWA is available.
It is a nonsense to ignore this problem, the only solution for us is to switch to an other software.

**Comment by ggazzo** [comment]
> @diegolmello @sampaiodiego @tassoevan
> 
> After upgrading from RC 6.6.6 to RC 6.7.0 our Electron RC desktop clients (3.9.14) started complaining of getting out of support in 1 day in our offline licensed production Enterprise setup.
> 
> Mobile client remained good, however.
> 
> Not sure if it is a coincidence where the info page also falsely claims that our license ends in one day: `Version supported until Sat, 13 Apr 2024.`
> 
> We got Enterprise/Premium offline license for this particular setup this year, but it was built in April 2017 originally.
> 
> We have to sit through this, and see whether the electron client's warning actually constitutes as failure to operate or not.
> 
> Edit: We got another user commenting that restarting the client cleared up the warning and it did not trigger anymore, at least immediately. We'll follow and report the situation.

Can I see our `/api/info` result?

**Comment by Gummikavalier** [comment]
> @Gummikavalier
> Can I see your `/api/info` result?

There you go:
```
{"version":"6.7","minimumClientVersions":{"desktop":"3.9.6","mobile":"4.39.0"},"supportedVersions":{"signed":"signing_key_redacted_by_gummi"},"success":true}
```

I removed the incredibly long signing key from the output. It was over 9000 characters long.
Our offline license for this instance was acquired in December 2023.

In the other news; after that 13 Apr 2024 has now passed this setup dropped as non supported:

![Screenshot from 2024-04-14 10-46-57](https://github.com/RocketChat/Rocket.Chat/assets/6958942/acbe5cb7-3910-4606-9cf3-a23df3ad8d32)

Mobile clients gave us a warning that the app stops working in 14 days.

**Comment by Gummikavalier** [comment]
I was able to activate the offline premium license with just these 6 steps. (Earlier description was 10 steps.)

1. Delete your existing workspace at cloud.rocket.chat
2. Open up access to cloud.rocket.chat in the firewall. (This immediately triggers the registration wizard.)
3. Register for a new premium trial license by completing the registration wizard
4. Press `Sync license update` on `/admin/subscription` page
5. Close down the access to cloud.rocket.chat again
6. On `/admin/settings/Enterprise` (aka Premium) replace the trial license code with the offline license code

You are done. After this refresh on the `/admin/info` page is all ok and the ending date for compliance is `Version supported until Fri, 1 Nov 2024`. Which is not ok but buys time.

Restart was not required. I tested that the fully compliant status survived the restart, though.

Because this is production service I cannot use this for testing/troubleshooting much. We'd need an offline license key for our test environment. (A license key that would have zero risk of screwing up the production registration.)

It may or may not be of importance that the exact length of the signed key under `/api/info` dropped from `9104` characters to `8103`. For the other parts there were no changes to the output.

**Comment by ggazzo** [comment]
@Gummikavalier I think this should solves your problem #31706

also deleting `Cloud_Workspace_Supported_Versions_Token` setting should also solve

**Comment by Gummikavalier** [comment]
> @Gummikavalier I think this should solves your problem #31706
> 
> also deleting `Cloud_Workspace_Supported_Versions_Token` setting should also solve

Thanks! :hugs:

**Comment by Gummikavalier** [comment]
I confirm this working for our Enterprise/Premium offline licensed setup. When loading the page there is a tenth of a second flash of "not supported status" (so quick that you can only make out the red label around it), but it then sets for all ok.

**Comment by tangramor** [comment]
I met the same problem on 6.7.0 in our inner network environment.
I upgraded the server to 6.7.2 and the client can open correctly.
But I am not sure if it is really fixed...

**Comment by Gummikavalier** [comment]
RC 6.9.1 suffers from `not supported` again in our test environment.

RC 6.8.1 is ok in both test and production.

https://github.com/RocketChat/Rocket.Chat/issues/32600

**Comment by nkeilar** [comment]
Yes, also seeing the message back...6.9.1 Outdated... and Not supported - *sigh*
