### ISSUE TITLE
Compability issue ESET Smart Secrurity

### ISSUE THREAD

**Issue by lunitic** [RocketChat/Rocket.Chat#3174]
Your Rocket.Chat version: 0.28 and rocketchat demo server
Seems to be some compability issues with ESET Smart Security in Windows 10.

Made a clean installation of W10 and everything worked.

After installing  ESET Smart Security  (30 days trial available) the following error shows up in the console.

![image](https://cloud.githubusercontent.com/assets/17207375/15107136/400b8658-15ce-11e6-9bc0-87ac0a2c603d.png)

Nor sure if this is an RC or ESET issue..

**Comment by lunitic** [comment]
We have opened a case towards ESET also.. They are investigating it.

Seems to be issue with SSL interception in their security application.

**Comment by geekgonecrazy** [comment]
@lunitic can you click the lock and click details:
![image](https://cloud.githubusercontent.com/assets/51996/15167590/bb43d1fa-16ef-11e6-9bf9-a9cc0db8077f.png)

Then click view certificate:

![image](https://cloud.githubusercontent.com/assets/51996/15167601/cc138a20-16ef-11e6-96e8-e69601ed9ab5.png)

Curious if its messing with the certs or not

**Comment by lunitic** [comment]
@geekgonecrazy 

UGLY AS HELL..  

![image](https://cloud.githubusercontent.com/assets/17207375/15170774/35ed8348-1749-11e6-88bb-3808438d1846.png)

**Comment by geekgonecrazy** [comment]
Yup they are intercepting and throwing their own SSL certs on it. 

Since its trying to inspect all traffic, it likely hates persistent connections like websockets.  

At any rate, this is for sure ESET's fault.  Nothing to my knowledge we can do to prevent it from touching our traffic. 

I doubt they are going to change it either... Maybe they will show you a way of turning that off.  Otherwise i'd seriously reconsider using their software :smile:

Feel free to log your end resolution here.  👍

**Comment by Molle500** [comment]
I was in contact with ESET a few days ago and recieved an email from them today telling me it's fixed :+1: 

Working with the upcoming patch!

**Comment by geekgonecrazy** [comment]
@Molle500 awesome!  👍
