### ISSUE TITLE
Rocket.Chat Developer Docs Survey

### ISSUE THREAD

**Issue by hugocostadev** [RocketChat/Rocket.Chat#31931]
Hello Rocket.Chat Community,

We’re on a mission to improve [community documentation](https://developer.rocket.chat/) and need your help! Your feedback will guide us in making our docs more helpful for users and contributors alike.

Please spare a moment to fill out our quick survey:

https://forms.gle/Zjx1fJUMMG9TdoWf7

Your insights are crucial for us to provide the best support and resources. Thank you for helping us make Rocket.Chat even better!

Best,
The Rocket.Chat Team

**Comment by huntermarchi** [comment]
want to contribute to this and fix this

**Comment by Garvanand** [comment]
### Following are some ways by which we can effectively improve community documentation and increase survey reach.

Include in Newsletter or Blog Post: If Rocket.Chat has a newsletter or blog, consider featuring the survey in upcoming editions or posts. This can help reach a wider audience of users and contributors.

Follow-up Reminders: Send periodic reminders about the survey to ensure that community members who may have missed the initial announcement have another opportunity to participate.

Expressing Gratitude: Showing appreciation to participants for taking the time to provide feedback. Consider acknowledging their contributions publicly or sending thank-you messages to demonstrate that their input is valued.

Kindly assign the issue to me ,so that I can raise a PR and work more upon the idea

**Comment by Visbhavesh** [comment]
I wanted to work in thus issue please allow me to work on this issue.
