### ISSUE TITLE
Releases are not installable

### ISSUE THREAD

**Issue by icelake102** [RocketChat/Rocket.Chat#32503]
gc-stats@1.4.0 is no longer reachable

**Comment by reetp** [comment]
> Can you please complete a proper bug template.

We have no idea how you have hit an issue.

Please describe it in more depth.

Thanks.

**Comment by broadcast98** [comment]
ERROR MESSAGE:
`node-pre-gyp ERR! install response status 403 Forbidden on https://node-binaries.s3.amazonaws.com/gcstats/v1.5.0/Release/node-v83-linux-x64.tar.gz`

can't install gc-stats , because the file is not exists on amazonaws.

WHY THIS ISSUE  existed for more than a year?

are there new users download and install the new versions?

why the new versions are released without any installing check?

**Comment by reetp** [comment]
> Can you please complete a proper bug template.

As I said before.


> WHY THIS ISSUE existed for more than a year?

It's open source.

What have you done to fix it? Assumingnit is a bug, and not because you haven't read properly.

> are there new users download and install the new versions?

Suggest you read all the docs.

Start here.

https://developer.rocket.chat/v1/docs/server-environment-setup

And then this. All of it including links.

https://gist.github.com/reetp/a66149d5f060f260643a353ca7067a98#rocketchat---asking-for-help

Then read all the code in github. Before you ask such questions.

> why the new versions are released without any installing check?

They aren't. 

Last, note github is not for support issues. Ask those on open.rocket.chat

Thanks.

**Comment by broadcast98** [comment]
> > Can you please complete a proper bug template.
> 
> As I said before.
> 
> > WHY THIS ISSUE existed for more than a year?
> 
> It's open source.
> 
> What have you done to fix it? Assuming it is a bug, and not because you haven't read properly.
> 
> > are there new users download and install the new versions?
> 
> Suggest you read all the docs.
> 
> Start here.
> 
> https://developer.rocket.chat/v1/docs/server-environment-setup
> 
> And then this. All of it including links.
> 
> https://gist.github.com/reetp/a66149d5f060f260643a353ca7067a98#rocketchat---asking-for-help
> 
> Then read all the code in github. Before you ask such questions.
> 
> > why the new versions are released without any installing check?
> 
> They aren't.
> 
> Last, note github is not for support issues. Ask those on open.rocket.chat
> 
> Thanks.

"So, how do you check things before release that such obvious bugs still make it through? Are you a bunch of laughing monkeys?!"
