### ISSUE TITLE
Authentication on the device constantly resets

### ISSUE THREAD

**Issue by NikitaGBS** [RocketChat/Rocket.Chat#32536]
### Description:

Authentication on the device constantly resets.

### Steps to reproduce:

1. Open the application.
2.  Select the server.
3. Enter the login and password.
4.  Close the application from the background.
The server selection window constantly opens.
### Actual behavior:

![IMG_7393](https://github.com/RocketChat/Rocket.Chat/assets/47414795/8a980585-e1b5-43a5-9604-3d253261d90c)

### Client Setup Information

- iOS (iPhone 15 pro max)
- 4.49.0.61154 version app

**Comment by reetp** [comment]
You have not filled in a bug template so provided insufficient information about your issue to determine what is happening, but the most common problem is incorrect server setup.

This is a support issue rather than a bug.

If you have a Pro or Enterprise subscriotion please open a support  request.

Otherwise please ask in:

https://open.rocket.chat/channel/support

Or 

https://forums.rocket.chat/
