### ISSUE TITLE
Rocket chat desktop version for Mac no longer works

### ISSUE THREAD

**Issue by commishjw** [RocketChat/Rocket.Chat#32562]
Just keep getting black screens (see attached)
<img width="933" alt="Screen Shot 2024-06-05 at 8 34 08 AM" src="https://github.com/RocketChat/Rocket.Chat/assets/171835552/d1523d84-ffae-42f1-a4a9-0417f909246b">

**Comment by reetp** [comment]
You have provided zero information to assist debugging.

Please re-open in the correct repo and provide server and client information as per the bug templates. We can't help you without that.

https://github.com/RocketChat/Rocket.Chat.Electron

**Comment by commishjw** [comment]
What the hell is the matter with you? I'm not a techie. Repo? Server and client information? The software has worked just fine for years and no longer does. Reinstallation did not fix.

**Comment by reetp** [comment]
> What the hell is the matter with you? I'm not a techie. Repo? Server and client information? The software has worked just fine for years and no longer does. Reinstallation did not fix.

Please be more civil. This is open source, not paid support. If you are going to be rude you are going to be ignored and get zero help.

You may not be a 'techie' but if you are reporting bugs you will have to provide some technical information somehow or no one can help you.

Do you manage your own server?

If your server has a paid Pro or EE licence then you should contact support directly.

Is your server accessible from a web browser?

If it is not then you need to copy and fill in the template details from here and paste it below - don't open a new bug.

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&projects=&template=bug_report.md

If the server is accessible from a browser then the issue is with your client, not your server and then correct repository (repo) for issues with the app is:

https://github.com/RocketChat/Rocket.Chat.Electron

The bug template is here.

https://github.com/RocketChat/Rocket.Chat.Electron/issues/new?assignees=&labels=type%3A+bug&projects=&template=bug-report.yml&title=Bug+title

If you don't complete it then no one can help you.

We need to know server and app details. At a vague guess you have upgraded the Rocket client app to 4.0.0 and something has broken in the app, but we can't tell without knowing more about that, and the server.

Thanks.

**Comment by commishjw** [comment]
Apologies….

I have never downloaded an app from the Apple store to a Mac desktop and just gotten a black (not blank) screen when trying every menu item in the software.

Something is incompatible and I can’t be bothered to try to fix. Will use the web version of chat rather than the desktop version. Many others have reported this problem in the past. Solutions don’t seem easy.

You can close my case.

**Comment by reetp** [comment]
>  I have never downloaded an app from the Apple store to a Mac desktop and just gotten a black (not blank) screen when trying every menu item in the software

Bugs occur.

> Something is incompatible and I can’t be bothered to try to fix.

Well, that's sad but we can't fix your issue without some detail.

>  Will use the web version of chat rather than the desktop version.

If that works we at least know your server is running, so it isn't a bug for this repo.

> Many others have reported this problem in the past.

Where? Without detail we can't know it's related

> Solutions don’t seem easy.

They aren't without information.

I did a rough 'how to' on debugging several years ago.

This may help you help us to help you (open source is a two way street), especially the links on "How to report bugs effectively" and "How to ask smart questions"

https://gist.github.com/reetp/a66149d5f060f260643a353ca7067a98

If you want us to look at your issue open a new bug in the Rocket.Chat Electron repo with some server & client details, particularly server version, client version and Mac hardware/OS and we'll take a look and try to fix it for you and others.

Thanks.

**Comment by commishjw** [comment]
I found and installed the prior version of the software for Mac desktop and everything works again. Thanks for your patience.

**Comment by reetp** [comment]
FYI it seems that this may be a caching issue, but you cannot reset the cache with the Mac App store version but you can with the github version available here (depending on your company policies). 

https://github.com/RocketChat/Rocket.Chat.Electron/releases

Not tested on Windows.

This should be opened in the Electron repo.

**Comment by reetp** [comment]
There may be another issue with certain videos playing under Mac.

**Comment by reetp** [comment]
For reference

"Disable Hardware Acceleration is the solution for now. Per Electron expert this is a problem on hardware"
