### ISSUE TITLE
The latest version 6.9.1 not supported

### ISSUE THREAD

**Issue by lovekyleman** [RocketChat/Rocket.Chat#32600]
As you can see the photo below 
![image](https://github.com/RocketChat/Rocket.Chat/assets/93461213/c522c23d-3cf3-499d-b836-a104ebdc4fb7)

**Comment by LiloBzH** [comment]
Hello

Same issue here. With the last docker version, i have the same error.

**Comment by lovekyleman** [comment]
> Hello
> 
> 
> 
> Same issue here. With the last docker version, i have the same error.
> 
> 

That's not good 😆😆

**Comment by chotaire** [comment]
Ooookay!

![acb0f2a270447d88f124d912dbd83bef](https://github.com/RocketChat/Rocket.Chat/assets/9246549/71d973c0-f865-43d2-9d82-9ceec6481b5f)

![27424ed55b4a755e715b62d489002958](https://github.com/RocketChat/Rocket.Chat/assets/9246549/45193234-d211-4377-a56d-c952f15bce4d)

**Comment by Gummikavalier** [comment]
Same in our test server too with 6.9.1.

No issues with 6.8.1.

**Comment by ryanvito** [comment]
I've had mixed results. I've been able to restart the container and occasionally it shows up as supported. Not sure if the variability helps.
![image](https://github.com/RocketChat/Rocket.Chat/assets/4916594/8af32368-b817-4d79-a4ed-46d4ef40c1c7)

**Comment by casalsgh** [comment]
Checking into it folks, will provide updates ASAP

**Comment by lovekyleman** [comment]
> I've had mixed results. I've been able to restart the container and occasionally it shows up as supported. Not sure if the variability helps.
> 
> ![image](https://github.com/RocketChat/Rocket.Chat/assets/4916594/8af32368-b817-4d79-a4ed-46d4ef40c1c7)
> 
> 

Restart RC can't help here. Still not supported

**Comment by thokich** [comment]
Hello

Same issue here. With the last docker version, i have the same error.

**Comment by chotaire** [comment]
After reading https://github.com/RocketChat/Rocket.Chat/issues/31706 and seeing that nobody of the Rocket.Chat team actually ever really resolved this (or gave instructions on how to resolve this), I will cease updating our production Rocket.Chat instance until I see green light here that the issue has been resolved for everyone.

From my understanding this is not just a warning message. This would disconnect all mobile clients after max. 14 days if I read correctly. 

It is absolutely unbelievable how scared one must always be to update this piece of software.

**Comment by lovekyleman** [comment]
> After reading https://github.com/RocketChat/Rocket.Chat/issues/31706 and seeing that nobody of the Rocket.Chat team actually ever really resolved this (or gave instructions on how to resolve this), I will cease updating our production Rocket.Chat instance until I see green light here that the issue has been resolved for everyone.
> 
> 
> 
> From my understanding this is not just a warning message. This would prevent all mobile and Electron clients from connecting after max. 14 days if I read correctly. 
> 
> 
> 
> It is absolutely unbelievable how scared one must always be to update this piece of software.

Yeah. After that I will carefully update my RC server. RC has a lot of bugs but seems no one really cares about them.

**Comment by reetp** [comment]
Please note that this is with the dev team for urgent attention.

> RC has a lot of bugs but seems no one really cares about them.

I think if you look you will see we have paid a lot more attention to bugs here recently (you are not aware of the internal systems that Rocket uses and the work that goes on behind the scenes).

Gabriel Casals and I have recently been working on getting clear issues resolved/fixed. Some of those will come to pass in due course, but it takes a while to filter through with all the competing priorities that the dev, product and sales teams have. Clearly if you have paid support you can contact support immediately.

Otherwise note that this is open source. The source is there. There is no guarantee about anything else.

However, I am pretty sure there will be a resolution to this fairly quickly.

-----------

Please note also.

Anyone here using docker with 'latest' should go and change that **immediately**.

You should NEVER use 'latest' unless you are either developing, or like nasty surprises.

For production fix your versions, watch for issues, upgrade on your own schedule, save yourself grief.

https://docs.rocket.chat/deploy/deploy-rocket.chat/deploy-with-docker-and-docker-compose

> Set the RELEASE variable in the .env to your desired Rocket.Chat version.

> See our [releases page](https://github.com/RocketChat/Rocket.Chat/releases) and [available docker images.](https://docs.rocket.chat/deploy/deploy-rocket.chat/deploy-with-docker-and-docker-compose#rocket.chat-docker-images) Keeping the default release as latest is not recommended.

Personally I _never_ run with the latest releases - I always stay 0.1 behind so currently on 6.8.x 

YMMV.

**Comment by lovekyleman** [comment]
Someone reported this "not supported" problem 4 months ago and this bug still there. This is unbelievable

**Comment by chotaire** [comment]
@reetp Thank you for the clarification, it's good to hear this is high on the priority list.

**Comment by reetp** [comment]
NP.

(No need to @ anyone - we do read)

**Comment by casalsgh** [comment]
Team, fixes are on it's way and so are adjustments to our automated tests. Gathering info on any actions that might be needed from admins. Please bear with me on this one.

**Comment by chotaire** [comment]
> I think if you look you will see we have paid a lot more attention to bugs here recently (you are not aware of the internal systems that Rocket uses and the work that goes on behind the scenes).

Yes, the number of showstopping issues that wreck installations have reduced. 

> 
> Gabriel Casals and I have recently been working on getting clear issues resolved/fixed. Some of those will come to pass in due course, but it takes a while to filter through with all the competing priorities that the dev, product and sales teams have. 

That is great to hear.

> Otherwise note that this is open source. The source is there. There is no guarantee about anything else.

Nobody will ever guarantee bugfree software, whether that is opensource or not.

> Anyone here using docker with 'latest' should go and change that **immediately**.
> You should NEVER use 'latest' unless you are either developing, or like nasty surprises.

While "not using latest tag in docker" is known practice, the problem lies elsewhere. Please let me elaborate:

a) The latest major version is neither flagged pre-release, nor being on a dev branch, nor otherwise noted unstable. It is assumed latest stable version which is under support. 
b) Rocket.Chat major versions have an extremely short lifecycle and new major versions are released very quickly. This only lets admins assume it is about time to update to stay on track with development.

> For production fix your versions, watch for issues, upgrade on your own schedule, save yourself grief.
> 
> https://docs.rocket.chat/deploy/deploy-rocket.chat/deploy-with-docker-and-docker-compose
> 
> > Set the RELEASE variable in the .env to your desired Rocket.Chat version.
> 
> > See our [releases page](https://github.com/RocketChat/Rocket.Chat/releases) and [available docker images.](https://docs.rocket.chat/deploy/deploy-rocket.chat/deploy-with-docker-and-docker-compose#rocket.chat-docker-images) Keeping the default release as latest is not recommended.
> 
> Personally I _never_ run with the latest releases - I always stay 0.1 behind so currently on 6.8.x

This is very vital info coming from a dev. This should be extremely visible on the main page of this git. And in many other places. Users should be warned that the latest major version is not assumed stable, that there exists no dev branch and no beta releases. That users are advised to stay one major version behind. This would save countless of admins from extraordinary headache or worse. 

Had I not always tested on test instances AND created snapshots of the production instance before upgrading or even just updating to a new minor release, I'd have killed our production instance a remarkable number of times already, or lets say I would have been forced to switch to a different product because users were no longer able to work as expected.

All this because it has never been clear to me that "latest stable" is not stable. May I please suggest that this is made much more visible, or that you would consider to open a dev branch or to the least flag latest major version as pre-release or otherwise make it more obvious?

Please do not forget, there are no downgrade options. This gets even more difficult with docker installations. Please help users make the best choice and, if you are not reconsidering your release strategy, at least make an effort by documenting this as visibly as you can.

Thanks for your time.

**Comment by reetp** [comment]
This is not really the place for a wider discussion on Rocket - this is a bug tracker - and you should really be discussing this on open.rocker.chat  However, some of your comments make assumptions that may mislead others and need correcting.

NB. I am not a dev. I did work for them for a period a few years back and understand the internals but I do not get paid by Rocket now - I am just a trusted community member.

I am a small sysadmin with a bit of experience. I have used Rocket since around 0.16 and learned a few lessons along the way.

I follow my OWN release schedule. It is sensible and cautious. I am merely suggesting that as an admin you should consider a similar strategy for your own good.

> While "not using latest tag in docker" is known practice, the problem lies elsewhere.

No, that is it. Period. Don't use it. It has inherent issues. Update to a fixed version when you are happy with it.

Release are releases. Development etc is in github on branches, usually develop. Not in docker images. They are just a snapshot of development. That will not change.

When they feel code is suitable for release they do so -  usually following their agile release plans. They release RCs about 10 days prior from the 20th and then a full release on or about the 30th.

This has been going on quite a while now since they went to a rapid release schedule several years back.

A release is zero guarantee of stable. In reality what code is?

It is a release that they consider is OK to go as they have performed some testing and QA. But the risk to upgrade is entirely yours. Do your due diligence. It is why it is stated in the docs NOT to use latest. That is warning enough.

> Had I not always tested on test instances AND created snapshots of the production 

That is just prudence and good admin. 

> It is simply the case that most users consider a latest major version being stable.

Assumptions. There are a thousand quotes on their dangers. That is because IME most users don't read enough and make badly informed decisions, usually based on information and sales pitch from companies who should know better.

Please, write some more to help users how to administer a Rocket server and do a PR on the docs repo.

> Windows 11

What makes you think that any released version of Windows ever was stable? Who told you that ? Microsoft? Why do they have Enterprise versions where admins can pin releases instead of auto upgrading if they were so solid and stable and reliable? Desktop users dogfood for Enterprise.

> release strategy: release early, release quickly,

It is not my choice. It is the way they operate. Understand it and adapt accordingly.

>  would personally recommend a dev branch to prevent the obvious.

It's here. They just don't build a docker image. You could if you really wanted to - the tools are here.

https://github.com/RocketChat/Rocket.Chat/tree/develop

For further discussion you can get hold of me as `reetp` in 

https://open.rocket.chat/channel/support

Can we now please close comments unless they **strictly** relate to the bug, and wait for your fixes to land.

Thank you.

**Comment by casalsgh** [comment]
The internal team still working on a solid fix for it. Expect a new patch 6.9.2 containing the fix to be shared soon. 
Adjustments are being made also to prevent such an event from happening again.

**Comment by casalsgh** [comment]
From reetp as a nice reference -> https://gist.github.com/reetp/ddd0580ab9f9397715da1c14cd85a73c

**Comment by casalsgh** [comment]
Folks, Patch released are out and to fix the situation, please upgrade to any of the following versions 6.5.8, 6.6.10, 6.7.5, 6.8.2 and 6.9.2
