### ISSUE TITLE
Powered by rocket.chat

### ISSUE THREAD

**Issue by djeber** [RocketChat/Rocket.Chat#3270]
Your Rocket.Chat version: (30)
how can i modify the"powered by rockethat" on the login page !!

**Comment by zxweed** [comment]
+1. The logo I have uploaded are shown on the login page only...

**Comment by yuchaozh** [comment]
@zxweed Hi, I am also working on customize the rocket chat for the login page. But I do not know where to start. Can you tell me which file is for the login page?

Thanks.

**Comment by zxweed** [comment]
@yuchaozh you should edit the files Rocket.Chat/programs/web.cordova/app/images/logo/logo.svg / Rocket.Chat/programs/web.browser/app/images/logo/logo.svg by any SVG Editor, like Inkscape

**Comment by vyasjay2793** [comment]
Hello,
Can someone help me that how i modify the"powered by rocket.chat" on the login page??

**Comment by jszaszvari** [comment]
You can hide/remove it with some custom CSS.

Go into Settings -> Layout -> Custom CSS and pop this in there

.powered-by {
  display: none;
}





On 22 April 2017 at 7:09:57 pm, Jay Vyas (notifications@github.com) wrote:

Hello,
Can someone help me that how i modify the"powered by rocket.chat" on the
login page??

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/RocketChat/Rocket.Chat/issues/3270#issuecomment-296359663>,
or mute the thread

**Comment by vyasjay2793** [comment]
@jszaszvari Thank you dear.

It's worked!

**Comment by rahul7471** [comment]
@vyasjay2793 @jszaszvari does this css apply for live chat window??
where these css get applied.
I tried but it did not work. 
needed urgent help.

**Comment by vyasjay2793** [comment]
@rahul7471 
As mentioned by @jszaszvari that's the right path, that already i've applied but currently i've uninstalled so i could not get proper path for you!

@jszaszvari if you could plz help him to get this sorted out!

**Comment by shahzad285** [comment]
@JSzaszvari 
I added the custom css to hide the logo but it didn't work for me. Do I need to do anything? Please let me knwo

**Comment by durdenclub** [comment]
I have installed Rocket.Chat via Snap in Ubuntu 18. Can you please help me to remove this "powered by" thing ? 
Thanks

**Comment by MuneebKalathil** [comment]
I have added following in **/opt/Rocket.Chat/programs/web.browser/app/livechat/1.chunk.0c6a0.css**

_.powered-by__3NpjT{display:none;}_

Version 3.3.3

It is not snap. Manual Installation.
