### ISSUE TITLE
Bug: Bottom of left channel list is cut off

### ISSUE THREAD

**Issue by KervyN** [RocketChat/Rocket.Chat#3284]
Your Rocket.Chat version: 0.31.0
If all channels do not fit into the sidebar, you are not able to scroll to the bottom. There are some pixels missing. 
See screenshots. I scrolled down to the bottom:
![bildschirmfoto 2016-05-18 um 12 26 37](https://cloud.githubusercontent.com/assets/1584820/15355599/fb5720e4-1cf3-11e6-96fe-e43db215adc7.png)

Theres is the "private groups" section including one private group missing. This applies only to the end of the list. See 2nd screenshot. There are the last two channels missing.
![bildschirmfoto 2016-05-18 um 12 30 35](https://cloud.githubusercontent.com/assets/1584820/15355689/7d87dae0-1cf4-11e6-974f-33fa56083bc6.png)

Tested in the OSX App, Firefox and Chrome.

Best regards
 Boris

**Comment by mnt** [comment]
@KervyN 

Would you please try to reproduce the problem on Rocket.Chat version: 0.34.0? 

I tried reproducing this bug but didn't find any problems.

1. I made enough channels so that the sidebar does not reach the bottom.

![untitled-3](https://cloud.githubusercontent.com/assets/8972761/16289902/dcfcf318-392b-11e6-864f-ad893ecfe9a2.jpg)

2. I scrolled down and found no problems.

![untitled-5](https://cloud.githubusercontent.com/assets/8972761/16289908/e9aaf222-392b-11e6-9dfb-c9ae1927f27d.jpg)

P.S I even tried to create a few direct messages but still did not find the bug.

**Comment by KervyN** [comment]
Yep, it's fixed. Thanks a lot.
