### ISSUE TITLE
An error occurred during installation on Ubuntu

### ISSUE THREAD

**Issue by tangalan83** [RocketChat/Rocket.Chat#33083]
https://docs.rocket.chat/docs/deploy-with-ubuntu

Bash
cd /tmp/bundle/programs/server && npm install --production

found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

Bash
npm audit --parseable

review  tar     moderate        >=6.2.1 Denial of service while parsing a tar file due to lack of folders count validation https://github.com/advisories/GHSA-f5x3-32g6-xq36       node-pre-gyp>tar

How to fix this error？ thanks!

**Comment by Dhruveren** [comment]
You can try to update the tar package  `npm update tar --depth 3`

**Comment by reetp** [comment]
> How to fix this error？ thanks!

This looks like a support request rather than a bug.

If you log an issue you must fill out a bug template properly to help us understand the situation.

If you are using Ubuntu you may  be better of with snaps for easier installation.

https://docs.rocket.chat/docs/deploy-rocketchat#recommended-deployment-methods

All of this is support so can we please take it to either https://forums.rocket.chat or [https://open.rocket.chat #support ](https://open.rocket.chat/channel/support)

Thanks.
