### ISSUE TITLE
pdf viewer not display content in storage type mode webdav 

### ISSUE THREAD

**Issue by rze0** [RocketChat/Rocket.Chat#33251]
### Description:

PDF viewer not display content in storage type mode webdav In the browser and in Desktop Clients windows.
If you change the storage type to GridFS, it displays correctly.

### Steps to reproduce:

1.  Switch storage type to webdav
2.  upload a file to chat
3.  сlick the file name

### Expected behavior:

Display the content in the same way as in storage type GridFS.

### Actual behavior:

1. webdav https://i.imgur.com/QAR3i2K.png browser https://i.imgur.com/BLjncGW.png not work
2.  settings https://i.imgur.com/k1L0it5.png and try https://i.imgur.com/1HXZjTE.png
3. GridFS https://i.imgur.com/9RcDlM5.png work (switched mode, uploaded a new file, checked.)

### Server Setup Information:

- Version of Rocket.Chat Server:  6.12.0
- License Type: Community
- Number of Users: 20-30
- Operating System: Debian 11
- Deployment Method:  tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v14.21.3
- MongoDB Version: 5.0.26

### Client Setup Information

- Desktop App: 4.0.2
- Browser Version: Chrome 128.0.6613.121
- Operating System: W11 Pro 64Bit

**Comment by reetp** [comment]
You should be using a reverse proxy + https on your rocket server - not http/3000.

You should set your webdav up in a similar way. You don't tell us what system you are using. Nextcloud or a.n. other?

Gridfs will work as it is effectively an "internal" link and serving the file correctly.

Likely the webdav url/file is being served incorrectly.

I think this is an issue with your webdav, not rocket.

**Comment by reetp** [comment]
So yoor working version does what is meant to with Rocket and WebDav, correct?

**Comment by rze0** [comment]
> So yoor working version does what is meant to with Rocket and WebDav, correct?
Uploading files to chat works. Downloading files from chat work. Pdf viewing does not work. It is displayed as in the screenshots above.

**Comment by rze0** [comment]
> When it fails does it only do it in the client, or both client and browsers?
> 
> Your fails above point to the client?

Client and browsers, Desktop App: 4.0.2, Browser Version: Chrome 128.0.6613.121.
Screenshots are taken in the desktop client.
I reconfigured the webdav server to https with the correct certificate. But it didn't work. Settings https://i.imgur.com/Ro4L0AK.png

I also brought up TrueNAS and tried to configure through it. webdav http. But that didn't help either.

**Comment by reetp** [comment]
Pretty sure that this is a mime type issue and your webdav or web server is not serving up the right file type - it is sending plain text and not application/pdf

Without trying to teach you to suck eggs have you checked your mime type settings? Both in Rocket and in your web server?

A search on the interwebs for something like "nginx mime type" may assist.

Also have you tried testing local file storage as well (using your web proxy - not accessing via localhost:3000)?

**Comment by akshayw1** [comment]
Can I work on this issue?

**Comment by reetp** [comment]
> Can I work on this issue?

First see my earlier response 33331. You do not need to ask, and no one assigns things, but you do need to understand how the organisation works. Best to ask on open.rocket.chat

Second do you even understand the issue? Can you replicate it, because if you can't, how do you know what to fix? 

If you read all the comments - which you really must do - you will see more information is required.

**Comment by IMPORTASIA115** [comment]
Hello, I have felt a moral responsibility to share with the community something that happened to me. After some time, having 10 users and very long conversations, everything became slow. When I checked, like one does with WhatsApp, the chat history from a long time ago, it took more than a minute to load an image from over 8 months ago. Uploading videos took a long time, and sometimes audio messages wouldn’t upload for users, requiring a retry.

The simple solution I was looking for, and I think it would have been good to configure from the beginning, is as follows: go to Workspace, Settings, File Uploads, select Filesystem as the storage type. Then, download and add the path to the folder you created with mkdir and set permissions with chown, preferably in the same /opt directory as Rocket.Chat.

Why does this happen? Because the default option, GridFS, makes MongoDB partition the file into many parts, and this means that if many clients are accessing at the same time, MongoDB becomes overloaded. I have modified it, and now it works great; uploading videos and other files is quick.

Recommendations: have good storage and RAM; in my case, I have 25 GB of RAM and 1 TB of disk because files will be called directly without being divided as MongoDB did. The PDFs are now working correctly with Rocket.Chat’s viewer, which previously had issues.

**Comment by reetp** [comment]
Read the docs.


> Though GridFS is used in Rocket.Chat for file storage because MongoDB offers this functionality with zero configuration; 

> ** it is not recommended for day-to-day file storage needs in a production environment because it puts an immense amount of load on the database.**

https://docs.rocket.chat/docs/recommendations-for-file-upload

Also look for two repos on migrating old files to file storage which will speed it up.
