### ISSUE TITLE
fail to install "gc-stats"! 

### ISSUE THREAD

**Issue by broadcast98** [RocketChat/Rocket.Chat#33369]
In the search results for "gc-stats", about fail to install "gc-stats". I found that multiple people have submitted the same issue over the past year. 

I notice that you repeat silly "issue template" in every response.  

If you’re not a technical person, it’s your job to confirm issues and submit them to the technical team, rather than closing all the problems.

**Comment by reetp** [comment]
> In the search results for "gc-stats", about fail to install "gc-stats". I found that multiple people have submitted the same issue over the past year.

Yup there is a clue in that.

Read the docs. All of them.

> I notice that you repeat silly "issue template" in every response.

I do because decades of experience helping triage bugs tells us that if the issue is documented correctly it is much easier to determine it is actually an issue or just a support request. Hence a simple to use template is provided for you.

That saves a lot of people a lot of time.

> If you’re not a technical person, it’s your job to confirm issues and submit them to the technical team, rather than closing all the problems.

It's not my job. I don't work for Rocket. I am a long time open source contributor trying to help people. I have a good idea of whats a bug and what is not.

If it looks like a bug I'll ask the team to take a look. But to do that it needs a lot of information.

Note. You are the one asking for help, not me.

Also note your attempts at abuse such as adding & deleting comments are noted and posted for others to see.

> Are you suffering from psychological issues? You should seek help from a psychologist. This job is not suitable for you.

> So, how do you check things before release that such obvious bugs still make it through? Are you a bunch of laughing monkeys?!"

![Screenshot_20240926_101607_GitHub.jpg](https://github.com/user-attachments/assets/00d4a9ea-391c-44b3-beba-0643af35f76f)

Note my comments here about abuse.

https://gist.github.com/reetp/a66149d5f060f260643a353ca7067a98#how-to-ask-for-help

And read the rest of it. You'll help yourself.

Thanks and have a nice day.
