### ISSUE TITLE
workspace is not registered

### ISSUE THREAD

**Issue by dahaiaqsw** [RocketChat/Rocket.Chat#33674]
i'll take 1-4 step to launch my workspace, but in the 4th step，it shows workspace is not registered even though the email verification has been successful,
rc.version: 6.5.3
mongo:6.0.3

and i still try the latest version,  set OVERWRITE_SETTING_Show_Setup_Wizard=completed and db.rocketchat_settings.update({"_id":"Show_Setup_Wizard"}, {$set: {"value" : "completed"} });

But it never works.  help me pls!

![Snipaste_2024-10-19_13-23-54](https://github.com/user-attachments/assets/679089ca-5c75-43ec-86f3-017643f95c49)

**Comment by reetp** [comment]
Please search first before opening issues. This has been answered before. Disposable addresses are not permitted. 

https://github.com/RocketChat/Rocket.Chat/issues/32805#issuecomment-2232991244

**Comment by hgw77** [comment]
Can you tell me what do you mean with `Disposable addresses are not permitted` because I have the same problem. I use my regular `gmx` address. When I get the confirmation Email and click the link I see the success message in the browser. Then when I open the Tab where the wizard is still open I can see the `Workspace is not registered` popup (like in the image above). 

I tested so far Version `7.0`,`6.13` and `6.10.7` with the same result. That is very annoying. I tested also the older `6.3.4` version. With this version the registration is working.

**Comment by reetp** [comment]
> Disposable addresses are not permitted

Use a proper domain. `me@myoffice.com` or `me@myorg.net`

The likes of hotmail, gmail or other generic (disposable) domains are not permitted.

**Comment by barnabynagy** [comment]
I use a mydomain.com email and I have the same exact issue. Created the image on railway.app

**Comment by Nasnl** [comment]
I have the same thing. I use my company email address and it just refuses to launch the app whereas it does say that the email address is verified. This is not a matter of disposable email addresses, it's my company domain that is in use for over 15 years.

**Comment by reetp** [comment]
> I have the same thing. I use my company email address 

Pretty pointless commenting on a long closed issue with no individual setup info.

Things change. Fast.

You need to tell us about your deployment because for 99.9% of users it works perfectly if you use a genuine adddress (and not from a restricted nation)

Read down.

https://gist.github.com/reetp/a66149d5f060f260643a353ca7067a98#before-you-start
