### ISSUE TITLE
Random phantom ding dong "door" notification sounds occurring 

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat#33840]
### Description:
We have had several employees reporting they are getting "phantom random ding dong" notifications. The sound is the "Door" notification in rocket, you can hear an example here: https://freesound.org/people/Kinoton/sounds/670297/

### Steps to reproduce:

1. Don't do anything
2. ???
3. Ding dong!

### Expected behavior:

No random ding dongs in the middle of the night

### Actual behavior:

Random ding dongs happening without new chats or room invites.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.13.0
- License Type: Enterprise

### Client Setup Information

- Desktop App or Browser Version: 4.1.1
- Operating System: Windows

**Comment by jalajk3004** [comment]
i would like to contribute

**Comment by Gummikavalier** [comment]
We are having this too. So far we have noticed it is Mac users who are getting this most. (Practically all of them, and in dozens.)

Disabling notifications in RC does not help, nor turning their volume down.

Because of that I'm suspecting that it may be the new common MacOS 15 Sequoia network issue. It has consistent but random issues with antimalware vendor's and VPN client's virtual network adapters, as well as with just MacOS's own firewall.

**Comment by wreiske** [comment]
FWIW our CIO uses Windows as his daily driver and he gets these random ding dongs in the middle of the night on his Windows PC.

**Comment by Gummikavalier** [comment]
Thanks! Not a Mac problem solely then. :disappointed:

**Comment by reetp** [comment]
Does this still occur on v7 ?

If so I'll refer it to the team.

**Comment by Gummikavalier** [comment]
At least we haven't moved yet to RC 7.0.0 because of apps installation problem with deno (no more about that here), so I cannot confirm it yet.

I think I've also heard these by now and curiously only when Zoom session has been open. Even when I myself had set `Busy` status in RC which usually prevents any notifications and their sounds.

So again I'm unsure whether this sound is caused by Zoom or RC. @wreiske Do your users use Zoom / Zoom client actively? Many of our users are hearing dingdongs during Zoom calls.

I also suspect they may be triggered by combination of Zoom and M365 Outlook when the events start / are ongoing. So would not be RC related at all at least in all similar cases.

**Comment by wreiske** [comment]
Ding dong is still happening. Seems to be related to network issues or websocket re-connecting.

**Comment by wreiske** [comment]
Wow, that's super annoying. Ding dong!

**Comment by reetp** [comment]
Can you let me know if this occurs on 7.1 ?

If so I' ll refer it.

**Comment by reetp** [comment]
I have lobbed this at Casals.

If you have any further info let us know.

**Comment by casalsgh** [comment]
Asked core team to check. We had this issue in the past, got fixed and seems is annoying folks once again. Sorry about that

**Comment by wreiske** [comment]
This still occurs in 7.2.0.

https://open.rocket.chat/group/mie-rocket?msg=WJ7pocjgbJfsRBcJb

**Comment by reetp** [comment]
Anyone else?

**Comment by wreiske** [comment]
I found the root cause for my ding dong issues. Found the ding dong. I had a new chat with someone I've never responded to. I opened on accident while busy, and then set "Mark unread" because I needed to go back to it later. It was the first time I loaded the chat, and now forever until I open that up it will Ding Dong as a new room.

<img width="669" alt="Rocket Chat_bcsuIftYpj" src="https://github.com/user-attachments/assets/ba598cae-2c15-4a0f-859b-c89921cfad9a" />

There's no way to know it was that room - since I had several other chats unread and there's no differentiation in the UI to know it's a "new" room.
