### ISSUE TITLE
logo format

### ISSUE THREAD

**Issue by Iix** [RocketChat/Rocket.Chat#3387]
The current logo `/assets/logo.png` is actually an SVG Scalable Vector Graphics image, and not a PNG Portable Network Graphics image in Rocket.Chat v0.31.0.

This causes the image to appear in the desktop browser, whereas in the mobile app (tested on Android & iOS) it doesn't. - The logo appears when calling the full URL (https://chat.foo.bar/assets/logo.png) in the browser of the mobile app, so the issue seems to be with the rocket.chat mobile-client.

Looks like the file `/public/images/logo/logo.svg` is not converted into a PNG properly...

**Comment by downeym** [comment]
FYI, this also means if you upload a custom PNG logo via Administration, that logo appears in the mobile apps and the standalone desktop app, but not in the standard desktop web browser.

**Comment by ryannealmes** [comment]
Is the logo via Administration mean to update the logo used throughout the site? For example on the login page or when you are logged into the app.

This is not working for me like @downeym states. I am happy to look at the code and see what is happening, but I wanted to confirm the functionality since it's not in the docs yet.

**Comment by MartinSchoeler** [comment]
Closing this in favor of #3402
