### ISSUE TITLE
Warning about deprecated parameter "query" on API causing excessive logging on CloudWatch

### ISSUE THREAD

**Issue by Vanhaosd98** [RocketChat/Rocket.Chat#33905]
### Description:

Warning about deprecated parameter "query" on API causing excessive logging on CloudWatch

### Expected behavior:

Currently, because the number of logs is too large, I want to ask if there is a way to turn on/off log warnings related to deprecated?

### Actual behavior:

When I use APIs with the "query" parameter, there will be a Warning log, for example "/api/v1/settings.public"

### Server Setup Information:

- Version of Rocket.Chat Server: 6.10.0
- License Type: Community
- Number of Users: 
- Operating System: 
- Deployment Method: ECS Fargate (Docker image)
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by reetp** [comment]
> Version of Rocket.Chat Server: 6.10.0

First, upgrade. Now. There are security flaws in your version.

Either usr the latesr 6.10.x or newer.

Second, always test your issue on the latest version because they are unlikely to fix much on your version if a bug is found. So get a test VM and v7.x

Next, have you checked your log settings in Rocket?

admin/settings/logs

What log level is set?

**Comment by david-uhlig** [comment]
We run on `6.13.0` and this has been in the logs for quite some time. Log level is `0 - Errors only` .

**Comment by reetp** [comment]
OK, so the first thing you should do is do what I did and read the documentation which explains it.

This has been warned about for some time as a deprecated function since 5.x and is disabled by default in v7, and will be removed entirely in v8

https://developer.rocket.chat/v1/docs/en/deprecated-parameters?highlight=settings.public

As a result you should change your query as this will be a wontfix.

**Comment by david-uhlig** [comment]
> OK, so the first thing you should do is do what I did and read the documentation which explains it.
> 
> This has been warned about for some time as a deprecated function since 5.x and is disabled by default in v7, and will be removed entirely in v8

Looks like the ReactNative RC developers should have done that since the API request seem to stem from the mobile clients.

https://github.com/search?q=repo%3ARocketChat%2FRocket.Chat.ReactNative%20settings.public&type=code

**Comment by reetp** [comment]
> Looks like the ReactNative RC developers should have done that since the API request seem to stem from the mobile clients.

As you haven't told us anything about your setup beyond the fact that it is 6.13 it is hard to know exactly what causes your issue.

Documenting out your own issue rather than `#metoo` - which frequently isn't - is much more useful.

Note the original OP made this comment so appears to be using the API call themselves - unless they want to correct themselves.

> When I use APIs with the "query" parameter, there will be a Warning log, for example "/api/v1/settings.public"

I will check with the React dev why this is the case. Note that after checking on v7 it doesn't show a deprecated warning.

**Comment by david-uhlig** [comment]
> Note the original OP made this comment so appears to be using the API call themselves - unless they want to correct themselves.
> 
> > When I use APIs with the "query" parameter, there will be a Warning log, for example "/api/v1/settings.public"

That's fair, I guess I missed that part of their issue.

> Documenting out your own issue rather than `#metoo` - which frequently isn't - is much more useful.

I don't feel like there is much value in doing so: https://github.com/RocketChat/Rocket.Chat/issues/created_by/david-uhlig

**Comment by reetp** [comment]
> I don't feel like there is much value in doing so

I can't help that - I don't work here.

I am a band of one (where's the cavalry when you need them?) and trying to ensure the team look at anything that seems buggish or important.

Either way if you don't add your info & details you will get ignored.

If you let me know the situation on the other issues tested on v7 I'll try and get some eyes on if they still exist.

You can get me at

https://open.rocket.chat/channel/support

**Comment by reetp** [comment]
So the React dev said:

> It (settings.public) was soft removed on 7.0, but it can still be used with a env var.

> 4.54.1 should remove all calls to it.

That has just been released.

https://github.com/RocketChat/Rocket.Chat.ReactNative/releases/tag/4.54.1

This issue should be closed.

**Comment by casalsgh** [comment]
Vanhaosd98 based on the discussion here and as this is a "won't fix" closing the issue. Please re-open if you feel that is not covering your request.

**Comment by Vanhaosd98** [comment]
Thank you for your help, I have confirmed the issue has been resolved in version and 7.0.0.
