### ISSUE TITLE
Move towards Glip approach?

### ISSUE THREAD

**Issue by jmatsushita** [RocketChat/Rocket.Chat#346]
Here's a [blogpost describing what the Glip approach is](http://blog.glip.com/bid/342385/Glip-Puts-Conversations-at-the-Heart-of-Team-Collaboration). This is the relevant extract:

> With Glip, all of these activities take place within a conversation stream and in context, reducing the time and stress of managing multiple applications and email threads

I've been trying this and the concept is powerful. Moving "standard" things like tasks, calendar, links and files "inside" the chat rather than dealing with 2 way integration for key apps is really compelling (there are still integrations in Glip).

![](http://glip-help.s3.amazonaws.com/ComposeNewTask-1.png)

Is that a direction that the rocket chat team would be interested in?

Probably also of interest a [Glip vs Slack comparison](http://blog.glip.com/glip-vs.-slack-a-comparison) with a simple take-away "_Slack = Chat + Integrations  |  Glip = Chat + Apps + Integrations_"
##

**Comment by jmatsushita** [comment]
@engelgabriel @rodrigok No interest? Roadmap too full? Don't see the point?

**Comment by engelgabriel** [comment]
WE DO! Totaly! Sorry for not replying! 

We are even working on the idea already... so anyone can create new packages that would register new message types (events, tasks, files) and room types (chat, whiteboard, conference call)

The link you sent was really helpful to make it more "real" what we have thoght we wanted to do since the beginning of the project.

Do you want to join the team and help us get there? :)

**Comment by jmatsushita** [comment]
That's awesome to hear! I've been playing with meteor a bit but I don't have the bandwidth to contribute unfortunately. But whenever you guys have tasks and files up, then I'll probably beta test! Otherwise maybe the Gitter open source peeps (@malditogeek) would be into contributing to Rocket.Chat ? :)

**Comment by engelgabriel** [comment]
Related to https://github.com/RocketChat/Rocket.Chat/issues/293

**Comment by graywolf336** [comment]
Related to this, would be neat to have meetings and meeting requests which you can mark certain members as required and they're reminded every so often to respond to the meeting request.

**Comment by engelgabriel** [comment]
![image](https://cloud.githubusercontent.com/assets/1000217/9983184/4d6d5368-5fca-11e5-85d2-52871a996356.png)

**Comment by engelgabriel** [comment]
Interesting idea o enhance autocomplete http://i.imgur.com/XX42La8.gif

**Comment by malditogeek** [comment]
@engelgabriel that's sweet! what app is that from?

**Comment by malditogeek** [comment]
@engelgabriel nevermind, found it https://chatgrape.com

**Comment by engelgabriel** [comment]
:+1:

**Comment by geekgonecrazy** [comment]
@engelgabriel that would be awesome.  :+1:

**Comment by jmatsushita** [comment]
```#``` for linking items and ```!#``` for creating items?

**Comment by rchikballapur** [comment]
What's the status on this thread? It looks extremely interesting to have this feature.

**Comment by jmatsushita** [comment]
Is it me or https://github.com/RocketChat/Rocket.Chat.Ops is actually a big step forward to allow this use case?

**Comment by marbetschar** [comment]
Are there any news regarding this issues original intent? Don't really get what the current state of this issue is ;)

```
With Glip, all of these activities take place within a conversation stream and in context, reducing the time and stress of managing multiple applications and email threads
```

**Comment by Vaquero84** [comment]
I wanted to ask about the state, too. I've read that there are some kind of packages one could install that would provide new functionality like this, but I couldn't locate an example. Not that I'd entirely understand it. Once, such a package would be installed on a server, would it then also be available to all mobile and dektop clients?
For now our team stuck with glip, because we previously had all the separate shared calender and tasks apps, but it was a hassle getting everyone setup. It's much easier to have everything in one place (well, polls and nextcloud integration are still missing), but I'd prefer an open source alternative like rocket.chat to a proprietary service.

**Comment by geekgonecrazy** [comment]
Anyone participating have ideas on what we could rename/refactor this ticket to be a true feature request?  Right now its very generic and not really something someone can act or implement.

Please feel free to open a detail feature request on our [forums](https://forums.rocket.chat) where we can review and decide if we plan to implement.  Feel free to also link to this ticket for historic.  The better layed out we can get the request the easier it is for us to make definitive decision on whether we plan to implement or not.
