### ISSUE TITLE
[Win 10] RocketChat freezes one to three times a day (freezing)

### ISSUE THREAD

**Issue by punkr0ck** [RocketChat/Rocket.Chat#3462]
My Rocket.Chat version: 1.3.1 (**Desktop Version**)
Win 10 Pro, latest Updates.

From far unknown reasons RocketChat freezes one to three times daily. There is no more interaction possible.

**Comment by sduensin** [comment]
Happens to me as well.  Same version.  I also occasionally come back to my PC and find the desktop client area to just be black.  All I can see is the menu bar and server list.

**Comment by phopkins** [comment]
I'm also using same version on same version of windows and my chat screen is freezing many times a day.
I use the handy "Application - Reload" menu to get the chat back. I'm assuming because of the existence of this menu item that this is not an uncommon issue.

Would really appreciate a fix for this.
Thanks

**Comment by MartinSchoeler** [comment]
If you still have this issue please reopen this in here https://github.com/RocketChat/Rocket.Chat.Electron

Thanks!
