### ISSUE TITLE
Option to delete messages from banned user after kick

### ISSUE THREAD

**Issue by hooramin** [RocketChat/Rocket.Chat#351]
In every public chatroom sites we see hate speech and spams
in this issue #206 you must add an option to kick users and remove all of their message after ban ! 

Also we will have a lot of abuse reports from private messages too , but in Rocketchat we don't have any option to  receive the reports now.

Unfortunately Rocketchat developers just focus on optional features and didn't plan any todo for backend and administration part, while it's most important worriment in public online communities !

I have a lot of idea for this part , but i don't think administration part be in your priorities since you labeled #327 as just a feature request !

**Comment by sampaiodiego** [comment]
hey @hooramin , thanks for your concern.

the primary focus of rocket.chat is for private use, like teams of companies who want their own chat service. because of that, this administration tools are not in our main roadmap.

we would be glad to hear your thoughts in this area.. and with your patience on implementation. =)

**Comment by marceloschmidt** [comment]
This is possible now by going to /admin/users. To ban users you deactivate their account. To delete user and their messages, you hit the delete button.
