### ISSUE TITLE
Can't play embedded videos

### ISSUE THREAD

**Issue by frdmn** [RocketChat/Rocket.Chat#3547]
Your Rocket.Chat version: demo instance via Electron client as well as Chrome

![ohnetitel3 mov](https://cloud.githubusercontent.com/assets/944459/16035407/3fbcd386-3217-11e6-9813-b1827cc610ff.gif)
![ohnetitel2 mov](https://cloud.githubusercontent.com/assets/944459/16035406/3faf4da6-3217-11e6-9475-c274400e4767.gif)

Video in question: http://up.frd.mn/4BuzWg2FmY.mov

**Comment by Marekai** [comment]
Same for rocket.chat version  0.32: 
.mov and .3gp Videos dont play in: Chrome, Firefox in OSX, and under Android 5.1 in Chrome.

**Comment by rasos** [comment]
Recording and playing a video is is a very common use case.
Camcorder videos recorded on an up-to-date Android  / Cyanogenmod (by clicking the paper-clip sign and then the camcorder icon) can not be played on the same device, neither in the RC App nor in the Firefox or Chrome browser on the same device or on a Linux desktop. The reason is that 3gp is simply not supported in video html5 due to patent issues. 
Proposal for fix: convert any 3gp video on the server. 
This worked for me and saves a lot of bandwidth (the webm file was 20 times smaller than the 3gp):
`ffmpeg -i VID_20160614_195849.3gp VID_20160614_195849.webm`

**Comment by geekgonecrazy** [comment]
So we may need to use something other then the html5 video element.

**Comment by rasos** [comment]
https://github.com/flowplayer/flowplayer is GPLv3

**Comment by rasos** [comment]
After some further research found out that flowplayer does not really support 3gp. As it does not do any transcoding, it relies on what browsers support: http://demos.flowplayer.org/videotest/canplay.html 

So ffmpeg transcoding on the server seems to be the only option, ideally with the following steps:
1. trigger ffmpeg when an 3gp file has been uploaded
2. notify user that video format conversion is starting and ask for patience (optional)
3. replace message with new *.webm file name

**Comment by geekgonecrazy** [comment]
I don't think we're going to want to introduce ffmpeg transcoding into the stack.  The likely solution here is if the browser can play the video we'll show it.  Otherwise we'll offer it as a file to download.  

Think of the case where you are running on a single core server and someone uploads a big video file that needs transcoded.  They will be sharing that single core.  My experience with video conversion... It takes up a lot of CPU.  Then the Rocket.Chat server will suffer and your users will not be happy.

**Comment by rasos** [comment]
Well, rendering certainly depends on your hosting environment, you could lower the nice value not to interfere with other services on the same machine. 
Offering a download for 3gp is also a good idea, then it is played with the device's video player.
We should handle amr audiofiles similar, they are recorded on Android with the standard audio recorder, but can't be played wiithin an HTML5 audio tag.

**Comment by rasos** [comment]
Now with the integrated browser-based-recorder webm is produced and can be played on Android, iOS and web browser. So this ticket could be closed.

**Comment by rasos** [comment]
webm seems not to be played on Safari, though. See https://www.w3schools.com/html/html5_video.asp

**Comment by Sing-Li** [comment]
Closing.  Please let us know if it is still a problem for you.
