### ISSUE TITLE
deploy develop to prod

### ISSUE THREAD

**Issue by galrotem1993** [RocketChat/Rocket.Chat#3609]
Your Rocket.Chat version: 0.32.0

hi,

i want to deploy/publish the develop version to my production server.

what is the best way (best practice) for this? (deploy the rocket chat with all the depended packages)

**EDIT**

the servers (dev and prod) are ubuntu 14.04.
i run the application in the dev with just "meteor" command

thanks all

**Comment by k0nsl** [comment]
How is it deployed on your development server? Docker? In case of docker you could always save the mongodb image, then transfer it to your production server and simply load the saved copy. Then just fire up Rocket.Chat with something like `docker-compose` (may need some customisation).

That is how I did it, anyway.

**Comment by galrotem1993** [comment]
i edited the post, my app is running on ubuntu 14.04

**Comment by k0nsl** [comment]
@galrotem1993 

Yes, ok. But how is it deployed on your Ubuntu? Via Docker? Or did you follow these instructions:
https://rocket.chat/docs/installation/manual-installation/ubuntu/

**Comment by galrotem1993** [comment]
i am not using docker
i follow this steps: https://github.com/RocketChat/Rocket.Chat#development

and changed some things

**Comment by k0nsl** [comment]
@galrotem1993 

Ah, I see. In that case you should just be able to copy your `.meteor` directory to the other server.

**Comment by galrotem1993** [comment]
can i compile/build the hole project with the packages to a node project and run it with the node?

**Comment by lucasvanhalst** [comment]
You should just use docker, switching between versions is as simple as changing one line in a config file :smile:

**Comment by k0nsl** [comment]
@lucasvanhalst: I completely agree. I used to be doing the method which @galrotem1993 is doing, but it's no good, not for production anyway.
Docker is really pleasant to work with once you get used to it (it is very easy to learn).

**Comment by eemapel** [comment]
How about when creating meteor build for Docker? I don't think all test packages and hooks get included. What's the best way to do that? --debug doesn't seem to do anything else than avoid minifying things.

**Comment by kruczjak** [comment]
@galrotem1993 If you want to build your current develop version not to docker image, you can use my script:

`iiet-chat` is my folder with git repo.

```
#!/bin/bash

(cd ~/iiet-chat && git stash && git pull)
(cd ~/iiet-chat && meteor build --server https://<yours_prod_url_here> --directory ~/server)

echo "Installing npm dependencies"
(cd ~/server/bundle/programs/server && npm install)

echo "Installing newrelic"
(cd ~/server/bundle && npm install newrelic)
sed -i "1s/^/require('newrelic');/" ~/server/bundle/main.js
ln -s ~/newrelic.js ~/server/bundle/newrelic.js

pm2 startOrRestart /home/ubuntu/pm2.json
```
It's additionally adds newrelic monitoring :)

pm2 is "Production process manager for Node.js apps" (it simply restarts app)

It will build app to ~/server directory. You can run it on prod server (and then restart app, e.g. using pm2) or run on development server and then `tar` ~/server, `sftp` to production server, untar and restart (but you must have same node version on both server or very strange things will happen :D )

Maybe not the best way but it works :)

**Comment by Almax** [comment]
Hi there,
Can somebody help with deploying or running my own fork
i have Rocketchat fork with minor changes, but i can't get it run on my vps with https
my workflow looks like:
**1** cloning forked repo from git and change directory to the repo
**2** then `meteor build --server my_hostname --directory `.
**3** then going to  bundle/programs/server - `cd ./bundle/programs/server`
**4** npm install
**5**  then `sudo MONGO_URL=mongodb://127.0.0.1:27017/rocketchat ROOT_URL=https://my_hostname PORT=8080 node main.js`
        _port 8080 because of 80 port was in use - thats actually confused me_ 


 -  system message says that app is running on my_hostname under given port
➔ +----------------------------------+
➔ |          SERVER RUNNING                 |
➔ +----------------------------------+
➔ |                                                         |
➔ |       Version: 0.35.0                           |
➔ |  Process Port: 8080                          |
➔ |      Site URL: https://my_hostname  |
➔ |                                                          |
➔ +----------------------------------+
but when i try to enter the site i got 502 err / or no connection

--------------------
Then i've deployed the docker image by following steps in the official docs
and app is work like charm with https enabled
but i would to know how to run my own fork of the RC with docker
_/* i follow instructions in the docker off.site to make docker image. with unsuccessfull result*/_

Does somebody have build your own docker image from forked repo and run it?
How can i build my own docker image from my forked repo?
so that i can run it with https enabled 
the Mean important purpose for that is - **running rocketchat with https enabled under 80 port**
thats the problem that i cant solve 
ANY Help Appreciated

**Comment by k0nsl** [comment]
What do you see when you try to browse `https://my_hostname:8080`?

**Comment by Almax** [comment]
502 bad gateway

**Comment by k0nsl** [comment]
Oh, of course it wouldn't work when trying to access it via HTTPs directly interfacing with the Rocket.Chat application. My bad!

Please post your nginx reverse proxy configuration for your Rocket.Chat project. I am convinced the problem can be found in your nginx configuration.

**Comment by Almax** [comment]
nginx conf - **/etc/nginx/sites-enabled/default**
```
# Upstreams
upstream backend {
    server 127.0.0.1:3000;
}
# HTTPS Server
    server {
        listen 443 ssl;
        server_name myhost.com;

        error_log /var/log/nginx/rocketchat_error.log;

        ssl_certificate /etc/nginx/certificate.crt;
        ssl_certificate_key /etc/nginx/certificate.key;
        ssl_dhparam /etc/nginx/dhparams.pem;
       ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:$              ssl_prefer_server_ciphers on;
        ssl_session_cache shared:SSL:20m;
        ssl_session_timeout 180m;

        location / {
            proxy_pass http://127.0.0.1:3000/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forward-Proto http;
            proxy_set_header X-Nginx-Proxy true;
            proxy_redirect off;
        }
    }
```
there is hosts
```
127.0.0.1    localhost.localdomain    localhost
127.0.0.1    myhost.com    localhost
```
P.S.
have tested nginx with `sudo service nginx configtest && sudo service nginx restart`
everything ok

**Comment by kruczjak** [comment]
@Almax it seems you have chat running on port `8080` and in nginx you try to proxy through port `3000`.
Just try e.g. changing `http://127.0.0.1:3000/` -> `http://127.0.0.1:8080/` in nginx and it should probably work :)

**Comment by k0nsl** [comment]
Yep, that's your problem! :D

**Comment by Almax** [comment]
@kruczjak  Unfortunately, it doesnt work
port was changed with no effect

**Comment by amadou009** [comment]
Hello I cant't build RocketChat.
I had just modify : /Rocket.Chat/packages/rocketchat-ui-login/login# gedit form.html.
![capture d ecran de 2016-07-26 12 45 01](https://cloud.githubusercontent.com/assets/18334094/17153003/4afe7cc0-532f-11e6-837c-dd48f5f217f9.png)

Someone could help me

**Comment by amadou009** [comment]
Hello I cant't build RocketChat.
I had just modify : /Rocket.Chat/packages/rocketchat-ui-login/login# gedit form.html.
![capture d ecran de 2016-07-26 12 45 01](https://cloud.githubusercontent.com/assets/18334094/17153003/4afe7cc0-532f-11e6-837c-dd48f5f217f9.png)

Someone could help me

**Comment by mitijain123** [comment]
I had installed in my development machine :
https://github.com/RocketChat/Rocket.Chat#quick-start-for-code-developers
made some changes in packages/rocketchat-ui-login/login/form.html:

and deployed in ubuntu server following:
https://rocket.chat/docs/installation/manual-installation/ubuntu/#manual-install

Now how to deploy my changes made in file packages/rocketchat-ui-login/login/form.html to the server?

I want this to customize the login page html tags.

**Comment by MartinSchoeler** [comment]
Closing this since the original question was already answered. 
If you have any further questions please join our community server in the [#support](https://demo.rocket.chat/channel/support) channel or ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat)
