### ISSUE TITLE
how can use video conference settings

### ISSUE THREAD

**Issue by johnfelipe** [RocketChat/Rocket.Chat#3645]
http://sesionentiemporeal.felipeurrego.com/

i read about https://github.com/jitsi/jitsi-meet and other but how can integrate quick an easy my demo instance?

**Comment by geekgonecrazy** [comment]
@johnfelipe out of the box we have it set to meet.jit.si feel free to use that.  Otherwise follow the instructions on jitsi meet's documentation to set up your own.  Then specify the address in the video conference settings:

![image](https://cloud.githubusercontent.com/assets/51996/21168325/c1fdf258-c178-11e6-9e1b-0347ae93c941.png)
