### ISSUE TITLE
Message editing settings

### ISSUE THREAD

**Issue by marceloschmidt** [RocketChat/Rocket.Chat#374]
Allow/Disallow message editing
Allow/Disallow message deleting
 Show/Hide that a message has been edited/deleted
 Keep history of edited/deleted messages

**Comment by rwakida** [comment]
hi @marceloschmidt I noticed you implemented these changes, but it looks like the message template is not reactive due to "nrr".   Are you planning on making the icons reactive to setting change?  For example, the edit icon is not reactively removed after the Message_AllowEditing is set to false.  Thanks.

**Comment by marceloschmidt** [comment]
Hey @rwakida. We have to think about performance vs usability. Do we really need those icons to immediately reflect settings? Is that something that will be changed more oftenly than not?

**Comment by rwakida** [comment]
:smile:  agreed.  My only gripe is that the edit icon is still visible with pointer cursor, but no feedback is given to the user as to why they can't edit, and the delete icon is visible and still works. 

Also, we need to protect the serverside methods.  The updateMessage and deleteMessage need to check the settings.

**Comment by marceloschmidt** [comment]
You're right! Thanks for the reminder. I'll work on that tonight.


--
Marcelo Schmidt

**Comment by rwakida** [comment]
thanks! we need that in our fork.

**Comment by marceloschmidt** [comment]
@rwakida that is done
