### ISSUE TITLE
Don't automatically convert uploaded avatar to JPEG

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/Rocket.Chat#3766]
A suggestion: don't automatically convert uploaded avatar to JPEG — this is particularly "annoying" for those who want an animated GIF as their avatar.

**Comment by engelgabriel** [comment]
This should be a server setting.

**Comment by rodrigok** [comment]
We do not support resize of animated gifs.

We can add an setting to define which image types we should resize, then users can remove the gif from the list allowing users to use animated gifs (with no resize)

For other formats it's better to convert to JPEG to reduce the file size.

**Comment by rubahness** [comment]
A bunch of white space is added to uploaded GIF avatars; is that part of the conversion to JPEG?  It has the result that small animated icons appear even smaller because the converted image + whitespace is scaled back down to avatar height. (not to mention no animation and all the jpeg artifacts)  Original av image is 31x30
![partyclo-c](https://cloud.githubusercontent.com/assets/10877955/21661687/5fb3674a-d28a-11e6-8c04-71bfda6eed66.gif)
![rocketchatgifs](https://cloud.githubusercontent.com/assets/10877955/21661660/2f82fe6e-d28a-11e6-9889-a93333088163.png)

**Comment by timkinnane** [comment]
+1. I've made a series of beautiful png avatars for my bots with transparency, but they all inherit an ugly white background on upload. :(

**Comment by mixrat** [comment]
+1

This was added to the 0.50.0 milestone but still no animation in 0.56.0. Is this still in the works?

**Comment by Bielecki** [comment]
Anything? I made transparent .png avatar, but it converted it with black background.

**Comment by engelgabriel** [comment]
We will close this in favor of https://github.com/RocketChat/Rocket.Chat/issues/11230
