### ISSUE TITLE
How to load Rocket.Chat on webview android?

### ISSUE THREAD

**Issue by fantashi** [RocketChat/Rocket.Chat#383]
When i load webview on mobile app, it show only blue screen. Can not show form login.

**Comment by engelgabriel** [comment]
How do you plan to login? Maybe if we have SSO in place?

**Comment by Sing-Li** [comment]
For any Android 5.x device (Lollipop  - since November, 2014), look on Google Play for [Android System Webview](https://play.google.com/store/apps/details?id=com.google.android.webview) from Google.

Webviews before 5.0 are not upgradable, and baked into the ROM.

The Webview on 4.4.2   (KitKat - since Oct, 2013) works fine.

If you're programming Cordova / Phonegap -- even older devices, all the way back to Ice Cream Sandwich 4.0 - Oct 2011, may be able to use the [Intel Crosswalk WebView](https://crosswalk-project.org/) replacement.

Any device pre-2011, with Android version older than 4.0, will likely not work.

**Comment by engelgabriel** [comment]
We found a bug on our own server.. that was configuring the cross header twice (once on the app, other on nginx). Please reopen the issues if it is still not working.

**Comment by fantashi** [comment]
Thank for your support, now everything is good :)

**Comment by yuchaozh** [comment]
@fantashi 

Hi, I am also working on embedding rocket chat into Android webview. I have the same issue. It just showing the loading page but did not redirect to login page. And the logcat says: "You are running a browser with no localStorage or userData support. Logging in from one tab will not cause another tab to be logged in". Do you know how to fix this?

Thanks!

**Comment by engelgabriel** [comment]
hi @fantashi did you see the cordova project?

**Comment by engelgabriel** [comment]
@fantashi We can offer you development services if you need help to get  this done. Please contact me on the https://demo.rocket.chat server if you are interested.

**Comment by yuchaozh** [comment]
@Sing-Li  I am running on a emulator of Android version: 5.10. What do you mean "For any Android 5.x device (Lollipop - since November, 2014), look on Google Play for Android System Webview from Google."? Just install the Android System Webview app?

Thanks.

**Comment by Sing-Li** [comment]
@yuchaozh   Please note that the comment was made almost a year ago.

The Android ecosystem doesn't stand  still that long.  But yes, the Webview app _used to_ update the system webview with 5.1 as of last August  :)

**Comment by janakamarasena** [comment]
@fantashi  @yuchaozh were you able to solve the problem @Sing-Li  am running into the same problem this is a native android app running on android 6.0.1 any help is much appreciated.

Thanks
