### ISSUE TITLE
Encrypted messages in database ?

### ISSUE THREAD

**Issue by sm1ly** [RocketChat/Rocket.Chat#3879]
Your Rocket.Chat version: 0.35
Hello there.
What about encrypted messages in database? Like if I use mongo and see not messages in base, but hashes? like otr, but for groupchats

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @sm1ly 

I am closing this issue because we think there is no actual bug in Rocket.Chat in what you're describing. Here's why:

* while I understand your feature request and personally agree that this is something very interesting, https://forums.rocket.chat would be the right place to start a discussion about this. If you reach a conclusion there, one could still open a complete feature request including technical solutions and stuff.
* this topic is so huge, it needs to be discussed before implementing it (which could then maybe happen in a github issue)

Cheers
Thomas
