### ISSUE TITLE
Removing "readonly" html flag allows username edition when admin has disabled it

### ISSUE THREAD

**Issue by giovaneliberato** [RocketChat/Rocket.Chat#3891]
Given I'm a non-admin user
And the system admin disabled the "change username" function
<img width="553" alt="screen shot 2016-08-01 at 12 11 48 pm" src="https://cloud.githubusercontent.com/assets/2964631/17305200/57e64efa-57f7-11e6-9d9d-550ee62348a4.png">

When I remove the `readonly="readonly"` flag on html input field
Then I can edit an save a new username

Your Rocket.Chat version: 0.35.0

**Comment by tgxn** [comment]
This should be disallowed as of [this section of code](https://github.com/RocketChat/Rocket.Chat/blob/master/packages/rocketchat-ui-account/account/accountProfile.coffee#L64). INterestingly, it seems that it's prevented this since a while ago (I went through the git history, and the git blame and I can;t see where this was implemented/added.

Can you confirm that it is in fact, changing your username when you update it by changing the readonly flag?

Having the version that's running in your instance would be extremely helpful, as we can figure out why this is being allowed, if it in fact is allowed.

**Comment by giovaneliberato** [comment]
Hello @tgxn 
Yes, I actually changes the username. The version running is: 0.35.0

**Comment by graywolf336** [comment]
Can't test until #3940 is fixed, sadly.

**Comment by rodrigok** [comment]
I can't reproduce, please reopen if the problem persists
