### ISSUE TITLE
iframe https within Http site

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#3908]
Hello, is there a way to have an iframe that can embed https inside http site? 
perhaps a plugin or away to include Rocket Chat with an iframe that will open a separate window (https) without leaving the option to login from that window after logging out..  (i.e hiding the subdmain)

this is what i see in the consol: 

Mixed Content: The page at 'https://chat.mysite.com/admin/info' was loaded over HTTPS, but requested an insecure image 'http://www.mysite.com.com/wp-content/uploads/2016/03/image.png'. This content should also be served over HTTPS.

Your Rocket.Chat version: 0:36

**Comment by tgxn** [comment]
The error you're seeing in the console is actually a warning - The image should still be loaded, but Chrome is telling you that it's not secure content, so anything loaded over HTTP could be vulnerable, even though the parent page was loaded over HTTPS.

It happens when the HTTPS page requests animage from the wp-content part of your site (probably from within the iFrame).

There's some discussion [here](http://security.stackexchange.com/questions/894/are-there-security-issues-with-embedding-an-https-iframe-on-an-http-page) regarding putting a HTTPS frame inside a HTTP site, and it is generally not suggested, as it exposes the end user to a variety of attacks.

My suggestion would be to see if you can configure SSL on your WordPress site, and then this will no longer be an issue.

**Comment by geekgonecrazy** [comment]
as @tgxn this should just be a warning.  If you want to get rid of it use https on your wordpress site.  :)  But its a browser thing.  Nothing we can really do about it

**Comment by childnode** [comment]
:information_source:  see #971
