### ISSUE TITLE
Message search doesn't find text from urls and url previews

### ISSUE THREAD

**Issue by thursdaybw** [RocketChat/Rocket.Chat#3922]
![selection_346](https://cloud.githubusercontent.com/assets/8906871/17425237/4cc12b0c-5b0e-11e6-9b03-ca2597e9749d.png)

As shown in the provided screen shot, appears the search doesn't work.
Typing into the search box in a channel, a word that has been mentioned in that channel elicits a result of
'no results found'

Rocket chat server info: 
![selection_347](https://cloud.githubusercontent.com/assets/8906871/17425209/f616c226-5b0d-11e6-90df-9a71cff3155e.png)

**Comment by tgxn** [comment]
I did a small amount of testing, and it seems that because of the way the URL Linker works, the details that are pulled in (Site Title, Truncated Body) are not in the searchable portion of the chat, as they are pull in at run-time. (You can see this as when you edit the messages, only the url is visible)
![image](https://cloud.githubusercontent.com/assets/293107/17427247/a82ba546-5b11-11e6-80a2-e1e4faeaa5f7.png)

It seems that because the search is regex, I put this together and it seems to return the results you'd like: `/.*docker.*/i` (where message contains the word "docker" - case insensitive)
![image](https://cloud.githubusercontent.com/assets/293107/17427260/b50d4c88-5b11-11e6-8f7a-54ee7b659c3b.png)

I would suggest that the function be changed to default to a case-insensitive, "contains" query, rather than the current implementation.

**Comment by thursdaybw** [comment]
Thanks; Suspected something along those lines, and agree.

**Comment by dopykuh** [comment]
The same appears for generated commit messages from gitlab (by using webhook api). Those are not searchable.

**Comment by reetp** [comment]
@rocket-cat close
I'm going to close this off as it is really a NFR rather than a bug.
Please follow up with a new post in Feature Requests at the forums.
