### ISSUE TITLE
How to build release version myself

### ISSUE THREAD

**Issue by tampham47** [RocketChat/Rocket.Chat#3935]
Hi, 
I am a developer, I want to make my own changes, and deploy these changes as production mode.
I want to build release version from source code, like this (https://rocket.chat/download)
But I don't know how to do this, anybody help?

Thank you,

**Comment by mbanusic** [comment]
Since this is a meteor app, you should be able to build it with `meteor build` [see here](https://guide.meteor.com/build-tool.html).
`
cd /your/dev/dir
meteor build --server https://demo.rocket.chat --directory /your/build/location
`

There is also `example-build.sh` script with some initial setup. Modify it to match you dir structure.

**Comment by tampham47** [comment]
@mbanusic thanks, I will try tonight.

**Comment by orrchen** [comment]
Hi,
Is the example-build.sh script still available? I can't find it in the repository.
Thanks
