### ISSUE TITLE
blank page after registration

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat#400]
I got a blank page after registration!

**Comment by rwakida** [comment]
@sampaiodiego @rodrigok I noticed this as well.  It only happens when registering after logout and appears after the enter name,email,password page and before the select username page.  
To replicate:
1. Login as any user.
2. Logout
3. Click on register a new account link
4. enter name, email, password and click submit button. 
5. blank page displayed.  

If I refresh the page, then the select username page is displayed.
