### ISSUE TITLE
File Upload Button missing when Audio Recorder is disabled

### ISSUE THREAD

**Issue by revlis-x** [RocketChat/Rocket.Chat#4038]
Version: 0.37.0
Since the latest version, when I disable the Audio Recorder feature in Admin > Message the File Upload Button goes missing in the message input box.

**Comment by tgxn** [comment]
The problem lies on [this line](https://github.com/RocketChat/Rocket.Chat/blob/0.37.0/packages/rocketchat-ui-message/message/messageBox.coffee#L70) of code.

This is due to the `or not Template.instance().showMicButton.get()` part will return false, thus the send button is permanently enabled, thus hiding the share buttons.

I'll keep it in mind and bundle it into my pull request #4033.

**Comment by MartinSchoeler** [comment]
@revlis-x have you tried to do this in 0.37.1 version? I have tried there and the button was just fine

**Comment by revlis-x** [comment]
@MartinSchoeler in 0.37.1 it works fine. Seems to have been fixed by d70a0e84f186eec5360bcc904d3a3bca84016cd8
