### ISSUE TITLE
Room name alias

### ISSUE THREAD

**Issue by thursdaybw** [RocketChat/Rocket.Chat#4108]
This is a feature question, while I'm thinking of it.

Room name aliases.

The most obvious use case is so that links and references to renamed rooms continue to work.

It could also be fun in same cases, to have a formal room name and a nickname, but this is a matter
of taste.

**Comment by brendanheywood** [comment]
A bit more context, this breaks down into two use cases:

* [ ]  Handling channel renamed more elegantly. ie if a channel is renamed we should record an internal alias of the old channel name so that api hooks and mentions in history and other places still work and link to the new room. 

* [ ] alias'es for the sake of aliases, eg #Australia #au #ozzie all go to the same place

**Comment by MartinSchoeler** [comment]
This would be a very nice feature, but unfortunately it does not align with our current roadmap, so it's probable that it would not be implemented in the near future. I will be closing this issue for now, if we plan to add a feature like this we will reopen this issue. Thanks for the valuable feedback!

**Comment by betz** [comment]
I also think this would be a nice feature. coming from the matrix world, where rooms can have multiple aliases, missing it. subscribing
