### ISSUE TITLE
MongoDb: High CPU Usages

### ISSUE THREAD

**Issue by ankibalyan** [RocketChat/Rocket.Chat#4169]
I've created the custom build from rocket.chat master branch, After successful installation It worked well for 1 day, now it is consuming almost all the cpu processing, after that it keep restarting the app.

Here is Rocket.chat version details
`{
  "version": "0.38.0",
  "build": {
    "date": "2016-09-01T09:06:08.033Z",
    "nodeVersion": "v0.10.40",
    "arch": "x64",
    "platform": "darwin",
    "osRelease": "15.6.0",
    "totalMemory": 17179869184,
    "freeMemory": 3585601536,
    "cpus": 4
  },
  "commit": {
    "hash": "8de32051f66fcc807b4ccf6fcde18195d2150f58",
    "date": "Tue Aug 30 14:25:04 2016 -0300",
    "author": "Gabriel Engel",
    "subject": "version bump to 0.38.0",
    "tag": "0.38.0",
    "branch": "master"
  },
  "GraphicsMagick": {
    "enabled": false
  },
  "ImageMagick": {
    "enabled": true,
    "version": "Version: ImageMagick 6.8.9-9 Q16 x86_64 2016-06-01 http://www.imagemagick.org\nCopyright: Copyright (C) 1999-2014 ImageMagick Studio LLC\nFeatures: DPC Modules OpenMP\nDelegates: bzlib cairo djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png rsvg tiff wmf x xml zlib\n\n"
  }
}`

here is the screenshot 

![screen shot 2016-09-01 at 1 03 06 pm](https://cloud.githubusercontent.com/assets/7150671/18168320/b8781198-7072-11e6-8b72-2c3af1e8833d.png)

**Comment by DavePS** [comment]
Please leave more informations about your installation ?

**Comment by ankibalyan** [comment]
I've created my custom build image from the rocket chat base image.

**Comment by ankibalyan** [comment]
The root cause of problem here was `services.resume.loginTokens` It was adding multiple login tokens with every login request from the app. So after some time it gets high with very large user object for each user, making mongoDb busy.
here I've answered on my SO [Question](http://stackoverflow.com/questions/39272938/mongodb-with-node-is-using-high-cpu-usage-on-docker/39389470#39389470).

**Comment by sampaiodiego** [comment]
@ankibalyan are you running your mongodb on replica set mode?

**Comment by ankibalyan** [comment]
@sampaiodiego  No I'm not running it on replica set.

**Comment by sampaiodiego** [comment]
@ankibalyan you need to run your mongodb in replica set mode even if you have one member.

it's because meteor uses mongodb's oplog to listen for modification.. if you do not use mongo as a replica set member, meteor will poll mongodb for modification which can lead into perfomance issues (like you are experiencing).

after you turn your mongodb as a replica set member you need also to set the `MONGO_OPLOG_URL` environment variable in order to rocket.chat use the oplog tailing.

Please check this docs: 
- [convert mongodb to replica](https://docs.mongodb.com/manual/tutorial/convert-standalone-to-replica-set/)
- [installing rocket.chat](https://rocket.chat/docs/installation/manual-installation/ubuntu/#setup-mongodb-replica-set)

**Comment by ankibalyan** [comment]
@sampaiodiego thank you for valuable information, I'll implement the same and let you know.

**Comment by sampaiodiego** [comment]
you're welcome.. I'll close the issue in the meantime.. please, reopen if needed.
