### ISSUE TITLE
images don't load when clicked

### ISSUE THREAD

**Issue by chovy** [RocketChat/Rocket.Chat#4251]
Your Rocket.Chat version: v1.3.1 mac

when i click on an uploaded image I just get a blank page in chrome. I used incognito mode to be sure it wasn't any plugins interfering, still no image.

**Comment by TheReal1604** [comment]
Hey @chovy ,

i think we need much more information here, to do an investigation on this. In my "home setup" it is working like a charm. Can you give us server logs from your rocket.chat server and reverse proxy when the issue is replicated? A screenshot from the developer console of your browser could be nice to. There we can look what request your browser does..

Thanks!

**Comment by chovy** [comment]
nevermind, i think there was some default setting the a user had. His images woudl show in the chatroom but when I clicked them i got a blank page, even in incognito. He said his "private" setting had it disabled or something. not sure.
