### ISSUE TITLE
Improve edit message

### ISSUE THREAD

**Issue by Molle500** [RocketChat/Rocket.Chat#4344]
I think Rocket chat's edit message should have the same style and functionality like Slack and Discord.

When you edit a message, the box where you edit the message is inside the post instead of having to type inside the message bar.

Slack: 
![slack](https://cloud.githubusercontent.com/assets/17712562/18614826/d14fc536-7d96-11e6-8685-e9aa0a6c7457.png)

Rocket chat: 
![rc](https://cloud.githubusercontent.com/assets/17712562/18614827/d52ea6e0-7d96-11e6-938e-0f5a47e17f9f.PNG)

**Comment by engelgabriel** [comment]
I disagree :) but let have a discussion about this.

**Comment by Jan-Ra-wlec** [comment]
I don't get the differenz, I like it how it is

**Comment by cedemore** [comment]
I prefer the first imag, like Slack. The first 5 times i edited a message i tried to edit the yellow box inside the message.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @Molle500 

I am closing this issue because we think there is no actual bug in Rocket.Chat in what you're describing. Here's why:

* This is no bug, it's a feature request. Apart from that, I don't think that's very likely to be changed, as it works quite well the way it is. If you still want to have a discussion about this, please head over to the forums (see below).

We use Github mainly for discussing bugs though. We understand, that setting up and operating a Rocket.Chat server is not trivial, yet we do not have the woman/man-power to help everybody. That is unfortunate, but simply a limitation of time. If it should turn out from your feedback to this message, that there is a bug involved, we will try to fix it with you.

That being said, we are very thankful that our community also does a great job in helping each other. I would therefore like to point you to some places where you can try asking for help. Usually, some friendly human being has time for you and your issue:

* **The Rocket.Chat Community Support Channel**: https://open.rocket.chat/channel/support
* **The Rocket.Chat Community Support Forum**: https://forums.rocket.chat/c/community-support

If you don't find a solution to your problem there, don't fret, as we also offer paid support: https://rocket.chat/support

You could, of course, spare yourself the hassle entirely and just choose the hosted version, where we provide you with a running Rocket.Chat instance: https://rocket.chat/cloud

Cheers
Thomas
