### ISSUE TITLE
How to update - Autoupdate?

### ISSUE THREAD

**Issue by Jan-Ra-wlec** [RocketChat/Rocket.Chat#4349]
Hello,

Last time when I made an Update, I deleted the RocketChat folder and reinstalled it. Is there any other possibility to do an Update?

What if you Add an Auto-Update Tab into adminstration?

Thank you
JR
Your Rocket.Chat version: 0.39.0

**Comment by Jan-Ra-wlec** [comment]
Okay, We'll migrate soon, so I'll try this on my private Server first. Thank you! But will there be an Update button (or command) in the Administration/backend?

**Comment by derekblankmccoy** [comment]
Agreed, for anyone running the normal server, there should be a simple update feature, similar to owncloud's auto update

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

First to everybody. If you still want to pursue this general topic of auto-updating, please check out #1581.

@Jan-Ra-wlec

I am closing this issue because we think there is no actual bug in Rocket.Chat. We understand, that setting up and operating a Rocket.Chat server is not trivial, yet we do not have the (wo)man-power to help everybody. That is unfortunate, but simply a limitation of time. If it should turn out from your feedback to this message, that there is a bug involved, we will try to fix it with you.

That being said, we are very thankful that our community also does a great job in helping each other. I would therefore like to point you to some places where you can try asking for help. Usually, some friendly human being has time for you and your issue:

* **The Rocket.Chat Community Support Channel**: https://open.rocket.chat/channel/support
* **The Rocket.Chat Community Support Forum**: https://forums.rocket.chat/c/community-support

If you don't find a solution to your problem there, don't fret, as we also offer paid support: https://rocket.chat/support

You could, of course, spare yourself the hassle entirely and just choose the hosted version, where we provide you with a running Rocket.Chat instance: https://rocket.chat/cloud

Cheers
Thomas
