### ISSUE TITLE
Custom Emjoi Additions Require Refresh

### ISSUE THREAD

**Issue by kodypeterson** [RocketChat/Rocket.Chat#4391]
Your Rocket.Chat version: 0.40 with Node 4.5

When adding a new custom emoji, in order to see the image and not the :emoji-name: all clients have to refresh.

**Comment by engelgabriel** [comment]
This is very annoying indeed.

**Comment by nokobon** [comment]
I'm pretty sure that 6639d80aee4cf9be537a8cd86058c70af82912b3 introduced this issue.

If `list` is created and used in `render()`, then other changes need to be made when creating/editing/deleting custom emoji.

The changes in the commit only sets/modifies `RocketChat.emoji.packages.emojiCustom.list` on `Meteor.startup()`

**Comment by nokobon** [comment]
This can be fixed by reverting `emojiCustom.js` to 4351a368ce630dbb045ca9cc5ab09ce42574177f unless there are any changes to emoji that I missed.
There shouldn't be any issues with aliases appearing in the emoji picker because that issue was introduced [here](https://github.com/RocketChat/Rocket.Chat/commit/c3a6b7c7b610015d251fc4ed8d38a45759e2ac46#diff-17377e791fc8e3f1939b847b2bf4f3ccR151)

If `RocketChat.emoji.packages.emojiCustom.list` is kept rather than reverting the file, the package will need to manipulate both `RocketChat.emoji.packages.emojiCustom.list` and `RocketChat.emoji.list` because of [how the autocomplete works](https://github.com/RocketChat/Rocket.Chat/blob/36e1e374eabc57f4fd1d459a18f409231221651f/packages/rocketchat-ui-message/message/popup/messagePopupConfig.coffee#L164).

**Comment by sampaiodiego** [comment]
@nokobon thanks for the investigation :) I'm already working on a fix for this.
