### ISSUE TITLE
Date-filter (search) is buggy

### ISSUE THREAD

**Issue by alfredbez** [RocketChat/Rocket.Chat#4407]
Date-filter is buggy:
![image](https://cloud.githubusercontent.com/assets/1001186/18741424/81b72a66-80af-11e6-98d4-3b16c84f5cbd.png)

see #4320

**Comment by gabriellsh** [comment]
Thanks for reporting this issue. We value your time in helping us to make Rocket.Chat great. We always try to fix confirmed problems as quickly as we can, and it appears that the issue you reported might already be fixed in the latest release. Can you please help us test it against current latest release? Much appreciated. And please remember to backup your data before upgrading, just to be safe. Cheers!

**Comment by alfredbez** [comment]
Hi there, I don't use rocket chat anymore.
