### ISSUE TITLE
Problem with multiple instances

### ISSUE THREAD

**Issue by PotHix** [RocketChat/Rocket.Chat#4525]
Your Rocket.Chat version: 0.41.0 from Docker image rocketchat/rocket.chat:0.41.0
Today we're using mesosphere's Marathon with a Mesos + Docker cluster. 

Every time we use more than one Rocket.Chat application instance we face a desync in messages. Both applications point to the same MongoDB cluster. We open the same chat into 2 different computers to check the delivery. It only works when we have the luck to be using the same instance, otherwise the messages just not appear on the other machine.

Are we doing something wrong?

**Comment by vitamindck** [comment]
I have this exact same issue. HA setup with load balances nginx frontend on
two separate servers, two rc instances, and Mongo X2 with arbiter.

Started happening on 0.35. Deactivated one of the nginx servers so they are
no longer load balanced and that desync problem goes away. Using 0.39 now,
just for reference.

On Oct 3, 2016 7:11 PM, "Willian Molinari" <notifications@github.com> wrote:

Your Rocket.Chat version: 0.41.0 from Docker image
rocketchat/rocket.chat:0.41.0
Today we're using mesosphere's Marathon with a Mesos + Docker cluster.

Every time we use more than one Rocket.Chat application instance we face a
desync in messages. Both applications point to the same MongoDB cluster. We
open the same chat into 2 different computers to check the delivery. It
only works when we have the luck to be using the same instance, otherwise
the messages just not appear on the other machine.

Are we doing something wrong?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/RocketChat/Rocket.Chat/issues/4525>, or mute the thread

**Comment by TheReal1604** [comment]
@PotHix https://github.com/RocketChat/Rocket.Chat.Docs/issues/87

I wrote a write up of my MongoDB / RC HA installation. Works like a charm for me.

**Comment by cpitman** [comment]
Thanks @TheReal1604 

The key part that was missing for me was that each instance has to be able to contact each other via an INSTANCE_IP and PORT that are registered in mongo. I had been under the impression that all communication happened via the database. All of my instances are docker containers, so by default they all had the hostname "localhost" and port "3000".

**Comment by TheReal1604** [comment]
@cpitman got the same problems like you and contacted the developers which give me the hint with the "INSTANCE_IP" thingy :-). At the moment it´s not documented. (only in my post)

**Comment by PotHix** [comment]
@TheReal1604 thanks for the documentation but it are not working yet. I'm not using docker-compose, but a infrastructure with Marathon + Mesos + Docker. In my configuration I did the setup of `INSTANCE_IP` and `PORT` but not the `extra_hosts`, not available on Marathon.

Any chance of getting it to work without it?

**Comment by TheReal1604** [comment]
@PotHix Please open a separate issue to solve this. I think it could be DNS related.
