### ISSUE TITLE
Support mp3 audio upload

### ISSUE THREAD

**Issue by cheuklam** [RocketChat/Rocket.Chat#4552]
Your Rocket.Chat version: 0.43.0
I noticed the current voice recorder is making use of recorderworker.js which is recording dual channel non-compressed wav file. I found a folk has already wrote a js based on recorderworker and lame which provide mono mp3 recording. Shall we try to incopeate into RocketChat? as more and more user rely on voice message nowadays, wav give a high pressure on the storage system.

Here is the link for your reference:
http://audior.ec/blog/recording-mp3-using-only-html5-and-javascript-recordmp3-js/

Best, CL

**Comment by yuchaozh** [comment]
+1, Safari and IE not supports wav file. But all they supports .mp3 file

**Comment by graywolf336** [comment]
@cheuklam feel free to submit a pull request to add this :)

**Comment by goiaba** [comment]
I know the issue talks about mp3, but...

I have changed the `Rocket.Chat/packages/rocketchat-ui/client/lib/recorderjs/audioRecorder.js` to directly use a [MediaRecorder](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder). It works fine, but MediaRecorder seems to not be fully supported by all browsers. I thought we could use it when available (generating webm/ogg files) and falling back to wav otherwise.

Besides that, another possibility would be to use [opus-recorder](https://www.npmjs.com/package/opus-recorder) to solve this. What do you guys think?

I don't have experience with this stuff, but I'm willing to cooperate. Just need some tips here...

**Comment by amonemian** [comment]
@goiaba Would you please share your new changes in code audioRecorder.js?
I am newbie to Rocket Chat and It would be more efficient to transfer mp3 or ogg files instead of wav

**Comment by amonemian** [comment]
Dear @goiaba ,
Hope all goes well with you. Still waiting for your wav to mp3/ogg converter.

**Comment by rodrigok** [comment]
Closed via https://github.com/RocketChat/Rocket.Chat/pull/9726
