### ISSUE TITLE
Jitsi (video calls) not showing chat box in desktop app

### ISSUE THREAD

**Issue by hughlroberts** [RocketChat/Rocket.Chat#4585]
Your Rocket.Chat version: 0.41.1

Jitsi cuts off the chat box and doesn't allow you to change the size of the video/boxes while on the calls. Can we get a way to adjust the size of the video and chat boxes?

![screen shot 2016-10-10 at 10 37 53 am](https://cloud.githubusercontent.com/assets/22516740/19227174/e0112b78-8ed5-11e6-8a71-513ba6625134.png)

**Comment by IQ2022** [comment]
also space there is  space taking most of the screen.. 


![image](https://cloud.githubusercontent.com/assets/12454319/19240639/53a3c264-8ed9-11e6-8525-b8b4eb41d5c1.png)

**Comment by hughlroberts** [comment]
That's a new issue @IQ2022 just saw that today... must be a new bug?

**Comment by dopykuh** [comment]
+1 could also confirm both.

**Comment by sduensin** [comment]
Just installed 0.48.2.  Same deal.  REALLY hoping to use RC to ditch Skype at work!

**Comment by omicron81** [comment]
Rocket.Chat+
Version 1.3.1

I use the Rocket.Chat desktop app as a small window. If I try to start the video chat, all I see is this (black boxes were added by me, but the blue area in front of the chat window is really there):
![rocketchatvideobug](https://cloud.githubusercontent.com/assets/8233992/22426091/425cb812-e6fe-11e6-9424-54d9f1ae9aa6.png)

So, instead of a video chat it just hides the chat.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Folks, this issue is a mess as it describes at least two or more bugs. Also the UI has changed dramatically so I would like to ask each of you to reproduce their issue on the latest stable version of Rocket.Chat (0.62.1) and then report it as a new issue **if it is still present there**.

Cheers
Thomas
