### ISSUE TITLE
Call cuts off when you click on another chat

### ISSUE THREAD

**Issue by hughlroberts** [RocketChat/Rocket.Chat#4586]
Your Rocket.Chat version: 0.41.1

Jitsi cuts off the video (or audio) calls when you click on another chat window. 

Would be great if you could continue to chat with people while you're doing an audio call or be able to reference another chat box where you were talking with someone and need to remember what you wrote.

**Comment by asthomasdk** [comment]
We have been seeing this as well - can be both confusing and frustrating. 

For both the audio and video, I would suggest having them in a separate little window instead of in the right hand navigation panel. This would make audio and video features more independent of what the user is doing otherwise in Rocket while on calls. 

It also makes it much easier to see that you are in a call - which can sometimes be difficult to track with the current implementation.

**Comment by PPPBerlin** [comment]
Rocket.Chat Version: 0.55.1
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.8.1

We like the integrated Jitsi Window, but the problem described above is really annoying. I would like for instance a detachable window for Browser and "native" Clients and block Video Calls for the user in the other rooms to prevent the confusion, where the Sound comes from. :)

**Comment by rasos** [comment]
You can configure that Jitsi is opening in another tab to avoid this behaviour.

**Comment by sampaiodiego** [comment]
we'll change it to make it as a floating popover as the current bigbluebutton implementation

**Comment by micksharma** [comment]
Hi , I want to work in this bug?

**Comment by shanu13** [comment]
hi , can you assign me on this bug ?

**Comment by prachi-the-comder** [comment]
Can you assign me this bug

**Comment by hugocostadev** [comment]
Fixed
