### ISSUE TITLE
Collapsing Menu

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#4688]
Is there a way to add a Collapse menu Option, and adding some sort of Icons for Channels/ Rooms / Msgs ? (which brings to mind another idea, of having the ability to set different type of icon for every channel created (admin to select them)  - this will be helpful if you have your chat embedded in i-frame

Similar to Word press

![image](https://cloud.githubusercontent.com/assets/12454319/19582196/a6723ff0-9700-11e6-88e7-177b4b295b12.png)

![image](https://cloud.githubusercontent.com/assets/12454319/19582202/b3fd7b8a-9700-11e6-84e9-f2951a7aea82.png)

Your Rocket.Chat version: 0.43 and loving it :)

**Comment by bkraul** [comment]
Very crude...but something like this, maybe?
![image](https://user-images.githubusercontent.com/14616851/37297505-db92b824-25eb-11e8-9eaa-28c488d4f520.png)

**Comment by sampaiodiego** [comment]
thanks for the suggestion but we don't plan to implement this.

**Comment by bkraul** [comment]
Diego. It's all good. The customization options allow for solutions to this. Plus, resizing the electron client removes the sidebar when needed anyway. Thank you for at least looking at this.

**Comment by eagle-te** [comment]
@sampaiodiego 
reason?

@bkraul 
You mean the sidebar replacement with the mobile burger menu style? It's an alternative but not a good substitution to a reduced sidebar layout and introduces an unnecessary step for switching channels. I currently need to change the css width values via the dev console, in order to have an average chat experience with the browser occupying half a screen. The default icon bar size takes up more than 30% of the UI.

**Comment by sampaiodiego** [comment]
@thiagosanchz may you give @eagle-te a reason for not implementing that? thx
