### ISSUE TITLE
C:\RocketChat\main.js stopped running on Windows server 2012 R2

### ISSUE THREAD

**Issue by dbmLeon** [RocketChat/Rocket.Chat#4701]
Your Rocket.Chat version: (make sure you are running the latest)
Event Viewer:
Child process [3116 - C:\Program Files (x86)\nodejs\node.exe --harmony "c:\RocketChat\node_modules\node-windows\lib\wrapper.js" -f "C:\RocketChat\main.js" -l "Rocket.Chat" -g 0.25 -w 1 -r 3 -a n] terminated with 0

**Comment by dbmLeon** [comment]
Is there anybody encountered the same issue? Any suggestion would be appreciate!

**Comment by KonradTUM** [comment]
Same problem here... is there any solution to this.. I just installed everything fresh without errors but when I start the rocket.chat service it terminates again with this message

**Comment by KonradTUM** [comment]
anyone?

**Comment by dbmLeon** [comment]
Yes. Sir.

**Comment by jhonla** [comment]
Same problem here....

**Comment by catmanjan** [comment]
Me too, event viewer shows:

Service started successfully.
Starting C:\RocketChat\main.js
C:\RocketChat\main.js stopped running.
Restarted 1250 msecs after unexpected exit; attempts = 1
Child process [4828 - C:\Program Files (x86)\nodejs\node.exe  --harmony C:\RocketChat\node_modules\node-windows\lib\wrapper.js --file C:\RocketChat\main.js --log "Rocket.Chat wrapper" --grow 0.25 --wait 1 --maxrestarts 3 --abortonerror n --stopparentfirst undefined] finished with 1

**Comment by robbihun** [comment]
@KonradTUM @jhonla ... I know it's a year later, and you've likely given up - but if you ever reattempt (and for anyone else who comes across this) that error is because RocketChat is expecting a url in the format "http://my.domain.url" or in my case "http://localhost" instead of "localhost"

You do not have to go through the entire installation from scratch to fix it, but you can edit the {install path}/daemon/rocketchat.xml with the correct parameters.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close
