### ISSUE TITLE
LDAP Put users in different permission roles based on group

### ISSUE THREAD

**Issue by spweigand** [RocketChat/Rocket.Chat#4735]
Your Rocket.Chat version: 0.44

Hi,

i want to achieve the following for users and their permission roles.

LDAP Users put into the role "users" and users through hidden url registration put into the role "guest"

I saw an example in Accounts->Registration->custom fields that you can configure roles there but even the example isn't working.

Can someone help?

**Comment by Jannibal** [comment]
I solved this problem by changing the permissions for users (which are the outsiders that register) to be as restrictive as for guests, and then making a new role called "employee" which mirrors the default user permissions. Then I added (manually) all of the LDAP users into the "employee" group. Tedious, but worked for such a small company as us.

This solves the problem where we'd like guests to be able to register using the secret URL, but still keep their permissions restricted. 

But a problem arises when we have the LDAP fallback. It has to be enabled in order to have a guest (that is not on our LDAP) be able to log in. But this fallback allows for users that have been removed from LDAP to log in with their old credentials and permissions, since they are allowed as fallback.

**Comment by spweigand** [comment]
Thanks for the reply. 

What you described is the same what i ended up making. But it feels more like a workaround and not the final solution. I thought there was a more "comfortable" way through the custom fields in the Accounts section.
