### ISSUE TITLE
how to clear cache ( .css ) rebuild ??

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#4750]
Your Rocket.Chat version: (make sure you are running the latest)
im add and edit some code in .less files
![less](https://cloud.githubusercontent.com/assets/22897987/19746436/c57097b4-9bd6-11e6-93b9-f27ed986825d.png)
and iwant rebuild cache files but idont know how??

**Comment by MartinSchoeler** [comment]
I am closing this issue since github is not the best place to ask this kind of question. Please join our community server in the [#support](https://demo.rocket.chat/channel/support) channel or ask your question on stackoverflow with the [rocket.chat tag](https://stackoverflow.com/questions/tagged/rocket.chat)
