### ISSUE TITLE
Create a link to display all available emojis

### ISSUE THREAD

**Issue by marceloschmidt** [RocketChat/Rocket.Chat#480]

**Comment by sampaiodiego** [comment]
as @fduraibi suggested in #1599 
> Add a "more..." link at the bottom of the basic emoji list that opens up a tabbed window with all available emojies, similar to how Discourse does it:

![cqmh7lpuaaefk-a](https://cloud.githubusercontent.com/assets/432460/11664265/b7152dbe-9dae-11e5-9dcd-43aca5662b91.png)

**Comment by djeber** [comment]
this will be helpful

**Comment by wtsarchive** [comment]
I think this task is actually kind of important, because it would allow us to change the current behavior of message box, which currently displays a list of emojis when one types `:` sign. This is very disruptive as it requires you to press Enter to acknowledge your emoji choice every time you want to write one by hand (it's especially annoying for writing simple ones like `:)` and similar. If we had a separate list of emojis, we could only show emoji autocompletion after typing one or two characters **after** colon.

**Comment by engelgabriel** [comment]
http://blog.discourse.org/2015/12/emoji-and-discourse/

**Comment by sampaiodiego** [comment]
just adding more references:
https://github.com/Ranks/emojione
http://emoji.codes/
http://www.emoji-cheat-sheet.com/
http://emojione.com/demo/

**Comment by mattbk** [comment]
+1
