### ISSUE TITLE
501 Mail Not Sent

### ISSUE THREAD

**Issue by Zegorax** [RocketChat/Rocket.Chat#4851]
Your Rocket.Chat version: 0.45.0 with Docker

I tried by many ways possible to get the registration mail verification to be working, but I couldn't figure it out.
There's nothing in the logs, the instance is running fine and everything else is working. I can send successfully a mail to my user with the test button on the SMTP page. If I add a user manually, the mail comes successfully too. The mail does not send in those cases : 

- The user register for the first time (Message : Mail successfully sent, but isn't)
- The user forgot his password (501 Mail not sent)

I don't know what to do, since there's nothing in the logs.

**Comment by sscholl** [comment]
this issue was closed via #6940 in 0.56.0 FOR ME

Go to Administation->E-Mail->SMTP->Protocol (smtps)

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Closing this as there are far too less information to even try to reproduce your issue. Please add additional logs and adhere to the [issue template](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/ISSUE_TEMPLATE.md) if this issue is still present for you in the latest stable version of Rocket.Chat.

Cheers
Thomas
