### ISSUE TITLE
When will Rocket.Chat support Firebase Cloud Messaging?

### ISSUE THREAD

**Issue by kramer65** [RocketChat/Rocket.Chat#4861]
We deployed the Rocket.Chat Cordova app to the Play Store under a client's name and want to set up push notifications for it, but GCM seems [to be deprecated](https://developers.google.com/cloud-messaging/) in favour of FCM (Firebase Cloud Messaging). 

From the issues https://github.com/RocketChat/Rocket.Chat/issues/4182 and https://github.com/RocketChat/Rocket.Chat/issues/4468 I think I understand that the Rocket.Chat Cordova app does not support FCM yet.

Will the Cordova app support FCM in the future, and if so, does anybody have any idea or estimation as for to when that will be?

**Comment by maxlinux2000** [comment]
+1 UP!

I confirm. If we go to create a new gcm api key, rocketchat doesn't works because this api key is in firebase.
Same thing happens on a plugins in wordpress using same key, so is not a api key mis-configuration.

In addition from firebase consiole we can send push messages to the apps, and 


Firebase -> Rocket.chat.cordova = OK!
Rocket.chat.browser -> Rocket.chat.cordova = Unautorized!
Rocket.chat.cordova -> Rocket.chat.browser = Unautorized!
Rocket.chat.cordova -> Rocket.chat.cordova = Unautorized!

**Comment by fabian-z** [comment]
@maxlinux2000 
I created my GCM project today and got the Unauthorized error, too. Now push notifications work for me after importing the GCM project into [Firebase Console](https://console.firebase.google.com) and using the server key displayed there (different from GCM API key). It should work as well when creating a new project there.

Although it should be noted that the warning there states that support for server keys will be dropped in favor of Firebase "cloud messaging tokens", so I think proper FCM support as requested here should still be on the roadmap.
