### ISSUE TITLE
If admin renames a user during DM, the user's UI displays 'You must join to view messages in this channel'

### ISSUE THREAD

**Issue by garychapman** [RocketChat/Rocket.Chat#4892]
Using RC 0.45.0

**Steps to reproduce:**

1. (while logged in as admin) Start a DM with a user
2. Go to Admistration->Users and rename the user you're DM'ing with
3. On the user's UI, the 'Start of conversation' message is replaced with 'You must join to view messages in this channel'

**Cause:**

The `removed` handler in _roomObserve.coffee_ sets `roomData<_id>` to `undefined`, and then the `canPreview` helper in _room.coffee_ throws an exception when trying to test `room.t` because `room` is undefined. An obvious easy fix would be to change this to `room?.t` but I'm not sure if this might have unforeseen consequences.

**Comment by gabriellsh** [comment]
Thanks for reporting this issue. We value your time in helping us to make Rocket.Chat great. We always try to fix confirmed problems as quickly as we can, and it appears that the issue you reported might already be fixed in the latest release. Can you please help us test it against current latest release? Much appreciated. And please remember to backup your data before upgrading, just to be safe. Cheers!
