### ISSUE TITLE
[n00b] Need advice for coffee script implementation

### ISSUE THREAD

**Issue by katopz** [RocketChat/Rocket.Chat#492]
Hi guys,

I'm pretty new to coffee script and have some question.
* What the best IDE for it? jump click to definitions and breakpoint debug would be nice.
* I saw plenty of example e.g. http://meteorpedia.com/read/REST_API#Restivus in js but not in coffee script, How can I deal with that? I should convert to coffee script first? This not make sense to me because I will lost in translation somewhere and should take too much time.
* Can I mix (current code base)coffee script with (my own features)js? What build workflow for that? I know I must learn coffee script somehow, but I got very tight timeline to deal with for this project.

I know it's not related much to project. I just lost and whining.
Feel free to close it if you not in the mood.

Thanks.

**Comment by engelgabriel** [comment]
Hi,

Most of use just use Eclipse 3.0 with a free plugins for CoffeeScript, but I know that @Sing-Li is a Jetbrain fan.

Maybe a quick explanation about how CoffeeScript works on meteor will help:

Any Meteor app is "just" a NodeJs app. The NodeJS binary don't know a thing about CoffeeScript... so who does it works? When you `meteor run` or `meteor build` the meteor command will scan all your project directories recursively, and transpile all .coffee files into new .js files. That answers your 3rd question, because if you have a .js file, meteor will just skip one step on the _build_ process.

You can go to http://coffeescript.org/ and click Try CoffeScrtip to convert from CoffeeScript to JS, or go to http://js2.coffee/ for the other way around.

We expect PRs to be written in CoffeeScript. :)
