### ISSUE TITLE
Security issue: editing messages

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/Rocket.Chat#4930]
Your Rocket.Chat version: 0.45.0

A client of mine brought this to my attention and I can confirm the validity. There's a strange security issue with regard to editing messages, an older version appears when a message is ‘replied’ to or referenced, rather than the current version of the message. This could be potentially "bad" in some scenarios.

**Comment by lucasvanhalst** [comment]
That's true, links to messages are just attachments to messages instead of actual references to a message. As a result an older version of the message can be stored in such an attachment.
I guess attachments like that be refactored so it only stores a reference to another message instead of the message text

**Comment by cyclops24** [comment]
Part of #8494

**Comment by engelgabriel** [comment]
I am not sure this is a bug, I can image the in my case, I'd like the version f the message I replied to or quotes to never change... or if it changes, there should be a way for people to see the version that I was actually referring to.
