### ISSUE TITLE
Push notification without using GCM or APN

### ISSUE THREAD

**Issue by g0ldstrike** [RocketChat/Rocket.Chat#4942]
Your Rocket.Chat version: 0.46.0-develop

I successfully got my push notifications working for the abovementioned version, in combination with the Cordova app, built with my own GCM credentials.

I am aware of the disadvantages of notifications without using GCM or APN. However, I was curious whether Rocket.Chat currently supports notifications being sent straight from server to app, possibly by using the current TCP connection (not going via Google's/Apple's servers). Is this implemented, or are the only options using the gateway/GCM/APN?

**Comment by Nemra1** [comment]
I gree with you

**Comment by jszaszvari** [comment]
Apple do not allow this, it's against their developer terms to release an app that circumvents APNS. If you want push notifications you need to use their system. 

Why would you want to do it yourself when both Google and Apple have developed state of the art systems to do exactly that.

**Comment by maxlinux2000** [comment]
I don't think that is possible, because the push messages works only with GCM/APN credentials + the developer digital sign and in case of google the reversed domain id of developer team.... too much!!

I think that can be useful mail advise + a sort of deep links.
The mayor email server, like google, yahoo, hotmail... works like a push message, so in the moment that your account receive a new email, your phone advise you with a push.

If in the body of email we can insert a deep link that run rocket.chat and open the message, we have a working push message system, without GCM/APN credentials.
The only request for the user is to use a push like email server, like gmail, but consider that all android user have one account, and most users of iOS, too.

**Comment by rafaelks** [comment]
Currently it's not possible to send push notifications without FCM or APN, we may revisit this in the future with other solutions, thank you! 👍

**Comment by jcz1** [comment]
:-(

**Comment by eladnava** [comment]
Hey all,
Just waned to let you know that it's possible to send push notifications nowadays to Android devices without FCM, using a paid product called Pushy, which uses an MQTT connection to deliver notifications reliably:
https://pushy.me/

Full disclosure: I work for Pushy.

**Comment by dalhakeem** [comment]
@eladnava have you tried this or by chance have any instructions to do this?

**Comment by dalhakeem** [comment]
Guess its time to move to guilded since no one has any info on why mobile notifications just randomly stops working. good luck everyone.

**Comment by maxlinux2000** [comment]
I have stopped using rocketchat, not because it is bad, but because of
the notifications.
Instead I use DeltaChat, which is an email client that looks like
WhatsApp. It allows me to have my own server (IMAP) and notifications
are ensured because IMAP-Push is used for this job. And all this is on
a single server without having to trust third parties.

Ideally, Rocketchat would also have its own notification system.

greetings and good luck
