### ISSUE TITLE
Can't use some Rocket.Chat features using docker on aliyun

### ISSUE THREAD

**Issue by BenjaminUJun** [RocketChat/Rocket.Chat#5047]
Your Rocket.Chat version: (0.45.0)
 I deployed the Rocket.chat on docker at aliyun, and follow the instructions at the https://rocket.chat/docs/, but some features just can not pop up like uploading a file, voice chat, Face to Face Video Conferencing (aka WebRTC ) etc. Does anyone have the same issue as mine, plz leave some comments!

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @BenjaminUJun 

I am closing this issue because we think there is no actual bug in Rocket.Chat in what you're describing. Here's why:

* I deem it to be very unlikely to be an issue of Rocket.Chat itself. This is more likely due to either the way you deploy or the way you configure your Rocket.Chat instance

We use Github mainly for discussing bugs though. We understand, that setting up and operating a Rocket.Chat server is not trivial, yet we do not have the woman/man-power to help everybody. That is unfortunate, but simply a limitation of time. If it should turn out from your feedback to this message, that there is a bug involved, we will try to fix it with you.

That being said, we are very thankful that our community also does a great job in helping each other. I would therefore like to point you to some places where you can try asking for help. Usually, some friendly human being has time for you and your issue:

* **The Rocket.Chat Community Support Channel**: https://open.rocket.chat/channel/support
* **The Rocket.Chat Community Support Forum**: https://forums.rocket.chat/c/community-support

If you don't find a solution to your problem there, don't fret, as we also offer paid support: https://rocket.chat/support

You could, of course, spare yourself the hassle entirely and just choose the hosted version, where we provide you with a running Rocket.Chat instance: https://rocket.chat/cloud

Cheers
Thomas
