### ISSUE TITLE
Unable to import CSV

### ISSUE THREAD

**Issue by a5his** [RocketChat/Rocket.Chat#5050]
Rocket.Chat version 0.46.0

Hi, I was testing this new csv import feature but not able import my sample csv files. As I upload my sample csv file it throws an error message `A file uploaded isn't a valid csv export file`. I have attached my sample csv files along with this issue. 

I have followed this released document https://rocket.chat/docs/administrator-guides/import/csv/

Can you help me understanding what is wrong with my csv files or am i missing anything?

[sample-csv.zip](https://github.com/RocketChat/Rocket.Chat/files/613728/sample-csv.zip)

Thanks

**Comment by graywolf336** [comment]
Hi @a5his, as stated in that guide it must be a **flat zip** which means the first time in the zip can not be a folder but instead should be the files. If you're zipping on linux/mac then you do the zip command from inside the folder which contains the `users.csv` and the `channels.csv`. Does that make sense?

**Comment by a5his** [comment]
@graywolf336 yep. Thanks for an explanation.

**Comment by graywolf336** [comment]
@a5his Did that make it work for you? If so, mind going ahead and closing this issue?

**Comment by a5his** [comment]
@graywolf336 importing CSV worked but I got another issue when something goes wrong. 

While importing CSV, if there is any error I have to restart the server to do another import. The error was duplicate timestamp provided in messages and was unintentional.

**Comment by graywolf336** [comment]
@a5his Please open a new issues about that, with the error details and stacktrace

**Comment by a5his** [comment]
@graywolf336 
Not able to create this error. 
Thanks.

**Comment by graywolf336** [comment]
@a5his I don't follow then....so you are getting an error or are you not? 🤔

**Comment by asharabdullah** [comment]
Hi all I have just started installing Rocket Chat today and I've read about how the zip file should be structured.
I have tried the follwoing ways:
1. Folder containing only users.csv and zipped up the folder (in Mac)
2. Folder containing users.csv and directmessages folder and general folder then zipped up the folder
3. zipped up the users.csv directly

Method 3 caused a problem importing.
Method 1 and 2 do not lead to users being created. Instead on the import screen before I click on "start importing" button the csv entries are counted as "Messages" instead of users.

Does anyone else have the same problem?
Thank you.
Best regards

PS: If this does not seem to work I would not mind doing a direct import to database if we could do that.
<img width="895" alt="Bildschirmfoto 2021-01-24 um 13 34 27" src="https://user-images.githubusercontent.com/77923322/105630363-0a198400-5e49-11eb-8c72-4df1bf5d6be2.png">
<img width="400" alt="Bildschirmfoto 2021-01-24 um 13 29 25" src="https://user-images.githubusercontent.com/77923322/105630370-169ddc80-5e49-11eb-9dd7-34c535998f12.png">
