### ISSUE TITLE
Windows Server 2012 R2 Installation issues

### ISSUE THREAD

**Issue by manjotsingh108** [RocketChat/Rocket.Chat#5069]
Hi,
I m trying to install Rocket chat on server but getting errors while running npm install command

![rc windows issue](https://cloud.githubusercontent.com/assets/24263735/20790637/38295c4a-b7df-11e6-9da0-de5928feee23.png)

Need help to resolve this issue..

Thanks..

**Comment by KonradTUM** [comment]
Edit the following file:
programs/server/npm-shrinkwrap.json
Find the fibers section and replace 1.0.5 with 1.0.10 in all 3 lines like this:
 `"fibers": {
      "version": "1.0.10",
      "from": "1.0.10",
      "resolved": "1.0.10"
    },`

Also, in this folder:
programs/server/npm/npm-bcrypt/node_modules
replace bcrypt with an updated version (0.7.8 -> 0.8.5).

**Comment by basitkhanpk** [comment]
Hi, Thanks for your great help! i hve changed the entries in fiber and installation is successful, i created the service as well, but when its not listening on said port http://localhost:3000 boht mongodb & rocketchat services are up and running. can you please guide what should i do to troubleshoot it?

**Comment by basitkhanpk** [comment]
While Diagnosing the log file i found the following error in rocketchat.err file


C:\RocketChat\programs\server\boot.js:283
}).run();
   ^

Error: $ROOT_URL, if specified, must be an URL
    at Error (native)
    at packages/meteor/url_server.js:8:1
    at C:\RocketChat\programs\server\packages\meteor.js:1132:4
    at C:\RocketChat\programs\server\packages\meteor.js:1274:3
    at C:\RocketChat\programs\server\boot.js:242:10
    at Array.forEach (native)
    at Function._.each._.forEach (C:\RocketChat\programs\server\node_modules\underscore\underscore.js:79:11)
    at C:\RocketChat\programs\server\boot.js:137:5


in Windows Event Viewer Log:
Child process [13152 - C:\Program Files (x86)\nodejs\node.exe  --harmony C:\RocketChat\node_modules\node-windows\lib\wrapper.js --file C:\RocketChat\main.js --log "Rocket.Chat wrapper" --grow 0.25 --wait 1 --maxrestarts 3 --abortonerror n --stopparentfirst undefined] finished with 1

i dont know what is missing now..

**Comment by robbihun** [comment]
@basitkhanpk Check your ROOT_URL value in {installpath}\daemon\rocketchat.xml - make sure it is in a url format e.g. "http://localhost" instead of "localhost"

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @manjotsingh108 

I am closing this issue because we think there is no actual bug in Rocket.Chat in what you're describing.

We use Github mainly for discussing bugs though. We understand, that setting up and operating a Rocket.Chat server is not trivial, yet we do not have the woman/man-power to help everybody. That is unfortunate, but simply a limitation of time. If it should turn out from your feedback to this message, that there is a bug involved, we will try to fix it with you.

That being said, we are very thankful that our community also does a great job in helping each other. I would therefore like to point you to some places where you can try asking for help. Usually, some friendly human being has time for you and your issue:

* **The Rocket.Chat Community Support Channel**:
https://open.rocket.chat/channel/support (for general support)
* **The Rocket.Chat Community Dev Channel**:
https://open.rocket.chat/channel/dev (for development-focussed support)
* **The Rocket.Chat Community Support Forum**:
https://forums.rocket.chat/c/community-support

If you don't find a solution to your problem there, don't fret, as we also offer paid support: https://rocket.chat/support

You could, of course, spare yourself the hassle entirely and just choose the hosted version, where we provide you with a running Rocket.Chat instance: https://rocket.chat/cloud

Cheers
Thomas
