### ISSUE TITLE
Add the ability to type immediately after a mention tag

### ISSUE THREAD

**Issue by Molle500** [RocketChat/Rocket.Chat#5167]
One thing that happens from time to time is people ending their sentence with taggning the person the post is about and ending with a dot. However the dot breaks the tag and is now just normal text instead.
Both slack & discord allow immediately typing after a tag which is really nice.

Discord:
![dsc](https://cloud.githubusercontent.com/assets/17712562/21072896/dd356420-bed0-11e6-83a9-0e01ff810ae0.PNG)

Rocketchat: 
![rc](https://cloud.githubusercontent.com/assets/17712562/21072899/e2c078da-bed0-11e6-932f-d4785a512548.PNG)

**Comment by rodrigok** [comment]
We need to block usernames ending with `.`, now it's possible to create usernames like `rodrigo.`

**Comment by Molle500** [comment]
@rodrigok Actually on discord and slack you can type anything after the tag name. When you press tab or enter to snap out of the tag so it knows it done. The tag will then stay like that, even if u type like @rodrigokasfga

**Comment by ulope** [comment]
This is a really annoying issue. We've had quite a few cases where people haven't been aware of messages due to a period or comma preventing the mention from working.

Examples of common problematic cases:
- `Please remember to do the thing @someuser.`
- `This needs to be looked at by @someuser, @otheruser or @nobody.`

**Comment by engelgabriel** [comment]
@ggazzo maybe we can fix this with the new message input component?

**Comment by hugocostadev** [comment]
Fixed!
