### ISSUE TITLE
Create a Help tab on flex-tab-bar

### ISSUE THREAD

**Issue by karlprieb** [RocketChat/Rocket.Chat#5188]
Add a tab called Help on `flex-tab-bar` and move formatting tips to the new tab.

@RocketChat/core

**Comment by geekgonecrazy** [comment]
This would take into account the stuff located below the text input also?
![image](https://cloud.githubusercontent.com/assets/51996/21111934/54a11ee8-c069-11e6-9e1d-a2fee6f2a130.png)

I ask because frequently notice this gets really screwy especially on mobile when the text "someone is typing" is added

**Comment by engelgabriel** [comment]
Yes, we will remove the *stuff* located below the text input, and add something like this on the side tab:

![image](https://cloud.githubusercontent.com/assets/1000217/21112122/a8cc7e28-c08b-11e6-9f52-8e7bb1a22683.png)

**Comment by karlprieb** [comment]
We decide to move this to the bottom of message box, so I will close this issue.
