### ISSUE TITLE
getUsersOfRoom does not return users of room

### ISSUE THREAD

**Issue by spinza** [RocketChat/Rocket.Chat#5193]
Your Rocket.Chat version: 0.47.1

This call doesn't actually return users.  Basically it seems to fail because the subscription data does not contain the user objects (I think). 

The method returns "subscriptions" here: 
https://github.com/RocketChat/Rocket.Chat/blob/master/server/methods/getUsersOfRoom.js#L2

But they are all filtered out here:
https://github.com/RocketChat/Rocket.Chat/blob/master/server/methods/getUsersOfRoom.js#L2

The resulting structure returns the number of users/subscriptions in the channel but the records structure is empty.

**Comment by spinza** [comment]
Is this something that is fixable?

**Comment by spinza** [comment]
It wasn't working when I tested it as above. It didn't return anything in a channel with online users.

**Comment by ggazzo** [comment]
hey @spinza , can you show us more information? do you have a public server?(maybe we could test), because we are quite sure this method works, we use them on our member list...
open.rocket.chat:
![image](https://user-images.githubusercontent.com/5263975/41198154-2072038e-6c49-11e8-9bb5-34e4f9bea8c5.png)

I made a test here, and I couldn't find any problem with the result
![s3zb8aw1u0](https://user-images.githubusercontent.com/5263975/41198147-f2e8d348-6c48-11e8-95eb-7eba03b1518f.gif)

**Comment by spinza** [comment]
Back when I posted it was not working.  I was wanting to integrate something and the API call did not work. Hence my comment.  I gave up on this and haven't looked at it since.  May be fixed now as you seem to show.

I wanted to automatically add users to a room based on some external data.  Could not check if they were in the room as this call didn't work.

**Comment by spinza** [comment]
Maybe this was the fix:
https://github.com/RocketChat/Rocket.Chat/commit/c9bfdc6747769c7f2dd2f9b162c376648311436f#diff-3ebd579e0d8906b13b7eb04e4bb61e1a

**Comment by ggazzo** [comment]
thanks @spinza, then I will be closing, if you try again and for some reason you couldnt use, please let us know.
