### ISSUE TITLE
Rocket.Chat with systemd 

### ISSUE THREAD

**Issue by thiesschneider** [RocketChat/Rocket.Chat#5361]
Hi, I try to use Rocketchat with systemd combined with an automated Letsencrypt cert and automated nginx configuration.

If I run docker-compose with the file from github my nginx does not write the configuration the right way and I only can connect via IP:Port (which is certainly a problem of my nginx container but I think it can happen more people than me). 
If I try to translate the docker-compose file to systemd (on my own or via [container-transform](https://github.com/micahhausler/container-transform) for example) rocketchat is not starting correctly and exits if i try to run the containers.
I have three systemd files for Rocketchat (Rocketchat, Rocketchat database and the Rocketchat database replica) 

Now I found the systemd part in the docs and I think it is not up to date: https://rocket.chat/docs/installation/docker-containers/systemd/ 
It says: DockerFiles.git cannot be found.
Can you please update the docs and explain a little more?

I run coreos and It would be great to run the container without docker-compose (or is this the way it should be done) and integrate the automatic cert and conf file for nginx. Or do you prefer to run Rocketchat with traefik? Why?

It would also be great to make the docs more clear for more users. 
For example: I cant find any hints about why opolog is good for rocketchat except in the ubuntu part. Or it would be nice to have a docker-compose file more explained (what ENVs you can use and which are the containernames etc.)

I read through the issues to find some answers for me but I think it would be nice to add more documentation and make it easier for people to use rocketchat (individually) - because its great software ;)

**Comment by dohseven** [comment]
:+1: I'm also struggling with RocketChat and systemd...

I use docker-compose to run the latest version of RocketChat on an Ubuntu server, but I don't find any documentation about the way to use systemd to automatically start RocketChat at boot.

The only information I found is the following:
- This [page](https://rocket.chat/docs/installation/docker-containers/systemd/) about how to "Deploy Rocket.Chat to Linux that run on systemd": as indicated by @thiesschneider, the link to the [DockerFiles.git](https://github.com/RocketChat/DockerFiles.git) is dead.
- This [page](https://github.com/RocketChat/Rocket.Chat.Docs/blob/master/3.%20Installation/4.%20Manual%20Installation/PM2,%20Systemd,%20Upstart.md) about systemd, but it doesn't explain how to use docker-compose with systemd. Is it impossible?
- This [section](https://rocket.chat/docs/installation/docker-containers#7-automatic-startup-crash-recovery) of the installation manual only indicates how to create upstart jobs.

Is there any more documentation available?

**Comment by engelgabriel** [comment]
Did you guys look at http://container-solutions.com/running-docker-containers-with-systemd/ ?

**Comment by thiesschneider** [comment]
Hey @engelgabriel,

do you manage to run rocket.chat with systemd?

here are my files:

Rocket.Chat:
```
[Unit]
Description=RocketChat
Requires=docker.service
Requires=db_rocketchat.service
Requires=db_repl_rocketchat.service
After=docker.service
After=db_rocketchat.service
After=db_repl_rocketchat.service

[Service]
EnvironmentFile=/etc/environment
User=core
#KillMode=none
Restart=always
TimeoutStartSec=0
ExecStartPre=-/usr/bin/docker kill rocketchat
ExecStartPre=-/usr/bin/docker rm rocketchat
ExecStartPre=-/usr/bin/docker pull rocketchat/rocket.chat:develop


ExecStart=/usr/bin/docker run \
    --name rocketchat \
    -p 3000:3000 \
    -v /container/rocketchat/uploads:/app/uploads \
    -e "LETSENCRYPT_EMAIL=name@domain.de" \
    -e "LETSENCRYPT_HOST=sub.domain.de" \
    -e "MAIL_URL=smtp://name@domain.de/" \
    -e "MONGO_OPLOG_URL=mongodb://db_rc:27017/local" \
    -e "MONGO_URL=mongodb://db_rc:27017/rocketchat" \
    -e "ROOT_URL=https://sub.domain.de" \
    -e "VIRTUAL_HOST=sub.domain.de" \
    -e "VIRTUAL_PORT=80" \
    rocketchat/rocket.chat:develop

ExecStop=-/usr/bin/docker kill rocketchat
ExecStop=-/usr/bin/docker rm rocketchat

[Install]
WantedBy=multi-user.target

[X-Fleet]
Global=true
```

Rocket.Chat Database

```
[Unit]
Description=db_rc
Requires=docker.service
After=docker.service

[Service]
EnvironmentFile=/etc/environment
User=core
#KillMode=none
Restart=always
TimeoutStartSec=0
ExecStartPre=-usr/bin/docker kill db_rc
ExecStartPre=-/usr/bin/docker rm db_rc
ExecStartPre=-/usr/bin/docker pull mongo:3.2

ExecStart=/usr/bin/docker run \
    --name db_rc \
    -v /container/rocketchat/db:/data/db \
    -v /container/rocketchat/db/dump:/dump \
    mongo:3.2 \
    mongod --smallfiles --oplogSize 128 --replSet rs0

ExecStop=-/usr/bin/docker kill db_rc
ExecStop=-/usr/bin/docker rm db_rc

[Install]
WantedBy=multi-user.target

[X-Fleet]
Global=true
```

Rocket.Chat Database Replica

```
[Unit]
Description=db_repl_rc
Requires=db_rc.service
After=db_rc.service

[Service]
EnvironmentFile=/etc/environment
User=core
#KillMode=none
Restart=always
TimeoutStartSec=0
ExecStartPre=-usr/bin/docker kill db_repl_rc
ExecStartPre=-/usr/bin/docker rm db_repl_rc
ExecStartPre=-/usr/bin/docker pull mongo:3.2

ExecStart=/usr/bin/docker run \
    --name db_repl_rc \
    mongo:3.2 \
    mongo db_rc/rocketchat --eval "rs.initiate({ _id: 'rs0', members: [ { _id: 0, host: 'localhost:27017' } ]})"

ExecStop=-/usr/bin/docker kill db_repl_rc
ExecStop=-/usr/bin/docker rm db_repl_rc

[Install]
WantedBy=multi-user.target

[X-Fleet]
Global=true
```

**Comment by dohseven** [comment]
And here are my files (should I create a separate issue?):
- /etc/systemd/system/rocketchat_mongo.service
`[Unit]
Description=MongoDB service for RocketChat
After=docker.service
Requires=docker.service

[Service]
TimeoutStartSec=0
RestartSec=10
Restart=always
WorkingDirectory=/var/lib/rocketchat
ExecStartPre=-/usr/local/bin/docker-compose stop mongo
ExecStart=/usr/local/bin/docker-compose up -d mongo
ExecStop=/usr/local/bin/docker-compose stop mongo

[Install]
WantedBy=multi-user.target`

- /etc/systemd/system/rocketchat_app.service
`[Unit]
Description=RocketChat
After=docker.service
Requires=docker.service
After=rocketchat_mongo.service
Requires=rocketchat_mongo.service

[Service]
TimeoutStartSec=0
RestartSec=10
Restart=always
WorkingDirectory=/var/lib/rocketchat
ExecStartPre=-/usr/local/bin/docker-compose stop rocketchat
ExecStart=/usr/local/bin/docker-compose up -d rocketchat
ExecStop=/usr/local/bin/docker-compose stop rocketchat

[Install]
WantedBy=multi-user.target`

In my case, the Mongo service keeps restarting, I don't know why:
`$ systemctl status rocketchat_mongo.service 
● rocketchat_mongo.service - MongoDB service for RocketChat
   Loaded: loaded (/etc/systemd/system/rocketchat_mongo.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) since Tue 2017-01-03 14:05:30 CET; 9s ago
  Process: 29703 ExecStop=/usr/local/bin/docker-compose stop mongo (code=exited, status=0/SUCCESS)
  Process: 29647 ExecStart=/usr/local/bin/docker-compose up -d mongo (code=exited, status=0/SUCCESS)
  Process: 29634 ExecStartPre=/usr/local/bin/docker-compose stop mongo (code=exited, status=0/SUCCESS)
 Main PID: 29647 (code=exited, status=0/SUCCESS)
$ systemctl status rocketchat_mongo.service 
● rocketchat_mongo.service - MongoDB service for RocketChat
   Loaded: loaded (/etc/systemd/system/rocketchat_mongo.service; enabled; vendor preset: enabled)
   Active: deactivating (stop) since Tue 2017-01-03 14:05:54 CET; 80ms ago
  Process: 30208 ExecStart=/usr/local/bin/docker-compose up -d mongo (code=exited, status=0/SUCCESS)
  Process: 30192 ExecStartPre=/usr/local/bin/docker-compose stop mongo (code=exited, status=0/SUCCESS)
 Main PID: 30208 (code=exited, status=0/SUCCESS);         : 30260 (docker-compose)
   Memory: 7.8M
      CPU: 1.016s
   CGroup: /system.slice/rocketchat_mongo.service
           └─control
             └─30260 /usr/local/bin/docker-compose stop mongo
$ systemctl status rocketchat_mongo.service 
● rocketchat_mongo.service - MongoDB service for RocketChat
   Loaded: loaded (/etc/systemd/system/rocketchat_mongo.service; enabled; vendor preset: enabled)
   Active: activating (start-pre) since Tue 2017-01-03 14:06:17 CET; 146ms ago
  Process: 30537 ExecStop=/usr/local/bin/docker-compose stop mongo (code=exited, status=0/SUCCESS)
  Process: 30484 ExecStart=/usr/local/bin/docker-compose up -d mongo (code=exited, status=0/SUCCESS)
 Main PID: 30484 (code=exited, status=0/SUCCESS);         : 30742 (docker-compose)
   Memory: 19.1M
      CPU: 139ms
   CGroup: /system.slice/rocketchat_mongo.service
           └─control
             └─30742 /usr/local/bin/docker-compose stop mongo`

**Comment by thiesschneider** [comment]
So I figured out how to get rocket.chat up and running with systemd

I really want to encourage someone to answer my first questions:
> Now I found the systemd part in the docs and I think it is not up to date: https://rocket.chat/docs/installation/docker-containers/systemd/
> It says: DockerFiles.git cannot be found.
> Can you please update the docs and explain a little more?

> ...do you prefer to run Rocketchat with traefik? Why?

>  I cant find any hints about why opolog is good for rocketchat except in the ubuntu part. 

Here are my working setup with systemd files. Please be aware that I use an automated [Nginx Proxy](https://github.com/jwilder/nginx-proxy) and an automated [Letsencrypt generator](https://github.com/alastaircoote/docker-letsencrypt-nginx-proxy-companion)

First you need to create a new docker network and in my case some volumes (see systemd *DATA...* )
`docker network create rocketchat_default`

Then create the systemd files and enable them. In the rocketchat.service I add the nginxproxy to the rocketchat_default network. Otherwise it is not automatically exposed on your subdomain.

db_repl_rc.service:
```
[Unit]
Description=db_repl_rc
Requires=db_rc.service
After=db_rc.service

[Service]
EnvironmentFile=/etc/environment
User=core
KillMode=none
Restart=always
TimeoutStartSec=0
ExecStartPre=-/usr/bin/docker kill db_repl_rc
ExecStartPre=-/usr/bin/docker rm db_repl_rc
ExecStartPre=-/usr/bin/docker pull mongo:3.2

ExecStart=/usr/bin/docker run \
      --name db_repl_rc \
      --volumes-from *DATACONTAINER* \
      --link db_rc:db_rc \
      --net=rocketchat_default \
      mongo:3.2 \
      mongo db_rc/rocketchat --eval "rs.initiate({ _id: 'rs0', members: [ { _id: 0, host: 'localhost:27017' } ]})"

ExecStop=-/usr/bin/docker kill db_repl_rc
ExecStop=-/usr/bin/docker rm db_repl_rc

[Install]
WantedBy=multi-user.target

[X-Fleet]
Global=true
```

db_rc.service
```
[Unit]
Description=db_rc
Requires=nginxletsencrypt.service
Requires=docker.service
After=nginxletsencrypt.service
After=docker.service

[Service]
EnvironmentFile=/etc/environment
User=core
#KillMode=none
Restart=always
TimeoutStartSec=0
ExecStartPre=-/usr/bin/docker kill db_rc
ExecStartPre=-/usr/bin/docker rm db_rc
ExecStartPre=-/usr/bin/docker pull mongo:3.2


ExecStart=/usr/bin/docker run \
    --name db_rc \
    -v .../path:/data/db \
    --volumes-from *2.DATACONTAINER* \
    --net=rocketchat_default \
    mongo:3.2 \
    mongod --smallfiles --oplogSize 128 --replSet rs0

ExecStop=-/usr/bin/docker kill db_rc
ExecStop=-/usr/bin/docker rm db_rc

[Install]
WantedBy=multi-user.target

[X-Fleet]
Global=true
```

rocketchat.service
```
[Unit]
Description=RocketChat
Requires=docker.service
Requires=db_rc.service
Requires=db_repl_rc.service
After=docker.service
After=db_rc.service
After=db_repl_rc.service

[Service]
EnvironmentFile=/etc/environment
User=core
#KillMode=none
Restart=always
TimeoutStartSec=0
**ExecStartPre=-/usr/bin/docker network connect rocketchat_default Nginx**
ExecStartPre=-/usr/bin/docker kill rocketchat
ExecStartPre=-/usr/bin/docker rm rocketchat
ExecStartPre=-/usr/bin/docker pull rocketchat/rocket.chat:develop

ExecStart=/usr/bin/docker run \
    --name rocketchat \
    -v .../path:/app/uploads \
    -e LETSENCRYPT_EMAIL=email@domain.xx \
    -e LETSENCRYPT_HOST=sub.domain.xx \
    -e MONGO_OPLOG_URL=mongodb://db_rc:27017/local \
    -e MONGO_URL=mongodb://db_rc:27017/rocketchat \
    -e ROOT_URL=https://sub.domain.xx \
    -e VIRTUAL_HOST=sub.domain.xx \
    -e VIRTUAL_PORT=80 \
    --link db_rc:db_rc \
    --net=rocketchat_default \
    --expose 3000 \
    rocketchat/rocket.chat:develop

ExecStop=-/usr/bin/docker kill rocketchat
ExecStop=-/usr/bin/docker rm rocketchat

[Install]
WantedBy=multi-user.target

[X-Fleet]
Global=true
```

After that you have to add a file in your v-host volume named sub.domain.xx_location and add (eventually your letsencrypt container has to add something automatically... just restart if you cant connect):
```
client_max_body_size 1234M;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
proxy_set_header Host $http_host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forward-Proto http;
proxy_set_header X-Nginx-Proxy true;
proxy_redirect off;
```

I dont know if I need to link the containers if they are in the same network and added the "--expose" variable because of some github answer...

Perhaps it is possbile to update the docs?

**Comment by thiesschneider** [comment]
#5465
