### ISSUE TITLE
IOS/Mobile - Open app to last used state (Channel/DM) [$100]

### ISSUE THREAD

**Issue by bleomycin** [RocketChat/Rocket.Chat#5413]
It would be extremely nice if the ios app had an option to pick up where you left off from instead of returning to the Home screen at every launch. 

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=40600786)](https://www.bountysource.com/issues/40600786-ios-mobile-open-app-to-last-used-state-channel-dm?utm_source=40600786&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by engelgabriel** [comment]
@laggedHero we already to it on the iOS version, so it should be relatively easy to do it on all clients.

**Comment by bleomycin** [comment]
@engelgabriel This is already done on the ios client? Is there a setting I missed? My ios client does not function this way, it returns to the Home screen when the app is opened.

**Comment by graywolf336** [comment]
@bleomycin I believe he means the native iOS version which is under development.

**Comment by engelgabriel** [comment]
I mean the beta native one :)

**Comment by snaiperskaya96** [comment]
Should this happen on all the platform instead of only iOS and android?

**Comment by laggedHero** [comment]
@engelgabriel The iOS native and the iOS Cordova versions are completely different beasts. Doing on the native does not mean it will be easier to do on the Cordova later. There's no direct relation.

@bleomycin I'll see it open again in the same channel you left. Would that work?

**Comment by bleomycin** [comment]
@laggedHero sure same channel is fine as long as that behavior also applies to direct messages? I spend an awful lot of time in direct messages as opposed to public channels.

**Comment by soundstorm** [comment]
Just posted a hot fix in #5708 - I put it into custom scripts / logged in

**Comment by snaiperskaya96** [comment]
So how did this finish up? Is it solved or?

**Comment by rafaelks** [comment]
@snaiperskaya96 I’m sorry for the delay in our response and thanks for asking. We’re dropping support on new features and improvements in our Cordova application, since we are now investing everything in our native apps.

If you still need this feature being implemented in Cordova, I suggest that someone from the community (or you?) develop it and submit a pull-request to our project.

If you want to check our native apps, download them here on the following links:

- iOS: https://itunes.apple.com/us/app/rocket-chat/id1148741252?mt=8
- Android: https://play.google.com/store/apps/details?id=chat.rocket.android

Thank you!
