### ISSUE TITLE
501 Bad sender syntax for password reset emails.

### ISSUE THREAD

**Issue by jGleitz** [RocketChat/Rocket.Chat#5473]
Your Rocket.Chat version: 0.48.2 (installed with `snap`)

When a user attempts to reset their password in the Login form, it results in the error message 

> 501 5.1.7 Bad sender address syntax

![mailerror](https://cloud.githubusercontent.com/assets/4305652/21769032/030d08ba-d67d-11e6-95a7-63d7cac4fae1.png)

Sending emails works in other cases, though, for example when

 * adding a new user through the admin interface
 * testing the email settings in the admin interface

**Comment by rapcal** [comment]
Rocket.Chat version `0.49.4` installed on `Ubuntu 16.04` via `snap`

Logging a similar issue here, because it really seems to be closely related. Excuse me in advance if I should have opened another ticket.

Password and verification emails are failing with MAIL FROM syntax error, as per the screenshot below. Other messages are sent without issues. 

![screen shot 2017-01-22 at 10 14 08](https://cloud.githubusercontent.com/assets/620436/22182390/90a0eb34-e08b-11e6-9818-037ac6e3fb02.png)

From my smtp provider logs I get something like this (relevant nodes only) :

```json
{
  "error_code":"501",
  "raw_reason":"501 5.5.2 MAIL FROM syntax error",
  "reason":"501 5.5.2 MAIL FROM syntax error",
  "type":"policy_rejection"
}
```

Being a policy rejection on the sender's address, my suspicion is that RocketChat is not getting the correct `From_Email` setting on these email instances (validations/pw reset).

**Comment by rapcal** [comment]
Reading the source code, I've stumbled upon the `_addSmarshSyncedCronJob`.
Just reboot the server and everything is working.
Maybe a lucky break 👍

**Comment by jGleitz** [comment]
Neither rebooting the machine nor restarting the Rocket.Chat server application changes the issue for me.

**Comment by CCRDude** [comment]
Exactly the same problem here, even after updating to 0.50.1.

**Comment by dark-penguin** [comment]
I can confirm that this is still present in 0.53.0. I run Rocket.Chat with Docker, not snap, and I have not set MAIL_URL variable because according to #6192 this is not necessary as it will be automatically built from the values in Administration -> Email -> SMTP . Indeed, test messages work, "Registration via Admin" messages work, but email confirmation does not work - and hence people either can not create their own accounts, or can not receive notifications if email validation is not required for account creation.

**Comment by kartwang** [comment]
I have same problem in 0.52.0, and i check my mail server log, it's say :

`Apr 18 18:56:56 smtp postfix/smtpd[6302]: connect from server1 [x.x.x.x]

Apr 18 18:56:56 smtp postfix/smtpd[6302]: lost connection after MAIL from server1 [x.x.x.x]

Apr 18 18:56:56 smtp postfix/smtpd[6302]: disconnect from server1 [x.x.x.x]
`

The test mail is work fine in SMTP setting, and send invitation mail.

I has try "restart server" button in Administrator -> General -> RESTART THE SERVER, and my server freeze after 2 sec. I need kill the process and restart the process. 

I also try restart my machine, but still not working.

**Comment by alexweissman** [comment]
I am also experiencing this issue in 0.55.1, on Ubuntu 16.04.  Other features that use SMTP work fine.

**Comment by mwinckler** [comment]
This appears to still be an issue on 0.63.1 (installed via snap). The `From` header is entirely missing on password reset emails, causing them to be rejected by some SMTP servers.

**Comment by wegerhoff** [comment]
Still having this issue with Version 2.4.11.
Mail-Sending fails only for PW-Reset function. Restarting of service/server didn't help.
