### ISSUE TITLE
REST API login with encrypted password

### ISSUE THREAD

**Issue by rasos** [RocketChat/Rocket.Chat#5494]
We are developing a native App for Rocket.Chat for Android, iOS & WP and make heavily use of the REST API and DDP calls. At login, we can send the password in 0.48.2 in plain text only: 
https://rocket.chat/docs/developer-guides/rest-api/authentication/login
However, we do not want to store it in plain text on the mobile device.
Could we have an option to login with a sha256 password?

**Comment by rasos** [comment]
Meanwhile we managed to login via DDP only, handing over token in cookieJar, so we do not store the password anymore in the App.

**Comment by graywolf336** [comment]
If you're developing a native application, DDP methods is the best way to go so that items are real time and you subscribe to data instead of having to continually poll.

However, this depends on https://github.com/kahmali/meteor-restivus/pull/217 being merged in. Closing this in favor of that pull request since that is the restapi library we use.

**Comment by kahmali** [comment]
We've merged the PR in Restivus mentioned above. It's been published in [v0.8.12](https://github.com/kahmali/meteor-restivus/blob/devel/CHANGELOG.md#v0812---2017-01-23). Just a heads up.
