### ISSUE TITLE
Video calling and screen/session sharing functionality.

### ISSUE THREAD

**Issue by spathare21** [RocketChat/Rocket.Chat#5632]
Your Rocket.Chat version: (make sure you are running the latest)

ca we have video calling and screen sharing functionality with rocket chat, like hangout call. as rocket chat is quite similar to slack channel and i think slack do not have calling and screen sharing functionality.
if we add that in rocket chat it will be an added advantage. and will help to increase the users.

this funtionality should have to be between 1:1 and 1:M i.e 1 user to group and user to user.

**Comment by Nemra1** [comment]
we need too add call ringtone first 
to now we dont have call ringtone

**Comment by jszaszvari** [comment]
There is screen sharing and video calling through the JITSI solution which is working well as of the latest release (for the desktop clients)

The only thing that would make it a  'call' would be if you could change the message sound for the video call to be something different rather than the default message sound.

**Comment by rodrigok** [comment]
Since we already have Jitsi support for video and screen sharing I'll close this one.
