### ISSUE TITLE
Trying to run meteor build command runs into error

### ISSUE THREAD

**Issue by danXyu** [RocketChat/Rocket.Chat#569]
![error](https://cloud.githubusercontent.com/assets/4897245/9442118/0cdb3276-4a48-11e5-8961-b60841f8c32c.png)

While the meteor build command is running, it runs into "Killed" during the minifying phase of the build. Don't know why this would be occurring.

**Comment by rodrigok** [comment]
Probably you are having an issue with insufficient memory.

While Meteor is minifying all files, servers with less than 1024mb of ram can experience this problem.

You can increase the memory of your server or build in your machine and then send to the server.

Feel free to reopen this issue if the problem is not related with what I said.
