### ISSUE TITLE
Password lost email template variables not working  (some)

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#5914]
Rocket.Chat Version: 0.50.1
Running Instances: 3
DB Replicaset OpLog: enabled

I tryed to create some custom email templates for my users and saw that the following variables not working at the moment:

[name]
[fname]
[lname]

Can you fix this? :-)

**Comment by graywolf336** [comment]
The fix for this is easy, if someone wants to hash it out quickly.

https://github.com/RocketChat/Rocket.Chat/blob/develop/server/methods/sendForgotPasswordEmail.js#L14

Needs to pass in the user data that https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-lib/lib/placeholders.js#L12 requires.

**Comment by ftoledo** [comment]
I have same issue at Verification with custom template text on version 0.62.1
[name] and [email]  are not replaced.
