### ISSUE TITLE
SNAP Update

### ISSUE THREAD

**Issue by dmkjr** [RocketChat/Rocket.Chat#5939]
Rocket.Chat Version: 0.50.1

I have tried to update SNAP by terminal

snap refresh rocketchat-server

However, it's telling me that an update is not available.  Is there another method to push the update?

Thx - David

**Comment by geekgonecrazy** [comment]
@dmkjr Since snaps auto update, we've changed our process slightly.  We no longer immediately release when a new release is cut.  We spot check them and make sure nothing is wrong.  We don't want anyone's server to just randomly go down because of a bad update.  As we increase testing, we will probably make this automatic.  

Just a precaution to protect you guys from an install going down.  I'm testing it now, and it'll be available in a few minutes.

**Comment by dmkjr** [comment]
Thanks.

**Comment by geekgonecrazy** [comment]
Verified and released. Feel free to reach out in the [#ubuntu-snap](https://demo.rocket.chat/channel/ubuntu-snap) channel on our demo server for inquiries like this.
