### ISSUE TITLE
default channel will not show on non-admin sidebar, nor can be accessed

### ISSUE THREAD

**Issue by jy2008** [RocketChat/Rocket.Chat#5975]
after 2 channels, any other channel created and set to default by admin will not automatically show on non-admin user's side bar. Even worse, if some of channels has been changed name, non-admin user cannot even join the channel even though they can see it in "more channels" list, but when they tried to click on it, it gave error message saying: "no channel with name"example" was found"

why is that?

Rocket.Chat Version: 0.49
Running Instances: Ubuntu14.04
DB Replicaset OpLog:
Node Version:0.45

**Comment by MartinSchoeler** [comment]
@jy2008  Thanks for reporting this issue. We value your time in helping us to make Rocket.Chat great. We always try to fix confirmed problems as quickly as we can, and it appears that the issue you reported might already be fixed in the latest release. Can you please help us test it against current latest release? Much appreciated. And please remember to backup your data before upgrading, just to be safe. Cheers!

**Comment by Devact** [comment]
I confirm this issue too.

**Comment by ogubchenko** [comment]
Confirmed in 0.52.0

**Comment by rodrigok** [comment]
Can you guys check if it is fixed in our develop version?

**Comment by MartinSchoeler** [comment]
#7270 fixed this
