### ISSUE TITLE
Changing desktop notification duration does not change anything

### ISSUE THREAD

**Issue by smolendawid** [RocketChat/Rocket.Chat#5999]
Rocket.Chat Version: 2.4.0 and 2.1.0 as well

I noticed that changing desktop notification duration time does not work. Whatever I'll choose, notification  is always displayed for around 3 seconds only. Same using Windows 7 and Mint.

**Comment by engelgabriel** [comment]
I believe the desktop notification duration only works for the web client. @rodrigok is it correct?

**Comment by smolendawid** [comment]
In my opinion it kills the app, becasue the message is hardly seen, easy to miss. I think it is important feature to do

**Comment by kamaok** [comment]
The same on my side
Rocket Chat server - 0.52
It doesn't matter what I set up in duration notification as in web client(web browser) as in desktop client(version 2.4.0)
Moreover it looks like the settings in Administration->General settings->Notification->Duration notification doesn't work properly as well.
It woud be great if you were able to fix it.
For now  it is a big drawback as for me

**Comment by LongShanksBraveHeartKiller** [comment]
Also having this issue. Notification duration appears to do nothing global or user over ride. Same for both chrome and the stand-alone client. Can someone shed some light on this? Both client and server are on latest version.

**Comment by Anguel** [comment]
I did some research and it looks like Windows notification duration can be only controlled through Windows registry, i.e. not by applications directly, and can be set only to up to 5 minutes. In order to prevent chat messages from being overlooked (which happens constantly because users not always sitting in front of their PC just don't see the small number in the tray) the only possibility I can think of is to make the Rocket Chat client blink in the **taskbar** (and optionally in the tray), even when minimized to the tray. Blinking the tray only is also not clearly visible.

**Comment by CurtisVFX** [comment]
We are still experiencing this on Centos 7 with rocketchat 2.13.2
Notifications do not remain longer then a few seconds.

**Comment by tassoevan** [comment]
Issue moved to [RocketChat/Rocket.Chat.Electron #890](https://github.com/RocketChat/Rocket.Chat.Electron/issues/890) via [**ZenHub**](https://www.zenhub.com/)
