### ISSUE TITLE
Configurable Volume for Notifications

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat#6087]
Using html5's `audioelem.volume`

**Comment by madguy02** [comment]
audioelem.volume has to be added in client/notification.js? @graywolf336

**Comment by wildaces215** [comment]
Is this still open I would like to tackle this issue!

**Comment by marceloschmidt** [comment]
@wildaces215 yes, it is open and we thank you for your interest :) let me know if I can help you anyhow.

**Comment by wildaces215** [comment]
Ok I'll get to it when I get a chance!

**Comment by wildaces215** [comment]
I'm looking at the notifications directory and saw the code for notificaiton.js. Should I create a new file in order to create the code for changing of volume or add the code to notificaiton.js?

**Comment by graywolf336** [comment]
@wildaces215 did you ever decide which route to go? If not, then I'd say stick it in the existing file

**Comment by wildaces215** [comment]
No I did not but I'lll stick it it in the existing file then.

**Comment by wildaces215** [comment]
I was thinking for the configurable volume that is there would be a number to se the volume to?

**Comment by lindoelio** [comment]
Hi @marceloschmidt! I'm motivated to solve this issue.

**Comment by lindoelio** [comment]
Hi guys!
As suggestion, I've done implements based on the follows technical design:

- The control of volume for notifications is a new property value of user preferences, stored in your embedded settings document. It's can be configurable in same currently designated UI for setting user account preferences throught out a input range slider wich receive a integer from "0" to "100" value;
- I've created the rocketchat:slider package encapsuling a generic input range styled as slider so improve code reuse and to provide one default HTML5 component at Rocket.Chat core/web for this slider feature. For this, I've also included SCSS suport using the package fourserven:scss, as recomended of MDG on the Meteor Guide.
- Although the property "value" of the HTML5 audio element assume a float number as input value, I suggested the range from of "0" to "100" keeping in mind one simpler default metric (and more flat as possible) for integrations with the data structure on de persisted model, since the others application interfaces will need this feature in the future, probably.

Do it your review and send me your feedback :-)
