### ISSUE TITLE
How can I post a link with anchor text?

### ISSUE THREAD

**Issue by Buzzele** [RocketChat/Rocket.Chat#6096]
Rocket.Chat Version: 
Running Instances: 
DB Replicaset OpLog:
Node Version:

**Comment by graywolf336** [comment]
Markdown style `[text](https://url.com)`

**Comment by graywolf336** [comment]
@alisianoi that would be a new feature inside of Rocket.Chat. The usual procedure for feature requests is as follows:

* feature request is incoming via [the feature requests category in the forums](https://forums.rocket.chat/c/feature-requests)
* feature request is pre-approved by Rocket.Chat team member
* feature request is discussed and refined until it is utterly clear what is to be implemented and what is to be achieved by the feature request. Technical details might be part of this discussion
* feature is approved by Rocket.Chat team member (**or not** - then it will not be done - yet might still be done as a Rocket.Chat App by the community)
* feature request is transferred to github and labelled with "Feature: Planned"

So that's the process I recommend following to get it inside of Rocket.Chat. :)
