### ISSUE TITLE
push notifications real name instead of username?

### ISSUE THREAD

**Issue by iAmShorty** [RocketChat/Rocket.Chat#6114]
Rocket.Chat Version: 0.52.0
Running Instances: 1
DB Replicaset OpLog:
Node Version: 4.5.0 - x64

we have set up ldap auth and some cryptic names that are not showing what user is posting to the channel. is it possible to use the real name instead of the username in chat rooms and push notifications?

**Comment by vooydzig** [comment]
I kind of have similar problem: I was creating users with "cryptic" non-changable user names that I didn't want to show in push notifications. I ended up patching `sendNotificationsOnMessage.js` file so that I get user real name. I.e in `sendNotificationsOnMessage.js` line 267:
```	
if (RocketChat.settings.get('Push_show_username_room')) {
	push_username = user.name ? user.name : user.username;
	push_room = `#${ room.name }`;
}
```

For more generic solution probably additional check should be made if `UI_Use_Real_Name` is set to true. 

As a side note: the most preferable solution for me, would be creating "notifications layout" section in admin page where I could set what I consider `push_username` and `push_room`.

**Comment by sampaiodiego** [comment]
[looks like](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js#L60) we are doing this right now, so closing this =)
