### ISSUE TITLE
Uploaded image preview won't display when putting the title box of apostrophe.

### ISSUE THREAD

**Issue by zorenleo** [RocketChat/Rocket.Chat#6178]
Rocket.Chat Version: 0.52.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: 4.7.3 - x64
<img src="https://i.imgsafe.org/3889fe086b.png">

**Comment by maximiliend** [comment]
I'm having the same issue :
![rocket_chat_screen](https://cloud.githubusercontent.com/assets/4664700/23438353/d01c5b7e-fe11-11e6-8c38-bb7585bba55a.jpg)

with Rocket.Chat Version: 0.52.0 & Node Version: 4.5.0

I can provide more details if needed.

**Comment by Valiantiam** [comment]
I also have this issue exactly. My examples are the same. Version: 0.52.0 & Node Version: 4.5.0

**Comment by tpayen** [comment]
Same here, version 0.54.1
This seems to come from the embedded css in div#inline-image that doesn't escape the image name in url
`background-image: url('https://localhost/file-upload/Krk4gmSGemgXPbH8h/b'lablabla.png');` NOK
`background-image: url('https://localhost/file-upload/Krk4gmSGemgXPbH8h/b\'lablabla.png');` OK

**Comment by reffu42** [comment]
I'm having the same issue, interestingly enough, the image preview seems to work, indicating that like @tpayen said, it's only a problem in the css, not in the database or elsewhere.

**Comment by reffu42** [comment]
As a side effect of this, you can inject custom css into the image preview. For instance, something a co-worker found out is that setting the name (after upload) of a file to `'); position:fixed; top:1em; left: 15em; ` will cause it to sit at the top of the page and not go away until the preview is collapsed. This could be especially bad because you could make an absolute or fixed position image that covers up the screen, preventing the  preview from being collapsed without the use of the browsers dev-tools

**Comment by Hudell** [comment]
It seems to have been fixed already, as I couldn't replicate it. If anybody runs into this problem again it can be reopened.
