### ISSUE TITLE
Reminder of unread messages

### ISSUE THREAD

**Issue by nickolasdeluca** [RocketChat/Rocket.Chat#6218]
We're starting to use Rocket Chat now...
Sometimes my co-workers don't see the notification of a new message and the app doesn't have a way to send a new notification reminding you that you have a unread message...
Is there a way to activate this? 
Also, I've read that rocket chat has an bot and it has custom scripts, can we write something that warns the user in case of unread messages after 5 minutes or something like that?

Rocket.Chat Version: 0.52.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.7.3

**Comment by dmoldovan123** [comment]
+1

**Comment by timkinnane** [comment]
This is an old issue and my impression is that it's not a common requirement and people might even be annoyed by a UI feature that bugged them to read messages. There are visual indications that channels have unread messages (somewhat improved since this was created) and there's been more recent enhancements to add read-receipts on #3411.

I will however take your suggestion for a custom bot script because I think that could be a good solution for those instances where this is more important. Follow that on #10174.
