### ISSUE TITLE
"http" missing from message

### ISSUE THREAD

**Issue by xsoft** [RocketChat/Rocket.Chat#6273]
Rocket.Chat Version:  0.53.0
Running Instances: 1
Node Version: v4.7.3

Message like:

```
pokus
```http://aaaa.cz
bbb
ccc```
```

sends:

```
pokus
```://aaaa.cz
bbb
ccc```
```

Screen: http://imgur.com/a/cfj0D

Like HTTP is missing.
PS: Is also possible that quote (or any other punctuation) NOT resolve this url? (its kinda ugly when sending more URL)

**Comment by localguru** [comment]
can confirm on  0.52.0

**Comment by gdelavald** [comment]
Hey, I'm looking into this one. 
Looks like the rocketchat-markdown interprets the http as the language and removes that from the string.

**Comment by gdelavald** [comment]
I would have to ask someone else about some logic in this feature, seems like when you are adding a multiline block it expects the first word to be the code language and then it automatically does highlighting for that. However, this was causing issues when pasting links directly into the blockquotes, since it would interpret `http` in front of the url as the language and remove that from the message.

To fix this, I made a modification to the code match regex to compare the first line instead of the first word as language, this could lead to a different usage by the users (using the language name in the first line and code only on the subsequent), but I think fixing the issue with the http is something that affects more people. 

Here I'm trying to reproduce the bug, showing that the links are working:
<img width="420" alt="fixing http missing on blockquotes" src="https://cloud.githubusercontent.com/assets/6303966/23683897/48ca7106-037a-11e7-983d-de29031ac6fa.png">

And showing that the language is still recognized when used at the first line (only matches full words, when adding the `:` it loses meaning)
<img width="340" alt="language at first line still works" src="https://cloud.githubusercontent.com/assets/6303966/23683928/76dde37a-037a-11e7-8e2b-a595a76d2025.png">

Let me know if you think this is the correct way to fix the issue. Thanks.

**Comment by Dracozny** [comment]
punctuation causes the issue on the demo server. That said the link will still resolve if preview is enabled

**Comment by karlprieb** [comment]
Hey @gdelavald I agree with you. You can finish your fix :)
