### ISSUE TITLE
Slackbridge is broken

### ISSUE THREAD

**Issue by Vonnguru** [RocketChat/Rocket.Chat#6360]
Rocket.Chat Version: 0.53.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.7.3

Has anyone been paying attention to SlackBridge? It appears it is out of date. Slack Bot's require OAuth and do not appear to have API tokens anymore.

**Comment by jemus42** [comment]
What do you mean? I just tried to set up the bridge and added a new bot for that, receiving a token.

![](https://dump.jemu.name/2017-03-vx6cmpockqw4vsp.png)

The actual syncing however does not work, which is how I found this issue.  
So… _if_ I have a bot API token, _should_ the bridge work?

**Comment by Vonnguru** [comment]
Yes, it does work but the documentation on how to set things up is incorrect. 

The proper link is https://slack.com/apps/A0F7YS25R-bots

The documentation needs to be updated.

**Comment by tanc** [comment]
Slackbridge is working fine for me on 0.55.1 with two way sync. Followed the documentation. Updated rocket and it started working so its possible a reboot of rocket is required.

**Comment by idevit** [comment]
Tested; working, 
updated documentation in pull request.

**Comment by lindoelio** [comment]
Hello, everyone! We've been paying attention to SlackBridge, yep :-) We've implementing fix, improvements and new features around, which are shall available soon for all.

By the time, a Rocket.Chat server restart is really required. The current docs is updated and covering what is need for this.

I'll close this issue, since the question was finished.

Keep in the rocket :-)
