### ISSUE TITLE
Feature Request : "night / dark mode" switch available to users

### ISSUE THREAD

**Issue by Julianoe** [RocketChat/Rocket.Chat#6405]
I'm from the "blue light" fighters team and work (i guess like many of you) on screens a big part of the time, and my users too. One of the first thing that was asked to me when introducing Rocket : "does it have night mode ?"

I know we can redesign through the admin but i though it would be awesome (and not that complicated ?) to **add a Dark/light theme separation and let the user choose one or another in his parameters**.

**Comment by soenkef** [comment]
+1 nice feature!

**Comment by lucasvanhalst** [comment]
This is basically the same as #277, now that they've refactored a lot of the colours it should be a lot easier to implement

**Comment by HammyHavoc** [comment]
Would love to see this; a member of our team is legally blind and struggles with black text on a bright white background, but likewise, some of our team prefer that. Themes change the UX for everybody rather than on an individual level, so per-user themes and/or a dark mode per user would be amazing for accessibility, and even I could appreciate it as I spend so long staring at screens.

**Comment by HammyHavoc** [comment]
Found this earlier today: https://github.com/0x0049/Rocket.Chat.Dark
Something similar as an option per-user would be great.

**Comment by zalloy** [comment]
I agree with @HammyHavoc It would be better to have dark mode available as an option in the rocket.chat client, so that users can choose for themselves which mode to use. Personally, I use a dark theme on nearly everything, so it kind of bugs me that there's no good way to set this for rocket.chat

**Comment by vynmera** [comment]
This should really, _really_ be a thing.
I managed to make a dark theme CSS for Rocket.Chat a little bit ago, but it's very messy because 90% of colors are hardcoded. So if we really want to achieve this (we do), we'll need to redo a lot of our UI templates to get rid of the hardcoded colors...
...if someone can point me in the right directions though, I'll be happy to attempt to port my dark theme into RC :-)

**Comment by HammyHavoc** [comment]
@vynmera I'd buy you a coffee/beer/beverage of your liking if you could sort this!

**Comment by vynmera** [comment]
I've begun work on this, anything specific I should add?

**Comment by HammyHavoc** [comment]
Somewhere between what Discord's dark color scheme looks like without ripping it off, and the dark mode for Windows 10. I think that'd be a happy medium for readability. I think it'll probably be one of these things that the community provides feedback on once the option is in there to switch to dark mode.

Thanks! :- )

**Comment by vynmera** [comment]
@HammyHavoc Check out #11071 :)

**Comment by Julianoe** [comment]
Love it!

**Comment by sampaiodiego** [comment]
we'll make that possible by custom themes https://github.com/RocketChat/Rocket.Chat/issues/1887

**Comment by dstensnes** [comment]
How is this going? Currently use rocket chat with Dark Reader extension in Firefox, but would prefer something native such that it is easily available for more people.

**Comment by reetp** [comment]
> How is this going? Currently use rocket chat with Dark Reader extension in Firefox, but would prefer something native such that it is easily available for more people.

It's closed, so going nowhere so no point in commenting here.
Please follow the links for where something might be happening.

**Comment by ata-star** [comment]
> How is this going? Currently use rocket chat with Dark Reader extension in Firefox, but would prefer something native such that it is easily available for more people.

Rocket chat sucks, the devs dont know CSS
