### ISSUE TITLE
search field:  find users by their real name (alias) and email

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#6406]
Rocket.Chat Version: 0.52.0

Hi,

it would be helpful to find users by their real name (profile alias) and email address and not only by their username.

Ciao!

**Comment by Nosferous** [comment]
Searching by full name components (first, last or both) USED to work. And broke in version 0.51.0 I see this as an issue/bug and not a feature/improvement. Since version 0.51 you cannot search reliably by first name. You must search last name or username (for my environment linked to AD accounts).

Not sure if email searching worked before- so that aspect may be a feat request/improvement.

See the report localguru referenced:
Creating New DM Issue - Cannot search users by First Name for new Direct Messages since V 0.51.0 - still present up to current version 0.54.2 #6006

^ Current Title- I'm updating as each Server Version releases that this is still an issue. The fix sounded simple enough that they had modified the way the query worked and that they would have someone change it back. Originally Milestoned for version 0.52.0 it's been adjusted version after version now to 0.55.x

**Comment by engelgabriel** [comment]
it is still an issue on version `0.55.0`?

**Comment by Nosferous** [comment]
@engelgabriel Searching by first name now works for me in version 0.55.0 I cannot comment regarding searching by email address since my users rocket chat username matches their email address usernames.

**Comment by localguru** [comment]
is working in 0.58.0 now.
