### ISSUE TITLE
Why do some gifs auto play while others do not and require you to click on them

### ISSUE THREAD

**Issue by freshmonarch** [RocketChat/Rocket.Chat#6451]
Rocket.Chat Version: 2.4.0
Running Instances: 
DB Replicaset OpLog:
Node Version:

**Comment by MartinSchoeler** [comment]
@freshmonarch which platform are you using?

**Comment by freshmonarch** [comment]
I'm just using the desktop app

**Comment by MartinSchoeler** [comment]
Thanks for reporting this issue. We value your time in helping us to make Rocket.Chat great. We always try to fix confirmed problems as quickly as we can, and it appears that the issue you reported might already be fixed in the latest release. Can you please help us test it against current latest release? Much appreciated. And please remember to backup your data before upgrading, just to be safe. Cheers!
