### ISSUE TITLE
Display multiple file formats as embedded media (ePub, ODF, PDF)

### ISSUE THREAD

**Issue by designgurudotorg** [RocketChat/Rocket.Chat#6536]
It seems to me that there's massive interest in this functionality and implementation shouldn't be too difficult - basically, it would be great if any ODF, PDF or ePUB document is uploaded it automatically becomes viewable within the chat area using one of the following Open Source scripts:

https://github.com/futurepress/epub.js/
http://viewerjs.org/

I don't have great JS chops so I can't unfortunately whip up a pull request but perhaps someone reading this could? Or alternatively maybe there's a quick way to automatically rewrite the URLs to document uploads and render them with these scripts just in Administration > Layout > Custom Scripts?

q./

ref: https://github.com/RocketChat/Rocket.Chat/issues/2741 & https://github.com/RocketChat/Rocket.Chat/issues/255

**Comment by arjamizo** [comment]
is there any progress on this task? 
Thanks

**Comment by ml48603** [comment]
I am interested in a pdf viewer for RocketChat.

Is there a reason why this functionality was not included when the image viewer plugin was created?
Are there patches to the client available that add a pdf viewer?

Running RC Client on Ubuntu Linux 16.04.2 LTS Desktop
Running RocketChat 0.56 Server on Ubuntu Linux 16.04.2 LTS Server

**Comment by bayareacoder** [comment]
Pls update on status of enabling an embedded file viewer for PDF files. This is the #1 file interchange format so I believe it should be high on the roadmap to support an internal viewer rather than downloading a file each time. This is even more the case since RocketChat does not seem to support a Markup editor to create posts (as Slack does), meaning that with Rocket.Chat you need to create a file and upload it for long-form post.

**Comment by tobzsc** [comment]
Any news on this? This is also something we are missing. :(

**Comment by ml48603** [comment]
Can this functionality be added as an add on or plug in to exiting RC Clients?  Or would the new functionality need to be programmed into the core of the client?  Are there technical reason that make adding this functionality particularly challenging?  Does a bounty need to be offered to get this project moving for RC Clients supporting Android, Windows, Ubuntu platforms?  Is there a system for multiple people to come together and commit to a bounty as a group? (So people pledging to pay a bounty don't back out when the project is done.)

**Comment by FabianZimbalev** [comment]
+1    Any news here ? This is implemented in all the other solutions like Slack, HipChat ect...
For me it would actually be enough to see the downloaded files in a list or something in the chat and then open it in the appropriate Program when I click it. And an auto-download destination so that you don´t have to select where to download it to every time.

**Comment by rodrigok** [comment]
@ggazzo @tassoevan can you add some update here?

**Comment by reetp** [comment]
For PDFs this Issue should resolve it:
https://github.com/RocketChat/Rocket.Chat/pull/10519
I'm not sure about previews for other file types

**Comment by tassoevan** [comment]
@ggazzo spotted the issue; I'm preparing a correction for it.

**Comment by marceloschmidt** [comment]
This has been implemented for PDF and also deployed. We'll accept Pull Requests for other formats. Thanks.
