### ISSUE TITLE
New users able to post in read only rooms, and new user posts can't be erased.

### ISSUE THREAD

**Issue by tempestb** [RocketChat/Rocket.Chat#6716]
Rocket.Chat Version: 0.53.0
Running Instances: 1
DB Replicaset OpLog: disabled
Node Version: 4.7.3

We are running Rocket Chat over at https://community.storj.io

Recently, for some reason we're not aware of, new users are able to post in read only forums (Such as #announcements) and Admins cannot delete posts of users.

To me, this sounds like an index corruption of some sort, but I'm just guessing.  Either way, we don't know how to fix it.

**Comment by MartinSchoeler** [comment]
@tempestb  Thanks for reporting this issue. We value your time in helping us to make Rocket.Chat great. We always try to fix confirmed problems as quickly as we can, and it appears that the issue you reported might already be fixed in the latest release. Can you please help us test it against current latest release? Much appreciated. And please remember to backup your data before upgrading, just to be safe. Cheers!

**Comment by tempestb** [comment]
Thank you Martin, we'll go ahead and update Rocket.Chat.  I appreciate you letting me know this was addressed.
