### ISSUE TITLE
Add Active Directory Fields on userpage

### ISSUE THREAD

**Issue by alexbrazier** [RocketChat/Rocket.Chat#6757]
Issue copied from RocketChat/Rocket.Chat.Electron#418 by @ST-KW

## Description

As a user I want to see some active directory fields like phone number, mobile number or position at the user page in the app.

![image](https://cloud.githubusercontent.com/assets/25076997/25004788/567c2e90-2056-11e7-97e3-3a603b942555.png)

#### Current Behavior

It's not possible to show additional Information at the user page.

#### Expected Behavior

It's possible to select some (existing) active directory fields in the rocket.chat config and these fields are shown at the user page e.g. phone number, mobile number or position.

**Comment by mikeboltonca** [comment]
+1
This is extremely valuable for a lot of business deployments.
Since we're pulling the user's Active Directory data anyway, it's just a matter of collecting additional AD profile fields, and choosing where to display them.
Displaying that information in the profile page is a great idea. I would also suggest an option to display one or two fields next to the user's name in the main chat window.

Here's a mockup:
![ad field mockup](https://user-images.githubusercontent.com/16619325/27044024-fdd7a97a-4f50-11e7-95d6-bcf2bbb31a97.jpg)

**Comment by ggazzo** [comment]
hey we have more information now, like email, roles, and more: we have customs fields and we can choose if they will appear on userinfo or not, please check the last version. any problem reopen (:
