### ISSUE TITLE
Trigger notification with Jitsi "Click to join" video call

### ISSUE THREAD

**Issue by rasos** [RocketChat/Rocket.Chat#6773]
When starting a video call with Jitsi meet, a button "Join video call" appears.
However, this does not trigger a push notification nor is a new message number or a highlighting of the group in the left bar shown. This way, users are not notified about invitations to video chats.

Our Rocket.Chat Version: 0.52

**Comment by rasos** [comment]
Also please make the button "Click to Join" translatable (i18n).   
And when it has been pressed, fade out the video button at the right side bar (otherwise we have seen users click on it when they want to join).

**Comment by sagarshah8814** [comment]
Any update on this?

**Comment by asshewale** [comment]
@MartinSchoeler @sezinkarli @rodrigok @vkislichenko @sagarshah8814 @rasos : Hi Devs. I also want the same in iOS , I have integrated Jitsi, in Rocket Chat, on chat window of Rocket chat i have one button to initiate a video call to user/users i am chatting with,  So i want that other users should get a notification or something to joine to same conference created by me, as we have to create one conference number to start the conference which number we appends to our server url, and if other people use the same conference number with our url then we are able to chat in same  conference , any one will please help me how can i make Jitsi video call working in Rocket chat ... 

Your any help will be highly appreciated.

**Comment by rodrigok** [comment]
Hi @asshewale, can you explain your integration?

**Comment by asshewale** [comment]
Hi @rodrigok Thanks for your valuable time, i have integrated the Jitsi in Rocket chat using following steps

1. I downloaded Jitsi Clone from [jitsi/jitsi-meet](https://github.com/jitsi/jitsi-meet)
2. Then i followed the steps given under [Jitsi Meet SDK for iOS](https://github.com/jitsi/jitsi-meet/tree/master/ios) 

I have integrated this in Rocket chat clone, so one the chat window of Rocket Chat i have one Button, on tapping of which i navigates user to JitsiViewController, where i have one View to which i have assigned JitsiMeetView Class as per the guide, there i am using our server's URL instead of meet.jit.si, 

And to open a conference in Jitsi we have to give/append one room number to our URL,  Which creates or initiates a conference room , and other person have to use/hit to same URL with same room number appended by first user to enter in the same conference room, 

On tapping of that video button i am generating one  random number and i am appending it to our URL programatically, now what i want suppose me and you we both are chatting and i am tapping on the video button to initiate a video conference, you should get an invitation to joine the same conference, 

I am not able to get the logic actually how should i achive this, 

As Web's Rocket chat app has internal support to Jitsi, Web's Rocket chat has Video button on chat and from Admin login there Rocket chat provides  some settings to give a URL and room number scheme , and after that whoever the people chatting in between if one person initiated a video call other people gets a 'Click To Joine' button in chat itself to joine the conference, 

Do we have anything like web for Mobile Rocket chat and Jitsi please...

**Comment by Saeidk0** [comment]
Hello,
How to join an existing VC with Jitsi? I have an invitation to a call (with a password) I can't join the call with "START A CALL" option.
