### ISSUE TITLE
Query users.list by disallowed fields

### ISSUE THREAD

**Issue by reist** [RocketChat/Rocket.Chat#6837]
Experimenting with the API, I found that it allows using any field in both sort and query, so a limited user could search for someone by email or any other of the fieldsToKeepFromRegularUsers or RocketChat.API.v1.defaultFieldsToExclude.
Allowing the first field list at least (email, phone, etc) seems to me a security issue. They API should return an error or a blank list on such fields in sort or query.

Example query: {'emails.address': 'bill@gates.com'}
Even if the data is filtered out, it doesn't matter if a record is returned.

**Comment by graywolf336** [comment]
We'd welcome a pull request to fix this issue. :+1:

**Comment by MarcosSpessatto** [comment]
Hello @reist, it seems that this issue was resolved in older PRs. Looking at this issue and checking the actual code, we can see that there is a treatment for fields that can or cannot be used as a filter on all endpoints involving `users`. We encourage you to upgrade your version of rocket.chat if you have not done yet.

As you can see here: https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-api/server/helpers/parseJsonQuery.js#L24

Please, let me know if the problem persists.

**Comment by MarcosSpessatto** [comment]
Closing this issue once it was answered in the above comment. Thanks.
