### ISSUE TITLE
Exception in delivering result of invoking 'login': TypeError: e is not a function

### ISSUE THREAD

**Issue by tqkruger** [RocketChat/Rocket.Chat#6839]
Rocket.Chat Version: 55.1
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.5.0 

Login via iframe

The desktop client can't reconnect unless the application is reloaded. 
<img width="768" alt="skaermbillede 2017-04-29 kl 18 01 37" src="https://cloud.githubusercontent.com/assets/21054876/25556900/3e226910-2d06-11e7-8554-3ba231e88272.png">

**Comment by TryingToImprove** [comment]
I solved the issue:

Instead of using the `loginToken`, we went to update the mongodb with a services.iframe.token, which seems to have solve the issue.

I think that the problem is with `token` when you are trying to reconnect, because it needs the previous `token`, and when signing in with https://rocket.chat/docs/developer-guides/rest-api/#logon it returns a new token

**Comment by tqkruger** [comment]
Solved as @TryingToImprove writes
