### ISSUE TITLE
Is it possible to install Rocket.Chat without access to SSH/Shell Console?

### ISSUE THREAD

**Issue by gesundelehre** [RocketChat/Rocket.Chat#6867]
If not, it would be pretty hard to install on a free Web Host somewhere.
Thanks for the reply

**Comment by jszaszvari** [comment]
You need to find a host that supports hosting meteor / node 

It's an application With a web frontend, not a  website. Your not just rendering pages when they are loaded, there Is a entire application/server running in the background. 

Use someone like Heroku or Digital Ocean but free hosting will be limited, as it's costing someone money. Your looking for more of a application host than a web host.  

Even with ssh access to your web hosting provider , they probably would not appreciate someone trying to run a server based app. (If it's merely for web hosting )

You might find something suitable here https://rocket.chat/docs/installation/paas-deployments/

**Comment by k0nsl** [comment]
Good luck trying to run Rocket.Chat on a free web hosting plan. I think it wouldn't even be possible on my BuyShared ‘RESELLER 125G’ due to OOM limitation (if we pretend we got that far). At any rate, a VPS or dedicated server is the preferred choice if you want to deploy Rocket.Chat without having to constantly worry about getting yourself terminated due to abuse. Et cetera.
