### ISSUE TITLE
URGENT .. web client taking more then 1/2 gig of RAM .. need to stop using rocketchat .. 

### ISSUE THREAD

**Issue by vikaskedia** [RocketChat/Rocket.Chat#6932]
Damm ...

![image](https://cloud.githubusercontent.com/assets/6703876/25899425/a7dfc744-3544-11e7-8e80-832f4eb0b0d6.png)

![image](https://cloud.githubusercontent.com/assets/6703876/25899448/c346d55e-3544-11e7-918e-78996b95830d.png)

**Comment by vikaskedia** [comment]
PLEASE stop adding new features .. and work on this with all focus ..

I love rocketchat and I want it to succeed .. 

more than features users need their apps to be snappy ..

I run macbook pro 13 inch without touch bar with 8 GB of memory .. latest chrome stable ..

**Comment by neoangin** [comment]
Just use safari on mac for rocket chat and everything will be ok.

**Comment by vikaskedia** [comment]
In our organization .. Chrome is the only supported browser .. it is deployed to 40 end points using Munki .. and it allows to control various enterprise policies .. like preventing any extension installation .. having preinstalled extensions etc ...

The probability of me being able to move the organization over to Safari from Chrome is less than 1%

**Comment by geekgonecrazy** [comment]
@vikaskedia I definitely see the cause for frustration.  Can you give some details to help us figure out what's causing so much memory usage?  

Do you have a lot of channels?
How long is your window open before it's using 1gig of Ram?
During this time is it sitting here or what kinda actions are you performing?  Are there lots of people talking?
What kind of content is in your channels?  Mainly short conversational messages?  Heavy in images or gifs?  Large bodies of text?

Please give us as much information as you can to help us reproduce.

**Comment by engelgabriel** [comment]
@vikaskedia our focus now have not been in adding new features that would make the UI heavier, we have been converting CoffeeScript to JS, adding more unit tests and 2e2 tests, more API options, fixing WebRTC integrations, etc. Our goal now is to make the app more stable and polished so we can launch our version 1.0

The memory issue maybe caused by some caching layer we have been working on, that should make the load time faster, but we will investigate.
