### ISSUE TITLE
how to show topic of channel Instead name of channel

### ISSUE THREAD

**Issue by saeedjalali1** [RocketChat/Rocket.Chat#6973]
Rocket.Chat Version: 0.56.0-develop
Running Instances: 
DB Replicaset OpLog:Enabled
Node Version: 4.8.1 - x64

Hi,How to change the name of channel in side menu with topic?
![image](https://cloud.githubusercontent.com/assets/15178117/26058043/4d6bff20-3991-11e7-95fe-5b9620b7f7e7.png)

 and how to add topic name name create the channel ?
The reason I raised this issue when you create a channel with other language instead English give error.

**Comment by madguy02** [comment]
@saeedjalali1  i  think you can name your channel and topic being a mention about the channel appears inside once you open the channel....Alsoi don't think it should give an error if your name isn't English.I tried it in the community server demo.rocket.chat

**Comment by saeedjalali1** [comment]
Hi,thanks for answer.
![image](https://cloud.githubusercontent.com/assets/15178117/26092435/2845f558-3a26-11e7-84a2-01daa46ee487.png)

As you can see arabic name for channel is not valid. How to fix it?

**Comment by liuweireign** [comment]
@saeedjalali1  you can config the name verificaiton in administration -> general -> utf8

**Comment by saeedjalali1** [comment]
@liuweireign I trying this solution. but not working :-( give the same error.
in utf8 regex setting add `.` for checking all words. [try this](http://www.regexr.com/)

**Comment by MartinSchoeler** [comment]
Thanks for reporting this issue. We value your time in helping us to make Rocket.Chat great. We always try to fix confirmed problems as quickly as we can, and it appears that the issue you reported might already be fixed in the latest release. Can you please help us test it against current latest release? Much appreciated. And please remember to backup your data before upgrading, just to be safe. Cheers!
