### ISSUE TITLE
Improve alerts of password reset

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#70]
##

**Comment by alayek** [comment]
hi, I am interested in working on this issue. Though I am new, I have already worked on #1725 and have gotten some familiarity with the process.

**Comment by Sing-Li** [comment]
@alayek you're on!     Looking forward to the PR.

**Comment by alayek** [comment]
Before that, I would like to get some clarity on the issue, since this is lacking description in detail.

For the moment, we are resetting password by going to `My Account -> Profile` and then hitting `Save Changes`. This displays a Toast notification saying "Profile Saved Successfully"

Are we planning to replace this Toast, with some password change specific code? Like "Password Reset Successfully"? Or would we want more, such as on reset password logout the user and ask the user to login again? Or do we add an email confirmation, with text like "Someone just reset the password" and a recovery link?

**Comment by MartinSchoeler** [comment]
@engelgabriel which ones you mean? The toasts in the password reset by email and by settings looks pretty decent to me
![workspace 1_013](https://cloud.githubusercontent.com/assets/20868078/20388525/6a9abc52-acac-11e6-8e1d-6a003248eacc.png)
![workspace 1_014](https://cloud.githubusercontent.com/assets/20868078/20388526/6aca4f62-acac-11e6-9fec-adaaf8e27ede.png)
Or maybe something i didn't see?

**Comment by eric-horvat** [comment]
Hi, I'd like to try to work on this issue as part of hacktoberfest but I'm not really sure what the issue is meant to address. The above comments indicate to me that there might not be that much left to do.

**Comment by dhruvdutt** [comment]
I would like to take this up. :hand:
