### ISSUE TITLE
Automated conversion of the CoffeeScript to ES6

### ISSUE THREAD

**Issue by Igloczek** [RocketChat/Rocket.Chat#7035]
I'm not an author or even a user of https://github.com/decaffeinate/decaffeinate but folks from PostCSS / Autoprefixer already used this tool to prepare version 7.0 of their plugin (https://github.com/postcss/autoprefixer/releases/tag/7.0.0), so it might be useful for you too.

**Comment by MartinSchoeler** [comment]
@Igloczek We appreciate the suggestion, and actually we have been using these automated converters. They are pretty useful, but we still have to clean the code afterwards, since they leave lots of code that can be simplified for readability sakes. And its almost over now, only 2.7% coffee files left :smile:
