### ISSUE TITLE
Missing username

### ISSUE THREAD

**Issue by mikt** [RocketChat/Rocket.Chat#7037]
Problem: Whenever a user is registered for a new account, the "username" field is blank. (but the name field is set)

Steps to reproduce:
Set "Manually Approve New Users" to true.
Register your rocket.chat account.
Search the newly registered account in the admin.
The username field of the account is blank.

Is there a way for me to force users to pick a username upon registration?

Rocket.Chat Version: 0.56.0-rc.5
Running Instances: 	1
DB Replicaset OpLog: Disabled
Node Version: v4.8.2

**Comment by madguy02** [comment]
@mikt go to Administration ->under settings there are options like (Accounts,Analytics etc),since your issue is based on accounts(click on that) you will have a list of options (true or false along with it).If you want to force a username,just go and change 'allow username change' to false. If its something else that you want,then comment back

**Comment by mikt** [comment]
@madguy02 I want to prevent the scenario as in this image:
http://i.imgur.com/U4uIlKr.png

In this scenario the users don't have usernames.. How can I force them to select a username when they signup for the account?

**Comment by MartinSchoeler** [comment]
@mikt After you accept a new user, the first time he logins he will be prompted to select his username. So until he logins for the first time, he wont have a username. I think that is made so a unwanted user cant waste a username

**Comment by mikt** [comment]
When a username is blank, it does not allow me to activate the user via the api. (Even when I know the user ID) 
Is it possible to convert this to a feature request?

**Comment by dmanchev** [comment]
We are having a similar issue : When using LDAP, users will log with their LDAP user/password and their actual "Name" will be blank because they don't go through the "Registration" process. 

I've allowed users to change their profiles and names, but some are lazy or just don't bother. 
In most cases that's fine since Rocket.Chat will show their LDAP trigram instead of a name and we can figure out who's who. However, if someone without a "Name" set sends you a private message, the notification window will show "null" instead of their name. 

Is there a way to force Rocket.Chat to automatically fill the "Name" field with the LDAP username, so that this scenario is avoided?

**Comment by bbrauns** [comment]
Have a look at: Administration - Ldap - User Data Field Map

![image](https://cloud.githubusercontent.com/assets/6813310/26400832/35849afe-4083-11e7-80a5-3b3f80ef8483.png)

**Comment by dmanchev** [comment]
The field is grayed out, and if i get it right it can only set "name" and "email" ? There's already a mapping of those two, but it fills the "username" and not the "Name" field

**Comment by rahul-meena** [comment]
i am having this issue too , the newly registered user don't have a username and unable to login .

**Comment by lightweight** [comment]
I'm also finding this tricky - especially with manual account activation and the fact that it requires a username to be specified... It seems to me that this requirement is unnecessary, no?
