### ISSUE TITLE
Error message when importing users fro LDAP

### ISSUE THREAD

**Issue by killstyl** [RocketChat/Rocket.Chat#7087]
Rocket.Chat Version: 0.55.1
Running Instances: 9 
DB Replicaset OpLog: Enabled
Node Version: v4.5.0

When importing users we get error message. 

[34mI20170525-08:57:44.991(0) rocketchat_logger rocketchat_logger.js:377 [31mLDAP ➔ Search.error { [SizeLimitExceededError: Size Limit Exceeded]   dn: [Getter],   code: [Getter],   name: [Getter],   message: [Getter] } 
[34mI20170525-08:57:44.991(0) rocketchat_logger rocketchat_logger.js:377 [31mLDAPSync ➔ error { [SizeLimitExceededError: Size Limit Exceeded]   dn: [Getter],   code: [Getter],   name: [Getter],   message: [Getter] } 
[34mI20170525-08:58:30.701(0) rocketchat_logger rocketchat_logger.js:377 [31mLDAP ➔ Search.error { [SizeLimitExceededError: Size Limit Exceeded]   dn: [Getter],   code: [Getter],   name: [Getter],   message: [Getter] } 
[34mI20170525-08:58:30.703(0) rocketchat_logger rocketchat_logger.js:377 [31mLDAPSync ➔ error { [SizeLimitExceededError: Size Limit Exceeded]   dn: [Getter],   code: [Getter],   name: [Getter],   message: [Getter] } 
[34mI20170525-08:58:30.704(0) Exception while invoking method 'ldap_sync_users' SizeLimitExceededError: Size Limit Exceeded   at Object.Future.wait (/home/rocket/Rocket.Chat/programs/server/node_modules/fibers/future.js:449:15)   at LDAP.searchAllSync (packages/meteor.js:213:24)   at LDAP.searchUsersSync (/home/rocket/Rocket.Chat/programs/server/packages/rocketchat_ldap.js:281:16)   at sync (/home/rocket/Rocket.Chat/programs/server/packages/rocketchat_ldap.js:730:26)   at [object Object].Meteor.methods.ldap_sync_users (/home/rocket/Rocket.Chat/programs/server/packages/rocketchat_ldap.js:1219:16)   at [object Object].methodsMap.(anonymous function) (/home/rocket/Rocket.Chat/programs/server/packages/rocketchat_lib.js:1069:26)   at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)   at maybeAuditArgumentChecks (/home/rocket/Rocket.Chat/programs/server/packages/ddp-server.js:1823:12)   at /home/rocket/Rocket.Chat/programs/server/packages/ddp-server.js:905:20   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /home/rocket/Rocket.Chat/programs/server/packages/ddp-server.js:904:41   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /home/rocket/Rocket.Chat/programs/server/packages/ddp-server.js:903:46   at [object Object]._.extend.protocol_handlers.method (/home/rocket/Rocket.Chat/programs/server/packages/ddp-server.js:876:21)   at /home/rocket/Rocket.Chat/programs/server/packages/ddp-server.js:755:85      - - - - -   at messageCallback (/home/rocket/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/client/client.js:1419:45)   at Parser.onMessage (/home/rocket/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/client/client.js:1089:14)   at emitOne (events.js:77:13)   at Parser.emit (events.js:169:7)   at Parser.write (/home/rocket/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:117:8)   at end (/home/rocket/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:72:19)   at Parser.write (/home/rocket/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:118:10)   at end (/home/rocket/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:72:19)   at Parser.write (/home/rocket/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:118:10)   at end (/home/rocket/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:72:19)   at Parser.write (/home/rocket/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:118:10)   at end (/home/rocket/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:72:19)   at Parser.write (/home/rocket/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:118:10)   at end (/home/rocket/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:72:19)   at Parser.write (/home/rocket/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:118:10)   at Socket.onData (/home/rocket/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/client/client.js:1076:22)   at emitOne (events.js:77:13)   at Socket.emit (events.js:169:7)   at readableAddChunk (_stream_readable.js:153:18)   at Socket.Readable.push (_stream_readable.js:111:10)   at TCP.onread (net.js:536:20)

**Comment by Levesque7** [comment]
We are also getting a similar error when importing. We have about 3500 users.

I believe the issue is caused by the Active Directory search limit. Searches are capped at 1000 results in AD. However, powershell's AD cmdlet library is able to get around that limit somehow, so it is possible. Perhaps with paging for the searches?

@killstyl are you also in AD environment and trying to import >1000 users?

Error below:

[34mI20170603-18:10:50.429(-5) rocketchat_logger rocketchat_logger.js:377 [31mLDAP ➔ Search.error { [SizeLimitExceededError: Size Limit Exceeded]   dn: [Getter],   code: [Getter],   name: [Getter],   message: [Getter] } 
[34mI20170603-18:10:50.431(-5) rocketchat_logger rocketchat_logger.js:377 [31mLDAPSync ➔ error { [SizeLimitExceededError: Size Limit Exceeded]   dn: [Getter],   code: [Getter],   name: [Getter],   message: [Getter] } 
[34mI20170603-18:10:50.434(-5) Exception while invoking method 'ldap_sync_users' SizeLimitExceededError: Size Limit Exceeded   at Object.Future.wait (/snap/rocketchat-server/616/node_modules/fibers/future.js:449:15)   at LDAP.searchAllSync (packages/meteor.js:213:24)   at LDAP.searchUsersSync (/snap/rocketchat-server/616/programs/server/packages/rocketchat_ldap.js:281:16)   at sync (/snap/rocketchat-server/616/programs/server/packages/rocketchat_ldap.js:730:26)   at [object Object].Meteor.methods.ldap_sync_users (/snap/rocketchat-server/616/programs/server/packages/rocketchat_ldap.js:1219:16)   at [object Object].methodsMap.(anonymous function) (/snap/rocketchat-server/616/programs/server/packages/rocketchat_lib.js:1069:26)   at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)   at maybeAuditArgumentChecks (/snap/rocketchat-server/616/programs/server/packages/ddp-server.js:1823:12)   at /snap/rocketchat-server/616/programs/server/packages/ddp-server.js:905:20   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /snap/rocketchat-server/616/programs/server/packages/ddp-server.js:904:41   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /snap/rocketchat-server/616/programs/server/packages/ddp-server.js:903:46   at [object Object]._.extend.protocol_handlers.method (/snap/rocketchat-server/616/programs/server/packages/ddp-server.js:876:21)   at /snap/rocketchat-server/616/programs/server/packages/ddp-server.js:755:85      - - - - -   at messageCallback (/snap/rocketchat-server/616/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/client/client.js:1419:45)   at Parser.onMessage (/snap/rocketchat-server/616/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/client/client.js:1089:14)   at emitOne (events.js:77:13)   at Parser.emit (events.js:169:7)   at Parser.write (/snap/rocketchat-server/616/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:117:8)   at end (/snap/rocketchat-server/616/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:72:19)   at Parser.write (/snap/rocketchat-server/616/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/messages/parser.js:118:10)   at TLSSocket.onData (/snap/rocketchat-server/616/programs/server/npm/node_modules/meteor/rocketchat_ldapjs/node_modules/ldapjs/lib/client/client.js:1076:22)   at emitOne (events.js:77:13)   at TLSSocket.emit (events.js:169:7)   at readableAddChunk (_stream_readable.js:153:18)   at TLSSocket.Readable.push (_stream_readable.js:111:10)   at TLSWrap.onread (net.js:540:20)  
[34mI20170603-18:13:59.589(-5) rocketchat_logger rocketchat_logger.js:377 [31mLDAP ➔ Connection.error connection { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }

**Comment by killstyl** [comment]
Yes, approximately 3000 users.

**Comment by josean7link** [comment]
I have the same problem, but when I am using the ldapsearch I can get all my users. Without problems.

We have more of 1600 Users. So what is the problem.
