### ISSUE TITLE
"Add users" list keeps disappearing

### ISSUE THREAD

**Issue by TomasHofman** [RocketChat/Rocket.Chat#7117]
Rocket.Chat Version: 0.56.0-rc.1
Running Instances: 
DB Replicaset OpLog:
Node Version: 4.8.1

In web client, when adding users to a private channel, when I write user name into "Add users" box, list of users appears, but then it disappears quickly (sometimes less then a second). It doesn't matter if I have mouse pointer on the list or not, or browsing through it via arrow keys.

This really makes adding users difficult.

Happens both in Chrome or Firefox (53.0.2), as well as in the Electron desktop app (2.7.0-1).

**Comment by TomasHofman** [comment]
Opened here instead: https://github.com/RocketChat/Rocket.Chat.Electron/issues/458

**Comment by TomasHofman** [comment]
Opening this instead of https://github.com/RocketChat/Rocket.Chat.Electron/issues/458, as this is probably webapp issue.

**Comment by MartinSchoeler** [comment]
Thanks for reporting this issue. We value your time in helping us to make Rocket.Chat great. We always try to fix confirmed problems as quickly as we can, and it appears that the issue you reported might already be fixed in the latest release. Can you please help us test it against current latest release? Much appreciated. And please remember to backup your data before upgrading, just to be safe. Cheers!

**Comment by TomasHofman** [comment]
I'm not sure how to figure out the version I'm using, but I can confirm that the issue is resolved. Thanks!
