### ISSUE TITLE
Archive (aka freeze) Channels / Groups

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#722]
Need the ability to archive channels / groups
##

**Comment by graywolf336** [comment]
:+1:

**Comment by graywolf336** [comment]
Right now you can archive channels and groups, but you can still post messages there along with doing actions in that room to previous messages. So, we need to prevent actions when the room is archived.

**Comment by matthias-brun** [comment]
Also: Since the changes which changed/introduced the room info tab, the Archiving button is shown to every user even if they have no permissions to use it. (It won't actually do anything unless you have the permissions though)
I'm currently working on fixing that as well as making the Archiving function more like the the other options displayed in that panel. (Edit button, selection like in private group/channel, etc.)
I'll see how far I get and submit a pull request either today or tomorrow.

**Comment by graywolf336** [comment]
This is now completed.
