### ISSUE TITLE
Live Chat: No desktop notification when someone joins live chat queue

### ISSUE THREAD

**Issue by puetzstef** [RocketChat/Rocket.Chat#7292]
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: activated
Node Version: v 4.8.2.

Hi there,

I'm using the live chat feature and activated the live chat queue. It would be great if there was a desktop notification on the agents desktop each time someone has joined the queue. At the moment only a sound is played. If sound is deactivated on a agents desktop, he does not get notified if someone joins the live chat queue. So eventually the agents will miss chat requests.

Greetings,
Stefan

**Comment by G00mbah** [comment]
The strange thing is, you do get a visual notification when the chat has ended. Why not when the chat is requested?

**Comment by monty241** [comment]
Have same issue. Rocket.Chat+ client version 2.8.0.

When I came back in office, the team missed 2 sales calls for this. Luckily the email address remains shown, but it is unprofessional when the expectations of the requestor of a chat are not met in real-time.

The settings on such a livechat room are:

![image](https://user-images.githubusercontent.com/7579444/29452174-ade2ba42-8405-11e7-8e85-d6c540047f00.png)

And on account:

![image](https://user-images.githubusercontent.com/7579444/29452313-28a8cd5c-8406-11e7-8714-996f88568130.png)

![image](https://user-images.githubusercontent.com/7579444/29452320-2dc25cfe-8406-11e7-91eb-7995e536d5ba.png)

Only the chime works (new message), but is easy to miss even at 100% volume.

The desktop notifications are not shown except when I press Test (I will raise separate bug issue).

The sound for room creation is not played when a new livechat room is created (I will raise separate bug issue).

The unread tray icon alert is not shown (I will raise separate bug issue).

As a workaround I've tried to have the webhooks for room creation forward it to Slack.

Although room creation itself is nicely listed as:

`{"token":"xxx","channel_name":"testchannel","timestamp":"2017-08-18T08:59:39.798Z","user_id":"xxx","user_name":"gle3","owner":{"username":"gle3","_id":"xxx"},"room":{"name":"testchannel","t":"c","msgs":0,"u":{"_id":"xxx","username":"gle3"},"customFields":{},"ts":"2017-08-18T08:59:39.798Z","ro":false,"sysMes":true,"_updatedAt":"2017-08-18T08:59:39.800Z","_id":"xxx","usernames":["this_will_be_filled_in_with_usernames_when_replayed"]}}`

There is no webhook fired on RocketChat for an incoming livechat, a message exchange or ending a livechat.

But in Livechat you can configure different webhook receiver specifically for livechat. That one works, but the webhook is only called when everyone is offline and at session end:

`{"_id":"xxx","label":"Guido Leenders","code":29,"createdAt":"2017-08-18T09:02:55.990Z","lastMessageAt":"2017-08-18T09:05:56.280Z","visitor":{"_id":"xxx","name":"Guido Leenders","username":"guest-2","email":"xxx","phone":null,"department":"xxx","ip":"xxx","os":"iOS 10.3.2","browser":"Mobile Safari 10.0"},"agent":{"_id":"xxx","username":"gle3","name":"Guido Leenders","email":"xxx"},"type":"LivechatSession","messages":[{"username":"guest-2","msg":"test","ts":"2017-08-18T09:02:55.994Z"},{"username":"gle3","msg":"testback","ts":"2017-08-18T09:03:54.665Z","agentId":"xxx"}]}`

There is no event triggered on session start (raised enhancement issue).

So there is no workaround. IMHO it is not an improvement, but a bug since the LiveChat functionality was integrated into RocketChat more but many user options have not been reflected to incorporate this internal change. At the original merge time it would have been an enhancement, but now it is a bug.

**Comment by ingmartinfarias** [comment]
is very important this
