### ISSUE TITLE
User Roles not Persistent if they leave a Public Channel

### ISSUE THREAD

**Issue by waveyuk** [RocketChat/Rocket.Chat#7330]
If I set a user to be a moderator of the room in the back-end administration, if they leave that room, and re-join, whilst their tag says they are and administrator, they are unable to see the "Mute" and "Remove Users" buttons on people's profiles. To restore this functionality, I have to add them again in the Permissions settings.

Rocket.Chat Version:  0.56.0
Running Instances:  1
DB Replicaset OpLog: Enabled
Node Version:4.8.1

**Comment by waveyuk** [comment]
@MartinSchoeler ideally, I don't think if a user is made a moderator that they should lose those rights if they leave a channel.  The rights should only be revoked if done so by an admin or whoever has access rights to do this.  Of course, with the issue of not being able to see in the admin UI who has moderator rights to a room (see issue #5898 for clarification), then it is harder to remove those rights from the back-end.

**Comment by subham103** [comment]
Actually this is happening because we are removing the subscriptions for the particular user in the room when the user leaves the room(``removeByRoomIdAndUserId``). As @waveyuk  said, we shouldn't change the user permissions if the user leaves the room, and as the UI doesn't reflect these changes upon removal of a user, it's going to be an easy update to fix this. Will try to solve this issue:)

**Comment by ggazzo** [comment]
I will close this issue since it's very old and we never heard more complaints about it, and to be honest, I cant see we doing this change...so I'm sorry but, if you are sure its an important feature, please open it again and we can discuss more about
