### ISSUE TITLE
Add option to not use :tm: icon for ™ character

### ISSUE THREAD

**Issue by drasbeck** [RocketChat/Rocket.Chat#7386]
Rocket.Chat Version: 0.56.0

The icon Rocket.Chat exchanges the ™ character for is a little obnoxious, and it would be great with the option to not use it.

What I see:
![what_i_see](https://user-images.githubusercontent.com/8578706/27773976-2fd2934a-5f87-11e7-8c87-e0dc3c0695ff.png)

What I would like to see:
![what_i_would_like_to_see](https://user-images.githubusercontent.com/8578706/27773977-3254c58e-5f87-11e7-9a51-a29ea923a322.png)

**Comment by drasbeck** [comment]
I have not experienced this with any other characters. It simply exchanges `™` for `:tm:` as far as I can see.

**Comment by geekgonecrazy** [comment]
Ah it's the TM emoji!  Makes sense now!  I thought this was happening with the TM Unicode character

**Comment by 2xB** [comment]
I think there is confusion because this is actually a bug: If you enter the trademark symbol ™, `U+2122` - not the emoji variant ™️ `U+2122-FE0F` (!) -, it is exchanged with the emoji version. This does not happen for e.g. copyright (©, `U+00A9`) or any other character I tested that is listed in https://github.com/RocketChat/Rocket.Chat/blob/157b882d38b34b7b79dea527316554fe33f70891/app/emoji-emojione/lib/rocketchat.js , and it also quite frankly doesn't make any sense.
