### ISSUE TITLE
Error starting SSL Caddy with snap Rocket.Chat

### ISSUE THREAD

**Issue by mzambretti** [RocketChat/Rocket.Chat#7419]
Hello. I'm trying to configure and start the snap version of Rocket.Chat with Caddy but there is something that is not working!

**snap --version** 
snap    2.25+16.10
snapd   2.25+16.10
series  16
ubuntu  16.10
kernel  4.8.0-58-generic

**Caddyfile**
****.*******.**
proxy / localhost:3000 {
  websocket
  transparent
}

**Error**
root@sardinha:~# sudo systemctl status snap.rocketchat-server.rocketchat-caddy
● snap.rocketchat-server.rocketchat-caddy.service - Service for snap application rocketchat-server.rocketchat-caddy
   Loaded: loaded (/etc/systemd/system/snap.rocketchat-server.rocketchat-caddy.service; enabled; vendor preset: enabled)
   Active: failed (Result: start-limit-hit) since qua 2017-07-05 11:44:25 BRT; 20s ago
  Process: 3128 ExecStart=/usr/bin/snap run rocketchat-server.rocketchat-caddy (code=exited, status=1/FAILURE)
 Main PID: 3128 (code=exited, status=1/FAILURE)

jul 05 11:44:25 sardinha systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Main process exited, code=exited, status=1/FAILURE
jul 05 11:44:25 sardinha systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Unit entered failed state.
jul 05 11:44:25 sardinha systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Failed with result 'exit-code'.
jul 05 11:44:25 sardinha systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Service hold-off time over, scheduling restart.
jul 05 11:44:25 sardinha systemd[1]: Stopped Service for snap application rocketchat-server.rocketchat-caddy.
jul 05 11:44:25 sardinha systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Start request repeated too quickly.
jul 05 11:44:25 sardinha systemd[1]: Failed to start Service for snap application rocketchat-server.rocketchat-caddy.
jul 05 11:44:25 sardinha systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Unit entered failed state.
jul 05 11:44:25 sardinha systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Failed with result 'start-limit-hit'.

**Comment by geekgonecrazy** [comment]
@mzambretti can you run: `sudo journalctl -u snap.rocketchat-server.rocketchat-caddy` and see what logs you can find there?

**Comment by mzambretti** [comment]
Hi @geekgonecrazy !

jul 06 00:22:41 sardinha /usr/bin/snap[7021]: cmd.go:114: DEBUG: not restarting into "/snap/core/current/usr/bin/snap" ([VERSION=2.24 2.24]): older than "/usr/bin/snap" (2.25+16.10)
jul 06 00:22:43 sardinha snap[7021]: Activating privacy features...2017/07/06 00:22:43 [chat.oxipira.br] failed to get certificate: acme: Error 429 - urn:acme:error:rateLimited - Error creating
jul 06 00:22:43 sardinha systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Main process exited, code=exited, status=1/FAILURE
jul 06 00:22:43 sardinha systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Unit entered failed state.
jul 06 00:22:43 sardinha systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Failed with result 'exit-code'.
jul 06 00:22:43 sardinha systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Service hold-off time over, scheduling restart.
jul 06 00:22:43 sardinha systemd[1]: Stopped Service for snap application rocketchat-server.rocketchat-caddy.
jul 06 00:22:43 sardinha systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Start request repeated too quickly.
jul 06 00:22:43 sardinha systemd[1]: Failed to start Service for snap application rocketchat-server.rocketchat-caddy.
jul 06 00:22:43 sardinha systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Unit entered failed state.
jul 06 00:22:43 sardinha systemd[1]: snap.rocketchat-server.rocketchat-caddy.service: Failed with result 'start-limit-hit'.

**Comment by geekgonecrazy** [comment]
@mzambretti it looks like you've hit the rate limit from letsencrypt: 
> failed to get certificate: acme: Error 429 - urn:acme:error:rateLimited - Error creating

**Comment by mzambretti** [comment]
hum.. so, do you know can I fix it?

**Comment by geekgonecrazy** [comment]
The timeout is something around an hour.  So I would edit your caddy file and add http://yoursite

That'll stop it from trying to get an ssl cert.

Then.. while you wait on the rate limit to expire.. Make sure your site is publicly accessible at the domain your specified.  Because during the letsencrypt process it serves a file up at http://yoursite to verify you are in control of that domain.  So if it can't reach it.. it won't give an ssl cert.

**Comment by watou** [comment]
I just had these symptoms, only to discover that I had forgotten that certbot needed me to leave open ports 80 and 443 on the firewall for the certificate renewal process.  I had closed off ports 80 and 443 after setting everything up, which was fine until it came time to renew the certificate.  I tried to switch to DNS challenge instead but the certbot in caddy was too old to support my DNS provider. So I opened up ports 80 and 443 again and caddy started up correctly.

**Comment by geekgonecrazy** [comment]
@watou do you have a reference for it being too old?  would love to take a look :+1:

**Comment by watou** [comment]
@geekgonecrazy That caddy is too old is an assumption on my part, based on seeing this in the log: 

```
2017/07/07 10:36:37 /var/snap/rocketchat-server/812/Caddyfile:8 - Parse error: Unsupported DNS provider 'dyn'
```

**Comment by geekgonecrazy** [comment]
ah.. yeah a dynamic dns provider.  I'm guessing letsencrypt its self doesn't support authenticating with dyn.

**Comment by watou** [comment]
The [caddy docs](https://caddyserver.com/docs/automatic-https#dns-challenge) say they support a DNS challenge, and link to their [github repo](https://github.com/caddyserver/dnsproviders) listing all the DNS providers supported, including [dyn](https://github.com/caddyserver/dnsproviders/tree/master/dyn).  I don't know how that repo is part of caddy or why I got the error message above.

**Comment by geekgonecrazy** [comment]
Looks like dyn has been there a good while before our release.  I'm not sure what's going on.  

We are using the latest release that was available as of 9 days ago when 0.57.1 was released.  That appears to be: caddy 0.10.4

Might be worth asking on their forums.

**Comment by watou** [comment]
@geekgonecrazy Thanks for looking at the issue.  I will do more investigation and report back.

**Comment by geekgonecrazy** [comment]
Please feel free to re-open or report back if you find anything.  :+1:

**Comment by watou** [comment]
It appears that support for the DNS challenge requires that caddy is built to explicitly include the DNS challenge provider you want to use (see [this from the author](https://caddy.community/t/which-dns-providers-should-caddy-support-by-default/58/28) and [the wiki on writing your own DNS challenge](https://github.com/mholt/caddy/wiki/Writing-a-Plugin:-DNS-Provider).) None are included by default.  So the external plugin nature of DNS challenge in caddy is at odds with using a pre-built binary that doesn't anticipate which DNS challenge the user ultimately wants to use.  The consensus [here](https://caddy.community/t/which-dns-providers-should-caddy-support-by-default/58) was not to include them all by default due to the bloat and external dependencies it would entail.  I have not yet asked anyone how to add the capability to the build process to include the DNS challenge(s) to caddy at build time.  

It would be very nice if my Rocket.Chat server didn't have to leave ports 80 and 443 open.  On the down side, using the DNS challenge requires you to put API keys or username/passwords in environment variables in plaintext, depending on your DNS provider.

Please re-open this issue if the above information can in any reasonable way be addressed in how Rocket.Chat ends up with the caddy binary the user uses, and thank you!

**Comment by geekgonecrazy** [comment]
@watou created an issue to add that as its off topic to this issue.  Thanks for digging and coming back with the info.  Will make it much easier

**Comment by mirzazeyrek** [comment]
`rm -rf /root/snap/rocketchat-server/current/.caddy` and then restarting again helped to get rid of this pesky `Start request repeated too quickly` message.

Please let me know if that works for you.

**Comment by geekgonecrazy** [comment]
New version of caddy is out and in the newest release of the snap 0.65.1. hopefully the workaround will no longer be needed
