### ISSUE TITLE
On Logon UI when LDAP fails we should return the LDAP failure code

### ISSUE THREAD

**Issue by Megatronic79** [RocketChat/Rocket.Chat#742]
http://wiki.servicenow.com/index.php?title=LDAP_Error_Codes#gsc.tab=0

or better still translate the code into the Descriptive:

example
Code 49 / 52e 	= AD_INVALID CREDENTIALS

**Comment by marceloschmidt** [comment]
We could use the help of someone with LDAP knowledge.

**Comment by emcguinness** [comment]
This seems related enough to not open up a new issue (I hope). Currently when failing a login using ldap I am getting the error box appear in the top right but it is completely blank. From what I can tell it is trying to toast an object rather than the actual message.
```
null  != e ? void ("no-valid-email" === e.error ? r.state.set("email-verification") : toastr.error(e.reason)) : FlowRouter.go("index")
```
Hard to give an exact line number as I am using Chrome dev tools pretty print to make any sense of it but in that it is 53667. If I break the javascript around here e.reason is actually an object:

```
Object {error: 49, reason: "Invalid Credentials", message: "Invalid Credentials [49]", errorType: "Meteor.Error"}
```

Toasting e.reason.message would likely give better feedback though I am not familiar enough with meteor to rebuild and test this myself.

**Comment by blaskovicz** [comment]
i can try to take a look at this

**Comment by rodrigok** [comment]
Now login fallbacks to default account system if LDAP logins was not successful.
