### ISSUE TITLE
WordPress integration

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#747]
1- wordpress user integration
if not
2- signup/login within wordpress/ webpage as an API? 
3- Send alerts to (specified) channels once a new post is published.

**Comment by marceloschmidt** [comment]
Someone with WordPress knowledge can take this?

**Comment by nonsintetic** [comment]
I know quite a bit about Wordpress, but not a lot about meteor. I can try and pitch in on the WP part once a general approach has been laid out by someone who knows both.

**Comment by engelgabriel** [comment]
@nonsintetic I think we need your help here indeed. 

1. We need to find a good WordPress oAuth or SAML plugin. Do you know any?
2. Do you know how to write WP plugins? We can give you the Rest URLs to send the alerts to.

**Comment by nonsintetic** [comment]
I've used this once before in a very basic way: https://wordpress.org/plugins/miniorange-saml-20-single-sign-on/
It's a rather new plugin, not a massive history of development, but does what it says on the tin. Haven't had a look at the code in it.

I can write plugins, the plugin part is just 2 lines of code. The Wordpress REST API (http://v2.wp-api.org/) is still a bit of a beta affair (they plan to merge it into the core at some point), alternatively i can write a custom endpoint for you to send data to, handle it within Wordpres etc.
Just gimme a sample of the data you want to send (in JSON) and I can write the Wordpress stuff.

**Comment by engelgabriel** [comment]
That's great. We are working on the integration points. I'll get your a doc with the API to test. If you can help, it would be awesome!!!!

**Comment by nonsintetic** [comment]
Good, I'll make something as soon as I get it. 

Regarding *SAML plugins*, the only one available that doesn't use an external SaS service is https://wordpress.org/plugins/saml-20-single-sign-on/, it's basically an implementation of simplesamlphp (https://simplesamlphp.org/). It makes Wordpress a SAML SP, it works, but it's kind of hacked-together if you ask me. 

The way I see it is: what would be useful is to have a plugin that makes Wordpress a SAML *IdP* instead and use that in Rocket Chat. That way you can just keep using the Wordpress login functions, login screen and database for storage like before, just add a plugin for RC. There isn't one available at this moment, but one could be written using simplesamlphp without too much hassle.

Otherwise, migrating to a different accounts system to use a chat system would be overkill for most people, especially since most of them already have users signed up to their WP site.

**Comment by engelgabriel** [comment]
@nonsintetic I think we are saying the same thing. I don't want people to have to migrate to a different accounts system. We want to keep WP and the Identity Provider, either via SAML or oAuth, and Racket.Chat will just use our generic packages to login using those credential.. as you can with Facebook, LinkdeIn, GitHub, etc on our https://demo.rocket.chat server.

So how should we start?

**Comment by engelgabriel** [comment]
Shall we use this?

https://wordpress.org/plugins/oauth2-provider/

**Comment by nonsintetic** [comment]
I have that plugin installed on my test server and it works fine, all it really needs is a rocket.chat plugin very similar to the Gitlab one (a generic oAuth plugin). I'm not sure how Gitlab works, but I imagine it's just the links that differ.

**Comment by engelgabriel** [comment]
Hi @rodrigok can you help?

**Comment by rodrigok** [comment]
@nonsintetic and @engelgabriel now we have buttons on section **accounts** to add a custom oAuth section, so you can configure the login with wordpress their I think.

**Comment by engelgabriel** [comment]
@rodrigok :+1:

**Comment by nonsintetic** [comment]
Ok I've had a very long chat with @marceloschmidt and we've managed to log into RC with Wordpress. Unfortunately there was an issue with RC expecting 'id' in the response instead of 'ID' which is what came from Wordpress in the /oauth/me info, details on how it was fixed below in the tutorial.
(According to @marceloschmidt the part that handles that on RC's end is in the Meteor codebase - https://github.com/meteor/meteor/blob/devel/packages/accounts-base/accounts_server.js#L1328) 

Here's how it was done: 
**Rocket Chat Side**
1. Administration > Accounts : (bottom-right next to Save settings) click 'Add custom oAuth'
2. name it 'wordpress' (case sensitive). Can be anything you want, just keep in mind it will have to be typed exactly the same in the redirect uri on the Wordpress plugin side of things (details lower)
3. fill out these settings for the new oAuth you created
```
Authorize Path: /oauth/authorize
Button Text: anything you want
Enable: true
ID: this is the 'Client ID' you get when you get to step 4 on the Wordpress side of the instructions
Identity Path: /oauth/me
Secret: this is the key you get when you complete step 4 below on the Wordpress side, just hover over the newly created client's name and you'll see a 'Show Secret' link, copypaste that hash here
Token Path: /oauth/token
URL: http://yourwordpresssiteurl.com
```

**Wordpress Side**:
1. oAuth Provider plugin: https://wordpress.org/plugins/oauth2-provider/ (free version, tested with v.3.1.7)
2. EITHER: add 1 line of code to get it working with RC:
 in wp-content/plugins/oauth2-provider/includes/filters.php , around line 123, after `unset($me_data['user_url']);` add this `$me_data['id'] = $me_data['ID'];` 
   OR: add this GIST to your template's functions.php file (https://gist.github.com/nonsintetic/af01e406732b923754b2)
3. in the plugin's settings > Advanced Configuration - tick all Grant Types
4. in the plugin's settings > Clients - select "Add new client", client name: anything, redirect uri: `http://<your rocketchat server link>/_oauth/wordpress` (very important: if you chose a different name for your custom oAuth in Rocket Chat, use that exact name here after '/_oauth/' - case sensitive), description: anything

After all these steps have been completed, if the client ID and the secret match between RC and WP, if the fix is applied. You just go to your rocketchat and click the newly appeared button to log in, if you're not logged into wordpress you'll get the wordpress login screen in a popup. 

Possible errors encountered (by me):
 - 502 errors on login - check if the fix is applied (you'll get an error in the rocketchat console `Exception while invoking method 'login' Error: Service data for service wordpress must include id` if it's not applied). Check if the paths in RC's custom oAuth method are set correctly. If is still doesn't work check the meteor console, it will probably give you insight on what exactly is wrong. 
- 'key doesn't match' or similar error in the popup - problem with client id or secret (don't match)
- redirect uri errors - check if the redirect uri set in the plugin has the same (case sensitive) name as your oAuth method in RC (you'll have to remember because it's forced uppercase in the UI currently).
- you got it all wrong, deleted the custom oAuth method and started again, but the old redirect uri or key are still being used: you'll have to delete them by hand from mongodb (there's a bug with deleting custom oAuth methods currently) - in mongodb go to 'meteor/collections/meteor_accounts_loginServiceConfiguration' and delete what's there. You can use Robomongo ( a gui editor for mongodb databases )

**Comment by marceloschmidt** [comment]
Thank you very much, @nonsintetic! I'll add this to the wiki, so it doesn't get lost.

**Comment by syedalamabbas** [comment]
This should be updated. Now this is a built in feature with Rocket Chat. 
So for Rocket Chat side: You don't have to do 'Add custom oAuth' and fill in whole bunch of details as the above comments state, instead look for Wordpress tab and fill in fewer details and a wordpress login button appears.

**Comment by engelgabriel** [comment]
@marceloschmidt, should we update the WIKI?

**Comment by wargamesqcf** [comment]
Does this still work or do I need to edit the  template's functions.php ?

**Comment by rankun203** [comment]
Now I need to add these code

```php
$me_data['id'] = $me_data['ID'];
$me_data['name'] = $me_data['username'];
```

into `wp-content/plugins/oauth2-provider/includes/filters.php`.

**Comment by wargamesqcf** [comment]
WP OAuth Server updated to 3.2 and I can't get it to work with rocketchat.

**Comment by wargamesqcf** [comment]
I am getting this from my logs.

[34mW20161219-18:15:38.588(0) (oauth.js:101) [35mUnable to base64 decode state from OAuth query: undefined
[34mW20161219-18:15:38.589(0) (oauth.js:101) [35mUnable to base64 decode state from OAuth query: undefined
[34mW20161219-18:15:38.591(0) (oauth.js:428) [35mError in OAuth Server: Failed to complete OAuth handshake with wordpress at http://five-rings-online.net:3000/_oauth/wordpress/oauth/token. socket hang up

**Comment by Sing-Li** [comment]
Anyone upgraded 3.2 and has it working?  @IQ2022 @nonsintetic @rankun203 @syedalamabbas

**Comment by flantascience** [comment]
I'm also interested in this

**Comment by IQ2022** [comment]
if we have money we should higher a professional Wordpress programmer to build a plugin for RC that does complete membership integration .. and user database sycn between both ends.. given 3/4 world sites are running wordpress so, i think its worth it..

**Comment by wargamesqcf** [comment]
would it better if RC was able to look at the WP DB for users?

**Comment by IQ2022** [comment]
would be nice if they can actually create a membership plugin that handles Wordpress :) like member+ or https://codecanyon.net/item/ultimate-membership-pro-wordpress-plugin/12159253 plugin :D

**Comment by johnlund** [comment]
The built-in RC Wordpress oAuth doesn't seem to work with WP oAuth Server at all.

I've had some luck with custom oAuth, but I'm having the same issue as @wargamesqcf. I've included the fix above and am not getting the missing `id` error anymore, but am still seeing this:

```[34mW20170221-20:26:24.094(0) (oauth.js:101) [35mUnable to base64 decode state from OAuth query: undefined
[34mW20170221-20:26:24.098(0) (oauth.js:101) [35mUnable to base64 decode state from OAuth query: undefined
[34mW20170221-20:26:24.100(0) (oauth.js:428) [35mError in OAuth Server: invalid_request```

I'm using WP oAuth 3.2.001 non-pro, and it works with no problem in an iframe within my Wordpress site. It doesn't work standalone unless I try logging in once, get the error, then reload the page, or if I am already logged in to WP and attempt to login to RC in the same browser. But it does not work for any of the RC apps (desktop and mobile).

**Comment by wargamesqcf** [comment]
I have no idea what iframe is but can you walk me through how you did it?

**Comment by johnlund** [comment]
@wargamesqcf Basically, if the user is already logged into WP, I can get the RC oAuth to work, but if they are not logged in, RC login does not work.

RC Custom oAuth:
* Enabled: True
* URL: homepage of WP site
* Token path: /oauth/token
* Identity path: /oauth/me
* Authorize path: /oauth/authorize
* Scope: openid
* Token sent via: Header
* ID: from WP oAuth Server
* Secret: from WP oAuth Server
* Username field: I have this blank, but I'd love to be able to import display names from WP (any ideas how to do this?)
* Merge users: false (not sure exactly how this works, and I don't want to mess up my user data)

WP oAuth Server:
* General
    * API Enabled - Checked
* Advanced
    * Everything checked
* Clients
    * Setup a new client using the callback URL from the top of the RC custom oAuth settings
    * Get the ID and secret for the fields in RC custom oAuth settings

**Comment by wargamesqcf** [comment]
I just get /oauth/error/404 when I try this thanks for trying atleast.

**Comment by flantascience** [comment]
I've had a few people comment on this.  Here's what worked for me...

 Enable   True
URL   https://peerunschooling.net/members/
Token Path   /oauth/token
Identity Path   /oauth/me
Authorize Path   /oauth/authorize
Scope    openid
Token Sent Via     Header 
Id
Secret
Login Style    Redirect


WPOAuth 3.2.87

Grant Types 
Authorization Code:	YES
Client Credentials:	YES
User Credentials:	 YES
Refresh Tokens:	 YES
Allow Implicit:	  YES


Misc Settings
Token Length	    30
Require Exact Redirect URI:	     NO
Enforce State Parameter:	     YES



OpenID Connect 1.0a
Enable OpenID Connect:	     NO
ID Token Lifetime	 3600


Token Lifetimes   
Access Token Lifetime	 86400
Refresh Token Lifetime	864000



Redirect URI:   https://members.peerunschooling.net/_oauth/punetauth

**Comment by flantascience** [comment]
Check my post I just dropped on this article:
https://github.com/RocketChat/Rocket.Chat/issues/747

That's how I did the settings.
Then, I created an iframe in my WordPress page using this code:

<iframe src="https://members.peerunschooling.net" style="position:
absolute; top: 60;left: 0;   width: 100%;    height: calc(100% -
60px);"></iframe>

This positions a full-screen iframe just below my header containing the
RocketChat app.

Jim Flannery

jim-flannery.com
p. 860-578-4966
e. jim@jim-flannery.com
s. jim_flannery

**Comment by johnlund** [comment]
Thanks Jim.

**Comment by gjsman** [comment]
So, overall, is it possible to use the non-pro version to do this, or not?

I've tried with the settings, and a WordPress sign-in page loads, et citera, but it suddenly ends with a "Internal Server Error." The error in logs is:


[34mI20171014-20:51:02.644(0) Exception while invoking method 'login' SyntaxError: Unexpected token <   at Object.parse (native)   at CustomOAuth.getAccessToken (/snap/rocketchat-server/1142/programs/server/packages/rocketchat_custom-oauth.js:166:17)   at Object.handleOauthRequest (/snap/rocketchat-server/1142/programs/server/packages/rocketchat_custom-oauth.js:224:28)   at OAuth._requestHandlers.(anonymous function) (packages/oauth2.js:27:31)   at middleware (packages/oauth.js:203:5)   at packages/oauth.js:176:5
