### ISSUE TITLE
LDAP authentication not working!?

### ISSUE THREAD

**Issue by wgfreitas** [RocketChat/Rocket.Chat#7484]
Rocket.Chat Version: 0.57.1
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: v4.8.1

Hi, everyone!

I've installed and set up LDAP authentication, but Firefox returns "User not found or incorrect password".

➔ info Init LDAP login test 
➔ Connection.info Init setup 
➔ Connection.info Connecting ldap://server1.abc.br,server2.abc.br:389 
➔ Connection.info LDAP connected 
➔ Bind.info Binding admin user Administrator@abc.br 
➔ Search.info Searching user test 
➔ Search.info Search result count 1 
➔ Auth.info Authenticating CN=Test,CN=Users,DC=abc,DC=br 
➔ Auth.info Authenticated CN=Test,CN=Users,DC=abc,DC=br 
➔ Connection.info Disconecting 
➔ info Querying user 
➔ info Logging user 
➔ info Syncing user data 
➔ info Syncing user avatar

What's wrong with that configuration? Thanks!

**Comment by PhilMarsden** [comment]
I'm seeing exactly the same problem with connecting to an Active Directory server over LDAP

**Comment by Gummikavalier** [comment]
LDAP to AD works for us with 0.57.0 at least.

If you use 'login failback disabled' option, you may have to promote some other user to admin and delete the original administrator account, as well as any other (manually) created local accounts that already have the same name in AD.

If none of your LDAP accounts work, you could check if you can sync the accounts in admin console and check under 'Users' that they get populated into Rocket.Chat. If that does not happen, you have some kind of problem with LDAP bind or connectivity to start with.

For instance we use OU instead of CN in LDAP path for the bind account like in CN=bindaccount,**OU**=subpath,DC=domain,DC=com.

**Comment by wgfreitas** [comment]
Thank you, @Gummikavalier!
I'm not understanding what is wrong with this setup because I've set up an AD user as administrator and Rocket.Chat/admin/users was synchronized (all AD users were imported).

**Comment by Gummikavalier** [comment]
@wgfreitas If you create a completely new user into AD, can that account log in?

For the reference, here are all our LDAP settings (that are other than the defaults).

```
Enable:	True
Login Fallback:	False
Host:	abc.domain.com
Port:	636
Encryption:	SSL/LDAPS
Domain Base:	OU=users,DC=domain,DC=com
Domain Search User:	CN=bindaccount,OU=subpath,DC=domain,DC=com
Domain Search Password:	********

Domain Search Filter:	&(memberof=CN=groupname,OU=groups,DC=domain,DC=com)!(userAccountControl:1.2.840.113556.1.4.803:=2)
 * This includes all users in one group and excludes all disabled accounts. This was tricky to get working as there is a bug with the use of parenthesis, and correct syntax did not work. This is not mandatory, though.

Username Field:	sAMAccountName
 * This is default, but I just mentioned it as it matches with the value below.)

Unique Identifier Field:	sAMAccountName
Sync Data:	True
Sync User Avatar:	False
User Data Field Map:	{"displayName":"name", "mail":"email"}
Import LDAP users:	True
```

**Comment by wgfreitas** [comment]
Thank you, @Gummikavalier!

Yes, I think it was related with #7472.
The only setting that I've changed was,

Sync User Avatar:	False

Login is being processed properly.
