### ISSUE TITLE
Limit @ user list to members of private room

### ISSUE THREAD

**Issue by danieljhochman** [RocketChat/Rocket.Chat#7489]
If I have a private room and try to @ someone, the users which appear in the list should be limited to the members of that private room.

**Comment by danieljhochman** [comment]
@Sing-Li - this is not a show stopper for us (for pahse 1)  but seems like an important bug to fix

**Comment by geekgonecrazy** [comment]
Related/Duplicate #2588

**Comment by localguru** [comment]
+1

**Comment by pettitto** [comment]
I actually quite like the fact you can @ other people in a private room. If you're talking about someone specifically, it's good to be able to show someone who you're talking about so the other person you're talking to can click on that linked persons profile, for example and grab their e-mail address/details.

**Comment by danieljhochman** [comment]
@ing other people is fine. Showing members in the auto-complete who are not in the private room, is not correct. Look how Slack does it.

**Comment by geekgonecrazy** [comment]
Here it seems like privacy by default would be best.  Maybe allow it to be overrode to show all via permission

**Comment by danieljhochman** [comment]
@geekgonecrazy - what's the use-case for showing non-members in a private room? Why even make it a setting?

**Comment by geekgonecrazy** [comment]
The main use case would be so that people that like to refer to people outside the room still can.  But by default it wouldn't be possible.

Also wouldn't be a setting.  Lets say for instance the permission is on admin.  Admin could see and mention anyone. 

If you decided to set your server up so your staff can see others on the server but guests you invite in (lets say clients) are not.  You would simply assign the guest a role with out the permission to view / mention users not in group.

Not saying this is how it will be implemented. Just saying this is what would be most flexible.  The developer that takes this will ultimately be the one to decide.

A permission could always be added later if people missed being able to mention.

**Comment by jszaszvari** [comment]
Why not just seperate the list into 

----
Users of this channel
----
x
x
x
x

----
Users not in this channel
---
x
x
x
x


And have the priority autocomplete be the people in the room.

**Comment by geekgonecrazy** [comment]
@jszaszvari because of privacy primarily.  :)  The few i've talked to that want this want to invite their clients to a private group and them not be able to use autocomplete and accidentally see other clients.
