### ISSUE TITLE
Custom CSS cause server freeze

### ISSUE THREAD

**Issue by mhou1981** [RocketChat/Rocket.Chat#7491]
Edited: I have narrowed it down to this CSS causing entire server to freeze.

Rocket.Chat Version: 0.57.1
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: v4.8.1

I am trying to add customer HTML to the page to display a header navigation bar which required some specialized CSS for Internet Explorer and Microsoft Edge.  I have added the following content into the Admin -> Layout -> Custom CSS
```
.account-box  .options  .animated-hidden {
  transform: translateY(-200%) translateY(-50px);
}
```

Everything works well on the local instances with applied CSS.  However, once the same setting migrated to my production environment (about 70 online user), server stopped to freeze and loading has become very slow for everyone.  Page started to be display as broken and people can no longer logged in.  Once this customization for IE/Edge only CSS been removed, all page return to normal.

We also have HuBot setup in our Rocket Chat instances.  At this stage, we are not sure why this simple CSS could have cause entire server failure.

Server spec:
4 Core
8GB RAM
Ubuntu 16.04 LTS 64 bits
All Rocket Chat and Mongo DB are using SNAP.

**Comment by MartinSchoeler** [comment]
Hey, looks like you seem to be looking for support. You will have a better chance of getting help if you go to one of the places listed in [here](https://rocket.chat/docs/getting-support/#community-support) since github is not the best place to ask for support. For now i will be closing this issue, as it does not fit our issue guidelines
