### ISSUE TITLE
Blue screen shows after running RocketChat over SSL 

### ISSUE THREAD

**Issue by NawrasAli** [RocketChat/Rocket.Chat#7544]
### Description:

I installed RocketChat successfully. It works fine through 3000 port (mydomain :3000/). However, it shows blue screen when I try to run it over httpS (https ://my domain)

I use nginx as the main web server and as a reverse proxy.

### Server Setup Information:

* Version of Rocket.Chat Server:  0.57.2
* Operating System: Debian Jessie server
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* Node Version: v4.7.1

### Relevant logs:
Console: 
https:// domain. com/ xxxxxxxxxxxxxxxxxxxxxxxxx .css?meteor_css_resource=true NOT FOUND
Same error shown in nginx logs: No such file or directory

Please help me! I'm trying to solve this issue since days and I have no clue :(

**Comment by geekgonecrazy** [comment]
It sounds like your reverse proxy handling the ssl isn't properly proxying requests to rocket.chat.

Have you seen our documentation for setting up nginx reverse proxy? https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy#running-behind-a-nginx-ssl-reverse-proxy

Please give that a shot.  Going to go ahead and close since not a bug or feature request.  Feel free to follow up here or one one of our other [support methods](https://rocket.chat/docs/getting-support)
