### ISSUE TITLE
Visibility of scrollbar on left side of Navigation Drawer

### ISSUE THREAD

**Issue by sacOO7** [RocketChat/Rocket.Chat#7587]
![screenshot from 2017-07-27 18 55 43](https://user-images.githubusercontent.com/16723785/28672779-5213e23a-72fe-11e7-836f-a6b42dda0243.png)

I have lot's of favorite channels on the left side. Initially I thought no scrollbar was available to scroll through all of them. But, on proper observation it was available with very small width and color matching background. Is there any setting to change it's color other than background or can you set default styling to make it **visible on first glance**? Please give your suggestions :+1:

**Comment by marco-aa** [comment]
@sacOO7 maybe i'm wrong but you could use chrome develtop toolbar and use the inspector to get the element / id-name and set a color - if this works you can use custom-css in the admininterface for custom-css. This could be a work around. If you only a User you could find some browser plugin wich is overwrting the css as a work around, too ;)

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @sacOO7 

we believe that the issue you reported has already been reported by somebody else. Please have a look at #8049 for further information. If you believe we closed your issue in error and your issue is, in fact, not the same as the one mentioned before, feel free to reopen this issue and tell us why.

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
@rocket-cat label add duplicate
