### ISSUE TITLE
Bot users without email and password

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat#7785]
Using different bots and users requires an account for each bot-user. This has to have an email and password (you could possibly set any random value) but as bots should not be used to log in, why do they need those values?

**Comment by pkgodara** [comment]
related to #7125

**Comment by timkinnane** [comment]
@soundstorm Bots actually do use a password to login, via Asteroid. There's currently no support for webhook or API based bots due to limitations in setting up message streams for them to read through those protocols. The email issue I think is valid though, but is more related to #7125, so I'm closing this one.
