### ISSUE TITLE
[Refactor] Localization files needs heavy refactor

### ISSUE THREAD

**Issue by mnlbox** [RocketChat/Rocket.Chat#7813]
Hi guys,
Localization files needs heavy refactor because many of files not in the same state with `en.i18n.json` for example here is the `af.i18n.json` content:
```
{
  "#channel": "#channel"
}
```
On the other side some localization break in some languages for example:
English:
```
  "Cannot_open_conversation_with_yourself": "Cannot open a conversation with yourself",
```
Arabic:
```
  "Cannot_open_conversation_with_yourself": "لا يُمكن البدء بمحادثة مع نفسك",
```
`Cannot_open_conversation_with_yourself` key is exist in English and Arabic files but not exist in `bg.i18n.json`.
I guess we needs some refactor and use same key for all files.
On the other hand this is some related issue about localization:
#7746 
#7649 
...

I found also many related PR about localizations for example:
#7814 
#7815 
...

### Server Setup Information:
* Version of Rocket.Chat Server: 0.59.0-develop
* Operating System: linux
* Deployment Method(snap/docker/tar/etc): -
* Number of Running Instances: 
* DB Replicaset Oplog: Enabled
* Node Version: 4.8.4 - x64

**Comment by MartinSchoeler** [comment]
@mnlbox we use [lingohub](https://translate.lingohub.com/sign_in) to manage our translations. If you are interested on contributing and helping translate rocket.chat, more details can be found [here](https://rocket.chat/docs/contributing/translating/#translating). We would appreciate the contribution. Thanks!

**Comment by mnlbox** [comment]
@MartinSchoeler I think we need some contributing rules to keep language file sync then translator better can translate files. Now we need search in English file and add key/value manually.

**Comment by mnlbox** [comment]
@karlprieb , @sampaiodiego , @gdelavald, @ggazzo any idea about some rule or protocol to keep language message files sync?

**Comment by MartinSchoeler** [comment]
This might not be as simple as it looks, since most of our translations comes from community contributors. So we can not ensure that we have people creating translations for all languages. It is something that one person or group can't do it alone since it needs knowledge from various different languages. For now i will be closing this since it is not possible to patronize our current translation methods. You can help us by finding people that knows these incomplete languages and want to contribute. Thanks for the feedback!
