### ISSUE TITLE
Message action dropdown isn't showing in firefox

### ISSUE THREAD

**Issue by lucasvanhalst** [RocketChat/Rocket.Chat#7962]
In firefox, open demo.rocket.chat and try to click the 'more' button on a message. The dropdown sometimes doesn't show up and the rest of the chat window becomes white. It doesn't happen when the last message in the current channel isn't visible.

![https://i.imgur.com/WNDH50H.gif](https://i.imgur.com/WNDH50H.gif)

**Comment by johnvoloski** [comment]
The problem happens on `.rc-popover__wrapper`. The width and height is fixed defined on 300vh/vw. But on firefox the behaviour is expand parent object. I fixed that, setting w: 100vmin and h: vmax, and the result is size equal of a body. But the problem is positioning about top/left of `.rc-popover__wrapper`, I`m trying to solve that`s now.

**Comment by karlprieb** [comment]
Blocked by #8023

**Comment by karlprieb** [comment]
Closed by #8101
