### ISSUE TITLE
[Feature] Add a link or button for back to "/home" page

### ISSUE THREAD

**Issue by cyclops24** [RocketChat/Rocket.Chat#7997]
By default user redirect to `/home` when done a success login after that user can't back `/home` from anywhere. I think it's not well UX experience and need a link or button somewhere for go back to `/home`.

**Comment by Gummikavalier** [comment]
Agreed, clicking logo should do this by default but it does not.

Until that you can achieve this by setting it manually in the settings:
Administration -> Layout -> Content -> Side Navigation Footer
`<a href="/home"><img src="assets/logo" /></a>`

**Comment by aditya19496** [comment]
I will do it.

**Comment by cyclops24** [comment]
@aditya19496 are you done it?
If you don't have time I can do it myself. 😉

**Comment by aditya19496** [comment]
yeah i have done it. On my way for a pull request.
Sorry for the delay.

**Comment by gdelavald** [comment]
Hey guys, thanks for the suggestion.

Like @Gummikavalier said, this can be customized in the Administration settings since the user could expect a different url to be open, like in the demo where we use the github url.

I will close this issue, if you guys have any strong opinions on this please let me know.

**Comment by cyclops24** [comment]
@gdelavald I think it's better to add same link as default. It's a general best practice in UX.

**Comment by mnlbox** [comment]
@gdelavald I also agree with @cyclops24
