### ISSUE TITLE
Channel Suggestions Only Suggesting Joined Channels

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat#803]
While I was working on the `/join` command I noticed that the channel suggestions you get when you type `#` are only channels which you have joined. This is rather limiting when you're using the `/join` command and want a list of the channels which you can join that match what you're typing.

**Comment by gmsecrieru** [comment]
We are currently using ChatSubscription collection to populate autocomplete's suggestions, that's why you are only seeing the channels that you already joined. 

At this very moment we don't have a client collection which keeps sync of all existing channels, and AFAICT that's something we do need to keep using the autocomplete component - ref. messagePopupConfig`s [popupChannelConfig](https://github.com/RocketChat/Rocket.Chat/blob/master/client/views/app/messagePopupConfig.coffee) for reference).

Do you folks foresee any issues with subscribing to all channels? Is there a better approach to tackle this? May I pick your brains @RocketChat/owners ? :)

**Comment by sampaiodiego** [comment]
So. Synced data (via meteor subscription) has a server perfomance cost affected by how many users are online.

I think we could to a subscription only for this kind of autocomplete and not keep all data synced all the time. Like how mizzao:autocomplete does.

The server cost to keep all clients data synced could be too high for a casually used feature.

**Comment by Morgul** [comment]
Just throwing some $0.2 in here. Most installs will have a small (less than, say, 100) channels. The round trip time for sending 100 strings (probably averaging less than 20 characters) should be small enough that, in theory, making an _explicit_ call to get the list of all channels shouldn't prohibitively impact the usability of the autocomplete.

**Comment by rodrigok** [comment]
We can change the channel auto complete to search on the server just like users auto complete.

**Comment by gmsecrieru** [comment]
I've followed @rodrigok 's  suggestion and it was pretty easy, even though I am still not sure if we may hit performance issues. 

What do you folks think about this? Should I move forward with a PR?

**Comment by rodrigok** [comment]
When I did the change of user's autocomplete to use the server side search we had this discussion and we decided to test.

I don't know how many rooms we can have in a installation, we have more than 10k users in the demo today.

The best solution for this 2 cases is to be dynamic, use server side when the number of records is greater than a certain number (like 200, can be configurable) and use client side when less than this amount. This was my idea, but we need to do the last part, the cache on the client side when the number of records is few.
