### ISSUE TITLE
simple Task Support (cronjobs)

### ISSUE THREAD

**Issue by TheBelgarion** [RocketChat/Rocket.Chat#8067]
It would be nice to have a simple scheduling option to support re-occurring tasks e.g. motd or simply calling an integration every hour or once a day !?

I was thinking of a workaround, like calling another script via a simple cronjob on the server and output the command for the Integration. Problem with that is that I currently ignore rockcat because I used to create endless loops on some use cases ( the command work beeing in the output=

### Description:

Option to call a Script Integration similar to cronjob format 

### Server Setup Information:

current version 0.54.2

**Comment by jszaszvari** [comment]
If you are using hubot you could accomplish this by using this module in your scripts:  https://github.com/kelektiv/node-cron

**Comment by timkinnane** [comment]
@TheBelgarion if you're still interested in this, please comment on #10174 to give a suggestion, or discuss in the forum under [Feature Requests](https://forums.rocket.chat/c/feature-requests).

This issue is not with a current feature or within the current roadmap, so we'll close it for now. Thanks.
