### ISSUE TITLE
[API] Merge all files APIs to only one for dm/channels/groups/im

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#8118]
### Description:

Today we have 4 APIs to show the list of files: `channels.files`, `groups.files`, `dm.files` and `im.files`. Can we merge everything and call `files` just passing the `rid`?

**Comment by graywolf336** [comment]
I am going to say no, as this is planned for the future v2 of the rest api and we haven't decided on that since the schema of things internally has always been changing.

V2 of the rest api is going to be moving away from the `noun.action/items` to a more restful url state of `items/:itemId/action`.

@RocketChat/core we need to decide on a timeline for v2 as our product matures along with versioning the real time api methods at the same time.

**Comment by rafaelks** [comment]
I'm closing this issue since we don't have plans to change the structure of the API right now, only next version.
