### ISSUE TITLE
simpleSAMLphp anyone got it working?

### ISSUE THREAD

**Issue by rickwarren** [RocketChat/Rocket.Chat#8208]
Has anyone gotten authentication working with simpleSAMLphp?    

I can't seem to get it to return the rc token back to /validate endpoint after authentication via the identity provider.   It returns back to rocketchat without the token its looking for in the URI and spits out:

Sorry, an annoying error occured

TypeError: Cannot read property '0' of undefined
Close Window

PS.  this is not a feature request. this is a bug. please do not mislabel it.

**Comment by localguru** [comment]
Not with simpleSAMLphp, but directly with Sibboleth.

**Comment by riwarren** [comment]
That's what I hear. Is it possible to run shibboleth identity provider that authenticates against a simplesamlphp identity provider?

**Comment by localguru** [comment]
@riwarren I thought it's the other way around. I know that our Moodle installation uses simplesamlphp, because Sibbileth doesn't work in the direct way. I did some changes to our RC SAML interface, but effects only the way users are created. If I remember right, SAML is working out of the box with Shibboleth. I had some problems with https://www.testshib.org/ but with our local Sibboleth it's working.

**Comment by arminfelder** [comment]
can you give us a saml trace, and also could you test it with my fork: https://github.com/arminfelder/Rocket.Chat/tree/0.59.0-rc-samlExceptions , for which I have created a pull request yesterday?

**Comment by geekgonecrazy** [comment]
Since this isn't specifically related to Rocket.Chat i'd recommend making use of our forums to discuss this: https://forums.rocket.chat

Going to go ahead and close
