### ISSUE TITLE
Replace Cordova with Native mobile apps

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#8232]
Add ALERT for "TRY NOW the Native apps" on the Cordova apps

**Comment by jszaszvari** [comment]
@engelgabriel  see my comments here https://github.com/RocketChat/Rocket.Chat/pull/7909#issuecomment-325150842

Be careful about pushing people to use the native apps till they offer the full functionality that is expected out of a mobile client.

**Comment by neurobe** [comment]
for those forking RC, but not intending to have Native Apps, will this feature be default = false?

**Comment by engelgabriel** [comment]
Thanks @jszaszvari , we are very mindful of this. We won't remove the old one, but for 99% of users, even without the full functionality, the performance of the Native apps is more important than the missing features.

**Comment by engelgabriel** [comment]
Yes @neurobe, the alert will be optional, and configurable by the admin.

**Comment by rebeld** [comment]
@engelgabriel I would be interested in seeing your sources for that statistic, the vast majority of my users vastly prefer the cordoba version because of missing features in the native app. Performance is not their primary metric.

**Comment by rafaelks** [comment]
@rebeld Interesting! Could you point us what features are you talking about?

**Comment by rebeld** [comment]
Primarily reactions and custom emoji, but also editing account settings (iOS, iPhone, v 1.4.0)

**Comment by rafaelks** [comment]
@rebeld Great! We really wanna add this features to our native apps, they're all being used a lot (specially the reactions, hehe). 👍

**Comment by rebeld** [comment]
Actually, pretty much anything missing from the post action menu (pin, quote, reply, edit). And we make extensive use of the pin and search tabs too.

**Comment by rebeld** [comment]
Context: We use RC primarily for social connectivity and event organization, channels are created for topics and events. The pin tab is used to track resources, custom emoji help establish the community character and tone, and reactions are used for community cohesion and well, post reactions.

**Comment by rafaelks** [comment]
@rebeld We know that this is confusing right now, we're working really hard to develop all the required features into the native apps. We also know that the native apps doesn't have all the features that Cordova (basically, web) have. That's because of obvious reasons: Cordova is basically our web inside of a WebView.

We want to give our users the best experience ever when using our apps, and we think that going with native development (with the features implemented) that would be the best instead of just wrapping everything in a web view.

Right now, we **won't** remove the Cordova app from the store and you **will** choose if you want to tell your users about the native app or not. At the same time you think native app doesn't fit for you because of some features, other users are loving the native apps because of the performance and all the native look-and-feel that the apps have.

Please, have patience and help us giving feedbacks and testing our apps in a while, that would help us a lot and I'm sure everyone will be grateful.

Thank you! 🚀

**Comment by kkumaresan** [comment]
Hi, we at Mongrov have developed a react-native mobile client library for Rocket.Chat. Please check this url: https://github.com/mongrov/roverz . Works both on iOS and Android. If you get a chance, do check this project for a comprehensive native mobile app using Rocket.Chat. We welcome your feedback 🙂

**Comment by rafaelks** [comment]
Discussion was moved to our forums: https://forums.rocket.chat/t/deprecate-our-cordova-mobile-applications/452/5.
