### ISSUE TITLE
RestAPI:  post method got Error with cors

### ISSUE THREAD

**Issue by huynhquocmy** [RocketChat/Rocket.Chat#8404]
When try with rest api: /api/v1/login POST method, I got this issue:
```
TypeError: Cannot read property 'authRequired' of undefined at Route.share.Route.Route._authAccepted 

(D:\huynh\Rocket.Chat\.meteor\local\build\programs\server\packages\nimble_restivus.js:403:17) at Route.share.Route.Route._callEndpoint 
```
Please help.

**Comment by huynhquocmy** [comment]
Here for 
more details: httpss://github.com/RocketChat/Rocket.Chat/issues/7735#issuecomment-334416237

**Comment by sampaiodiego** [comment]
this might be a CORS issue..

@huynhquocmy you can change CORS values on Rocket.Chat from Administration panel > General:
![image](https://user-images.githubusercontent.com/8591547/42774827-2b08a460-8909-11e8-8e85-b7b8e62e57df.png)

**Comment by crowmw** [comment]
I have the same issue. 
CORS values on Rocket.Chat changed to `enabled` and `https://localhost:8080`  (https because im using this address). Have same issue when CORS Origin changed to `*`

I always getting http 500 internal server error on `/api/v1/login POST method`

My request code from js app
```
axios
    .post(
      'https://rocketchat.scc24.pl/api/v1/login',
      {
        username: 'valid_username',
        password: 'valid_password'
      },
      {
        headers: {
          'Content-Type': 'application/json;charset=UTF-8',
          'Access-Control-Allow-Origin': 'https://localhost:8080'
        }
      }
    )
```
RocketChat version: 0.64.1

![image](https://user-images.githubusercontent.com/2963127/43944658-fd69eed0-9c7f-11e8-88ad-5ce49621174b.png)
