### ISSUE TITLE
Why is 0.57.4 latest release now?

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#8421]
Hi,

why is `0.57.4` latest release now. Wouldn't be `0.58.4` expected?

https://github.com/RocketChat/Rocket.Chat/releases

And the master branch is still on `0.58.3`.

Ciao!

**Comment by oliver-bowman** [comment]
+1

**Comment by rodrigok** [comment]
Hi @localguru 

We released the version [0.58.4](https://github.com/RocketChat/Rocket.Chat/releases/tag/0.58.4) and the version [0.57.4](https://github.com/RocketChat/Rocket.Chat/releases/tag/0.57.4).

By a wrong release order, the latest released was set to version `0.57.4` instead of `0.58.4`, it was fixed some hours ago.

The master branch was pointing to version `0.58.3` waiting the merge of the [Sync PR](https://github.com/RocketChat/Rocket.Chat/pull/8420) from the `0.58.4`

**Comment by jszaszvari** [comment]
@rodrigok 

I'm confused, Why a update for 57.x which is from july, when the previous current release was 58.2

ie, why are 2 seperate versions being update?
