### ISSUE TITLE
[NEW] Let user link other social accounts into the same account

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#8496]
### Description:

We need to have a way to link all the social accounts available in the server into user's account. This feature was requested from the KDE guys (@ruphy and @tomaluca95). Their need is basically to let the users that are using RC already login using their own oAuth system. 

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.0-rc.13
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): Hosting
* Number of Running Instances: 20
* DB Replicaset Oplog: Enabled
* Node Version: v4.8.4

### Steps to Reproduce:

1. Have a server with Twitter, Google+, GitHub and some custom oAuth enabled.
2. Create a user with email;
3. Try to login the user with Twitter;
4. It will try to create a new account, instead of linking to the same user;

### Expected behavior:

- It should be a way to link my Twitter account into my user of RC;
- It could be a link into the "My Profile" page on the web (and the apps);

### Actual behavior:

- You can't link any network account into your account;

**Comment by rafaelks** [comment]
@ruphy @sampaiodiego just mentioned to me that if your login accounts has the same email, they'll link. But we'll still need a way to link accounts without the emails being the same, or even without email.

**Comment by mrinaldhar** [comment]
From what I understand, if the emails being used are different, i.e. different email to sign up for rocket chat and a different one that twitter has, using this twitter account in OAuth would require us to verify the email that is being used by the user's twitter account. So basically, we get the email from twitter OAuth, send a verification email to that address, and once verified, link that email to the user. 

If I'm not wrong, this goes against the idea of OAuth a little bit, since the point of it was to allow users to login to third party services using their social account instead of their email, and now we're requiring them to check their email for a verification link. They'd rather just sign up with their email, right?

**Comment by ruphy** [comment]
Hi, yes and no. This allows users who had already signed up with a legacy method to switch to OAuth-based providers, for example. Or to add a password in case they are getting rid of the ID provider account, for any reason...

**Comment by soundstorm** [comment]
Just changed my mail address to that used with the oauth account, linked them and changed it back. Works but is not comfortable ;-)

**Comment by Hudell** [comment]
I'll close this in favor of #3187.
