### ISSUE TITLE
[Bug] missing "More channels..." link in left navigation bar

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#8571]
### Description:

The `More channels...` link in left navigation bar is missing

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.1 open.rocket.chat

### Steps to Reproduce:

1. login and see `CHANNELS` section in left navigation bar

 Tested with 

   * Google Chrome Version 62.0.3202.62 (Offizieller Build) (64-Bit) on  on Ubuntu/Linux
   * Firefox 56.0 (64-Bit) on Ubuntu/Linux
   * Firefox 52.4.1 ESR (32-Bit) on Win7

### Expected behavior:

`More channels...` link is presented

![0584](https://user-images.githubusercontent.com/8544984/31820308-06b09a8c-b5a1-11e7-9fc9-249347fe557a.jpg)

### Actual behavior:

`More channels...` link is missing

![0591](https://user-images.githubusercontent.com/8544984/31820319-181d2ca4-b5a1-11e7-9d72-2a62ede6e4c1.jpg)

### Relevant logs:

none

**Comment by JSG01** [comment]
same here

**Comment by MartinSchoeler** [comment]
@localguru This was removed on purpose, this will be replaced with a new feature in the new future. For now you can use the search to find channels. Thanks!

**Comment by TwizzyDizzy** [comment]
@MartinSchoeler thought about whether I should reply to this or not, but I can't help it:

A decision to remove UI elements that the users is used to (and actually needs to find channels) in favour of a feature that isn't there yet is just plain wrong and can hardly be excused.

You have to consider multiple aspects how the user is using a feature you provide. In the context at hand 

* it can be like you say, that the user wants to search a specific channel that he thinks might exist
* **but** it might also be the case, that users used this function to just look what channels are there... to get an overview of "what's going on on this server".

In the latter case, your aim as a user is to get an overview over ALL channels, not just one that one is looking for.

With this decision, you have robbed the user of this ability without providing an alternative. From a perspective of "how happy are you with using an interface", this is an outright bummer. That's why the decision of yours to go about it the way you did is just plain wrong. Sorry to say that.

Cheers
Thomas

**Comment by localguru** [comment]
@MartinSchoeler please reopen this ticket for discussion.

**Comment by AmShaegar13** [comment]
@TwizzyDizzy I would agree with you if you couldn't just search for # which would yield the same as the old 'more channels'.

**Comment by TwizzyDizzy** [comment]
Well... you can't ... or at least: I can't. Just tried it: searching for "#" doesn't yield my test-channel called "#foobar". Anything I'm missing? :)

Cheers
Thomas

**Comment by AmShaegar13** [comment]
Well, I'm on mobile. Looks like the search results contain only a limited number of channels 😕

**Comment by Bradymck** [comment]
Agreed, this really needs to be added back until this new feature is actually ready.

**Comment by MartinSchoeler** [comment]
The more channels option was removed as part of our UI redesign. Channels can still be found via the channel search. In a coming release we will be adding a discovery menu, that will make finding channels better than ever.

We have been working really hard on the new UI. We know it will take some time to get used to the changes. But we feel this is going to offer a much more polished experience for users. 

I agree with @TwizzyDizzy that we should warn users before doing a change like that, and for that we are sorry, but our UI Team has been working around the clock to make this huge redesign happen, so mistakes like that are bound to happen.

We will make sure to notify users on breaking changes like that in the future 

We appreciate all your patience, support and feedback.

**Comment by geekgonecrazy** [comment]
A good way to see changes before they are released is to hang out on our community server.  We always run the latest release candidate there. This time the release candidate was actually around for a good while before we released it.

As @MartinSchoeler said we have a coming that will be much better then the more channels.

We're investing a lot of time making the UI something we can actually be proud of.  Unlike most open source projects that have a subpar UI and great internals.  We want to look great all the way through.

**Comment by TwizzyDizzy** [comment]
Hey @geekgonecrazy:

> A good way to see changes before they are released is to hang out on our community server.

While this is partly true, I would still argue that proper release notes would be the way to go here. A push model is most often the better choice than a pull (user needs to actively look for it) model. I realize, that this leads to a bit more effort on your side, yet I think it is worth it because it enables users to track (larger) changes before they hit them :)

Looking forward though, what you have in stock for this topic of channel search!

@MartinSchoeler:

> We have been working really hard on the new UI. We know it will take some time to get used to the changes. But we feel this is going to offer a much more polished experience for users.

And I appreciate that. I think that this new UI is an important step forward for RC! :) One would have wished, though, that it would have been introduced in a more consistent way. Take that as a feedback only, as I think this topic is going to resolve itself over time :)

Cheers
Thomas

**Comment by a321465** [comment]
The search only returns 6 results for channel names which is hardly convenient if you are trying to just get a list of channels.

**Comment by wargamesqcf** [comment]
Yeah I dislike this new channel search function I liked the list of all the channels.

**Comment by geekgonecrazy** [comment]
> I just simply don't understand the thought process being removing a feature with the intent of improving it down the road. Why not leave it in place until the improvement is ready to go?

I don't know details exactly.  But basically the markup and styles all got worked over to pull this redesign off.  Because of this it would have required extra Dev time to make this old functionality work only to then have to remove it for the new channel discovery feature.

> Yeah I dislike this new channel search function I liked the list of all the channels.

Search doesn't replace it.  A new feature called discover will replace it.  Hopefully landing next release.

**Comment by geekgonecrazy** [comment]
> While this is partly true, I would still argue that proper release notes would be the way to go here. A push model is most often the better choice than a pull (user needs to actively look for it) model.

Yes I would agree.  Personally thinking some of these maybe we should do a blog post about with screenshots. I'll bring this idea back up to the team. :)

**Comment by apastuhow** [comment]
@TwizzyDizzy '#' in search returns only 5 channels, not all

**Comment by georgeowell** [comment]
Heya, sorry to be negative but this was also a major issue for us in our enterprise deployment. The search doesn't list all the channels so basically users are required to search for channels that they have no way of knowing exist. 

It's actually hobbled the whole platform for any new users we have. I don't understand how this could have got into the stable branch. I look forward to the new solution folks are working on but the project really should try not to break existing functionality with new features.

Thanks and respect to all the devs who work on this project but I just had to let folks know that this was really frustrating for our users.

**Comment by checksum0** [comment]
This is more than beyond a major issue and makes people doubt the ability of the Rocket.Chat team. They removed a UI feature for a upcoming feature that is not yet ready, the only feature that was a proper channel list. 

They are also promising a new UI/UX "that will take a while to get used to"...

Dev gotta dev I guess?

**Comment by volas** [comment]
Any news? It's been 2 months...

**Comment by mld18** [comment]
We also receive negative feedback with respect to this decision from our Rocket users. Hence, I also have to ask: do you plan to release a 0.59.x-Version with a revert of the "more channels..." removal? I would be fine if I would have to do some manual CSS work to make the link visible. 

On a more general note: have you considered to have a stable and an experimental branch of development? People around here keep asking if we shouldn't pick a different, more stable tool. Some would even refrain from some of the cool features just to don't run into unexpected surprises on a regular base. I just want to pass on this perception of Rocket.chat to you.

**Comment by TwizzyDizzy** [comment]
@mld18 

> Some would even refrain from some of the cool features just to don't run into unexpected surprises on a regular base. I just want to pass on this perception of Rocket.chat to you.

This has been brought up before and I think lessons have been learned. For now, I think we have to wait and see, if those learnings will be applied ;)

> Hence, I also have to ask: do you plan to release a 0.59.x-Version with a revert of the "more channels..." removal?

I don't think that this will be the case, because the new "Channel Search" feature in the upcoming 0.60.0 release will supersede the "More channels" feature.

On this topic:
> On a more general note: have you considered to have a stable and an experimental branch of development?

I already opened a similar issue here: #8352 - You may just chime in over there, if you have something to add.

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
Hi @geekgonecrazy

after having deployed 0.60.1 I have to return to this topic. As of yet, the full functionality of "More channels" has yet to be restored. As a user, there is currently NO way to get a list **ALL** channels on an RC instance.

I have just tested this:
* login as admin, look for some random room in the admin interface (in my case called "aem-empire")
* klick into the new search bar as a users
* scroll from top to bottom
* "aem empire" is not listed there

So it is still the case, that one cannot get a full overview of all channels. This is badly needed.

Cheers
Thomas

**Comment by geekgonecrazy** [comment]
@twizzydizzy search I believe is still the only way to see all channels.

Ill see if I can locate the appropriate issue where the channel discovery will be added.

**Comment by volas** [comment]
@geekgonecrazy search is useless if you don't know what to look for. It's shows only 5 channels per request.
This is a big problem for communities with many channels, they look unfriendly to new users.

<details><summary>open.rocket.chat now:</summary>

![screen](https://user-images.githubusercontent.com/4064061/34422361-050ec1b6-ec26-11e7-821b-97d43080f865.png)

</details>

I love RocketChat, but this situation is very disappointing 😕

**Comment by engelgabriel** [comment]
We are starting to work on something similar to this:

![image](https://user-images.githubusercontent.com/1000217/34542387-80f9d6d4-f0c3-11e7-805b-b9da4923a763.png)

**Comment by theorenck** [comment]
@arthurgiustina we need a new definition that sintetize both slack's "browse more channels" and our former Discover design. More specifically it should be implemented as a table, with the avatar, name, channel topic, number of members and at least the date of the last message. But feel free to add you whatever you judge necessary.

**Comment by arthurgiustina** [comment]
![discover](https://user-images.githubusercontent.com/30700871/34808321-51cb3b52-f675-11e7-8147-339156d84719.png)

![default](https://user-images.githubusercontent.com/30700871/34808322-51eb714c-f675-11e7-93d8-cf307a501a2e.png)

@theorenck @engelgabriel 
Abstract Link: https://share.goabstract.com/eafced50-9ca1-475c-88f5-7aed98f4c0a2

**Comment by mrsimpson** [comment]
One remark: there is (yet) another search field on top. Unless there is a real full text Search connected (see #8381) it is hard for users to understand which properties are covered by the string entered. 

Also this raises the question how a glibly fulltext-search should be visualized. Were about to implement an option occupying the tabbar’s space, so we’d be thankful for your feedback, @arthurgiustina

**Comment by engelgabriel** [comment]
This needs to me a "Full Text Search", with Title, Topic, Tags (coming soon) and have infinite scroll or paged.

**Comment by fcoppolani** [comment]
Hi Guys, just to give some feedback here. We are stuck today to the 0.56 version but we want to move to the last version. We were waiting for this issue to be implemented but now I realize that we need to upgrade at least to 0.59 quickly (because of security issue 8408). Do you have any ideas whether this issue can be indeed delivered in 0.61.1 ? Thanks for your work.

**Comment by geekgonecrazy** [comment]
I believe since this is actually not just a fix but actual development of a feature, it'll likely land in 0.62.0

The guys are definitely working on it now to try and get it in 😄

**Comment by mineZcash** [comment]
Before updating my server to 0.60.3 a new user could find a list of channels on the left sidebar with the "more" text.

Now that this is gone, new users don't know the channels available or how to search for them.

My chat has 25+ public channels, If you start typing in the search bar it only shows 5 in alphabetical order! A new user not familiar with Rocket chat thinks there are only 5 channels.

Since alot of channels on my server start with #Zcash a new user never sees them and leaves thinking that the server is inactive.

This is why the use of all the other channels by new users has dropped by 90% since updating to this new format!

Please allow Admin the option to auto-list all available public channels on the left bar for new users, or bring back the "more channels" button

**Comment by geekgonecrazy** [comment]
Please see #9642

**Comment by rodrigok** [comment]
Closed by #9642

**Comment by vectorselector** [comment]
> @TwizzyDizzy I would agree with you if you couldn't just search for # which would yield the same as the old 'more channels'.

I would agree with you if there was a default list of all channels on the left-nav-bar. As-is there is basically little reason for a nav bar. 
Where's the list of all channels? Search? that's a different entity. General menu/list of channels and/or rooms.

Scenario: I just mongodump'ed and then mongorestored. After restore, a search will find the old channels, but absolutely NONE of them are in the left-hand-nav list. 
Is it possible to add items to this bar, like bookmarks/channels/cake-recipes?
