### ISSUE TITLE
Update method

### ISSUE THREAD

**Issue by efih** [RocketChat/Rocket.Chat#8628]
Hi guys

i serached a lot but still dont figure out how the update process work on linux systems
our rocket chat was installed on Ubuntu server with the version 0.58.4 , and in 21/10/2017 our rocket chat updated automatically to version 0.59.1

now, i have few questions
1. there any auto-update process ? - how can i cancel/enable it ?
2. how can i update my server safely ? - and how down update if we have any issue ?

Thanks

**Comment by francaflavio** [comment]
Good Question. Me too

**Comment by ArchimedesFM** [comment]
Hi guys
It depends on the installation method - did you installed it via snap?
Snaps "biggest" feature is that it auto updates every software on a daily basis.
It is very easy to install rocket.chat or other tools via snap, but you cant disable the auto updater - it is the key feature of snap. To prevent auto updates we blocked the url http://api.snapcraft.io

**Comment by francaflavio** [comment]
I installed manually in Debian.

**Comment by jszaszvari** [comment]
* Take a copy of your file uploads directory and avatars directory if they are stored on disk
* Backup your MongoDB Instance using the mongodump command 
* Backup the old install folder and remove it. 
* Install the latest version and point it at your DB 
* Move the file uploads and avatar folders back 
* Start Rocket.Chat

Everything you need, other than uploads and avatars is stored in MongoDB

**Comment by efih** [comment]
To the developer.
Please add an option to enable/disable the auto update  in the management UI.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

First to everybody. If you still want to pursue this general topic of auto-updating, please check out #1581.

Hi @efih 

I am closing this issue because we think there is no actual bug in Rocket.Chat. We understand, that setting up and operating a Rocket.Chat server is not trivial, yet we do not have the woman/man-power to help everybody. That is unfortunate, but simply a limitation of time. If it should turn out from your feedback to this message, that there is a bug involved, we will try to fix it with you.

That being said, we are very thankful that our community also does a great job in helping each other. I would therefore like to point you to some places where you can try asking for help. Usually, some friendly human being has time for you and your issue:

* **The Rocket.Chat Community Support Channel**: https://open.rocket.chat/channel/support
* **The Rocket.Chat Community Support Forum**: https://forums.rocket.chat/c/community-support

If you don't find a solution to your problem there, don't fret, as we also offer paid support: https://rocket.chat/support

You could, of course, spare yourself the hassle entirely and just choose the hosted version, where we provide you with a running Rocket.Chat instance: https://rocket.chat/cloud

Cheers
Thomas
