### ISSUE TITLE
Unable to assign moderator / admin privelges to Channels

### ISSUE THREAD

**Issue by tiredofit** [RocketChat/Rocket.Chat#8630]
### Description:

Since Upgrade to 0.59.1 (DB 104) in the members list when we click on a name it takes us directly to a Direct Message, instead of showing their profile and being able to assign moderator/owner priveleges of a Channel.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.1
* Operating System: Docker
* Deployment Method(snap/docker/tar/etc): Docker
* Number of Running Instances:  3
* DB Replicaset Oplog: True
* Node Version: 4.8.4

### Steps to Reproduce:

1. Create Room
2. Invite Users
3. Open Membership sidebar

### Expected behavior:

Previous versions showed a profile of the user along with buttons to assign them priveleges for the room.

### Actual behavior:

Direct Message

**Comment by marceloschmidt** [comment]
It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

**Sit tight!**

**Comment by fadanner** [comment]
The behaviour for me in 

* Version:  0.59.3
* Operating System: Ubuntu
* Deployment Snap
* Node version v4.8.4

Are there any news on this or a workaround?

**Comment by MartinSchoeler** [comment]
Closing this due lack of updates, if you experience this on the latest release, feel free to open a new issue.

Thanks!
