### ISSUE TITLE
"Allow Reacting" for readonly channels not work

### ISSUE THREAD

**Issue by volas** [RocketChat/Rocket.Chat#8632]
### Description:

After turned on "Allow Reacting" in "Room Info" the state is not saved, and users still can't react on messages.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.1

The problem can be reproduced on the cloud

### Steps to Reproduce:

1. Enable "Read Only" for Room
2. Enable "Allow Reacting"
3. Close "Room Info"
4. Open "Room Info" again, "Allow Reacting" is set to "off"

### Expected behavior:

Should work

### Actual behavior:

Does not work

### Relevant logs:

nothing

**Comment by marceloschmidt** [comment]
It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

**Sit tight!**

**Comment by marceloschmidt** [comment]
The contributors most likely able to help are:

@geekgonecrazy

**Comment by geekgonecrazy** [comment]
Deleted auto-posted comment from integration FYI.  :top:

**Comment by geekgonecrazy** [comment]
@volas please use the issue template.  As is your issue doesn't provide enough information.

**Comment by volas** [comment]
Updated.

**Comment by PhABC** [comment]
Can confirm. Changing "allow reacting" state doesn't work for read-only channels. Toggle works, message saying reacts are not allowed appears, but when pressing on the 'x', the change doesn't seem to be saved.
