### ISSUE TITLE
Implement settings for adding Open Graph meta

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/Rocket.Chat#868]
Would it interest anybody other than me to have implementation of [open graph meta tags](https://developers.facebook.com/docs/sharing/best-practices#tags) (Facebook) and possibly even Twitter ["cards"](https://dev.twitter.com/cards/overview)?

I could not find any earlier discussion about this.

Best wishes,
-k0nsl
##

**Comment by rodrigok** [comment]
Sounds interesting, what is necessary to implement this?

**Comment by gmsecrieru** [comment]
@k0nsl could you please give us more info on this?

**Comment by garg** [comment]
I encountered a problem where Facebook misidentifies my rocket.chat website's title despite the Site Name being correctly set. Facebook is misidentifying it because it wants og:title and og:url properties explicitly set according to their debugger here: https://developers.facebook.com/tools/debug/og/object?q=https%3A%2F%2Fpaint.chat 

That debugger also shows that when FB tries to determine the site name, it comes up with Rocket.Chat and I don't know where it's getting that from.

Here is the ogp website: http://ogp.me/ As far as I can tell, there needs to be meta tags for url and sitename in the header:

From the site:


>Basic Metadata
>To turn your web pages into graph objects, you need to add basic metadata to your page. We've based >the initial version of the protocol on RDFa which means that you'll place additional <meta> tags in the <head> of your web page. The four required properties for every page are:

>og:title - The title of your object as it should appear within the graph, e.g., "The Rock".
og:type - The type of your object, e.g., "video.movie". Depending on the type you specify, other properties may also be required.
og:image - An image URL which should represent your object within the graph.
og:url - The canonical URL of your object that will be used as its permanent ID in the graph, e.g., "http://www.imdb.com/title/tt0117500/".
As an example, the following is the Open Graph protocol markup for The Rock on IMDB:

>```html
<html prefix="og: http://ogp.me/ns#">
<head>
<title>The Rock (1996)</title>
<meta property="og:title" content="The Rock" />
<meta property="og:type" content="video.movie" />
<meta property="og:url" content="http://www.imdb.com/title/tt0117500/" />
<meta property="og:image" content="http://ia.media-imdb.com/images/rock.jpg" />
...
</head>
...
</html>
```

**Comment by IQ2022** [comment]
:+1:

**Comment by pierreozoux** [comment]
I think we can close the issue, there is now a meta section in admin.

**Comment by SupRavII** [comment]
(y)
