### ISSUE TITLE
Autocomplete username improvements

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#874]
Related to #848 

@dbussert @rodrigok follow up from #848 

I just tried this on slack and typing @ only matched on username.  Am I missing something?

I keep running into it..

![image](https://cloud.githubusercontent.com/assets/51996/10063423/1ed2d09e-6233-11e5-80e2-dccbcce4108a.png)

![image](https://cloud.githubusercontent.com/assets/51996/10000522/49e2d7a2-6062-11e5-899a-ee4e194adb64.png)

To me this is important to get right.  Because in a multi person conversation its good to mention them so they see your message and it doesn't get lost.  So i'm doing this constantly.  When the wrong name pops up... it gets pretty irritating.

It was mentioned in #848 that we want to be able to @PERSON NAME  I don't see slack / github or any other platform doing this..

Does it really make sense to include name when we never actually see their name but only their username?

@RocketChat/owners 
##

**Comment by marceloschmidt** [comment]
I think usernames only should be enough! :+1: for that!

**Comment by dbussert** [comment]
@geekgonecrazy I think your slack image proves the point.  The user `sun` only shows up because their first name is `Mars`, which matched the @mar.  Same for `xzil3d`.  Trello also does matching by real name or username.  I just tested out my team's Gitlab and it matches by both real name and username (we use Google Apps OAuth login).

![image](https://cloud.githubusercontent.com/assets/2479487/10064116/2882c864-6243-11e5-9d92-33286b65c883.png)

**Comment by geekgonecrazy** [comment]
@dbussert btw my screens are from Rocket.Chat.  But I just tried it and it is case sensitive.  That alone would solve part of the problem..

Because if I were to say a persons name i'd start off with a Capital letter in their name.  A username I would not.

**Comment by dbussert** [comment]
@geekgonecrazy I retested our gitlab and it is not case sensitive fwiw.

**Comment by geekgonecrazy** [comment]
@dbussert so on github / gitlab that wouldn't bother me at all.  But the speed I type / carry multiple conversations is greatly decreased.  It doesn't bother me the least bit to stop and search through and tag the appropriate person.

But when i'm carrying on a conversation with a person and mentioned them i'm used to IRC client style auto complete.  I type @ + first few letters <tab> and carry on with my sentence.  This is realtime, so we need to be efficient.

I also kind of feel like the people that are going to be referring to each other by first name are likely going to be using their name in their username...

**Comment by graywolf336** [comment]
Putting my two cents....some communities won't even use the first and last names. I know mine won't, as we're a gaming server and people go by their usernames instead of their real names. So, if they put something false in there I wouldn't really want that showing up. Not sure how much this adds, but maybe add it to be configurable in someway.

**Comment by marceloschmidt** [comment]
I say we should remove the name from the search, and see what comes out of it... if people miss it, we may add that as an admin settings later on. @RocketChat/owners ?

**Comment by rodrigok** [comment]
Slack matches username and name, but sort results better.
If you prefer we can change to match only username and see what happens

![captura de tela 2015-09-24 as 10 01 38](https://cloud.githubusercontent.com/assets/234261/10073993/4f129df0-62a3-11e5-902b-195b70695a71.png)

**Comment by engelgabriel** [comment]
Can it be an option on the settings?

**Comment by geekgonecrazy** [comment]
@rodrigok maybe if we used index score?  Been a while since i've done it.  But I know you can have mongo score based on match.  

@engelgabriel yeah even if an option.  That'd be cool :)

**Comment by gwillen** [comment]
Is this an appropriate place for me to ask: what's up with 'all' showing up randomly as a match in some autocompletes but not others? E.g. on our Rocket, "@all" is the first autocomplete hit for @a, @c, @g, but no other letters. This is weird when trying to autocomplete people with those initials.

**Comment by marceloschmidt** [comment]
It's not really random... @all will show for @all, @channel and @group. That's why it shows up as first on @a, @c and @g.

**Comment by ninja-** [comment]
can we do this client-side and cache team members to avoid this ugly loading screen after typing every letter after "@"?

**Comment by sampaiodiego** [comment]
doing client-side cache could be a problem for large teams.

**Comment by geekgonecrazy** [comment]
@sampaiodiego I don't think the issue is really the fact that it shows up.  If you type fast and hit tab it'll often times autocomplete to `@all`, even though the first letter is anything other then an a.

**Comment by gwillen** [comment]
A team would have to be _extremely_ large for client-side caching to be a problem. Google has something like 50,000 employees; if they were all on the same slack instance, and it took 10 bytes apiece to store their names in a trie, that would be 500k of RAM, in a pretty extreme case -- in this day and age that's really not much at all. And speeding up autocompletion would be pretty nice.

**Comment by sampaiodiego** [comment]
@gwillen I made an export of users on the demo server (27k users), only with the fields `_id`, `name` and `username`. the file size gets 1.9MB

**Comment by gwillen** [comment]
@sampaiodiego Ooh, didn't think about the need to include the 'name' field. Perhaps that could be elided in the case of large installations? I guess you'd also have to disable the ability to autocomplete on it to get much benefit (otherwise it's going to be present in the trie even if you don't display it.) If you do that, I imagine the memory burden goes down a _lot_, since names tend to be longer than usernames?

**Comment by geekgonecrazy** [comment]
Caching is great.. but i'd honestly be happy with it showing the proper name suggested and have a slight delay of it talking to the server to do a db query.  Especially in large instances.  If the last spoke in the channel was just bumped up in the stack of suggested, that alone would help

**Comment by gwillen** [comment]
Regarding showing the proper name, I have a bug open for what seems to be the cause of that at #1446 -- the client just doesn't wait for the autocomplete list to finish loading the latest results before it completes when you hit 'TAB' or 'ENTER'. That shouldn't be too bad to fix, independent of any client-side caching; the client just has to wait, after you hit 'TAB', for the autocomplete results to come back, BEFORE picking the first one.

**Comment by Sing-Li** [comment]
Yes. I tend to agree with @gwillen and @geekgonecrazy 

Perhaps we should make it actually usable, useful, without chance of constant mistake FIRST;  then deal with improvements later.

I'm saying this *primarily* because, EVERY day,  I continue to send @all messages daily when typing fast with autocomplete.

**Comment by fabiomontefuscolo** [comment]
Is it possible to search user using `'^' + selector.username` at https://github.com/RocketChat/Rocket.Chat/blob/develop/server/publications/userAutocomplete.coffee#L18?

I'm looking for this file at my docker instance, but I can't find.

**Comment by marceloschmidt** [comment]
I don't know why this issue was still open, since now we search usernames only. Though @fabiomontefuscolo suggestion is a good one too, IMHO. What do you think, @RocketChat/core ? Have you ever used the autocomplete to select a user and instead of typing their initials, you typed something to the middle? If you have, do you think that's expendable?

**Comment by engelgabriel** [comment]
We are still planning to enable full names back in the system, so lets wait for that to be completed before we make any decision.

**Comment by pescobar** [comment]
in case it helps to take a decision...in our rocket chat instance we use ldap for authentication and we automatically assign the ldap uid as rocketchat username. The problem is that ldap uid is not always descriptive enough to know who is who in the rocketchat channels. Being able to autocomplete also on name (which we also get automatically from ldap) is really convenient in our setup.

It would be nice to have name autocompletion feature at least as an option which can be enabled/disabled. This was working in previous releases and it was really convenient for us.

There is some more discussion about this topic in this other issue https://github.com/RocketChat/Rocket.Chat/issues/2785#issuecomment-214987339

**Comment by marceloschmidt** [comment]
As commented on #2129, I think we should search for users that start with what's typed and then do another search for contains, removing the former results from this search. This way, users that start with the text would show up first in results, but we'd still show the contained ones.

**Comment by rodrigok** [comment]
@marceloschmidt IMHO we should search only from the start, not containing.

@pescobar We can't use search for names right now, we are working to improve the cache of data on the client side, after that we will be able to do that. For your LDAP setup, you can change the `username` field to be generated using other fields from LDAP like the first and last name.

**Comment by iojeda** [comment]
Hi, I'm in the exact same situation like @pescobar, since we also have LDAP integration with our rocket.chat install, and must say I totally agree with him.
It will be really usefull and will help a lot if we can at least have an option to enable search by name if you dont want to set this as a default behaviour.

@rodrigok Thanks for your tip, but this will difficult login if we use things like "name.lastname" as username but its a posible solution.
What will happen If we change this in a production env? all chats for the old usernames will be lost? or it will be linked automatically to the new users?

**Comment by pescobar** [comment]
> What will happen If we change this in a production env? all chats for the old usernames will be lost? or it will be linked automatically to the new users?

I have exactly the same concern.

I also have ldap accounts with same name.lastname . The only field which is unique for sure is uid and that's why we use it as username. Using username.lastname could be a temporary workaround now that we only have few accounts active in rocketchat but I think this workaround would bring us troubles in the future when more users start using the chat

**Comment by rodrigok** [comment]
@iojeda @pescobar well, it depends, we have some configurations, one of is for unique fields, so users are linked between LDAP and Rocket.Chat by the unique field and not by the username field, so in theory you can go to the chat account settings and change your username and keep the link with LDAP.

In fact we need to test this behavior, I can't do that right now, will be awesome if you guys could clone your DB and start a new instance to test these ideas.

**Comment by iojeda** [comment]
Thanks @rodrigok I will test it and will give you feedback ;)

**Comment by iojeda** [comment]
Hi @rodrigok and @pescobar. 
I made the changes and as you already suggested and i must say that changing the username field does not harm at all.
Users keep using sAMAccountName for login and now I can search by name or surname so problem solved.
Thanks ;)

Here i attach actual config just in case you whant to replicate it @pescobar 
![ldap](https://cloud.githubusercontent.com/assets/5243583/15804971/e48bfdc6-2b12-11e6-8cdb-8fedeb826b35.png)

New users will be asked on first logon if they want they user name like "name.surname" and they can edit it.
For old users you will need to manually change their username on the Users tab at administator console.
Hope this helps ;)

**Comment by rodrigok** [comment]
@iojeda are you sure `# {} GivenName. # {Sn}` is working? The correct value should be `#{givenName}.#{sn}`

I already fixed the translation here https://github.com/RocketChat/Rocket.Chat/commit/ebcc80c74960dc3232dabd3f27c7ad2dcdee0906

**Comment by iojeda** [comment]
That's what i copy pasted on the username field following field tips. Surprisingly its working although I found it a bit weird when i saw it.
it makes more sense this new value you say.
I will change it then, thanks for the tip.

**Comment by SpencerCarstens** [comment]
Has there been any movement on this issue? It's a serious hinderance for my whole team.

I'm willing to throw some cycles at helping solve any blocking issues to help this along.

😃

**Comment by aventrax** [comment]
I'd want too an option to be able to search @ displayName

**Comment by rodrigok** [comment]
@SpencerCarstens Can you explain what exactly you want? We have a lot o subjects in this thread.

@aventrax We will release a new cache system for RC soon, then we can work to bring display name to messages and auto complete.

**Comment by aggregat4** [comment]
It is great that we can now (0.41.0) show real names in messages but we can now no longer search for people by their real name. If you switch with CTRL+P or try to mention someone this only matches the username. This reduces usability enormously. The usernames are technical artifacts that are in LDAP and not that what people can use to easily find someone.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

I cannot confirm the initial issue to be true in 0.61.0. I just verified that I can mention `thotest` which is my LDAP handle as well as my username, which is `thomas.test`. Also independant of case. If you still see this, please describe all the surrounding aspects, maybe post a screenshot of your profile and a little GIF of you trying to mention yourself.

Cheers
Thomas
