### ISSUE TITLE
[Query] Health Monitor.

### ISSUE THREAD

**Issue by ramanamatya** [RocketChat/Rocket.Chat#8765]
Hello Team,

This is just a query, I wanted to ask.

Is there is any-plans or process for the *health monitor indication* to check if the server, database is up and running.

Thank you 😄

**Comment by lunitic** [comment]
Couldn't you use Nagios, they have a mongodb check . 
https://github.com/mzupan/nagios-plugin-mongodb
https://www.nagios.org/ 

To have it inside rocket.chat seems pretty useless , if something is wrong then you will not be able to access the server..

**Comment by MartinSchoeler** [comment]
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.

**Comment by Lemmmy** [comment]
I think this issue was wrongly dismissed. Health monitor data can be used for a reverse proxy health check, to know when one server is down and to roll over to another. Often, the rocketchat webserver returns a positive response even if it is actually down, and a health check API would solve this problem.

**Comment by jeffmaher** [comment]
Seconding @Lemmmy on this. This seems like a pretty important feature request so that a team can easily monitor an installation and produce alerts when the system is experiencing issues. Curious if this is on the roadmap.
