### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by qiibinn** [RocketChat/Rocket.Chat#8782]
when trying to start the project with command "meteor nom start", got error in log file as the following:

-------------------
7021 verbose stack TypeError: Cannot read property '0' of undefined
7021 verbose stack     at rmStuff (/Users/qb/.meteor/packages/meteor-tool/.1.6.0.130umtl.ycp7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/lib/unbuild.js:61:24)
7021 verbose stack     at tryCatcher (/Users/qb/.meteor/packages/meteor-tool/.1.6.0.130umtl.ycp7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
7021 verbose stack     at ret (eval at makeNodePromisifiedEval (/Users/qb/.meteor/packages/meteor-tool/.1.6.0.130umtl.ycp7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
7021 verbose stack     at lifecycle.then.then (/Users/qb/.meteor/packages/meteor-tool/.1.6.0.130umtl.ycp7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/lib/install/action/unbuild.js:12:12)
7021 verbose stack     at tryCatcher (/Users/qb/.meteor/packages/meteor-tool/.1.6.0.130umtl.ycp7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
7021 verbose stack     at Promise._settlePromiseFromHandler (/Users/qb/.meteor/packages/meteor-tool/.1.6.0.130umtl.ycp7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
7021 verbose stack     at Promise._settlePromise (/Users/qb/.meteor/packages/meteor-tool/.1.6.0.130umtl.ycp7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
7021 verbose stack     at Promise._settlePromise0 (/Users/qb/.meteor/packages/meteor-tool/.1.6.0.130umtl.ycp7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
7021 verbose stack     at Promise._settlePromises (/Users/qb/.meteor/packages/meteor-tool/.1.6.0.130umtl.ycp7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
7021 verbose stack     at Promise._fulfill (/Users/qb/.meteor/packages/meteor-tool/.1.6.0.130umtl.ycp7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
7021 verbose stack     at /Users/qb/.meteor/packages/meteor-tool/.1.6.0.130umtl.ycp7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/bluebird/js/release/nodeback.js:42:21
7021 verbose stack     at <anonymous>
7022 verbose cwd /Users/qb/Rocket.Chat
7023 verbose Darwin 16.7.0
7024 verbose argv "/Users/qb/.meteor/packages/meteor-tool/.1.6.0.130umtl.ycp7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node" "/Users/qb/.meteor/packages/meteor-tool/.1.6.0.130umtl.ycp7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "i"
7025 verbose node v8.8.1
7026 verbose npm  v5.4.2
7027 error Cannot read property '0' of undefined
7028 verbose exit [ 1, true ]

**Comment by MartinSchoeler** [comment]
Not enough information provided.  Please check our [issue guidelines](https://rocket.chat/docs/contributing/reporting-issues) again for help on providing additional information.

**Comment by satyapramodh** [comment]
I am having the same issue while trying to setup. Please re-open the issue.

Operating System / Version / Architecture: Ubuntu 16.04.3, x64
Browser type and version, including any add-ons: Firefox v57
Rocket.Chat version: 0.60.0-develop
Expected behavior: `meteor npm install` install all packages and start the app
Actual behavior: 
<code>
npm ERR! Cannot read property '0' of undefined
</code>
Can the bug consistently be reproduced? If so, how?
1. Download NVM
2. Install and run node lts/carbon
3. run `meteor npm install` or `meteor npm start`

Relevant errors and other log output:

<pre>
7982 info lifecycle minimist@0.0.8~preuninstall: minimist@0.0.8
7983 info lifecycle minimist@0.0.8~uninstall: minimist@0.0.8
7984 verbose unbuild rmStuff minimist@0.0.8 from /home/pramodh/projects/rocket/node_modules
7985 verbose unbuild rmStuff in /home/pramodh/projects/rocket/node_modules/write/node_modules
7986 info lifecycle minimist@0.0.8~postuninstall: minimist@0.0.8
7987 silly unbuild webdriverio@4.9.11
7988 info lifecycle webdriverio@4.9.11~preuninstall: webdriverio@4.9.11
7989 info lifecycle webdriverio@4.9.11~uninstall: webdriverio@4.9.11
7990 verbose unbuild rmStuff webdriverio@4.9.11 from /home/pramodh/projects/rocket/node_modules
7991 info lifecycle webdriverio@4.9.11~postuninstall: webdriverio@4.9.11
7992 silly unbuild optimist
7993 info lifecycle undefined~preuninstall: undefined
7994 info lifecycle undefined~uninstall: undefined
7995 verbose unlock done using /home/pramodh/.npm/_locks/staging-d55c1c1661e19dbf.lock for /home/pramodh/projects/rocket/node_modules/.staging
7996 verbose stack TypeError: Cannot read property '0' of undefined
7996 verbose stack     at rmStuff (/home/pramodh/.meteor/packages/meteor-tool/.1.6.0_1.obe9u1++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/lib/unbuild.js:61:24)
7996 verbose stack     at tryCatcher (/home/pramodh/.meteor/packages/meteor-tool/.1.6.0_1.obe9u1++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
7996 verbose stack     at ret (eval at makeNodePromisifiedEval (/home/pramodh/.meteor/packages/meteor-tool/.1.6.0_1.obe9u1++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
7996 verbose stack     at lifecycle.then.then (/home/pramodh/.meteor/packages/meteor-tool/.1.6.0_1.obe9u1++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/lib/install/action/unbuild.js:12:12)
7996 verbose stack     at tryCatcher (/home/pramodh/.meteor/packages/meteor-tool/.1.6.0_1.obe9u1++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
7996 verbose stack     at Promise._settlePromiseFromHandler (/home/pramodh/.meteor/packages/meteor-tool/.1.6.0_1.obe9u1++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
7996 verbose stack     at Promise._settlePromise (/home/pramodh/.meteor/packages/meteor-tool/.1.6.0_1.obe9u1++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
7996 verbose stack     at Promise._settlePromise0 (/home/pramodh/.meteor/packages/meteor-tool/.1.6.0_1.obe9u1++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
7996 verbose stack     at Promise._settlePromises (/home/pramodh/.meteor/packages/meteor-tool/.1.6.0_1.obe9u1++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
7996 verbose stack     at Promise._fulfill (/home/pramodh/.meteor/packages/meteor-tool/.1.6.0_1.obe9u1++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
7996 verbose stack     at /home/pramodh/.meteor/packages/meteor-tool/.1.6.0_1.obe9u1++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/bluebird/js/release/nodeback.js:42:21
7996 verbose stack     at <anonymous>
7997 verbose cwd /home/pramodh/projects/rocket
7998 verbose Linux 4.10.0-42-generic
7999 verbose argv "/home/pramodh/.meteor/packages/meteor-tool/.1.6.0_1.obe9u1++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node" "/home/pramodh/.meteor/packages/meteor-tool/.1.6.0_1.obe9u1++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm" "install"
8000 verbose node v8.9.3
8001 verbose npm  v5.5.1
8002 error Cannot read property '0' of undefined
8003 verbose exit [ 1, true ]
</pre>

**Comment by vaibhavReachlocal** [comment]
I am having same issue - 

14151 verbose stack TypeError: Cannot read property '0' of undefined
14151 verbose stack     at rmStuff (/usr/local/lib/node_modules/npm/lib/unbuild.js:61:24)
14151 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
14151 verbose stack     at ret (eval at makeNodePromisifiedEval (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
14151 verbose stack     at lifecycle.then.then (/usr/local/lib/node_modules/npm/lib/install/action/unbuild.js:12:12)
14151 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
14151 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
14151 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
14151 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
14151 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
14151 verbose stack     at Promise._fulfill (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
14151 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/nodeback.js:42:21
14151 verbose stack     at <anonymous>
