### ISSUE TITLE
[NEW] Send message with REST API

### ISSUE THREAD

**Issue by cardoso** [RocketChat/Rocket.Chat#8864]
### Description:

We currently have a chat.postMessage API:
https://rocket.chat/docs/developer-guides/rest-api/chat/postmessage (outdated)

But that doesn't allow us to specify an id for the message like the Real-Time API:
```swift
{
    "msg": "method",
    "method": "sendMessage",
    "id": "42",
    "params": [
        {
            "_id": "message-id", // << specify id
            "rid": "room-id",
            "msg": "Hello World!"
        }
    ]
}
```

We need something similar, but REST. 

Either a new one (chat.sendMessage) mimicking the Real-Time API,
or adding _id in the existing chat.postMessage

**Comment by rafaelks** [comment]
@graywolf336 This one needs a little priority for the mobile apps.

**Comment by graywolf336** [comment]
Idea: change the current endpoint to accept a query that switches the internal logic to use the Meteor method of `sendMessage`. The reason we can't change the current logic is because it allows sending the same message to multiple channels thus resulting in more than one message object which is also the reason we can't allow the `_id` to be provided since then it wouldn't be unique on that index.

**Comment by rafaelks** [comment]
@graywolf336 I think a new API will be more simple to maintain and to write the docs.

**Comment by graywolf336** [comment]
Will be added with #8947
