### ISSUE TITLE
No Male Face Palm Emoji

### ISSUE THREAD

**Issue by hannes-angst** [RocketChat/Rocket.Chat#8901]
Description:
There are round about 43% human with an Y instead of another (deactivated) X chromosome. I would like to suggest adding male (face palm) emojis to the library.

### Server Setup Information:
* Version of Rocket.Chat Server: 2.9.0
* Operating System: macOS High Sierra 10.13.1
* Deployment Method(snap/docker/tar/etc): -
* Number of Running Instances:  -
* DB Replicaset Oplog: -
* Node Version: -

### Steps to Reproduce:
1. Open a chat window
2. Type ":face_palm" 
3. Search for a male face

![image](https://user-images.githubusercontent.com/2822902/33013551-c9794662-cde4-11e7-9e00-72f2b08a80aa.png)

### Expected behavior:
Male face palm emoji selectable from drop down by typing ":face_palm" 

### Actual behavior:
Only female face palm emoji available in the dropdown.

**Comment by MartinSchoeler** [comment]
@hannes-angst This is not a Rocket.Chat issue, we are using the "Emoji One" emoji package. You can open a issue on their repo https://github.com/emojione/emojione . Alternatively you can also add a custom emoji to your server. Thanks!

**Comment by transjen** [comment]
@hannes-angst did you just assume the emotion's gender?

**Comment by ziorufus** [comment]
The problem is present even if one inserts the male palm emoji from the keyboard.
I understand that this is an issue from another package, but the result is that Rocket.Chat (even recent versions!), a chat program, has some missing emoji. This could not be acceptable in 2017, and even more is not acceptable in 2024.

<img width="162" alt="Screenshot 2024-08-05 at 17 40 52" src="https://github.com/user-attachments/assets/4f76b547-f280-4506-b9bb-c90d3681cf54">
<img width="191" alt="Screenshot 2024-08-05 at 17 40 13" src="https://github.com/user-attachments/assets/adfa80a2-2db5-4a8f-862b-93088f59f16c">
