### ISSUE TITLE
Can't create cyrillic room name

### ISSUE THREAD

**Issue by umnique** [RocketChat/Rocket.Chat#892]
It is error message: 
"is not a valid room name,
use only letters, numbers and dashes"
when try to create room name in Russian (e.g. "Знакомства").
##

**Comment by gmsecrieru** [comment]
I ran a quick test and, for the channel creation (and name editing), it's just a matter of changing `server/methods/createChannel.coffee` and `server/methods/saveRoomName.coffee` regex validation:
![screen shot 2015-09-25 at 11 12 23](https://cloud.githubusercontent.com/assets/190883/10102715/5f9b1854-6376-11e5-820a-df9647d6a071.png)

 However, we mostly end up with an ugly URL, since FlowRouter.path params are [automatically encoded](https://github.com/kadirahq/flow-router#flowrouterpathpathdef-params-queryparams)
![screen shot 2015-09-25 at 11 15 49](https://cloud.githubusercontent.com/assets/190883/10102833/ff229b36-6376-11e5-8ecf-32c16e2e8fef.png)

...but we can access the channel by its regular characters, so it might be a not-that-big issue
![screen shot 2015-09-25 at 11 19 43](https://cloud.githubusercontent.com/assets/190883/10102884/611df998-6377-11e5-866e-a1470fff276e.png)

...as it could be `decodeURIComponent`ed back
![screen shot 2015-09-25 at 11 36 54](https://cloud.githubusercontent.com/assets/190883/10103367/de489a48-6379-11e5-9526-f623d700192b.png)

Anyways, this was just a bit of hacking into our codebase but we would certainly need to test this further and come up with a long-lasting solution :smile:

**Comment by Sing-Li** [comment]
Yes.  Please read the last comment of this thread -  kadirahq/flow-router#168

**Comment by gmsecrieru** [comment]
Related to #640
