### ISSUE TITLE
Unable to connect to our server except twice.

### ISSUE THREAD

**Issue by asshewale** [RocketChat/Rocket.Chat#8920]
Hi Devs... i am new to RC, i really loved the way it works,  Actually i downloaded the RC's clone from git repository, we do have integrated the RC in web application with in that we are using our own server's URL instead of using the open.rocket.chat, The same we tried to implement in our mobile app, As per that we replaced the open.rocket.chat url from the RC's clone with our server's url, Issue is, sometimes we are able to connect but most of times we fails to connect to our server... Any one will please suggest me how should i trace the issue, we tried with the server side for number of open connections for particular app by server but that is not the issue..   The scenario is , two times we are able to connect to our server then it also allows us to login, but 3rd time its not allowing us to connect to our server it just shows the loading and loading .. then we have to kill the app and try again to connect to our server... in this step sometimes it allows to connect again for two times or even sometimes it doesnt allow to connect to server any more,  We are really struggling a lot to trace the issue from last two days, Will you guys please help us with some ideas please, your any help will be highly appreciated.

**Comment by geekgonecrazy** [comment]
When it comes to mobile couple of things.

* iOS you must have https.  Its an iOS thing.
* Make sure you have websockets properly forwarded through by your reverse proxy.
* If you don't need to compile from source... don't.  Use official release, helps us help you when you are on an official release.  :)

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @asshewale 

I am closing this issue because we think there is no actual bug in Rocket.Chat in what you're describing. Here's why:

* not enough information (see [issue template](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/ISSUE_TEMPLATE.md))
* probably no Bug but rather a deployment issue

We use Github mainly for discussing bugs though. We understand, that setting up and operating a Rocket.Chat server is not trivial, yet we do not have the woman/man-power to help everybody. That is unfortunate, but simply a limitation of time. If it should turn out from your feedback to this message, that there is a bug involved, we will try to fix it with you.

That being said, we are very thankful that our community also does a great job in helping each other. I would therefore like to point you to some places where you can try asking for help. Usually, some friendly human being has time for you and your issue:

* **The Rocket.Chat Community Support Channel**:
https://open.rocket.chat/channel/support (for general support)
* **The Rocket.Chat Community Dev Channel**:
https://open.rocket.chat/channel/dev (for development-focussed support)
* **The Rocket.Chat Community Support Forum**:
https://forums.rocket.chat/c/community-support

If you don't find a solution to your problem there, don't fret, as we also offer paid support: https://rocket.chat/support

You could, of course, spare yourself the hassle entirely and just choose the hosted version, where we provide you with a running Rocket.Chat instance: https://rocket.chat/cloud

[GENERIC ROCKET.CHAT SALUTATION]
[USERNAME OF THE ONE WHO TRIGGERED THE BOT]
