### ISSUE TITLE
Cryptic error when trying to send a test email with SMTP settings 

### ISSUE THREAD

**Issue by robguinness** [RocketChat/Rocket.Chat#8934]
### Description:

I am attempting to configure SMTP settings. I believe I have the correct settings, however, I get an error when clicking "SEND A TEST MAIL TO MY USER". The error message says, "Error
Error trying to send email: 140642254661440". In the log, there is no mention of an error, only "rocketchat-server.rocketchat-server[9079]: Sending test email to email@example.com"

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.3
* Operating System: Linux (Ubuntu 16.04)
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: ??
* Node Version: v4.8.4

### Steps to Reproduce:

1. Configure settings in Admin--> Email --> SMTP
2. Save changes
3. Click "SEND A TEST MAIL TO MY USER"

### Expected behavior:

Success with sending email.

### Actual behavior:

An error message says, "Error
Error trying to send email: 140642254661440"

### Relevant logs:
Nothing in browser log. Server log has:

Nov 23 17:15:58 imgc rocketchat-server.rocketchat-server[9079]: rocketchat_logger.js:375 Meteor ➔ method sendSMTPTestEmail -> userId: oBDTNkR3hEpdJrArA , arguments:  {}
Nov 23 17:15:58 imgc rocketchat-server.rocketchat-server[9079]: Sending test email to email@example.com

**Comment by robguinness** [comment]
Hi @MartinSchoeler, could you help me look into this issue further? Let me know if you need further details.

**Comment by robguinness** [comment]
Can someone please help with this?

**Comment by reetp** [comment]
Suggest you post your server settings and any other relevant setups details.
Anything in your mail server logs?

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

It's very likely that this is something related to your SMTP server. Please have a look at the log files of your mailserver. Without any logs, though, we won't be able to help you. For now I'm closing this.

If this is still an error on your side, please provide additional logs and get back to me. I'll be happy to reopen if this turns out to be a bug after all.

Cheers
Thomas

**Comment by ceefour** [comment]
I think that the very point of this issue this the lack of more detailed error logs in Rocket.Chat server itself. If a connection fails, for example due to wrong SMTP hostname, etc. there will be no mailserver logs to check because Rocket.Chat was not connecting to that server in the first place.

Currently I'm also having an issue in 3.6.3 where Rocket.Chat crashes when sending test email. (not sure if relevant to this issue)

However, I suggest an improvement to Rocket.Chat error messages for sending test email, so any such problems will be easier to diagnose?
