### ISSUE TITLE
can't connect, connection lost/// during slack import 

### ISSUE THREAD

**Issue by maxpen** [RocketChat/Rocket.Chat#8945]
### Description: https://gyazo.com/4d83def2c5fd39adfdd6e3c11023ad88  I get this all the time from being an end user on all rocketchat instance after just a few min of not typing or  as an admin owner as well when I try to import a slack file. 

I'm not running this on a domain just on server IP, clean install on a droplet.

Here's my console log output:; https://pastebin.com/LxQPKRmQ
Log file: https://pastebin.com/RyZ5yLDc 

### Server Setup Information:

Operating System: Ubuntu 4.4.0-101-generic
Deployment Method(snap/docker/tar/etc):snap
Number of Running Instances: 1
DB Replicaset Oplog:
Node Version: v4.8.4

### Steps to Reproduce:

1. 
2. 
3.

**Comment by jszaszvari** [comment]
You have not provided any information what-so-ever that will help someone troubleshoot or see whats going on. 

I'm sure the logs would tell you exactly why it crashed.

**Comment by maxpen** [comment]
Here's my console log output:; https://pastebin.com/LxQPKRmQ
Log file: https://pastebin.com/RyZ5yLDc

**Comment by lindoelio** [comment]
Hey @maxpen. Thanks for your contribution here.

This is happening because your instance have been setup for production mode, so you will need SSL ecryption. Try use LetsEncrypt in your droplet. See more in https://www.digitalocean.com/community/tutorials/how-to-set-up-let-s-encrypt-with-nginx-server-blocks-on-ubuntu-16-04.

Keep in the loop :-)
