### ISSUE TITLE
How to update RocketChat on WeDeploy?

### ISSUE THREAD

**Issue by matek200412** [RocketChat/Rocket.Chat#8950]
Hello!
I want to update my RocketChat on WeDeploy.io to latest version but I don`t know how to do it.
Please, help!
 
 
 
 
 
 
 

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.2
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): WeDeploy
* Number of Running Instances: 1
* DB Replicaset Oplog:
* Node Version: v4.8.4

### Steps to Reproduce:

1. 
2. 
3.

**Comment by zenorocha** [comment]
@jonnilundy can you help this user?

**Comment by jonnilundy** [comment]
Hey @matek200412! 

To update your version of Rocket.Chat on a WeDeploy deployment you can change the image version in your `wedeploy.json` to the version you would like to pull from [Docker Hub](https://hub.docker.com/r/library/rocket.chat/tags/). 

Your `wedeploy.json` would look something like this:

```
{
  "id": "app",
  "image": "rocket.chat:0.58.4"
}
```

If you do not declare a version, we will automatically use the latest version of the image. You can also check out our [Rocket.Chat Demo](https://github.com/wedeploy/demo-rocketchat) to see more code.

**Comment by MartinSchoeler** [comment]
Hey, looks like you seem to be looking for support. You will have a better chance of getting help if you go to one of the places listed in [here](https://rocket.chat/docs/getting-support/#community-support) since github is not the best place to ask for support. For now i will be closing this issue, as it does not fit our issue guidelines
