### ISSUE TITLE
[Important]

### ISSUE THREAD

**Issue by Nikokatsu** [RocketChat/Rocket.Chat#8953]
Could you please remove the addons for the Heroku Deployment please?
When i try and deploy it it always asks for my credit card, can someone remove it?

**Comment by geekgonecrazy** [comment]
Its a deployment option.  If its asking for credit card you must have already used the free options.

**Comment by Nikokatsu** [comment]
Can you remove the addons? I dont want to use a credit card. Is there a way that you can remove the addons? Please

**Comment by geekgonecrazy** [comment]
If you create a new account it should make you enter any credit card info.

If it does please let me know which ones do.  The add-ons included with heroku are required in order to function.

If you let me know which add-on it's trying to charge you for after creating a new account I can try to investigate why it's trying to charge you.
