### ISSUE TITLE
Proxy authentication via NTLM for Rocket.Chat and Rocket.Chat+ apps

### ISSUE THREAD

**Issue by ruKurz** [RocketChat/Rocket.Chat#8974]
When using external storage for attachments or pasting links to external websites and you're running the RC+ app behind a corporate proxy that requires an authentication for resolving the URLs, the preview can't be rendered within the Rocket.Chat+ apps.

For this issue it would be great to see a proxy configuration within the apps, that supports NTLM based authentication for the corporate proxy.

relates to #8894

**Comment by jonesjardel** [comment]
I was just looking for it...

**Comment by ruKurz** [comment]
I also opened an issue here, since I think `Rocket.Chat.Electron` is the right project.

https://github.com/RocketChat/Rocket.Chat.Electron/issues/620

**Comment by mauricio-sonegatti** [comment]
I think defining the Proxy Auth for apps has to be done on the server, hence why it's important to keep the issue here. More because whe have a lot o integration through some Cloud Services.
For now, as I'm running my RC on a VM, I can set the network connection through a VPN tunnel to access services outside the corporate proxy, it works.
