### ISSUE TITLE
[Sandstorm]  Merge  Sandstorm branch down to master

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#907]
Modifications made in adapting to Sandstorm need to be made a permanent part of master.

This eliminate the need to maintain a separate branch, and allow the Sandstorm app to have features parity with our mainstream apps.

**Comment by Sing-Li** [comment]
Need some guidance for *best practices* from those who have done this before in other Meteor to Sandstorm ports.

@kentonv , @jparyani , @dwrensha  ,  @rodrigok , @geekgonecrazy 

**Background**
Meteor app has template + JavaScript code on client side.

**Problem**
We want one code base that will:
* handle web and mobile builds
* handle Sandstorm builds

We dont' want:
* duplication of code
* inclusion of code *anywhere* NOT intended for the platform (i.e. sandstorm code included in web builds)
* reactive/dynamic triggering of platform specific code (security!)

**Problem Example**
Sandstorm requires that we rip out normal user authentication.  How to structure our Template + JavaScript code to satisfy all the goals above?

**Not so nice solution**
A 'builder tool' that will slice-and-dice the code to fit during build.

**Better solution?**
All  ideas and thoughts welcomed.

**Comment by jparyani** [comment]
The accounts-oauth package has an `unregisterService` function (see https://github.com/meteor/meteor/blob/ca4b798cdd8fc83442a57c5140dcca6e5362b127/packages/accounts-oauth/oauth_common.js#L27).

I'm not sure this actually helps you at all since it sounds like you never want the code to get past the build step, but if you're ok with dynamically doing it at run-time, this is one way to go.

**Comment by Sing-Li** [comment]
Gabriel completed this last week.
