### ISSUE TITLE
[Sandstorm]  Use Sandstorm's avatars

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#908]
Sandstorm handles users authentication and management, including avatars.

Use Sandstorm's user avatars instead of maintaining our own.

**Comment by Sing-Li** [comment]
See this commit, and associated comments for access to the Sandstorm managed user avatars...

https://github.com/sandstorm-io/meteor-accounts-sandstorm/commit/19a6fde497c7b0c67cf46aa5f0382cee9e1323ed

**Comment by kentonv** [comment]
Assuming you're using the latest version of accounts-sandstorm, the avatar URL is placed in `user.services.sandstorm.picture`. All you need to do is publish this field to the client and use it.

While you are at it, you should also initialize the user's username based on `user.services.sandstorm.preferredHandle`. I would recommend only showing the user name chooser if their preferred handle is unavailable.

Docs: https://github.com/sandstorm-io/meteor-accounts-sandstorm#user-profile-info

**Comment by engelgabriel** [comment]
@kentonv we don't have customized URLs for avatar, the url is fixed `/avatar/[username]` so we will probably have to do a permanent redirect to `user.services.sandstorm.picture` upon request.

How does the picture update works?
Does it generates a new URL?
Is this URL accessible for Rocket.Chat to download and store on its on storage?
Should users be able to set a different username/avatar?

Let's work on this PR together?

**Comment by kentonv** [comment]
@engelgabriel 

> we don't have customized URLs for avatar, the url is fixed /avatar/[username] so we will probably have to do a permanent redirect to user.services.sandstorm.picture upon request.

Well, that would work, but it will perform a lot worse. You have a caching problem where you can't set the cache timeout high otherwise a change to the user's avatar won't show up immediately, but if you set the timeout low then the browser is constantly re-requesting the same data.

It looks to me like the Rocket.Chat client subscribes to the Meteor.users collection, at least for users currently visible. Could you not use a client-side template helper to generate the image URL using `user.services.sandstorm.picture` on Sandstorm and `/avatar/[username]` elsewhere?

> How does the picture update works?

Users update their picture in the Sandstorm account settings. Then, the next time the user opens Rocket.Chat, `accounts-sandstorm` will automatically update `user.services.sandstorm.picture` to the new URL.

> Does it generates a new URL?

Yes.

> Is this URL accessible for Rocket.Chat to download and store on its on storage?

Yes, but this would be wasteful and slow. Users who know each other probably already have each other's pictures cached in their browser, so it's best to reuse the canonical address.

> Should users be able to set a different username/avatar?

On Sandstorm, probably users should only set their avatar in the Sandstorm settings, not separately inside Rocket.Chat, to avoid confusion.

Username is a bit more complicated. Sandstorm lets users set a "preferred handle" but it is not guaranteed to be unique, so Rocket.Chat may need to de-dupe. For now I think it's fine to keep the existing UI, but initialize the username from `preferredHandle` instead of from `profile.name` as it is currently. You can also probably skip the first-time username prompt if the user's preferred name is available.

> Let's work on this PR together? #2253

Cool, I'll take a look.

**Comment by engelgabriel** [comment]
Having all the picture URLs on the client is trickier... on the demo server we have 60k users, we can keep the 60k URL in memory, neither dynamically request them as the messages appear for performance issues. We decided to have a ?_dc=0 query parameter on all avatars and a cache instruction to make the picture valid for the current browser session only. When an user changes an avatar mid of other users session, we broadcast a signal to increment the ?_dc=1 for that specific username for that session.
