### ISSUE TITLE
Can't add snippet in 0.59.4

### ISSUE THREAD

**Issue by amateo** [RocketChat/Rocket.Chat#9178]
Hi,

  I have just upgraded from 0.58.4 to 0.59.4. Since then, I can't create snippet (which I could did with previous version).

  I have enabled it in Administration>Messages>Allow Message Snippeting and in permission of users (in fact, it's the same configuration which was working with 0.58.4), but the option to create the snippet is not displayed in the message's options.

![captura de pantalla de 2017-12-19 09-52-53](https://user-images.githubusercontent.com/3133951/34149553-c257c516-e4a5-11e7-8370-cddf90aee3b7.png)

**Comment by dmitriy-olhovsky** [comment]
The same issue appears in the fresh versions (1.0.3 and 1.2.0 dev). After activation "Allow Message Snippeting" option possibility to create code snippet is missing.  I only have spippet option on the channel details menu, but with infinite loop. Maybe I need to activate another option or use another method to fix the issue? Thanks.

![зображення](https://user-images.githubusercontent.com/7704786/59336718-ba378900-8d07-11e9-820b-bedbbc6ebc95.png)

**Comment by deadpony** [comment]
that is the reason 

https://github.com/RocketChat/Rocket.Chat/blob/64a95524010ac4a5723f278e8667d47409810f2b/app/message-snippet/client/actionButton.js

**Comment by Amorik** [comment]
I am having the same issue as @dmitriy-olhovsky issue with v1.1.1 and v.1.1.3. 

I am running a fresh basic no complexity install, single user, the admin account. The permissions to  create snippets was added to the admin account and the option enabled.

**Comment by reetp** [comment]
@rocket-cat close

I think this can be closed as there have been massive changes since this was opened.

Note also that snippeting has been revised as well.

This was the original PR I believe:
https://github.com/RocketChat/Rocket.Chat/pull/4623

Send the message snippet as an attachment 
https://github.com/RocketChat/feature-requests/issues/99

Update message actions - remove existing Snippet icon - uses PR 14268 below
https://github.com/RocketChat/Rocket.Chat/issues/14254

Update message actions - "Commented code for now, because the behavior of the snippets will be changed in the future. See: RocketChat/feature-requests#99"
https://github.com/RocketChat/Rocket.Chat/pull/14268

So that comments out and breaks the Snippeting code.

This should be followed up on the feature request or the PR which broke the existing action with a replacement.

**Comment by karmaking** [comment]
I'm having the same issue here right now; v2.2.1 - anything to tweak for this to work?

**Comment by reetp** [comment]
You can read the info above but this is closed. Follow up in the NFR mentioned as if there is any work, that is where it will happen.
