### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by umardraz** [RocketChat/Rocket.Chat#9208]
Hi

I am running latest Rocket.chat using docker. How i can run multiple instances like chat1.mydomain.com, chat2.mydomain.com and chat3.mydomain.com.

Do I need separate docker instances or single Rocket.Chat installation is enough?

**Comment by bprinsloo** [comment]
Might be wrong, but on ubuntu I created instances for different domains on different ports as follow : 
sudo forever-service install -s main.js -e "ROOT_URL=https://domain.com/ MONGO_URL=mongodb://localhost:27017/db1 PORT=3000" domain1service

and then for the second domain
sudo forever-service install -s main.js -e "ROOT_URL=https://domain2.com/ MONGO_URL=mongodb://localhost:27017/db2 PORT=3001" domain2service

This then creates two services which I can run independently. Withing NGINX I then configure the domains to use the two ports for the different domains.

 server {
    listen 80;
    server_name domain1.com www.domain1.com;
    error_log /var/log/nginx/rocket.domain1.com.access.log;

    ssl off;

    location / {
        proxy_pass http://myserver.com:3000/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forward-Proto http;
        proxy_set_header X-Nginx-Proxy true;

        proxy_redirect off;
    }
}

**Comment by pettitto** [comment]
There's documentation on it here too: https://rocket.chat/docs/installation/manual-installation/multiple-instances-to-improve-performance/#run-multiple-instances-of-rocket-chat

**Comment by umardraz** [comment]
Hi

My question was multiple sudomains

chat1.domain.com
chat2.domain.com
chat3.domain.com
chat4.domain.com

Do we need a separate instance of each subdomain or a single installation of rocketchat can do this?

**Comment by bprinsloo** [comment]
For my method above you only need one installation. What I do is to create an service instance per domain or subdomain, all from the same installation.

**Comment by umardraz** [comment]
Yes I saw that, but I am more interested with docker swarm

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @umardraz

I am closing this issue because we think there is no actual bug in Rocket.Chat and we use Github mainly for discussing bugs. We understand, that setting up and operating a Rocket.Chat server is not trivial, yet we do not have the woman/man-power to help everybody. That is unfortunate, but simply a limitation of time. If it should turn out from your feedback to this message, that there is a bug involved, we will try to fix it with you.

That being said, we are very thankful that our community also does a great job in helping each other. I would therefore like to point you to some places where you can try asking for help. Usually, some friendly human being has time for you and your issue:

* **The Rocket.Chat Community Support Channel**: https://open.rocket.chat/channel/support
* **The Rocket.Chat Community Support Forum**: https://forums.rocket.chat/c/community-support

If you don't find a solution to your problem there, don't fret, as we also offer paid support: https://rocket.chat/support

You could, of course, spare yourself the hassle entirely and just choose the hosted version, where we provide you with a running Rocket.Chat instance: https://rocket.chat/cloud

Cheers
Thomas
