### ISSUE TITLE
[NEW] BigBlueButton Integration

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#9230]
We would like to support https://bigbluebutton.org as an alternative for video conference.

The plan is to work with https://mconf.com to integrate the new HTML5 UI from https://html5-dev.mconf.com when it gets merged https://github.com/bigbluebutton/bigbluebutton/pull/4661

**Comment by TwizzyDizzy** [comment]
As discussed at the summit: please add a label "feature-needs-review" label.

/cc @SeanPackham 

Cheers
Thomas

**Comment by dmoldovan123** [comment]
Hello,
 Integration with html5 not work. I have error on logs:
Exception while invoking method 'bbbJoin' Error: failed [404] <html><head><title>Apache Tomcat/7.0.68 (Ubuntu) - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;backgr...     at Object.exports.makeErrorByStatus (packages/http.js:176:10)     at Request._callback (packages/http.js:140:24)     at Request.self.callback (/var/www/Rocket.Chat-0.69.0/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:186:22)     at emitTwo (events.js:126:13)     at Request.emit (events.js:214:7)     at Request.<anonymous> (/var/www/Rocket.Chat-0.69.0/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1163:10)     at emitOne (events.js:116:13)     at Request.emit (events.js:211:7)     at IncomingMessage.<anonymous> (/var/www/Rocket.Chat-0.69.0/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1085:12)     at Object.onceWrapper (events.js:313:30)     at emitNone (events.js:111:20)     at IncomingMessage.emit (events.js:208:7)     at endReadableNT (_stream_readable.js:1064:12)     at _combinedTickCallback (internal/process/next_tick.js:138:11)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)

**Comment by bunesm** [comment]
I have the same problem.
I did the integration correctly but there is still an error:

Exception while invoking method 'bbbJoin' Error: failed [404] ....

Can someone help us?

**Comment by fcecagno** [comment]
It's probably related to this issue: https://github.com/RocketChat/Rocket.Chat/issues/12050
Try to configure your server as https://<domain>

**Comment by dmoldovan123** [comment]
Hello, does not work with https://<domain>

**Comment by padrogass** [comment]
same problem here:

error log from bigbluebutton server:

**[error] 13494#13494: *542 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.200.33, server: meet.xxx.es, request:
"GET
/bigbluebutton/api/hooks/create?callbackURL=https%3A%2F%2Fchat.xxx.es%2Fapi%2Fv1%2Fvideoconference.bbb.update%2FMdEa6Yv8EyehtumqCZMtNXBW9AQoDMphick3WYGZfGTgeEgJ555&meetingID=MdEa6Yv8EyehtumqCZMtNXBW9AQoDMphick3WYGZfGTgeEgJ555&$
HTTP/1.1", upstream:
"http://127.0.0.1:3005/bigbluebutton/api/hooks/create?callbackURL=https%3A%2F%2Fchat.xxx.es%2Fapi%2Fv1%2Fvideoconference.bbb.update%2FMdEa6Yv8EyehtumqCZMtNXBW9AQoDMphick3WYGZfGTgeEgJ555&meetingID=MdEa6Yv8EyehtumqCZMtNXBW9AQoDM$
host: "meet.xxx.es"**

**Comment by fcecagno** [comment]
@dmoldovan123 "getaddrinfo ENOTFOUND" means that your Rocket.Chat server is unable to resolve `<domain>`, you might want to check that.

**Comment by fcecagno** [comment]
@padrogass It looks like you're not running bbb-webhooks (I didn't know it was necessary to integrate with Rocket.Chat).

**Comment by padrogass** [comment]
Hi @fcecagno! i have installed it and reboot and i get the same error... i have also reboot both servers, rocketchat and bbb server

**Comment by fcecagno** [comment]
@padrogass do you see any error on the Rocket.Chat side?

**Comment by padrogass** [comment]
@fcecagno 
[34mI20181122-22:50:25.406(1) Exception while invoking method 'bbbJoin' Error: failed [404] <html>  <head><title>404 Not Found</title></head>  <body bgcolor="white">  <center><h1>404 Not Found</h1></center>  <hr><center>nginx/1.10.3 (Ubuntu)</center>  </body>  </html>       at Object.exports.makeErrorByStatus (packages/http.js:176:10)     at Request._callback (packages/http.js:140:24)     at Request.self.callback (/snap/rocketchat-server/1343/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:186:22)     at emitTwo (events.js:126:13)     at Request.emit (events.js:214:7)     at Request.<anonymous> (/snap/rocketchat-server/1343/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1163:10)     at emitOne (events.js:116:13)     at Request.emit (events.js:211:7)     at IncomingMessage.<anonymous> (/snap/rocketchat-server/1343/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1085:12)     at Object.onceWrapper (events.js:313:30)     at emitNone (events.js:111:20)     at IncomingMessage.emit (events.js:208:7)     at endReadableNT (_stream_readable.js:1064:12)     at _combinedTickCallback (internal/process/next_tick.js:138:11)     at process._tickDomainCallback (internal/process/next_tick.js:218:9) 

rocketchat is resolving ok the bbb domain... the 404 error is getting due to a 50X previous error in bbb server.

**Comment by padrogass** [comment]
it is a 502 error.

i have tested here my bbb server api here http://mconf.github.io/api-mate/ and all the responses are ok. I think it must be some rocket.chat problem...

**Comment by fcecagno** [comment]
@padrogass it looks like Rocket.Chat requires BigBlueButton webhooks to be properly installed and configure. Make sure you can access `https://<domain>/bigbluebutton/api/hooks/create` in your server, and that you see checksumError, but it still returns OK 200.

**Comment by padrogass** [comment]
@fcecagno you are right!

I have installed bbb-webhooks, and when I launch the meeting, it doesn't load html5 client, it starts flash player.

it loads all the bbb app, not only the webcam. :(

**Comment by padrogass** [comment]
i have the html5client running in bbb server :)

**Comment by engelgabriel** [comment]
The support for BigBlueButton has been added a few version ago via https://github.com/RocketChat/Rocket.Chat/pull/11837

Let's open new issues for bug reports and improvements.

**Comment by Shaverdoff** [comment]
is no any fix or explaine how to get worked variants rc+bbb?
