### ISSUE TITLE
Cannot build code

### ISSUE THREAD

**Issue by BlessBau** [RocketChat/Rocket.Chat#9232]
### Description:

I have some customization and want to create a release, so as a meteor project, I did try:
`meteor build --directory /opt/publish`

### Server Setup Information:

* Version of Rocket.Chat Server: Latest from repo
* Operating System: Ubuntu Server 16.04
* Deployment Method(snap/docker/tar/etc):
* Number of Running Instances:  1
* DB Replicaset Oplog:
* Node Version:

### Steps to Reproduce:

1. meteor build --directory /opt/publish

### Expected behavior:

A deploy-able code should be produced

### Actual behavior:

A code was generated with errors and this is the last output on my screen
`Currently, it is only possible to build iOS apps on an OS X system.
updated 2 packages in 2.434ss                \
to: wrong argumentsve plugins                /

toEnd: wrong arguments

postcss-custom-properties: /opt/Rock2/packages/rocketchat-emoji/client/emojiPicker.css:9:3: variable '--message-box-container-border-color' is undefined and used without a fallback      postcss-custom-properties: /opt/Rock2/packages/rocketchat-emoji/client/emojiPicker.css:9:3: variable '--message-box-container-border-color' is undefined and used without a fallback`

**Comment by AmShaegar13** [comment]
Did you run `meteor npm install` before and built rocketchat:lib twice as suggested in [example-build-run.sh](https://github.com/RocketChat/Rocket.Chat/blob/develop/example-build-run.sh)?

**Comment by BlessBau** [comment]
yes, I did that after reviewing example-build-run.sh
I tried for both centos 7 and ubuntu 16.04, got the same error.

**Comment by BlessBau** [comment]
btw, when trying to run the produced code, this is the error that I am getting:

`node main.js 
/opt/build/bundle/programs/server/boot.js:50
const { pause } = require("./debug.js");
^

SyntaxError: Unexpected token {
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:373:25)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/opt/build/bundle/main.js:4:1)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10) `

  
should I turn off something before building?`

**Comment by AmShaegar13** [comment]
Version 0.60.0 requires node v8.8.1. You can see the required version [here] (

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @BlessBau 

I am closing this issue because we think there is no actual bug in Rocket.Chat in what you're describing. Here's why:

* help with build errors is best given over at: https://forums.rocket.chat/c/community-support

We use Github mainly for discussing bugs though. We understand, that setting up and operating a Rocket.Chat server is not trivial, yet we do not have the woman/man-power to help everybody. That is unfortunate, but simply a limitation of time. If it should turn out from your feedback to this message, that there is a bug involved, we will try to fix it with you.

That being said, we are very thankful that our community also does a great job in helping each other. I would therefore like to point you to some places where you can try asking for help. Usually, some friendly human being has time for you and your issue:

* **The Rocket.Chat Community Support Channel**: https://open.rocket.chat/channel/support
* **The Rocket.Chat Community Support Forum**: https://forums.rocket.chat/c/community-support

If you don't find a solution to your problem there, don't fret, as we also offer paid support: https://rocket.chat/support

You could, of course, spare yourself the hassle entirely and just choose the hosted version, where we provide you with a running Rocket.Chat instance: https://rocket.chat/cloud

Cheers
Thomas
