### ISSUE TITLE
Since last Chrome update browser is always getting stuck during incoming call (Chrome v 63.0.3239.84 x64, Windows )

### ISSUE THREAD

**Issue by ivanvoitovych** [RocketChat/Rocket.Chat#9303]
### Description:

Since last Chrome update browser is always getting stuck during incoming call (Chrome v 63.0.3239.84 x64, Windows )

### Server Setup Information:

Chat url: https://open.rocket.chat
users: ivan.vojtovich, ivan.voitovych
### Steps to Reproduce:

1. Start a call from one machine 
2. Accept call on other side (second machine with last Chrome, Windows based)
3. Tab stuck after call accepting

### Expected behavior:

Tab should never stuck

### Actual behavior:

Tab stuck after call accepting

### Relevant logs:
no logs

**Comment by shchotchuk** [comment]
I have the same issue. Does anyone have any ideas how to solve this?

**Comment by VinArt** [comment]
I have the same issue with Version 63.0.3239.108 (Official Build) (64-bit) on Linux. What is interesting, call succeeds when I make a call and the recipient is using Chrome Version 61.0.3163.100 (Official Build) (64-bit) , but not the other way around. Also for me in the popup I see html tag: 
![image](https://user-images.githubusercontent.com/3738015/34625445-f97ab1dc-f258-11e7-8378-30c31b776ad7.png) instead of it being rendered to an icon.

**Comment by MartinSchoeler** [comment]
Hey I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks
