### ISSUE TITLE
Rocket.Chat without websockets?

### ISSUE THREAD

**Issue by Poeschl** [RocketChat/Rocket.Chat#9307]
Hi,
is there a way to get the push notifications without the use of Websockets?
My company would like to host a rocket.chat instance on AWS and access it from behind a company-proxy :/ (without websocket support)

The messages are coming through perfectly, the only downside are the missing notifications. Is there a way to make them also work without the blocked websockets?

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

I do not think that this is going to happen. Websockets are paramount for the function of Rocket.Chat and having a fallback would probably require the implementation of client-side polling..

@geekgonecrazy: if there are plans to have some polling fallback, please reopen or forward to the frontend guys :)

Cheers
Twizzy

**Comment by geekgonecrazy** [comment]
We actually do fall back in web.  Mobile doesn't.. maybe open request on those repo's to fall back to polling.

But we will always need websocket or something real time to let us get events in real time.  Otherwise you have to wait until the next poll to see new messages.

We may not always push everything back and forth over the websocket.  In fact mobile now only uses for events.  But we can't really just get rid of it

**Comment by TwizzyDizzy** [comment]
That's what I thought, so I guess we gonna leave this closed. Thanks for your feedback on this.

Cheers
Thomas
