### ISSUE TITLE
Oauth identity path and username field

### ISSUE THREAD

**Issue by jy2008** [RocketChat/Rocket.Chat#9321]
My RC is the newest version. I have a custom Oauth provider written by someone else, not a mainstream one like google or facebook. It only works up to request access token part, because the link 
https://mydomain.com/oauth/token?client_id=CLIENT_ID&client_secret=CLIENT_SECRET&grant_type=authorization_code&code=AUTHORIZATION_CODE&redirect_uri=CALLBACK_URL
works, then the next step won't work, receiving access token/user info part doesn't work, it says on RC `internal server error`. I have a `getUserInfo` controller which will generate json on the provider side, but route is `put` not `get`. i put the route `api/userinfo` into RC's identity path. Is the `put` method the reason why it won't get user info? Also what is `Username field`, do i need to fill that in? fill in what info?

**Comment by geekgonecrazy** [comment]
User identity is definitely retrieved via a get. 

This seems very, very strange for a user info GET to be a PUT

**Comment by AFrangopoulos** [comment]
@geekgonecrazy What exactly does getIdentity() return for this flow?
I am using a custom OAuth provider that returns the ID i require inside the accessToken json response.  Therefore, I don't need to do a getIdentity() (for my specific provider) and just wondering what else I need to wire up so my user gets Logged in.  I can't seem to mimic the flow and there is a lack of comments in the code.  Thanks

**Comment by geekgonecrazy** [comment]
Having the info in the accessToken response is great.  But I don't believe it's looking there for it.

Implementing your own oauth server is a noble challenge.  But I'd recommend using a package or something that is set up to deliver the info on the oauth routes

**Comment by AFrangopoulos** [comment]
Right, it isn't looking for it there.  But if all it does is an /identity callback to the Auth server to get "that info" then it just saves me a request.
I was just wondering how I would Log that user in right after I receive my Access Token response.
When I get my accessToken response, I have everything I need.  In the case of someone who has "registered" already, I just need to query for the user with that "unique external id" and log that person in.  My trouble is actually logging that person in (I literally have that user from the DB in my possession at this point) and is what I need some help on.  This is mainly because I don't really know what the code does after this point (javascript is pretty unfriendly in reverse engineering flows due to its dynamic typing)

**Comment by AFrangopoulos** [comment]
@geekgonecrazy  It looks I got it to work using my own flow.  The only thing that I don't like is that after it returns from OAuth, it goes back to the login page for a quick second and then reroutes to "/".  Is this normal RC behavior?   Also, is there any clarity on what getIdentity() returns?  Right now I am querying for the user that matches my external_id.  But this involves a $loki key which i have to omit to login without error.  Not much on this $loki property other than Documentation saying "you can ignore this"

**Comment by geekgonecrazy** [comment]
Loki is our cache layer.

I'm going to suggest this would be more appropriately discussed in the forum. https://forums.rocket.chat especially since this isn't a bug. 

Going to go ahead and close.
