### ISSUE TITLE
Database migration error.

### ISSUE THREAD

**Issue by DiegooMM** [RocketChat/Rocket.Chat#9331]
Hi, I have rocketchat server version: 0.58.2, and now I installed a new server Ubuntu using the snap install, everthing work fine until I tried migrate the database.

Using mongodump and mongrestore the migrate worked, I can see the information inside mongodb with no problem, but the history doesn't appear in Rocketchat he still blank.

You guys know if I have to do some configuration for the history appears on the new server?

Thanks.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @DiegooMM

I am **temporarily** closing this issue as you have not used our [issue template](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/ISSUE_TEMPLATE.md) (the text that is already filled in automatically, when you open a new issue). Please understand, that in order to solve your issue as fast as possible, we need to understand your issue and your setup as good as possible to first reproduce it on our side and then fix it.

Therefore, we kindly ask you to adhere to the issue template and provide us with the information we need. **For that, please edit your inital post rather than replying with the issue template. We will then have a look at your feedback and re-open the issue.**

This benefits all users as we are able to understand and fix issues faster. Thank you for understanding and being kind to us and others :)

Cheers
Twizzy
