### ISSUE TITLE
Blog comments?

### ISSUE THREAD

**Issue by rawsh** [RocketChat/Rocket.Chat#9333]
It would be interesting if rocket.chat could be used as comments on a website - e.g. a channel with blog article links would have a threaded chain for each article. Does something like this exist currently, and if not, what webhooks do you suggest to create it? Simply embed the chat?

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hey @rawsh

I'm closing this as I'm pretty sure that this is not gonna come anytime soon, if at all.

Also: if you are still interested in this please head over to the feature request category: https://forums.rocket.chat/c/feature-requests

If this turns out to be a hot topic, we might reconsider this feature.

Cheers
Twizzy
