### ISSUE TITLE
X is now typing display should be debounced

### ISSUE THREAD

**Issue by SamSaffron** [RocketChat/Rocket.Chat#9337]
At the moment I notice quite a few times where people are typing and "X is typing" just flashes while they are typing, it is very distracting. 

It would be nice if there was client side debounce there so it only ever changes state maximum of 1 or 2 times a second.

**Comment by geekgonecrazy** [comment]
Some times depending on the client it does seem to flicker.  I think i've seen when the person typing is on iOS so we may want to debounce also on iOS side if we aren't already @rafaelks do you know if iOS already is?

Either way we should probably do server side.

**Comment by rafaelks** [comment]
@SamSaffron @geekgonecrazy Yes, this is happening when type on iOS, because we're calling `typing` event each time user types a character. I did open an issue about it but closed since we don't have any clarification how we should handle this type of thing client-side (if we should do or not). Here's the issue: https://github.com/RocketChat/Rocket.Chat.iOS/issues/940.

The flickers only happen on the `web client` (right?).

**Comment by geekgonecrazy** [comment]
Yeah the flicker isn't seen on iOS.  It's only seen on web client.  We should at the very least not hide and show it between every event.  If we get same event again we should just leave it showing, or increase the timeout

**Comment by SamSaffron** [comment]
Just confirming this is a web client only issue afaik.

**Comment by rafaelks** [comment]
We're going to change the logic on the iOS app in order to avoid this behaviour on the web client. Basically, after investigating, the web is doing `/typing` event every 10 seconds instead.
