### ISSUE TITLE
issues compiling #9305

### ISSUE THREAD

**Issue by MIKNOTAURO** [RocketChat/Rocket.Chat#9425]
Hey Guys,
I'm having some issues compiling rocketchat.
I had to open a new issue because a guy closed it without any solution.
I'm getting this error :
**************
postcss-custom-properties: /home/ubuntu/Rocket.Chat/packages/rocketchat-theme/client/imports/components/sidebar/sidebar-account.css:151:3: variable '--sidebar-header-small-padding' is undefined and used without a fallback
**************
My actual env :
node v8.9.3
npm v5.6.0
I've been trying different environments(node and npm), even a clean linux ubuntu xenial installation with the same issue.

parent issue #9305 

Thanks for your help ;)

**Comment by MartinSchoeler** [comment]
Hey, looks like you seem to be looking for support. You will have a better chance of getting help if you go to one of the places listed in [here](https://rocket.chat/docs/getting-support/#community-support) since github is not the best place to ask for support. For now i will be closing this issue, as it does not fit our issue guidelines
