### ISSUE TITLE
[BUG] Some emoji rendering problems in "last message UI"

### ISSUE THREAD

**Issue by cardoso** [RocketChat/Rocket.Chat#9538]
### Description:

![](https://i.imgur.com/l2GD4Fk.png)

0.61.0 (open)
macOS
Chrome Version 63.0.3239.132 (Official Build) (64-bit).

**Comment by sampaiodiego** [comment]
also, emojione emojis are stretched.

custom emojis are broken as well:
![image](https://user-images.githubusercontent.com/8591547/35525318-4ccb30cc-050b-11e8-9c8d-64e85576d4ab.png)

**Comment by meghalagrawal** [comment]
I got the issue cause, Can I work on the issue?

**Comment by sampaiodiego** [comment]
thanks @meghalagrawal for the interest on working on this issue =)

feel free to start working on any issue you may find..

but as you may have noticed this one particularly has a PR already in progress https://github.com/RocketChat/Rocket.Chat/pull/9623, so there is need for additional work :wink:

**Comment by TwizzyDizzy** [comment]
@rocket-cat open

Not sure whether this is a different (if so, let's open a new issue) or the same issue, but Emoji-Rendering in last message in the sidebar is still broken in 0.61.1 opposed to the fact it was declared fixed in the changelogs. See the attached screenshot. This happens on Chromium (64.0.3282.140) as well as Firefox (58.0.2).

![image](https://user-images.githubusercontent.com/179595/36250471-33bd8838-123e-11e8-8eda-25217b58a9bb.png)

Cheers
Thomas
