### ISSUE TITLE
New sidebar header and views

### ISSUE THREAD

**Issue by karlprieb** [RocketChat/Rocket.Chat#9541]
- [x] Header
- [x] Search
- [x] Sidebar views
	- [x] Extended view
	- [x] Medium view
	- [x] Condensed view
- [x] Sort and filters
	- [x] Alphabetical sort
	- [x] Activity sort
	- [x] Favorites filter
	- [x] Unreads filter
- [x] Tests and review

RocketChat will offer a new sidebar experience with a new header, 'extended', 'medium' and 'condensed' view and a sort/filter system.

![image](https://user-images.githubusercontent.com/9200155/35527391-be0b0522-0511-11e8-8f3b-0d5479c30f56.png)

**Comment by RichardFoxworthy** [comment]
@karlprieb  I like these designs a lot - I think they will be very useful for many RC users, 

However for my users and my usecases, all these options are too complicated. I would like to have an admin option to disable/remove any or all of these header icons, and set any underlying features to default values. 

My own usecase for Rocket.chat is to deploy a lot of simplified and customised RC instances, each with a small set of channels, to users who are not sophisticated users of software and chat interfaces.

Because we have a small set of channels, my users do not need the search, sort and discovery features to be exposed to them at all, and for the 'view' option, I'd be happy for them to simply have their view default to 'medium' and not be shown any view customisation options. Also, they will not have ability to create new channels either, so I would like the option to disable and hide all of the options shown in these header designs
