### ISSUE TITLE
Missing "more channels" link on left sidebar.

### ISSUE THREAD

**Issue by tempestb** [RocketChat/Rocket.Chat#9573]
### Description:

We're running v0.60.4 and it appears that the link on the left hand side that normally allows one to see all the available channels is missing.  So when new users join, they can only see around 5 channels (Out of 40) and cannot find the rest unless we provide them a #name in the channel.  Which is obviously tedious.  

It is up at https://community.storj.io if you want to take a look.

### Server Setup Information:

* Version of Rocket.Chat Server:  v0.60.4
* Operating System:
* Deployment Method(snap/docker/tar/etc):
* Number of Running Instances: 
* DB Replicaset Oplog:
* Node Version:

### Steps to Reproduce:

1. 
2. 
3.

**Comment by localguru** [comment]
duplicate #8571

**Comment by TwizzyDizzy** [comment]
Hi @tempestb,

we believe that the issue you reported has already been reported by somebody else. Please have a look at #8571 for further information. If you believe we closed this in error and your issue is, in fact, not the same as the one mentioned before, feel free to reopen this issue and tell us why.

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
@rocket-cat label add duplicate

**Comment by TwizzyDizzy** [comment]
@rocket-cat close
