### ISSUE TITLE
Image 403 Error

### ISSUE THREAD

**Issue by hobbsome** [RocketChat/Rocket.Chat#9589]
Hello,

I am trying to use your API to get messages from a channel. However, once I get those messages when I try and download attachments using the URL specified I get a 403 error even with the `X-User-Id` and `X-Auth-Token`.

**Comment by hobbsome** [comment]
Hi, could I get some help with this?

**Comment by MarcosSpessatto** [comment]
@hobbsome Can you provide more informations? Like what endpoint and how can we simulate this error, please?

**Comment by tandeson** [comment]
I think I'm having the same issue:

I use the REST API to get a message, which contains a URL to the message:
environment.RocketChatServer + message.attachments[0].image_url
( my server name such as 'https://rocketchat.foo.com' and the image_url, such as ''/file-upload/MzAKsqhn54sEJt5eS/20180504145314_3918475292411152406.jpg"

If I try to fetch the file using a http get, I get a 403 error. 

If I got into RocketChat's web interface in another tab - I can get get the file. It seems that it's using cookies ( rc_uid and rc_token ) to allow access. However, if I set the same tokens in my code, using the response from the user authentication ( e.g. the same ones for X-User-Id and X-Auth-Token. ), but I've logged out of the Rocketchat web interface - I can no longer get the file.

It would be nice if I could get the file by using the paramters X-User-Id and X-Auth-Token, instead of having to get a cookie setup ( assuming that is the authorization check being used).

I think we're running version 0.62 or 0.64, I'll confirm with our admin.

**Comment by hobbsome** [comment]
Thanks!

**Comment by PrajvalRaval** [comment]
@tandeson @hobbsome  Can you send me an example usage code of getting image using this headers, probably in nodejs ? We are working on RC Alexa Skill and this error has been an issue for quite a while.

**Comment by SardorbekR** [comment]
@PrajvalRaval have you found a solution? Although I am sending a request to download link with headers, I am still getting 403

**Comment by zakrush** [comment]
Hi/
