### ISSUE TITLE
Folder storage

### ISSUE THREAD

**Issue by gecusters** [RocketChat/Rocket.Chat#9598]
# Folder storage

After installing the snap package of Rocket.Chat with the sudo snap install rocketchat-server commando I checked the directory and saw it created 3 folders. /snap/core/3887, /snap/rocketchat-server1214, /snap/rocketchat-server1215. I noticed these files are using 100% of the data given (checked with Glances). Should I worry about this or is this normal behaviour?

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @gecusters

I am closing this issue as you have not used our [issue template](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/ISSUE_TEMPLATE.md) (the text that is already filled in automatically, when you open a new issue). Please understand, that in order to solve your issue as fast as possible, we need to understand your issue and your setup as good as possible to first reproduce your issue on our side and then fix it.

For that, we kindly ask you to adhere to the issue template and provide us with the information we requested. This benefits all users as we are able to understand and fix issues faster. So please, be kind to us and others :)

Cheers
Thomas
