### ISSUE TITLE
Rdio Integration

### ISSUE THREAD

**Issue by guarilha** [RocketChat/Rocket.Chat#960]
Expand rdio links like this

![Slack](https://cloud.githubusercontent.com/assets/902478/10248657/4e1694f6-68f7-11e5-8635-67d7a2368212.png)

instead of this

![screenshot from 2015-10-02 11 16 37](https://cloud.githubusercontent.com/assets/902478/10248667/5b9fa14e-68f7-11e5-8211-f1a5644acc6d.png)

**Comment by kakawait** [comment]
@engelgabriel can be closed thanks to #1241

**Comment by engelgabriel** [comment]
Tried http://rd.io/x/wYYhizEt5kk/ and didnt work :(

**Comment by engelgabriel** [comment]
What am I missing @kakawait and @rodrigok  ?

**Comment by kakawait** [comment]
@engelgabriel do you have any error on log? Does other oembed medias work? Like YouTube or Soundcloud ?

**Comment by kakawait** [comment]
@engelgabriel problem comes from rdio itself. Because when requesting API

http://www.rdio.com/api/oembed/?format=json&url=http%3A//rd.io/x/wYYhizEt5kk

returns `404 Not found`

Whereas other try works

http://www.rdio.com/api/oembed/?format=json&url=http%3A//rd.io/x/Q1IjXC8s

screen from (https://demo.rocket.chat)

![screen shot 2015-11-12 at 19 12 54](https://cloud.githubusercontent.com/assets/275609/11126876/6eecd740-8971-11e5-9bd8-e395521d1e64.png)

**Comment by engelgabriel** [comment]
Hehehe... they don't like me :(
