### ISSUE TITLE
Message Bubbles

### ISSUE THREAD

**Issue by HammyHavoc** [RocketChat/Rocket.Chat#9681]
Tempting people to migrate away from Skype currently, but chat bubbles for ease of reading is something that's missing from Rocket.Chat; any interest in bringing this to the UX as an option? People are very familiar with it from Facebook Messenger and iMessage too.

**Comment by HammyHavoc** [comment]
@madguy02 Skype uses message bubbles too, it's fairly standard for readability, though some people prefer the Slack/Discord style that Rocket.Chat currently uses, which is why I think offering the choice would be really important for aiding adoption from current Skype and Skype for Business users. :- ) UX options are an important aspect of increasing market share.

**Comment by jszaszvari** [comment]
Message Bubbles are so early 2000s. 

You could probably do this with some custom CSS . 

Slack has done lots of usability studies around how to represent the Messaging interface and every time they have come back saying that 'bubbles' make the product feel 'childlike' or 'immature' 

Just my personal opinion though.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @HammyHavoc 

First off: thank you for takting interest in Rocket.Chat and its improvement. Unfortunately though,I am closing this issue because this is a feature request. The usual procedure for feature requests is as follows:

* feature request is incoming via [the feature requests category in the forums](https://forums.rocket.chat/c/feature-requests)
* feature request is pre-approved by Rocket.Chat team member
* feature request is discussed and refined until it is utterly clear what is to be implemented and what is to be achieved by the feature request. Technical details might be part of this discussion
* feature is approved by Rocket.Chat team member (**or not** - then it will not be done - yet might still be done as a Rocket.Chat App by the community)
* feature request is transferred to github and labelled with "Feature: Planned"

Please understand, that we do not want to clutter Github with wishes and ideas as we have decided to use the forums for that.

When you compose a feature request in the forums, please ask yourself the following questions:

* is my feature request something that benefits everybody or at least a great amount of people
* is my feature request something that is technically possible (only if you have the expertise)
* [... maybe more?...]

Cheers
Thomas

**Comment by pixobit** [comment]
I don't understand how can the bubbles feature be ignored, I think it makes it much more readable

**Comment by DezyNation** [comment]
5 years and still no progress on this feature??
