### ISSUE TITLE
how to disable Rocket.Chat server autoupdate

### ISSUE THREAD

**Issue by svartedauen** [RocketChat/Rocket.Chat#9691]
We use Rocket.Chat **0.61.0** in our company (**Linux x64 OS version 4.4.0-112-generic**) and constantly get automatic updates on the server that break customers.

It happens that the push notices will break, it happens that the user sees a white screen. This happens after the server spontaneously updates the software.

Is it possible to somehow temporarily **disable automatic updates** on the server or put it on the schedule?

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @svartedauen

I am closing this issue because we think there is no actual bug in Rocket.Chat. Here's why:

There can be multiple reasons for automatic updates happening, here are some of them:
* you deployed via snap
* you have ubuntu automatic updates enabled
* unknown other stuff.

In any case, Rocket.Chat itself has no auto-update feature and is not responsible for your automatic updates.

We use Github mainly for discussing bugs though. We understand, that setting up and operating a Rocket.Chat server is not trivial, yet we do not have the woman/man-power to help everybody. That is unfortunate, but simply a limitation of time. If it should turn out from your feedback to this message, that there is a bug involved, we will try to fix it with you.

That being said, we are very thankful that our community also does a great job in helping each other. I would therefore like to point you to some places where you can try asking for help. Usually, some friendly human being has time for you and your issue:

* **The Rocket.Chat Community Support Channel**: https://open.rocket.chat/channel/support
* **The Rocket.Chat Community Support Forum**: https://forums.rocket.chat/c/community-support

If you don't find a solution to your problem there, don't fret, as we also offer paid support: https://rocket.chat/support

You could, of course, spare yourself the hassle entirely and just choose the hosted version, where we provide you with a running Rocket.Chat instance: https://rocket.chat/cloud

Cheers
Thomas
