### ISSUE TITLE
Setting Direct Messages Only

### ISSUE THREAD

**Issue by c0fe** [RocketChat/Rocket.Chat#9700]
Does Rocket.Chat have capabilities to support direct messaging only? Like Skype, AIM (used to) and other applications?

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @c0fe 

I am closing this issue because we think there is no actual bug in Rocket.Chat in what you're describing. Here's why:

* you are asking a normal support question
* anyway: the answer to your question is: there is currently no way to run Rocket.Chat in direct-messaging-only mode. And I doubt it's planned by the developers as Rocket.Chat is intended as a chat platform, not a messenger.

We use Github mainly for discussing bugs though. We understand, that setting up and operating a Rocket.Chat server is not trivial, yet we do not have the woman/man-power to help everybody. That is unfortunate, but simply a limitation of time. If it should turn out from your feedback to this message, that there is a bug involved, we will try to fix it with you.

That being said, we are very thankful that our community also does a great job in helping each other. I would therefore like to point you to some places where you can try asking for help. Usually, some friendly human being has time for you and your issue:

* **The Rocket.Chat Community Support Channel**: https://open.rocket.chat/channel/support
* **The Rocket.Chat Community Support Forum**: https://forums.rocket.chat/c/community-support

If you don't find a solution to your problem there, don't fret, as we also offer paid support: https://rocket.chat/support

You could, of course, spare yourself the hassle entirely and just choose the hosted version, where we provide you with a running Rocket.Chat instance: https://rocket.chat/cloud

Cheers
Thomas
