### ISSUE TITLE
Users are not allowed to use capital letters in room name specification

### ISSUE THREAD

**Issue by Cymassius** [RocketChat/Rocket.Chat#9703]
### Description:

Adding new rooms is quite simple, but if i want to have a room name with capital letters inside, thats not possible. But thats not a feature, because as admin i can edit room preferences and there i can use capital letters. Why not as user?

### Server Setup Information:

* Version of Rocket.Chat Server: 0b71e0e2fe47280d862db18f89575cf15da9c6b1 / 0.61.0
* Operating System: Linux x64 / Ubuntu
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1
* DB Replicaset Oplog:
* Node Version: v8.9.3

### Steps to Reproduce:

1. Create new channel/room - "my_room"
2. Try to choose capital letters in room name specification -> not allowed
3. Login as admin
4. Go to rooms/channels
5. Edit the channel/room
6. Try to change room name in to "My_Room"
7. Does work perfectly

### Expected behavior:

Both variants (user and admins) should allow capital letters for room names. 

### Actual behavior:

Only admins can specifiy room names with capital letters

### Relevant logs:
no relevant logs

**Comment by TwizzyDizzy** [comment]
@rocket-cat label add duplicate

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @Cymassius

we believe that the issue you reported has already been reported by somebody else. Please have a look at #4029 for further information. If you believe we closed your issue in error and your issue is, in fact, not the same as the one mentioned before, feel free to get back to us here and tell us why.

Cheers
Thomas
