### ISSUE TITLE
Why Sometime login with rocket.cat user

### ISSUE THREAD

**Issue by anujku123** [RocketChat/Rocket.Chat#9723]
I am login using iframe . All thing going fine. But some time when user login , but in iframe shown me login as @rocket.cat user . Please help me what is issue that . Is there any configuration for that or what is problem. If i clear browser history it working fine . Please me what happen iframe  shown me login as @rocket.cat user .

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @anujku123 

I am temporarily closing this issue as you have not used our [issue template](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/ISSUE_TEMPLATE.md) (the text that is already filled in automatically, when you open a new issue). Please understand, that in order to solve your issue as fast as possible, we need to understand your issue and your setup as good as possible to first reproduce it on our side and then fix it.

Therefore, we kindly ask you to adhere to the issue template and provide us with the information we need. For that, please edit your inital post rather than replying with the issue template. We will then have a look at your feedback and re-open the issue.

This benefits all users as we are able to understand and fix issues faster. Thank you for understanding and being kind to us and others :)

Cheers
Thomas
