### ISSUE TITLE
[Bug] Emojis look weird in channel list

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat#9724]
### Description:

Since 0.61, the last message of a channel is displayed in the channel list (if property `Store_Last_Message = true`). But if the last message is a (custom) emoji, this looks a bit weird.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61

### Steps to Reproduce:

1. Enable `Store_Last_Message`
2. Post a (custom) emoji in a channel

### Expected behavior:

Emoji is displayed correctly in channel list.

### Actual behavior:

Regular emoji:

![rocket_chat_](https://user-images.githubusercontent.com/3596824/36252352-a785ac68-1244-11e8-8339-af7103229285.png)

Custom emoji (minion):

![sidebar-emoji](https://user-images.githubusercontent.com/3596824/36252274-4a506c72-1244-11e8-8449-229d96640c76.png)

**Comment by TwizzyDizzy** [comment]
@rocket-cat label add duplicate

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @janrudolph 

we believe that the issue you reported has already been reported by somebody else. Please have a look at #9623 for further information. If you believe we closed your issue in error and your issue is, in fact, not the same as the one mentioned before, feel free to get back to us here and tell us why.

Cheers
Thomas
