### ISSUE TITLE
[Feature Request] LDAP sync should disable old users.

### ISSUE THREAD

**Issue by monspid** [RocketChat/Rocket.Chat#9727]
It would be nice if LDAP sync `disabled` all the users which do not fit to LDAP filter. It means if we fire employee we delete him from the LDAP group. It would be nice if the user turns to `disabled`.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @monspid 

we believe that the issue you reported has already been reported by somebody else. Please have a look at #7235 for further information. If you believe we closed your issue in error and your issue is, in fact, not the same as the one mentioned before, feel free to get back to us here and tell us why.

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
@rocket-cat label add duplicate

**Comment by monspid** [comment]
Yup, that's it ;-)
