### ISSUE TITLE
Sync with Active Directory

### ISSUE THREAD

**Issue by leonardosoares** [RocketChat/Rocket.Chat#9730]
Such as synchronizing with the active directory in a way that only imports users and leaves the groups out. I have many groups organized hierarchically, and I do not want them to appear on Rocket.Chat

Example:

**master_group**
   _group_01_
       user_01
       user_02
   _group_02_
       user_01
       user_02
   _group_03_
       user_01
       user_02

I need only the users, all of them belong to master_group. But when I synchronize, Rocket.Chat imports the groups as if they were simple users.

I hope I have been clear, I count on the help of all.
Thank you!

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @leonardosoares 

I am closing this issue because we think there is no actual bug in Rocket.Chat in what you're describing. Here's why:

* this is a LDAP support question rather than an actual bug - please use the forums or the chat (see below) for that :)

We use Github mainly for discussing bugs though. We understand, that setting up and operating a Rocket.Chat server is not trivial, yet we do not have the woman/man-power to help everybody. That is unfortunate, but simply a limitation of time. If it should turn out from your feedback to this message, that there is a bug involved, we will try to fix it with you.

That being said, we are very thankful that our community also does a great job in helping each other. I would therefore like to point you to some places where you can try asking for help. Usually, some friendly human being has time for you and your issue:

* **The Rocket.Chat Community Support Channel**: https://open.rocket.chat/channel/support
* **The Rocket.Chat Community Support Forum**: https://forums.rocket.chat/c/community-support

If you don't find a solution to your problem there, don't fret, as we also offer paid support: https://rocket.chat/support

You could, of course, spare yourself the hassle entirely and just choose the hosted version, where we provide you with a running Rocket.Chat instance: https://rocket.chat/cloud

Cheers
Thomas
