### ISSUE TITLE
Cannot Close "File exceeds.." Pop-up

### ISSUE THREAD

**Issue by afroDC** [RocketChat/Rocket.Chat#9731]
### Description:

Cannot close `File exceeds allowed size of x MB. [error-file-too-large]` pop-up with the CLOSE button. Pop-up remains

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0
* Operating System: Linux/Ubuntu 16
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* Node Version: 8.8.1

### Steps to Reproduce:

1. Upload file size larger than allowed parameters in Rocket Chat
2.  Try to close pop-up warning.

### Expected behavior:

Clicking close and the pop-up disappearing.

### Actual behavior:

Pop-up stays until you close Rocket chat

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @afroDC 

we believe that the issue you reported has already been reported by somebody else. Please have a look at #9387 for further information. If you believe we closed your issue in error and your issue is, in fact, not the same as the one mentioned before, feel free to get back to us here and tell us why.

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
@rocket-cat label add duplicate
