### ISSUE TITLE
Email admin when new user registers and registration requires admin approval

### ISSUE THREAD

**Issue by mhkeller** [RocketChat/Rocket.Chat#976]
If this is already a feature let me know and I will see if I misconfigured my smtp settings but it would be useful if when a new user registers and the admin has selected the option requiring approval, then the admin gets an email notifying them of such.
##

**Comment by designgurudotorg** [comment]
Is anyone working on this issue?

**Comment by drasbeck** [comment]
I second that question. This issue _does_ seem important for admins.

**Comment by geekgonecrazy** [comment]
What type of alert would you guys expect?  Just an email saying there is a new user needing approved?

**Comment by AdrianoCahete** [comment]
> Just an email saying there is a new user needing approved?

I'm not actively using RC neither know if is a workaround to do this, but this is exactly what I wanted.

**Comment by janrudolph** [comment]
Especially in a corporate world, this feature will find many lovers. Our team admins complain about the missing notification. 

I have suggested another concept some weeks ago. Instead of using email, admin notifications could be sent in a special admin channel: https://github.com/assistify/Rocket.Chat/issues/95 Thereby the admin would have a kind of dashboard. However, I haven't implemented it so far.
