### ISSUE TITLE
[BUG] I can auth without a loginToken

### ISSUE THREAD

**Issue by guilhermecfviana** [RocketChat/Rocket.Chat#9791]
### Description:

I can auth without a loginToken.

Example: 

postMessage({
            event: 'login-with-token',
            loginToken: ''
          },'*');

Before:
![01](https://user-images.githubusercontent.com/17053653/36441028-1fc00d2c-1650-11e8-804a-3ed3e7e2ef53.jpg)

After:
![02](https://user-images.githubusercontent.com/17053653/36441045-2f7750c2-1650-11e8-9af3-7c7e3a256997.jpg)

The login is done successfully in a random user, but I was expecting an error by passing the empty loginToken

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0
* Operating System: Linux 4.4.0-1049-aws
* Deployment Method(snap/docker/tar/etc): Snap
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* Node Version: v8.8.1

**Comment by TwizzyDizzy** [comment]
It may be my missing JS knowledge, but I cannot reproduce your issue. Could you elaborate in a step-by-step manner? :)

Cheers & Thanks
Thomas

**Comment by vitorblz** [comment]
@TwizzyDizzy The configured authentication method must be Iframe

**Comment by 0markill** [comment]
Seems to be a few faulty checks in the iframe login package.
in iframe_client.js the 'callLoginMethod' is left unchecked and gets called whether 'tokenData.token' value exists or not.
iframe_server.js only checks if 'result.iframe' exists but not if 'result.token' does which makes it always pass if iframe login is enabled, and since the findOne query in mongo has optional parameters i guess it just returns a user regardless.

**Comment by nimetu** [comment]
I believe that adding `check(result.token, String);` to iframe_server.js will fix this one and also #9530

https://github.com/RocketChat/Rocket.Chat/blob/da6c2c0489e7916c22bfccc956b908c88ebaff86/packages/rocketchat-iframe-login/iframe_server.js#L3
