### ISSUE TITLE
Reactions broken when using  Mobile browsers and Cordova App 

### ISSUE THREAD

**Issue by lunitic** [RocketChat/Rocket.Chat#9800]
### Description:
When using the cordova app it is not possible to do reactions on a message, this bug was introduced around 0.59 maybe earlier. Easiest way to replicate it is to download the cordova app and try do a reaction on https://open.rocket.chat. Have tested against 0.59 - 0.61.1

Its seems like the event is not pushed to the server . The emoji selector pops up but nothing happens when you click on an emoji.

### Server Setup Information: 
Ubuntu 
### Version of Rocket.Chat Server: 
Tested servers 0.59.6, 0.60.3 61.1 and https://open.rocket.chat
### Operating System: 
XUbuntu 16.04 LTS
### Deployment Method(snap/docker/tar/etc): 
build from source
### Number of Running Instances: 
1
### Node Version:  
8.9.4
### Steps to Reproduce: 
Surf to https://open.rocket.chat with either  chrome or safari on your smartphone hold finger on a message and try to add a reaction. 
### Expected behavior:
An emoji should be added to the message 
### Actual behavior:
Nothing happens

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hey @lunitic 

then I'd suggest you open this issue in the Cordova App Repo :)
https://github.com/RocketChat/Rocket.Chat.Cordova

If you think this is actually a server bug, then this repo would have been correct. In that case, just get back to me and I will reopen.

Cheers
Thomas

**Comment by lunitic** [comment]
@TwizzyDizzy Its not in the client since this is a Server side issue.

**Comment by TwizzyDizzy** [comment]
> Its not in the client since this is a Server side issue. Same client work flawless towards earlier version of the server.

My first question would be: why is it the server? To be fair though, the evidence you brought forward doesn't really make it possible to tell with certainty, that it's definately one of them but since it's "somehow app related" I'd say it's a bit better to have in the app repo. Also to prevent duplicates there :)

Thanks for opening the issue there!

Cheers
Thomas

**Comment by lunitic** [comment]
To rule out the cordova m, I just tested using reaction with the regular web browser both on Android and IOS. Both failes with the reaction. None of them sends away the event.

**Comment by TwizzyDizzy** [comment]
@rocket-cat open

Alright, then I agree with you, that it's probably a server issue. I will reopen this issue. Please add the information requested in the [issue template](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/ISSUE_TEMPLATE.md) (in your initial post) and rename the so that it reflects that it's not about the app.

Thank you
Thomas

**Comment by lunitic** [comment]
@TwizzyDizzy done
