### ISSUE TITLE
Livechat translation review

### ISSUE THREAD

**Issue by theorenck** [RocketChat/Rocket.Chat#9848]
### Description:
- [x] Review the translation (mainly for the widget)
- [x] Ensure that the browser's default language will automatically used
- [x] Review the translation of Livechat admin
- [x] Review the translation of Livechat settings

**Comment by renatobecker** [comment]
I added 2 more items related to translation, because I found several keys used without translation to Portuguese. So, because of this, I spent more time translating these keys and checking for other missing translations.
I made some tests like changing the language of the browser and the language of the OS and I checked if the translation was correct.
Now the translation of widget, administrative and livechat settings are reviewed for both English and Portuguese.
