### ISSUE TITLE
Add the navigation history into the messages box

### ISSUE THREAD

**Issue by theorenck** [RocketChat/Rocket.Chat#9853]
### Description
Add the navigation history into the messages box (to give more context for the attendee)
- [x] migrate navigation history to messages collection
- [x] send it as a message to the attendee as rocketcat
- [x] create a setting to manage it (enabled by default)

**Comment by renatobecker** [comment]
Hi @theorenck and @sampaiodiego !

I started this issue today and I've talked to @theorenck about this because I had some doubts.
The main point is how the message will be displayed to the agents, for example, we'll display the page title and page link of the visitor's page or simply send a message with the link to Rocket.Chat and the message will appear the same way the links are displayed, containing the "banner" of the link that was just sent. 
Another point is that sending notifications to agents as a notification the message will not be stored, so if it is important to have this informations in the future, it will be necessary to create a specific message type to avoid that these messages appears on the visitor's side.

**Comment by sampaiodiego** [comment]
the first idea was to use a regular message with history URL included on its body, even if sent by `rocket.cat` it could be stored on DB.. but as you described, I think the main problem would be how to avoid showing them to visitor.

based on that I would suggest then to create a new message type (e.g.: `livechat-history`) and show the message like a system message.
