### ISSUE TITLE
Password reset URL is wrong

### ISSUE THREAD

**Issue by a11anarete** [RocketChat/Rocket.Chat#9863]
### Description:

Password reset URL is going to the login page.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0
* Operating System: CentOS 7
* Deployment Method(snap/docker/tar/etc): RPM
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* Node Version: v8.9.3
* mongoDB Version: 2.6.12

### Steps to Reproduce:

1. When a user clicks on re-set password.
2. User gets the email and a link to re-set their password.
3. User then clicks on the re-set password link.
4. User is directed back to the login page.

### Expected behavior:

The link shows the reset password page

### Actual behavior:

The link goes to the login page

### Other information -- the email example below:

Hello,

To reset your password, simply click the link below.

`https://[hostDNS]/#/reset-password/[SHA256 hash]`

Thanks.

#### * I found that removing the # hash, the link goes to the correct URL.

`https://[hostDNS]/reset-password/[SHA256 hash]`

#### * Where can I change this setting?

Thank you in advance.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @a11anarete 

we believe that the issue you reported has already been reported by somebody else. Please have a look at #3883 for further information. If you believe we closed your issue in error and your issue is, in fact, not the same as the one mentioned before, feel free to get back to us here and tell us why.

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
@rocket-cat label add duplicate

**Comment by a11anarete** [comment]
Hi @TwizzyDizzy thank you for your reply.  

This is different, as I explained on my message #3883 is a separate issue.
So I would like to keep this open unless you know where this URL is set?

Cheers.

**Comment by TwizzyDizzy** [comment]
Please do correct me, if I am wrong, but I still believe what you're describing is the result of #3883.

The URL in the `text/plain` part of the mail is generated incorrectly (containing the hash sign where it should not be: `/#/reset-password/`) which leads to getting redirected to the login page.

If you don't agree, please show me where exactly your issue is different.

Cheers
Thomas

**Comment by a11anarete** [comment]
Hi, apologies it is the same result.

Do you know where this code is specified?

Cheers.

**Comment by TwizzyDizzy** [comment]
Unfortunately, I don't, as I'm no dev. Sorry.

Cheers
Thomas

**Comment by a11anarete** [comment]
ok no worries. thanks again.

**Comment by a11anarete** [comment]
Just for information, I was looking at the `app.js` which had this line and thought this was the problem.  I removed the `#/` and restarted the service but still the same error.

...
				Accounts.emailTemplates.resetPassword.html = function (userModel, url) {
					url = url.replace('/#/', '/');
					return html.replace(/\[Forgot_Password_Url]/g, url);
				};
...

**Comment by TwizzyDizzy** [comment]
Hi there,

please, whatever you find, add it in #3883 now :)

Cheers & Thanks
Thomas

**Comment by a11anarete** [comment]
Ah of course, this is close :)
