### ISSUE TITLE
[FEATURE REQUEST] Warn users when using @all and @here how many people they will notify 

### ISSUE THREAD

**Issue by robbyoconnor** [RocketChat/Rocket.Chat#9867]
### Description:

Users should be warned when they use `@all` and `@here` -- similar to how Slack does it. It's a pet peeve of mine when people use `@all` and `@here`.

**Comment by JSzaszvari** [comment]
@rocket-cat label add enhancement

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @robbyoconnor 

we believe that the issue you reported has already been reported by somebody else. Please have a look at #5157 for further information. If you believe we closed your issue in error and your issue is, in fact, not the same as the one mentioned before, feel free to get back to us here and tell us why.

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
@rocket-cat label remove enhancement

**Comment by TwizzyDizzy** [comment]
@rocket-cat label add duplicate
