### ISSUE TITLE
TLS/SSL connection between Rocket.Chat and MongoDB

### ISSUE THREAD

**Issue by Csiffy** [RocketChat/Rocket.Chat#9893]
### Description:

I did not find solution TLS/SSL connection between the rocket.chat and MongoDB.
MongoDB working with SSL, but how can I create SSL connection with the rocket.chat?

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0
* Operating System: CentOS
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: min. 2
* DB Replicaset Oplog: -
* Node Version: 8.9.4
* mongoDB Version: 3.6.2

### Steps to Reproduce:

-

### Expected behavior:

The connection should be encrypted between the Rocket.Chat and MongoDB

### Actual behavior:

We have to use with username/password

Thank you very much.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @Csiffy 

I am closing this issue because we think there is no actual bug in Rocket.Chat in what you're describing. Here's why:

* this is nothing Rocket.Chat is responsible for. You have to adjust your `MONGO_URL` to achieve TLS encryption between RC and MongoDB. Here's an example: `MONGO_URL=mongodb://user:pass@mongodb.host:27017/rocketchat_database?ssl=true`

We use Github mainly for discussing bugs though. We understand, that setting up and operating a Rocket.Chat server is not trivial, yet we do not have the woman/man-power to help everybody. That is unfortunate, but simply a limitation of time. If it should turn out from your feedback to this message, that there is a bug involved, we will try to fix it with you.

That being said, we are very thankful that our community also does a great job in helping each other. I would therefore like to point you to some places where you can try asking for help. Usually, some friendly human being has time for you and your issue:

* **The Rocket.Chat Community Support Channel**: https://open.rocket.chat/channel/support
* **The Rocket.Chat Community Support Forum**: https://forums.rocket.chat/c/community-support

If you don't find a solution to your problem there, don't fret, as we also offer paid support: https://rocket.chat/support

You could, of course, spare yourself the hassle entirely and just choose the hosted version, where we provide you with a running Rocket.Chat instance: https://rocket.chat/cloud

[GENERIC ROCKET.CHAT SALUTATION]
[USERNAME OF THE ONE WHO TRIGGERED THE BOT]
