### ISSUE TITLE
[QUESTION] Api endpoint for forgot password

### ISSUE THREAD

**Issue by aniketsingh03** [RocketChat/Rocket.Chat#9896]
I wanted to know the api endpoint to use for getting instructions through email to reset the password in case a user forgets his password. I searched the api docs but was unable to find any relevant information.
Can someone help me with this?

**Comment by TwizzyDizzy** [comment]
Hi @aniketsingh03 

I am closing this issue because we think there is no actual bug in Rocket.Chat in what you're describing. Here's why:

* please consult the community support forum (see below)

We use Github mainly for discussing bugs though. We understand, that setting up and operating a Rocket.Chat server is not trivial, yet we do not have the woman/man-power to help everybody. That is unfortunate, but simply a limitation of time. If it should turn out from your feedback to this message, that there is a bug involved, we will try to fix it with you.

That being said, we are very thankful that our community also does a great job in helping each other. I would therefore like to point you to some places where you can try asking for help. Usually, some friendly human being has time for you and your issue:

* **The Rocket.Chat Community Support Channel**: https://open.rocket.chat/channel/support
* **The Rocket.Chat Community Support Forum**: https://forums.rocket.chat/c/community-support

If you don't find a solution to your problem there, don't fret, as we also offer paid support: https://rocket.chat/support

You could, of course, spare yourself the hassle entirely and just choose the hosted version, where we provide you with a running Rocket.Chat instance: https://rocket.chat/cloud

Cheers
Thomas

**Comment by aniketsingh03** [comment]
Fine, thanks @TwizzyDizzy . I was just working on the android app and was looking for the endpoint. I'll switch over to support section :smile:
