### ISSUE TITLE
Create admin-settings for the new view settings in the sidebar

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#9941]
### Description:

I couldnt find any admin setting where I can set a default for the new view options on the sidebar.

![image](https://user-images.githubusercontent.com/5877910/36786981-b341707a-1c88-11e8-9690-59054c5d79d9.png)

This view settings should have an admin setting to set this view in a default state for all users which not adjusted this setting yet (or for new users).

https://github.com/RocketChat/Rocket.Chat/pull/9608 
@johnyb0y mentioned this already in the pull request.

### Server Setup Information:

* Version of Rocket.Chat Server:  0.62.0
* Operating System: Ubuntu Server 16.04 LTS
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1

**Comment by johnyb0y** [comment]
Thanks for creating the issue. We will skip 0.62.0 because the rather huge change in UX would throw off many of my users.

**Comment by karlprieb** [comment]
@johnyb0y When we fix that and add an default view mode on admin you'll be able to hide the button on sidebar using custom css or maybe we can add an option on admin to decide which buttons will be visible for users.

**Comment by johnyb0y** [comment]
Thanks for your response and work. I dont' want to miss the added buttons and new functionality, they are great!

What i need to prevent is a sudden change in UI, because that would break the usage of Rocketchat in my company instantly :/ 

what would be very convenient for admins with non-tech-savvy users like me:
A way to define a **default view** which is enabled by default, but can still be changed if users want to. 
For example: `Show Favorites ON, Sort by Activity ON, Summarize Rooms OFF`

After that, users can still change the look to their liking using the new buttons. 

RocketChat.Electron uses a similiar way for a rollout of default settings to users.
You can define certain things in Rocket.Chat's admin interface and push it to all Rocketchat.Electron Clients, **as default value** (for example duration of notification visibility), but users can still change it to their own liking.
Something like this for the sidebar would be great! Thanks!

**Comment by karlprieb** [comment]
@johnyb0y I get it, you can set the sort/filter settings on admin already and we'll add an option to set the sidebar view mode default on admin, ok?

**Comment by johnyb0y** [comment]
Sounds great 👍

**Comment by TheReal1604** [comment]
@karlprieb thanks!
