### ISSUE TITLE
Multiple SlackBridge

### ISSUE THREAD

**Issue by rajsardhara** [RocketChat/Rocket.Chat#9948]
Hello,

Is there a way I can integrate with multiple Slack same time?, We've few clients using Slack And I want to integrate with all of them but with current setup it allows only one, Can I use WebHook instead? Anyone got working script?

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @rajsardhara 

I am closing this issue because we think there is no actual bug in Rocket.Chat in what you're describing.

We use Github mainly for discussing bugs though. We understand, that setting up and operating a Rocket.Chat server is not trivial, yet we do not have the woman/man-power to help everybody. That is unfortunate, but simply a limitation of time. If it should turn out from your feedback to this message, that there is a bug involved, we will try to fix it with you.

That being said, we are very thankful that our community also does a great job in helping each other. I would therefore like to point you to some places where you can try asking for help. Usually, some friendly human being has time for you and your issue:

* **The Rocket.Chat Community Support Channel**:
https://open.rocket.chat/channel/support (for general support)
* **The Rocket.Chat Community Dev Channel**:
https://open.rocket.chat/channel/dev (for development-focussed support)
* **The Rocket.Chat Community Support Forum**:
https://forums.rocket.chat/c/community-support

If you don't find a solution to your problem there, don't fret, as we also offer paid support: https://rocket.chat/support

You could, of course, spare yourself the hassle entirely and just choose the hosted version, where we provide you with a running Rocket.Chat instance: https://rocket.chat/cloud

Cheers
Thomas
