### ISSUE TITLE
LDAP wont automatically login users

### ISSUE THREAD

**Issue by Abraka** [RocketChat/Rocket.Chat#9980]
Version of Rocket.Chat Server: 0.61

Hello, I have problem with LDAP login. My users login into rocket chat with a same username/password as they have for login to their computers. But they must type username/password every time, when they open rocket chat site in their browser. How to setup rocket chat, so that they will get logged in automatically, when they open rocket chat site? Thx.

**Comment by OtavioCapila** [comment]
Look for `Login Expiration in Days` inside Administration > Accounts.
![image](https://user-images.githubusercontent.com/29285724/36909197-2685ac92-1e1c-11e8-99dc-0dd133099b7a.png)

**Comment by OtavioCapila** [comment]
Are you using Nginx?Here we had the same problem when using Docker+Nginx.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @Abraka 

as @OtavioCapila said: you can try raising the Login Expiration. As for what I think I'm reading between the lines: please keep in mind, that **LDAP is no Single-Sign-On** mechanism. It's for authentication only.

Therefore I'm closing this issue, as I think no bug is involved. If you think otherwise, please say why and remember the adhere to the [issue template](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/ISSUE_TEMPLATE.md).

Cheers
Thomas

**Comment by Abraka** [comment]
So, how can I make LDAP working with Single-Sign-On mechanism for my rocket chat users?

**Comment by kaiiiiiiiii** [comment]
That's something you should bring up in the rocket.chat forum, not as an issue on github.

https://forums.rocket.chat/
