### ISSUE TITLE
docker-compose access to mongodb server from another local computer

### ISSUE THREAD

**Issue by Xarkam** [RocketChat/Rocket.Chat#9994]
Hello,

how to access the mongodb server from another station ?

I wish I could do the administration of my base rocket.chat but I can not connect to the instance mongodb with robo3t.

A `docker-compose ps` does not show that mongodb is bind on 0.0.0.0

Thank you.

**Comment by TwizzyDizzy** [comment]
@rocket-cat close

Hi @Xarkam 

I am closing this issue because we think there is no actual bug in Rocket.Chat in what you're describing.

We use Github mainly for discussing bugs though. We understand, that setting up and operating a Rocket.Chat server is not trivial, yet we do not have the woman/man-power to help everybody. That is unfortunate, but simply a limitation of time. If it should turn out from your feedback to this message, that there is a bug involved, we will try to fix it with you.

That being said, we are very thankful that our community also does a great job in helping each other. I would therefore like to point you to some places where you can try asking for help. Usually, some friendly human being has time for you and your issue:

* **The Rocket.Chat Community Support Channel**:
https://open.rocket.chat/channel/support (for general support)
* **The Rocket.Chat Community Dev Channel**:
https://open.rocket.chat/channel/dev (for development-focussed support)
* **The Rocket.Chat Community Support Forum**:
https://forums.rocket.chat/c/community-support

If you don't find a solution to your problem there, don't fret, as we also offer paid support: https://rocket.chat/support

You could, of course, spare yourself the hassle entirely and just choose the hosted version, where we provide you with a running Rocket.Chat instance: https://rocket.chat/cloud

Cheers
Thomas

**Comment by Xarkam** [comment]
Hello,
Yes it is not a bug. It is a legislative problem. The laws in my country say that I must be able to provide direct access to the database if asked.

I will go on the community chat to ask my questions.

Thank you.
